### ISSUE TITLE
When duplicating smart blocks AND criteria are merged into OR

### ISSUE THREAD

**Issue by kmahelona** [LibreTime/libretime#1006]
**Describe the bug**
If you have multiple criteria such as "Genre contains Pop" and "Genre does not contain Rock" in a smart black, and then you duplicate the smart block, you get a new smart block with "Genre contains Pop OR Genre does not contain Rock"

**To Reproduce**
1. Create a smart block with multiple criteria of the same "selector" e.g. Genre, Label, etc.
2. Save the smart block
3. Duplicate the smart block
4. Edit the new smart block and you'll see the AND turns into an OR

**Expected behavior**
AND criteria should be preserved rather than merged to become OR. Alternatively... you could make the option to choose and AND or and OR for multiple criteria of the same "selector" but this would require more work.

**LibreTime version:**
Latest master

**Installation method:**
 - OS: Debian
 - OS Version 10
 - Method: ./install

**Screenshots**
![Screen Shot 2020-04-23 at 8 16 22 PM](https://user-images.githubusercontent.com/5294466/80076049-b0c1b300-859f-11ea-9b1e-7dc3b15cde5f.png)
![Screen Shot 2020-04-23 at 8 16 48 PM](https://user-images.githubusercontent.com/5294466/80076052-b28b7680-859f-11ea-89af-33d48cc1e226.png)

**Comment by Robbt** [comment]
I suspect the issue is in the jQuery that processes the smart block from the database. It is messy and needs a lot of work. Look at #732 for an example.

Meaning I suspect the issue doesn't manifest until you edit the duplicate smartblock. 

But this is a good example that we can use as a test to try and debug the jQuery code.
