### ISSUE TITLE
LibreTime not installable with Python 2.7 due to setuptools 45 not supporting 2.7

### ISSUE THREAD

**Issue by Robbt** [LibreTime/libretime#1010]
**Describe the bug**
Tried to install Ubuntu Xenial via vagrant and the install failed because Setuptools no longer supports Python 2.7

**To Reproduce**
Run install via `vagrant up ubuntu-xenial`

**Expected behavior**
It should work until we switch to python 3 in #951

I think that changing https://github.com/LibreTime/libretime/blob/e584f859feb98412f9bff3e9b588e7079d987bb7/install#L927
to have <45 after setuptools will fix it.

It did for me. This will be solved by switching to Python 3 but if that is delayed it might make sense to add another hot fix.

**Comment by paddatrapper** [comment]
I hope to fix the Liquidsoap issue tomorrow and then it should be merge-able (hopefully)

**Comment by Robbt** [comment]
Cool we can close this one with #951.

**Comment by paddatrapper** [comment]
Fixed with the port to Python 3
