### ISSUE TITLE
continuation playlist (not sure what to call it)

### ISSUE THREAD

**Issue by Aphris-Karu** [LibreTime/libretime#1016]
I need a playlist/smartblock that can be scheduled in such a way that each show continues where the last left off.

For example:
I have a radio play (something like Orson Welles war of the worlds) that is 3 hours long and broken into 5 min segments. Each MP3 is listed as "part #.mp3" starting at 1 and going up to 36.
I want to schedule it in 1 hr segments every Saturday for the next 3 weeks.
So Episode 1 would be 1-12, Episode 2 would be 12-24, and Episode 3 would be 24-36 (or something like that. In this case I like to repeat the last episode of the previous week as a reminder but that is not necessary. )

I have lots of these radio plays so it would be nice to smartblock them for the year.

**Comment by Robbt** [comment]
Ok, I think that this would probably just be most easily done by scheduling this manually.

I'm not sure how we would encapsulate the idea of a continuing playlist into the current codebase as what happens is a playlist is cut-off when it is overbooked. So there would need to be a new data structure in the database made to have it remember where it was in a playlist and then try to resume it.

**Comment by Aphris-Karu** [comment]
I dont know about it being easily done by scheduling this manually but it can be done that way. It takes time to set up a bunch of these.

Was just hoping to get an automated way to do it at some point. 

As to cut-off when overbooked, that is a whole other issue as things like podcases can vary in time. So adding the ability to tell it to ether cutoff or run over and start the next show late would be nice as well. So if I have a syndicated podcast that varies from 2h to 3h 45m it would be nice to tell it to continue the podcast and start the next show when finished but keep the same end time for the second show.

**Comment by Robbt** [comment]
Yeah, it seems like a valid feature request, just not sure how easy it would be to implement.

Allowing tracks to run over would also require some deep changes to the current LibreTime scheduling paradigm. At what point do you decide that it is too much overflow and how do you fix the schedule to deal with the disruption caused by an overflow.

**Comment by Aphris-Karu** [comment]
I was picturing the run over events to simply be a show that is tagged as play to end. When it hits the end of the audio it then picks the show who's time it is currently in and plays that show to the end time for that show. The only caveat would be that the show tagged play to end must be >= the allotted time.

**Comment by zklosko** [comment]
Since shows have the ability to be linked, why not add a checkbox that says something like **Continue from previous show**? Linked shows do use the same playlist for multiple shows. Just a thought.

**Comment by zklosko** [comment]
@Aphris-Karu it might be easier for you to edit everything together in the DAW of your choice. This way, you have three audio files instead of 36, and it would be easier to schedule and play them back, and you have more control over the transitions.

**Comment by Robbt** [comment]
This in particular I don't think is very simple to accomplish within the constraints of our current data structure/organizational pattern of shows. So I don't plan on implementing it anytime soon and I'm not sure how easy it would be to implement but I understand the goal which is making it easy to play longform content over a wider period of time.
