### ISSUE TITLE
No Audio

### ISSUE THREAD

**Issue by danielmoore123** [LibreTime/libretime#1018]
Hi,
We are having problems with the native hardware audio output in Libretime, no matter how we configure it, there is no audio output, despite this, every other app in Ubuntu can play audio as normal. 
We are using the builtin audio 3.5mm jack at the back of the PC and no other sound card(s).

We're not too concerned with how to get an audio out, whatever works will be fine, things we have tried:
1) Installed pulseaudio manually and it's controller, no change
2) Installed OSS plugin for liquidsoap, tried that, no change
3) Updated the OS to Ubuntu 18, no change

If anyone has any ideas that would be much appreciated, please note: we are new to Linux.

**Comment by Robbt** [comment]
Check out the fix on #473 
`sudo usermod -a -G audio www-data `
Run that from a terminal reboot and see if it works. The output should be through ALSA most likely and configured from the Streaming settings page.

**Comment by danielmoore123** [comment]
Hi @Robbt,
Thank you for your reply, I'm afraid that has been tried and hasn't fixed it...
I've just uninstalled PulseAudio to see if that helps but it hasn't, `alsamixer` works and I can play audio from a browser for example, just not Libretime specifically... (although I have to note loss of the volume control option and ability to adjust in the Ubuntu GUI!)

I'm now following https://github.com/savonet/liquidsoap/issues/755#issuecomment-486061244

**Comment by danielmoore123** [comment]
Just as I hit post, https://github.com/savonet/liquidsoap/issues/755#issuecomment-486061244 seemed to fix it! Yay! Thank you for all your help, it is much appreciated.
