### ISSUE TITLE
No sound when live streaming using alternative ports

### ISSUE THREAD

**Issue by JvL-exec** [libretime/libretime#1020]
Hi,

Already browsed a lot of tutorials/issues here, it looks similar to #945 and #955. Can't get my live broadcast via master source (or show) to be hearable via stream. Hope there's a fix?

I have installed LibreTime on a Raspberry Pi3 running Ubuntu 18.04.4 LTS.
Stream is running via normal schedule, but when I try to broadcast live via /master (or /show) source I don't hear anything. Tested connection via BUTT and Mixx, both inputs are visible in LibreTime. 

- I can see a connection and input feed (via Butt and Mixx) 
- Both BUTT and Mixx can connect to host via hostname, port, mount, user/pw
- The Icecast server is online and visible
- LibreTime sees the source input and puts the stream On Air. 

**To Reproduce**
Ubuntu 18 image for Raspberry Pi
Install LibreTime via Git Clone
Set master stream user / password
BUTT / Mixx connect to LibreTime on other machine (MacOS 10.10) via local network
source codec MP3 128kb/s
Toggle input to master source 

**Expected behavior**
Stream should be heard

**LibreTime version**
LibreTime version 1d65945ed
Liquidsoap Version: 1.1.1-7.2ubuntu1

**System**
Raspberry Pi3+
Ubuntu 18.04.4 LTS
Installed Github package installer (./install)

Can put log files if necessary (please guide me which one)

**Comment by Robbt** [comment]
Have you been able to test your BUTT/Mixxx setup to be sure that the issue isn't further up the chain ?

Check out the /var/log/airtime/pypo/liquidsoap - I think that's the right directory and see if the pypo-liquidsoap.log shows anything.

You could also try connecting directly to icecast with the hardcoded password in /etc/icecast.xml and see if you run into the same issue or if bypassing libretime works.

**Comment by JvL-exec** [comment]
Thanks for the quick reply! 

- I tested bott BUTT and Mixxx setup, no problems there. 
- Also a direct plug into Icecast gives me sound on the stream. 
- I changed back to the original ports for master (8001) and source (8002) in LibreTime, BUTT/Mixxx. 

SOUND from the stream!! Yess!

Does that mean that the Liquidsoap configuration doesn't pick up the new ports when I change them in LibreTime?

**Comment by paddatrapper** [comment]
> Does that mean that the Liquidsoap configuration doesn't pick up the new ports when I change them in LibreTime?

It would seem so... A quick grep through the liquidsoap scripts doesn't reveal any hard-coded values for port numbers. I guess the thing to check is if airtime-liquidsoap restarts as expected when the ports are updated in the stream settings. Additionally, do you have any firewall set up on the server?

**Comment by JvL-exec** [comment]
- after a systemctl restart airtime-liquidsoap, I see liquidsoap changes the ports (see log below)
- However the stream fails again, no sound 
- No Firewall set on the server at this point. 

This is my first experience with Linux and I'm running tests on a local network to figure out how this all works technically. The next step is to put LibreTime out on a public stream, all secure and well.

Here the log file from the moment I see the port change.

----- pypo-liquidsoap/ls_script_legacy.log ----

2020/05/05 10:40:37 [harbor:3] Adding mountpoint '/master' on port 8420
2020/05/05 10:40:37 [harbor:3] Adding mountpoint '/show' on port 8421
2020/05/05 10:40:37 [threads:3] Created thread "http polling" (1 total).
2020/05/05 10:40:37 [stream432:3] Connecting mount stream432 for source@192.168.2.17...
2020/05/05 10:40:37 [stream432:3] Connection setup was successful.
2020/05/05 10:40:37 [lang:3] timeout --signal=KILL 45 pyponotify --connect --stream-id=1 --time=1588668037.75 &
2020/05/05 10:40:37 [threads:3] Created thread "wallclock_main" (2 total).
2020/05/05 10:40:37 [clock.wallclock_main:3] Streaming loop starts, synchronized with wallclock.
2020/05/05 10:40:37 [dummy:3] Source failed (no more tracks) stopping output...
2020/05/05 10:40:37 [dummy(dot)1:3] Source failed (no more tracks) stopping output...
2020/05/05 10:40:37 [dummy(dot)2:3] Source failed (no more tracks) stopping output...
2020/05/05 10:40:37 [dummy(dot)3:3] Source failed (no more tracks) stopping output...
2020/05/05 10:40:37 [dummy(dot)4:3] Source failed (no more tracks) stopping output...
2020/05/05 10:40:37 [map_metadata_5859:3] Inserting missing metadata.
2020/05/05 10:40:37 [master_show_schedule_noise_switch:3] Switch to show_schedule_noise_switch.
2020/05/05 10:40:37 [show_schedule_noise_switch:3] Switch to schedule_noise_switch.
2020/05/05 10:40:37 [schedule_noise_switch:3] Switch to map_metadata_5859.
2020/05/05 10:40:55 [lang:3] master connected
2020/05/05 10:40:56 [decoder:3] Method "MAD" accepted "audio/mpeg".
2020/05/05 10:40:56 [lang:3] timeout --signal=KILL 45 pyponotify --source-name=master_dj --source-status=true &
2020/05/05 10:40:56 [threads:3] Created thread "harbor source feeding" (3 total).
2020/05/05 10:40:56 [master_harbor:3] Decoding...
2020/05/05 10:41:18 [server:3] New client: localhost.
2020/05/05 10:41:18 [lang:3] dynamic_source.get_id
2020/05/05 10:41:18 [server:3] Client localhost disconnected.

**Comment by narcisgarcia** [comment]
1. What are all public TCP/UDP ports per service required to be open from Internet?
2. How do I replace 8001 and 8002 ports by other ones? Is this hardcoded by listeners/client applications?

**Comment by narcisgarcia** [comment]
The only way I've found to change broadcast ports freely is to set master_live_stream_port and dj_live_stream_port values directly to database.
Example for first time setting of TCP/64018 and TCP/64019:

sudo -i -u postgres psql -d airtime -c "INSERT INTO cc_stream_setting (keyname, value, type) VALUES ('master_live_stream_port', 64018, 'integer');"

sudo -i -u postgres psql -d airtime -c "INSERT INTO cc_stream_setting (keyname, value, type) VALUES ('dj_live_stream_port', 64019, 'integer');"

(and restart services)

**Comment by paddatrapper** [comment]
So if writing the changes to the DB works, my guess would be that the configuration options on the streaming page where you can set the port are not being written to the DB correctly

**Comment by jooola** [comment]
@JvL-exec Is this issue still relevant with the latest versions of LibreTime ?

**Comment by narcisgarcia** [comment]
What it must be checked is: If configuration interface really triggers actions to save `master_live_stream_port` and `dj_live_stream_port` on database, and/or if the action fails.

**Comment by jooola** [comment]
The version you are using is not supported anymore.

Changing the harbor/input stream ports is done in the configuration file, and any stream configuration changes requires a restart of liquidsoap. So this ticket is not relevant anymore.

**Comment by narcisgarcia** [comment]
And what about web interface?

**Comment by jooola** [comment]
> And what about web interface?

What do you mean ?
