### ISSUE TITLE
Web-based Installer crashes when special characters used in rabbitmq password

### ISSUE THREAD

**Issue by Robbt** [libretime/libretime#1026]
**Describe the bug**
A user reported a bug with the installer, it was determined to be because the php code failed to parse a line 29 of /etc/airtime/airtime.conf with a "!" character in the rabbitMQ password.

**To Reproduce**
Install.
Set RabbitMq password to something containing !
Go to web-based installer and type in the new password.
Get stuck.

**Expected behavior**
It should install as normal and parse the config file even with special characters. If this isn't feasible then the web-based installer should warn the user when they input a special character for the password vs. proceeding and then crashing.

This hasn't been confirmed yet by a developer and is just speculative based upon crash report and subsequent successful install w/o character by user.

**Comment by paddatrapper** [comment]
Reopening as the issue still exists, but now mitigated by #1035
