### ISSUE TITLE
Make a nicer-looking website for LibreTime

### ISSUE THREAD

**Issue by zklosko** [LibreTime/libretime#1029]
**Describe the solution you'd like**
Our mkdocs site looks like it came out of the early 2000's, especially compared to Airtime's. Can we switch to Github Pages? It looks like it requires less configuration than mkdocs and uses the same markdown to generate pages. In addition, we can use Jekyll for blogging if we feel like it. Someone would just have to change where the libretime.org domain points to.

**Comment by Robbt** [comment]
This was definitely on our radar - see #590 - we even had a nice splashy launch page but could never figure out how to set it up. We are currently using github pages with the HTML generated by Travis CI from mkdocs. Now that we are in a situation where our mkdocs has broken links it might be a good time to come up with a better launch front-page and move the docs to a sub-directory.

**Comment by zklosko** [comment]
Okay. I've gotten started. The theme isn't that great, but it's a good start. See PR #1030.

**Comment by paddatrapper** [comment]
We can close this by merging the PR

**Comment by gusaus** [comment]
The improvements to https://libretime.org/ look great (thanks @zklosko 🥇).  Would it still be beneficial to incorporate something closer to what @ned-kelly was working on https://ned-kelly.github.io/libretime-website/ for the primary domain and have this be a docs subsite?

If implementation is/was the main blocker https://github.com/LibreTime/libretime/issues/1029#issuecomment-626317622, what about building the marketing site with something like WordPress? 

If that was in the realm of possibility or good idea, we can re-open or create a new issue to further explore. 

Just wanted to get the idea out of our chat in Town Square https://chat.libretime.org/libretime/channels/town-square

**Comment by paddatrapper** [comment]
I think a WordPress main site with docs generated as a sub site/section is a good idea. I don't have any experience building WordPress sites, but I can host them. I'm happy to stand one up for someone to mess around with theming and content. Can do docs on docs.libretime.org and link to it from the site?

**Comment by Robbt** [comment]
I've done a lot of wordpress and drupal sites but I think we'd be better off with keeping the site as is. We can incorporating marketing/blogging into this new site and it's such an improvement over the last one. If someone wants to build a new site focused on marketing then go for it but I think currently we'd be better off putting our energy into refining the new site.

**Comment by gusaus** [comment]
@zklosko mentioned Jekyll (https://jekyllrb.com/showcase/) and it definitely looks like that could power something closer to #590 

How difficult and time-consuming would it be to incorporate some of those elements? Do we have someone well versed enough to take that on?

If we decided to go the WordPress route, I could try to replicate some of the elements on a dev site.

**Comment by gusaus** [comment]
Looks like incorporating https://github.com/LibreTime/libretime/pull/590#issuecomment-631477473 is a work in progress. 🤘

**Comment by zklosko** [comment]
A pro of using Jekyll is that it interface with GitHub to build the site every time commits are pushed. That, and the entire site can be written in markdown, so we don't have to rewrite any docs. What would be nice is if we can make @ned-kelly's splash page into a Jekyll theme so that it can be easily incorporated into our Jekyll build.

**Comment by gusaus** [comment]
> What would be nice is if we can make @ned-kelly's splash page into a Jekyll theme so that it can be easily incorporated into our Jekyll build.

If that's possible and not too time consuming, I think everybody talking in this issue is down with that idea. Guess we can continue the conversation in the PR https://github.com/LibreTime/libretime/pull/590#issuecomment-631477473

@zklosko off topic (at least with regards to this closed issue) - the LibreTime setup on your station is pretty slick! Maybe there's an opportunity to collaborate on improving players and integration https://discourse.libretime.org/t/custom-audio-players/140/33

**Comment by zklosko** [comment]
It would be awesome if someone else would be able to give me a hand with [this](https://zklosko.github.io/spirit-of-radio/). ;)
https://github.com/zklosko/spirit-of-radio

**Comment by paddatrapper** [comment]
Wow! That looks really good!

**Comment by gusaus** [comment]
@zklosko https://zklosko.github.io/spirit-of-radio/index is looking great! What do you need help with? 

Should we reopen this issue since the nicer looking website is still a work in progress?

**Comment by zklosko** [comment]
I guess we could reopen. I just created an issue on the spirit-of-radio repo to track what needs to be done. https://github.com/zklosko/spirit-of-radio/issues/1

Feel free to fork, commit, and open a PR.

**Comment by gusaus** [comment]
So is the code going to remain in this repo? If so, we should make sure this and related issues are labeled with docs, website, or whatever would be appropriate.

**Comment by zklosko** [comment]
@gusaus I wish, but I couldn't get Github to find it, so I've merged the code in with our repo. It's really only the items in `/_layouts`, '/css', '/Vendor', and `_config.yml`. I've been working on it more, so the theme is pretty much done.

**Comment by gusaus** [comment]
@zklosko So someone with the proper powers should fork your repo?

**Comment by paddatrapper** [comment]
@gusaus there is an open PR merging it all into this repo

**Comment by zklosko** [comment]
What @paddatrapper said, but you're welcome to extend on the theme in my repo, which others can still use. I will just need to copy changes over manually.

**Comment by gusaus** [comment]
Couple questions/thoughts with regards to https://github.com/LibreTime/libretime/pull/1053 (which is looking amazing!) - 

https://zklosko.github.io/libretime/index - It's cool to see some logos of stations that are using. Wondering if there's a way to present more stations... possibly in a way that could benefit the project. One potential way could to provide a tier on https://opencollective.com/libretime where having a stations logo being listed on the website could be a sponsor perk. 

As mentioned in the [forum](https://discourse.libretime.org/t/libretime-services-and-other-ways-to-sustain-the-project/326/16), this page on the OBS site might provide some inspiration with regards to how Open Collective could be incorporated into the contribute or sponsor page.
https://obsproject.com/contribute

Possibly stuff we can consider after https://github.com/LibreTime/libretime/pull/1053 is complete.

**Comment by zklosko** [comment]
@gusaus 

> https://zklosko.github.io/libretime/index - It's cool to see some logos of stations that are using. Wondering if there's a way to present more stations... possibly in a way that could benefit the project. One potential way could to provide a tier on https://opencollective.com/libretime where having a stations logo being listed on the website could be a sponsor perk.

I like it, but I don't think LibreTime is well-known enough to pull that off. I think at this point we want to show community use to get people on board, but we can look into sponsoring images on the front page once we've taken off more.

And once we get out of alpha.
