### ISSUE TITLE
WebCaster support requires SSL liquidsoap harbour

### ISSUE THREAD

**Issue by paddatrapper** [libretime/libretime#1032]
Browsers are blocking insecure requests on otherwise secure pages. Thus, something like [WebCaster](https://webcast.github.io/webcaster/) will not work without a SSL liquidsoap harbour. (See https://github.com/webcast/webcaster/issues/7#issuecomment-428494803)

We need to work out if we can offer both a secured and un-secured harbour so that people can use either depending on their needs.

**Comment by risharde** [comment]
Definitely needs to support ssl

**Comment by jooola** [comment]
Now that we have an easy way to customize liquidsoap from the configuration file, I think we can start drafting an advanced setup (not by default and for users experienced with the CLI):
- Add a `liduisoap.certs` config section that accept certificates paths.
- Update the liquidsoap entrypoint generation to setup the ssl certs if provided.
- Add a `secure` boolean switch in the inputs stream config section to enable ssl or not.
- Write a guide on how to set this up, using a certbot certificates.

**Comment by paddatrapper** [comment]
Do you think we will expose both a secure and non-secure port simultaneously?

**Comment by jooola** [comment]
I think everything should be secure, I was mainly answering to the original ticket, that mentioned to have both insecure and secure ports.

Reading the liquidsoap (need some testing to comfirm), we can listen on the same port and have multiple mountpoint. So I don't know if splitting main and show into 8001 and 8002 is a feature or from a limitation. With that in mind we could have 8001 for insecure and 8002 for secure connection.

**Comment by paddatrapper** [comment]
Ok. In that case I think `secure_port` would work over a feature flag
