### ISSUE TITLE
Airtime Analyzer ReplayGain fails with Python 3.5

### ISSUE THREAD

**Issue by paddatrapper** [LibreTime/libretime#1041]
Calling `subprocess.check_output()` with `text=True` was only added in Python 3.7:

https://github.com/LibreTime/libretime/blob/0c5c8fae5238eabe7da73a2490535976205f2d3a/python_apps/airtime_analyzer/airtime_analyzer/replaygain_analyzer.py#L23-L24

Before then `universal_newlines` was used: https://docs.python.org/3.7/library/subprocess.html#subprocess.check_output

**Comment by rjhelms** [comment]
Per the python docs, both `text` and `universal_newlines` are present in Python 3.7 and up as aliases of each other, so changing this call to use `universal_newlines` instead should be compatible with newer versions while resolving this issue in python 3.5 and 3.6.

I don't have a proper Libretime dev environment set up to test thoroughly, but making this change and reinstalling Libretime on my staging environment seems to resolve this issue with Ubuntu 18.04 LTS / Python 3.6.

**Comment by paddatrapper** [comment]
@rjhelms can you submit a PR with that fix? I'm happy to review, test and merge

**Comment by rjhelms** [comment]
@paddatrapper Apologies for the delay in getting to this - PR has been submitted.

**Comment by paddatrapper** [comment]
Thanks!
