### ISSUE TITLE
Listener Stat fails on Python 3

### ISSUE THREAD

**Issue by Robbt** [LibreTime/libretime#1045]
**Describe the bug**
Listener stat's can be acquired via the stats page.

**To Reproduce**
Install latest branch with python 3.
Go to Analytics -> Listener Stats

See error:
Stream Data Collection Status

_a: Please make sure admin user/password is correct on Settings->Streams page.

In zendphp Log 
INFO (6): localhost Array
(
    [0] => Array
        (
            [keyname] => _a_listener_stat_error
            [value] => a bytes-like object is required, not 'str'
            [type] => string
        )

)

This leads me to believe it is a python 3 issue since we ran into this.

**Expected behavior**
If correct user/password are on the stream it should show this.

**LibreTime version:**
LibreTime with Python 3 packages

**Installation method:**
 Reported on 18.04 and tested on 16.04 locally. Needs further testing w/ newer python versions.

Also see original request for help at discourse forum - https://discourse.libretime.org/t/listener-stats-from-a-3rd-party-stream/570/4

**Comment by paddatrapper** [comment]
Probably something in pypo that is not calling api_client with the correct type of object

**Comment by paddatrapper** [comment]
The offending line

https://github.com/LibreTime/libretime/blob/ebb6b59755e204d80ff27857b33369ef0de502a5/python_apps/pypo/pypo/listenerstat.py#L38
