### ISSUE TITLE
proposal: pause the constant LibreTime connection to Icecast

### ISSUE THREAD

**Issue by dmnktoe** [LibreTime/libretime#1057]
This is more an idea or a proposal I would like to discuss with you. I've been playing around with the fallback streams in the Icecast configuration lately and noticed that LibreTime is really constantly connected to the Icecast stream, even if there is no content scheduled or no live input.

Unfortunately this means that there is no possibility to send programs via a fallback stream. One option would be to specify in the settings that LibreTime automatically "logs off" from Icecast if no program is scheduled or no live input is available.

After more and more discussions about the new LibreTime API, I noticed one more thing. In the old Airtime Pro documentation ([Airtime Pro API](https://help.sourcefabric.org/hc/en-us/articles/115000382243-Airtime-Pro-API#%E2%80%9Clive_info_v2%E2%80%9D)) there is the possibility to get live information. "source_enabled" outputs either "Scheduled" or "MASTER". "MASTER" but of course only if a program is connected to LibreTime. However, "Scheduled" is always output even though no program is scheduled. 

I make use of this function to display a small live-indicator on our webpage / app, when our radio station is going live. But sometimes I just upload a pre-recorded audio file and let it play out and then I would like to use the "Scheduled" key to display the live indicator as well. But as soon the stream is finished and the program is over, the "old Airtime API" still says "Scheduled".

One consideration here would be to rewrite the API so that if no program is scheduled, the API will also output that no program is scheduled.

Let me know what do you think. Have a great week!

Edit: This really isn't a bug, so can a mod remove the "bug" label and set the "proposal" label instead?

**Comment by Robbt** [comment]
So this probably falls into the territory of liquidsoap customization as the easiest way to handle it within the LibreTime framework. Basically you could have libretime's liquidsoap script handle the backup stream, but that isn't something that we have spent the time to make easy - See #229

But the option to disable scheduled playback is something I could see making sense. It sounds like the other idea has to do with the metadata being displayed and I have seen LibreTime display that it is offline when there is nothing scheduled, so I'm not 100% sure what instance you are shooting for. Is it just API specific ?
