### ISSUE TITLE
Waveform - Cue In & Cue Out / Fade In & Fade Out

### ISSUE THREAD

**Issue by nscpro** [LibreTime/libretime#1063]
For Libretime to work even more as a professional web radio studio solution, it is very important that the transition of songs is smooth. To do this, it is very important to be able to set a cue in and cue out point for the songs when compiling the playlist. It is also important to set a fade in and fade out point. In Airtime 2.5 there is a possibility to use a waveform solution for this. That would be a huge step forward if you could take this opportunity.

Another thing that would be very important is that just as DJ programs automatically recognize the tempo of a song when you record a song, it would be great if Libretime could do that to show and identify the tempo of the song itself.

There could also be a possibility to use a microphone in the future to speak something between songs.

**Comment by paddatrapper** [comment]
Cue points are set by silan already. These should already be used by LibreTime to set the start and end of songs. You can set the fade in an out times for playlists. I'm not sure if that is used to cross-fade or to fade in at the beginning of the playlist and out at the end.

BPM detection in airtime_analyzer - #1064

Live shows - this is supported by using a show or master mount and streaming to it live. Using the LibreTime library in that is tracked in #480 and #1033

**Comment by nscpro** [comment]
@paddatrapper I can indicate the time of Cue In and Cue Out in the field, but where I know to the nearest hundredth when to set the Cue In or Cue Out point. On top of the waveform I see a wave and I can set it to a point and give the time myself automatically. Do I really have to go over every song I've uploaded to Libretime with Audacity or another program to find out the time?

Fade In and Fade Out same topic. Every song is start and end is different. If I set 0.5 or 1 all songs, then he still fades it quite strangely on many songs.

Can i use Libretime library (some scheduled shows) and microphone same time? I understand that if I have a scheduled show on the air and at the same time I just go live with a live show, it will interrupt the show that is currently on the air. Maybe in a form like the usual on the radio, I can talk between songs for a while with a microphone, right?

**Comment by paddatrapper** [comment]
I think having the waveform display would be useful. It would only work for pre-defined playlists though. Smartblocks would not have waveforms to display. There you would need to just define a generic time, which the Cue In and Out would work for. Silan trims silence off tracks, so there will be a fade with actual content involved instead of silence.

> Can i use Libretime library (some scheduled shows) and microphone same time?

The current way of doing this is to duplicate the library in something like Mixxx or Rivendell and stream the output of that and your mic to LibreTime. #1033 and #480 are the two issues that track having proper live assist support that integrates the LibreTime library without needing to duplicate it.

**Comment by nscpro** [comment]
@paddatrapper It would be nice if pre-defined playlists could use Cue In and Out in the form of a waveform.

I hope such changes come sometime :)

**Comment by hairmare** [comment]
If we move forwards on this, a refactor from waveform to the [peaks.js](https://waveform.prototyping.bbc.co.uk/) ecosystem should be on our agenda.
