### ISSUE TITLE
No audio in web player

### ISSUE THREAD

**Issue by saikiran91** [LibreTime/libretime#1067]
I recently installed LivreTime. I will able to attach it to my website and start the show. In the audience/listeners end if the users click on the play button in web player the button changes to pause and I can see the title text etc. But I can't hear the audio. When I check the console below is what I see. Any help is greatly appreciated.
Request URL: http://127.0.0.1:8000/airtime_128

<img width="1193" alt="Screenshot 2020-06-22 at 2 38 01 AM" src="https://user-images.githubusercontent.com/3991577/85235425-54113600-b432-11ea-810b-f433bdfac074.png">

**Comment by paddatrapper** [comment]
Can you post /etc/airtime.conf?

**Comment by MCAlexPrime** [comment]
I have same bug. http://lhradio.pp.ua/
When i click to play, nothing works

**Comment by zklosko** [comment]
I believe the same is happening in #461

**Comment by paddatrapper** [comment]
Fixed in #1145

**Comment by paddatrapper** [comment]
Pulling from the config file: #1147
