### ISSUE TITLE
HTTPS webstream unplayable errors not shown to user

### ISSUE THREAD

**Issue by paddatrapper** [libretime/libretime#1068]
Liquidsoap < 1.3.7-1 on Debian and Ubuntu (Debian Buster, Ubuntu 18.04) is not built with SSL support. So HTTPS webstreams cannot be played. Silence is played instead, and no error is provided to the user

We should improve the error detection and reporting here in the logs and, potentially, the web UI

**Comment by Aeris1One** [comment]
On a very fresh install, I linked a new domain and set up SSL Certificate using certbot and... 
![image](https://user-images.githubusercontent.com/29739547/88430258-6b0fc300-cdf8-11ea-983a-5b387a02a6de.png)

**Comment by paddatrapper** [comment]
What is the contents of your `/etc/airtime.conf`? That looks like your server name defined there is the IP address and not the domain that the SSL certificate is valid for

**Comment by paddatrapper** [comment]
But no, not related to this issue

**Comment by valerio-bozzolan** [comment]
I was able to replicate on Debian GNU/Linux buster (current stable).

Adopting an `http://` stream fixed my issue as workaround.

**Comment by paddatrapper** [comment]
I have added SSL support to Liquidsoap for Bullseye, but we still need better error reporting
