### ISSUE TITLE
Contributing: Russian translation

### ISSUE THREAD

**Issue by yarik2720** [LibreTime/libretime#107]
Hi! I'd like to contribute for Russian translation of Libretime

**Comment by hairmare** [comment]
As you may have noticed we [don't have an interface](http://libretime.org/translating/)/#78 for that yet.

I figured out how to regenerate the base strings and could have something ready for use with [poedit](https://poedit.net/) in a reasonable timeframe. I'm assuming that you will not be the only russian translator so it probably makes more sense to prioritize zanata as per #78.

**Comment by hairmare** [comment]
I'm updating the po files in #108 so they contain the new strings. automation and zanata to be done later...

**Comment by hairmare** [comment]
I set up a zanata for LibreTime and tested it by round-tripping some de-DE strings. It may be found at https://translate.zanata.org/iteration/view/libretime/master.

It is based on the strings from #108. 

Merging back to github is not automated yet. So you'll need to let me know when you are done so I can pull the new strings from zanata. I'll try pulling them at somewhat regular intervals until this is automated but feel free to let me know if you want me to manually trigger a merge.

**Comment by hairmare** [comment]
I looks like I need to know your zanata username to add you to the project. You can get one by going to https://translate.zanata.org/.

I'll set you up as the language admin if that's ok with you.

**Comment by korotkov13** [comment]
@hairmare I got the same account as here

**Comment by hairmare** [comment]
@korotkov13 You are now a Translation Maintainer, Russian Translator, and Reviewer.

This means you can also translate other languages and add translators as well. Thanks for contributing.

Let me know if you need any help or would like for me to pull the translations back into LibreTime.

**Comment by yarik2720** [comment]
My username yarik2720

**Comment by hairmare** [comment]
@yarik2720 I gave you the same permissions as Yuriy

**Comment by korotkov13** [comment]
almost 79% ready)

**Comment by korotkov13** [comment]
Most are translated and approved.
I will continue later if no one will help until then.

**Comment by yarik2720** [comment]
99% ready. Some fuzzy strings remain

**Comment by korotkov13** [comment]
@yarik2720 Great job!
I edited a little bit and approved.
I think we can close this thread and adding translation to master.

**Comment by yarik2720** [comment]
Agreed

**Comment by hairmare** [comment]
You will have to restart apache after updating the `.mo` files. That's not convenient but it's that way php-gettext works.

**Comment by hairmare** [comment]
Some issues with the Javascript code also remain, I'm working on pinning them down so the new texts actually show up so don't be surprised if it looks like some of your work went missing. It's there I just need to squash some bugs for everything to show up properly.

**Comment by yarik2720** [comment]
![virtualbox_2017-03-24_22-03-58](https://cloud.githubusercontent.com/assets/1839978/24309676/d39094e4-10dd-11e7-9fc2-062269f69ec6.png)
something went wrong

**Comment by korotkov13** [comment]
![screen shot 2017-03-24 at 22 05 36](https://cloud.githubusercontent.com/assets/25418594/24309758/295986d8-10de-11e7-9563-c65e48084b85.png)
It's fine on my test site

**Comment by yarik2720** [comment]
Yes, sorry, it cache couse. I'll edit some translations that can overlapp elements

**Comment by hairmare** [comment]
@yarik2720 Yeah, the cache is a pain. <kbd>Cmd+Shift+R</kbd> and private mode windows are my friend when I hack on the CSS :rage2: 

If you can change the wording that it looks better that would be nice. We'll also try making it friendlier for more than one language when it come to edge cases. Feel free to create issues or PRs for any edge cases where you think adapting the CSS makes sense.
