### ISSUE TITLE
schedule messed up over night / dates moved to another month and another week

### ISSUE THREAD

**Issue by H0ST4L3X** [LibreTime/libretime#1075]
EDIT: nevermind. It was a browser issue. Using a fresh browser profile everything works fine.

**Comment by Robbt** [comment]
Ok, weird, must have been something to do with javascript gone awry or a failure to connect properly to the backend. Glad you figured it out, sounded bad from the email I received.

**Comment by H0ST4L3X** [comment]
@Robbt With a new vanilla Firefox profile it works fine. Still, what I wonder about is, that with the profile I used before it worked just fine, no troubles for many months. I can not really get behind it.
And yes, I was pretty stressed for an hour or two until another program manager told me on his side it was fine, so I figured it must have something to do with my browser setting / client issue.
