### ISSUE TITLE
Unable to Uninstall Libretime: airtime-celery.service could not be found

### ISSUE THREAD

**Issue by J0hn3ch** [LibreTime/libretime#1079]
**Description of the bug**
When I run `sudo ./uninstall` inside the ~/libretime folder, LibreTime exit from uninstallation with the message:

> Failed to stop airtime-celery.service: Unit airtime-celery.service not loaded.

**Installation method:**
 - OS: Debian
 - OS Version: 10 Buster
 - Method: `sudo ./install -fiap`

**Comment by paddatrapper** [comment]
This is probably to do with the rename from `airtime-celery` to `libretime-celery`. As a work around, you can rename `/etc/systemd/system/libretime-celery.service` to `/etc/systemd/system/airtime-celery.service` and then run uninstall
