### ISSUE TITLE
Use network drive mounted at /mydrive for media folder

### ISSUE THREAD

**Issue by adukale** [LibreTime/libretime#1081]
I am trying to use network drive mounted at /mydrive for media folder but when I enter the path in setup page, the page reports an error stating "you need to enter fully qualified path". I have tried changing the owner of the /mydrive to www-data but no use.
Please advise.

**Comment by paddatrapper** [comment]
How are you mounting the drive? Is it NFS, Samba, etc?

**Comment by adukale** [comment]
I am mounting the same via FUSE file system.

**Comment by paddatrapper** [comment]
Try mount it as `/srv/airtime/stor`? You could be running into #620

**Comment by adukale** [comment]
I tried mounting the same as "/srv/airtime/stor" but then the installer gives error and does not proceed. Also tried doing  chown -R www-data.www-data /mydrive/songs, but I get the same error.
![lib1](https://user-images.githubusercontent.com/1003980/90021053-5b382000-dcce-11ea-8544-b8ffe8f80ce4.PNG)

**Comment by paddatrapper** [comment]
Are there any errors in the developer console or in `/var/logs/airtime/`?

**Comment by adukale** [comment]
Here is the log from zendphp.log:
`array (
  'type' => 1,
  'message' => 'Uncaught Error: Call to a member function getDirectory() on null in /usr/share/airtime/php/airtime_mvc/application/models/MusicDir.php:34
Stack trace:
#0 /usr/share/airtime/php/airtime_mvc/application/models/Systemstatus.php(222): Application_Model_MusicDir->getDirectory()
#1 /usr/share/airtime/php/airtime_mvc/application/models/Systemstatus.php(236): Application_Model_Systemstatus::GetDiskInfo()
#2 /usr/share/airtime/php/airtime_mvc/application/common/TaskManager.php(266): Application_Model_Systemstatus::isDiskOverQuota()
#3 /usr/share/airtime/php/airtime_mvc/application/common/TaskManager.php(60): PodcastTask->shouldBeRun()
#4 /usr/share/airtime/php/airtime_mvc/application/common/TaskManager.php(104): TaskManager->runTask(\'PodcastTask\')
#5 /usr/share/airtime/php/airtime_mvc/application/controllers/plugins/PageLayoutInitPlugin.php(70): TaskManager->runTasks()
#6 /usr/share/airtime/php/vendor/zf1s/zend-controller/library/Zend/Controller/Plugin/Broker.php(260): PageLayoutInitPlugin->routeShutdown(Object(Zend_C',
  'file' => '/usr/share/airtime/php/airtime_mvc/application/models/MusicDir.php',
  'line' => 34,
)
2020-08-12T14:09:21+00:00 WARN (4): 172.105.48.178 SQLSTATE[55P03]: Lock not available: 7 ERROR:  could not obtain lock on row in relation "cc_pref"
2020-08-12T14:09:21+00:00 INFO (6): 172.105.48.178 Notifying RabbitMQ to send message to pypo
2020-08-12T14:09:21+00:00 INFO (6): 172.105.48.178 Registered Component: pypo@172.105.48.178
2020-08-12T14:09:21+00:00 INFO (6): 172.105.48.178 Registered Component: show-recorder@172.105.48.178
`

**Comment by adukale** [comment]
What I have done now is, completed the setup with default values and after that modified the "cc_music_dirs" table in database with my network drive path. After I update the value the libretime fails to load it shows error page.
Dont know what I am mistaking.

**Comment by paddatrapper** [comment]
It is defined in the config file as well I think (`/etc/airtime/airtime.conf`)

**Comment by adukale** [comment]
Nope, config file does not have entry for the media folder.

**Comment by xabispacebiker** [comment]
You are not mounting the filesystem correctly and libretime cannot access the mount point. Mount the network drive as @paddatrapper suggested and in the setup use that path (/srv/airtime/stor)
