### ISSUE TITLE
Do not assume existing PHP version from distro release

### ISSUE THREAD

**Issue by paddatrapper** [LibreTime/libretime#1083]
The install script assumes the version of PHP that should be installed based on the distro and release detected. If a different PHP version is already installed, this can cause issues (#1077). We should rather test if PHP is installed. If so, install PHP packages for that version. If not, install as currently done.

**Comment by zklosko** [comment]
Does this still need to be done?

**Comment by paddatrapper** [comment]
Until we replace PHP, yes
