### ISSUE TITLE
Changing port from 80 to another for API

### ISSUE THREAD

**Issue by eskapiste** [LibreTime/libretime#1085]
Hi there guys!
I want to add ssl to icecast2 (i did it on another server without libretime some time ago) but it requires icecast to be accessible on port "80".
So i wonder, is it possible to change API port to another, not 80?
i tried to change it in airtime.conf - nothing changed.
also, it is mentioned in your docs that if you change base_url or base_port, you have to change it in api_client.cfg also.
but i can't find this file in /etc/airtime

**Comment by zklosko** [comment]
After changing it in airtime.conf, did you restart Libretime services/the computer?

**Comment by paddatrapper** [comment]
Also SSL icecast doesn't require port 80 access. I have it working on a second domain using a reverse proxy
