### ISSUE TITLE
2 new Setups of Xubuntu 18.04.04 with updates before installing last Libretime-Master and they jumped tu 18.04.05

### ISSUE THREAD

**Issue by klaus13** [LibreTime/libretime#1087]
Making 2 times new installation of Operation System and Libretime Master, I have seen that Celery can not be started.

There was also an issue to get access to localhost. 
sudo chown -R www-data:www-data /usr/share/airtime/php/airtime_mvc/ resolved to get access.
I'm not sure that this is the best to do.

The next issue is that Gain Replaiy don't work too.
I like to use new Libretime Master because the new Track Type and Artwork is very useful for quick identification of Tracks.
So I would like to get soloution to fix this difficulties.

Reading that more Libretime users have this issues too and it seams that the problems are related to the Operation System   and  not to Libretime, it would maybe be more simple to use exactly the right version of Operating System like Xubuntu 18.03.0 (?) and do no more updates after the installation of this Operating System version. 

For to know witch Operating System will be the best for the last tested Libretime Master installation, please write this some were with the installation instruction. we could save some time.

I think it will be impossible for developers to hunt all the time behind every System update. On other PC's I follow this updates and there is nearly every days some new things to get.

So I will make some tests to find which (X)ubuntu version will work the best without any update and the actual Libretime Master installation. 

Maybe this is the easiest way to get peace for some time....

**Comment by paddatrapper** [comment]
Ubuntu 18.04: https://libretime.org/install

**Comment by klaus13** [comment]
Ok, I will make a new setup with Xubuntu 18.04 and take care to do not make any update to see if it's better working. Thank you for for your quick answer.
