### ISSUE TITLE
Let DJ’s edit their show description & URL

### ISSUE THREAD

**Issue by kaya-karaca** [LibreTime/libretime#1090]
Hello everyone,

i’m stuck with a problem. I want our DJ’s to be able to edit the description & url of their assigned shows / instances. I found some assignable user roles here: https://github.com/LibreTime/libretime/blob/master/airtime_mvc/application/configs/ACL.php

But i guess when i activate it for the DJ’s they would also be able to change the date and everything else from the show.

Any ideas how to solve that problem?

Thanks a lot!

**Comment by paddatrapper** [comment]
This is not currently supported, but I think adding more customizable permissions may be a good idea. My thinking is having a set of ACL rules that can be assigned to users or groups. By default we ship groups corresponding to the current permissions (Guest, DJ, Programme Manager, Admin) and allow more to be created and assigned to users. A user can be a member of 0 or more groups and be associated with 0 or more permissions
