### ISSUE TITLE
No manual pages from interface links

### ISSUE THREAD

**Issue by narcisgarcia** [LibreTime/libretime#1095]
Dashboard - Tracks

You haven't added any tracks
Click 'Upload' to add some now.
Learn about tracks -> libretime.org/manual/tracks -> 404 Tape Page not found :(

Same at Playlists when empty
Same at Smart Blocks when empty
Same at Webstreams when empty
Same at Podcasts when empty

**Comment by paddatrapper** [comment]
I don't understand what the problem here is? Can you explain in more detail?

**Comment by narcisgarcia** [comment]
When user clicks on "Learn about..." this link goes to an unexisting page.
Help links to external (libretime.org) documentation are broken.

**Comment by paddatrapper** [comment]
Ah I see. This is from the documentation redesign in #1053

**Comment by narcisgarcia** [comment]
Then this bug is pending to LibreTime is released with links fixed + old pages redirected to new ones to attend old LT versions.

**Comment by zklosko** [comment]
Yeah, I need to go back and fix a few things. Do I need to open a new issue and pull request for that?

**Comment by paddatrapper** [comment]
No, just open a PR closing this issue and any others that are included
