### ISSUE TITLE
Switch from Apache to Nginx (or Lighttpd) with self-signed certificate

### ISSUE THREAD

**Issue by zklosko** [LibreTime/libretime#1099]
**Describe the solution you'd like**
I think it would be nice for us to switch the Libretime installer to deploy Libretime with Nginx instead of Apache. I've heard that Nginx tends to be faster overall and uses less system resources to run, plus it supports the PHP we use. While we're at it, I think there should be an option in the installer to deploy a self-signed certificate with Libretime, for those who will need to use the application behind a proxy that Letsencrypt cannot reach. HTTPS is the standard these days and so it should come standard on Libretime.

**Describe alternatives you've considered**
There are other web servers like lighttpd.

**Additional context**
Below is the `airtime.conf` site configuration in Apache:

```
<VirtualHost *:80>
   ServerAdmin foo@bar.org
   DocumentRoot /usr/share/airtime/php/airtime_mvc/public/
   php_admin_value upload_tmp_dir /tmp
   php_value post_max_size 500M
   php_value upload_max_filesize 500M
   php_value request_order "GPC"
   php_value session.gc_probability 0
   php_value session.auto_start 0

AddOutputFilterByType DEFLATE text/plain
   AddOutputFilterByType DEFLATE text/html
   AddOutputFilterByType DEFLATE text/xml
   AddOutputFilterByType DEFLATE text/css
   AddOutputFilterByType DEFLATE application/xml
   AddOutputFilterByType DEFLATE application/xhtml+xml
   AddOutputFilterByType DEFLATE application/rss+xml
   AddOutputFilterByType DEFLATE application/javascript
   AddOutputFilterByType DEFLATE application/x-javascript
   AddOutputFilterByType DEFLATE application/json


  <Directory /usr/share/airtime/php/airtime_mvc/public/>
      RewriteEngine On
      RewriteCond %{REQUEST_FILENAME} -s [OR]
      RewriteCond %{REQUEST_FILENAME} -l [OR]
      RewriteCond %{REQUEST_FILENAME} -d
      RewriteRule ^.*$ - [NC,L]
      RewriteRule ^.*$ index.php [NC,L]

      DirectoryIndex index.php
      AllowOverride all
      Order allow,deny
      Allow from all

      Require all granted
  </Directory>
</VirtualHost>
```

I'd imagine the equivalent in NGINX would start to look like this:

```
server {
    listen 80;
    server_name libretime;
    root /usr/share/airtime/php/airtime_mvc/public/;

    index index.php index.html index.htm;

    location / {
        try_files $uri $uri/ =404;
        if (-e $request_filename) {
              rewrite ^/(.*)$ /index.php last;
        }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;
        fastcgi_param PHP_ADMIN_VALUE "upload_tmp_dir= /tmp";
        fastcgi_param PHP_VALUE "post_max_size = 500M";
        fastcgi_param PHP_VALUE "upload_max_filesize = 500M";
        fastcgi_param PHP_VALUE "upload_max_filesize = 500M";
        fastcgi_param PHP_VALUE "session.gc_probability = 0";
        fastcgi_param PHP_VALUE "session.auto_start = 0";
     }

    location ~ /\.ht {
        deny all;
    }
}
```

**Comment by zklosko** [comment]
With trying the code in the description, I'm able to get the static elements (the favicon, a png in the root folder, the robots.txt file) to display as static, but I'm getting 502 Bad Gateway errors when trying to go to main interface.

I'm not as familiar with NGINX. Any ideas?

**Comment by paddatrapper** [comment]
PHP 7.4 is untested and I'm not sure Zend works with it. See https://github.com/LibreTime/libretime/pull/967#issuecomment-619245235

**Comment by zklosko** [comment]
What version of PHP do we currently use?

**Comment by paddatrapper** [comment]
You need a line configuring the 404 page: `error_page   404  =  /404.html;` (where `/404.html` is the actual 404 page URL)

**Comment by gstrauss** [comment]
@zklosko 
> There are other web servers like lighttpd, but they're not Nginx. ;)

True.  lighttpd can be faster and lighttpd uses fewer resources.

```
server.port = 80
server.name = "libretime"
server.document-root = "/usr/share/airtime/php/airtime_mvc/public/"
server.upload-dirs = ("/tmp")  # lighttpd default is "/var/tmp"
server.max-request-size = 512000  # num in KB; 500 MB is 512000KB

index-file.names = ("index.php")

server.modules += ("mod_rewrite")
url.rewrite-if-not-file = ( "" => "/index.php/${url.path}${qsa}" )

server.modules += ("mod_fastcgi")
fastcgi.server += ( ".php" =>
   ((
        #(if using PHP-FPM 7.4 or later)
        #"socket" => "/run/php/php-fpm.sock",
        "socket" => "/run/php/php7.2-fpm.sock",
        "broken-scriptfilename" => "enable"
   ))
)

server.modules += ("mod_deflate")
deflate.cache-dir = "/var/cache/lighttpd/compress/"
deflate.mimetypes = ("text/plain", "text/html", "text/xml", "text/css", 
                     "application/xml", "application/xhtml+xml", "application/rss+xml",
                     "application/javascript", "application/x-javascript", "application/json")
```

**Comment by zklosko** [comment]
@gstrauss you have a very good point. 👍 

Does your code work as is?

**Comment by gstrauss** [comment]
I have not set up a Libretime environment, but the sample config above should get your most of the way there, if not all the way.

**Comment by zklosko** [comment]
@paddatrapper I just can't figure out how to do all of the URL rewrites that Libretime requires.

**Comment by paddatrapper** [comment]
What rewrites are needed?

**Comment by zklosko** [comment]
```
      RewriteEngine On
      RewriteCond %{REQUEST_FILENAME} -s [OR]
      RewriteCond %{REQUEST_FILENAME} -l [OR]
      RewriteCond %{REQUEST_FILENAME} -d
      RewriteRule ^.*$ - [NC,L]
      RewriteRule ^.*$ index.php [NC,L]
```

This needs to be accounted for. The login page is at `/login`, but is not a literal file (say `login.php`) within the Public directory, so the web server needs a way to find the page that does not literally exist. I hope that makes sense.

**Comment by zklosko** [comment]
I think I got the rewrite condition set... now it looks like there's an issue with it communicating with PHP. :(

**Comment by zklosko** [comment]
As interesting of an idea as this may or may not be, we've got bigger fish to fry. This can hold off until a Libretime rewrite.

**Comment by gstrauss** [comment]
> The login page is at /login, but is not a literal file (say login.php) within the Public directory, so the web server needs a way to find the page that does not literally exist. I hope that makes sense.

FYI: in lighttpd.conf that might look something like the following, assuming '.' is not in the final path segment.
```
server.modules += ("mod_rewrite")
url.rewrite-if-not-file = ("^(.*/[^./]+)$" => "${url.path}.php${qsa}",
                           "" => "/index.php/${url.path}${qsa}" )
```

**Comment by zklosko** [comment]
@gstrauss I was able to get the login page to display, but the authentication module (or whatever) isn't working correctly.

```
server {
    location / {
	root /root/here;
	try_files	$uri index.php =404;

	if (-e !$uri) {
		rewrite (.*) index.php;
	}
    }
}
```
