### ISSUE TITLE
Cover metadata assigned to wrong item

### ISSUE THREAD

**Issue by xabispacebiker** [LibreTime/libretime#1100]
**Describe the bug**
Cover metadata gets assigned to the first item (tab) in the batch, instead of the current edited item

**To Reproduce**
1. Go to the library
2. Edit two or more tracks
3. Assign the cover to the first visible item.
4. The cover is assigned to the last visible item.

**Expected behavior**
The cover should be assigned to the edited item

**Screenshots**
![libretime_cover_bug](https://user-images.githubusercontent.com/1733884/97793064-0f1ebc80-1be7-11eb-8483-2fec06396b6f.png)

**LibreTime version:**
2003e685b

**Installation method:**
 - OS: Debian
 - OS Version 9 stretch

**Client (please complete the following information if applicable):**
 - Browser, tested on safari, chrome

**Comment by zklosko** [comment]
Are we able to close this issue?
