### ISSUE TITLE
Microsite fails to connect to non-HTTPS streams.

### ISSUE THREAD

**Issue by rjhelms** [LibreTime/libretime#1102]
The built-in microsite has forceHTTPS set to "true" for the stream player. This causes stream playback to fail for non-HTTPS installations.

https://github.com/LibreTime/libretime/blob/2003e685b04a1115f7c87d381f9887d10fa226e6/airtime_mvc/application/views/scripts/embed/player.phtml#L21-L26

While all production deployments should certainly use HTTPS, the stream URL should likely not be changed by the player

Steps to reproduce:
- deploy Libretime on a non-HTTPS environment
- attempt to connect to stream in microsite

Expected: stream plays successfully
Actual: player changes http:// to https:// in stream URL and fails to connect

Version: master (2003e685b)
Distro: Ubuntu 18.04 LTS

**Comment by hairmare** [comment]
I concur with the fact that this is a bug, but `forceHTTPS=true` does feel better than fixing this with `forceHTTPS=false` (unless I'm missing something, I probably am).

Can we obsolete this by focusing on a TBD high level TLS/SSL issue?

In the long run this might also be be related to, if not solved by, the #2 refactor introducing vue components.

**Comment by rjhelms** [comment]
My understanding is that `forceHTTPS=true` changes any stream url to begin with HTTPS, while `forceHTTPS=false` passes through whatever stream URL to the player unchanged which - ideally - should be passed correctly as HTTP or HTTPS to the view based on server setup.

To my understanding, the URL in the view comes from /airtime_mvc/application/models/StreamSetting.php, which seems to hard-code `http`: https://github.com/LibreTime/libretime/blob/5b822afe14046157a8d9fbdff103eb383673e6be/airtime_mvc/application/models/StreamSetting.php#L78-L82

Based on that, perhaps @hairmare's suggestion of a higher-level TLS/SSL issue is the best approach (to this total newbie to Libretime's codebase, at least) - I could see any good solution to this issue quickly expanding far beyond the original scope.

**Comment by zklosko** [comment]
It is possible to add a self-signed certificate to Icecast and serve on 8443, thus serving an encrypted stream; would that be worth a shot?

**Comment by paddatrapper** [comment]
I think setting `forceHTTPS=false` is the right thing here - let Nginx/Apache handle HTTP->HTTPS redirection like everywhere else in the code base. If we can some how set `forceHTTPS=true` when `force_ssl=True` in the config, that would be great (https://libretime.org/docs/reverse-proxy)

**Comment by zklosko** [comment]
I think this can be closed due to #1145 and #1147.

**Comment by paddatrapper** [comment]
Fixed in #1145
