### ISSUE TITLE
Possibility to group library by album, artist, etc..

### ISSUE THREAD

**Issue by xabispacebiker** [LibreTime/libretime#1104]
**Is your feature request related to a problem? Please describe.**
Not really.

**Describe the solution you'd like**
I would like to have the possibility of grouping the elements of the library by album, artist, etc .. in order to better manage the library

**Describe alternatives you've considered**
I have considered the alternative of creating a new branch with this changes, I know how to do it, but I'd like to know if you guys have any proposal, idea..

**Additional context**
the idea is to keep the library more orderly and clean:

![Captura de pantalla 2020-11-07 a las 1 48 18](https://user-images.githubusercontent.com/1733884/98426952-5dc2cf80-209b-11eb-8cb1-ecfd31154b05.png)

**Comment by zklosko** [comment]
Does the "sort by Album" feature not do the trick?

Personally, I'd prefer you contribute the idea to our Libretime so we don't have a lot of splinted projects. Also, based on the screenshot, was that a mockup or did you get it working successfully? Screenshot looks great. 👍

**Comment by xabispacebiker** [comment]
The "sort by album" functionality does not fulfill at all. The grouping feature would also allow us to use folding which I think would help visually a lot.

the screenshot is just a mockup though ;)

nyway, I have more urgent things to develop for libretime before I start with this one, I just wanted to drop the idea so that we can give it shape if we are finally interested

**Comment by zklosko** [comment]
It looked so good I thought it was real! Got really excited for a second.

What are some of your more urgent ideas? Love to help/unofficially managing the site/documentation.
