### ISSUE TITLE
Proposal: Remove unworking features from Libretime

### ISSUE THREAD

**Issue by zklosko** [LibreTime/libretime#1108]
Hi everyone. This is never a fun thing to bring up regarding something you're passionate about, but I think it's time to "trim the fat", so to speak. Libretime currently has a handful of features that either don't work, aren't integrated well, or are better served by 3rd party software/SaaS solutions that could add complexity if we were to embed them into a Libretime install. I think they should be removed to help us close out the 3.0 Release Blocker, but everything is certainly open to discussion, which I was hoping for from this post.

Here's a list to get us started:

- Publishing to My Podcast or Soundcloud: currently doesn't work (#1061 #1043 #1042)
- Hosting a podcast from Libretime (My Podcast): doesn't work by extension of broken publishing command, but a number of better options exist, including Bluberry for Wordpress and Anchor.fm. Add a download button to the interface for easy file retrieval?
- Microsite: kinda disappointing for what it is, and not helpful for stations not exposing Libretime to the outside internet. I'd like to suggest we replace the microsite with a customizable login form and focus on widget development for HTML5 and Wordpress. (#1060 #1094 https://github.com/LibreTime/libretime/issues/249#issuecomment-620260712)
- Reset Password function: We don't have an integrated sendmail server or docs on how to set one up; would still require use of an SMTP mail provider. I suggest we remove said form and add to login form: "Forgot your password? Contact your system administrator." (#724)
- ~Stream statistics: Cool function, but requires Piwik (now Matomo) which needs a custom setup and a MySQL database. If we aren't going to integrate Matomo into the install, why not add a place for code from an Analytics SaaS to be pasted to track stats externally? (See https://github.com/LibreTime/libretime/issues/196#issuecomment-450668733)~
- Red logout button in menu: we already have a logout link in the upper right corner of the UI, no need for a second. Fixing in #1101.

**Comment by Robbt** [comment]
I agree with most of this. At least removing the Podcast stuff.

Stream Statistics does work without additional software. You can just do additional stream analysis with Matomo by exporting your icecast logs.

**Comment by zklosko** [comment]
@Robbt Ah, I stand corrected. I'll have to add that to the docs.

**Comment by paddatrapper** [comment]
I think this is a good idea, though adding better docs on email and the required config flags may be trivial enough to do that instead of removing the reset password logic. Could be wrong though, I don't know PHP very well

**Comment by zklosko** [comment]
I'm not too familiar with it either. Would it be hard to embed a Captcha password reset mechanism?

**Comment by hairmare** [comment]
I gave removing Soundcloud a go here: #1158 

I we also end up removing Podcast publishing completely then we could also get rid of `airtime-celery` completely. There has been some interest in the feature though. OTOH I don't think that fixing it is all that viable since there are most likely issues in the celery stuff anyway.

**Comment by paddatrapper** [comment]
> Edit: @paddatrapper, wouldn't they need an SMTP host? Would it be foolish to assume everyone has access to one?

No, you could use something like sendgrid or gmail

**Comment by zklosko** [comment]
I'm going to argue that our clientele is likely not going to want to integrate additional external services. I think if we can come up with some kind of captcha password reset option that would be best.

**Comment by paddatrapper** [comment]
That would still require sending them an email. We need some out of band way of sending them an email reset token. That can't be done by a captcha verifying that they aren't a bot
