### ISSUE TITLE
LibreTime support for Ubuntu 20.04 LTS (Focal Fossa)

### ISSUE THREAD

**Issue by valerio-bozzolan** [LibreTime/libretime#1109]
At the time of writing the LibreTime's installer supports Ubuntu 18.04 (Bionic Beaver) but not Ubuntu 20.04 LTS (Focal Fossa).

About Ubuntu 20.04 LTS (Focal Fossa): this is the latest long-term supported Ubuntu distribution and it will have official support for 5 years until April 2025.

This issue is about landing to this new distribution (where _new_ means 7 months ago at the time of writing).

## What to do

1. [ ] Try Propel v.2 and fix migration issues
2. [ ] package Liquidsoap in Ubuntu (bonus point!)

The issues with 20.04 are listed here: #1024.

## Notes

Another reason is that Liquidsoap and its plugins are not in Ubuntu's official repositories. This is maybe caused by lack of support of these packages since Debian GNU/Linux 10 (buster). The Liquidsoap's plugins were dropped since Debian GNU/Linux 9 (stretch):

* https://packages.debian.org/jessie/liquidsoap-plugin-gstreamer (Debian 8: OK)
* https://packages.debian.org/stretch/liquidsoap-plugin-gstreamer (Debian 9: OK)
* https://packages.debian.org/buster/liquidsoap-plugin-gstreamer (Debian 10: missing)

Anyway I think we can overcome this lack and we may be able to land on Ubuntu 20.20 LTS (Focal Fossa) before 2025.

**Comment by paddatrapper** [comment]
The issues with 20.04 are listed here: #1024. The biggest problem is PHP 7.4 in 20.04, which Propel (which we use for database stuff) doesn't support. We need to migrate to Propel v2 to fix that

**Comment by zklosko** [comment]
What if we moved towards a NoSQL database, like CouchDB or MongoDB? I'm not too familiar with MongoDB, but I've been poking around in CouchDB and it uses API calls and JSON for pretty much all database operations.

**Comment by valerio-bozzolan** [comment]
This is still strategic until 2025. No need to close.

**Comment by paddatrapper** [comment]
I've pinned it so that it doesn't get marked as stale
