### ISSUE TITLE
feature-request: add cloning function in smart blocks/playlists

### ISSUE THREAD

**Issue by korotkov13** [LibreTime/libretime#112]
when I click on the Smart block, pops up only 2 options: preview and remove. It would be nice to add a feature copy/cloning. 
For example I have a smart block with certain parameters and duration 1-hour, I need the same block, but the duration of 30 minutes. Now to make it, I need to manually re-fill all parameters.

**Comment by Robbt** [comment]
Great idea, this should make the creation of these blocks less tedious.

**Comment by korotkov13** [comment]
I found in last release, that you added "Duplicate playlist" function in Playlists.
Can't wait to try it with smart blocks  :raised_hands:

**Comment by Robbt** [comment]
This has been added in a PR. It doesn't copy the track contents of static smartblocks, only the criteria. Let me know if you think it would be useful to copy the tracks for static smartblocks as well.

**Comment by Robbt** [comment]
This has been committed.

**Comment by korotkov13** [comment]
just saw about it. will check it today in a few hours.
Thanks!!!

**Comment by korotkov13** [comment]
@Robbt I upgraded updated version, but it is not work. 
It shows in context menu, but nothing happens when i click "duplicate"

**Comment by korotkov13** [comment]
I will try to check it on clean system.

**Comment by Robbt** [comment]
Ok, weird. Can you check the /var/log/airtime/zendphp.log and see if you notice any errors.
