### ISSUE TITLE
Bug: Looming Rate Limit on Travis-CI

### ISSUE THREAD

**Issue by hairmare** [LibreTime/libretime#1123]
**Describe the bug**
We will most likely be affected by [travis-ci only offering a limited free tier](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing) going forward.

**To Reproduce**
1. Use travis-ci with the new free tier for a bit
2. Run into limit
3. Be frustrated

**Expected behavior**
Not to run into rate limiting when contributing to LibreTime.

**LibreTime version:**
CI/CD related.

**Additional context**
Travis recently introduced these limits.

IMHO the obvious solution is a refactor towards using [GitHub Actions](https://github.com/features/actions).

I put the 3.0-release-blocker tag on this since we don't have a generic release blocker label and I'd like to get this fixed before we do the next alpha or beta point release.

**Related**
* #1112 (ooff, I didn't even realize)

**Comment by paddatrapper** [comment]
+1 for Github actions. They also run much more quickly, so we can get feedback without waiting the 24hra or so that Travis takes to run.

**Comment by Robbt** [comment]
Sounds like a good plan to me.

**Comment by zklosko** [comment]
It turns out Github Actions' free plan isn't much better than Travis's. It might actually be worse: https://docs.github.com/en/free-pro-team@latest/github/getting-started-with-github/githubs-products.

**Comment by paddatrapper** [comment]
That document says 2000 action minutes for an organisation, which is double the 1000 for travis (as I understand it). The major advantage I see is the faster run times

**Comment by zklosko** [comment]
Ah, okay. I see now.
