### ISSUE TITLE
Proposal: Rewrite our installer in Python

### ISSUE THREAD

**Issue by zklosko** [LibreTime/libretime#1134]
**Describe the solution you'd like**
It would be cool to rewrite our installer in Python. Snapcraft has a [guide for packaging snaps coded in Python](https://snapcraft.io/docs/python-apps), and so we could make a utility that installs, uninstalls, and backs up a Libretime instance. This could be an easy way for us to get into the Snap store. A nice bonus is snaps can be compiled from Github repos, improving our CI/CD process.

It would also be nice if all of the configuration could be done in the installer as well (taking in the information from the onboarding screens, as well as executing the proper commands to change passwords, start services, etc.) so users complete the install process and then don't need to touch a command line again.

**Describe alternatives you've considered**
I haven't considered any other alternitives or done any research on Flatpack or other packaging types for Linux. I know many people don't like snaps, maybe because Canonical is kinda the Apple of the Linux world? It also might make it more difficult to install Libretime from the source code.

**Comment by Robbt** [comment]
I'm not a big fan of snaps and supporting them exclusively would likely make LibreTime only run on Ubuntu. On the otherhand if this was added as an additional installation option it could make it easier for people to get LibreTime up and running.

I think that the multi-docker container installation could also use some attention as that is another route that people like to do. I suspect that Flatpack and the other image based installers such as AppImage are not really designed for the sort of software that LibreTime is. Based upon my understanding they're primarily designed around single purpose applications vs. something like LibreTime that is multiple services. I'm also not sure if snaps would be the ideal way of packaging LibreTime but it may be worthy of investigation.

**Comment by hairmare** [comment]
Wouldn't `.deb`/`.rpm` files also replace the installer? The main issue I've had wrt Snapcraft is that it is way to hard to disable their auto-update mechanism. For a 24x7 broadcast system this doesn't seem very sensible.

**Comment by zklosko** [comment]
You both make good points, but I'm just thinking from the perspective of the installer, which would run scripts to create a Libretime instance. When the Snap would update, it would only update the utility, not the instance. Snaps can also be installed on Debian, Fedora, and Raspberry Pi OS.

**Comment by paddatrapper** [comment]
I think the issue of background daemons is there with snaps. If you can run multiple services in a single snap, then great. It would be a nice way to support install on pretty much any distro. I don't think it should bee our only method of install though. 

Currently I think PPA is the easiest way of installing LT, but for it to be effective we need to have more frequent releases. There are lots of important changes in master at the moment that aren't in alpha.8

Some more musings about snap packaging for LT: https://github.com/LibreTime/libretime-debian-packaging/issues/3
