### ISSUE TITLE
Error while changing webserver port

### ISSUE THREAD

**Issue by samkitk** [LibreTime/libretime#1143]
**Describe the bug**
Upon changing the webserver port in the web-setup (fresh install on a fresh Ubuntu 18.04 LTS), all kinds of settings go haywire. Liquidsoap stops working, the webpage (home index page) waits for connection from 127.0.0.1 for stream airtime_128 and more.

**To Reproduce**
Fresh Install using libretime.org/install

Change the webserver port to other port than (80 or 443) while web-setup is initiated.

**Expected behavior**
Expected it to work fine, since I changed the base_port variable, but it did not.

**LibreTime version:**
Version from the upgrade popup if you can reach it.

**Installation method:**
 - OS: [Ubuntu]
 - OS Version [18.04.5 LTS] 
 - Method: [sudo bash install -fiap]
 - Details: [Details on website]

**Comment by paddatrapper** [comment]
Did you change the Web port during the install too?

**Comment by samkitk** [comment]
Yes.

During the web setup install. (Fresh install where you connect with
database and enter your music directory storage path etc)

**Comment by paddatrapper** [comment]
I mean before that, in the ./install call

**Comment by samkitk** [comment]
No, not during then. No changes done. Absolutely followed what the instructions outlined on the website.

**Comment by paddatrapper** [comment]
Then the probably is there. Off the top of my head, at least the Apache config needs updating with the new port and add `Listen $port` at the top of the apache file.

Also are you trying to change the Icecast port or the webserver?

**Comment by samkitk** [comment]
Nope, I think I will have to ask apache to liste port, will get back to you once if I try.
