### ISSUE TITLE
Error in airtime-liquidsoap script (probably a python dependency)

### ISSUE THREAD

**Issue by samkitk** [LibreTime/libretime#1146]
Jan 01 22:11:52 radio airtime-liquidsoap 2021/01/01 22:11:52 [cue_cut_5777:3] Cueing in...
Jan 01 22:11:52 radio airtime-liquidsoap 2021/01/01 22:11:52 [cue_cut_5777:3] Cueing in...
Jan 01 22:11:52 radio airtime-liquidsoap 2021/01/01 22:11:52 [amplify_5781:3] Overriding amplification: 0.387258.
Jan 01 22:11:52 radio airtime-liquidsoap 2021/01/01 22:11:52 [amplify_5781:3] Overriding amplification: 0.387258.
Jan 01 22:11:52 radio airtime-liquidsoap 2021/01/01 22:11:52 [lang:3] timeout --signal=KILL 45 pyponotify --media-id=450 &
Jan 01 22:11:52 radio airtime-liquidsoap 2021/01/01 22:11:52 [lang:3] timeout --signal=KILL 45 pyponotify --media-id=450 &
Jan 01 22:11:52 radio airtime-liquidsoap 2021/01/01 22:11:52 [lang:3] Using stream_format 0
Jan 01 22:11:52 radio airtime-liquidsoap 2021/01/01 22:11:52 [lang:3] Using stream_format 0
Jan 01 22:11:52 radio airtime-liquidsoap message repeated 2 times: [ 2021/01/01 22:11:52 [lang:3] Using stream_format 0]
Jan 01 22:11:52 radio airtime-liquidsoap Traceback (most recent call last):
Jan 01 22:11:52 radio airtime-liquidsoap   File "/usr/bin/pyponotify", line 4, in <module>
Jan 01 22:11:52 radio airtime-liquidsoap     __import__('pkg_resources').run_script('airtime-playout==1.0', 'pyponotify')
Jan 01 22:11:52 radio airtime-liquidsoap   File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3238, in <module>
Jan 01 22:11:52 radio airtime-liquidsoap     @_call_aside
Jan 01 22:11:52 radio airtime-liquidsoap   File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3222, in _call_aside
Jan 01 22:11:52 radio airtime-liquidsoap     f(*args, **kwargs)
Jan 01 22:11:52 radio airtime-liquidsoap   File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3251, in _initialize_master_working_set
Jan 01 22:11:52 radio airtime-liquidsoap     working_set = WorkingSet._build_master()
Jan 01 22:11:52 radio airtime-liquidsoap   File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 567, in _build_master
Jan 01 22:11:52 radio airtime-liquidsoap     ws.require(__requires__)
Jan 01 22:11:52 radio airtime-liquidsoap   File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 884, in require
Jan 01 22:11:52 radio airtime-liquidsoap     needed = self.resolve(parse_requirements(requirements))
Jan 01 22:11:52 radio airtime-liquidsoap   File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 770, in resolve
Jan 01 22:11:52 radio airtime-liquidsoap     raise DistributionNotFound(req, requirers)
Jan 01 22:11:52 radio airtime-liquidsoap pkg_resources.DistributionNotFound: The 'defusedxml' distribution was not found and is required by airtime-playout
Jan 01 22:11:52 radio airtime-liquidsoap message repeated 2 times: [ 2021/01/01 22:11:52 [lang:3] Using stream_format 0]
Jan 01 22:11:52 radio airtime-liquidsoap Traceback (most recent call last):
Jan 01 22:11:52 radio airtime-liquidsoap   File "/usr/bin/pyponotify", line 4, in <module>
Jan 01 22:11:52 radio airtime-liquidsoap     __import__('pkg_resources').run_script('airtime-playout==1.0', 'pyponotify')
Jan 01 22:11:52 radio airtime-liquidsoap   File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3238, in <module>
Jan 01 22:11:52 radio airtime-liquidsoap     @_call_aside
Jan 01 22:11:52 radio airtime-liquidsoap   File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3222, in _call_aside
Jan 01 22:11:52 radio airtime-liquidsoap     f(*args, **kwargs)
Jan 01 22:11:52 radio airtime-liquidsoap   File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3251, in _initialize_master_working_set
Jan 01 22:11:52 radio airtime-liquidsoap     working_set = WorkingSet._build_master()
Jan 01 22:11:52 radio airtime-liquidsoap   File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 567, in _build_master
Jan 01 22:11:52 radio airtime-liquidsoap     ws.require(__requires__)
Jan 01 22:11:52 radio airtime-liquidsoap   File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 884, in require
Jan 01 22:11:52 radio airtime-liquidsoap     needed = self.resolve(parse_requirements(requirements))
Jan 01 22:11:52 radio airtime-liquidsoap   File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 770, in resolve
Jan 01 22:11:52 radio airtime-liquidsoap     raise DistributionNotFound(req, requirers)
Jan 01 22:11:52 radio airtime-liquidsoap **pkg_resources.DistributionNotFound: The 'defusedxml' distribution was not found and is required by airtime-playout**

**Comment by paddatrapper** [comment]
We need more details: 

**Installation method:**
 - OS: [e.g. Ubuntu]
 - OS Version [e.g. 16.04.5 LTS (Xenial Xerus)] 
 - Method: [e.g. `./install` script or packages]
 - Details: [how did you call the install script, where did you get packages from]
