### ISSUE TITLE
Scheduller won't show up

### ISSUE THREAD

**Issue by Luisce61** [LibreTime/libretime#1151]
**Describe the bug**
I Have been using Libretime for a few number of months without any issue at all. However as from yesterday I am unable to enter into the calendar (scheduller) page. 
I am just wondering if it has something to be with the change of year as no other changes have happened in my machine at all and just last Monday I was able to do it

**To Reproduce**
1. Go to 'calendar' 

**Expected behavior*
A new page open with all the schedules 

**LibreTime version:*
Cf84f82ea

**Installation method:**
 - OS: Ubuntu server 
 - OS Version 18.04
 - Method: [e.g. `./install script (I believe, just following the instructions on web
 - Details: as above

**Screenshots**

**Client (please complete the following information if applicable):**
 - OS: [e.g. Fedora]

**Additional context**

**Comment by paddatrapper** [comment]
Are there any relevant lines in the Zend log in /var/log/airtime/?

**Comment by zklosko** [comment]
I want to jump in and say I found a file that might give us a Y2KXX situation...

```
$this->view->headScript()->appendFile($baseUrl.'js/libs/moment-timezone-with-data-2010-2020.min.js?'.$CC_CONFIG['airtime_version'], 'text/javascript');
```

**Comment by paddatrapper** [comment]
That is now merged, so does this still happen on master?
