### ISSUE TITLE
Release 3.0.0-alpha.9

### ISSUE THREAD

**Issue by hairmare** [LibreTime/libretime#1155]
**Is your feature request related to a problem? Please describe.**
We haven't tagged anything since almost a year.

**Describe the solution you'd like**
Before we start merging the new api (#958) and all the vue stuff (#1122, #1150), I'd like to tag 3.0.0-alpha.9.

**Describe alternatives you've considered**
Tag after merging the api and starting with vue.

**Additional context**
As per https://github.com/LibreTime/libretime/pull/1144#discussion_r551198278 this will also help us with getting things like removing legacy systemd units going.

I'm almost done with writing the release notes and did quite a alot of testing recently. Most of my recent work was on a dev branch, but I've now switched to doing acceptance tests on master.

I think there is more than enough content on master to warrant a release and initial tests are looking like the tag would be mostly stable.

Did I miss any blockers for a soonish release? IMHO most open pull requests right now aren't blockers for alpha.9 and we'd be dropping quite a few features.

**Comment by paddatrapper** [comment]
I can't think of anything off the top of my head. Can also work on some testing

**Comment by zklosko** [comment]
#1150 has been changed to cleaning up and removing the libraries that no longer work and also removing TableTools in whole. I hope it can be considered before a 3.0.0-alpha-9 release.

**Comment by hairmare** [comment]
@zklosko including #1150 seems more than reasonable, I'm not sure about the one Ubuntu specific change to `./install` though (as noted in a comment review). I'll get it tested and merged tomorrow.

**Comment by paddatrapper** [comment]
Milestone: https://github.com/LibreTime/libretime/milestone/11

I'll go through and see if there is anything missing from that

**Comment by zklosko** [comment]
Can #1144 be added?

**Comment by paddatrapper** [comment]
Sure, what is your reasoning behind wanting it added?

**Comment by zklosko** [comment]
It looks basically done 🤷

**Comment by hairmare** [comment]
I was able to run "long-term" tests over the weekend and plan on tagging this evening after I finalize the contributor list in the releasenotes.

**Comment by hairmare** [comment]
I tagged the release and am currently waiting for travis to push the enriched tarball. If travis fails to push the tarball I am also preparing to push a local build if needed.
