### ISSUE TITLE
Add Crossfade from AutoDJ to Live Source

### ISSUE THREAD

**Issue by scysys** [LibreTime/libretime#1171]
**Describe the solution you'd like**
Actually when going live, program is ending to fast. It would be great if we can have a crossfade between autodj to live and live to autodj.

**Comment by paddatrapper** [comment]
You can do this by setting the crossfade option in the stream settings https://libretime.org/docs/settings#input-stream-settings

**Comment by scysys** [comment]
Ok thanks.
