### ISSUE TITLE
older played shows are not replaced automatically by the newest one

### ISSUE THREAD

**Issue by klaus13** [LibreTime/libretime#1177]
**Describe the bug**

Hello, it may be the same problem as #1176. To be sure, I have tried several different filters.
1. smart blocks, Track Type, is, XYZ. Advanced Options, Type Dynamic, Allow last track to exceed time limit: Yes, Sort Tracks: Newest, Preview: The last uploaded file (show) is displayed correctly !
This Smart Block is integrated into the playlist XYZ. As the exact playback time is somewhat delayed, another Smart Block with instrumental music is added to the same playlist XYZ to be on the safe side. 
3. In the calendar, this playlist XYZ is integrated into the show XYZ, Autoloading Playlist: Add Autoloading Playlist, Select Autoloading Playlist: XYZ, + update show. 
In reality, however, the old show remains in the calendar and is not replaced by the newer show for playback. It plays still the old show. I have to clear the shows manually in the calendar before the newest show can replace it !

I tried the same procedure with Album as the filter criterion. 
The result is exactly the same. So it is not due to the track type. 
The shows that have already been played remain loaded and are not replaced by the newer ones.

I hope this helps to localise the error. Many thanks for your help.

**LibreTime version:**
Version from the upgrade popup if you can reach it.

**Installation method:**
 - OS: [e.g. Ubuntu] OS **Xubuntu 18.04**
 - Libretime updated with latest Master the 13.02.2021
 - Method: **cd libretime, sudo git pull, sudo ./install**
 - Details: Executed as sudo ! all goes without difficulty to the end.

**Screenshots**
![00_NowPlayingShowCapture d’écran_2021-02-15_10-43-09](https://user-images.githubusercontent.com/20522347/107931375-7127e580-6f7c-11eb-9294-eeb411f61584.png)
![01_SmartBlock_BDJ_Capture d’écran_2021-02-15_10-47-12](https://user-images.githubusercontent.com/20522347/107931386-75ec9980-6f7c-11eb-8b4c-b6c09d8b6746.png)
![02Playlist_BDJ_Capture d’écran_2021-02-15_10-48-18](https://user-images.githubusercontent.com/20522347/107931398-79802080-6f7c-11eb-9623-9e051d918319.png)
![03AutoloadingPlaylist_Capture d’écran_2021-02-15_10-50-01](https://user-images.githubusercontent.com/20522347/107931414-7c7b1100-6f7c-11eb-99d2-97279f8005b9.png)
![04LastUploadedShow_Capture d’écran_2021-02-15_10-45-30](https://user-images.githubusercontent.com/20522347/107931417-7edd6b00-6f7c-11eb-9490-28b057ba661d.png)

**Client (please complete the following information if applicable):**
 - OS: Xubuntu 18.04
 - Browser Firefox 85.01

**Additional context**
The last Update of Libretime Master don't resolve this issue

**Comment by paddatrapper** [comment]
Yeah, this sounds very much like the issue is caching. How long is there between when the new content is added and the show beings?

**Comment by klaus13** [comment]
The new contend was uploaded the 2021:02:12, 2 days before.
