### ISSUE TITLE
Every Weekend, the stream goes silent!

### ISSUE THREAD

**Issue by CrimsonGhost138** [libretime/libretime#1183]
Every 7 days, to be more precise: In the night from saturday to sunday, at around 3-6am CET, the stream goes silent. The audio disapears. It stays silent until i just go to settings and Restart the stream. it is instantly working after the re-connect.

I tried to restart the whole server at tuesday, to see if the problem "wanders" from saturday night to tuesday night, but it stays "locked" on saturday, like there is some script programmed to mute the audio signal coming through every saturday night?! Because you can still see the tracks playing on Icecast but cannot hear no audio. 

Any ideas where to start to get rid of this?

Thanks alot, any input welcome! we have this problem since we started with LibreTime, so for 3 months now :(

**Comment by paddatrapper** [comment]
Try swap out the icecast server perhaps? Try to narrow down if it is icecast or libretime
