### ISSUE TITLE
Nginx suport

### ISSUE THREAD

**Issue by AnonymousWebHacker** [libretime/libretime#1186]
I would like you to give it support for nginx

**Comment by jooola** [comment]
@paddatrapper We should pin this one

**Comment by AnonymousWebHacker** [comment]
In the end, I used free me for a while, I got to configure with nginx and everything was perfect. Only libetime gave some errors and I have not used it anymore. If I see my nginx conf, I'll post it here

**Comment by jooola** [comment]
@AnonymousWebHacker Would you mind posting your nginx/php-fpm config here ?

**Comment by AnonymousWebHacker** [comment]
@jooola I stopped using that server and ended up deleting it, but with pleasure I can make you a configuration and publish it here

**Comment by jooola** [comment]
@paddatrapper What about we slowly make using nginx the default ?

We will probably need it for the docker setup, I can start experimenting deploying it using the ansible role, and we can use apache2 in the installer until we are confident about the swap.

The apache config will always be available for those who want to use apache, but I feel it should make #1637 easier.

**Comment by paddatrapper** [comment]
Sounds good. I end up placing LibreTime behind an Nginx reverse-proxy anyway and am much more familiar with Nginx in general than Apache.

**Comment by AnonymousWebHacker** [comment]
> @AnonymousWebHacker Would you mind posting your nginx/php-fpm config here ?

I no longer use libretime for a long time, but I remember that in the end the installation was left at http://ip-server:8090 (for example, I don't even remember the ports XD )

You can do a redirect, (a reverse proxy) using nginx.
You just listen to port 80 and 443 (ssl) and forward it to the server

```
server {
    listen 80;
    listen [::]:80;
    server_name stream.domain.com;

    return 301 https://$server_name$request_uri;

    location / {
        proxy_pass http://localhost:8090;
    }

    proxy_set_header X-Real-IP $remote_addr;
}

server {

        listen 443 ssl;
        listen [::]:443 ssl;

        server_name stream.domain.com;
        client_max_body_size 100M;

        # Certificates for ssl, you can use certbot ..etc
        ssl_certificate          /etc/letsencrypt/live/stream.domain.com/fullchain.pem;
        ssl_certificate_key      /etc/letsencrypt/live/stream.domain.com/privkey.pem;
        ssl_trusted_certificate  /etc/letsencrypt/live/stream.domain.com/chain.pem;

        proxy_read_timeout 720s;
        proxy_connect_timeout 720s;
        proxy_send_timeout 720s;

        # Proxy headers
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;

        location / {
                proxy_redirect off;
                proxy_pass http://localhost:8090;
        }
}
```

**Comment by jooola** [comment]
@paddatrapper Should replace apache with nginx and leave users configure apache manually if want to keep it ? Or should we provide both in the installer ?

I feel like swaping from apache to nginx is a big move, but I don't know if its smart trying to maintain both in the installer. If we choose nginx as default webserver I think I would go all the way in.

An alternative is to find the right apache configuration so we can run php-fpm with both nginx and apache which makes it inter changable.

**Comment by jooola** [comment]
I also think that using php-fpm will reduce the differences between the install script and the docker setup.
