### ISSUE TITLE
Debian Buster pycairo install failed

### ISSUE THREAD

**Issue by stanlog** [LibreTime/libretime#1191]
**Describe the bug**
Error on Pycairo install during LibreTime install:
`Writing /tmp/easy_install-ya5mh8e_/pycairo-1.19.1/setup.cfg
Running pycairo-1.19.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-ya5mh8e_/pycairo-1.19.1/egg-dist-tmp-4yid3dt9
no previously-included directories found matching 'docs/_build'
warning: no files found matching 'README' under directory 'tests'
warning: no files found matching 'README' under directory 'examples'
cairo/device.c:30:10: fatal error: Python.h: Aucun fichier ou dossier de ce type
 #include <Python.h>
          ^~~~~~~~~~
compilation terminated.
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1`

**To Reproduce**
Launch install
`sudo bash install -fiap`

**Expected behavior**
We need install python3-dev before launching installation. After installing python3-dev, no more error. Maybe add it in the pkg list in the script ?

**LibreTime version:**
3.0.0-alpha.9

**Installation method:**
 - OS: Debian
 - OS Version: 10
 - Method: install script from git
 - Details: sudo bash install -fiap

**Comment by cr3pt** [comment]
Install **python3-cairo-dev**
