### ISSUE TITLE
Update release

### ISSUE THREAD

**Issue by undoablemixlr** [LibreTime/libretime#1192]
hello,

I would like to update the version of LebreTime 0f7fbf1d5. The link to the documentation is no longer accessible!
 I would like to have a tutorial to do this!

Thanks in advance !

Syl.

**Comment by paddatrapper** [comment]
Use release 3.0.0-alpha.9? https://github.com/LibreTime/libretime/releases/tag/3.0.0-alpha.9

**Comment by paddatrapper** [comment]
https://libretime.org/docs/upgrading
