### ISSUE TITLE
Webstream playback cut off

### ISSUE THREAD

**Issue by rjhelms** [libretime/libretime#1197]
From further troubleshooting, the conditions and reproduction steps as listed below are *not* the only circumstances where this occurs. So far, only unifying factor seems to be playing a webstream.

**Describe the bug**
Under certain circumstances, when the web stream is playing in two consecutive shows, Libretime will prematurely stop playback and go offline despite having scheduled programming.

The conditions for this to happen seem to be as follows:

- show 1 has a webstream, which overflows the duration of the show by some amount
- show 2, immediately following, contains the same webstream
- the instance of the webstream in show 2 begins *before* the time that the instance in show 1 would have ended

This potentially is dependent on the metadata coming from the webstream - I had initially suspected this was the cause of the issue but I am no longer confident in that assumption:
- by the time that the instance in show 1 would have ended, the title coming from the webstream has not changed

It seems like pypofetch "thinks" that the it is still the instance from show 1 that is playing, and stops playback - leaving the station offline until either `POLL_INTERVAL` next elapses (8 minutes by default?) or the next scheduled item occurs.

One solution to avoid this would be to have the duration of the webstream in each show *exactly* fill the duration of the show, but there seems to be no way to accomplish this.

**To Reproduce**
1. Schedule two consecutive shows, both containing some content at the top of the show, and then a webstream w/ duration such that it is slightly longer than the show and will be cutoff
2. The content in the 2nd show at the top of the hour should be shorter than in the first
3. Ensure that title coming from webstream does not change at top of hour **(may not be related!)**
4. Note how long "overhang" in first show is.
5. Playback of second show cuts off at the "overhang" time.
6. Libretime UI shows "offline", but that stream should still be playing.
7. Libretime output is silence, title "Libretime - Offline".

**Expected behavior**
Playback in a show is never affected by content from previous show.

**LibreTime version:**
2bed9d99a (this is the branch for pull request #1161 - otherwise up to date with master at time of reporting)

**Installation method:**
 - OS: Ubuntu
 - OS Version 18.04.05 LTS Bionic Beaver
 - Method: `./install -fiap`
 - Details: Cloned github repo, invoked installer

**Additional context**

We are using this functionality to simulcast a webstream during "off hours" for a community radio station.  To achieve this, we have a playlist that consists of the following:

- a smartblock, to play 1 station ID chosen randomly
- potentially one or more short PSA clips (currently manually added to playlist)
- the webstream, with a default length of 1h00m to ensure it fills the hour.

This playlist is scheduled each hour, through the "autoload playlist" feature.

I initially thought this was because it was the exact same media item in Libretime, so tried with two of different lengths (50m and 10m) but that does not change behavior. It occurs even if two separate media items are used, that point to the same stream.

See attached excerpts from notify.log and pypo.log from when this recently occurred - timeline was as follows:

2021-04-28 14:51:29: instance of stream started in "show 1" - this is 10 minutes long per note above, so "would" end at 15:01:29
2021-04-28 14:56:31: title from stream changes to "Robert Stone - Some Clowns"
2021-04-28 15:00:00: stream playing gets cut off, to change to content from "show 2" playlist
2021-04-28 15:01:27: "show 2" returns to the stream - title is still "Robert Stone - Some Clowns"
2021-04-28 15:01:29: playback is cutoff. notify.log logs an `InvalidContentType` error (because nothing is playing, even though something is scheduled?)
2021-04-28 15:09:27: pypofetch queue timeout, playback resumes

It is a major issue to be broadcasting dead air for potentially up to 8 minutes!

[notify.log](https://github.com/LibreTime/libretime/files/6393457/notify.log)
[pypo.log](https://github.com/LibreTime/libretime/files/6393460/pypo.log)

**Comment by rjhelms** [comment]
One potential workaround would be to reduce POLL_INTERVAL to some absurdly small amount - eg single-digit value - to minimize off-air time, but I am concerned about performance (and log spam) with that case.

**Comment by rjhelms** [comment]
From further investigation, I am not certain that title staying the same is actually a necessary condition for this issue to occur.

**Comment by rjhelms** [comment]
Conditions / reproduction steps given in issue are not accurate. Working from theory that this was caused by webstream at end of a show, I rearranged things webstream only played for 55 minutes, with end of show being media files (again, chosen by smart blocks.)

Despite this, issue still occurs, albeit not consistently.

**Comment by jooola** [comment]
@rjhelms Have you tested this with a recent version of Libretime ? A lot has changed since the version you are currently running and I know they are a few fixes for similar cases.

The important log file would be the pypo-liquidsoap log file.
