### ISSUE TITLE
Install docs link does not work

### ISSUE THREAD

**Issue by narcisgarcia** [LibreTime/libretime#1198]
Here in this page:
https://github.com/LibreTime/libretime/releases
There is an "installation" chapter saying "The main installation docs may be found at..." and the link y bad formed:

1. The effective link goes to a 'not found' page at Github.com
2. The shown URL goes to a 'Sorry… there’s nothing there' page at libretime.org

**Comment by paddatrapper** [comment]
Thanks for picking this up, I have fixed the link. Should point to https://libretime.org/install
