### ISSUE TITLE
Problem: Password Reset does not work for station owners (aka super admins)

### ISSUE THREAD

**Issue by hairmare** [LibreTime/libretime#12]
This is not coupled to billing so it was not covered in #11. Since station owner users are managed by WHMCS the get to go to a special place to reset their password. On non SaaS deploys this is certainly not what we need, everyone including the owner should be able to reset their password.

Solution: Make the superadmin info on the Password Reset page configurable.

* [ ] ability to deactivate the text block on the page
* [ ] ensure that resetting works for super admins
* [ ] make the link that is shown when WHMCS is active configurable

**Comment by Robbt** [comment]
So there is a superadmin account separate from admin I'm presuming ?

**Comment by hairmare** [comment]
The WHMCS superadmin stuff was disabled by #11 for the most part, what remains is the text block on the reset password page and maybe the form handler needs fixing to allow `admin` to reset as well.
