### ISSUE TITLE
Playlists, calendars, entries, users and all other data are no longer displayed

### ISSUE THREAD

**Issue by Michael5464** [libretime/libretime#1202]
On the start page Libretime and after login no more files and entries are displayed. Also all user data are no longer available. Libretime reports OffAir although the stream is online and sends the playlists. With another Porgrammananger is still all available. Two others have the same problem. 
Can this be a problem with the user rights ? I don't want to register a new user because the system works for others. Can someone help me?

**Comment by Robbt** [comment]
Do thinks work with the first superadmin user ?

What is the role of the user who is experiencing the problem ?

Have you tried refreshing the browser cache with shift refresh or logging in from a private/incognito window to make sure there isn't something weird with the caching going on.

**Comment by Michael5464** [comment]
Yes I work with the admin access.
The same error in the Incognito window.
What is striking is that I can't upload a file either. All displays are empty, no other users are listed. I think it is a problem with the programme or even directory rights.

Here is the status:
● libretime-liquidsoap.service - Libretime Liquidsoap Service
   Loaded: loaded (/etc/systemd/system/libretime-liquidsoap.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2021-03-17 12:33:42 CET; 1 months 17 days ago
 Main PID: 5818 (liquidsoap)
    Tasks: 9 (limit: 4915)
   CGroup: /system.slice/libretime-liquidsoap.service
           └─5818 airtime-liquidsoap /usr/local/lib/python3.6/dist-packages/airtime_playout-1.0-py3.6.egg/liquidsoap/1.1/ls_script.liq --verbose -f

Mai 04 23:29:03 malta1122 airtime-liquidsoap[5818]: 2021/05/04 23:29:03 [s4:3] Prepared "/var/tmp/airtime/pypo/cache/scheduler/832.mp3" (RID 4).
Mai 04 23:29:03 malta1122 airtime-liquidsoap[5818]: 2021/05/04 23:29:03 [amplify_5781:3] Overriding amplification: 0.333811.
Mai 04 23:29:03 malta1122 airtime-liquidsoap[5818]: 2021/05/04 23:29:03 [lang:3] timeout --signal=KILL 45 pyponotify --media-id=61589 &
Mai 04 23:29:03 malta1122 airtime-liquidsoap[5818]: 2021/05/04 23:29:03 [lang:3] Using stream_format 0
Mai 04 23:29:03 malta1122 airtime-liquidsoap[5818]: 2021/05/04 23:29:03 [lang:3] Using stream_format 0
Mai 04 23:29:03 malta1122 airtime-liquidsoap[5818]: 2021/05/04 23:29:03 [lang:3] Using stream_format 0
Mai 04 23:29:03 malta1122 airtime-liquidsoap[5818]: #########################################
Mai 04 23:29:03 malta1122 airtime-liquidsoap[5818]: #           *** pypo  ***               #
Mai 04 23:29:03 malta1122 airtime-liquidsoap[5818]: #     pypo notification gateway         #
Mai 04 23:29:03 malta1122 airtime-liquidsoap[5818]: #########################################

**Comment by Michael5464** [comment]
It is also interesting that the Libretime start page on the web does not show the calendar or the track being played. The player cannot be called up either. Only the login button is working. However, the stream is still ON, although Libretime shows it as OFF.

**Comment by Robbt** [comment]
Zenphp.log under /var/log/airtime will probably have more information. This is an issue with the web front-end it appears.
