### ISSUE TITLE
Web interface is cropped

### ISSUE THREAD

**Issue by PeGaSuS-Coder** [libretime/libretime#1204]
I'm facing this issue on a fresh ubuntu install, where the web install is basically impossible to be used because it's cropped:
![web interface cropped](https://user-images.githubusercontent.com/25697531/117578796-6058bd00-b0f0-11eb-901d-de713c09c97a.png)

**Comment by zklosko** [comment]
Can you tell us more the system you're using? It looks like your screen resolution might be too low.

**Comment by PeGaSuS-Coder** [comment]
__$ lsb_release -a__
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.10
Release:	20.10
Codename:	groovy
```

__Screen resolution__
![screen_resolution](https://user-images.githubusercontent.com/25697531/119272494-7d1fe500-bc06-11eb-98b6-4a028e6ab41a.png)

**Comment by paddatrapper** [comment]
I can replicate this issue on a 1080p display with 137.5% display scaling

**Comment by PeGaSuS-Coder** [comment]
I my case there was no font scaling. I just installed libertime in my VPS, and connected via my computer browser.

**Comment by paddatrapper** [comment]
20.04 is WIP, yeah: #1168
