### ISSUE TITLE
Add metrics/stats infrastructure

### ISSUE THREAD

**Issue by jooola** [libretime/libretime#1209]
I would like to propose to add tool to export and collect stats and metrics from the different services in order to have a good overview of how the setup is running.

My proposal is to ship Prometheus and implement exporters for each of our services.

For those who want some visualization, it could then be made using any client supporting Prometheus (mainly Grafana), or some self made charts (I would not recommend this).

This feature could be opt-in or opt-out, but I know such information has great value for those running a large station.

In addition such metrics could also report some performance regression/improvement over time.

I am willing to help out for such feature as I will need such thing in production anyway.

Any thoughts about this ?

**Comment by paddatrapper** [comment]
Having configured exporters would be nice. Opt-in for Prometheus would be good, as having an existing metric server is probably a fairly common use-case

**Comment by jooola** [comment]
Some resources: https://github.com/savonet/liquidsoap/pull/1235

**Comment by jooola** [comment]
So I've been thinking a bit about this, and drafted some ideas:
[![](https://mermaid.ink/img/eyJjb2RlIjoiZ3JhcGggVERcbiAgICBhbmFseXplcltBbmFseXplcl1cbiAgICBhcGlbQVBJXVxuICAgIGNvcmVbQ29yZV1cbiAgICBpY2VjYXN0W0ljZWNhc3RdXG4gICAgbGlxdWlkc29hcFtMaXF1aWRzb2FwXVxuICAgIHBsYXlvdXRbUGxheW91dF1cblxuICAgIHByb21ldGhldXNbUHJvbWV0aGV1c11cbiAgICBhbmFseXplciAtLT4gcHJvbWV0aGV1c1xuICAgIGFwaSAtLT4gcHJvbWV0aGV1c1xuICAgIGNvcmUgLS0-IHByb21ldGhldXNcbiAgICBpY2VjYXN0IC0tPiBwcm9tZXRoZXVzXG4gICAgbGlxdWlkc29hcCAtLT4gcHJvbWV0aGV1c1xuICAgIHBsYXlvdXQgLS0-IHByb21ldGhldXNcblxuICAgIGFsZXJ0bWFuYWdlcltBbGVydG1hbmFnZXJdXG4gICAgcHJvbWV0aGV1cyAtLT4gYWxlcnRtYW5hZ2VyXG5cbiAgICBhZG1pbltBZG1pbl1cbiAgICBhbGVydG1hbmFnZXIgLS0-IHxNYWlsfCBhZG1pblxuICAgIGFsZXJ0bWFuYWdlciAtLT4gfEhvb2tzfCBhZG1pbiIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In0sInVwZGF0ZUVkaXRvciI6ZmFsc2UsImF1dG9TeW5jIjp0cnVlLCJ1cGRhdGVEaWFncmFtIjpmYWxzZX0)](https://mermaid-js.github.io/mermaid-live-editor/edit##eyJjb2RlIjoiZ3JhcGggVERcbiAgICBhbmFseXplcltBbmFseXplcl1cbiAgICBhcGlbQVBJXVxuICAgIGNvcmVbQ29yZV1cbiAgICBpY2VjYXN0W0ljZWNhc3RdXG4gICAgbGlxdWlkc29hcFtMaXF1aWRzb2FwXVxuICAgIHBsYXlvdXRbUGxheW91dF1cblxuICAgIHByb21ldGhldXNbUHJvbWV0aGV1c11cbiAgICBhbmFseXplciAtLT4gcHJvbWV0aGV1c1xuICAgIGFwaSAtLT4gcHJvbWV0aGV1c1xuICAgIGNvcmUgLS0-IHByb21ldGhldXNcbiAgICBpY2VjYXN0IC0tPiBwcm9tZXRoZXVzXG4gICAgbGlxdWlkc29hcCAtLT4gcHJvbWV0aGV1c1xuICAgIHBsYXlvdXQgLS0-IHByb21ldGhldXNcblxuICAgIGFsZXJ0bWFuYWdlcltBbGVydG1hbmFnZXJdXG4gICAgcHJvbWV0aGV1cyAtLT4gYWxlcnRtYW5hZ2VyXG5cbiAgICBhZG1pbltBZG1pbl1cbiAgICBhbGVydGluZyAtLT4gfE1haWx8IGFkbWluXG4gICAgYWxlcnRpbmcgLS0-IHxIb29rc3wgYWRtaW4iLCJtZXJtYWlkIjoie1xuICBcInRoZW1lXCI6IFwiZGVmYXVsdFwiXG59IiwidXBkYXRlRWRpdG9yIjpmYWxzZSwiYXV0b1N5bmMiOnRydWUsInVwZGF0ZURpYWdyYW0iOmZhbHNlfQ)

But many things needs to be discussed:
- what metrics we collect for each service:
  - Icecast: Most stats from [icecast](https://icecast.org/docs/icecast-latest/server-stats.html) and volume mean over 10 seconds (detect silence on the very end of the chain).  
  - Analyzer: Stats around files analyzed, failed, processing time per file.
  - API: basic metrics around HTTP
  - Liquidsoap: ? (should this be merged with playout ?)
- always prometheus by default ? (opt-out)
- never install alertmanager (or alternative) by default ? (opt-in or extra setup required)

**Comment by paddatrapper** [comment]
>     Liquidsoap: ? (should this be merged with playout ?)

The useful stuff here would be things like number of connections to the Icecast input harbours, time connected, output stream status for all enabled output streams

I don't think we should install and configure Prometheus and Alertmanager by default, just because it is a lot to maintain going forward. But I'm not too strongly decided there
