### ISSUE TITLE
Rename and move apps in the libretime namespace

### ISSUE THREAD

**Issue by jooola** [LibreTime/libretime#1212]
I propose to rename the new api package to `libretime_api` instead of `libretimeapi`, for consistency with the other tools naming.

`api/libretimeapi/` => `api/libretime_api/`

In some far future, I would even think the python apps could be moved in the root folder.

**Comment by paddatrapper** [comment]
I'd actually recommend the opposite - to follow PEP8, underscores should only be added if it aids readability -https://www.python.org/dev/peps/pep-0008/#package-and-module-names

**Comment by jooola** [comment]
I feel it does improves readability. I would even go fir stripping all libretime/airtime prefixes. But consistency is somehow missing the naming of the packages.

```
libretimeapi        => libretime_api        => api
airtime-celery      => libretime_celery     => scheduler
airtime_analyzer    => libretime_analyzer   => analyzer
api_clients                                 => api_client
icecast2                                    => icecast2
pypo                                        => pypo
```

**Comment by jooola** [comment]
To follow some kind of naming convention, the apps will have to be renamed at some point. Putting libretime in the components name is a not a good idea as it doesn't make component clearer, and is way more verbose/confusing.

Having some kind of conventions will to help us manage the project more efficiently.

A good approach is to namespace our packages in a common name.

```
libretimeapi        => libretime.api
airtime-celery      => libretime.celery
airtime_analyzer    => libretime.analyzer
api_clients         => libretime.api_client
pypo                => libretime.playout
```
