### ISSUE TITLE
Lowercase github organisation name

### ISSUE THREAD

**Issue by jooola** [libretime/libretime#1216]
Some might laugh at me, but I would propose to lowercase the libretime github organization name:

from `https://github.com/LibreTime/libretime` to `https://github.com/libretime/libretime`

The few reasons:
- some ci tasks/services requires a lowercase name https://github.com/LibreTime/libretime/actions/runs/1190504235.
- consistency
- don't mix functional name and styled name.

**Comment by jooola** [comment]
Someone was against this change, but I can't remember who. @paddatrapper do you think we can solve this and move forward ?

**Comment by paddatrapper** [comment]
https://docs.github.com/en/organizations/managing-organization-settings/renaming-an-organization

Also need to update Weblate, as that fails when the org name doesn't match exactly

**Comment by jooola** [comment]
Most of the pain points in the documentation you mentioned, aren't applicable in our case. Both lowercased and styled urls work when accessing the repo on github.

**Comment by paddatrapper** [comment]
I'll try get to this in the next day or so

**Comment by paddatrapper** [comment]
I've renamed the org and updated Weblate
