### ISSUE TITLE
Provide contrib ansible roles 

### ISSUE THREAD

**Issue by jooola** [LibreTime/libretime#1217]
I would like to propose [Ansible](https://www.ansible.com/) for installing and configuring Libretime on systems. The install script seems to be working, but it is missing a proper framework to enhance the overall install/configuration experience and capabilities.

I was thinking at something similar to the gitlab [omnibus](https://docs.gitlab.com/omnibus/architecture/) installer.

This will also bring a way to test the installation process using some Ansible testing framework (molecule).

I don't know if it can be integrated in the future docker images building. Probably.

Any thoughts ?

**Comment by zklosko** [comment]
I love that idea but I wonder if our unwieldy list of requirements would get in the way. Each OS we support has a different list of requirements. Using Anisble would require it (and Python 3) to be preinstalled on the system before getting the other dependencies too, whereas a Bash script doesn't require a separate interpreter to be installed on 99% of Linux systems.

But I agree: the installer needs to be rewritten.

**Comment by jooola** [comment]
Python3 doesn't seem to be a problem, as we ship a lot of python apps anyway, and installing ansible in a venv is as simple as running `pip install ansible`.

So I don't think this should be a blocker.

**Comment by paddatrapper** [comment]
I think having an ansible role that we support would be good, but I don't think it should be the main installation route. My concern that ansible requires more setup than using the installation script. Personally I think an apt repo and deb should be the main installation route, but that needs more maintainers than just me to be practical (still haven't got alpha.9 into the PPA...)

**Comment by zklosko** [comment]
I agree with @paddatrapper. We could probably add the making of .deb packages to our CI/CD pipeline via. Github Actions, so every time we make a new release it'll automatically generate a package and upload it to Debian's repos.

I'm reading this about how to make a .deb package: https://www.sindastra.de/p/1684/how-to-make-a-basic-debian-and-ubuntu-package-deb-the-easy-way/. Do we need to do much more?

There's a Github Actions action already for dpkg-buildpackage: https://github.com/marketplace/actions/build-debian-package-buster.

**Comment by paddatrapper** [comment]
> I'm reading this about how to make a .deb package: https://www.sindastra.de/p/1684/how-to-make-a-basic-debian-and-ubuntu-package-deb-the-easy-way/. Do we need to do much more?

That is very wrong/outdated... We use [git-buildpackage](https://honk.sigxcpu.org/piki/projects/git-buildpackage/) to build our Debian packages in https://github.com/LibreTime/libretime-debian-packaging. Some documentation on how that works is [here](https://github.com/LibreTime/libretime-debian-packaging/issues/14#issuecomment-756136392).

We currently do not package into Debian, as we do not [policy](https://www.debian.org/doc/debian-policy/). We do however upload Ubuntu packages to the [PPA](https://launchpad.net/~libretime/+archive/ubuntu/libretime/). It requires GPG signed packages for uploading, so even just for that reason we couldn't go a Github Action for generating packages. There are also other reasons for having someone create the package and test it - there are changes that are required to keep up with Standards Version support (i.e. changes to Debian policy), copyright documentation changes, packaging script changes, etc.

**Comment by zklosko** [comment]
> It requires GPG signed packages for uploading, so even just for that reason we couldn't go with a Github Action for generating packages.

There has to be a way to import a GPG key as a Github Secret or something.

**Comment by paddatrapper** [comment]
Sure, but I don't want my GPG key to be publicly accessible, even if it is just to LT maintainers. I don't even keep a copy on my pc, just hard copy backups in a safe and a hardware key

**Comment by zklosko** [comment]
Could we get a secret key just for the project?

**Comment by jooola** [comment]
I am working on this and will soon have a MVP, the repo is here https://github.com/jooola/ansible-role-libretime .

**Comment by zklosko** [comment]
Is the goal to have Ansible for bare-metal and Docker for containers?

**Comment by jooola** [comment]
I'll leave folks willing to deploy libretime as docker stack with ansible write their own playbooks, as most of the installation process has been delegated to the docker image building anyway.

The ansible role will install on 'bare-metal' systems with systemd.

**Comment by jooola** [comment]
The role at https://github.com/jooola/ansible-role-libretime is now able too fully install libretime on bullseye and focal.

Closing this as resolved.

**Comment by paddatrapper** [comment]
Do we want to maintain that under the LibreTime namespace?

**Comment by jooola** [comment]
This would be great to make it somewhat official, yes. I would like to move it under the libretime namespace.

The role is quiet new though, and I might not want to comply to C4 yet. So unless this is a blocker I am happy to move the repo. Once the tool has reached some kind of maturity and a public large enough, development will start adopting a C4 workflow or similar.

**Comment by paddatrapper** [comment]
While I think following C4 is a good idea eventually, I don't see it as a blocker for having the role under the LT namespace. And really the only 2 C4 things that would be violated is the don't merge your own PR and everything happens via PR. The latter is more important when there is more than 1 developer working on the repo anyway and the former isn't really an issue unless the team is much larger.

**Comment by jooola** [comment]
Ok, in that can we can move the repo. I'll start the transfer.

**Comment by jooola** [comment]
Oh, how can we actually do the transfer, looks like I need to be able to create a repo in the org to do the transfer. This isn't the case. I though It would trigger a transfer request on your side.

Should I invite you to as admin, so you can transfer the repo ?

**Comment by paddatrapper** [comment]
Yeah, think that should work
