### ISSUE TITLE
Migrate analyzer tests to pytest

### ISSUE THREAD

**Issue by jooola** [LibreTime/libretime#1219]
In order to modernize and be able to easily modify the analyzer module, I propose to migrate the old noses test to pytest.

I am working on this right now. A PR should follow, but I am waiting for #1210 to be merged (formatting is a pain right now, couldn't branch from master).

Next, I'll try to add an extra analyzer that use ffmpeg to guess the silenced parts of a track. See https://github.com/LibreTime/libretime/issues/1214#issuecomment-850856541

**Comment by paddatrapper** [comment]
#1178 is the overarching issue tracking this

**Comment by jooola** [comment]
Right I forgot about this ticket.
