### ISSUE TITLE
Dashboard panes: Several "Learn about..." help links are pointing to a broken link for libretime docs

### ISSUE THREAD

**Issue by feizing** [libretime/libretime#1220]
The dashboard area presents a call-out linked to documentation on `libretime.org`. When clicking the link on certain dashboard panes, the link takes you to the website's 404 page ("DEAD AIR"). This appears to be caused by the trailing slash in the `href`.

**To Reproduce**
1. Navigate to the dashboard pane for one of the following: 
- Tracks (i.e. main dashboard pane when you click on Dashboard), 
- Playlists
- Smartblocks
- Webstreams
2. Click on the "Learn about..." hyperlink
3. See error

**Expected behavior**
Arrive to relevant `libretime.org` documentation page when clicking on link.

**LibreTime version:**
56b999aba

**Installation method:**
 - OS: Debian
 - OS Version: Buster 
 - Method: Vagrant dev install

**Screenshots**
![image](https://user-images.githubusercontent.com/10385275/120090161-31ad8100-c0b5-11eb-9abb-0c4c98026174.png)

**Client**
 - OS: Fedora 33
 - Browser: Brave/Chromium
 - Version 1.24.x

**Additional context**
Issue also referenced in [1101](https://github.com/LibreTime/libretime/pull/1101)

**Comment by jooola** [comment]
What about fixing this on both sides ?
I would recommend adding a redirection plugin on the website and also update any old links to use the new ones.

This could be used: https://github.com/jekyll/jekyll-redirect-from
