### ISSUE TITLE
Xenial EOL (Paid ESM) - May 2021

### ISSUE THREAD

**Issue by jooola** [LibreTime/libretime#1226]
Ubuntu 16.04 LTS ‘Xenial Xerus’ transitions into the extended security maintenance (ESM).

See https://ubuntu.com/blog/ubuntu-16-04-lts-transitions-to-extended-security-maintenance-esm

I don't know if we support distribution that are under a paid maintenance service. So I propose to drop support for Ubuntu 16.04.

This will raise the minimum python version to 3.7 I think, which is quiet good !

**Comment by paddatrapper** [comment]
Yeah, so ideally I'd like to land Ubuntu 20.04 support and drop 16.04 at the same time. The only potential issue with dropping 16.04 is that it then makes upgrading to LibreTime from Airtime difficult, potentially making #71 impossible

**Comment by paddatrapper** [comment]
The minimum Python version will be 3.6 - Ubuntu 18.04 ships with that

**Comment by jooola** [comment]
Ah missed that, my bad.

This issue is actually a major blocker. Most libraries dropped support for python3.5. For instance I have trouble with pip, the distro version is pip 8, and I had some trouble building some wheels with that version, and upgrade to pip >20 drops support for python 3.5.
It's possibly a mistake on my side, but we should test this in the CI, ubuntu 16.04 with python 3.5

**Comment by paddatrapper** [comment]
Nose has dropped support for 3.5, so we are unable to run our python test suite on 16.04

**Comment by paddatrapper** [comment]
Seems we are running into more issues with Python 3.5. Getting the following error when trying to create a 16.04 vagrant VM:

```
    ubuntu-xenial:  * Installing API client...
    ubuntu-xenial: python3 /vagrant/python_apps/api_clients/setup.py install --install-scripts=/usr/bin
    ubuntu-xenial: Traceback (most recent call last):
    ubuntu-xenial:   File "/vagrant/python_apps/api_clients/setup.py", line 7, in <module>
    ubuntu-xenial:     from setuptools import setup
    ubuntu-xenial:   File "/usr/local/lib/python3.5/dist-packages/setuptools/__init__.py", line 18, in <module>
    ubuntu-xenial:     from setuptools.dist import Distribution
    ubuntu-xenial:   File "/usr/local/lib/python3.5/dist-packages/setuptools/dist.py", line 585
    ubuntu-xenial:     license_files: Optional[List[str]] = self.metadata.license_files
    ubuntu-xenial:                  ^
    ubuntu-xenial: SyntaxError: invalid syntax
```

**Comment by jooola** [comment]
Is that the distribution setuptool package ?

**Comment by paddatrapper** [comment]
As far as I know, yes

**Comment by paddatrapper** [comment]
Ah no, we install setup tools from pip for some reason in`./install`

**Comment by jooola** [comment]
From the Github Actions pipeline: The ubuntu-16.04 environment is deprecated and will be removed on September 20, 2021.
