### ISSUE TITLE
AttributeError in datetime.time: no attribute fromisoformat

### ISSUE THREAD

**Issue by matias-tecnosoul** [LibreTime/libretime#1228]
Hi, I've been having some playout issues with the LT v64d07865d inside a fresh ubuntu18.
We had a few "stanby" and Onair indicator going offline.
I've found a few
 _AttributeError: type object 'datetime.time' has no attribute 'fromisoformat'_

> Jun  3 15:30:06 xtrema airtime-playout[101]: Traceback (most recent call last):
> Jun  3 15:30:06 xtrema airtime-playout[101]:   File "/usr/local/lib/python3.6/dist-packages/airtime_playout-1.0-py3.6.egg/pypo/pypofetch.py", line 440, in manual_schedule_fetch
> Jun  3 15:30:06 xtrema airtime-playout[101]:     self.schedule_data = self.api_client.get_schedule()
> Jun  3 15:30:06 xtrema airtime-playout[101]:   File "/usr/local/lib/python3.6/dist-packages/api_clients-2.0.0-py3.6.egg/api_clients/version2.py", line 73, in get_schedule
> Jun  3 15:30:06 xtrema airtime-playout[101]:     fade_in = time_in_milliseconds(datetime.time.fromisoformat(item['fade_in']))
> Jun  3 15:30:06 xtrema airtime-playout[101]: AttributeError: type object 'datetime.time' has no attribute 'fromisoformat'
> Jun  3 15:30:06 xtrema uwsgi[77]: [pid: 556|app: 0|req: 104/914] 127.0.0.1 () {36 vars in 640 bytes} [Thu Jun  3 19:30:06 2021] GET /api/v2/schedule/?ends__range=2021-06-03T19%3A30%3A06Z%2C2021-06-03T20%3A30%3A06Z => generated 7850 bytes in 103 msecs (HTTP/1.1 200) 7 headers in 214 bytes (1 switches on core 0)
> Jun  3 15:30:06 xtrema uwsgi[77]: [pid: 557|app: 0|req: 225/915] 127.0.0.1 () {36 vars in 531 bytes} [Thu Jun  3 19:30:06 2021] GET /api/v2/show-instances/62/ => generated 411 bytes in 15 msecs (HTTP/1.1 200) 7 headers in 227 bytes (1 switches on core 0)
> Jun  3 15:30:06 xtrema uwsgi[77]: [pid: 554|app: 0|req: 33/916] 127.0.0.1 () {36 vars in 511 bytes} [Thu Jun  3 19:30:06 2021] GET /api/v2/shows/3/ => generated 261 bytes in 18 msecs (HTTP/1.1 200) 7 headers in 227 bytes (1 switches on core 0)
> Jun  3 15:30:06 xtrema airtime-playout[101]: 2021-06-03 15:30:06,249 [pypofetch] [ERROR]  Unable to fetch schedule
> Jun  3 15:30:06 xtrema airtime-playout[101]: 2021-06-03 15:30:06,249 [pypofetch] [ERROR]  type object 'datetime.time' has no attribute 'fromisoformat'
> Jun  3 15:30:06 xtrema airtime-playout[101]: Traceback (most recent call last):
> Jun  3 15:30:06 xtrema airtime-playout[101]:   File "/usr/local/lib/python3.6/dist-packages/airtime_playout-1.0-py3.6.egg/pypo/pypofetch.py", line 440, in manual_schedule_fetch
> Jun  3 15:30:06 xtrema airtime-playout[101]:     self.schedule_data = self.api_client.get_schedule()
> Jun  3 15:30:06 xtrema airtime-playout[101]:   File "/usr/local/lib/python3.6/dist-packages/api_clients-2.0.0-py3.6.egg/api_clients/version2.py", line 73, in get_schedule
> Jun  3 15:30:06 xtrema airtime-playout[101]:     fade_in = time_in_milliseconds(datetime.time.fromisoformat(item['fade_in']))
> Jun  3 15:30:06 xtrema airtime-playout[101]: AttributeError: type object 'datetime.time' has no attribute 'fromisoformat'
> Jun  3 15:30:06 xtrema airtime-playout[101]: 2021-06-03 15:30:06,250 [pypofetch] [INFO ]  Loop #76
> 

and also

> Jun  3 16:07:22 xtrema airtime-playout[101]: Traceback (most recent call last):
> Jun  3 16:07:22 xtrema airtime-playout[101]:   File "/usr/local/lib/python3.6/dist-packages/airtime_playout-1.0-py3.6.egg/pypo/pypofetch.py", line 440, in manual_schedule_fetch
> Jun  3 16:07:22 xtrema airtime-playout[101]:     self.schedule_data = self.api_client.get_schedule()
> Jun  3 16:07:22 xtrema airtime-playout[101]:   File "/usr/local/lib/python3.6/dist-packages/api_clients-2.0.0-py3.6.egg/api_clients/version2.py", line 73, in get_schedule
> Jun  3 16:07:22 xtrema airtime-playout[101]:     fade_in = time_in_milliseconds(datetime.time.fromisoformat(item['fade_in']))
> Jun  3 16:07:22 xtrema airtime-playout[101]: AttributeError: type object 'datetime.time' has no attribute 'fromisoformat'
> Jun  3 16:07:22 xtrema uwsgi[77]: [pid: 558|app: 0|req: 839/1666] 127.0.0.1 () {36 vars in 640 bytes} [Thu Jun  3 20:07:22 2021] GET /api/v2/schedule/?ends__range=2021-06-03T20%3A07%3A22Z%2C2021-06-03T21%3A07%3A22Z => generated 6533 bytes in 94 msecs (HTTP/1.1 200) 7 headers in 214 bytes (1 switches on core 0)
> Jun  3 16:07:22 xtrema uwsgi[77]: [pid: 556|app: 0|req: 210/1667] 127.0.0.1 () {36 vars in 531 bytes} [Thu Jun  3 20:07:22 2021] GET /api/v2/show-instances/62/ => generated 411 bytes in 13 msecs (HTTP/1.1 200) 7 headers in 227 bytes (1 switches on core 0)
> Jun  3 16:07:22 xtrema uwsgi[77]: [pid: 557|app: 0|req: 397/1668] 127.0.0.1 () {36 vars in 511 bytes} [Thu Jun  3 20:07:22 2021] GET /api/v2/shows/3/ => generated 261 bytes in 16 msecs (HTTP/1.1 200) 7 headers in 227 bytes (1 switches on core 0)
> Jun  3 16:07:22 xtrema airtime-playout[101]: 2021-06-03 16:07:22,325 [pypofetch] [ERROR]  Unable to fetch schedule
> Jun  3 16:07:22 xtrema airtime-playout[101]: 2021-06-03 16:07:22,325 [pypofetch] [ERROR]  type object 'datetime.time' has no attribute 'fromisoformat'

Could that be related?
thanks

**Comment by paddatrapper** [comment]
Ah, this seems to vs because fromisofornat was introduced in Python 3.7... https://docs.python.org/3.7/library/datetime.html#datetime.time.fromisoformat

**Comment by paddatrapper** [comment]
Should use https://docs.python.org/3.7/library/datetime.html#datetime.datetime.strptime instead

**Comment by matias-tecnosoul** [comment]
Any tips to solve it in the meanwhile?
Are there any events that trigger that?
thanks!

**Comment by paddatrapper** [comment]
#1229 should fix it

**Comment by matias-tecnosoul** [comment]
great!!

Now I'm seeing this in the logs. The output stream hanged a couple more times but not sure if this are the related logs... Shoud we open a new issue?
thanks again!!
 

> Jun  4 12:09:30 xtrema airtime-playout[100]: 2021-06-04 12:09:30,929 [pypofetch] [ERROR]  Unable to fetch schedule
> Jun  4 12:09:30 xtrema airtime-playout[100]: 2021-06-04 12:09:30,929 [pypofetch] [ERROR]  time data '00:00:00' does not match format '%H:%M:%S.%f'
> Jun  4 12:09:30 xtrema airtime-playout[100]: Traceback (most recent call last):
> Jun  4 12:09:30 xtrema airtime-playout[100]:   File "/usr/local/lib/python3.6/dist-packages/airtime_playout-1.0-py3.6.egg/pypo/pypofetch.py", line 440, in manual_schedule_fetch
> Jun  4 12:09:30 xtrema airtime-playout[100]:     self.schedule_data = self.api_client.get_schedule()
> Jun  4 12:09:30 xtrema airtime-playout[100]:   File "/usr/local/lib/python3.6/dist-packages/api_clients-2.0.0-py3.6.egg/api_clients/version2.py", line 76, in get_schedule
> Jun  4 12:09:30 xtrema airtime-playout[100]:     cue_in = time_in_seconds(fromisoformat(item['cue_in']))
> Jun  4 12:09:30 xtrema airtime-playout[100]:   File "/usr/local/lib/python3.6/dist-packages/api_clients-2.0.0-py3.6.egg/api_clients/utils.py", line 174, in fromisoformat
> Jun  4 12:09:30 xtrema airtime-playout[100]:     datetime_obj = datetime.datetime.strptime(time_string, "%H:%M:%S.%f")
> Jun  4 12:09:30 xtrema airtime-playout[100]:   File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
> Jun  4 12:09:30 xtrema airtime-playout[100]:     tt, fraction = _strptime(data_string, format)
> Jun  4 12:09:30 xtrema airtime-playout[100]:   File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
> Jun  4 12:09:30 xtrema airtime-playout[100]:     (data_string, format))
> Jun  4 12:09:30 xtrema airtime-playout[100]: ValueError: time data '00:00:00' does not match format '%H:%M:%S.%f'
> Jun  4 12:09:30 xtrema airtime-playout[100]: 2021-06-04 12:09:30,929 [pypofetch] [INFO ]  Loop #27
>

**Comment by paddatrapper** [comment]
hmm... That error implies there are more time formats that we should account for. Essentially the `.%f` should be optional

**Comment by paddatrapper** [comment]
#1231

**Comment by matias-tecnosoul** [comment]
I edited python_apps/api_clients/api_clients/utils.py and python_apps/api_clients/tests/test_utils.py as mentioned and rebooted. That bug is gone but the output stream keeps getting an offline state in icecast, even though the online indicator and the now playing tag is correct in the player. Maybe this is a different issue?

**Comment by paddatrapper** [comment]
Yeah that sounds like a different issue
