### ISSUE TITLE
Setup automatique dependencies update bot

### ISSUE THREAD

**Issue by jooola** [LibreTime/libretime#1230]
Adding a dependencies update bot to the project has already been mentioned in the community channels. I would like to open a ticket in order to make a decision, and get this done.

The 2 bots I know of are:
- https://dependabot.com/
- https://github.com/renovatebot/renovate

Using dependabot is pretty straightforward, renovate seems to have more knobs we can configure.
I would go with dependabot, which is probably enough for this project needs.

Who can set this up ?

**Comment by paddatrapper** [comment]
The only thing that could be an issue is our PHP stack - most of that we can't update thanks to the Zend dependency. Is it possible to disable PRs for PHP dependency updates?

**Comment by jooola** [comment]
Last time I configured dependabot I had to configure it for specific languages, so you could choose not to configure for the php stack.

I would configure to check for GitHub actions updates, python requirements, and we can add some npm package check once we use these package manager.

**Comment by jooola** [comment]
Last time I configured it I went trough the dependabot web interface, but we could use a config file, maybe that's better.

https://dependabot.com/docs/config-file/
