### ISSUE TITLE
Drop python-daemon in python apps

### ISSUE THREAD

**Issue by jooola** [LibreTime/libretime#1232]
I think daemonizing a process should be handled by the system, not the software. Because systemd/upstart/docker handle this task better and this simplify the python apps.

Any thoughts ?

**Comment by paddatrapper** [comment]
Where does this happen? As I understand, all the python apps use an init system to run

**Comment by jooola** [comment]
Yes, we use init system but some remaining code from the sysV ages is still here.
Here is an example:
https://github.com/LibreTime/libretime/blob/master/python_apps/airtime_analyzer/airtime_analyzer/cli.py#L33-L42

**Comment by jooola** [comment]
And I think I saw it in some PR somewhere
