### ISSUE TITLE
Drop SysV init system support 

### ISSUE THREAD

**Issue by jooola** [LibreTime/libretime#1247]
On the community channels, I proposed to drop support for the old SysV init system.
Our oldest supported systems Ubuntu 16.04 and Centos 7 defaults to systemd, and all other recent systems as well.

Keeping Sysv would be to please people who switched back to SysV intentionally. For those who still want to use SysV, I suggest they dig into the project to retrieve the old SysV config files.

I would even ask myself if we should not also drop Upstart support ? Who is still using it ?

**Comment by paddatrapper** [comment]
What do we gain by dropping it?

**Comment by jooola** [comment]
We gain time for other features, simplify the installation process and cleanup the repository.

Also, I know this is not totally right, but this allow to suggest people still using sysV to use systemd, simply because it is way more powerful than sysv.

Plus, on the Debian side, they doesn't seem to require packages to have sysv related files.

If we want to support the sysV init system, we need to properly support it and fix some few things.

Our best answer should come by polling the community to know what is used by who.

**Comment by jooola** [comment]
http://upstart.ubuntu.com/ From the upstart website, it is in maintenance once, and didn't had any new release since 2014.

**Comment by jooola** [comment]
I stumbled on this long explanation, and according to the usage list, I would say it is safe to only support the Systemd init system. https://unix.stackexchange.com/a/287282 and https://en.wikipedia.org/wiki/Systemd#Adoption

**Comment by jooola** [comment]
Now that we have a better idea regarding the use of sysv by the community, I would like to accept this issue.

Maybe we want to wait for the next community meetup in order to gather more feedback in the community survey and confirm the change at this moment. @paddatrapper What do you think ?

But, backed by the explanations linked in my previous comment, and the result of the community survey below, I feel confident in dropping support for SysV.

Result from the 01/09/2021:
![image](https://user-images.githubusercontent.com/19195485/131682362-a9a5039a-8163-4c38-ad1e-1e6fd672b2c2.png)

**Comment by paddatrapper** [comment]
Yeah, I think we can accept this based on the survey so far

**Comment by jooola** [comment]
Should we drop Upstart as well ?

**Comment by paddatrapper** [comment]
Yes, I think so
