### ISSUE TITLE
Error during importing smart block

### ISSUE THREAD

**Issue by yarik2720** [LibreTime/libretime#126]
I found error during importing smart block in current program in time when tracks were chaning
(in old versions of airtime 2.5.1 in that time there was problem, that metainfo were changes back to previous trackname when new track starting)
![vlcsnap-2017-03-26-12h42m00s683](https://cloud.githubusercontent.com/assets/1839978/24330196/f395b356-1221-11e7-9cff-13c381be0f17.png)

**Comment by hairmare** [comment]
It seems the code is not transaction safe when it comes to saving new tracks. The [PostgreSQL docs](https://www.postgresql.org/docs/9.1/static/transaction-iso.html) say:

> When an application receives this error message, it should abort the current transaction and retry the whole transaction from the beginning. 

I think transactions where rather new in 2.5 and they seem to have not been done properly everywhere.

**Comment by hairmare** [comment]
So far I haven't been able to replicate this locally. If you have any tips on how I can reproduce this, please let me know.

**Comment by Robbt** [comment]
So if I understand the issue it is trying to add smartblocks onto currently playing tracks sometimes fails because the system marks them as already updated. This could be releated to #232 and tested at the same time.

**Comment by hairmare** [comment]
@yarik2720 I'm going to close this since it seems stale and we where never able to reproduce it. Feel free to re-open it or let us know if you have any more insights into how we could reproduce it and we will be glad to reopen this issue.
