### ISSUE TITLE
Install documentation will install from master 

### ISSUE THREAD

**Issue by jooola** [libretime/libretime#1264]
The new install documentation suggest that the git installation method is the default one, and install directly from master, instead of using a tag to target a specific version. This is a bad idea.

It seems, since the rewrite of the documentation, some things are difficult to track coming from an previous installation based on previous documentation.

**Comment by paddatrapper** [comment]
With the current state of development and the slow rate of releases, this is still the best way to go. With a 3.0 beta release, this should change to follow versioned releases

**Comment by jooola** [comment]
Ok, so you you recommend installing from master, even in production ?
I dont mind running from master, bug we had some pretty dumb bugs here and there and I don't want to update the local installation repo every 2 days.

On the other hand I would really like to help getting this v3 out so we can focus on the more attractive stuff.

**Comment by paddatrapper** [comment]
Perhaps the solution is to release a alpha.10 in the next couple of days and then release a 3.0 beta after there has been some time for feedback and bug reports on alpha.10. The only thing that is preventing me from going ahead is #1254, which I would like to have in an alpha.10 release

**Comment by paddatrapper** [comment]
I am really tempted to make the deb package/PPA installs the default way of doing things. That way users can track known versions and not have to follow master. It also makes the install instructions easy (at least on Ubuntu and potentially Debian if we find a way of doing DPA without running an entire APT repo): 1. enable PPA, 2. Install libretime package

**Comment by jooola** [comment]
In the new documentation, when installing using git, we suggest checkout the latest tag. So this is resolved.

I don't think adding a note for those willing to run from the main branch might be a good idea. People with enough experience with git (and probably also command line) will know they can run from the main branch. That said, having people installing a tagged version might introduce a lot of duplicate bug reports, that have already been fixed. We could release more often to counter this.
