### ISSUE TITLE
2021-07-11 | Installation Error

### ISSUE THREAD

**Issue by z8rsvenbergner** [LibreTime/libretime#1267]
I use Ubuntu 18.04 like the installer said.

The Installation is not working.
See the Screenshot below:
![CleanShot 2021-07-11 at 16 50 19](https://user-images.githubusercontent.com/75265769/125199785-2c248880-e268-11eb-9001-6c0593f8d640.jpeg)

**Comment by paddatrapper** [comment]
This log is incomplete, but from the looks of it, it is the same issue fixed in #1262

**Comment by matias-tecnosoul** [comment]
same problem here with latest git today.
some more logs:

> Installed /usr/local/lib/python3.6/dist-packages/libretime_analyzer-0.1-py3.6.egg
> Processing dependencies for libretime-analyzer==0.1
> Searching for pycairo==1.19.1
> Reading https://pypi.org/simple/pycairo/
> Downloading https://files.pythonhosted.org/packages/e8/9d/c8be300fc6b1298559d37a071c3833b0b251e0fff334d2e4c408d5789162/pycairo-1.19.1.tar.gz#sha256=2c143183280feb67f5beb4e543fd49990c28e7df427301ede04fc550d3562e84
> Best match: pycairo 1.19.1
> Processing pycairo-1.19.1.tar.gz
> Writing /tmp/easy_install-7qrsi79d/pycairo-1.19.1/setup.cfg
> Running pycairo-1.19.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-7qrsi79d/pycairo-1.19.1/egg-dist-tmp-x37_xd1a
> no previously-included directories found matching 'docs/_build'
> warning: no files found matching 'README' under directory 'tests'
> warning: no files found matching 'README' under directory 'examples'
> zip_safe flag not set; analyzing archive contents...
> cairo.__pycache__.__init__.cpython-36: module references __file__
> cairo.__pycache__._cairo.cpython-36: module references __file__
> creating /usr/local/lib/python3.6/dist-packages/pycairo-1.19.1-py3.6-linux-x86_64.egg
> Extracting pycairo-1.19.1-py3.6-linux-x86_64.egg to /usr/local/lib/python3.6/dist-packages
> Adding pycairo 1.19.1 to easy-install.pth file
> 
> Installed /usr/local/lib/python3.6/dist-packages/pycairo-1.19.1-py3.6-linux-x86_64.egg
> Searching for PyGObject<=3.36.1,>=3.34.0
> Reading https://pypi.org/simple/PyGObject/
> Downloading https://files.pythonhosted.org/packages/93/41/bf9ab8929f51dac2979ae81bb094728bacee3ceb049def72d3fc1bcb4241/PyGObject-3.36.1.tar.gz#sha256=012a589aec687bfa809a1ff9f5cd775dc7f6fcec1a6bc7fe88e1002a68f8ba34
> Best match: PyGObject 3.36.1
> Processing PyGObject-3.36.1.tar.gz
> Writing /tmp/easy_install-v3vbzwn3/PyGObject-3.36.1/setup.cfg
> Running PyGObject-3.36.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-v3vbzwn3/PyGObject-3.36.1/egg-dist-tmp-nmcsb6ap
> Package py3cairo was not found in the pkg-config search path.
> Perhaps you should add the directory containing `py3cairo.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'py3cairo' found
> Traceback (most recent call last):
>   File "/tmp/easy_install-v3vbzwn3/PyGObject-3.36.1/setup.py", line 178, in _run_pkg_config
>   File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
>     **kwargs).stdout
>   File "/usr/lib/python3.6/subprocess.py", line 438, in run
>     output=stdout, stderr=stderr)
> subprocess.CalledProcessError: Command '('pkg-config', '--print-errors', '--exists', 'py3cairo >= 1.11.1')' returned non-zero exit status 1.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/tmp/easy_install-v3vbzwn3/PyGObject-3.36.1/setup.py", line 186, in _run_pkg_config
>   File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
>     **kwargs).stdout
>   File "/usr/lib/python3.6/subprocess.py", line 438, in run
>     output=stdout, stderr=stderr)
> subprocess.CalledProcessError: Command '['pkg-config', '--exists', 'py3cairo']' returned non-zero exit status 1.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/tmp/easy_install-v3vbzwn3/PyGObject-3.36.1/setup.py", line 199, in _run_pkg_config_or_exit
>   File "/tmp/easy_install-v3vbzwn3/PyGObject-3.36.1/setup.py", line 188, in _run_pkg_config
> __main__.PkgConfigMissingPackageError: Command '('pkg-config', '--print-errors', '--exists', 'py3cairo >= 1.11.1')' returned non-zero exit status 1.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/dist-packages/setuptools/sandbox.py", line 152, in save_modules
>     yield saved
>   File "/usr/local/lib/python3.6/dist-packages/setuptools/sandbox.py", line 193, in setup_context
>     yield
>   File "/usr/local/lib/python3.6/dist-packages/setuptools/sandbox.py", line 254, in run_setup
>     _execfile(setup_script, ns)
>   File "/usr/local/lib/python3.6/dist-packages/setuptools/sandbox.py", line 43, in _execfile
>     exec(code, globals, locals)
>   File "/tmp/easy_install-v3vbzwn3/PyGObject-3.36.1/setup.py", line 1288, in <module>
>   File "/tmp/easy_install-v3vbzwn3/PyGObject-3.36.1/setup.py", line 1283, in main
>   File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 153, in setup
>     return distutils.core.setup(**attrs)
>   File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
>     dist.run_commands()
>   File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
>     self.run_command(cmd)
>   File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
>     cmd_obj.run()
>   File "/usr/local/lib/python3.6/dist-packages/setuptools/command/bdist_egg.py", line 164, in run
>     cmd = self.call_command('install_lib', warn_dir=0)
>   File "/usr/local/lib/python3.6/dist-packages/setuptools/command/bdist_egg.py", line 150, in call_command
>     self.run_command(cmdname)
>   File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
>     cmd_obj.run()
>   File "/usr/local/lib/python3.6/dist-packages/setuptools/command/install_lib.py", line 11, in run
>     self.build()
>   File "/usr/lib/python3.6/distutils/command/install_lib.py", line 109, in build
>     self.run_command('build_ext')
>   File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
>     cmd_obj.run()
>   File "/tmp/easy_install-v3vbzwn3/PyGObject-3.36.1/setup.py", line 1118, in run
>   File "/tmp/easy_install-v3vbzwn3/PyGObject-3.36.1/setup.py", line 1110, in _setup_extensions
>   File "/tmp/easy_install-v3vbzwn3/PyGObject-3.36.1/setup.py", line 1093, in add_pycairo
>   File "/tmp/easy_install-v3vbzwn3/PyGObject-3.36.1/setup.py", line 927, in get_pycairo_include_dir
>   File "/tmp/easy_install-v3vbzwn3/PyGObject-3.36.1/setup.py", line 911, in find_pkg_config
>   File "/tmp/easy_install-v3vbzwn3/PyGObject-3.36.1/setup.py", line 222, in pkg_config_version_check
>   File "/tmp/easy_install-v3vbzwn3/PyGObject-3.36.1/setup.py", line 213, in _run_pkg_config_or_exit
> SystemExit: Command '('pkg-config', '--print-errors', '--exists', 'py3cairo >= 1.11.1')' returned non-zero exit status 1.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/root/libretime/python_apps/airtime_analyzer/setup.py", line 31, in <module>
>     zip_safe=False,
>   File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 153, in setup
>     return distutils.core.setup(**attrs)
>   File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
>     dist.run_commands()
>   File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
>     self.run_command(cmd)
>   File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
>     cmd_obj.run()
>   File "/usr/local/lib/python3.6/dist-packages/setuptools/command/install.py", line 67, in run
>     self.do_egg_install()
>   File "/usr/local/lib/python3.6/dist-packages/setuptools/command/install.py", line 117, in do_egg_install
>     cmd.run(show_deprecation=False)
>   File "/usr/local/lib/python3.6/dist-packages/setuptools/command/easy_install.py", line 408, in run
>     self.easy_install(spec, not self.no_deps)
>   File "/usr/local/lib/python3.6/dist-packages/setuptools/command/easy_install.py", line 650, in easy_install
>     return self.install_item(None, spec, tmpdir, deps, True)
>   File "/usr/local/lib/python3.6/dist-packages/setuptools/command/easy_install.py", line 697, in install_item
>     self.process_distribution(spec, dist, deps)
>   File "/usr/local/lib/python3.6/dist-packages/setuptools/command/easy_install.py", line 745, in process_distribution
>     [requirement], self.local_index, self.easy_install
>   File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 768, in resolve
>     replace_conflicting=replace_conflicting
>   File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 1051, in best_match
>     return self.obtain(req, installer)
>   File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 1063, in obtain
>     return installer(requirement)
>   File "/usr/local/lib/python3.6/dist-packages/setuptools/command/easy_install.py", line 669, in easy_install
>     return self.install_item(spec, dist.location, tmpdir, deps)
>   File "/usr/local/lib/python3.6/dist-packages/setuptools/command/easy_install.py", line 695, in install_item
>     dists = self.install_eggs(spec, download, tmpdir)
>   File "/usr/local/lib/python3.6/dist-packages/setuptools/command/easy_install.py", line 890, in install_eggs
>     return self.build_and_install(setup_script, setup_base)
>   File "/usr/local/lib/python3.6/dist-packages/setuptools/command/easy_install.py", line 1162, in build_and_install
>     self.run_setup(setup_script, setup_base, args)
>   File "/usr/local/lib/python3.6/dist-packages/setuptools/command/easy_install.py", line 1146, in run_setup
>     run_setup(setup_script, args)
>   File "/usr/local/lib/python3.6/dist-packages/setuptools/sandbox.py", line 257, in run_setup
>     raise
>   File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
>     self.gen.throw(type, value, traceback)
>   File "/usr/local/lib/python3.6/dist-packages/setuptools/sandbox.py", line 193, in setup_context
>     yield
>   File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
>     self.gen.throw(type, value, traceback)
>   File "/usr/local/lib/python3.6/dist-packages/setuptools/sandbox.py", line 164, in save_modules
>     saved_exc.resume()
>   File "/usr/local/lib/python3.6/dist-packages/setuptools/sandbox.py", line 139, in resume
>     raise exc.with_traceback(self._tb)
>   File "/usr/local/lib/python3.6/dist-packages/setuptools/sandbox.py", line 152, in save_modules
>     yield saved
>   File "/usr/local/lib/python3.6/dist-packages/setuptools/sandbox.py", line 193, in setup_context
>     yield
>   File "/usr/local/lib/python3.6/dist-packages/setuptools/sandbox.py", line 254, in run_setup
>     _execfile(setup_script, ns)
>   File "/usr/local/lib/python3.6/dist-packages/setuptools/sandbox.py", line 43, in _execfile
>     exec(code, globals, locals)
>   File "/tmp/easy_install-v3vbzwn3/PyGObject-3.36.1/setup.py", line 1288, in <module>
>   File "/tmp/easy_install-v3vbzwn3/PyGObject-3.36.1/setup.py", line 1283, in main
>   File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 153, in setup
>     return distutils.core.setup(**attrs)
>   File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
>     dist.run_commands()
>   File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
>     self.run_command(cmd)
>   File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
>     cmd_obj.run()
>   File "/usr/local/lib/python3.6/dist-packages/setuptools/command/bdist_egg.py", line 164, in run
>     cmd = self.call_command('install_lib', warn_dir=0)
>   File "/usr/local/lib/python3.6/dist-packages/setuptools/command/bdist_egg.py", line 150, in call_command
>     self.run_command(cmdname)
>   File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
>     cmd_obj.run()
>   File "/usr/local/lib/python3.6/dist-packages/setuptools/command/install_lib.py", line 11, in run
>     self.build()
>   File "/usr/lib/python3.6/distutils/command/install_lib.py", line 109, in build
>     self.run_command('build_ext')
>   File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
>     cmd_obj.run()
>   File "/tmp/easy_install-v3vbzwn3/PyGObject-3.36.1/setup.py", line 1118, in run
>   File "/tmp/easy_install-v3vbzwn3/PyGObject-3.36.1/setup.py", line 1110, in _setup_extensions
>   File "/tmp/easy_install-v3vbzwn3/PyGObject-3.36.1/setup.py", line 1093, in add_pycairo
>   File "/tmp/easy_install-v3vbzwn3/PyGObject-3.36.1/setup.py", line 927, in get_pycairo_include_dir
>   File "/tmp/easy_install-v3vbzwn3/PyGObject-3.36.1/setup.py", line 911, in find_pkg_config
>   File "/tmp/easy_install-v3vbzwn3/PyGObject-3.36.1/setup.py", line 222, in pkg_config_version_check
>   File "/tmp/easy_install-v3vbzwn3/PyGObject-3.36.1/setup.py", line 213, in _run_pkg_config_or_exit
> setuptools.sandbox.UnpickleableException: SystemExit(PkgConfigMissingPackageError(CalledProcessError(1, ('pkg-config', '--print-errors', '--exists', 'py3cairo >= 1.11.1')),),)
>

**Comment by paddatrapper** [comment]
Should be fixed in #1269, or at least works under Vagrant on Ubuntu 18.04

**Comment by radiobijoux** [comment]
I've faced this issue on every reinstall I've done (about a dozen, practicing things and testing things out) and discovered early on that all I needed to do was just perform a quick reinstall as soon as the first install finished with that error.  On the second attempt, it performs all of the missing functions that failed on the first attempt and all works as it should once it's complete.

**Comment by paddatrapper** [comment]
@radiobijoux ah, then that points to installing `py3cairo` earlier in the process. I'll test installing it at the beginning of the install script and see if that fixes the issue

**Comment by radiobijoux** [comment]
Will give it a try today.
Thanks!

**Comment by radiobijoux** [comment]
Install works perfectly 1st time, every time.
