### ISSUE TITLE
how to remove elements from a web page?

### ISSUE THREAD

**Issue by phoenixqss** [LibreTime/libretime#1268]
how to remove the calendar, the podcasts item and the next item after the calendar from the web page. So that only the player remains at the bottom of the page and nothing else .
![maxresdefault](https://user-images.githubusercontent.com/86921524/125351169-6c6b3000-e368-11eb-831d-5c521bc3cdc7.jpg)
Everything that is circled must be removed . how can I do this ?Please help me....

**Comment by zklosko** [comment]
You would need to edit the code in PHP to do this. We don't have a setting or option in the interface to remove elements of the microsite.
