### ISSUE TITLE
Debian Bullseye Support

### ISSUE THREAD

**Issue by jooola** [LibreTime/libretime#1271]
I would like to add support for Debian Bullseye, as the Full freeze is tomorrow, GA should be in a few weeks.

See https://wiki.debian.org/DebianBullseye

**Comment by paddatrapper** [comment]
This will probably run into the same issues as Ubuntu 20.04 (#1168). The biggest issue is finding a good PPA for PHP support, as PHP 7.4 is not supported by our PHP framework. I think the author of the PPA I've added for Ubuntu 20.04 has a Debian apt repo that we could use. Not sure if there is a Bullseye repo yet though

**Comment by jooola** [comment]
What about using the php sury repository ? https://deb.sury.org/

**Comment by paddatrapper** [comment]
Yup, that's the one I was thinking of
