### ISSUE TITLE
chaining smart blocks in the show - they play together at the start-end point

### ISSUE THREAD

**Issue by chicco64** [LibreTime/libretime#1272]
I installed libretime using "git clone" with debian10.
I create several consecutive "shows" in the calendar (eg 09.55 - 10.05 // 10.05-10.15 ) and, within the show, I insert a smart-block (longer than the show duration, as obviously it can happen...), the next show starts at the appointed time, but does not stop the previous one, therefore the songs contained in the outgoing show and the incoming show overlap.
In the example, "a rose in the wind" and "slave to love" don't stop when "complicated" starts playing.
Thanks for the reply.
<img width="672" alt="libretime-smartblocks" src="https://user-images.githubusercontent.com/59960414/126132874-e5a38ea3-961f-440b-bade-378c884b6053.PNG">

**Comment by paddatrapper** [comment]
What is the content of `/var/log/airtime/pypo/pypo.log`?

**Comment by chicco64** [comment]
[pypo.log](https://github.com/LibreTime/libretime/files/6839967/pypo.log)

**Comment by paddatrapper** [comment]
And the liquidsoap logs from the same directory?

**Comment by chicco64** [comment]
this is the log in /var/log/airtime/pypo-liquidsoap

[ls_script.log](https://github.com/LibreTime/libretime/files/6847591/ls_script.log)

**Comment by chicco64** [comment]
I proceeded to do a new installation but the problem remains the same, can you give me feedback? thank you

**Comment by undoablemixlr** [comment]
Hello,
I have the same problem, I would also like to have an idea to correct this !

**Comment by michielgardner** [comment]
I have the same problem. It happens on any show that is overbooked, not only when using smart blocks. 

I found that cue_out in the API response of the schedule is not set correctly since API v2. 

You can reproduce this by creating 2 shows of 1 minute. If you put a track longer than 1 minute in these shows, the cue_out for this track in the API response should be set to 60 seconds (which it does on pre-API v2 installs), instead of the full length of the track which causes the overlap.

To install the latest pre-API v2 version which does not have this problem, you can run this after cloning the git repository (before installing):

```git checkout 79ea5dfc739c5a517c14452a3afa32186209ad6e```

**Comment by Robbt** [comment]
Thanks for finding this. I suspected it might be an issue with the new API. Now the challenge of analyzing the code and discovering the bug.

**Comment by paddatrapper** [comment]
> You can reproduce this by creating 2 shows of 1 minute. If you put a track longer than 1 minute in these shows, the cue_out for this track in the API response should be set to 60 seconds (which it does on pre-API v2 installs), instead of the full length of the track which causes the overlap.

This will need logic in the API for detecting when the cut-off should be. It should be in the database and propagated through the API response. The API client uses the `cue_in` and `cue_out` values from the response

**Comment by michielgardner** [comment]
I think this is where the new cue_out value is calculated in the v1 API: https://github.com/LibreTime/libretime/blob/8e54cd1f12e86f63ef58f34009447df08b5afd6d/airtime_mvc/application/models/Schedule.php#L1022

On both API versions the schedule in the database looks the same, so the new cue_out value is calculated _after_ the database request in the v1 API.

**Comment by paddatrapper** [comment]
You've hit the nail on the head, I think

**Comment by undoablemixlr** [comment]
> I have the same problem. It happens on any show that is overbooked, not only when using smart blocks.
> 
> I found that cue_out in the API response of the schedule is not set correctly since API v2.
> 
> You can reproduce this by creating 2 shows of 1 minute. If you put a track longer than 1 minute in these shows, the cue_out for this track in the API response should be set to 60 seconds (which it does on pre-API v2 installs), instead of the full length of the track which causes the overlap.
> 
> To install the latest pre-API v2 version which does not have this problem, you can run this after cloning the git repository (before installing):
> 
> `git checkout 79ea5dfc739c5a517c14452a3afa32186209ad6e`
------------------------
hello, being neophyte, I would like to have a link to download API V2 which you speak about in your post in order to install it and solve this dysfunction of mixed tracks. I am grateful to you in advance
...

**Comment by jooola** [comment]
@paddatrapper Are you providing a fix or should I assign myself to this one ?

**Comment by paddatrapper** [comment]
I haven't had a chance to work on this yet. Not sure if the correct solution is to mirror what the PHP API does and do it when returning or write it into the DB when the schedule changes. The latter would require more work (as it would need updating every time the schedule DB table changes), but would make the DB consistent at least...

**Comment by paddatrapper** [comment]
Looks like it needs to be in the API response - Cue out has a meaning for a track itself - when the track should stop playing in isolation

**Comment by paddatrapper** [comment]
@jooola fix PR open

**Comment by undoablemixlr** [comment]
Thanx !!
