### ISSUE TITLE
Renaming `master` branch to `main`

### ISSUE THREAD

**Issue by jooola** [LibreTime/libretime#1277]
I propose to rename the `master` branch to `main`, guided by this draft's reasoning https://datatracker.ietf.org/doc/html/draft-knodel-terminology-05, specially this section https://datatracker.ietf.org/doc/html/draft-knodel-terminology-05#section-3.1.

Tracking the draft : https://datatracker.ietf.org/doc/draft-knodel-terminology/

I am unsure of what will break after this change, but we can include this change before the v3 beta/stable release.

**Comment by zklosko** [comment]
A branch name should only affect our CI/CD. We should complete this ASAP.

**Comment by Robbt** [comment]
This sounds like a good idea to me. I'm not sure what I need to do exactly to enact the change but I could figure it out.

**Comment by jooola** [comment]
Weblate depends on the default branch name, it has to be updated once this is resolved.

**Comment by jooola** [comment]
@Robbt Mayb I ping you for this one ?

**Comment by Robbt** [comment]
I'm up for doing this but don't want to break anything and haven't had much time to dive into the docs regarding the specific commands, but thanks for sharing them. @hairmare I believe could also do it, or we could elevate @paddatrapper to be able to make the change as well.

**Comment by jooola** [comment]
I propose one of the admins do the changes and I make sure everything is working as expected and I will provide a PR changing the files still referencing master.

Github is handling everything it there side with https://github.com/github/renaming#renaming-existing-branches.
