### ISSUE TITLE
Analyzer systemd service stops on SIGKILL, SIGTERM seem unhandled

### ISSUE THREAD

**Issue by jooola** [LibreTime/libretime#1278]
SystemD uses the SIGTERM signal to ask nicely the process to stop, after some timeout (90 seconds by default), SystemD sends a SIGKILL to kill the process.

The analyzer currently does not handle properly the SIGTERM signal, so each service stop (or restart) take 90 seconds and isn't gracefully handled.

**LibreTime version:** master @ d58fe19ae3cd01f6339e8f25d76b607e5d6b3716
**OS:** Debian Buster

Some journald logs:
```
[running `systemctl stop libretime-analyzer`]
Aug  2 15:56:00 libretime-auk libretime-analyzer[416]: LibreTime Analyzer 1.0                                                              
Aug  2 15:56:00 libretime-auk systemd[1]: Stopping LibreTime Media Analyzer Service...                                                     
Aug  2 15:57:30 libretime-auk systemd[1]: libretime-analyzer.service: State 'stop-sigterm' timed out. Killing.                             
Aug  2 15:57:30 libretime-auk systemd[1]: libretime-analyzer.service: Killing process 416 (libretime-analy) with signal SIGKILL.           
Aug  2 15:57:30 libretime-auk systemd[1]: libretime-analyzer.service: Main process exited, code=killed, status=9/KILL                      
Aug  2 15:57:30 libretime-auk systemd[1]: libretime-analyzer.service: Failed with result 'timeout'.                                        
Aug  2 15:57:30 libretime-auk systemd[1]: Stopped LibreTime Media Analyzer Service. 
```

**Comment by paddatrapper** [comment]
It looks like `airtime_analyzer/message_listener.py` breaks on `KeyboardInterrupt` and `SystemExit` exceptions. I expect that SIGTERM doesn't trigger a SystemExit exception. This is in the pika library [calls](https://pika.readthedocs.io/en/stable/modules/adapters/blocking.html#pika.adapters.blocking_connection.BlockingChannel.start_consuming) however

**Comment by tomachinz** [comment]
Yes I had this same problem. I could see it restarting every 5 seconds in the logs I believe (using lnav log analyzer).
Can't recall with which distro I used... but it may well have been Debian come to think of it - since that is the version recommended in the docs! Then I tried it with AV Linux, then Ubuntu Server, then MX Linux, then tried using muli-container docker, but I want postgres to be on bare metal so I decide to scrap that and if bare metal install not work on MX I will format and go back to try **Ubuntu Server LTS** stable, I have a hunch this will work fine. I plan to install lightdm for a GUI even though is definitely a server not workstation.

**Comment by tomachinz** [comment]
> It looks like `airtime_analyzer/message_listener.py` breaks on ... This is in the pika library [calls] 

So I will look for a call to start_consuming() inside of this message_listener.py yes? Ideally to try to find a different way to do whatever it is trying. It is not a bug in Pika that needs fix but the analyzer calls or use of said lib yeah?

I will have a squiz and a ponder shortly... re:
`pika.exceptions.ReentrancyError – if called from the scope of a BlockingConnection or BlockingChannel callback`

**Comment by jooola** [comment]
@tomachinz I think you will have to call `stop_consuming` during the signal handling in the main thread, this should stop the underlying thread nicely. 

I haven't looked at the code yet, but that is what I am guessing.

**Comment by paddatrapper** [comment]
https://github.com/LibreTime/libretime/blob/master/python_apps/airtime_analyzer/airtime_analyzer/message_listener.py#L132

Uses a blocking connection that listens for messages using the pika library. Pika raises SystemExit for SIGHUP received (I expect), which we catch and handle: https://github.com/LibreTime/libretime/blob/master/python_apps/airtime_analyzer/airtime_analyzer/message_listener.py#L90

I would guess this is a bug in the version of pika we use

**Comment by paddatrapper** [comment]
I have no strong feelings either way. Kombu looks like it would work fine

**Comment by jooola** [comment]
Seems like the API is also hanging on stop/shutdown.

**Comment by jooola** [comment]
This seem to be even more annoying when running with docker.

**Comment by jooola** [comment]
I've been experimenting a bit with the analyzer rabbitmq connection, and it looks like the hang actually happens in the status reporter. I need to investigate some more though.

**Comment by jooola** [comment]
```
Feb  6 16:49:24 bullseye libretime-analyzer[49516]: Traceback (most recent call last):
Feb  6 16:49:24 bullseye libretime-analyzer[49516]:   File "/usr/local/bin/libretime-analyzer", line 8, in <module>
Feb  6 16:49:24 bullseye libretime-analyzer[49516]:     sys.exit(cli())
Feb  6 16:49:24 bullseye libretime-analyzer[49516]:   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1128, in __call__
Feb  6 16:49:24 bullseye libretime-analyzer[49516]:     return self.main(*args, **kwargs)
Feb  6 16:49:24 bullseye libretime-analyzer[49516]:   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1053, in main
Feb  6 16:49:24 bullseye libretime-analyzer[49516]:     rv = self.invoke(ctx)
Feb  6 16:49:24 bullseye libretime-analyzer[49516]:   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1395, in invoke
Feb  6 16:49:24 bullseye libretime-analyzer[49516]:     return ctx.invoke(self.callback, **ctx.params)
Feb  6 16:49:24 bullseye libretime-analyzer[49516]:   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 754, in invoke
Feb  6 16:49:24 bullseye libretime-analyzer[49516]:     return __callback(*args, **kwargs)
Feb  6 16:49:24 bullseye libretime-analyzer[49516]:   File "/usr/local/lib/python3.9/dist-packages/libretime_analyzer/main.py", line 45, in cli
Feb  6 16:49:24 bullseye libretime-analyzer[49516]:     _msg_listener = MessageListener(config.rabbitmq)
Feb  6 16:49:24 bullseye libretime-analyzer[49516]:   File "/usr/local/lib/python3.9/dist-packages/libretime_analyzer/message_listener.py", line 77, in __init__
Feb  6 16:49:24 bullseye libretime-analyzer[49516]:     self.wait_for_messages()
Feb  6 16:49:24 bullseye libretime-analyzer[49516]:   File "/usr/local/lib/python3.9/dist-packages/libretime_analyzer/message_listener.py", line 121, in wait_for_messages
Feb  6 16:49:24 bullseye libretime-analyzer[49516]:     self._channel.start_consuming()
Feb  6 16:49:24 bullseye libretime-analyzer[49516]:   File "/usr/local/lib/python3.9/dist-packages/pika/adapters/blocking_connection.py", line 1865, in start_consuming
Feb  6 16:49:24 bullseye libretime-analyzer[49516]:     self._process_data_events(time_limit=None)
Feb  6 16:49:24 bullseye libretime-analyzer[49516]:   File "/usr/local/lib/python3.9/dist-packages/pika/adapters/blocking_connection.py", line 2026, in _process_data_events
Feb  6 16:49:24 bullseye libretime-analyzer[49516]:     self.connection.process_data_events(time_limit=time_limit)
Feb  6 16:49:24 bullseye libretime-analyzer[49516]:   File "/usr/local/lib/python3.9/dist-packages/pika/adapters/blocking_connection.py", line 824, in process_data_events
Feb  6 16:49:24 bullseye libretime-analyzer[49516]:     self._flush_output(common_terminator)
Feb  6 16:49:24 bullseye libretime-analyzer[49516]:   File "/usr/local/lib/python3.9/dist-packages/pika/adapters/blocking_connection.py", line 514, in _flush_output
Feb  6 16:49:24 bullseye libretime-analyzer[49516]:     self._impl.ioloop.poll()
Feb  6 16:49:24 bullseye libretime-analyzer[49516]:   File "/usr/local/lib/python3.9/dist-packages/pika/adapters/select_connection.py", line 579, in poll
Feb  6 16:49:24 bullseye libretime-analyzer[49516]:     self._poller.poll()
Feb  6 16:49:24 bullseye libretime-analyzer[49516]:   File "/usr/local/lib/python3.9/dist-packages/pika/adapters/select_connection.py", line 1184, in poll
Feb  6 16:49:24 bullseye libretime-analyzer[49516]:     events = self._poll.poll(self._get_max_wait())
Feb  6 16:49:24 bullseye systemd[1]: Stopping LibreTime Media Analyzer Service...
Feb  6 16:49:24 bullseye libretime-analyzer[49516]:   File "/usr/local/lib/python3.9/dist-packages/libretime_analyzer/message_listener.py", line 136, in graceful_shutdown
Feb  6 16:49:24 bullseye libretime-analyzer[49516]:     self.disconnect_from_messaging_server()
Feb  6 16:49:24 bullseye libretime-analyzer[49516]:   File "/usr/local/lib/python3.9/dist-packages/libretime_analyzer/message_listener.py", line 128, in disconnect_from_messaging_server
Feb  6 16:49:24 bullseye libretime-analyzer[49516]:     if not self._channel.is_closed and not self._channel.is_closing:
Feb  6 16:49:24 bullseye libretime-analyzer[49516]: AttributeError: 'BlockingChannel' object has no attribute 'is_closing'

```

**Comment by jooola** [comment]
> Seems like the API is also hanging on stop/shutdown.

The API setup is sometimes hanging because the systemd unit is not properly configured to work with uwgsi.

I improved the configuration used when deploying with ansible https://github.com/LibreTime/ansible-role-libretime/blob/main/templates/systemd/libretime-api.service.j2

**Comment by paddatrapper** [comment]
Please upstream those changes into the api service file here

**Comment by jooola** [comment]
Those changes are almost in sync with the work on the installer in #1543. Also I wanted to address https://github.com/LibreTime/ansible-role-libretime/issues/10 before pushing this upstream.
