### ISSUE TITLE
Problem: Missing dependicies for python-rgain

### ISSUE THREAD

**Issue by HaJoHe** [LibreTime/libretime#128]
Hello,

at least for a dockerized installation, there are some missing dependicies to get replaygain working.

These are:
python-gst-1.0 gir1.2-gstreamer-1.0 gstreamer1.0-plugins-bad

**Comment by hairmare** [comment]
Depending on the distro you are using you can add these to one of the following:

* installer/lib/requirements-debian-jessie.apt
* installer/lib/requirements-debian-wheezy.apt
* installer/lib/requirements-ubuntu-precise.apt
* installer/lib/requirements-ubuntu-trusty.apt

Do you know why it needs plugins-bad?

**Comment by HaJoHe** [comment]
you're right... ugly should be ok.

**Comment by hairmare** [comment]
Are you installing python-rgain from pip? Maybe there is a proper package that already expresses the deps?

**Comment by HaJoHe** [comment]
Hi,
all installation has been done via the install script for ubuntu Trusty. Pip list shows, that it was installed via pip.

**Comment by hairmare** [comment]
The [debian package](https://packages.debian.org/jessie/python-rgain) requires plugins-good and recommends plugins-bad. It doesn't mention plugins-ugly though.

Looking at [ubuntu](http://packages.ubuntu.com/search?suite=all&searchon=names&keywords=rgain) the package from the distro looks a bit old. I'm not sure what the minimum requirements are on this package. 

Does anyone know what our minimum required version of replaygain is? I'd like to switch to an OS packaged one at some point if possible and we need to agree on a version to make that happen. Given that replaygain has a maintainer on Debian we should raise any issues with older version on  the distros respective bugtrackers.

If no one has any feedback on the minimum version I'll do a PR to move the install to apt soonish and we'll just figure out what version we need the "hard" way.

**Comment by HaJoHe** [comment]
You will need at least ugly for mp3 support.
From https://gstreamer.freedesktop.org/documentation/plugins.html
mpg123audiodec 	Decodes mp3 streams using the mpg123 library 	mpg123 	gst-plugins-ugly

**Comment by hairmare** [comment]
I see, thanks for the info. I'll add it to the installer when I add rgain.
