### ISSUE TITLE
Friends, I want to ask for help.

### ISSUE THREAD

**Issue by RTF6** [LibreTime/libretime#1286]
Our radio has not been able to restore the air for 2 months already. We have changed the server we have been working on for 5 years.
We started when there was still an airtime platform. In 2019, we switched to libertime.
Our assembly consisted of 16 ubuntu.
ssl 7.0.33 everything worked stably.
We worked without a PHP certificate.
We switched to 18 ubuntu. And the problems started that we didn’t know about.
Share a stable build for 18 ubuntu with a SSL certificate and working PHP.
![2021-08-10_14-53-01](https://user-images.githubusercontent.com/49484329/128863813-bbcdd437-5cd0-4722-b180-ae51c23698fd.png)

**Comment by paddatrapper** [comment]
I don't understand what you are trying to ask?

**Comment by RTF6** [comment]
> I don't understand what you are trying to ask?

What can you not understand? Libertime does not work for 18 Ubuntu.
Is there a stable build on ubuntu 18 with which you can work without errors in libertime? Or do all users work with 16 ubuntu libertime?
Tracks longer than 55 minutes change status to "offline" #1275
 Open  
https://github.com/LibreTime/libretime/issues/1275

**Comment by RTF6** [comment]
What configuration of the server software does not have this error.

**Comment by paddatrapper** [comment]
I would recommend using alpha.9 release then - https://github.com/LibreTime/libretime/releases/tag/3.0.0-alpha.9

**Comment by jbenz** [comment]
> > I don't understand what you are trying to ask?
> 
> What can you not understand? Libertime does not work for 18 Ubuntu.
> Is there a stable build on ubuntu 18 with which you can work without errors in libertime? Or do all users work with 16 ubuntu libertime?
> Tracks longer than 55 minutes change status to "offline" #1275

Yesterday I did a fresh install on debian 10 and have no issues with 61 minute files importing and streaming perfectly. 
If debian 10 is an option, worth considering.
