### ISSUE TITLE
Track type list is empty on default install

### ISSUE THREAD

**Issue by paddatrapper** [libretime/libretime#1300]
**Describe the bug**
When a new LT instance is created, there are no default track types and the install/set up documentation does not instruct the user to create any track types. This is confusing as the only item in the list is 'None'. You have to go to Settings -> Track Types to create a list and Settings -> General to set the default

**To Reproduce**

1. Create vagrant machine using `vagrant up debian-buster`
2. Step through install and restart components
3. Log in and go to Upload Track
4. See Track Type: None

**Expected behavior**
Either we need to improve the documentation and tell users to add track types, or we need to have a set of defaults that help in most cases.

**LibreTime version:** git ff96d55

**Installation method:**
- OS: Debian
- OS Version: Buster
- Method:  Vagrant `./install`

**Comment by jooola** [comment]
This is actually a database migration problem.

The following migration file clearly insert track types on migration, but seems broken.
https://github.com/LibreTime/libretime/blob/master/airtime_mvc/application/controllers/upgrade_sql/airtime_3.0.0-alpha.9.2/upgrade.sql

I don't know if inserting such data is a good default behavior.

**Comment by paddatrapper** [comment]
Looks like it needs adding to https://github.com/LibreTime/libretime/blob/master/airtime_mvc/build/sql/defaultdata.sql too
