### ISSUE TITLE
Untrimmed show heard in overlap with the next one

### ISSUE THREAD

**Issue by rocknowradio** [LibreTime/libretime#1310]
**Describe the bug**
Schedule two shows one after the other, in such a way that the first one has content longer than the show duration.
When the second show starts, the first show can be heard as well until it ends.

**To Reproduce**

1. Go to LT web UI.
2. Schedule one show say 13:00-14:00 and another one 14:00-15:00. First show contains 1h 3 mins length (the second 1h but it does not matter).
3. Schedule the shows.
4. When 14:00 mark is reached, both the first show content and the second show can be heard until the first show ends.

**Expected behavior**
First show should end (cutting the last 3 minutes from the 13:00-14:00 show overbooked with 3 mins) and the second should start. Instead, both are played.

**LibreTime version:**
cf75b14 (with #1309 manually applied)

**Installation method:**
- OS: Ubuntu
- OS Version 18.04.5 LTS (Bionic Beaver)
- Method: ./install -fiap
- Details: install script from downloaded package from the website

**Screenshots**
N/A

**Client (please complete the following information if applicable):**
- OS: Windows 10
- Browser: Chrome
- Version 92 (latest update)

**Comment by paddatrapper** [comment]
Duplicate of #1272, fixed in #1287

**Comment by rocknowradio** [comment]
Sorry, I didn't noticed the duplicate.
Just applied the patch and I will report back if fixed for me as well shortly.

**Comment by rocknowradio** [comment]
Well, I have applied the patch, restarted the services libretime-liquidsoap and libretime-playout, and the problem still manifests.
Are there other patches related to apply? Certain log entries to check for?

**Comment by rocknowradio** [comment]
Is it possible that the shows that were already created before I applied the patch to already have the cue_out incorrect, and only those created after the patch to have the correct cue_out?

**Comment by paddatrapper** [comment]
The cue_out is set on response from the API, so after restarting playout, the new values should be used

**Comment by rocknowradio** [comment]
So - if I understand correctly - suppose there is a show instance with duration of 8 minutes, containing 3 files for 3 minutes each.
In cc_schedule will be (assuming fade_in and fade_out are 0 for simplicity)
```
id starts   ends     clip_length cue_in   cue_out
-- -------- -------- ----------- -------- --------
1  00:00:00 00:03:00 00:00:03.0  00:00:00 00:03:00
2  00:03:00 00:06:00 00:00:03.0  00:03:00 00:06:00
3  00:06:00 00:09:00 00:00:03.0  00:06:00 00:09:00
```
but for the last row API v2 will get involved somehow at runtime and will return 00:02:00 (the end of show instance duration of 8 minutes) instead of 00:03:00 (which will overlap 1 minute into the next show instance) ?

If that is the case - and I assume it is reading the function get_cueout from models/schedule.py - then is there a log place where I can check if the cueout value is computed and used correctly?

The real case is:
```
airtime=> select id, starts, ends, file_id, clip_length, fade_in, fade_out, cue_in, cue_out from cc_schedule where instance_id = 19089 order by starts;
   id   |        starts         |         ends          | file_id | clip_length |  fade_in   |  fade_out  |  cue_in  |  cue_out
--------+-----------------------+-----------------------+---------+-------------+------------+------------+----------+------------
 671780 | 2021-08-24 11:00:00   | 2021-08-24 11:00:13.3 |     862 | 00:00:13.3  | 00:00:00.5 | 00:00:00.5 | 00:00:00 | 00:00:13.3
 671781 | 2021-08-24 11:00:13.3 | 2021-08-24 11:07:09.9 |    4947 | 00:06:56.6  | 00:00:00.5 | 00:00:00.5 | 00:00:00 | 00:06:56.5
 671782 | 2021-08-24 11:07:09.9 | 2021-08-24 11:15:39.7 |    1024 | 00:08:29.8  | 00:00:00.5 | 00:00:00.5 | 00:00:00 | 00:08:29.8
 671783 | 2021-08-24 11:15:39.7 | 2021-08-24 11:15:48.7 |    6092 | 00:00:09    | 00:00:00.5 | 00:00:00.5 | 00:00:00 | 00:00:08.9
 671784 | 2021-08-24 11:15:48.7 | 2021-08-24 11:22:32.4 |    2822 | 00:06:43.7  | 00:00:00.5 | 00:00:00.5 | 00:00:00 | 00:06:43.7
 671785 | 2021-08-24 11:22:32.4 | 2021-08-24 11:33:35.4 |    5376 | 00:11:03    | 00:00:00.5 | 00:00:00.5 | 00:00:00 | 00:11:03
 671786 | 2021-08-24 11:33:35.4 | 2021-08-24 11:33:44.4 |    6092 | 00:00:09    | 00:00:00.5 | 00:00:00.5 | 00:00:00 | 00:00:08.9
 671787 | 2021-08-24 11:33:44.4 | 2021-08-24 11:44:03.8 |     324 | 00:10:19.4  | 00:00:00.5 | 00:00:00.5 | 00:00:00 | 00:10:19.4
 671788 | 2021-08-24 11:44:03.8 | 2021-08-24 11:44:12.8 |    6092 | 00:00:09    | 00:00:00.5 | 00:00:00.5 | 00:00:00 | 00:00:08.9
 671789 | 2021-08-24 11:44:12.8 | 2021-08-24 11:50:09.9 |    1980 | 00:05:57.1  | 00:00:00.5 | 00:00:00.5 | 00:00:00 | 00:05:57.1
 671790 | 2021-08-24 11:50:09.9 | 2021-08-24 11:50:23.2 |     862 | 00:00:13.3  | 00:00:00.5 | 00:00:00.5 | 00:00:00 | 00:00:13.3
 671791 | 2021-08-24 11:50:23.2 | 2021-08-24 11:55:48.3 |    2455 | 00:05:25.1  | 00:00:00.5 | 00:00:00.5 | 00:00:00 | 00:05:25.1
 671792 | 2021-08-24 11:55:48.3 | 2021-08-24 12:02:56.4 |    3832 | 00:07:08.1  | 00:00:00.5 | 00:00:00.5 | 00:00:00 | 00:07:08
 671793 | 2021-08-24 12:02:56.4 | 2021-08-24 12:08:02   |    1888 | 00:05:05.6  | 00:00:00.5 | 00:00:00.5 | 00:00:00 | 00:05:05.6
 671794 | 2021-08-24 12:08:02   | 2021-08-24 12:08:15.3 |     862 | 00:00:13.3  | 00:00:00.5 | 00:00:00.5 | 00:00:00 | 00:00:13.3
 671795 | 2021-08-24 12:08:15.3 | 2021-08-24 12:20:29.6 |    1330 | 00:12:14.3  | 00:00:00.5 | 00:00:00.5 | 00:00:00 | 00:12:14.3
 671796 | 2021-08-24 12:20:29.6 | 2021-08-24 12:43:29.7 |     143 | 00:23:00.1  | 00:00:00.5 | 00:00:00.5 | 00:00:00 | 00:23:00
 671797 | 2021-08-24 12:43:29.7 | 2021-08-24 12:43:38.7 |    6092 | 00:00:09    | 00:00:00.5 | 00:00:00.5 | 00:00:00 | 00:00:08.9
 671798 | 2021-08-24 12:43:38.7 | 2021-08-24 13:01:32.2 |    5672 | 00:17:53.5  | 00:00:00.5 | 00:00:00.5 | 00:00:00 | 00:17:53.5
```
The last row has the cue_out equal with clip_length (00:17:53.5); the real cue_out should have been the difference between 13:00:00.0 - 12:43:38.7 which is 16:21.3.
Instead, in pypo.log I see:
```
...
'2021-08-24-12-43-38': {'start': datetime.datetime(2021, 8, 24, 12, 43, 38), 'end': datetime.datetime(2021, 8, 24, 13, 1, 32), 
'row_id': 671798, ... 'fade_in': 500.0, 'fade_out': 500.0, 'cue_in': 0.0, 'cue_out': 1073.5, 
'metadata': { ... 'length': '00:17:53.514300', ... 'cuein': '00:00:00', 'cueout': '00:17:53.514300', ... }

'2021-08-24-13-00-00': {'start': datetime.datetime(2021, 8, 24, 13, 0), 'end': datetime.datetime(2021, 8, 24, 13, 0, 8), 
'row_id': 671635, ... 'fade_in': 500.0, 'fade_out': 500.0, 'cue_in': 0.0, 'cue_out': 8.9, 
'metadata': {... 'length': '00:00:08.941875', ... 'cuein': '00:00:00', 'cueout': '00:00:08.941875', ... }
...
```
The second entry is the 8.9 seconds jingle starting the next show on 13:00.

The first entry is the one started at 12:43:38.7, with length 17:53.5 and show instance ending at 13:00:00, so the cueout should have been 
```00:13:00 - 00:12:43.38 - 0.5 sec fadein - 0.5 sec fade out = 960 ```
so approx. 960 seconds instead of 1073.5.

Does it make sense what I am describing here? 
Is it something that I can/should do to investigate more, add logger.log in certain places?
Obviously I can start hacking and spreading logging all over, but as usual a kick in the right direction would help tremendously.

**Comment by paddatrapper** [comment]
> If that is the case - and I assume it is reading the function get_cueout from models/schedule.py - then is there a log place where I can check if the cueout value is computed and used correctly?

It should be correct in the pypo log of the schedule response. Which it seems it is not judging by the log you posted... I think we need to see if we can get the test suite in `api/libretimeapi/tests/test_views.py` to fail in the way you are seeing, at least that should make it easier to debug

**Comment by rocknowradio** [comment]
That I am not sure, I'm still reading the code but for me is a long trip. 
Meanwhile I'll start the inverse function way, to make sure the implementation from the #1287 patch is ok and it's not some get_cue_out instead of get_cueout or something like that. At least to determine when this is called and why is not updating (or if it is not called, why).
If something arises - a fix or ... more questions - I will follow up.

**Comment by paddatrapper** [comment]
This is where the function is called and embedded into the serializer - https://github.com/LibreTime/libretime/blob/master/api/libretimeapi/serializers.py#L131

That serializer is what used to render the Schedule model into the view

**Comment by rocknowradio** [comment]
Sorry for not getting back sooner.
Monitored since last time, no more trouble on this issue. The patch fixes correctly the issue and for me it was a matter of reconfiguring.
Thank you guys for helping. Closing the issue as Fixed.
