### ISSUE TITLE
it is not possible to publish in mypodcast

### ISSUE THREAD

**Issue by chicco64** [LibreTime/libretime#1320]
I noticed that it is not possible to publish any audio tracks in the "mypodcast" section.
The "Publish" button does not give any results.
I have little experience with libretime yet, can you tell me if there is a solution? Thank you
<img width="704" alt="Capture1" src="https://user-images.githubusercontent.com/59960414/131828706-abc595f1-e215-42c6-9993-6097a7aa1ef4.PNG">

**Comment by paddatrapper** [comment]
Unfortunately the My Podcast feature is currently broken. It wasn't fixed when we forked from Airtime. It needs someone to work on it for it to be fixed

**Comment by chicco64** [comment]
I'm really sorry, I'm wondering if it is possible to remove the "Podcasts" and "My Podcast" buttons from the vertical menu on the left, and the relative "publish" buttons from the single tracks, by modifying the php code?

**Comment by jooola** [comment]
@chicco64 Should be doable. Would you like to do it ?

@paddatrapper Should we hide the podcast features before we ship v3 ?

**Comment by paddatrapper** [comment]
There is some discussion around it in #1108, and the consensus seems to be to remove it. So I think we can go ahead and do so. I'm happy with either before or after v3 beta depending on how things go

**Comment by jooola** [comment]
I was more thinking about hiding it, without removing much or the code. Again, because I would like to get v3 out

**Comment by jooola** [comment]
The discussion in #1108 seem to talk about the podcast following feature, but we are talking about mypodcast in this issue. Or maybe I din't understand properly.

I think the podcast following feature shouldn't be removed, the my podcast feature on the other hand could easily be re implemented and seem to be the broken piece.

**Comment by paddatrapper** [comment]
The podcast following feature works, it's the my podcast that doesn't. We should probably at least hide it and remove it later
