### ISSUE TITLE
Inviting new contibutors workflow is broken

### ISSUE THREAD

**Issue by jooola** [LibreTime/libretime#1323]
Currently the probot invite-contributors app isn't working: https://github.com/LibreTime/libretime/blob/master/.github/invite-contributors.yml

I don't really see why we should automatically add contributors as members. IMO, it could/should be done by hand if enough maintainers have permissions to add members.

I propose to add @paddatrapper as person capable of adding new members, and either remove or fix the invite-contributors app.

**Comment by paddatrapper** [comment]
The automation ensures that we adhere to C4 - https://rfc.zeromq.org/spec/42/#27-project-administration

**Comment by jooola** [comment]
C4 seems to describe how to promote a contributor as maintainer. And as far as I understand, someone opening a PR is already being a contributor, without being member of the Libretime organization.

I have been invited as contributor, I see that we have at team of >40 contributors, and most of them seem inactive. So maybe this organization is a bit overkill.

I think we should remove inactive members from the Libretime contributors team, and invite contributors manually. With this, we can allow members to have more capabilities to manage the project (edit labels, edit milestones, ...).

This makes me think that, I asked for write permissions on on labels/issues/milestones, I got added as member, but can't edit labels or milestones. Maybe this was intended that I can only do bug triage, but I was hoping to create a milestone/project for what comes after v3.

Additionally, since we want to follow C4, we should give @paddatrapper some more permissions, so we are not stuck when @Robbt or @hairmare are doing something else. We have hit this problem few times already with the community survey topic pinning and lowercasing the github project org.

Anyway, we can restore the invite-contributors app if maintainers think it is a good idea, I don't think it is useful.

cc @Robbt @hairmare
