### ISSUE TITLE
Sudo Bash Installation on Big Sur not happening

### ISSUE THREAD

**Issue by surface2air** [LibreTime/libretime#1325]
**Describe the bug**

Hi there, I downloaded the tar.gz file and extracted it on my Mac per instructions on the home page of your site (https://libretime.org/index), and tried to run a sudo bash install per these instructions in Terminal, but raised an "invalid flag" error.

**To Reproduce**

1. Go to 'Terminal'
2. Enter password'
3. Message received:
The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
bash-3.2# 
3. Follow instructions per message, and enter: chsh -s /bin/zsh
4. Enter command: install -fiap
5. Error message raised: install: iap: invalid flag

**Expected behavior**
Installation, possibly?

**LibreTime version:**
Version from the upgrade popup if you can reach it.

**Installation method:**

- OS: Mac OS
- OS Version Big Sur 11.5.2

**Comment by paddatrapper** [comment]
Linux is the only supported OS at the moment. You could try manually install the various components on mac, but I have no idea if they would work
