### ISSUE TITLE
Install entrypoints to default /usr/local/bin

### ISSUE THREAD

**Issue by jooola** [LibreTime/libretime#1343]
This issue is from this discussion https://github.com/LibreTime/libretime/pull/1342#issuecomment-918181773

> >I think we shouldn't install the scripts entry points in /usr/bin, as this is the path for system packages, using the default /usr/local/bin seems appropriate. @paddatrapper what do you think ?

> I agree, though we do need to be aware that packages may ship things to /usr/bin, so supporting that use case needs to be possible. Also in many instances /usr/local/bin is not in PATH

I don't have any idea of which packages installs to /usr/bin, maybe celery ? I will check

Regarding the presence of /usr/local/bin in PATH, I quickly check in docker images :

```sh
~/git/github.com/jooola/libretime $ docker run -it --rm debian:buster bash
root@a80f2df1f18d:/# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
root@a80f2df1f18d:/# exit

~/git/github.com/jooola/libretime $ docker run -it --rm ubuntu:focal bash
root@2a1573e3fabd:/# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
root@2a1573e3fabd:/# exit

~/git/github.com/jooola/libretime $ docker run -it --rm ubuntu:bionic bash
root@8dd8c213a44d:/# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
root@8dd8c213a44d:/# exit

~/git/github.com/jooola/libretime $ docker run -it --rm centos:7 bash
[root@b63179901d4f /]# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
[root@b63179901d4f /]# exit

~/git/github.com/jooola/libretime $ docker run -it --rm centos:8 bash
[root@445c5175db27 /]# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
[root@445c5175db27 /]# exit
```

**Comment by jooola** [comment]
After running `python setup.py install --record files.txt` in airtime-celery, celery does get installed in `/usr/local/bin/celery`.

I'll try with the other apps to check if we have some weird install paths. If not I'll propose a PR with a fix for this and #1350

**Comment by jooola** [comment]
I propose we add this to v3, as well as a pip based installation for the python apps. @paddatrapper Do you agree ?

**Comment by paddatrapper** [comment]
Yeah, sounds good
