### ISSUE TITLE
Pip does not support  --install-option="--install-scripts=/usr/bin"

### ISSUE THREAD

**Issue by jooola** [LibreTime/libretime#1350]
#1342 introduced a bug in the installer.

When installing the project in a vagrant box I get the following while install the python apps:
```
ERROR: Location-changing options found in --install-option: ['--install-scripts'] from command line. This is unsupported, use pip-level options like --user, --prefix, --root, and --target instead.
```

So we can either remove the option or revert to using setup.py instead of pip. I think using pip is a better idea, setup tools does not always resolve dependencies properly, and upgrading/uninstalling is cleaner using pip.

I propose to remove the install option and let pip install to /usr/local/bin.

Since the current state of the installer is broken on master, we should either resolve this fast or revert the commit from #1342 while we find a good solution for this.

Related to #1343

**Comment by paddatrapper** [comment]
For the moment, I think we should revert back to setup.py for the affected packages. Long term we should move, but that needs a migration path for existing installs

**Comment by paddatrapper** [comment]
Though if you have a chance to add that as part of the fix moving to /usr/local/bin, I'm happy with that too

**Comment by jooola** [comment]
I'll push a fix after some more testing.
