### ISSUE TITLE
API schedule return broken

### ISSUE THREAD

**Issue by paddatrapper** [LibreTime/libretime#1360]
**Describe the bug**
The schedule response from the API v2 is currently broken after #1356. The is_valid check logic is incorrect and results in errors as is_valid is a property and not a DB field.

**Comment by jooola** [comment]
Yup, sorry I didn't tested your PR, I'll try to do so, but this entire vagrant stuff is way too slow/complexe for quick testing.

**Comment by paddatrapper** [comment]
If you have a box up most of the time, it makes it fairly quick to test. The issue I find (at least on libvirt) is that I can't destroy and recreate a box without restarting my machine as the port-forwards do not come up correctly. Haven't had time to find a fix

**Comment by jooola** [comment]
While this issue has been fixed, the is_valid parameter is missing from the openapi specs.
