### ISSUE TITLE
Unclutter pypo logs from schedule update

### ISSUE THREAD

**Issue by jooola** [libretime/libretime#1367]
**Describe the bug**

Currently the pypo logs are mostly filled with new schedules updates. This is cluttering the logs a lot, what would be useful is to write the schedules updates in a dedicated file. An alternative would be to change the log level for this entry.

**Comment by paddatrapper** [comment]
It could probably be a debug message. Not sure if we can configure the logging level in the config file or not

**Comment by jooola** [comment]
Additionally what could be great it to dump each dict as json object in the file. One could use Promtail to send theses logs to Loki/Grafana or similar tools.
