### ISSUE TITLE
New install issue with libretime services

### ISSUE THREAD

**Issue by triangle-stream** [LibreTime/libretime#1389]
While attempting to install libretime on a fresh new vps (Ubuntu 18.04) some services such as playout and analyzer fail to start. I noticed that the libretime-playout service tries to execute /usr/bin/local/airtime-playout but airtime-playout is located in /usr/local/bin. If I try to run manually /usr/bin/airtime-playout it fails with an error on anyjson:
```
Traceback (most recent call last):
  File "/usr/bin/airtime-liquidsoap", line 4, in <module>
    __import__('pkg_resources').run_script('airtime-playout==1.0', 'airtime-liquidsoap')
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3242, in <module>
    @_call_aside
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'anyjson' distribution was not found and is required by airtime-playout
```

The server is updated and upgraded. The issue is also present on other fresh installs on other clean and new VPS.

**Comment by triangle-stream** [comment]
Thank you @paddatrapper 

The issue is present on a clean server, simply installing Libretime with install -fiap.

**Comment by jooola** [comment]
Could not reproduce this on the vagrant box while running from the main branch 6081dc161b8a4f31034929053ecb93bc3016394f and also the the pointed commit dfd34ba70049de4c1969ca845e7afaa58c24f9a7.

@triangle-stream Would you please provide more information about your setup so we can help you ?

**Comment by jooola** [comment]
@Wots-g I don't see how we can help you more than that, either you wait a bit for the fix to be released, or you use the workaround I proposed. If you need some help to merge a patch I am happy to help, but I don't see what else I can do.

**Comment by Wots-g** [comment]
> @Wots-g I don't see how we can help you more than that, either you wait a bit for the fix to be released, or you use the workaround I proposed. If you need some help to merge a patch I am happy to help, but I don't see what else I can do.



> @jooola, yeah I think we should probably cut a alpha.10 release ASAP to sort this. We need to do a battery of tests to ensure everything works as it currently stands before we can do that though

I can provide access to a virtual machine on proxmox, anydesk on windows 7 and debian 10 per vm?
