### ISSUE TITLE
Action "img" does not exist and was not trapped in __call()

### ISSUE THREAD

**Issue by kenrestivo** [libretime/libretime#1425]
Logging in
```
 2021-10-22T02:36:57+00:00 ERR (3): radio.foo.com
   [ErrorController.php:62 - errorAction()]
      - The requested action is not supported.: Zend_Controller_Action_Exception:
     Action "img" does not exist and was not trapped in __call()
    in /usr/share/airtime/php/legacy/vendor/zf1s/zend-controller/library/Zend/Controller/Action.php:485
	
Stack trace:
#0 /usr/share/airtime/php/legacy/vendor/zf1s/zend-controller/library/Zend/Controller/Action.php(518):
   Zend_Controller_Action->__call('imgAction', Array)
#1 /usr/share/airtime/php/legacy/vendor/zf1s/zend-controller/library/Zend/Controller/Dispatcher/Standard.php(308):
   Zend_Controller_Action->dispatch('imgAction')
#2 /usr/share/airtime/php/legacy/vendor/zf1s/zend-controller/library/Zend/Controller/Front.php(954):
    Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http),
	   Object(Zend_Controller_Response_Http))
#3 /usr/share/airtime/php/legacy/vendor/zf1s/zend-application/library/Zend/Application/Bootstrap/Bootstrap.php(105):
     Zend_Controller_Front->dispatch()
#4 /usr/share/airtime/php/legacy/vendor/zf1s/zend-application/library/Zend/Application.php(391):
     Zend_Application_Bootstrap_Bootstrap->run()
#5 /usr/share/airtime/php/legacy/application/airtime-boot.php(90):
     Zend_Application->run()
#6 /usr/share/airtime/php/legacy/public/index.php(72):
     require_once('/usr/share/airt...')
#7 {main}
```

**To Reproduce**

1. Log in
3. Look in /var/log/airtime/zendphp.log

**Expected behavior**
No weird squirrely errors in logs

**LibreTime version:**
fc2f0ad8428f7d04c38a6f6ca4d754139201b215

**Installation method:**

- OS: buster 10
- OS Version  buster 10
- Method: ./install -fiap
- Details:   ./install -fiap

Seems to work, but that's weird.

**Comment by jooola** [comment]
@kenrestivo Hey, sorry it has been a while since then, but could you provide use the url that triggered the error ?

So we can reproduce this and fix the bug.

**Comment by jooola** [comment]
This happens when calling an url with the following form `http://localhost:8080/locale/img`, where Zend tries to find the `imgAction` in the `LocaleController`. The beginning of that url has to refer to a valid controller, or you should hit 404 as expected.

This error is harmless, the only way for us to maybe fix that is to have the exact url hitting your server.

https://framework.zend.com/manual/1.11/en/zend.controller.exceptions.html#zend.controller.exceptions.internal
