### ISSUE TITLE
No module named 'pypo.notify'

### ISSUE THREAD

**Issue by SpaceTrucker2196** [LibreTime/libretime#1428]
**Describe the bug**

When trying to play tracks I'm getting an error for pypo.nofiy 

2021/11/02 22:45:18 [alsa_out(default):3] Samplefreq=44100Hz, Bufsize=32768B, Frame=4B, Periods=74
Nov 02 22:45:18 zebFM libretime-liquidsoap[17964]: Traceback (most recent call last):
Nov 02 22:45:18 zebFM libretime-liquidsoap[17964]:   File "/usr/local/bin/libretime-playout-notify", line 6, in <module>
Nov 02 22:45:18 zebFM libretime-liquidsoap[17964]:     from pypo.notify.main import run
Nov 02 22:45:18 zebFM libretime-liquidsoap[17964]: ModuleNotFoundError: No module named 'pypo.notify'
Nov 02 22:45:18 zebFM libretime-liquidsoap[17964]: Traceback (most recent call last):
Nov 02 22:45:18 zebFM libretime-liquidsoap[17964]:   File "/usr/local/bin/libretime-playout-notify", line 6, in <module>
Nov 02 22:45:18 zebFM libretime-liquidsoap[17964]:     from pypo.notify.main import run
Nov 02 22:45:18 zebFM libretime-liquidsoap[17964]: ModuleNotFoundError: No module named 'pypo.notify'
**To Reproduce**

After a clean install and successfully importing a few tracks.

After creating a new show and adding a track. 

**Expected behavior**
expecting the On-Air indicator to stay lit and track being to play.

**LibreTime version:**
3.0.0-alpha.10

**Installation method:**
021-05-07-raspios-buster

installed with $ sudo bash install -fiap

**Comment by paddatrapper** [comment]
I can replicate this issue using the current master branch. It works if libretime-playout is installed as an editable package `pip install -e .`, but not if installed uneditable.

**Comment by SpaceTrucker2196** [comment]
thanks! Replicated issues make the world turn. Have a great day!
