### ISSUE TITLE
./install command not found

### ISSUE THREAD

**Issue by jooola** [LibreTime/libretime#1434]
**Describe the bug**

The installer is throwing the following error:
```
./install: line 113: python3 -m pip install --upgrade setuptools~=58.0: command not found
```

This error was introduced by #1430, with a quoting issue. Bash didn't found the `"python3 -m pip install --upgrade setuptools~=58.0"` command.

We could either revert to using eval, or properly fix the quoting

This happens on the main branch the 9/11/2021

**Comment by paddatrapper** [comment]
For the moment we should probably revert to eval and then can look at fixing it
