### ISSUE TITLE
Handling security vulnerability reports

### ISSUE THREAD

**Issue by paddatrapper** [libretime/libretime#1438]
We need to decide on, and publish, how we handle security vulnerabilities.

The key things around that are:

1. Notification process - how do the maintainers get notified in a confidential way
2. Embargo length - how long after notification is the vulnerability allowed to be made public by the reporter
3. Release coordination - how do we distribute the fix

Point 1 I don't know how to address. Maybe we can setup a mail-forwarding address that we can then point people to?

On point 2, I think maybe 2-3 weeks (14-21 days). This should give us enough time to fix the issue, but not too long

For Point 3, currently we only support the latest release because LT is still in alpha. Thus, I suggest we cut a new release as the method of distributing the fix. Once 3.0 is out, we will probably need to define which versions we support and for how long, then make point releases for each.

**Comment by jooola** [comment]
I had a little laugh when I first read this, I mean we should totally tackle this, but with the current state of the codebase and the dependencies... :laughing:

For 1. I would suggest first an entry in the issue template chooser, linked to a SECURITY.md file somewhere in the repo.

For 2. My concern is actually how does people get notifier from this vulnerability ?
Is the discourse platform actually the best tool ? I disabled most of the notification so I expect other to do the same.
Maybe such notifications (release and security notice) would be send via a dedicated newsletter ?

**Comment by paddatrapper** [comment]
> For 1. I would suggest first an entry in the issue template chooser, linked to a SECURITY.md file somewhere in the repo.

It doesn't look like GitHub supports confidential issues, so I'm not sure reporting to the GitHub issue tracker is the best way to go. The whole point of reporting a security vulnerability is to allow time for it to be fixed before it is made public... A SECURITY.md file is definitely the way to document whatever our solution is, but it isn't the solution itself.

> For 2. My concern is actually how does people get notifier from this vulnerability ?
Is the discourse platform actually the best tool ? I disabled most of the notification so I expect other to do the same.
Maybe such notifications (release and security notice) would be send via a dedicated newsletter ?

We can create [Security Advisories](https://docs.github.com/en/code-security/security-advisories/about-github-security-advisories)

**Comment by jooola** [comment]
> It doesn't look like GitHub supports confidential issues, so I'm not sure reporting to the GitHub issue tracker is the best way to go. The whole point of reporting a security vulnerability is to allow time for it to be fixed before it is made public... A SECURITY.md file is definitely the way to document whatever our solution is, but it isn't the solution itself.

Yet, I forgot to say that I agree with the idea of using a mail for reporting.

**Comment by jooola** [comment]
This depends on https://github.com/libretime/organization/issues/7 as we need to setup some emails addresses.
