### ISSUE TITLE
Clock indicators displays wrong duration, elapsed and remaining time

### ISSUE THREAD

**Issue by xabispacebiker** [libretime/libretime#1440]
**Describe the bug**
On a fresh install, Clock indicators displays wrong duration, elapsed and remaining time

**To Reproduce**

1. Schedule something
2. The first seconds the display is right.
3. After a few seconds, the time display changes to wrong times

**Expected behavior**
It should display the correct duration, elapsed and remaining times

**LibreTime version:**
Lates from git, I am not sure but I think it is 3.0.0-alpha.10

**Installation method:**

- OS: Debian
- OS Version 11 Bullseye
- Method: install -fiap
- Details: git clone https://github.com/libretime/libretime.git

**Screenshots**
<img width="374" alt="Captura de pantalla 2021-11-13 a las 11 33 15" src="https://user-images.githubusercontent.com/1733884/141615487-59e945a7-6e84-4cae-8372-e5428d7d2dbc.png">

**Comment by zklosko** [comment]
Do you have your time zone set correctly? Wondering if the server is debating on which time zone to use: the one set by the system or the one set by the user account in Libretime.
