### ISSUE TITLE
Analyzer 's silence detection is not working

### ISSUE THREAD

**Issue by jooola** [LibreTime/libretime#1452]
**Describe the bug**

A file that has a long silence at it's end didn't receive an earlier cue out from the analyzer. I though this was supposed to be trimmed out by silan.

**To Reproduce**

1. Play the file
2. Experience silence at the end of the track.

**Expected behavior**

Silence should be trimmed out. Using cue_out detected by the analyzer.

**LibreTime version:** alpha 10

- OS: Debian 10

**Additional context**

The audio file:  
[Hocus Pocus - Petit pays.zip](https://github.com/LibreTime/libretime/files/7612046/Hocus.Pocus.-.Petit.pays.zip)

**Comment by paddatrapper** [comment]
This could be a silan bug or a bug in how we process the output

**Comment by jooola** [comment]
I suspect this to be solved with #1249
