### ISSUE TITLE
LibreTime stops generating calendar after 1 Year

### ISSUE THREAD

**Issue by Chris-The-Tuner** [libretime/libretime#1459]
**Describe the bug**
So i have a Instance running since 2020 which did work great without many issues.
Bus this year it decided that 26 of Dec is the Last day do have program.
All Shows are based on monthly (day of week) repeating, no end date set.

When i try to open the calendar of this month the page loads for a while until Apache times out.

At least a few of my fellow Radio makers did set their "look" to "week" so they can open the calendar at least, since mine was set to "month" my calendar page does not load.

I suspect that something in the database broke (probably full with stuff) ?
I have no clue how to even tackle this but i'm in a big hurry since this instance is Air-Critical for our local radio station and i'm afraid of it stopping our program right when the 27 of Dec comes.

Only Error i get anything from:
`PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 4096 bytes) in /usr/share/airtime/php/vendor/propel/propel1/runtime/lib/connection/PropelPDO.php`

**To Reproduce**
I would like to get this right but in my case: Leave LibreTime running 1 Year as a Air-Critical System for a local Radio station ?

**Expected behavior**
I expect to have a always generating calendar :)

**Installation method:**

- OS: Debian 10 (Buster)
- Method: Install script (as on webpage)

For any advice (what logs should i put here) just let me know.
I would post something but the only message i find is the timeout on the PHP script from the page :(

**Comment by Robbt** [comment]
Ok, can you check out /var/log/airtime/zendphp.log and see what errors might be in the log ?

**Comment by Chris-The-Tuner** [comment]
Here you go with the only stuff i find is strange, everything else is fine.
Even this cc_prefs error was there right after a fresh install (still is i have a private one that throws this right after installing)

`2021-12-21T19:46:35+01:00 WARN (4): radairtime.rad.ar SQLSTATE[55P03]: Lock not available: 7 FEHLER:  konnte Sperre für Zeile in Relation »cc_pref« nicht setzen
2021-12-21T19:46:57+01:00 WARN (4): radairtime.rad.ar SQLSTATE[55P03]: Lock not available: 7 FEHLER:  konnte Sperre für Zeile in Relation »cc_pref« nicht setzen
2021-12-21T19:52:32+01:00 WARN (4): radairtime.rad.ar SQLSTATE[55P03]: Lock not available: 7 FEHLER:  konnte Sperre für Zeile in Relation »cc_pref« nicht setzen
2021-12-21T19:56:43+01:00 ERR (3): 10.0.0.16 [Logging.php:166 - loggingShutdownCallback()] - Allowed memory size of 536870912 bytes exhausted (tried to allocate 4096 bytes) at /usr/share/airtime/php/vendor/propel/propel1/runtime/lib/conne
ction/PropelPDO.php:406
array (
  'type' => 1,
  'message' => 'Allowed memory size of 536870912 bytes exhausted (tried to allocate 4096 bytes)',
  'file' => '/usr/share/airtime/php/vendor/propel/propel1/runtime/lib/connection/PropelPDO.php',
  'line' => 406,
)
2021-12-21T20:00:01+01:00 WARN (4): 10.0.0.16 SQLSTATE[55P03]: Lock not available: 7 FEHLER:  konnte Sperre für Zeile in Relation »cc_pref« nicht setzen`

**Comment by Chris-The-Tuner** [comment]
So i investigated a bit more.
I tried to move the DB to a fresh system.
Installed LibreTime current Version via Install Script an a fresh server. (Hardware System etc. 1:1 with the old one even the DANTE Card is the same)
After successful install i dumped the contents of the old one right into the new DB and the error is recreated !

So it seems like a DB Problem, sadly i'm really not good with PostgreSQL therefore i'm totally lost.

Someone want to have a go on it ?
I could hand out the dump of the DB for research if needed.
