### ISSUE TITLE
Couldn't establish a connection to the database! - Debian 8.7

### ISSUE THREAD

**Issue by celiandu61** [LibreTime/libretime#146]
Hey, i'm trying to install libretime on my OVH VPS but on the first step of config page i got an error to connect to database.
![capture du 2017-04-06 22-28-27](https://cloud.githubusercontent.com/assets/6912744/24774212/64fc3a34-1b18-11e7-9f5c-07eb263b33fc.png)

rabbit server is up, i tried to re-set the password manually but no results ... 

I tried to install it exactly with the same method ( 5 try or more ) on a dply server and that work perfectly ( just use ./install ) ! There are on the same OS (debian 8.7), an IPV4 and an IPV6, same kernel (3.16.39-1+deb8u2 (2017-03-07)), same repo list and there are KVM server.

If somebody have an idea ! Ask me if you need more information.

**Comment by hairmare** [comment]
Weird. Can you connect to the database using `psql` on the command line?

**Comment by celiandu61** [comment]
No, i can't.
![capture du 2017-04-06 22-59-25](https://cloud.githubusercontent.com/assets/6912744/24775352/b93c4b30-1b1c-11e7-988f-6ced27b653dc.png)

**Comment by celiandu61** [comment]
I tried that but there is no socket created ...
http://stackoverflow.com/questions/31645550/why-psql-cant-connect-to-server

**Comment by celiandu61** [comment]
Ok, i found that in the log after trying to connect from settings page.
`2017-04-06 23:41:10 CEST [14822-1] LOG:  database system was shut down at 2017-04-06 23:33:40 CEST
2017-04-06 23:41:10 CEST [14822-2] LOG:  MultiXact member wraparound protections are now enabled
2017-04-06 23:41:10 CEST [14821-1] LOG:  database system is ready to accept connections
2017-04-06 23:41:10 CEST [14826-1] LOG:  autovacuum launcher started
2017-04-06 23:41:11 CEST [14828-1] [unknown]@[unknown] LOG:  incomplete startup packet
2017-04-06 23:41:50 CEST [14851-1] airtime@postgres FATAL:  password authentication failed for user "airtime"
2017-04-06 23:41:50 CEST [14851-2] airtime@postgres DETAIL:  Connection matched pg_hba.conf line 92: "host    all             all             127.0.0.1/32            md5"
2017-04-06 23:41:50 CEST [14852-1] airtime@postgres FATAL:  password authentication failed for user "airtime"
2017-04-06 23:41:50 CEST [14852-2] airtime@postgres DETAIL:  Connection matched pg_hba.conf line 92: "host    all             all             127.0.0.1/32            md5"
`

**Comment by hairmare** [comment]
Maybe OVH has a special DB config out of the box for security reasons. On CentOS I usually need to prepare the db [as document on my legacy docs](https://github.com/radiorabe/airtime#database-setup). If you figure this out I'd be glad to add it to the [preparing a server docs](http://libretime.org/manual/preparing-the-server/).

**Comment by Robbt** [comment]
Did you type Y when asked if you wanted to create the database user etc ? My guess is that you might have typed y instead (which reasonably seems like it would work) but if I recall there might still be a bug that basically treats y as no and only accepts Y. I recommend installing with sudo ./install -fiap or running ./install -fiap from root as this ignores the prompts etc which are only useful if you are installing on top of an old server. I'll try to confirm that this bug is still there and open an issue. I'm not sure if this is the issue that you ran into but I have my suspicion. Can you try just installing again with ./install -fiap and see if you run into the same issue ?

**Comment by celiandu61** [comment]
>  -----------------------------------------------------
>               * Configuring PostgreSQL *
> -----------------------------------------------------
> perl: warning: Setting locale failed.
> perl: warning: Please check that your locale settings:
>         LANGUAGE = (unset),
>         LC_ALL = (unset),
>         LANG = "fr_FR.UTF-8"
>     are supported and installed on your system.
> perl: warning: Falling back to the standard locale ("C").
> could not change directory to "/root/libretime": Permission denied
> psql: could not connect to server: No such file or directory
>         Is the server running locally and accepting
>         connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

I found that in log after trying  ./install -fiap ( exec in root )

**Comment by celiandu61** [comment]
I used that to fix the perl error but idk why it said permission denied, it's launched as root.

**Comment by hairmare** [comment]
I'm assuming /root/libretime is the location of your working copy. The permission denied doesn't really make sense :/

The "psql: could not connect to server" looks like PostgreSQL isn't running at all.

**Comment by celiandu61** [comment]
Yes but the service is up :/ If you have any idea i can try it.

**Comment by hairmare** [comment]
I think it can't create the airtime postgresql user. Does creating it manually as follows work?

```bash
sudo -u postgres psql -d postgres -tAc "CREATE USER airtime WITH ENCRYPTED PASSWORD 'airtime'; ALTER USER airtime CREATEDB;"
```

**Comment by celiandu61** [comment]
Found the problem. OVH doesn't set by default the LOCALE LANG --' After set it just purge postgresql, install it and use 
`sudo -u postgres psql -d postgres -tAc "CREATE USER airtime WITH ENCRYPTED PASSWORD 'airtime'; ALTER USER airtime CREATEDB;"`
to init it ;) 

Thx for your help !

**Comment by JohnnyC1951** [comment]
I sent an email to @Robbt about this. I found another problem that causes this.
