### ISSUE TITLE
Celery worker crashes

### ISSUE THREAD

**Issue by Robbt** [LibreTime/libretime#147]
I am running airtime-celery on a upgraded machine and running into this error - 
 Unrecoverable error: TypeError("'NoneType' object is not callable",)
This is evidently an issue with rabbitmq and celery - https://github.com/celery/py-amqp/issues/113 which is tied to https://github.com/celery/celery/pull/3752 prevent consuming queue before ready on startup (#3752)

**Comment by Robbt** [comment]
The workaround fix was to run sudo pip install -U git+http://github.com/Eugeny/celery#egg=celery==4.0.2.1
which installed a version of celery with the above mentioned fix. 
We should determine if this error is cropping up on other systems including the vagrant ones.

**Comment by hairmare** [comment]
This seems to be a very recent issue with celery, hence the need for upgrading to the patched celery. I'm hoping celery does a release soonish as requested by  https://github.com/celery/celery/pull/3752#issuecomment-287718734.

**Comment by hairmare** [comment]
Maybe there is an older version of celery that does not have this problem? Switching to that might be a quick fix rather than waiting for upstream to do a release.

**Comment by Robbt** [comment]
Yeah I think that things were designed for celery 3 as 4 was recently released. I didn't look into how to tell pip to install 3 vs. 4 but I think that would work.

**Comment by hairmare** [comment]
It's probably just a case of writing `'celery==$version'` like [analyzer does](https://github.com/LibreTime/libretime/blob/master/python_apps/airtime_analyzer/setup.py#L38) for some libs.

**Comment by Robbt** [comment]
I'm going to put it at the latest celery version and test it 3.0.19 to ensure that it works. If we every want to upgrade to celery 4 after this is fixed we can do that.
