### ISSUE TITLE
Scheduled tracks and podcasts are at least 1 hour behind

### ISSUE THREAD

**Issue by EuropeanManager** [libretime/libretime#1486]
I am running Libretime on ubuntu 18.04.05 TLS
LibreTime Version | 2003e685b

I am not sure even how to explain it to be understood correctly but I will try. 
We are playing podcasts (from 1 hour long) and everything was fine for a year or so, had no issues with the system. However, just yesterday I've noticed that all the podcasts are at least 1 hour behind, however:

1. In Libretime admin panel I can see that the PREVIOUS track was the one which is playing at the moment and on the left side you can see that the required track should be playing as it reflects on the "now playing" tab. 
2. In icecast admin panel I see that the CURRENT playing track is the one which is shown as PREVIOUS in Libretime admin panel.
3. I grab "Now playing" from icecast panel to show it on the 3rd party website - it shows that the CURRENT  playing track is the one which is shown as PREVIOUS in Libretime admin panel.

Even in the analytics playout history it is shown that everything is playing according the schedule I have. However, the reality is different. I think that's the system somehow got 1 hour late because it looks exactly like it.

I have some screenshots but I won't be sharing them here in public as it has some sensitive data.

**Comment by paddatrapper** [comment]
Is there any Daylight Savings Time involved in your locale? Also if you restart libretime-liquidsoap and libretime-playout, does it remain out of time?

**Comment by EuropeanManager** [comment]
> Is there any Daylight Savings Time involved in your locale? Also if you restart libretime-liquidsoap and libretime-playout, does it remain out of time?

What do you mean "Daylight Savings Time"? I've tried to restart but I need some time to see if the issue occurs.

**Comment by paddatrapper** [comment]
> What do you mean "Daylight Savings Time"?

Does the country you are based use Daylight Savings Time?

**Comment by EuropeanManager** [comment]
> > What do you mean "Daylight Savings Time"?
> 
> Does the country you are based use Daylight Savings Time?

Oh, nono we have 24/7/365 power/internet/water/gas supply, it's Europe.

**Comment by EuropeanManager** [comment]
> Is there any Daylight Savings Time involved in your locale? Also if you restart libretime-liquidsoap and libretime-playout, does it remain out of time?

Well... I restarted liquidsoap and playout and it seems it fixed the situation hopefully. Now the schedule is respected. Thanks!

**Comment by paddatrapper** [comment]
Daylight savings is the practice of changing the clocks forward and back by an hour at certain times in the year - https://en.wikipedia.org/wiki/Daylight_saving_time

**Comment by EuropeanManager** [comment]
> Daylight savings is the practice of changing the clocks forward and back by an hour at certain times in the year - https://en.wikipedia.org/wiki/Daylight_saving_time

So the issue still occurs after restarting those two mentioned above. 
And yes, omg, we do have this changing the clocks stuff.. But we did not changed it recently and I believe we did it at least once while I am using this software.
