### ISSUE TITLE
could not obtain lock on row in relation "cc_pref"

### ISSUE THREAD

**Issue by jooola** [libretime/libretime#1490]
**Describe the bug**

I find a log of these entries that clutter the zendphop.log file :
```
2022-01-06T09:26:00+01:00 WARN (4): radio.org SQLSTATE[55P03]: Lock not available: 7 ERROR:  could not obtain lock on row in relation "cc_pref"
```

I don't know if it is harmless, but it should be dealt with I think.

**Comment by samkitk** [comment]
My playout service is failing and I am encountering the same issue

**Comment by jooola** [comment]
@samkitk Please open a dedicated issue so we can have more details about your setup. Also the `could not obtain lock on row in relation "cc_pref"` log entry should not affect playout.
