### ISSUE TITLE
Replace rabbitmq with redis

### ISSUE THREAD

**Issue by jooola** [LibreTime/libretime#1501]
Here is the crazy idea: replacing rabbitmq with redis.

RabbitMQ is overkill and complex for the few messages we are trying to send. Redis would be more suited for our needs.

**Comment by zklosko** [comment]
Are you envisioning this to go in the 3.0 beta or the rewrite?

**Comment by jooola** [comment]
This is how I understand it, as long the bulk import feature (and other blocking tickets) is either implemented or delayed for v4, almost anything not drastic could be merged before 3.0 beta.

For me to tackle these missing features, I prefer to have working base blocks before building on top of it (like the config file format for instance).

That being said, if replacing rabbitmq with redis makes implementing these missing feature easier, then it might land, or simply if I feel like I want to work on this.

So I can't really say.

**Comment by zklosko** [comment]
Closing this as per your post in #1610
