### ISSUE TITLE
Publish python apps to pypi

### ISSUE THREAD

**Issue by jooola** [libretime/libretime#1504]
I propose to publish the different packages to pip.

This would reduce some dependency problem we have with the api_client and the shared package.

But this could also allow some to install some apps using pip.

**Comment by paddatrapper** [comment]
Do we want to track a single version number for all the apps or version them individually?

**Comment by jooola** [comment]
I think we can share the major version between apps, but manage minor/ patch versions individually ? I haven't put much thoughts at what could become a nightmare if we do this.

For now everything is still alpha, so I am trying to think what we need in the future.

**Comment by paddatrapper** [comment]
That does make using semantic-commits tricky. I think the only thing that will be easily supported there is a single version number for everything...

**Comment by jooola** [comment]
Yes, you are right, might introduce some nightmare logic.

The main problem I have with a single version number across apps, is that it make releasing versions harder, and less often. If we want to release a small patch for the api_client or the shared we have to bump everything while nothing might have changes elsewhere.

Currently Libretime release very few release, and have a low feedback rate from users, I would not want that velocity to prevent delivering fixes/feature for internal changes. A way to mitigate would be to work with version branches, so we can push fixes to the previous version branch and release faster without introducing untested features.

This idea seems more complex than expected, as I didn't thought about the versioning part of it. For now we are still in alpha maybe we can take advantage of that and versions everything as alpha.

I am now less convinced that publishing to pip is a good idea. Maybe with a dedicated version for each app this would make it easier. But that would mean reduce the number of app we have.

**Comment by paddatrapper** [comment]
Versioning everything as alpha still has the same considerations required - we can't publish the same version to pypi twice, so it will need some sort of differentiator.

The APIv2 client, when we get round to generating them, can be a separate repo with separate versioning and uploaded to pypi easily. The shared library is a bit more tricky and I'm not sure how to approach it.

**Comment by jooola** [comment]
Until we are a python only project I don't think this is worth it, put aside the versioning problems.

Closing for now, we can always reopen once in this future without PHP.
