### ISSUE TITLE
playout & liquidsoap service not starting after upgrade

### ISSUE THREAD

**Issue by maydo** [LibreTime/libretime#1514]
Hi,

i have just upgraded my old LT installation to latest 4443528
not sure which version was the old, must be 2020 i think

playout & liquidsoap services are not more starting, 

on ubuntu 18.04.
i did a
git pull
bash install -fiap

i have also tried the uninstall and install script
they run without errors, but both services still not start
there is no logs in the new or old log path in /var/log

from journalctl 
```
-- Automatic restarting of the unit libretime-playout.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
Jan 14 11:31:56 radyo1128 systemd[1]: Stopped Libretime Playout Service.
-- Subject: Unit libretime-playout.service has finished shutting down
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit libretime-playout.service has finished shutting down.
Jan 14 11:31:56 systemd[1]: libretime-playout.service: Start request repeated too quickly.
Jan 14 11:31:56 systemd[1]: libretime-playout.service: Failed with result 'exit-code'.
Jan 14 11:31:56 systemd[1]: Failed to start Libretime Playout Service.
-- Subject: Unit libretime-playout.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit libretime-playout.service has failed.
```

```
systemctl status libretime-playout
● libretime-playout.service - Libretime Playout Service
   Loaded: loaded (/etc/systemd/system/libretime-playout.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2022-01-14 11:47:58 CET; 6s ago
  Process: 27542 ExecStart=/usr/local/bin/libretime-playout (code=exited, status=1/FAILURE)
 Main PID: 27542 (code=exited, status=1/FAILURE)

Jan 14 11:47:58 systemd[1]: libretime-playout.service: Service hold-off time over, scheduling
Jan 14 11:47:58 systemd[1]: libretime-playout.service: Scheduled restart job, restart counter
Jan 14 11:47:58 systemd[1]: Stopped Libretime Playout Service.
Jan 14 11:47:58 systemd[1]: libretime-playout.service: Start request repeated too quickly.
Jan 14 11:47:58 systemd[1]: libretime-playout.service: Failed with result 'exit-code'.
Jan 14 11:47:58 systemd[1]: Failed to start Libretime Playout Service.
```

PS: output stream does also not connect, but maybe couse of missing playout service ?
any ideas ?

**Comment by paddatrapper** [comment]
Can you post the full log from `journalctl -fu libretime-playout`?

**Comment by maydo** [comment]
# journalctl -fu libretime-playout
-- Logs begin at Fri 2019-03-22 02:03:03 CET. --
Jan 14 12:59:46 libretime-playout[2757]:     raise TypeError("Cannot log to objects of type '%s'" % type(sink).__name__)
Jan 14 12:59:46 libretime-playout[2757]: TypeError: Cannot log to objects of type 'bytes'
Jan 14 12:59:46 systemd[1]: libretime-playout.service: Main process exited, code=exited, status=1/FAILURE
Jan 14 12:59:46 systemd[1]: libretime-playout.service: Failed with result 'exit-code'.
Jan 14 12:59:46 systemd[1]: libretime-playout.service: Service hold-off time over, scheduling restart.
Jan 14 12:59:46 systemd[1]: libretime-playout.service: Scheduled restart job, restart counter is at 5.
Jan 14 12:59:46 systemd[1]: Stopped Libretime Playout Service.
Jan 14 12:59:46 systemd[1]: libretime-playout.service: Start request repeated too quickly.
Jan 14 12:59:46 systemd[1]: libretime-playout.service: Failed with result 'exit-code'.
Jan 14 12:59:46 systemd[1]: Failed to start Libretime Playout Service.

**Comment by jooola** [comment]
I guess this has something to do with #1495 

Could you either post your log file `/var/log/libretime/playout.log` or give us more logs from journactl using `journalctl -n 100 -fu libretime-playout`

**Comment by maydo** [comment]
Jan 14 14:13:56 radyo1128 libretime-playout[8745]: Traceback (most recent call last):
Jan 14 14:13:56 radyo1128 libretime-playout[8745]:   File "/usr/local/bin/libretime-playout", line 33, in <module>
Jan 14 14:13:56 radyo1128 libretime-playout[8745]:     sys.exit(load_entry_point('libretime-playout==1.0', 'console_scripts', 'libretime-playout')())
Jan 14 14:13:56 radyo1128 libretime-playout[8745]:   File "/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
Jan 14 14:13:56 radyo1128 libretime-playout[8745]:     return self.main(*args, **kwargs)
Jan 14 14:13:56 radyo1128 libretime-playout[8745]:   File "/usr/lib/python3/dist-packages/click/core.py", line 697, in main
Jan 14 14:13:56 radyo1128 libretime-playout[8745]:     rv = self.invoke(ctx)
Jan 14 14:13:56 radyo1128 libretime-playout[8745]:   File "/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
Jan 14 14:13:56 radyo1128 libretime-playout[8745]:     return ctx.invoke(self.callback, **ctx.params)
Jan 14 14:13:56 radyo1128 libretime-playout[8745]:   File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
Jan 14 14:13:56 radyo1128 libretime-playout[8745]:     return callback(*args, **kwargs)
Jan 14 14:13:56 radyo1128 libretime-playout[8745]:   File "/usr/local/lib/python3.6/dist-packages/libretime_playout/main.py", line 118, in cli
Jan 14 14:13:56 radyo1128 libretime-playout[8745]:     setup_logger(level_from_name(log_level), log_filepath)
Jan 14 14:13:56 radyo1128 libretime-playout[8745]:   File "/usr/local/lib/python3.6/dist-packages/libretime_shared/logging.py", line 81, in setup_logger
Jan 14 14:13:56 radyo1128 libretime-playout[8745]:     logger.configure(handlers=handlers)
Jan 14 14:13:56 radyo1128 libretime-playout[8745]:   File "/usr/local/lib/python3.6/dist-packages/loguru/_logger.py", line 1689, in configure
Jan 14 14:13:56 radyo1128 libretime-playout[8745]:     return [self.add(**params) for params in handlers]
Jan 14 14:13:56 radyo1128 libretime-playout[8745]:   File "/usr/local/lib/python3.6/dist-packages/loguru/_logger.py", line 1689, in <listcomp>
Jan 14 14:13:56 radyo1128 libretime-playout[8745]:     return [self.add(**params) for params in handlers]
Jan 14 14:13:56 radyo1128 libretime-playout[8745]:   File "/usr/local/lib/python3.6/dist-packages/loguru/_logger.py", line 824, in add
Jan 14 14:13:56 radyo1128 libretime-playout[8745]:     raise TypeError("Cannot log to objects of type '%s'" % type(sink).__name__)
Jan 14 14:13:56 radyo1128 libretime-playout[8745]: TypeError: Cannot log to objects of type 'bytes'
Jan 14 14:13:57 radyo1128 systemd[1]: libretime-playout.service: Main process exited, code=exited, status=1/FAILURE
Jan 14 14:13:57 radyo1128 systemd[1]: libretime-playout.service: Failed with result 'exit-code'.
Jan 14 14:13:57 radyo1128 systemd[1]: libretime-playout.service: Service hold-off time over, scheduling restart.
Jan 14 14:13:57 radyo1128 systemd[1]: libretime-playout.service: Scheduled restart job, restart counter is at 5.
Jan 14 14:13:57 radyo1128 systemd[1]: Stopped Libretime Playout Service.
Jan 14 14:13:57 radyo1128 systemd[1]: libretime-playout.service: Start request repeated too quickly.
Jan 14 14:13:57 radyo1128 systemd[1]: libretime-playout.service: Failed with result 'exit-code'.
Jan 14 14:13:57 radyo1128 systemd[1]: Failed to start Libretime Playout Service.
----------------------------

/var/log/libretime does not exist.
/var/log/airtime/pypo & /var/log/airtime/pypo-liquidsoap both empty no files (but there was the normal log files before the upgrade)

**Comment by jooola** [comment]
Small tip, to format your code or logs use the triple backquotes like the following (ignore any `>` char):
```
> ```
> code
> ```
```

**Comment by maydo** [comment]
```
> ```
> code
> ```
```
thx, i was struggling with it :)

**Comment by maydo** [comment]
btw, for testing purpose.
just installed a new VM with ubuntu 20.04
git clone https://github.com/LibreTime/libretime.git
cd libretime
sudo bash install -fiap

running into same issue

<img width="1129" alt="Screenshot 2022-01-14 at 14 58 43" src="https://user-images.githubusercontent.com/27486434/149527370-d7b5ec38-8a61-4835-b586-575f8ac4bd54.png">

**Comment by jooola** [comment]
@maydo I just tested this on ubuntu focal (20.04) and didn't found any issue.

Could you provide more information of you setup ? You can fill the normally provided bug report form:
```
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**LibreTime version:**
Version from the upgrade popup if you can reach it.

**Installation method:**

- OS: [e.g. Ubuntu]
- OS Version [e.g. 18.04.5 LTS (Bionic Beaver)]
- Method: [e.g. `./install` script or packages]
- Details: [how did you call the install script, where did you get packages from]

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Client (please complete the following information if applicable):**

- OS: [e.g. Fedora]
- Browser [e.g. chrome, safari]
- Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

```

**Comment by maydo** [comment]
see my previous post. (with screenshot)
for testing, just installed a brandnew clean Ubuntu 20.04.3 LTS 

installation (standard procedure) with static local ip as virtual machine on a proxmox host
activated root user on ubuntu
logged per ssh as root

and installed latest LT

git clone https://github.com/LibreTime/libretime.git
cd libretime
bash install -fiap

installation runs without issues 
opening per local IP address i went thru the setup process with the defaults, just clicked next.
and its same, playout & liquidsoap services does not start

**Comment by jooola** [comment]
I just ran the installation process on both clean ubuntu 18.04 and 20.04 vm from hetzner. The only error I face was the `gettext` package missing from ubuntu 18.04 but that's irrelevant.

I cannot provide any help if you don't work with me, I need information on your setup that seem to be specific. I need to know what is different or what went wrong.

Could you paste the installation logs ?

**Comment by jooola** [comment]
Finally could reproduce this on ubuntu-18.04, I'll do some testing.

**Comment by maydo** [comment]
@jooola thx for that fix.

on todays new installed test system 20.04. its working fine now after latest pull 
but on my production system 18.04 playout & liquidsoap still not start, after latest pull 
so i did a do-release-upgrade to become both same, both on 20.04.

here is complete output of `bash install -fiap` from failing production system

[install.log](https://github.com/LibreTime/libretime/files/7873543/install.log)

**Comment by maydo** [comment]
from journalctl
PermissionError: [Errno 13] Permission denied: '/var/log/libretime'

it was a permission problem, created '/var/log/libretime' manually and chowned to www-data.
now its working

**Comment by paddatrapper** [comment]
Potentially the chown in the install script is not applied on upgrade
