### ISSUE TITLE
Weblate PR title doesn't match semantic-release

### ISSUE THREAD

**Issue by paddatrapper** [libretime/libretime#1530]
Currently the Weblate commits are semantic-releas compatible (`chore(legacy): translated using weblate ({{ language_name }})`) however, the PR title is `Translations update from Hosted Weblate`, which is not following semantic-release requirements. I don't see a way of configuring the PR title from the Weblate settings

**Comment by jooola** [comment]
Weblate 4.12 implemented a merge request template field. I just updated it on Weblate.
