### ISSUE TITLE
Move releases notes to docs/

### ISSUE THREAD

**Issue by jooola** [libretime/libretime#1535]
While I never wrote any, I think writing and browsing releases notes on the release page is difficult.

I think we should have these files versioned, and available on the website.

In addition, we are now able to generate a detailed changelog file that will also live in the repository, so we will probably want both changelogs and release notes not too far from each other.

This would also make the release process simpler, with a release being cut by merging a PR.

**Comment by zklosko** [comment]
Docusaurus will allow us to create versioned releases of our docs. I can add the release notes to what I'm working on.

**Comment by jooola** [comment]
@zklosko With versioned I just meant we should have the release notes files in the vcs. I am unsure if having a versioned documentation is a good idea, as it requires a lot of work. Maybe between major version it can be useful, but that's another topic.

**Comment by jooola** [comment]
@paddatrapper Should we replace the current releases notes in the releases page with links to the releases notes on the website ?

**Comment by paddatrapper** [comment]
I think not - having them in the GitHub releases is helpful when you want to quickly review changes and when we generate the notes automatically, we can populate both at the same time
