### ISSUE TITLE
Fix resources hardcoded in http://

### ISSUE THREAD

**Issue by valerio-bozzolan** [libretime/libretime#1537]
**Describe the bug**
I've seen some LibreTime resources hardcoded with `http://`. This is (at least for my installation) a protocol downgrade problem.

Some of these resources:

* https://github.com/LibreTime/libretime/blob/main/legacy/application/models/Preference.php#L1143
* https://github.com/LibreTime/libretime/blob/main/legacy/application/models/Preference.php#L1128
* https://github.com/LibreTime/libretime/blob/main/legacy/application/controllers/ApiController.php#L679
* ....

**Expected behavior**

Do not hardcode `http://` and adopt instead something like this:

* https://stackoverflow.com/a/14270161/3451846

As suggested, an extra option like `public_url` would be amazing to determine the schema/host/port/base URL.

---

Thank you for everyone reporting this kind of resources here. I will update the list.

**Comment by jooola** [comment]
The 2 lines in Preference.php are tricky. It would mean the liquidsoap/icecast input harbor accept secure connection (as it should) but this isn't a small change as the legacy code didn't plan for this in the past.

The third line seem easy to fix. I think the provided solution on stackoverflow is the right way to go, but that would mean we rely on a possible bad configured reverse proxy somewhere. This needs documentation.

An extra option would be to use a `public_url` field in the config to determine the schema/host/base url.

An extra note is that our apache configuration is missing a ServerName, I think we should add this configuration.

**Comment by valerio-bozzolan** [comment]
I think having the StackOverflow solution as default, together with a `public_url` as override configuration, is an amazing idea.

**Comment by paddatrapper** [comment]
Liquidsoap SSL is tracked in #1032
