### ISSUE TITLE
Got fed up of waiting. here is an independent forum

### ISSUE THREAD

**Issue by JohnnyC1951** [LibreTime/libretime#156]
All are welcome. Lets talk and get stuff DONE!
Pop in and at least say hi!
http://web-radio-support.websitesinternational.net/

**Comment by hairmare** [comment]
@JohnnyC1951 I would like to ask you to reflect on the way others perceive your posts. I consider your behaviour over the last couple of days to be rather harmful to the community at large and am asking you to self-correct your behavior. Please also refrain from name calling. We expect you to respect other potential community members just as we respect your positions.

As per our [code of conduct](https://github.com/LibreTime/code-of-conduct/blob/master/CODE_OF_CONDUCT.md) it is my responsability to remove, edit, or reject comments, commits, code, wiki edits, issues, and other contributions that are not aligned with the CoC. This is why I will edited the original text of this issue removing any snide references to members of the legacy upstream community.

**Comment by JohnnyC1951** [comment]
I had already considered that this was not the place for me, for the very reasons that you deleted, which is why I left. I was somewhat surprised to even get notified of your comment. I am more used to industry standard web-based project management group-ware. For the future, I am building some standalone Libretime widgets and extensions that do not touch core code, but you are welcome to incorporate into the core, should you wish. The first (a lightweight stand-alone weekly widget) will be available later today, possibly. The next will be a port of my already working Airtime automated, self updating, repeating show content generator using the latest data and audio from RSS Feeds, and should be ready in a week or so (mostly this involves writing an installer for the existing working code and reading the RSS urls and show lengths from the database instead of a CSV file). Good luck. Please delete all my other posts and threads. Thank you.

**Comment by hairmare** [comment]
Thanks for getting back to me. Just to be perfectly clear, all I deleted was the snide reference to a legacy community member in this issue. If someone else deleted any of your content I apologize for that. That was uncalled for and not what I expect from our community.

**Comment by JohnnyC1951** [comment]
We are done. Please delete this thread. Thank you.

**Comment by hairmare** [comment]
@LibreTime/maintainers These fruitless discussions have lead to be blocking the offending party at the orga level. I'm considering this a temporary ban and will reinstate the user after a weeks time. Sorry for all the noise. Let's get on with hacking.
