### ISSUE TITLE
Media Settings in install wizard broken

### ISSUE THREAD

**Issue by paddatrapper** [LibreTime/libretime#1562]
**Describe the bug**
It seems that (I think) #1558 has caused the Media Settings section of the install wizard to break. When opening it, the textbox is not pre-filled with the default `/srv/airtime/stor/` and entering it manually causes a JS error in `setup-config.js`:

```
Uncaught TypeError: data is null
    showFeedback http://192.168.10.100:8080/js/setup/setup-config.js:23
    cleanupStep http://192.168.10.100:8080/js/setup/setup-config.js:8
    cleanupProxy http://192.168.10.100:8080/js/setup/setup-config.js:136
    jQuery 7
    submitForm http://192.168.10.100:8080/js/setup/setup-config.js:138
    jQuery 22
    submitForm http://192.168.10.100:8080/js/setup/setup-config.js:133
    <anonymous> http://192.168.10.100:8080/:223
    jQuery 2

```

**Comment by jooola** [comment]
I'll have a look

**Comment by jooola** [comment]
The web ui setup does not properly handle when the storage path does not exist when running the setup. The fix the default at least, I reverted the default storage path to the on present in the installer, and I didn't updated the installer when changing the default storage path constant.
