### ISSUE TITLE
Replace config base_* url parts with a single base_url field

### ISSUE THREAD

**Issue by jooola** [libretime/libretime#1574]
**Is your feature request related to a problem? Please describe.**

The configuration of the multiple base_* fields in the config is difficult and unpractical. It is the source of a lot of guessing code and weird workarounds.

**Describe the solution you'd like**

Replace the following fields:
```ini
base_url =
base_port =
base_dir =
force_ssl =
protocol =
```
with a single `base_url`/`public_url`/`root_url` field (naming should be discussed). The field will need to be a full URL like the following:
```ini
base_url = http://localhost:8080 # dev url, actually not public
base_url = https://station.radio.org # common public url no custom port
base_url = https://radio.org/station # common public url no custom port with custom subdir
base_url = https://station.radio.org:9999 # weird and custom public url
```

**Comment by paddatrapper** [comment]
The only potential issue I can see here is running behind a reverse proxy or in a containerized setup, where the external ingress address could be different from the internal address. For example, external access from https://example.com, but internal communication between the API and other LT apps on http://example.local

**Comment by jooola** [comment]
Why not go through the reverse proxy even for internal communication ? This makes it even clearer when decoupling the apps, as they should be communicate securely using https.

The only real internal communication I can see are playout <-> liquidsoap.

**Comment by paddatrapper** [comment]
There are cost implications and potentially routing issues. For example Kubernetes uses ingresses for external access and services for internal.

The cost implications come from cloud providers charging for traffic going through a load balancer (i.e. the ingress in the Kubernetes example), while inter-cluster communication is free. There is a large incentive to use local addresses within the cluster and only use the ingress for external access.

The routing issues can be seen in LXC setups where, the ingress resolves to the host machine and routed to a reverse proxy before being routed further into the LXC network. This setup requires additional iptables rules to allow traffic to be routed from the container externally and then back to the container again.

In that setup, pod-to-pod (internal) communication using https is pointless as there is no mitm possibility unless the cluster is compromised, at which point you have bigger issues. Maintaining and updating the certs for internal comms is also a lot of work for not much added security.

Playout still uses the API alongside RabbitMQ, as does analyzer (downloading the file to process).

**Comment by jooola** [comment]
While I agree with your concern, and we should think about such deployment requirements, I think you are describing a really specific edge case. In addition libretime does not seems to be ready to be deployed in k8s cluster (or any decoupled setup), unless you already have your own docker images and deployment files ?

This specific requirements could be solved in many ways without blocking the renaming of such basic configuration entry. Like using a optional second configuration entry that is specific to the API and Legacy.

Such value make 

Currently a lot of communication currently going through the api_client, should actually go trough the message queue. Like the analyzer result, or event the playout stats, and many others. If a file download should occur, the internal url could be passed trough the message payload.

**Comment by paddatrapper** [comment]
> In addition libretime does not seems to be ready to be deployed in k8s cluster (or any decoupled setup), unless you already have your own docker images and deployment files ?

That is exactly what I'm working on in #1471. The LXC issue is one I have and do run into already as that is how we currently deploy LibreTime.

> This specific requirements could be solved in many ways without blocking the renaming of such basic configuration entry. Like using a optional second configuration entry that is specific to the API and Legacy.

I'm not blocking the change, but we do need to be careful about how we make the change to ensure that this use-case does not break. 2 URLs in the config could work well. 

> Currently a lot of communication currently going through the api_client, should actually go trough the message queue. Like the analyzer result, or event the playout stats, and many others. If a file download should occur, the internal url could be passed trough the message payload.

It would still need a config option for the internal URL to pass to the message queue.

**Comment by jooola** [comment]
> It would still need a config option for the internal URL to pass to the message queue.

Yes true, this was more of a sidenote that reduce the importance of the api_client, while we still require a way to define an internal url.

> I'm not blocking the change, but we do need to be careful about how we make the change to ensure that this use-case does not break. 2 URLs in the config could work well.

Noted, I'll do some research.

**Comment by jooola** [comment]
Ok, there is a little mix up in our discussion.

The current exploded parts are actually used as base to build both public URLs such as JavaScript and CSS resources and internal urls used by Playout through the API client.

So while our discussion is still valid, we should first address this confusing situation.

Ideally the resources should be served without any hostname+port, simply using absolute links. Any extra URL manipulation should be handled by the webserver/reverse proxy.
Some Models in legacy does use the server information to build internal url such as the Application_Model_StoredFile class.

Ideally this internal URL should be passed to the playout and use it to call the API, using the API client. #1344 start to become more and more important.

I'll keep investigating what would be the best path to solve this issue.

**Comment by paddatrapper** [comment]
I agree with relative URLs where possible. Though some places (for example the stream URLs) that won't work.

I'm still in 2 minds about #1344, but I'll comment on that with more details
