### ISSUE TITLE
Switch Vagrantfile to use bento boxes for ubuntu

### ISSUE THREAD

**Issue by bburton** [LibreTime/libretime#158]
HashiCorp recommends the Bento Ubuntu boxes over the ones provided by Canonical. See https://www.vagrantup.com/docs/boxes.html#official-boxes.

> ... we recommend the Bento boxes. The Bento boxes are open source and built for a number of providers including VMware, Virtualbox, and Parallels. There are a variety of operating systems and versions available.
> 
> These are the only two officially-recommended box sets.
> 
> **It is often a point of confusion,** but Canonical (the company that makes the Ubuntu operating system) publishes boxes under the "ubuntu" namespace on Atlas. These boxes only support Virtualbox and do not provide an ideal experience for most users. If you encounter issues with these boxes, please try the Bento boxes instead.

Link to [bento/ubuntu-14.04](https://atlas.hashicorp.com/bento/boxes/ubuntu-14.04) on Atlas.

Link to [bento/ubuntu-16.04](https://atlas.hashicorp.com/bento/boxes/ubuntu-16.04) on Atlas.

Note that the existing *ubuntu* option in the Vagrantfile utilizing the ubuntu/trusty64 base box needs to be retained for some period of time so users can manage their existing ubuntu boxes with the vagrant command.

I'm working on a patch that supports the following Vagrant options for Ubuntu:

* ubuntu-xenial -- uses a bento/ubuntu-16.04 base box; user can specify any supported provider.
* ubuntu-trusty -- uses a bento/ubuntu-14.04 base box; user can specify any supported provider.
* ubuntu -- uses the ubuntu/trusty64 base box as before but outputs the deprecation warning:
  'WARNING: The "ubuntu" option is deprecated. Please migrate to "ubuntu-trusty".'

**Comment by hairmare** [comment]
Closing due to having merged and tested #159
