### ISSUE TITLE
Version error on Ubuntu 20.04.3 LTS

### ISSUE THREAD

**Issue by antrys** [LibreTime/libretime#1587]
**Describe the bug**
Install gives the following output:
Detecting distribution and release ...
Detected distribution id: ubuntu
Detected distribution release id: 20.04
Detected distribution description: Ubuntu 20.04.3 LTS
ERROR: Distribution "Ubuntu 20.04.3 LTS" is not supported with "ubuntu-20.04"!

**To Reproduce**
1. run bash install -fiap as root

**Expected behavior**
No error?

**LibreTime version:**
libretime-3.0.0-alpha.10.tar.gz

**Installation method:**
Stable release and bash install -fiap as root 
as outlined on this page: https://libretime.org/index#get-started

**Additional context**
relatively Fresh linode install. (server's ~ a week old, currently only running coturn)
Server installed from linode's default 20.04 LTS image then updated with regular APT updates.

**Comment by paddatrapper** [comment]
You can manually set `--distribution=ubuntu --release=20.04` as a work around

**Comment by antrys** [comment]
Not sure what you mean by "manually set"
I tried passing those arguments on the command line and got the same result/error.
This is my first time working with the software.

**Comment by antrys** [comment]
Ok, I had a look inside the install script and I see it's looking for those arguments, but for some reason it doesn't work.

bash install -fiap --distribution=ubuntu --release=20.04

Detecting distribution and release ...
Detected distribution id: ubuntu
Detected distribution release id: 20.04
Detected distribution description: Ubuntu 20.04.3 LTS
ERROR: Distribution "Ubuntu 20.04.3 LTS" is not supported with "ubuntu-20.04"!

**Comment by jooola** [comment]
Libretime 3.0.0-alpha.10 does not support Ubuntu 20.04. Support for ubuntu 20.04 has not been released yet, it is in the current main branch.

We will soon cut a new release, you can wait for that or directly install using git. https://libretime.org/docs/getting-started/install/#installing-libretime
