### ISSUE TITLE
Link Checker Report

### ISSUE THREAD

**Issue by jooola** [libretime/libretime#1589]
## Summary

| Status        | Count |
|---------------|-------|
| 🔍 Total      | 831   |
| ✅ Successful | 690   |
| ⏳ Timeouts   | 0     |
| 🔀 Redirected | 0     |
| 👻 Excluded   | 76    |
| ❓ Unknown    | 0     |
| 🚫 Errors     | 65    |

### Errors in docs/appendix/rights-royalties.md
* [https://www.ascap.com/](https://www.ascap.com/): Failed: Network error

### Errors in website/versioned_docs/version-3.0.0-alpha.12/releases/3.0.0-alpha.11.md
* [https://github.com/libretime/libretime/issues/1522](https://github.com/libretime/libretime/issues/1522): Failed: Network error
* [https://github.com/libretime/libretime/issues/1292](https://github.com/libretime/libretime/issues/1292): Failed: Network error
* [https://github.com/libretime/libretime/issues/1519](https://github.com/libretime/libretime/issues/1519): Failed: Network error
* [https://github.com/libretime/libretime/issues/1493](https://github.com/libretime/libretime/issues/1493): Failed: Network error
* [https://github.com/libretime/libretime/issues/1421](https://github.com/libretime/libretime/issues/1421): Failed: Network error
* [https://github.com/libretime/libretime/issues/1558](https://github.com/libretime/libretime/issues/1558): Failed: Network error
* [https://github.com/libretime/libretime/issues/1354](https://github.com/libretime/libretime/issues/1354): Failed: Network error
* [https://github.com/libretime/libretime/issues/1559](https://github.com/libretime/libretime/issues/1559): Failed: Network error
* [https://github.com/libretime/libretime/issues/1496](https://github.com/libretime/libretime/issues/1496): Failed: Network error
* [https://github.com/libretime/libretime/issues/1707](https://github.com/libretime/libretime/issues/1707): Failed: Network error
* [https://github.com/libretime/libretime/issues/1491](https://github.com/libretime/libretime/issues/1491): Failed: Network error
* [https://github.com/libretime/libretime/issues/1168](https://github.com/libretime/libretime/issues/1168): Failed: Network error
* [https://github.com/libretime/libretime/issues/1349](https://github.com/libretime/libretime/issues/1349): Failed: Network error
* [https://github.com/libretime/libretime/issues/1507](https://github.com/libretime/libretime/issues/1507): Failed: Network error
* [https://github.com/libretime/libretime/issues/1563](https://github.com/libretime/libretime/issues/1563): Failed: Network error
* [https://docs.python-requests.org/](https://docs.python-requests.org/): Failed: Network error
* [https://github.com/libretime/libretime/issues/1591](https://github.com/libretime/libretime/issues/1591): Failed: Network error
* [https://github.com/libretime/libretime/issues/1409](https://github.com/libretime/libretime/issues/1409): Failed: Network error
* [https://github.com/libretime/libretime/issues/1606](https://github.com/libretime/libretime/issues/1606): Failed: Network error
* [https://github.com/libretime/libretime/issues/1495](https://github.com/libretime/libretime/issues/1495): Failed: Network error

### Errors in docs/releases/3.0.0-alpha.01.md
* [https://download.opensuse.org/repositories/home:/hairmare:/silan/xUbuntu_14.04](https://download.opensuse.org/repositories/home:/hairmare:/silan/xUbuntu_14.04): Failed: Network error

### Errors in docs/releases/3.0.0-alpha.03.md
* [https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3.0.patch](https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3.0.patch): Failed: Network error
* [https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3.0](https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3.0): Failed: Network error
* [https://download.opensuse.org/repositories/home:/hairmare:/silan/xUbuntu_14.04](https://download.opensuse.org/repositories/home:/hairmare:/silan/xUbuntu_14.04): Failed: Network error

### Errors in docs/releases/3.0.0-alpha.08.md
* [https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3-for-3.0.0-alpha.7.patch](https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3-for-3.0.0-alpha.7.patch): Failed: Network error
* [https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3.0-for-3.0.0-alpha.7](https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3.0-for-3.0.0-alpha.7): Failed: Network error

### Errors in website/versioned_docs/version-3.0.0-alpha.12/releases/3.0.0-alpha.05.md
* [https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3.0.patch](https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3.0.patch): Failed: Network error
* [https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3.0](https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3.0): Failed: Network error

### Errors in website/versioned_docs/version-3.0.0-alpha.12/releases/3.0.0-alpha.12.md
* [https://github.com/libretime/libretime/issues/1715](https://github.com/libretime/libretime/issues/1715): Failed: Network error
* [https://github.com/libretime/libretime/issues/1717](https://github.com/libretime/libretime/issues/1717): Failed: Network error

### Errors in docs/releases/3.0.0-alpha.07.md
* [https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3.0.patch](https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3.0.patch): Failed: Network error
* [https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3.0](https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3.0): Failed: Network error

### Errors in docs/releases/3.0.0-alpha.05.md
* [https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3.0](https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3.0): Failed: Network error
* [https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3.0.patch](https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3.0.patch): Failed: Network error

### Errors in docs/releases/3.0.0-alpha.06.md
* [https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3.0.patch](https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3.0.patch): Failed: Network error
* [https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3.0](https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3.0): Failed: Network error

### Errors in website/versioned_docs/version-3.0.0-alpha.12/admin-manual/setup/install.md
* [https://github.com/libretime/libretime/releases/download/%7Bvars.version%7D/libretime-%7Bvars.version%7D.tar.gz](https://github.com/libretime/libretime/releases/download/%7Bvars.version%7D/libretime-%7Bvars.version%7D.tar.gz): Failed: Network error

### Errors in website/versioned_docs/version-3.0.0-alpha.12/releases/3.0.0-alpha.03.md
* [https://download.opensuse.org/repositories/home:/hairmare:/silan/xUbuntu_14.04](https://download.opensuse.org/repositories/home:/hairmare:/silan/xUbuntu_14.04): Failed: Network error
* [https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3.0.patch](https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3.0.patch): Failed: Network error
* [https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3.0](https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3.0): Failed: Network error

### Errors in CONTRIBUTING.md
* [https://github.com/libretime/code-of-conduct/blob/main/code_of_conduct.md](https://github.com/libretime/code-of-conduct/blob/main/code_of_conduct.md): Failed: Network error

### Errors in website/versioned_docs/version-3.0.0-alpha.12/releases/3.0.0-alpha.04.md
* [https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3.0](https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3.0): Failed: Network error
* [https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3.0.patch](https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3.0.patch): Failed: Network error
* [https://download.opensuse.org/repositories/home:/hairmare:/silan/xUbuntu_14.04](https://download.opensuse.org/repositories/home:/hairmare:/silan/xUbuntu_14.04): Failed: Network error

### Errors in docs/releases/3.0.0-alpha.04.md
* [https://download.opensuse.org/repositories/home:/hairmare:/silan/xUbuntu_14.04](https://download.opensuse.org/repositories/home:/hairmare:/silan/xUbuntu_14.04): Failed: Network error
* [https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3.0.patch](https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3.0.patch): Failed: Network error
* [https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3.0](https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3.0): Failed: Network error

### Errors in website/versioned_docs/version-3.0.0-alpha.12/releases/3.0.0-alpha.02.md
* [https://download.opensuse.org/repositories/home:/hairmare:/silan/xUbuntu_14.04](https://download.opensuse.org/repositories/home:/hairmare:/silan/xUbuntu_14.04): Failed: Network error
* [https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3.0](https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3.0): Failed: Network error
* [https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3.0.patch](https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3.0.patch): Failed: Network error

### Errors in website/src/pages/contribute.md
* [https://github.com/libretime/code-of-conduct/blob/main/code_of_conduct.md](https://github.com/libretime/code-of-conduct/blob/main/code_of_conduct.md): Failed: Network error

### Errors in website/versioned_docs/version-3.0.0-alpha.12/releases/3.0.0-alpha.07.md
* [https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3.0.patch](https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3.0.patch): Failed: Network error
* [https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3.0](https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3.0): Failed: Network error

### Errors in docs/releases/3.0.0-alpha.11.md
* [https://docs.python-requests.org/](https://docs.python-requests.org/): Failed: Network error

### Errors in website/versioned_docs/version-3.0.0-alpha.12/appendix/rights-royalties.md
* [https://www.ascap.com/](https://www.ascap.com/): Failed: Network error

### Errors in website/versioned_docs/version-3.0.0-alpha.12/releases/3.0.0-alpha.01.md
* [https://download.opensuse.org/repositories/home:/hairmare:/silan/xUbuntu_14.04](https://download.opensuse.org/repositories/home:/hairmare:/silan/xUbuntu_14.04): Failed: Network error

### Errors in docs/admin-manual/setup/install.md
* [https://github.com/libretime/libretime/releases/download/%7Bvars.version%7D/libretime-%7Bvars.version%7D.tar.gz](https://github.com/libretime/libretime/releases/download/%7Bvars.version%7D/libretime-%7Bvars.version%7D.tar.gz): Failed: Network error

### Errors in docs/releases/3.0.0-alpha.02.md
* [https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3.0.patch](https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3.0.patch): Failed: Network error
* [https://download.opensuse.org/repositories/home:/hairmare:/silan/xUbuntu_14.04](https://download.opensuse.org/repositories/home:/hairmare:/silan/xUbuntu_14.04): Failed: Network error
* [https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3.0](https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3.0): Failed: Network error

### Errors in website/versioned_docs/version-3.0.0-alpha.12/releases/3.0.0-alpha.06.md
* [https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3.0](https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3.0): Failed: Network error
* [https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3.0.patch](https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3.0.patch): Failed: Network error

### Errors in website/versioned_docs/version-3.0.0-alpha.12/releases/3.0.0-alpha.08.md
* [https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3.0-for-3.0.0-alpha.7](https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3.0-for-3.0.0-alpha.7): Failed: Network error
* [https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3-for-3.0.0-alpha.7.patch](https://github.com/libretime/libretime/compare/master...radiorabe:feature/liquidsoap-1.3-for-3.0.0-alpha.7.patch): Failed: Network error

[Full Github Actions output](https://github.com/libretime/libretime/actions/runs/2412209979?check_suite_focus=true)

**Comment by jooola** [comment]
Any example link should have either `example.(org|com)` or `localhost`  as host name so it is automatically excluded by the link checker.

**Comment by paddatrapper** [comment]
Some aren't possible to do like that. For example the reverse-proxy docs need to differentiate between two different domains - LibreTime and Icecast (as well as the internal LibreTime domain). Is it possible to ignore specific links?

**Comment by jooola** [comment]
We can either create a .lycheeignore file or add `--exlude myhost` in the workflow file. I would prefer the later so all the configuration is in the same file.

**Comment by jooola** [comment]
The report is not updating anymore, this is why I propose #1885
