### ISSUE TITLE
Hot reload is not working when editing the documentation files

### ISSUE THREAD

**Issue by jooola** [LibreTime/libretime#1599]
**Describe the bug**

Hot reload is not working when editing documentation files.

**To Reproduce**

1. Run the website in dev mode
```sh
cd website
yarn
yarn start
```
2. Edit a file in the docs
3. The page is not reloaded nor updated.

**Expected behavior**

Editing a file should rebuild the file. And would normally refresh the page in the browser.
 
cc @zklosko

**Comment by zklosko** [comment]
```
client (webpack 5.68.0) compiled successfully
[WARNING] Duplicate routes found!
Attempting to create page at /, but a page already exists at this route
This could lead to non-deterministic routing behavior
```

There are two index pages with two different extensions. We need to use just one; Docusaurus defaults to the JS one if it detects multiples, and the JS one does hot reload on save.

Just to be safe, delete your `node_modules`, `.docusaurus`, and `build` folders and run

```
yarn install --frozen-lockfile
yarn start
```

**Comment by jooola** [comment]
I don't have the warning you have.

My issue is that the markdown files in the documentation does not always trigger hot reloads. In certain cases the document ar not refreshed. Cleaning the git folder and starting fresh seem to work, but the problem seem to happen after some iterations of editing.

I guess we will have to clean more often.
