### ISSUE TITLE
Run selenium tests through travis

### ISSUE THREAD

**Issue by hairmare** [LibreTime/libretime#16]
The existing tests in `tests/` are not being executed at a regular interval and we should run them through travis like #14 does with the phpunit tests.

Travis has some [docs on selenuim](https://docs.travis-ci.com/user/gui-and-headless-browsers/) and they recommend using [saucelabs](https://saucelabs.com/).

**Comment by hairmare** [comment]
What I figured out so far:

* The script `tests/run_selenium.sh` does not run out of the box (at least on CentOS)
* The used selenium version is old and lots has changed
* The tests don't cover too much but look ok

I'll try running these on travis in ubuntu since I believe we have a better chance there but might need to switch to a `sudo: true` box on travis.

**Comment by Robbt** [comment]
Ok, so I couldn't get this to work either. I had to install the openjdk to get it to run and also install iceweasel aka firefox. But then I haven't any results gotten past Launching Firefox. The Results.html file generated is blank. So this will require further research.

**Comment by zklosko** [comment]
The Selenium tests were removed in #1116
