### ISSUE TITLE
Drafting a design and architecture document

### ISSUE THREAD

**Issue by jooola** [libretime/libretime#1610]
LibreTime is currently missing a design document, to lead the global decision made in the LibreTime development.

I remember a document explaining the different parts of the project some time ago, It was on the old mkdocs website, I'll try to resurrect this document.

## Initial thoughts

From the few issues I read with design decision that have been proposed, some want to build a micro service architecture, others are heading to a monolithic API with an external Playout service.

Right now I feel we are without global vision for this application. And this lead to having the person provide a contribution to impose his idea. While I understand we cannot afford turning down contributions, we still need to have some kind of road map and design decision to prevent the project from being monkey patched every time someone want to implement an fix/feature.

For example, in #1592, I am working to replace pika with kombu in the Analyzer, it might might sens if we want to work in a micro service architecture, but has no point if we merge the analyzer inside a celery/worker task. While we still want to rely on a hardly functional multi tenant feature for the analyzer.

Another example, in #1501, I think we should not drop rabbitmq which gives advanced routing capabilities, but it does makes less sens to have such tool in a monolithic architecture. It seem that we will always have the communication between the API and playout, which is why I feel having rabbitmq will reduce some of the work required for playout. But again, this should be part of a design decision.

I also don't know if we try to keep SAAS feature while we want for any newcomers to be able to install the app. As both don't have the same needs and handling both is sometimes a huge amount of work.

## After the community meeting

During the community meeting, we have discussed the lack of such document with @paddatrapper and we agreed that we should start drafting one.

I don't think the microservice architecture is right way to go, it does not fix or improve any problematic situation in LibreTime. If we want to properly split code by concerns they are plenty of ways to do it.

The multi tenant feature does not seem to be used by anyone that we know, and brings complexity to the project. Spinning an additional analyzer instance for an additional client isn't much overhead in my opinion. I think that 1 client for 1 LibreTime stack is the right way to go, while we can put aside icecast or reverse proxies or such infrastructure tool that still can be easily shared in a multi client perspective.

I see 2 main component in LibreTime, 'Create the schedule' and 'Play the schedule'. The schedule creation component is a monolithic application, with the frontend talking to the django API. The Play block has it's own requirements in terms of logic and uptime, and should be left aside.

[Original schema without playout > api communication](https://mermaid.live/edit#pako:eNp1UttqAjEQ_ZUlTxb0B3wolNqCoGBpoQ_ZRcbNqKF7MxeKqP_e2cxG16r7knOZDJOzcxB5rVCMxcZAs02-JmmV0FdCBRs0AzlnkD2x3vhVofOBXISzVVm3fsUNcoPgcGnzLSpfoHwNPHFbTKKW8ZX2W5u6clgp-d6BngeNli-LaU_5rc0PmlZMvgPsPLp3M0dTwP4yxYLYoxnaytq7UENnzyn0zmtla2iknJ1x1qvQOeZgnZRTBtntRCVaSwkudx49Sjlnmny0NJYrcLACS_akQ61z9SeS0ej5HFf0Ig8m5RV1gkGKfa_Vq4nujhnKOG12Gf_r-ehiF2i3MEyCccmTvQsPdhdmbMyrFpzjTFt657EXwKOKcxMxFCWaErSi5T60F1JBG1BiKsYEFa7BFy4VaXWiUt_Qu_BNaVcbMXbG41CAd_Xnvsoj55qJBtqwksXTHyJ3FlM)

[![](https://mermaid.ink/img/pako:eNp1UttqAjEQ_ZWQJwv6Az4USm1BULC00IfsImMy1tC9mQtF1H_vbLLR3VrzkjPnzMxOzs6Ry1ohn_IvA82OfcyyitEpoYIvNCOxjCB_iHzjN4WWI7EKd8tG3vpNbCANgsO1lTtUvkDxHGLmdsgSl8eS9mxNXTmslHjtQE-DRoun1bzH_NTmG01Lss8AO43qbuZoCjhcp1hRdG-GNrP2LuTQ3VMKvfda2RoaIRYXnPcytEQJ1gkxjyC_nahEa8nB9d6jRyGWMWRvbZjSFTjYgCV51qFWGfwJNpk8XuxKWoqDSH4lnmCgUt8hO5jo3zFDWnQ7qhH_6XmvsDO0W5gYBOHq560Wph-aHvjO4fS1uH9BOS20pcefeq7cy7g04WNeoilBK9r4Y1uQcVqLEjM-JahwC75wGc-qM6X6hh6LL0q72vCpMx7HHLyr3w-VTHHMmWmgtSsjef4FpXUcvQ)](https://mermaid.live/edit/#pako:eNp1UttqAjEQ_ZWQJwv6Az4USm1BULC00IfsImMy1tC9mQtF1H_vbLLR3VrzkjPnzMxOzs6Ry1ohn_IvA82OfcyyitEpoYIvNCOxjCB_iHzjN4WWI7EKd8tG3vpNbCANgsO1lTtUvkDxHGLmdsgSl8eS9mxNXTmslHjtQE-DRoun1bzH_NTmG01Lss8AO43qbuZoCjhcp1hRdG-GNrP2LuTQ3VMKvfda2RoaIRYXnPcytEQJ1gkxjyC_nahEa8nB9d6jRyGWMWRvbZjSFTjYgCV51qFWGfwJNpk8XuxKWoqDSH4lnmCgUt8hO5jo3zFDWnQ7qhH_6XmvsDO0W5gYBOHq560Wph-aHvjO4fS1uH9BOS20pcefeq7cy7g04WNeoilBK9r4Y1uQcVqLEjM-JahwC75wGc-qM6X6hh6LL0q72vCpMx7HHLyr3w-VTHHMmWmgtSsjef4FpXUcvQ)

With the design briefly described above, I found answers to some of my questions:

- #1592 is useless if we plan to merge the analyzer as a worker task. This merge is a low priority as the current celery stack (php + celery v5) is blocking any easy improvements.
- #1501 we should keep RabbitMQ anyways, it bring a powerful routing capability needed between the 2 main components, and while we don't head towards a microservice architecture, anyone can plug his own tool in it.

## Please give us feedback

Maybe my ticket does not sound open for changes, but I would love to hear from those who disagree or have better ideas, and discuss with them.

Please note that if someone if pushing towards a particular design (that we should agree on anyway), that person should consider contributing to the project. As I don't see the myself working on something I am not comfortable with and without the person that had the idea in the first place.

cc @LibreTime/Maintainers

@paddatrapper You suggested we post this ticket on discourse instead of Github ? I could link to the discussion thread if Github is not the right place and lock this until we have all our inputs.

**Comment by jooola** [comment]
The discourse thread for this issue is here https://discourse.libretime.org/t/drafting-a-design-and-architecture-document/1121

**Comment by paddatrapper** [comment]
I agree with this design. The only thing I would note is that there will have to be communication between playout and the API, unless the message queue is capable of passing binary media files around.

**Comment by jooola** [comment]
I thought a bit about this and a small addition came to my mind:

The idea is to have a proper message consumer on the django side (We could use this is many cases), that return data that was previously requested though the Web API. The messages would use the Direct Reply-to message type, to behave similarly to a RPC call.

For example, we could push a schedule to playout, and playout can request a schedule from the message queue.
Another example, would be for the history and stats (metrics aren't involved here and should be handled by another tool), they all could be pushed to the message queue, and be ingested by the django message consumer, instead of relying on a api call.

There is no arrow between the worker, the web api and the message api, but I those communicate through the message queue or a sync call.

[![](https://mermaid.ink/svg/pako:eNp1U9tKAzEQ_ZWQJwXbDygiqFUQKlQUfMiWMs1ObejuZs3FUrT_7myyaXd7yUvOzDmZzCX55VLnyEd8WeiNXIFx7GOcVYxWCRV8obkSrxHMrqO_9otCySsxDXvjjX7rF18G6hWTBsHh3MoV5r5A8Rhs5lbIkm8WjzRraXTlsMrFcws63CGkNigeQK77fEgTraX05lAr8Roxu5--HKka9hMXZ5iNNms04jNsHY5uYtEidFJjXcD2UOGUrEv1NUrtXdDQ3mEK9e1VbjXUQkz2eNZRKIkSrBPiJYLEdTJK5X979Cj2HXhrzCTPwcECLNHjFjVMb8psMLjbjyJxyQ4kdTB6CQRHitr39vI5myS7bXSx7ZGO-CjoxZOdgbO-6DSzi0HaqbQvOhrEDNmPgqRnUT_s33l8hNjDICN5sEM67RRTNvH_BOZvoiw1-K_T-UuKNgi_4SWaElROf_a3kWecHl6JGR8RzHEJvnAZz6odSX1NrcCnXDlt-GgJhcUbDt7p920l-cgZj0k0VkAvu2xVu399mVnI)](https://mermaid.live/edit/#pako:eNp1U9tKAzEQ_ZWQJwXbDygiqFUQKlQUfMiWMs1ObejuZs3FUrT_7myyaXd7yUvOzDmZzCX55VLnyEd8WeiNXIFx7GOcVYxWCRV8obkSrxHMrqO_9otCySsxDXvjjX7rF18G6hWTBsHh3MoV5r5A8Rhs5lbIkm8WjzRraXTlsMrFcws63CGkNigeQK77fEgTraX05lAr8Roxu5--HKka9hMXZ5iNNms04jNsHY5uYtEidFJjXcD2UOGUrEv1NUrtXdDQ3mEK9e1VbjXUQkz2eNZRKIkSrBPiJYLEdTJK5X979Cj2HXhrzCTPwcECLNHjFjVMb8psMLjbjyJxyQ4kdTB6CQRHitr39vI5myS7bXSx7ZGO-CjoxZOdgbO-6DSzi0HaqbQvOhrEDNmPgqRnUT_s33l8hNjDICN5sEM67RRTNvH_BOZvoiw1-K_T-UuKNgi_4SWaElROf_a3kWecHl6JGR8RzHEJvnAZz6odSX1NrcCnXDlt-GgJhcUbDt7p920l-cgZj0k0VkAvu2xVu399mVnI)

**Comment by paddatrapper** [comment]
> The idea is to have a proper message consumer on the django side (We could use this is many cases), that return data that was previously requested though the Web API. The messages would use the Direct Reply-to message type, to behave similarly to a RPC call.

Why, what does this give us over an API call?

**Comment by jooola** [comment]
> Why, what does this give us over an API call?

I don't think all the web API calls should be replaced, or even worse duplicated. But I think some calls could be put in the message API.

It will add a better separate of concerns between the 2 services and reduce duplication.

For instance the schedule generation should have a proper separation, generate a list of items want to play and push everything to playout. The playout will then generate events based on this schedule data.

We need the possibility to push the schedule to playout, so to prevent duplication we should be using the same communication method to let playout query the schedule.

I also think that django should not be aware of "playout" events, which is not the current behavior. Legacy is building playout events and playout only handles them, separation of concerns is not respected here.

This will also force us to define a proper API between playout and django, as it is currently difficult to understand what belong where.

I hope I what I said makes sens ?

**Comment by paddatrapper** [comment]
Yeah, that makes sense
