### ISSUE TITLE
Generate website for PRs making documentation changes

### ISSUE THREAD

**Issue by paddatrapper** [libretime/libretime#1612]
It would be nice if we generated a viewable copy of the website for pull requests that modify the documentation. This would make reviewing changes in context easier and potentially allow us to link to specific issues via URL

**Comment by jooola** [comment]
Also crossed my mind, could this be handled by an external service or do we want find our own solution ?

**Comment by paddatrapper** [comment]
I think Netlify could well work. Not sure what the setup required is though

**Comment by jooola** [comment]
In that case, I propose that you head to https://www.netlify.com/legal/open-source-policy/#main, and fill out the form at https://opensource-form.netlify.com/

I am missing some information for this form, and apparently AGPL is not in there license drop down.

But maybe some research should be done before jumping on Netlify.

**Comment by paddatrapper** [comment]
Hmm... Looking through their policies makes me hesitate. I'll need to do some more digging.

I'm not sure the GitHub environment will help with what we want to do. I guess the big thing is overriding some of the docusaurus settings when building a PR and then hosting those changes somewhere. GitHub Pages is a little limited for this, as it assumes a single Pages site per repo. You can't specify multiple sites on different branches.

**Comment by jooola** [comment]
Using github pages should boil down to pushing some the build output to sub dir in the gh-page branch, without flushing previous files. This should be doable without too much hacky scripts.

The dynamic environment URL will be tracked by GitHub itself and removed once the PR closes.

I don't see this solution impossible. My only concern is that I don't want to play around the current website gh-page branch so we will need another repo to handle this. Maybe we can use the libretime.github.io repository ?

**Comment by paddatrapper** [comment]
> Maybe we can use the libretime.github.io repository ?

Can possibly do that. Will need @hairmare to update DNS for something like pr.libretime.org to point to that repo. Then can add a workflow to build and push the files to a directory there when the PR is created or updated and remove them once the PR is merged

**Comment by jooola** [comment]
I wonder if we should maintain a branch of the latest version (e.g. `current`), so we don't overwrite the documentation for the next release onto the current release.

Now that we suggest people to pin install from a specific tag/version and not from `main`, the documentation gets out of sync with the latest version. With our long release cycle, the differences between alpha.10 and the current main becomes dangerous.

That said, we are still in the alpha phase and our problem is mainly breaking changes documentation. This behavior should mirror the one we would have when releasing new major versions.

How should we handle this ? I've been advocating against a versioned documentation, but maybe having 2 versions (current and dev) could prevent some concerns.

**Comment by paddatrapper** [comment]
Yeah, I think having 2 - dev and the current release is a good way to go

**Comment by paddatrapper** [comment]
Sounds good 👍🏼 just need to remove the current contents of that git repo

**Comment by jooola** [comment]
This is finally working.

Be sure to see the `next` version of the docs, or you won't notice any changes on the website. (Go to `/docs/next/` instead of `/docs/`)
