### ISSUE TITLE
api v2 cannot update values

### ISSUE THREAD

**Issue by jooola** [libretime/libretime#1617]
**Describe the bug**

This code 
https://github.com/LibreTime/libretime/blob/98cea4dcd2acd5e0211bfec98f3929dbac7d51bb/playout/libretime_playout/pypofile.py#L88-L120

Should be handled by the analyzer, and doesn't  work as the api v2 is currently read-only. I went mad finding out why this value wasn't updated, and finally remembering that the api v2 is read only (it doesn't send any warning though !)

**Comment by paddatrapper** [comment]
> api v2 is read only

How is it read only? Is it that the api_client has not implemented the POST call? The API itself certainly supports writing

**Comment by jooola** [comment]
@paddatrapper Ok then I am confused. I thought as long as the managed flag was not switched, we could not update data in the database.

I've been starting to slowly integrate the api_client v2 for #1344 and this call was not working, and I also used a test script to run the api call and nothing changes.

The api didn't raise any error, and the returned data was right, but without the updated fields.

**Comment by paddatrapper** [comment]
The managed flag simply prevents migrations from being run on the DB tables listed. That is there because currently propel manages those migrations and the API needs updating to reflect changes there. Ultimately that needs to change so that Django handles the migrations, but I'm not sure we can set Propel to not handle them.

The fact that is isn't updating on a call to that method is definitely a bug...

**Comment by jooola** [comment]
Haha, funny one. So if the content type of you payload is not properly set, django will simply ignore it the data and try to ingest what he finds as valid.

We were using the api-client `RequestProvider` and `ApiRequest` tools to call the django api, and they didn't specify any content type for the json payload.

So this has been fixed with the rewrite of the api client v2. It now supports patch requests and add the content type when passing a dict to the json parameter.
