### ISSUE TITLE
How do we organise/split the api code

### ISSUE THREAD

**Issue by jooola** [libretime/libretime#1622]
This is an issue I've been thinking about a long time now, but since I haven't worked much in the API it wasn't really the moment to raise it.

I wonder how we plan to organize the code in the api service. I think we cannot continue with the current organization which simply packs everything in single files and do not have any logical separation by concerns.

A option is to split each concern by app, for instance having a `core` app with auth, users, version and status calls.
Another app could be `shows` with all the show, show instances, playlist and smart blocks.
Another app might be `storage` with files, but I am tempted to have this into core, while this might include some analyzing tasks.
And so on.
Also we might also require a `legacy` django app which hold all the legacy related tasks such as migrations or command line actions. This might be faded out in a far far future.

We could also use a single app but split concerns in different python modules, but I know that migrations conflicts might become difficult to handle in that case.

There are extensive discussion on the internet on how one should organize his Django project, and I think we should think about this before doing any further changes to the API. 

@paddatrapper What is you idea on this ?

I am leaning toward a multi app architecture, separated by logical concerns, concerns that you maybe described in https://github.com/LibreTime/libretime/issues/935#issuecomment-571940765 but I feel those categories are already too close to the real code. I would see wider categories.

**Comment by paddatrapper** [comment]
I also like the multi-app approach, I think it is the most future-proof
