### ISSUE TITLE
Dedicated user that run libretime

### ISSUE THREAD

**Issue by jooola** [libretime/libretime#1637]
We should consider adding a dedicated user to run the multiple LibreTime services.

For now we use `www-data` to run all the services. I think `www-data` is a generic user that might have already too much permission and might be used by other programs.

`www-data` will still  be used to serve files with the web server and handle uploads, but I would go towards a php-fpm solution, with the php process running as `libretime` and `www-data` simply having read only permission where it is needed.

We also have a dedicated `celery` user, but I think we should remove this celery user and use this new `libretime` user.

Regarding the backend services such as playout or analyzer, they definitely don' require the `www-data` user.

Depending on web server stack structure, we should have:
```bash
# Running user: libretime
/etc/systemd/system/libretime-analyzer.service

# Running user: libretime
# what about the uwgsi package user?
/etc/systemd/system/libretime-api.service

# Running user: libretime
# what about the celery package user?
/etc/systemd/system/libretime-celery.service

# Running user: libretime
/etc/systemd/system/libretime-liquidsoap.service

# Running user: libretime
/etc/systemd/system/libretime-playout.service

# Owner: libretime
# once liquidsoap does not write here anymore, we could change the permission to root
/etc/airtime

# Owner: libretime
# add www-data to the libretime group, for read only permission
/etc/airtime/airtime.conf

# Owner: libretime
/var/log/libretime

# Owner: libretime
/var/lib/libretime

# Owner: libretime
# how does the webserver write in here ?
/srv/airtime
```

**Comment by paddatrapper** [comment]
> # how does the webserver write in here ?
/srv/airtime

Once the API handles file upload, the webserver doesn't need access - celery downloads podcast items and then the API handles all uploads. The PHP file upload form and potentially the album art would need migrating

**Comment by paddatrapper** [comment]
Also with PHP running as `libretime` under php-fpm, what file upload does the web server require? It all goes through PHP anyway to read the config and place it correctly
