### ISSUE TITLE
Problem: Python magic does not match what major distros package

### ISSUE THREAD

**Issue by hairmare** [LibreTime/libretime#166]
## Issue

When installing with some pre-release packages I chose to install python-magic as a package. Turns out there are multiple libraries called python-magic and the one from the [official file command](http://www.darwinsys.com/file/) is not the one that [analyzer is using](https://github.com/LibreTime/libretime/blob/54ded86f6de3233c53e1dcbcb4f81902e508bed1/python_apps/airtime_analyzer/setup.py#L34). As detailed on https://github.com/ahupp/python-magic/issues/33 they share the same namespace in python and no one seems willing to do anything about it.

Since this is rather confusing I made a table to illustrate it:

| pypi package | python namespace | distro package | distro version | pypi version |
| ---- | ---- | ---- | ---- | ---- |
| `python-magic` | `magic` | not available | not available | 0.4.13 |
| `file-magic` | `magic` | `python-magic` | >= 5.11 | 0.3.0 |

This becomes a problem when we start packaging LibreTime in distro native formats because we need to package an additional dependency. I think the pip installed magic version takes precedence over what a distro installs but the packages both having the same namespace doesn't help at all.

## Proposed Solution
Given that the python-magic package installs the *official* binding on both [Debian](https://packages.debian.org/unstable/python-magic) and [CentOS](https://centos.pkgs.org/7/centos-x86_64/python-magic-5.11-33.el7.noarch.rpm.html) it think it makes most sense to rewrite our code to use that.

The needed package is also on [pypi](https://pypi.python.org/pypi/file-magic/0.3.0) <strike>but I can't seem to work out why it's version is too low</strike> and it's versioning doesn't match the distro package version because it's a separate python api version instead of being in sync with the main package.

See #169 for an implementation of this solution

**Comment by paddatrapper** [comment]
So this has become an issue again... Debian has moved to [python-magic](https://github.com/ahupp/python-magic) from Buster onwards, which means that Ubuntu 18.04 and 18.10 also [use it](https://launchpad.net/ubuntu/+source/python-magic)
