### ISSUE TITLE
Move systemd services files to /usr/local/lib/systemd/system/

### ISSUE THREAD

**Issue by jooola** [libretime/libretime#1665]
I am used to deploy systemd unit files to `/usr/lib/systemd/system`. According to https://unix.stackexchange.com/a/367237 it is recommended to deploy software service files to `/usr/local/lib/systemd/system`.

I think we should change the deploy path of the services files to either  `/usr/lib/systemd/system` or `/usr/local/lib/systemd/system`, as this should give us the possibility to overwrite the service files without worrying about admin custom changes in theses files.

A administrator can edit/overwrite some details of a service simply by running `systemd edit [--full] libretime-<name>.service`, which will create a new service file in `/etc/systemd/system` for the admin to edit. If the `--full` flag is used the original service files will be copied over before edition.

I am unsure which path is the right one, we could continue the idea that `/usr/lib/systemd/system` is for distro packages and `/usr/local/lib/systemd/system` for manually installed softwares. But I don't know if the `/usr/local/lib/systemd/system` is properly supported on all systems ?

https://www.freedesktop.org/software/systemd/man/systemd.unit.html
https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Unit%20File%20Load%20Path

**Comment by paddatrapper** [comment]
We would need to test it on the systems we support. I agree that installing to `/usr/local/lib/systemd/system` is the correct approach

**Comment by jooola** [comment]
The `/usr/local/lib/systemd/system` dir does not exist on debian by default, haven't tested if systemd scan this dir yet.

**Comment by jooola** [comment]
In the end I don't think it worth to add complexity to the deployment process, and I think we are fine by using `/usr/lib/systemd/system`.
