### ISSUE TITLE
weekly program widget and radio page do not use minified angular

### ISSUE THREAD

**Issue by Robby262** [LibreTime/libretime#167]
Change all (I only found one) code refs from:
 https://ajax.googleapis.com/ajax/libs/angularjs/1.3.16/angular.js
to
https://ajax.googleapis.com/ajax/libs/angularjs/1.3.16/angular.min.js
That is quite a big size reduction and you get a small, but noticeable, speed increase for free.

**Comment by Lapotor** [comment]
Hm will test later

**Comment by Robby262** [comment]
That's why I posted it. :) Been fine here for 2 days. It is only Google's minified version of the same thing.

**Comment by Robby262** [comment]
I have been minifying the unminified css files, one by one, also. Its slowly speeding up as I go.

**Comment by Robby262** [comment]
Just following Google's Speed insights stuff. Nothing controversial.

**Comment by hairmare** [comment]
I can only find [this reference](https://github.com/LibreTime/libretime/blob/3196603dde94bd806341a546fc292eb54fbc59d2/airtime_mvc/application/controllers/plugins/PageLayoutInitPlugin.php#L178) to the non minified version of angular in the backend. It does look like [the weekly program widget](https://github.com/LibreTime/libretime/blob/d6b7a86048e40448cd8ef5c4733da1087abcf20c/airtime_mvc/application/views/scripts/embed/weekly-program.phtml#L5) is still doing the wrong thing though. Are you sure the backend is doing this wrong?

I think there used to be a minification script that did most of the work at build time but I can't seem to find it again (and what I remember seeing certainly needs fixing).

**Comment by hairmare** [comment]
Also, it shouldn't be using the cdn version of angular as there is already one installed in `js/libs/angular.min.js`. The installed version is a slightly newer version than what is being referenced here and a cursory check shows that the weekly program most likely needs some slight refactoring to work with the backends version of angular.

**Comment by hairmare** [comment]
BTW, the minification script I was thinking about is [part of the release script](https://github.com/LibreTime/libretime/blob/ebd7c1d2a32e6dd8b2fec55eb9a53c849a0150f9/dev_tools/release/release.sh#L57-L61) but it's commented out. I think the js parts need an overhaul just as badly as php needed what was done in #14. I've been wanting to start on that refactor for a while but it's not going to be a simple one since lots of the libs used have local patches.

**Comment by Robby262** [comment]
>>"Are you sure the backend is doing this wrong on every page?"
It does it on the main index (radio station page) for sure (which does contain the schedule). The other pages 'seem' to be faster too. I will check it here. Maybe it's an illusion, I did minify some other stuff too.

**Comment by Robby262** [comment]
@hairmare  "It does look like the weekly program widget is still doing the wrong thing though." What have you found that it is doing wrong? It seems to work on my set up. I had thought it was wrong until I realized that it shows 7 days starting, with the current day (in the user's timezone) and showing the times (in the user's timezone), and not the Show Week from like Sunday to Saturday.

**Comment by hairmare** [comment]
Thanks for your feedback!

> What have you found that it is doing wrong?

I was confirming your findings. Without any changes it uses the non minified cdn version of angular (aka the wrong thing 😛 ). 

> It does it on the main index (radio station page) for sure (which does contain the schedule). 

The radio page embeds the weekly program widget using an iframe so fixing it certainly has an effect on it. The rest of LibreTime already uses the locally installed version.

It looks like I caught them all with #168

**Comment by Robby262** [comment]
Just a side note. A stand alone(-sh) responsive version of that weekly schedule widget has been made for plugging into websites. It works here.
