### ISSUE TITLE
Replace uwsgi with a ASGI replacement

### ISSUE THREAD

**Issue by jooola** [libretime/libretime#1719]
Moving towards the modern ASGI protocol, to support async and websockets.

https://asgi.readthedocs.io/en/latest/introduction.html#what-s-wrong-with-wsgi

I propose to use uvicorn + gunicorn https://docs.djangoproject.com/en/4.0/howto/deployment/asgi/uvicorn/

**Comment by paddatrapper** [comment]
Sounds good. They are both in the Debian repos and have been for a while. Looks like packaging is consistent and continuing. With that happening in Debian, it should trickle into Ubuntu nicely.

**Comment by jooola** [comment]
It is recommended to use ninx next to gunicorn +uvicorn, so we might want to wait for #1186 

That said, I am already experimenting in the ansible role with nginx and I should be able to add gunicorn as well.
