### ISSUE TITLE
Podcast Importer now just shows a spinning icon and doesn't import anymore.

### ISSUE THREAD

**Issue by Robby262** [LibreTime/libretime#172]
After a bunch of Ubuntu Trusty updates today,  the Podcast Importer now just shows a spinning icon and doesn't import anymore. Anyone else seen this?
Normal manual track import works fine.

**Comment by Robbt** [comment]
See if airtime-celery is running. We haven't gotten it into the status page yet, but if you run _grep -ir 'celery'_ from the command line it should so. If it is running check out the logs at /var/log/airtime/airtime-celery.log and see what is happening. It's possible you are running into the issue that I had with the newest version of celery 3.0.2 not working.

**Comment by Robby262** [comment]
Nothing returned from your grep command but these two are in the process list:
  693 	celery 	Apr19 	/usr/bin/python -m celery worker --config=celeryconfig --app=airtime-celery.task ...
      1059 	celery 	Apr19 	/usr/bin/python -m celery worker --config=celeryconfig --app=airtime-celery.task ...

Last few lines from  log: 
[2017-04-19 05:33:38,938: INFO/PoolWorker-1] Task podcast-download[php_58f6f6ab058778.88496622] succeeded in 6.35129423201s: '{"status": 1, "episodeid": 19, "fileid": 76}'
[2017-04-19 08:18:16,669: ERROR/MainProcess] consumer: Cannot connect to amqp://airtime:**@127.0.0.1:5672//airtime: [Errno 111] Connection refused.
Trying again in 2.00 seconds...

[2017-04-19 08:18:18,677: INFO/MainProcess] Connected to amqp://airtime:**@127.0.0.1:5672//airtime
[2017-04-19 08:18:18,685: INFO/MainProcess] mingle: searching for neighbors
[2017-04-19 08:18:19,703: INFO/MainProcess] mingle: all alone
[2017-04-19 08:18:19,724: INFO/MainProcess] airtime-celery@x-pedia ready.

**Comment by Robbt** [comment]
Ok, so the issue appears to be with connecting to the airtime rabbitmq server. Hmm, have you tried downloading other podcast items to see if it produces the same log ?

Was it working before the update and do you know what packages were updated ?

Is rabbitmq up and running ? I'm not sure what is causing this issue specifically with the podcast service being able to connect, because if rabbitmq were down the airtime_analyzer file import etc would also not be working.

**Comment by hairmare** [comment]
The `[2017-04-19 08:18:18,677: INFO/MainProcess] Connected to ...` line looks like it's connecting ok. I'm not sure why it's failing on the first connect though.

You can check which version of celery that is used by running `pip show celery`. The version needs to be <4. Over here 3.1.1 seems to work. Did you install from git or a tarball? The celery fix from #161 hasn't made it into a tarball yet. 

I'm planning on doing a release soon but want to be sure that we don't break liquidsoap in the release as reported in #140 or #146.

**Comment by Robby262** [comment]
I installed from tarball.
celery --version
4.0.2 (latentcall)

**Comment by hairmare** [comment]
Yupp, that's it. `pip install 'celery<4'` should get your install fixed and the soon to be tagged 3.0.0-alpha.1 will do that per default.

**Comment by Robby262** [comment]
Oh dear - its not happy at all now. It's celery and kumbu versions are all mixed up - even after uninstalling and reinstalling both. Seems residual files in usr/local/bin still ref 4.02 - and more. Still digging.

**Comment by hairmare** [comment]
Maybe an additional `pip install 'kombu<3.1'` helps?

I'm [hoping for a celery release](https://github.com/celery/celery/issues/3974) that addresses this but am not holding my breath.

**Comment by Robby262** [comment]
Seems I might have it fixed now. Thanks all
