### ISSUE TITLE
Rename api_client to api-client

### ISSUE THREAD

**Issue by paddatrapper** [libretime/libretime#1722]
We should rename the api_client to api-client so that it is consistent with the other python apps

**Comment by jooola** [comment]
I guess the idea behind this is to handle this https://github.com/libretime/libretime/pull/1471/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52 ?

**Comment by paddatrapper** [comment]
The folder. Yup, to avoid the work around there

**Comment by jooola** [comment]
Ok, I am fine with the change. I don't think we have too much logic based on this specific folder name.
