### ISSUE TITLE
Ubuntu 16+ support

### ISSUE THREAD

**Issue by OdinWynd** [LibreTime/libretime#174]
Please support ubuntu 16+

**Comment by Robby262** [comment]
See here: https://github.com/LibreTime/libretime/issues/173

**Comment by Lapotor** [comment]
And here: #157

**Comment by hairmare** [comment]
I just merged basic ubuntu 16 support. Please keep in mind that it's still experimental at this stage.

I'm pretty sure that there will be some bugs lurking in weird places (ie. silan segfaults [debian#855319](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=855319) and maybe more issues).

**Comment by hairmare** [comment]
This was fixed with 3.0.0-alpha.2. Please reopen if there are still any issues.
