### ISSUE TITLE
Upgrading LT v10 -> 11 Installer STOPS 

### ISSUE THREAD

**Issue by JohnnyC1951** [libretime/libretime#1742]
#1 add-apt-repository: command not found error in Ubuntu 18.04. Installer fails.
Proposed Solution - add this at the top of the installer (I have reported this several times and repeatedly told it is in all versions of Ubuntu, but it is not).

sudo apt-get install software-properties-common

#2 Installer STOPS

make[2]: Leaving directory ‘/root/libretime/legacy/locale’
make[1]: Leaving directory ‘/root/libretime/legacy’
make: Leaving directory ‘/root/libretime/legacy’
Install default Airtime apache configuration? (Y/n):
cp: not writing through dangling symlink ‘/usr/share/airtime/php/legacy/vendor/bin/phing’

Install stops and get a bash prompt.

Note:
File: /usr/share/airtime/php/legacy/vendor/bin/phing
Type: broken symbolic link to …/phing/phing/bin/phing
Size: 0 bytes Blocks: 0 IO Block: 4096 symbolic link

**Comment by paddatrapper** [comment]
Try move the vendor directory (e.g. vendor.bak) and rerun install. Composer should re-download the dependencies

**Comment by paddatrapper** [comment]
For the apt-add-repository issue, what Ubuntu image are you using and on what provider?

**Comment by JohnnyC1951** [comment]
I have used suppliers' images frpm Contabo, Euserv and a few more. All do NOT have that command preinstalled. I cannot see why we cannot simply add it to the install list as this debate has gone on for 6 years and it is completely non hazardous.

**Comment by JohnnyC1951** [comment]
After removing the vendor folder, the install completed with an OOPS.
Apache log says:
[Sat Apr 09 12:10:06.974889 2022] [php7:warn] [pid 17478] [client 51.15.13.176:46266] PHP Warning:  require_once(/usr/share/airtime/php/legacy/vendor/autoload.php): failed to open stream: No such file or directory in /usr/share/airtime/php/legacy/application/preload.php on line 5
[Sat Apr 09 12:10:06.974995 2022] [php7:error] [pid 17478] [client 51.15.13.176:46266] PHP Fatal error:  require_once(): Failed opening required '/usr/share/airtime/php/legacy/vendor/autoload.php' (include_path='.:/usr/share/php') in /usr/share/airtime/php/legacy/application/preload.php on line 5
[Sat Apr 09 12:19:09.925278 2022] [mpm_prefork:notice] [pid 1089] AH00169: caught SIGTERM, shutting down

**Comment by paddatrapper** [comment]
> I have used suppliers' images from Contabo, Euserv, poneytelecom.eu and a few more. All do NOT have that command preinstalled. I cannot see why we cannot simply add it to the install list as this debate has gone on for 6 years, is completely non hazardous and stops the install if not present,

I ask to try establish the impact of this bug. There is no existing bug report for this particular issue and accusing the maintainers of not bothering to try fix it is not helpful to the discussion. I have proposed a fix in #1755 

> [Sat Apr 09 12:10:06.974995 2022] [php7:error] [pid 17478] [client 51.15.13.176:46266] PHP Fatal error: require_once(): Failed opening required '/usr/share/airtime/php/legacy/vendor/autoload.php' (include_path='.:/usr/share/php') in /usr/share/airtime/php/legacy/application/preload.php on line 5

What is the content of /usr/share/airtime/php/legacy/vendor/ after the second install run?

**Comment by JohnnyC1951** [comment]
Accusing testers is not helpful to the discussion.

**Comment by JohnnyC1951** [comment]
/usr/share/airtime/php/legacy/vendor$ ls
autoload.php
composer
jooola
php-amqplib
simplepie
bin
james-heinrich
paragonie
phpseclib
zf1s
