### ISSUE TITLE
What are the different mime types of the stored audio files ? 

### ISSUE THREAD

**Issue by jooola** [libretime/libretime#1750]
I am working on replacing the playability check in the analyzer with a basic mime type check, configurable through the config file.

I am wondering what are the different mime type we encounter in the different radio stations running LibreTime.

Could some of you paste the result of the following query in some of the radio station you are managing ?
```sql
select distinct mime from cc_files;
```

The result will be used to populate a good default in the configuration schema.

Related to #1470 #1449

@paddatrapper @hairmare @Robbt

**Comment by paddatrapper** [comment]
Why replace it? The way it is structured now ensures that any file supported by liquidsoap can be imported. Reducing that to commonly used doesn't really add anything for us

**Comment by jooola** [comment]
This assumption is not true, playability does not fail on wma files for example (see #1449). With recent version of liquidsoap I don't htink this is the right way of checking for this.

In addition the check if not behaving as we expect see https://github.com/libretime/libretime/blob/652349c7494545106b2686a61f7305702133bc4a/analyzer/tests/pipeline/analyze_playability_test.py#L35-L41

**Comment by jooola** [comment]
To elaborate some more, liquidsoap is with recent version relying on ffmpeg to do most of the decoding/encoding, so I expect most if not all the audio formats to be playable.

Using liquidsoap as wrapper to check if ffmpeg is capable of playing a file seem to add an extra dependency we could remove.

To simplify this, we could check for the mime type, exclude all non audio files, and then check if we allow this specific mime type, as I don't expect to play wma files and I know they will fail to play.

But people should be able to tweak this list of allowed mime types so we don't exclude people without giving a way to add some specific/custom audio files.

**Comment by jooola** [comment]
Closing as lack of answers.

The debate on how to check for play ability it another topic.
