### ISSUE TITLE
Support different base_url config for components

### ISSUE THREAD

**Issue by paddatrapper** [libretime/libretime#1758]
Currently the config `base_url` is used to form the URL for API requests and external access for users. This is problematic in proxy situations such as Docker (#1471) where they are not necessarily the same. There we need to configure access to the APIs internally using `nginx` as the hostname, while externally (in dev), the hostname is `localhost`. Perhaps the config we need is:

```ini
[general]
base_url = localhost
internal_api_url = nginx # Default to base_url if not defined
```

**Comment by jooola** [comment]
Related to #1574

I wonder if we can find a way to programmatically guess the internal url for the service.

I propose to make it clear that this internal URL should only be used/propagated by the service it is describing. I mean that I would prefer not having playout looking for the internal URL in the configuration file, but have the api for instance, put the right URL in the schedule it is building. Data flow would be `config => api => schedule (use internal or public?) => playout`.

In addition, if we end up having multiple services that require a internal service (say to parse a Prometheus endpoint, or a similar mechanism) we will need to have internal url for playout as well (I don't think it will happen, and we could use the message queue to pass data or announce a internal url/location, as the service register is already doing).

I would also prefer having this internal URL in a `api` section, not a `general` section. (In the long term I would like to have the general section being moved out of its section, I think this is only doable using yaml).

**Comment by paddatrapper** [comment]
I'm not sure we will be able to have the api publish it's end point because it will still be needed to get it from the api. Potentially we could push the config to redis and have it be picked up from there, but then requires integration between the API and redis.

An api section is a good idea.

```ini
[api]
url = http://internal.example # default to base_url if not provided
```

We already have a `playout` section, so adding additional sections for other components as required is consistent with the existing code.

**Comment by jooola** [comment]
> We already have a playout section, so adding additional sections for other components as required is consistent with the existing code.

Yes, this was one of my points to use the `api` section and not the general section. 

> I'm not sure we will be able to have the api publish it's end point because it will still be needed to get it from the api. Potentially we could push the config to redis and have it be picked up from there, but then requires integration between the API and redis.

The way I see the playout startup mechanism  (I think it already works somewhat like this) is that playout connects to the message queue and calls for the stream settings (currently through the API, but according to the new design document we will need the `message API` to pass those data), the same way as if we would configure the stream settings in the UI and push them to playout to reload.

So we could do a Request/Reply (RPC like) call though rabbitmq to get the internal URL, and use it were needed. Will keeping in mind that most of those communication will be moved to the message queue instead of API call.

**Comment by paddatrapper** [comment]
Sounds good. I like the idea of playout and liquidsoap pulling their config from the message queue instead of the config file. Makes things a little more centralised. It also means that we could trigger live re-loads for those later down the line if we want

**Comment by jooola** [comment]
The problem I see is that some web API endpoints are used by both public users and playout. So we should really make clear that (in the future) the message API is only for internal usage, using the internal url. And the Web API is used by the public, so we will be using the public URL. But I would not mix both or it will bring too much complexity.

**Comment by paddatrapper** [comment]
We will have to use both for the Web api though in some cases. For example local docker doesn't have a domain name, but typically port-forwards from localhost. In this case using http://localhost has the public url within components to, for example, download media for playout will break.

I think the division should be between internal and external traffic. External traffic uses the public url, while internal uses the internal one

**Comment by paddatrapper** [comment]
The message API is a while out, so I suggest we add a internal_url to the general section to match the public_url. This then is used by the various components where they currently use public_url. It defaults to public_url if not defined

**Comment by jooola** [comment]
This is how you expect the internal url to be used ?

[![](https://mermaid.ink/img/pako:eNqVkVFrwyAQx7-K-NyObk8lD4NB91AYI7DBHpJQLnpJZEbFKmto-t0XY8LSbS_1Qe_-_n93J54p0xxpQiupv1gD1pH3Xa7IsIRyaBW6bD8FRdSNL6VgB2P1qcvSMSFpSIprjqzXj6Sf3N7KhOAJWiPxjum2vyrzt3CEYymQEeeafaI9NProku1mu-mJqoU65SriR1_WFkxDZirKYY2-7DXsxY8qsQbWZS_jsdDBiOwDS_KU7heqkdBp77I0nsXcdnF309Az-2vKWGMYgTCtHAiFNgwU2Ps-RP_641MWSBQC9dBPSQRR8diVrmiLtgXBh98_h8ucugZbzGkyhBwr8NLlNFeXweoNB4fPXDhtaVKBPOKKgnf6rVOMJs56nE07AcM_tJPr8g3-aMoZ)](https://mermaid.live/edit#pako:eNqVkVFrwyAQx7-K-NyObk8lD4NB91AYI7DBHpJQLnpJZEbFKmto-t0XY8LSbS_1Qe_-_n93J54p0xxpQiupv1gD1pH3Xa7IsIRyaBW6bD8FRdSNL6VgB2P1qcvSMSFpSIprjqzXj6Sf3N7KhOAJWiPxjum2vyrzt3CEYymQEeeafaI9NProku1mu-mJqoU65SriR1_WFkxDZirKYY2-7DXsxY8qsQbWZS_jsdDBiOwDS_KU7heqkdBp77I0nsXcdnF309Az-2vKWGMYgTCtHAiFNgwU2Ps-RP_641MWSBQC9dBPSQRR8diVrmiLtgXBh98_h8ucugZbzGkyhBwr8NLlNFeXweoNB4fPXDhtaVKBPOKKgnf6rVOMJs56nE07AcM_tJPr8g3-aMoZ)

**Comment by paddatrapper** [comment]
I think so. I'd need to dig into the system and check what exactly needs to use it, but off the top of my head at least legacy and playout will need it (legacy for passing urls to analyzer). My plan is to go through where the code uses public_url and see if they need changing. So a fairly small change set overall judging by #1770

**Comment by jooola** [comment]
Haha #1770 is the final touch of a few other PRs.

I think you will be tempted to load the internal_url when the api-client loads the configuration file, but I was hoping to remove this hard dependency on the shared library.

**Comment by paddatrapper** [comment]
I am aware of that, but the places where public_url are used are there. The other place where I need to go through carefully is legacy, where there are places where the public_url should be used over the internal one.

It isn't strictly necessary. Passing the URL into the API client constructor would also work

**Comment by jooola** [comment]
Related and maybe duplicate of #515

**Comment by paddatrapper** [comment]
Yes, it is a duplicate of #515
