### ISSUE TITLE
CI: ensure that requirements.txt is up to date

### ISSUE THREAD

**Issue by paddatrapper** [libretime/libretime#1776]
The CI should generate requirements.txt for changes to setup.py files in PRs. If the generation introduces changes, the workflow should fail. This ensures that PRs keep the requirements.txt up to date with the setup.py files

**Comment by jooola** [comment]
A pre-commit hook is already handling this. Maybe it is broken though, did you find  a problem somewhere ?

**Comment by paddatrapper** [comment]
The last python dependency update was 1 Feb and requirements were generated on 28 Feb, so updates haven't yet occurred

**Comment by jooola** [comment]
Here is the pre-commit hook failing on the requirement txt task when removing a dependency. It should do the same in the CI.
![image](https://user-images.githubusercontent.com/19195485/164294922-b7934202-2f10-44a2-9535-c2252e8f8797.png)

> How will automated python dependency update PRs handle this? Will the CI fail until we run the update and push it to the branch?

dependabot is capable of handling both files at the same time https://github.com/libretime/libretime/pull/1652/files

> The last python dependency update was 1 Feb and requirements were generated on 28 Feb, so updates haven't yet occurred

Could you provide a link please ?

**Comment by jooola** [comment]
We even have an example of the CI failing with a difference between the setup.py and the requirements file.

https://github.com/libretime/libretime/runs/6075622988?check_suite_focus=true

Closing as resolved.

**Comment by jooola** [comment]
Now that we use renovate, we still have the CI failing because both files are not updated, but can renovate handle both files at once ?

**Comment by jooola** [comment]
Nevermind here is a perfectly working example 7a15a61d011be23f04b39af9581fbf0d1dfdc6cb
