### ISSUE TITLE
Question. Can we just rerun the install in the new alpha release?

### ISSUE THREAD

**Issue by Robby262** [LibreTime/libretime#178]
I mean over the top of the old one?

**Comment by hairmare** [comment]
I see no reason why it shouldn't not work but haven't tested it. Be sure to make a backup of the system and have a rollback scenario ready should it fail.

**Comment by hairmare** [comment]
I updated the docs to reflect that it should work by re-running. I didn't end up mentioning most of the update related issues like #182 since I haven't given up on fixing them. I did add a paragraph that recommends a reboot. Feel free to nag if you think something is missing.

**Comment by Robby262** [comment]
How about if it finds a database, it backs it up anyway?

**Comment by hairmare** [comment]
For the time being you should backup the database and file storage manually as outlined in [Backing up the server](http://libretime.org/manual/backing-up-the-server/) (at least I kept that in the docs for #188).

The docs also mention that it makes sense to set up a regular backup routine. I would consider automated backups a nice feature for the installer, it could probably help set up a working backup routine.

I do understand why this was never part of legacy upstreams automated things. In most cases setting up a backup needs some environment specific considerations. I can add more info on backups in general to the backup page of the docs but will need to try some restores and do more testing of the backup process it makes sense (I'm not really a PostgreSQL guy myself). 

I ended up created #190 to track what I think makes sense for helping everyone get better backups. Feel free to chip in over there if you have backup specific inputs.

**Comment by Robby262** [comment]
PGPASSWORD="airtime" pg_dump -h localhost -U airtime-W -F t airtime > /serv/airtime/airtime_pg_dump_file.tar
One line.
