### ISSUE TITLE
Question: How does LibreTime 3.0.0-alpha.1 compare to Airtime Pro?

### ISSUE THREAD

**Issue by gusaus** [LibreTime/libretime#179]
I've yet to test the current release, and it's not really apparent what the status of the project unless you're coding. Generally speaking how comparable is the latest release to Airtime Pro? What could non-developers do to help?

**Comment by Lapotor** [comment]
>What could non-developers do to help?

Test it and report issues that developers can fix them

**Comment by hairmare** [comment]
> Generally speaking how comparable is the latest release to Airtime Pro?

I haven't used the SaaS version so I can't really tell. The SaaS has an autodj feature that does things a bit differently than the autoplaylist feature in LibreTime. 

> What could non-developers do to help?

Translating the UI is another one that should be easy.

If you can write Markdown you can also help with the documentation. You would need to set up a vagrant box to check your changes and maybe learn a little bit of git so you can PR changes. Small changes might be doable through the "Edit on GitHub" link on the docs (it takes you to the right place on GitHub and has a guided process to get a pr done from there).

**Comment by gusaus** [comment]
I appreciate the feedback. My main involvement, aside from using and providing LibreTime services (including SaaS), will be to direct contributors (code, documentation, community), help fundraise (if needed), and other things that can help sustain the project.

Currently if new contributors land on https://github.com/LibreTime, it might not be clear how they can contribute. 

With regards to a hosted LibreTime, I'd assume many small stations and independent broadcasters/podcasters would not want to deal with setting up and managing themselves. I'll try to test and compare LibreTime to AirTime Pro. Would be interested if anyone else was able to do the same and/or has interest in using or providing a hosted version.

**Comment by Robby262** [comment]
I know a couple of AT users had a go at repacking a virgin AT install as an Ubuntu distro image, I have no I dea how that went, but that would be very simple for the vps hosters to install - poof - instant Libreirtime.

**Comment by hairmare** [comment]
From a non technical perspective the difference also lies in pro being an already available saas, with LibreTime you get most of what is available on the saas + some more features that are slowly being brought back from 2.5.x but you have to roll you own hosting.

If someone would want to create a hosted version based on LibreTime code that has features similar to the legacy saas then the code would probably need some serious cleanup. There's nothing impossible from a technical standpoint, but it would mean putting some resources into a couple of devs that help getting the code to a beta/rc level. I'd also recommend looking at the long term situation in any case (ie. help out with #2, #132 and other issues that help sustain LibreTime and the community in the long run).

That said, the broadcast market is competitive niche market and users can already choose from lots of providers. Someone with the right experience in both the radio market and the high bandwidth hosting market might be able to pull off offering hosted LibreTime at a competitive rate. As stated in #5 AWS is one solution to scaling.

**Comment by Robby262** [comment]
I would have thought that spawning Docker instances of Libretime on a dedicated server would do the job quite well, as long as you manually kept track of payments.

**Comment by gusaus** [comment]
>  I'd also recommend looking at the long term situation in any case (ie. help out with #2, #132 and other issues that help sustain LibreTime and the community in the long run).

Totally agree - we want to both encourage and make it easy for service providers to contribute back to the project and community. 

@hairmare Thank you for providing a summary of what our group could help with on the AWS side -https://github.com/LibreTime/libretime/issues/5#issuecomment-298017343 cc @ergonlogic

**Comment by Robby262** [comment]
My manager and I have found it fairly difficult to contribute, beyond bug reporting. Code does not seem welcomed, even sneered at on one occasion, so we make it available elsewhere, to anyone, including the team.
