### ISSUE TITLE
Move from Dependabot to Renovate

### ISSUE THREAD

**Issue by paddatrapper** [libretime/libretime#1794]
[Renovate](https://github.com/marketplace/actions/checkout#usage) is a project doing much the same thing as Dependabot, but it allows much more configuration. For example we can disable PRs on Forks (default) and configure the commit message and PR titles to conform to semantic commits (default if detected). It also will open a PR once the GitHub app is enabled with some default config that we can then update.

Suggested changes:

- move config file to `.github/renovate.json`
- enable pre-commit (`:enablePreCommit`)
- add labels
- `:preserveSemverRanges`
- `:disableDependencyDashboard`

**Comment by jooola** [comment]
I am happy with using renovate, the only small problem I had is the extensive configuration options that are sometime poorly documented. But I don't think we need to dive in the deepest corners of the renovate configuration schema.

And it seems dependabot does handle all the use cases you are raising. Though one of the feature I would like to have is the auto merging feature for patch versions (mostly for the website).

**Comment by paddatrapper** [comment]
Can definitely configure auto-merging for patch versions (and maybe all actions updates?) Not sure if we want all patches or just the website ones.

Dependabot's fork issue has been unfixed for 3 years... https://github.com/dependabot/dependabot-core/issues/2198
