### ISSUE TITLE
Reduce CI/CD usage 

### ISSUE THREAD

**Issue by jooola** [libretime/libretime#1798]
We should reduce the CI/CD usage by running some workflow only for some changed files.

This is not related to any pricing limitation, but simply make the workflows more reactive as we do have limitations on the number of concurrent workflows/jobs, and reduce some CPU usage (its free but still eats energy).

I propose to split the test workflow into multiple workflow per component (analyzer/api/api-client/playout/legacy/...) so we can trigger some test only if some files changed.

Having workflow per component would move the CI/CD in a monorepo like structure, which seems to fit our needs.

We can use reusable workflow to reduce duplication. I already have a working example here https://github.com/jooola/libretime/pull/86

This does mean a total rebuild of our test workflows.

**Comment by paddatrapper** [comment]
Sounds good. We're also hitting https://www.githubstatus.com/incidents/b40k7ckrs7sp as far as I can tell, which is slowing things down drastically
