### ISSUE TITLE
Import causes Files to be shorter than they are

### ISSUE THREAD

**Issue by Chris-The-Tuner** [libretime/libretime#1818]
**Describe the bug**
I found that an Install of the newest Version (as of April. 27th 2022) causes uploaded Files to be shorter (time wise) than they really are.
I have Files from EXACTLY 1 hour and if i import it it gets down to around 57:49 thats a huge issue.
We need to have it play the files 1:1 as they come since theese are recorded Radio Shows.

Probably i should mention this is an Issue with Settings.
LT sets the Cue Out point way to early.

**To Reproduce**
Upload a MP3 with a known length

**Expected behavior**
I expect LibreTime to import my File as is.

**Installation method:**

- OS: Ubuntu
- Method: `./install` script

**Comment by paddatrapper** [comment]
Is there any silence or very quiet sections at the start or end?

**Comment by Chris-The-Tuner** [comment]
Yes there are but:
Silences in the middle are sometimes intended.

But having a file cue out 5min. early in a 60min. File is excessive.

Is there any way to change this ?

With -40db this should not be a cue out 🙈

Talk shows just have this :(

**Comment by jooola** [comment]
> Silences in the middle are sometimes intended.

Silences in the middle of a track are kept in the length computation. No worries in that direction.

> Is there any way to change this ?

If the problem you are describing is a cue in/out problem, you can edit those values on the file metadata edit view.

**Comment by jooola** [comment]
For a fine grained configuration during analysis, we wait for #1595 which should give us the ability to pass settings from the config file to the analyzer.

**Comment by Chris-The-Tuner** [comment]
> If the problem you are describing is a cue in/out problem, you can edit those values on the file metadata edit view.

This is no solution, the recordings of our Shows are importet automatically and are played via smart Blocks.
I can't babysit the system every day to set cues 

Is there a script that i could edit to change rhis behavior ?
I don't need a clean config solution for now, i'm happy to have a workaround in the meantime.

**Comment by jooola** [comment]
You could comment out the entire cue point step, unsure if default values are inserted though.

https://github.com/libretime/libretime/blob/3d7083f60290812242b71bdde9dbd73882104c4f/analyzer/libretime_analyzer/pipeline/pipeline.py#L97

For more details on this cuepoint step:

https://github.com/libretime/libretime/blob/3d7083f60290812242b71bdde9dbd73882104c4f/analyzer/libretime_analyzer/pipeline/analyze_cuepoint.py

The silences are computed with the following:

https://github.com/libretime/libretime/blob/3d7083f60290812242b71bdde9dbd73882104c4f/analyzer/libretime_analyzer/pipeline/_ffmpeg.py#L67-L99

**Comment by Chris-The-Tuner** [comment]
I'm willing to try this out as a quick fix.

Where on the systems are the files for that ?
Standard Ubuntu Server install.

**Comment by maxtimbo** [comment]
> Where on the systems are the files for that ?

I don't know if you found them yet, but I've been looking for them as well.

I finally found them in `/usr/local/lib/python3.7/dist-packages/libretime_{whatever package}` 

Slightly off topic, but how did you automate importing files? Or are you using the web gui?

**Comment by Chris-The-Tuner** [comment]
I managed to do it with a PHP Script (easy and works).
You can find it on the discourse Page: https://discourse.libretime.org/t/automatic-file-system-import-watched-folders-more/171/22
