### ISSUE TITLE
Weirdness in schedule after upgrading to Alpha.1

### ISSUE THREAD

**Issue by Robby262** [LibreTime/libretime#182]
![screenshot_2017-04-22_10-32-18](https://cloud.githubusercontent.com/assets/27588708/25303285/8212d9a8-2747-11e7-9612-bfc5fbc5f01a.png)
This was after upgrading Alpha.0 - 'over the top' of the old one. 'Extra' shows in schedule in the past appeared. Hard to explain, see the screenshot. Also, I think if it finds an old Airtime when it installs, I think it should force a reboot as the old 'in use' processes seem to still be in use - especially celery - the restart of it said 'airtime-celery not found' but it was running.

**Comment by Robby262** [comment]
**After a reboot, this is showing in my process list, but looks a bit odd to me:**
/usr/bin/python -m celery worker --time-limit=300 --concurrency=1 -n airtime-celery@x-pedia --config=celeryconfig --app=airtime-celery.tasks:celery --loglevel=INFO --logfile=/var/log/airtime/airtime-celery.log --pidfile=/var/run/celery/airtime-celery.pid PID 699
**but has a child process of:**
/usr/bin/python -m celery worker --time-limit=300 --concurrency=1 -n airtime-celery@x-pedia --config=celeryconfig --app=airtime-celery.tasks:celery --loglevel=INFO --logfile=/var/log/airtime/airtime-celery.log --pidfile=/var/run/celery/airtime-celery.pid PID 1065
**which is identical. Is this normal?**

**Comment by hairmare** [comment]
Multiple celery processes are normal. You can actually configure how many processes celery should spin up to allow for concurrent processing.

I've seen a similar artefact once while I was hacking but was never able to reproduce it. I think the underlying reason stems from deleted repeats of a show. I think it's either that or a failed db upgrade. In the latter case calling `utils/upgrade.py` manually might fix it.

**Comment by Robby262** [comment]
I just realized that it was just one show that was extra and it was a complete week long to the second.

**Comment by bburton** [comment]
In the legacy upstream 2.5.1, there was a defect where if you created a repeating show with no end, then change the schedule deleting one instance of the show, then schedule a new show, instances of the deleted show will show up overlapping whatever is there on subsequent days. 

I have run into this issue with version 2.5.1 when I had to delete a repeating show instance each fourth Sunday of a month for a schedule change. This would cause the schedule to go haywire afterward with overlapping shows and in some cases.  In addition, some unrelated shows would just disappear.

**Comment by Robby262** [comment]
Yes. I remember that it was fixed in 2.5.2 at least in the dev branch

**Comment by hairmare** [comment]
I'll try to do some comparing of 2.5.2 to 2.5.1. I think we are missing some patches that went into the 2.5.1.
