### ISSUE TITLE
Track import behaviour suggestion - duplicate avoidance.

### ISSUE THREAD

**Issue by Robby262** [LibreTime/libretime#183]
When a track with the same filename as an existing one is imported, it appends the date to the filename and so it imports a duplicate. I realize that this must be intended behaviour, but fills the track list with duplicates and stops my weekly shows - which are all the same time length as each other - and whose filename ends in ...-full-latest.mp3 from self updating. Could we have a switch to allow overwriting of the old physical file on import? In AT OS version this was easily done with the watch folders which did not rename the file. Meanwhile, I will see if I can hack that. I have a friend who runs a Rock Station using AT OS but NOT watch folders that ended up with lots of duplicates of the same track of differing qualities uploaded by different DJs, so I guess it was the same before.

**Comment by hairmare** [comment]
I think your use case will be best covered with the watch feature once that is up and running.

Allowing duplicate uploads is kind of a feature. I think the reason is that the uploader can also delete his own tracks. You wouldn't want to have a track that you scheduled go missing due to that.

Some kind of duplicate detection would be great. I would probably implement it as a warning that needs confirmation instead of having it just overwriting existing tracks. It should probably look at the  the id3 tags and not the filename.

**Comment by Robby262** [comment]
My main problem has been the urgency and pressure to get the station backup, which I now have, after a fire in a server farm. The station was under the AT DEV branch, 100% automatic and imports 80+ complete shows/week into existing show slots, each show having 3 repeats at different times of day. It even pads the show main track (typically 60-130mb mp3) with jingles & music to the exact show length.
So getting that functionality back is my priority. My old import jobs still work and dump the files into what would have been a tree of watched folders. I can now bulk import from that folder into Libre Time but as the files are not over-written on import - the automated updating of the repeating shows does not work and I now have to manually load 83x3=249 shows per week.

**Comment by hairmare** [comment]
Yeah fires suck, we had one back in 1999 and had to rebuild quite some things afterwards.

If the shows you would like to replace with the bulk import always have the same length and tags you might get away with just replacing them directly in the stor directory. I'm not sure how pypos local cache of files to play would figure into this. I believe the cache's file retention is somewhat configurable with `cache_ahead_hours` in airtime.conf but am not sure when they get removed from the cache.

**Comment by Robby262** [comment]
Yeah, that is worth a go. I will try that right now. If it is like AT OS, it will re-cache just before the impending show, like 12 mins before. In which case its just using the stor folder like a watched one.
