### ISSUE TITLE
Watchdog Network Share Directories

### ISSUE THREAD

**Issue by maxtimbo** [libretime/libretime#1835]
Importing music via the web gui is fine, but I'd also like to just dump a bunch of files into a network share. These directories would be configurable to import them as a particular track type. The software would ingest them, process the metadata, and ultimately move them to the final storage location. 

Final storage location is (from what I understand) `/srv/airtime/stor`, which I currently don't know if/how to configure.

**Comment by paddatrapper** [comment]
Duplicate of #70
