### ISSUE TITLE
MusicMaster playlists

### ISSUE THREAD

**Issue by maxtimbo** [libretime/libretime#1836]
The ability to export a log from MusicMaster to a network share directory, which is ingested by LibreTime, and generates "Shows" or schedules tracks. This would be pretty big time, imho....

**Comment by paddatrapper** [comment]
Can you share an example file format?

**Comment by maxtimbo** [comment]
> Can you share an example file format?

Log export file format is configurable. 
But here is one example:

```
00:00:00,,IM3,VPTH00,"redacted ROTA","                   ",00:10,  , ,,
00:00:10,,300,DA0303,"PARALYZER            ","FINGER ELEVEN      ",03:24,04,C,,
[ . . . ]
00:49:50,.,COM,DALIVE,"49:50 Stopset",,06:30,,L,                 
[ . . . ]
00:59:30,*,,..MEMO,"59:30 SOFT SYNC",,00:01,,,                   
01:00:00,,IM3,VPTH00,"redacted TOH","                   ",00:10,  , ,,
```

I believe this file format is a csv. You can break this down like this:


|Time (24hr clock)| idk | Category | Cart Number | Title | Artist | Length | idk | idk | idk |
| --- | --- | --- | --- | --- | --- | ---|---|--|---|
|00:03:44,|,|300,|DA3224,|"WON'T STAND DOWN     ",|"MUSE               ",|03:26,|04,|C,|,|

Notice the "STOPSET" at 49:50

```
00:49:50,.,COM,DALIVE,"49:50 Stopset",,06:30,,L,  
```
That would be replaced by the traffic software log:

```
00:49:00,,COM,DA1234,"redacted","redacted",00:30,, , , , ,
00:49:30,,COM,DA1235,"redacted","redacted",00:30,, , , , ,
00:50:00,,COM,DA1236,"redacted","redacted",00:15,, , , , ,
```

Like I said, though; This file format is highly configurable. Here's an example for Play Out One:

```
#HOURSTART 01
SDROFF	True	-1	-1	-2		False	5613244	False
INPUTOFF	True	-1	-1	-2		False	5613245	False
IM1000	True	-1	-1	-2		False	5613246	False
[ . . . ]
	True	-1	-1	-2	TRAFFICMERGE START 45:00	False	5613274	False
	True	-1	-1	-2	TRAFFICMERGE END 52:00	False	5613276	False
[ . . . ]
RM1723	True	-1	-1	-2		False	5613286	False
	True	-1	-1	-2	SOFTMARKER 59:50	False	5613287	False
```

A break down from this file format:

| Automation Filename/Command| idk | idk | idk | idk | idk | idk | idk |
|---|---|---|---|---|---|---|---|
|IM1000	|True	|-1	|-1	|-2		|False	|5613246	|False|

"TRAFFICMERGE START" is replaced by commercials, handled by traffic software:

```
01:45:00	1234	TRUE	2640278	redacted	30	redacted	
01:45:30	1235	TRUE	2762035	redacted	30	redacted
01:46:00	1236	TRUE	2768500	redacted	60	redacted	
```

All that is needed is a way to import logs, be it traffic or music. That then needs to be consistent so Music Scheduling and Traffic Scheduling software can be configured to export as such. 

Here are a couple of scheduling software suites I've worked with or have heard about:
[MusicMaster](https://musicmaster.com/)
[Marketron](https://www.marketron.com/marketrontraffic/)
[GSelector](https://www.rcsworks.com/gselector/)
[Aquira](https://www.rcsworks.com/aquira/)
[Wide Orbit Traffic](https://www.wideorbit.com/products/traffic/)

I wouldn't try to reinvent the wheel by trying to recreate these software suites. Just a set of consistent ingest rules and a mechanism for which to ingest.

**Comment by jooola** [comment]
I am having a hard time understanding this feature request:
- The tracks are already in the storage ? We only schedule them using the provided playlists ?
- LibreTime will only play some of the tracks in the playlist as the traffic scheduling software will take over for advertisements ?
- LibreTime will have to keep blanks between tracks according to the point above ? Unusre if I understand the playlist entries, but seems like they are blanks between tracks ?

**Comment by maxtimbo** [comment]
> * The tracks are already in the storage ? We only schedule them using the provided playlists ?

Tracks are already in storage, yes. I don't know how the scheduling software talks to the automation software, but it does this and gets the database entries for Category, Cart number, Artist, Title, etc. Again, configurable...

I believe MusicMaster works with developers through an API. I remember at one point years ago looking into this deeper, but it's kinda fuzzy in my memory.



> * LibreTime will only play some of the tracks in the playlist as the traffic scheduling software will take over for advertisements ?

LibreTime would combine the logs from the two different suites. So Music Scheduler sends music logs, has inject points programmed for traffic. Traffic Scheduler sends traffic logs. LibreTime injects those traffic spots into the (I guess we can call it) the Master log. The master log is what is played.

**Comment by paddatrapper** [comment]
The 2 log idea is explored in #1222

**Comment by jooola** [comment]
As per our discussion in the community channels, this feature can be solved using a hand made tool by pulling the logs from the external scheduling platform, and build playlists/shows using the libretime api.

This will not land in LibreTime for the time being. Such integration should use either the api/webhooks or a plugin architecture inside Libretime (currently missing).
