### ISSUE TITLE
Does updating from one alpha to the next work?

### ISSUE THREAD

**Issue by celiandu61** [LibreTime/libretime#184]
Hey, I want to use libretime for my webradion. But idk how to update libretime without reinstall ? Just git pull and ./install again ?

**Comment by hairmare** [comment]
I think @Robby262 tried with #178 and I think it worked but haven't heard back from him.

**Comment by Robby262** [comment]
I used the new tarball and it had a couple of issues which i flagged up in #182 
I would recommend an immediate reboot after the update.

**Comment by hairmare** [comment]
Sweet, so it's mainly the overlapping shows bug (and the reboot thing which I consider minor compared to what's going on with overlapping shows). Thanks for reporting #182 btw.

**Comment by Robby262** [comment]
Before the update there was no overlapping show. Immediately after opened admin - without a reboot, it appeared. I do not tink that is a coincidence and it has not reappeared since. So, I figured, in the way of caution, it might be a the mismatch of versions - hence my suggestion for a reboot before running it.

**Comment by hairmare** [comment]
@celiandu61 `git pull` and `./install` is the proper way and I updated the docs with #188 to show that. You should consider having a backup of everything in case anything goes wrong and it is also recommended that you have a fallback system available during the upgrade to ensure broadcast continuity.

**Comment by celiandu61** [comment]
Ok, thx for your answers ! What do i need to backup ( to be sure to forgot nothing )  ? 
Config files, database, storage folder and it's all ?

**Comment by hairmare** [comment]
Exactly, the config files at `/etc/airtime/`, the storage folder which is usually at `/srv/airtime/stor`, and the database should cover what you need.

**Comment by Robby262** [comment]
Read the storage folder path from the database! It is common on raided systems to mount /home on another drive and to put storage on that. I would say the public folder too. People put custom widgets & extra stuff in there.

**Comment by hairmare** [comment]
> Read the storage folder path from the database!

The `/systemstatus` page at «Settings», «Status» shows the path the path without needing to access the db directly.

**Comment by Robby262** [comment]
Well yes, but I was thinking about a backup cron.
