### ISSUE TITLE
Installer Error with Python install

### ISSUE THREAD

**Issue by zklosko** [libretime/libretime#1846]
**Describe the bug**
During a fresh installation, I keep getting the error message:

```
The directory '/home/username/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
```

**LibreTime version:**
3.0.0-alpha-12

**Installation method:**

- OS: Ubuntu
- OS Version 20.04 LTS
- Method: git install

**Comment by paddatrapper** [comment]
What is the command you are using to install?

**Comment by jooola** [comment]
Those logs are harmless.

The only down side is that you won't be using the cached pip files during the installation process.

**Comment by zklosko** [comment]
`sudo ./install -fiap`
