### ISSUE TITLE
Improve status and checks 

### ISSUE THREAD

**Issue by jooola** [libretime/libretime#1848]
**Is your feature request related to a problem? Please describe.**

The current status page checks for process on the same host, this will not work with a docker setup.
Some of the checks aren't reliable, depending if the main process such a celery/gunicorn keeps running but the child process failed, we don't necessarily get the right status of the different services.

**Describe the solution you'd like**

Either make the check platform specific, one check for systemd, another one for docker.
Or to make the checks way more generic, such as a HTTP endpoint healthcheck.

I am tempted to implement a prometheus client in each of our apps to have an http enpoint to check if the process is actually running.

**Comment by paddatrapper** [comment]
Prometheus endpoints would be helpful, but not sure if it will introduce too much complexity, requiring some sort of HTTP library and thread support

**Comment by jooola** [comment]
We could also simply write proper documentation to get the status of either the systemd services, using #1849 or using healthcheck commands inside the docker definitions.

**Comment by paddatrapper** [comment]
After more thinking, healthcheck commands will be very useful in Docker for Kubernetes as well. I'm torn about removing the status checks from the web UI, but maybe documentation and options for integration into other monitoring systems is the way to go

**Comment by jooola** [comment]
Yup, I also think the docker health checks don't require any discussion, they will be useful.

I fell we should prioritize the documentation, and maybe only show some of the status checks if we have access to `systemctl`, so we really can check for failed services. Using pgrep seems a bit too hacky.

I personally would prefer removing the status page, but I feel it can be handy for those who don't like the command line interface, or want a quick look at the status without having to ssh on the remote server.

**Comment by jooola** [comment]
The documentation provides commands to check the status of the systemd services, the check page relies on the systemctl command to check the status of the different service.

Future enhancement, such as docker support should consider tweaking the docs and the check page to comply with this ticket.

Closing as resolved.
