### ISSUE TITLE
Add a systemd libretime virtual target

### ISSUE THREAD

**Issue by jooola** [libretime/libretime#1849]
**Is your feature request related to a problem? Please describe.**

Having to write all the different services names is not practical when restarting the services or checking the status.

**Describe the solution you'd like**

I propose to have a "virtual" service for libretime, a libretime.target, that shoudl be capable of managing all the services that are part of it and getting the status as well.

Restarting all the services should be as simple as running `sudo systemctl restart libretime`

https://www.freedesktop.org/software/systemd/man/systemd.target.html

**Comment by paddatrapper** [comment]
Sounds good. I remember I looked into this a while ago, but I think I went the wrong direction, which obviously didn't work and then gave up

**Comment by jooola** [comment]
I went a bit ahead of myself, I don't think we will be able to have the status of all the services only using the target, but start/stop should work.
