### ISSUE TITLE
eth0 is not the name of my device

### ISSUE THREAD

**Issue by maxtimbo** [libretime/libretime#1852]
I noticed in the final stanza of the install bash script that eth0 is hard coded as the device for either centOS or for Debian based systems. 

```
if $is_centos_dist; then
  IP=$(ip -o -4 address show dev eth0 | grep -Po 'inet \K[\d.]+')
else
  # not on centos
  ip_device="eth0"
  IP=$(ifconfig ${ip_device} 2> /dev/null | awk -F'[ :]+' '/inet addr:/ {print $4}')
fi
```

My system has reported enp6s0. Another system uses enp8s0, etc. etc. Debian also uses `ip`, so I'm not sure that that if statement is necessary. (Also, isn't CentOS EOL?) 

I'm not sure how easy it would be to grab the active ethernet device. I'm not a bash guru, nor am I an awk, sed, or grep guru (regex still alludes me). But I ran a few commands, and I hope I'm not muddying the water with this:

```
$ nmcli device status
DEVICE  TYPE      STATE                   CONNECTION         
enp6s0  ethernet  connected               Wired connection 1 
virbr0  bridge    connected (externally)  virbr0             
lo      loopback  unmanaged               --    
```
Maybe use `nmcli device status` to get `TYPE` and `STATE` to determine `DEVICE`, and then run 

```
IP=$(ip -o -4 address show dev $(ip_device) | grep -Po 'inet \K[\d.]+')
```

**Comment by jooola** [comment]
Will be fixed in #1821
