### ISSUE TITLE
Anyone got a safe way to switch off silan?

### ISSUE THREAD

**Issue by Robby262** [LibreTime/libretime#193]
It's way too vicious.

**Comment by Robbt** [comment]
Have you tried `sudo apt-get remove silan`
I tested that on a Ubuntu trusty vagrant box and I was still able to upload a track and it appeared to be processed correctly by the airtime_analyzer python app where I think silan integrates.

**Comment by Robby262** [comment]
Cool! Thanks. I thought of that but figured it would crash on a missing call target.

**Comment by hairmare** [comment]
I think this is about https://github.com/x42/silan/issues/3. If it is, silan isn't too vicious, it's plain broken. 

A fix was merged into silan [0.3.3](https://github.com/x42/silan/releases/tag/v0.3.3). As described in https://github.com/LibreTime/libretime/issues/177#issuecomment-296000748, my attempt at bumping it in Debian is at [debian@855319](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=855319). This is an additional candidate for having our own repo (my CentOS build is [here](https://build.opensuse.org/package/show/home:radiorabe:audio/silan) btw). 

I also think [removing silan](https://github.com/LibreTime/libretime/issues/177#issuecomment-296375404) with `sudo apt-get remove silan` is the way to go if you would like to deactivate silan in a quick and dirty fashion.

The easiest way to make it configurable would probably be adding the config to `/etc/airtime/airtime.conf`. Given it's an advanced option it might be feasible if turning it off has to be done manually in the conf file.

**Comment by Robby262** [comment]
I fixed it in #197

**Comment by hairmare** [comment]
Did switching off silan by removing it yield any results?

**Comment by Robby262** [comment]
Was mostly ok, but one track played so load it woke the cat up.

**Comment by hairmare** [comment]
Sorry about the 🐱. That was probably replaygain acting up and not silan.

I'm closing this since it looks like we've got a safe way to turn off silan. Thanks for the feedback.

**Comment by Robby262** [comment]
I guess there will be a log entry or two lurking. 'Where is my silan?'

**Comment by paddatrapper** [comment]
Silan 0.3.3 is now in Debian unstable

**Comment by hairmare** [comment]
@paddatrapper Awesome news! Thank you so much for taking over maintainership of the debian packages.

About debian generally, I've been working on adding debian 9 support to the vagrant installer but have been sidetracked a bit with getting everything to work under libvirt so we can offer a `vagrant up` experience that allows it to work without non-free virtualbox or parallels.
