### ISSUE TITLE
Feature: Aggregate Listener Hours in Listener Stats

### ISSUE THREAD

**Issue by bdaneu12** [LibreTime/libretime#196]
I need aggregation for the period specified in the analytics area for my reporting.

**Comment by hairmare** [comment]
Hello @bdaneu12

Welcome to the LibreTime community. We are glad to have you on board. Help us keep LibreTime open and inclusive by following our [Code of Conduct (CoC)](https://github.com/LibreTime/code-of-conduct/blob/master/CODE_OF_CONDUCT.md). Feel free to let us know if [CONTRIBUTING.md](https://github.com/LibreTime/libretime/blob/master/CONTRIBUTING.md) is lacking anything you need to get onboarded rapidly.

Thank you for your feature request. We are trying to ensure that the release history of LibreTime is a list of meaningful issues logged and solved. To achieve this we need you to help out 
by only logging explicitly documented and provable issues (see [C4:2.4](https://rfc.zeromq.org/spec:42/C4/#24-development-process) for details on this process).

You can filter the data from the UI at «Analytics» -> «Playout History» with the following control:
<img width="480" alt="screen shot 2017-05-04 at 01 35 24" src="https://cloud.githubusercontent.com/assets/116588/25685773/00409830-306a-11e7-8554-81003df898f9.png">

If you need to customize the output you can do so with «Analytics» -> « History Templates». 

Can I ask you to describe your use case in more detail? How do you need to aggregate the data? Do you have any links to documentation on the relevant reporting standards?

Cheers
Lucas

**Comment by bdaneu12** [comment]
I need the total hours of play on the streams. Example: I need to report how many hours of music was played to people listening to the audio feeds it was a feature in the PRO version. I think it was called total listener hours I think so right now I have to count every hour peak on the line graph to get my 980 ish total hours played.


On May 3, 2017, at 7:37 PM, Lucas Bickel <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello @bdaneu12<https://github.com/bdaneu12>

Welcome to the LibreTime community. We are glad to have you on board. Help us keep LibreTime open and inclusive by following our Code of Conduct (CoC)<https://github.com/LibreTime/code-of-conduct/blob/master/CODE_OF_CONDUCT.md>. Feel free to let us know if CONTRIBUTING.md<https://github.com/LibreTime/libretime/blob/master/CONTRIBUTING.md> is lacking anything you need to get onboarded rapidly.

Thank you for your feature request. We are trying to ensure that the release history of LibreTime is a list of meaningful issues logged and solved. To achieve this we need you to help out
by only logging explicitly documented and provable issues (see C4:2.4<https://rfc.zeromq.org/spec:42/C4/#24-development-process> for details on this process).

You can filter the data from the UI at «Analytics» -> «Playout History» with the following control:
[screen shot 2017-05-04 at 01 35 24]<https://cloud.githubusercontent.com/assets/116588/25685773/00409830-306a-11e7-8554-81003df898f9.png>

If you need to customize the output you can do so with «Analytics» -> « History Templates».

Can I ask you to describe your use case in more detail? How do you need to aggregate the data? Do you have any links to documentation on the relevant reporting standards?

Cheers
Lucas

**Comment by hairmare** [comment]
The current «Analytics» -> «Listener Stats» only has information on the amount of connected users. It looks like the «Aggregate Listener Hours» feature was implemented after legacy upstream stopped publishing open source code. This means we need to re-implement it from scratch.

To be able to do this we need the feature to be explicitly documented. The following questions spring to mind and might help you get started should you be willing to document your needs.

* Where should we get what data from?
* How should it be displayed?
* What granularity do we need these stats in?
* What length of data retention is needed?
* Can we retain aggregated data or do we need the raw data?

I'm sure there are more questions I missed. Please help us make this issue meaningful enough that we can consider implementing it.

BTW, the output we currently have does not expose actual listening hours, adding up the values from the Listeners graph will probably not result in the right value.

**Comment by bdaneu12** [comment]
I will work on that for you right now this seems to be what I am looking for but I will find out once I try to install this into one of my test servers.


http://sourcefabric.booktype.pro/airtime-25-for-broadcasters/icecast-statistics-with-piwik/

/chapter: Icecast-Statistics-With-Piwik / Airtime 2.5 for ...<http://sourcefabric.booktype.pro/airtime-25-for-broadcasters/icecast-statistics-with-piwik/>
sourcefabric.booktype.pro
Icecast statistics with Piwik. Piwik (http://piwik.org/) is an open source web analytics platform which supports Icecast's log format, in Piwik version 2.0 or later.



________________________________

**Comment by hairmare** [comment]
Yes, that makes sense. Piwik will probably be able to answer your questions. 

If you find any issues with the docs, feel free to report them or contribute to fixing them in the LibreTime version of [Icecast statistics with Piwik](http://libretime.org/manual/icecast-statistics-with-piwik/).

**Comment by jerry924** [comment]
I actually need this also for PRO reporting. I can get the data out of the database and load into Excel to create my reports, but should be easy to build this into the current reporting.

* Listener Stats DB table has a start time and a count of listeners. 
* We take that start time until the next start time as the number of listeners during that range
* We can store the listener count and time range in a Range Hash Map only storing transitions (say when it changes from 5 listeners to 6 or from 10 to 9, etc).
* Then in the playout log, we know the start and end time of each track that was played
* Going from the start of the track to the end of the track, find the maximum number of listeners during the time the track played. 
    * sometimes a whole track will span multiple ranges in the Hash Map
    * sometimes a many tracks will be inside one range in the Hash Map
* For each track you will now have counted how many listeners
* Now you can sum up all plays of the same track and get accumulated listeners

Your report will look like this:

Track       Artist           Accumulated Listeners          Total Plays
--------   ------------  ------------------------------- ------------
Song1     Bob               124                                          12
Song2     Joe                1293                                        45


I already do this in Excel, but it more tedious than having it built into the track report.

**Comment by bjjayk** [comment]
Did anyone succeed in installing this lately? 
I tried to follow the tutorial for piwik, which is now called matomo. but it seems pretty different from what the turorial tells us.
I am struggling with the import of the icecast log. I just get some html-output in the console of my VM. the piwik site itself doesnt show my any data.

anyone who can help with this?

thanks
Jay

**Comment by Robbt** [comment]
I plan on doing this as a part of my improving the listener statistics effort. I'll share how documentation for how to get it to work with LibreTime if and when I figure it out.

**Comment by JohnnyC1951** [comment]
This is probably not the place to say this. I would like to see the Analytic graph be a stacked bar graph. That will save me adding all the streams up.

**Comment by bjjayk** [comment]
So to update you guys, I installed matomo suite. It has some free plogin for icecast but it is not that useful.
I also used the importer script, that seems to give us somewhat useful data.
The problem is that we have to import that manually all the time.
But what I learned from that is, that after the import there is actually a DB field that contains the time per session and this could be summed up by the MySQL is no time.
I am not sure though whether that duration is calculated by matomo/piwik or if it is already in the logs of Icecast.

Maybe it would be useful to copy what that import script of matomo does and keep the rest. It basically comes down to a couple of interesting information from that:
* location
* duration and maybe 
* aggregated schedule, when listners tune in.

**Comment by bjjayk** [comment]
https://coherent-receiver.com/google-analytics-and-icecast

maybe this would be of help. I think google analytics would be a good choice for many

**Comment by JohnnyC1951** [comment]
We already have such figures in the postgres database

**Comment by frecuencialibre** [comment]
see also @ned-kelly 's docker implementation: https://github.com/frecuencialibre/docker-multicontainer-libretime#icecast-google-analytics

**Comment by JohnnyC1951** [comment]
Internally. LT uses flot.js to display the stats. I would start by plundering that code as it works and is integrated.

**Comment by bjjayk** [comment]
> see also @ned-kelly 's docker implementation: https://github.com/frecuencialibre/docker-multicontainer-libretime#icecast-google-analytics

This seems to work.
I followed iroks tutorial, and it works from shell, but somehow doesn not keep runnung and the cron didnt work as well.

**Comment by bjjayk** [comment]
So after I tried to license my radio for Switzerland I, which was pretty easy and has no restrictions in the contract whatsoever, also wanted to be able to broadcast internationally. Therefore I contacted Audion GmbH , which represents IFPI, and after 4 weeks without response, I am now confronted with a so-called "small webcaster" contract.
Despite hilarious penalty fees for possible contract breach, and other very interesting terms, there is also a part about what is to be reported:
Number of listeners *per country* for each song being played out

so since all reports seem to be pretty complicated I wanted to ask here first, whether this seems possible to do?

all software I was testing so far never had a report function of listeners per country per song. I can see why they want this, for distributing the royalties internationally. But I don't see a solution for a small webcaster to realize that.

Any ideas on that?

**Comment by Robbt** [comment]
I think that matomo aka piwk offers geographic analytics, i don't know any of the specifics but I don't think this would be very easy to do with Libretime currently, but yeah IPs can roughly be connected to certain countries, it would seem like unless you were really big it wouldn't make sense to worry about international licensing. Sorry I can't be of much help with this as I don't know anything about what is required or how often/complete they expect reports. You might be better off using a 3rd party stream monitoring tool that compiles statistics than what is currently built-in. Maybe you can get what you need out of matomo see https://github.com/LibreTime/libretime/issues/283#issuecomment-427573205 for a possible use of ARCCloud that might be relevant.

**Comment by bjjayk** [comment]
Well, I have matomo installed. So there is a GeoIP database for the visits.
But obviously, matomo links the data to the URL being visited and not the particular song.
I wonder if there are other users out there trying to internationally broadcast and solved this?

I don't see how I would be able to link the exact amount of listeners per country to a song being played out. This would mean computing all IPs of a certain playout time representing the song, counting visitors by country and then put it into relation to the played out song.
I am not a programmer so this task is out of scope. And it can't be done manually.

So I guess my radio project is going to end before it even fully started.

**Comment by Robbt** [comment]
The Icecast logs could be correlated to a specific song based upon time and analyzed with Matomo they should contain geo-IP. There are a couple of other options, I have no idea about the EU laws but it might not be necessary to get international licensing. I am nearly 100% sure that most US stations don't do this but instead just deal with various US based reporting agencies so I'm not sure, you could ask someone like @hairmare and see what his station does, they're also based in Switzerland. The other option which might be kind of annoying but you could block everyone from listening who isn't based in Switzerland where you have the licensing covered see [this link](https://mediarealm.com.au/articles/icecast-stream-geoblocking/). Hope that is helpful. Is there a public link to the reporting format/requirements that can be shared so that I can look at what they are asking for ? I doubt it would be easy to write but it'd be good to compile everything.

**Comment by Robbt** [comment]
Yeah I would suspect that a small webcaster is not their target audience. I think that the maxmind geoIP database could be integrated into LibreTime but would require a fair amount of work to segregate listeners per song per country.

**Comment by iroks** [comment]
Despite hilarious penalty fees for possible contract breach, and other very interesting terms, there is also a part about what is to be reported:
> Number of listeners _per country_ for each song being played out 
> so since all reports seem to be pretty complicated I wanted to ask here first, whether this seems possible to do?
> all software I was testing so far never had a report function of listeners per country per song. I can see why they want this, for distributing the royalties internationally. But I don't see a solution for a small webcaster to realize that.

the post is older and I assume that you clarified this question. If not: before mentioned  Icecast2GoogleAnalytics v2 can do it
