### ISSUE TITLE
Define support distributions matrix

### ISSUE THREAD

**Issue by jooola** [libretime/libretime#1966]
We currently advertise that we require either Ubuntu LTS or Debian stable to install LibreTime.

In reality, we also try to support Bionic and Buster.

Now that v3 is nearly out, I would like to raise this distro version matrix discussion again. I think LibreTime should develop on the current stable distro only, and provide patch versions for oldstable distros.

The main reason I see LibreTime running on old stable distros is that the software was installed at the time old stable was stable, and upgrading requires maintenance work that might not be available. In the same idea, LibreTime is not be upgraded to a next "major" or even "minor" version to prevent downtime or introduce bugs in the radio station, which again requires maintenance work.

So supporting bionic and buster until there EOL for those specific use case might be sensible. Though, we have been breaking a lot of stuff between alpha's, and the reasoning above doesn't completely stand with regards to stability when we talk about the pre 3.0.0 versions.

So I propose to support the current stable distros for fresh installs, and only support old stable distros with patches upgrades.

Here is a idea of what I could see:

|              | Ubuntu 18.04 | Debian 10  | Ubuntu 20.04 | Debian 11  | Ubuntu 22.04 |
| ------------ | ------------ | ---------- | ------------ | ---------- | ------------ |
| Release date | 2018-04-26   | 2019-07-06 | 2020-04-23   | 2021-08-14 | 2022-04-21   |
| End of life  | 2023-04      | 2024-06    | 2025-04      |    2026-06        | 2027-04      |
| Versions     |              |            |              |            |
| 3.0.x        | supported    | supported  | supported    | supported  | WIP          |
| 3.1.x        |              |            | supported    | supported  | WIP          |

This should allow use to reduce the version matrix on some parts of the project, such as Liquidsoap ( I really want to drop liquidsoap < 1.4.x)

This kinda mimics a distro packaging behavior, where the software is maintained with security/bug fixes only for the time the distro is not EOL.

**Comment by paddatrapper** [comment]
This sounds reasonable. I suspect that by the time we get to 3.1, Debian 12 will be released, but that doesn't really affect things. How do you foresee things going forward - do we make a decision before each minor release about which distros we are supporting or do we determine an algorithmic support timeline?

**Comment by jooola** [comment]
`3.1.x` is only an idea of a next version, this could even be `4.0.x`.

I think we should evaluate depending on the changes that landed or that we allow to land in the main branch. So checking on each release (also considering semver) to define if we should maintain a version branch. Unsure if that can be expressed using an algorithm.

I consider 3.0.0 as a MVP after the fork plus cleanup / improvements. This version had to go out, but I think our work will break things again really soon, as our focus is on the rewrite.

I think we will drop bionic/buster really soon as we have to support liquidsoap 2.0.0 asap and maintaining 1.1.1 => 2.0.0 will be a nightmare.

**Comment by paddatrapper** [comment]
Yeah, sounds good. I am happy with that and it allows us to move things forward fairly quickly
