### ISSUE TITLE
Allow reloading liquidsoap from a remote playout 

### ISSUE THREAD

**Issue by jooola** [libretime/libretime#1997]
**Describe the bug**

In order to reload the liquidsoap config, playout use the following command:
https://github.com/libretime/libretime/blob/067b35e9bb5b5f437e93e0e3cf30fff0a45b999f/playout/libretime_playout/player/fetch.py#L180-L183

This does not permit updating the stream configuration from the UI while running libretime with docker-compose.

I see multiple ways of going around this

- Implement a liquidsoap harbor handler that allow playout to trigger a restart and liquidsoap restart on its own.

I am not sure I like allowing a restart from a remote location, but that might be the best solution.

Though, inside a container, killing pid 1 will stop the container, so we need a wrapper around liquidsoap that handle the config generation + restart. We will probably have to replace os.execl from the liquidsoap startup. 

- Move liquidsoap to a thread / subprocess of playout, so we only run a single playout container and manage the liquidoap restart in playout direclty.

Having liquidsoap as a service/container removes the really high uptime requirements from the Playout service, meaning we should be able to restart Playout (understand 5s downtime to gracefully stop and start) without having a stream interruption, while restarting liquidsoap WILL interrupt the stream.

So maybe it's a bad idea.

**Comment by jooola** [comment]
Also, an easier way to fix many of these problems is to use a file based stream config and remove the UI stream configuration.

This should also fix many issues we have in the project, such as public URLs, SSL harbor setup, and so one.

**Comment by paddatrapper** [comment]
Ultimately I think we should move the stream configuration into the config file. It shouldn't change that often on production systems and solves a lot of the issues we are running into about it
