### ISSUE TITLE
Bug when trying to edit tacks

### ISSUE THREAD

**Issue by Guillarda** [libretime/libretime#2000]
**Describe the bug**
When I want to change the metadata of a track and I save the metadata, the change does not apply and when I check the log, errors appear.

**To Reproduce**

1. Go to Tracks (in dashboard)
2. Click on a track
3. Click on a edit
4. Edit metadata
5. Click on save
6. See error in file

**LibreTime version:**
Version: 3.0.0-alpha.13

**Installation method:**

- OS: Ubuntu Server 
- OS Version: 20.04.4 (LTS)
- Method: sudo ./install PUBLIC_URL
- Details: git clone https://github.com/libretime/libretime

**Screenshots**
https://imgur.com/q6XccZv

**Client (please complete the following information if applicable):**

- OS: Windows 10
- Browser: Chrome
- Version: 103.0.5060.134 (Build officiel) (64 bits)

**Comment by jooola** [comment]
I could not reproduce this, file is saving as expected and no error logs.

Could you please tell me:
- which field you edited ?
- if you have track types ?
- if you upgraded from a previous version ?

**Comment by jooola** [comment]
Youhouuuu it's ticket number #2000, this calls for celebration 🎉  haha !

**Comment by Guillarda** [comment]
No matter which field I edit I always have this same problem

I don't have a track type

I didn't upgrade from an old version I just did a clean install

**Comment by jooola** [comment]
I tried again on ubuntu 20.04 LTS, could not reproduce the error.

Please provide more details on the error your are facing and details about your installation. Maybe also the logs please (and please no screenshot, those aren't useful).

**Comment by jooola** [comment]
I reproduced it, I'll dig into this.

**Comment by Guillarda** [comment]
Perfect, you've solved the problem
So to get it on my machine I have to wait for the next update I guess, right?

**Comment by jooola** [comment]
> Perfect, you've solved the problem So to get it on my machine I have to wait for the next update I guess, right?

You either wait for the next release or cherry-pick the commit and apply it to your installation:
```bash
# Pull the latest changes
git checkout main
git pull

# Return to version 3.0.0-alpha.13 and apply the fix
git checkout 3.0.0-alpha.13
git cherry-pick f137be09a1b2b1509768fa50960f02dbb04edeb1

# And rerun the install script
```
