### ISSUE TITLE
Time issue in song sheduling and listener stats. 3.0.0-alpha.13 

### ISSUE THREAD

**Issue by Michal4K** [libretime/libretime#2014]
**Describe the bug**
Manual scheduling show set wrong end time. Song start time is set correctly, but endtime is set to startime + playtime - 2 hours.
So the end time is before the start time.
I have server timezone set to Europe/Prage UTC+2h.

Also i thing time Listener Stats is -2 hours offset too. At 21:30:45 Europe/Prague i see last reported stat wit this timestamp:
1659461445
Tue Aug 02 2022 17:30:45 GMT+0000
Tue Aug 02 2022 19:30:45 GMT+0200

Maybe i just have somewhere incorrectly set time zone. But i didn't find anything what could cause this issue.

**To Reproduce**

1. Make clean install on Debian 11
2. upload song
3. create show starting now
4. manually add track to current show

**LibreTime version:**
 28cec51

**Installation method:**

- OS: Debina 11
- Details: installed exactly as describe here https://libretime.org/docs/admin-manual/setup/install/

**Screenshots**
![20220802_21h08m32s_grim](https://user-images.githubusercontent.com/12269903/182460199-7f91edca-f959-4374-8ad7-75356e3ea698.png)
![20220802_21h33m27s_grim](https://user-images.githubusercontent.com/12269903/182460216-2ee8b880-ebc8-4e93-9a49-90738a9ee7fd.png)

**Comment by jooola** [comment]
Hey, thanks for the ticket.

>  I have server timezone set to Europe/Prage UTC+2h.

Do you mean the operating system timezone or LibreTime ? There is a setting you have to configure with the right timezone if that's not already done.

![image](https://user-images.githubusercontent.com/19195485/182466362-339d82ec-55af-44bb-9fee-c2cae5582e6d.png)

The server stores datetimes @ UTC. And some parts of the software aren't consistent with displaying timezone aware or naive datetimes. So the error you are seeing is either a missing configuration or the UI not doing the timezone translation.

Related to #1455 #1201

**Comment by Michal4K** [comment]
I mean operating system timezone in libretime i have set it wrong. I correct but it didn't solve the issue. I try check the timestamps in db and the timestamps is wrong there too. Still can't schedule song correctly.

**Comment by jooola** [comment]
The listeners stats is not handling properly the date and times with timezones, this is known (by me at least, not sure there is a ticket), but it is a low priority issue.

The schedule bug is weird though, I'll try to reproduce this.

**Comment by jooola** [comment]
I could not reproduce the schedule bug. Please make sure you properly configure the timezone in the LibreTime global settings, and try again. If that does not fix it, I'll need more details from your setup. Maybe logs from legacy.

**Comment by Michal4K** [comment]
This is really weird. It is probably caused by some miss configuration in my system. I didn't actually install the system from scratch. I used template from our virtual environment. I tried reproduce this bug with clean install, but as you say it can not be reproduce.

For now i switch local time on my servers to UTC with dpkg-reconfigure tzdata and this solve the schedule bug.

I will trie to found what causing this scheduling issue in our debian 11 templates.

**Comment by Michal4K** [comment]
I found it. My issue is caused by broken time zones in our Debian 11 templates.

```
root@radio-h:~# zdump /usr/share/zoneinfo/UTC
/usr/share/zoneinfo/UTC  Thu Aug  4 14:17:18 2022 CEST
```

My issue wasn't solve by switching zone to UTC. It was solved by reinstalling tzdata, before i switch timezone to UTC.

So this is not related to libretime. Thank @jooola for your help me.
I think this issue can be closed now.

**Comment by jooola** [comment]
I think we can promote/improve the admin server time documentation in the install guide as preparation step so everything is in check before installing LibreTime.

I think a simple
```
$ timedatectl show --property=Timezone
Timezone=Europe/Paris
```
check and if the timezone isn't right link to a guide either our own or from the internet.
