### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by damidani** [libretime/libretime#2020]
**Describe the bug**
During the installation I get this error message
**To Reproduce**

sudo ./install http://IP

**LibreTime version:**
Version from the upgrade popup if you can reach it.
libretime-3.0.0-alpha.13
**Installation method:**

- OS: Ubuntu 20.04 & Debian 11

**Error**
cp: cannot create regular file '/usr/lib/systemd/system/libretime-api.service': No such file or directory

**Comment by jooola** [comment]
Hey, thanks for the ticket.

Could you please paste the entire install logs please ?

**Comment by damidani** [comment]
Hello I forgot to answer the answer I could find.
I installed libretile on a vos Lxc (container) proxmox once put in Vm that worked well. Depending on having some help

**Comment by tuxPM** [comment]
I got the same problem with official proxmox image of ubuntu (ubuntu-20.04-standard_20.04-1_amd64.tar.gz).
# ls -lh /usr/lib/systemd/
boot/                        logind.conf.d/               user-environment-generators/ user-preset/                 
catalog/                     user/                        user-generators/      

@damidani do you remember how did you fix it ?
