### ISSUE TITLE
Setup backport tools to cherry pick fixes into version branches

### ISSUE THREAD

**Issue by jooola** [libretime/libretime#2037]
Since we are going to maintain multiple versions of LibreTime, we will need to backport fixes to some of the version branches. This could be automated using back porting tools / bots.

Ideally, we could have a command that take a branch name as argument and opens a PR to backport the changes to this branch:

```
/backport 3.0.x
```

Some interesting tools: 
- https://github.com/sqren/backport

Here is how Nextcloud is handling it [https://github.com/nextcloud/server/pull/33495](https://togithub.com/nextcloud/server/pull/33495)

**Comment by paddatrapper** [comment]
That is a pretty cool tool. There is an action to manage it via labels I see

**Comment by jooola** [comment]
I am struggling a bit with multiple PRs and backporting changes.

Maybe we should leverage branch merges to update the main branch with changes made in 3.0.x. And sort/fix conflicts during the merge, instead of cherry-picking one commit at the time.

Or we should setup a tool that can help us.

Needs some thinking.

**Comment by jooola** [comment]
I think I made a mistake by naming the "stable" branch `3.0.x`, I propose to rename it to `stable` .

In addition maybe we can follow this logic for handling fixes and which branch is allowed to merge where:
[![](https://mermaid.ink/svg/pako:eNrFU8lOwzAQ_RVruJYqSSUOPiPBBQkBR1-mySS2iJ3IdlhU9d9xmqUlkFatkPAp8jzPW_SygbTKCDgUyt9ZrKUwLJy1RZNK5jyuS2KVzchyFkfdMJWUvlaN78f9ZaW18sJMIBqV-Q74Cb5ij5ZqtMoUDJmhd2apJHQ0u6uX18Ou40HhTTx5MiJ-533ajQPvEWOabEEHVB4LLuBttYyWkYBZid2zYdFAeF_5XH0cYeudyR1ub2w1jX4AnM72IQhpk5WnqDvFI_OBz_hsny9KE6vROXL_UYhkLEQyU4jkrwqR7IOKLyjEpUHBAsLCgMnCv7tpZwK8JE0CePjMKMem9K2cbYBi46vnT5MC97ahBTR1hp5uFRYWNfAcS0fbL9eRUSM?type=png)](https://mermaid.live/edit#pako:eNrFU8lOwzAQ_RVruJYqSSUOPiPBBQkBR1-mySS2iJ3IdlhU9d9xmqUlkFatkPAp8jzPW_SygbTKCDgUyt9ZrKUwLJy1RZNK5jyuS2KVzchyFkfdMJWUvlaN78f9ZaW18sJMIBqV-Q74Cb5ij5ZqtMoUDJmhd2apJHQ0u6uX18Ou40HhTTx5MiJ-533ajQPvEWOabEEHVB4LLuBttYyWkYBZid2zYdFAeF_5XH0cYeudyR1ub2w1jX4AnM72IQhpk5WnqDvFI_OBz_hsny9KE6vROXL_UYhkLEQyU4jkrwqR7IOKLyjEpUHBAsLCgMnCv7tpZwK8JE0CePjMKMem9K2cbYBi46vnT5MC97ahBTR1hp5uFRYWNfAcS0fbL9eRUSM)

This means we never merge the `main` branch in `stable without doing a release, all the fixes should always come from `stable` to `main`. We don't want to commit a fix in `main` while it is intended for `stable` and back port it to stable.

The stable branch can be merged in main any time we want to keep main up to date.

Though this is somewhat changing our versioning policy,  as we don't support multiple "stable" versions. (e.g. we want to maintain 3.0.x and 3.1.x). But we don't have this scenario yet, and we can always tag dev/alpha releases directly on the main branch.

@paddatrapper What do you think ? In terms of breaking change, I don't think anyone is using the branch 3.0.x or did we allow for users to use it ?

**Comment by paddatrapper** [comment]
I've started answering this a couple times, but ran out of time each attempt, so sorry for that.

I'm concerned about how this workflow interacts with C4. We're already deviating by releasing of a branch that isn't main, and this proposal deviates even more by merging fixes into stable as a typical fix development flow

**Comment by jooola** [comment]
Haha, we did deviate from C4, I would even say we deviated before using a maintenance release branch.

I read the entire C4 spec again and [another one with comments from one of the authors](https://hintjens.gitbooks.io/social-architecture/content/chapter4.html).

I think C4 doesn't perfectly fit our needs, the zeromq project and ours differ in many places, and I unsure if it is sane for the project to enforce C4 by the letter. For example, I feel that C4 was meant for libraries (zeromq), while we are a webapp. The Zeromq project and ours also differ in terms of contibutors, both the number and the nature of them (senior developer/learning to code) (entreprise backed/for fun).

We could probably supersede C4 and edit some parts to match our needs.

- I am fine with a single release branch, in that case we need to change our supported versions policy.

- We use conventionnal commits and I don't want to use the format defined by C4. While we ask for a reason/problem before implementing a feature, we don't define everything as being a problem. And we will loose some of the tooling build around conventionnal commits.

And probably some others specific parts, but the main points are already here.


Appart from not being compliant with C4, do you see issues that may arise with my idea ?

**Comment by paddatrapper** [comment]
Aside from C4, I don't see any issues with doing things the way you suggest
