### ISSUE TITLE
airtime-import not Found

### ISSUE THREAD

**Issue by Lapotor** [LibreTime/libretime#204]
Hello i want to import over 10GB of Musik over the Server it self. I uploaded the files to the server into the `/srv/airtime/uploads/incoming/` directory and then i want to run the command of airtime-import: `airtime-import copy /srv/airtime/uploads/incoming/imported/` the result is `airtime-import: Befehl nicht gefunden.`
What i should do

**Comment by Lapotor** [comment]
So i found the file and found a few errors.
[File Link](https://github.com/LibreTime/libretime/blob/master/utils/airtime-import/airtime-import)
The actuell is failure is: 
```
root@libretime:/home/libretime/libretime-3.0.0-alpha.1/utils/airtime-import# ./airtime-import
Traceback (most recent call last):
  File "./airtime-import", line 13, in <module>
    from mm2.media.monitor.pure import is_file_supported
ImportError: No module named mm2.media.monitor.pure
```
This is the line:
```
#sys.path.append('/usr/lib/airtime/media-monitor/mm2/')
from mm2.media.monitor.pure import is_file_supported
```
I can't find the path `/usr/lib/airtime/media-monitor/mm2/` on my server.
May it is moved or something i hope a few can help.

**Comment by Robby262** [comment]
It doesn't work. Look in the Issues lists regarding watched folders. Someone is working on it.

**Comment by Lapotor** [comment]
hm i did not find some that why only to add a function that rescan media folder

**Comment by Lapotor** [comment]
i think i get it #70

**Comment by Robby262** [comment]
Yes scheduled for next release
Someone made a for that seems to work - but it it quite a few files to patch

**Comment by Lapotor** [comment]
did you have the fork somewhere that i can overlook it ?

**Comment by Robby262** [comment]
In the meantime.. I am about to try this:
install LDXE light desktop, firefox and vnctightserver - already done and working.
Using a the remote VNC desktopand firefox, log into libretime using firefox (not chrome) and 'upload' the files from the server - through firefox - into libretime - all on the same server.

**Comment by Robby262** [comment]
JohnnyC made this, which some people were rude about #181
