### ISSUE TITLE
Output fails when moving tracks in current show

### ISSUE THREAD

**Issue by matias-tecnosoul** [libretime/libretime#2064]
When reordering some tracks in the current show we experience "cuts" or "jumps" in the output stream.

**To Reproduce**
1. Create a show with an autoloaded playlist.
2. When the show gets auto-loaded with tracks and starts playing, move some track's order in the current show dashboard. Moving or deleting scheduled tracks causes cuts in the output. 
3. Sometimes the cuts are brief but sometimes we experienced two tracks playing together. Removing the current scheduled track solved the overlapping.

**Expected behavior**
Reordering tracks in the current show sholud be possible without causing output errors.

**LibreTime version:**
05342e2e8

**Installation method:**

- OS: Debian
- OS Version: 11
- Method: ./install` script 
- Details: Git pulled.

**Client (please complete the following information if applicable):**

- OS: MacOS and Win
- Browser: chrome

**Comment by jooola** [comment]
When you say "some tracks" you mean you cannot always reproduce it ?
When does the cuts happen ? Directly when reordered or later on in the stream ?

Have you tried with alpha.13 ? I had a stream overlapping problem and fixed it, but unsure if the fix in before or after 05342e2e835ed4a336b257a09ff6b2c6a5ceb3b7

**Comment by matias-tecnosoul** [comment]
> When you say "some tracks" you mean you cannot always reproduce it ? 

Exactly. It happens randomly. Not every time I move a track but it happens very frecuently.

>When does the cuts happen ? Directly when reordered or later on in the stream ?

Directly. Right after moving a track.

> Have you tried with alpha.13 ?

No, I will try it. 

Could it be related to system's resources? I'm quite sure this is not the issue since I'm monitoring the server with "[Netdata](https://www.netdata.cloud/)" and don´t see any alerts. 
Thanks!

**Comment by jooola** [comment]
> Could it be related to system's resources?

Maybe, could you paste some logs ?
