### ISSUE TITLE
Problem: /srv/airtime/stor/imported belongs to root on trusty 3.0.0-alpha.1 vanilla install

### ISSUE THREAD

**Issue by Robby262** [LibreTime/libretime#207]
I just did a plain vanilla install from the tarball. Ubuntu Trusty.
It would not import. Every file failed.
On inspection I found that /srv/sirtime/stor/imported was set to root/root with no write access for any other user.
Changed the ownership and write access to www-data - and that seems to have fixed it.

**Comment by hairmare** [comment]
I think creating the folder with the right permissions is part of the setup routine done after the install script. Was there anything in the apache error log during that? Sometime errors don't show up in the regular zendphp.log but rather in $APACHE_LOG_DIR/error_log.

**Comment by hairmare** [comment]
I tried to reproduce this on a clean install to no avail. Here is what I did after setting up a basic trusty box using vagrant:

```bash
cd
curl -O -L https://github.com/LibreTime/libretime/releases/download/3.0.0-alpha.1/libretime-3.0.0-alpha.1.tar.gz
tar xvf libretime-3.0.0-alpha.1.tar.gz
cd libretime-3.0.0-alpha.1/
./install -fiap
```

After this I connected to the web interface, completed the setup as instructed by the webui and was able to upload files and play them back.

I also tried reproducing this with a pre-existing `/srv/airtime/stor` folder as follows.

```bash
mkdir -p /srv/airtime/stor
cd
curl -O -L https://github.com/LibreTime/libretime/releases/download/3.0.0-alpha.1/libretime-3.0.0-alpha.1.tar.gz
tar xvf libretime-3.0.0-alpha.1.tar.gz
cd libretime-3.0.0-alpha.1/
./install -fiap
```

In both cases everything seems to work as intended.

```bash
ls -al /srv/airtime/stor/
```
```console
total 16
drwxr-xr-x 4 www-data www-data 4096 May 23 12:46 .
drwxr-xr-x 3 www-data www-data 4096 May 23 12:44 ..
drwxr-xr-x 3 www-data www-data 4096 May 23 12:46 imported
drwxr-xr-x 2 www-data www-data 4096 May 23 12:47 organize
```

Maybe this depends on how exactly the installer is called. If you could post a log of the exact steps you took to help reproduce this that would be great.

**Comment by Robby262** [comment]
Sorry, been doing some more Airtime 2.5.2 installs and been busy. It looks very like the old issue 12 (which I now cant find).
I installed as root (not sudo) from command line, from tarball on Trusty. I saw AT had exactly this issue also, at one time and I saw a post somewhere from Robb who reported the same thing in LT.
I shall be doing another LT inst tomorrow - so I will keep an eagle eye out.

**Comment by Robby262** [comment]
I just did an install on an an Ocean Digital VPS Ubuntu Droplet 
All the folders under /srv are indeed www-data:www-data
So now I do not know what to say. :\ But I did not imagine it before. I had to manually fix it.

**Comment by hairmare** [comment]
Do you have any idea how the installs differ? Maybe `/src/airtime` was on a different mountpoint in one of the cases?

**Comment by Robby262** [comment]
they were both in like /libreinst

**Comment by hairmare** [comment]
It shouldn't matter where the tarball is unpacked. Maybe something is different in the base os installs? Where both setups on digital ocean?

**Comment by Robby262** [comment]
Yes
