### ISSUE TITLE
When shows ends, next shows starts without fade-in/fade-out

### ISSUE THREAD

**Issue by esbobkov** [libretime/libretime#2070]
**Describe the bug**
![image](https://user-images.githubusercontent.com/5690261/186404133-a1904d69-4877-49e6-9a03-17a648d69651.png)

I have this settings and my shows ends without fade out. How to fix it?
Shows programmed with autoloading playlists with dynamic SmartBlocks. "Allow last track to exceed time limit” enabled.

I don’t hear any difference when change “Default Fade Out” time

**To Reproduce**

1. Setup schedule and shows with autoloading playlists with dynamic SmartBlocks
2. Listen
3. No fade-out track in prev. show, when next show starts

**Expected behavior**
Hear fade-out track in prev. show, when next show starts

**LibreTime version:**
3.0.0-alpha.12, 3.0.0-alpha.13
liquidsoap 1.4.2, liquidsoap 1.4.4

**Installation method:**

- OS: Ubuntu
- OS Version: 20.04.4 Focal Fossa
- Method: `./install` script

**Additional context**
logs
```
2022/08/10 06:00:00 [server:3] New client: 127.0.0.1.
2022/08/10 06:00:00 [lang:3] vars.show_name
2022/08/10 06:00:00 [server:3] Client 127.0.0.1 disconnected.
2022/08/10 06:00:01 [cue_cut_9659:3] Cueing out...
2022/08/10 06:00:01 [cross_9665:3] Analysis: -17.615671dB / -nandB (0.00s / 0.00s)
2022/08/10 06:00:01 [crossfade:3] No transition: using default.
2022/08/10 06:00:01 [schedule_noise_switch:3] Switch to map_metadata_9743 with forgetful transition.
2022/08/10 06:00:01 [lang:3] transition called...
2022/08/10 06:00:01 [decoder:3] Method "FFMPEG" accepted "/var/lib/libretime/playout/scheduler/30.mp3".
2022/08/10 06:00:01 [dummy(dot)2:3] Source failed (no more tracks) stopping output...
2022/08/10 06:00:01 [dummy(dot)4:3] Source failed (no more tracks) stopping output...
2022/08/10 06:00:01 [s4:3] Prepared "/var/lib/libretime/playout/scheduler/30.mp3" (RID 0).
2022/08/10 06:00:01 [schedule_noise_switch:3] Switch to map_metadata_9732 with transition.
2022/08/10 06:00:01 [lang:3] transition called...
2022/08/10 06:00:01 [switch_9730:3] Switch to insert_metadata_9715.
2022/08/10 06:00:01 [lang:3] timeout --signal=KILL 45 libretime-playout-notify media '96018' &
2022/08/10 06:00:01 [lang:3] Using stream_format 0
2022/08/10 06:00:01 [lang:3] Using stream_format 0
2022/08/10 06:00:01 [lang:3] Using stream_format 0
2022-08-10 06:00:02.056 | INFO     | libretime_playout.notify.main:media:47 - Sending currently playing media id '96018'
```

**Comment by jooola** [comment]
I could reproduce this on the main branch, with bullseye. Fade in/out seem to be not working at all.

**Comment by esbobkov** [comment]
@jooola Any chance to fix it in near future?) How can I help?

**Comment by jooola** [comment]
> @jooola Any chance to fix it in near future?) How can I help?

Hey, yeah, I didn't do much digging into this one, as my focus was on releasing beta.0, and the tooling isn't quite ready yet for us to easily work on this.

I'll try again, but anything related to audio processing is currently difficult to work with.

**Comment by jooola** [comment]
Do you confirm that isn't working between tracks as well ?

**Comment by esbobkov** [comment]
Thank You! I understood.

> Do you confirm that isn't working between tracks as well ?
Yes, It's looks like it is

**Comment by ChronosX88** [comment]
Is there any workaround for it?

**Comment by lea-nsk** [comment]
I confirm that version 3.0.0-beta.2 (last updated on October 3rd) does not work with this function.

**Comment by hillfm** [comment]
Please fix it, I am very optimistic about this software!
