### ISSUE TITLE
Check for unused files across playout/liquidsoap containers

### ISSUE THREAD

**Issue by jooola** [libretime/libretime#2089]
**Describe the bug**

To clean it's media file cache, playout checks for unused files using the `lsof` command. This command expect to have liquidsoap running on the same host, and inform playout that the file is still being used.

https://github.com/libretime/libretime/blob/1edd941eb1ffef316d5d7bd3a2976abff4dc6754/playout/libretime_playout/player/fetch.py#L301-L305

In a multi container setup, lsof will not be able to check if a the liquidsoap process is using the files, we need to find another way of handling caching and garbage collection.

We also need to share the cache between the containers.

Maybe we should check via the liquidsoap server connection for unused files.

**Comment by jooola** [comment]
I need to check this lsof between container, maybe I made the wrong assumption and it is working.

**Comment by paddatrapper** [comment]
Do we reuse files? As far as I know each schedule item is downloaded, even if they point to the same media file

**Comment by jooola** [comment]
> Do we reuse files? As far as I know each schedule item is downloaded, even if they point to the same media file

I think we will have some problems with how it is currently handled:

https://github.com/libretime/libretime/blob/d3d622929dafe987b22f57c831f5c3dac6d02f0b/playout/libretime_playout/player/file.py#L41-L81

Having playout handling the cache while liquidsoap is the consumer is tricky, and liquidsoap doesn't give much details about files that have already been played. I'll read the liquidsoap documentation, maybe they provide a way to actually query for that info from the server.

**Comment by paddatrapper** [comment]
We could just cache every file

**Comment by jooola** [comment]
All files are cached, the problem is that we reuse the exact same file if it is scheduled again, and this would create a race when liquidsoap clean the file.

Maybe we should be smarter and not reuse the same filename for different play request, and use hardlink to prevent duplication ?

**Comment by paddatrapper** [comment]
I mean cache them separately. We don't end up using much disk space, as the roll over is only an hour. Just download each scheduled item even if it is already in the cache. I guess the downside is more writes in some use-cases, which could be an issue for SSDs

**Comment by jooola** [comment]
Marking this issue as "feedback needed" because the ticket is more a hypothetical problem that might happen but we didn't yet encountered it.
