### ISSUE TITLE
Digital Ocean Install issues Ubuntu Trusty LAMP droplet

### ISSUE THREAD

**Issue by Robby262** [LibreTime/libretime#209]
Maybe not really an issue - more a - 'Don't do this stupid thing Grandad!'. Continuing my install testing, I ran the install directly from a command box down tightvnc Gui.
Cryptography failed to compile - it was complaining of no TLS certificate available.
The install ran on for a few minutes and stopped in a sad heap.
Hmm.
I re-ran it down an ssh link and it almost installed. I got the Ist install screen up with configuring Postgresql which said Postgresql was not available. Other tools said it was.
Then the whole thing locked solid and I lost all control of the droplet. A reboot gave me no login access.
Abandoned as I could make no further progress.

**Comment by Robby262** [comment]
Update. Ran the same setup on the same server but on xenial.
Installed perfectly.

**Comment by hairmare** [comment]
Did you capture any log output to help narrow this down? I was able to install 3.0.0-alpha.1 on Ubuntu Trusty/14 running on dply.co (which is on digital ocean as far as I know) using the following cloud-init:

```bash
#!/bin/sh
export DEBIAN_FRONTEND=noninteractive;
# The HOME or COMPOSER_HOME environment variable must be set for composer to run correctly
export COMPOSER_HOME=/tmp

# update system
apt-get update;
apt-get -y upgrade;
apt-get install unzip;

# change to /tmp and download libretime
cd /tmp;
curl -O -L https://github.com/LibreTime/libretime/releases/download/3.0.0-alpha.1/libretime-3.0.0-alpha.1.tar.gz;
tar xvf libretime-3.0.0-alpha.1.tar.gz;
cd libretime-3.0.0-alpha.1/;

# install libretime
./install -fiap;
```

Dply has a free for developers tier that allows creating machines that are free for two hours, those are perfect for testing the install. They also allow creating "Deploy now" buttons. See below for an example that automatically deployed on Ubuntu 14 earlier today.

Libretime 3.0.0-alpha.1 on Ubuntu Trusty/14
[![Dply Libretime 3.0.0-alpha.1 on Ubuntu Trusty/14](https://dply.co/b.svg)](https://dply.co/b/oh3SuXKO)

To actually see the installers output you can connect to the box and run `tail -f /var/log/cloud-init-output.log`. 

The same cloud-init script worked fine (as in installed w/o error) on Ubuntu Xenial/16 but the resulting install exhibits #175.

**Comment by Robby262** [comment]
Hmm Plupload is not working on my Xenial - just as you reported above
