### ISSUE TITLE
Change api url /api-auth to /api/v2/auth

### ISSUE THREAD

**Issue by jooola** [libretime/libretime#2092]
Is there any reason for this particular url ?

This should simplify the reverse proxy url catching.

**Comment by jooola** [comment]
Maybe /api/v2/auth is a bad idea. As we might want to have something else there.

**Comment by paddatrapper** [comment]
/api/auth would work. It is that url because that is the generally given standard for DRF. I wouldn't want to stick it under the v2 path because it shouldn't be tied to the version of the API being used

**Comment by jooola** [comment]
The urls only include pages for the api browser (/login and /logout). So maybe we can namespace this under `/api/browser/` ?
