### ISSUE TITLE
New version available: 3.0.0-alpha.1 << after update

### ISSUE THREAD

**Issue by aresstokrat** [LibreTime/libretime#211]
Hi ! Thank you for your great work!

After updating to alpha.1 i still get this message in backend with red "!" buttn.
I did uninstall (with dropping tables in DB) before reinstall. 

small bug ;-)

**Comment by Robby262** [comment]
This is a known bug and it is just cosmetic.

**Comment by hairmare** [comment]
See #198 for more info.
