### ISSUE TITLE
Provide a vanilla icecast docker image for our container setup

### ISSUE THREAD

**Issue by jooola** [libretime/libretime#2136]
We currently use the https://hub.docker.com/r/infiniteproject/icecast docker image in the docker compose definition. This image has not been update for the past 2 year. While icecast didn't receive any update since then, some of the dependencies have and we should probably rebuild icecast onto these new dependencies (mainly thinking about the xslt and xml libraries that received some security fixes in the past years).

In addition, infiniteproject/icecast does not provide the beta versions of icecast, which could be handy for testing in libretime.

I don't want to add any features to the docker image, the image should be `vanilla`, so anyone else can reuse it.

It is only a matter of setting up a repo, and scheduling CI runs to build and push the images.

Regarding versioning, I think we should tag newly created images with `2.4.4-20220914` (icecast version  and current date), `2.4.4`, `2.4`, and `latest`.

Icecast should be compiled from the sources and not installed from the debian packages, or we will be limited when building beta images.

**Comment by paddatrapper** [comment]
I agree. This sounds reasonable

**Comment by jooola** [comment]
Here is my candidate https://github.com/jooola/icecast-docker

Once tested, we might want to move it to under the libretime umbrella.

**Comment by paddatrapper** [comment]
Looks good. That Dockerfile is sensible to me

**Comment by jooola** [comment]
> Looks good. That Dockerfile is sensible to me

What do you mean by sensible ?

**Comment by paddatrapper** [comment]
Meaning the way it is broken up and ordered is good, I didn't see anything major I would improve

**Comment by jooola** [comment]
So the icecast image is ready, I found a way to prevent publishing new tags when no changes occurred.

@paddatrapper I just send you a transfer request for the icecast-docker repo, so you can transfer it to the organization.

**Comment by paddatrapper** [comment]
Sure, will do

**Comment by paddatrapper** [comment]
It's moved to the LibreTime organisation

**Comment by jooola** [comment]
Great, thank you !

**Comment by paddatrapper** [comment]
> Maybe you can advise me about which ssl backend is better ? I didn't used curl with gnutls, and I think this diverges from the debian package.

Sorry, I meant to have a look at this, but haven't had a chance. Should get to later today

**Comment by jooola** [comment]
> Sorry, I meant to have a look at this, but haven't had a chance. Should get to later today

All good, it's a really specific question, was just hoping you already had an opinion based on your Debian fu. I could simply read the docs about it.

**Comment by paddatrapper** [comment]
There is some things I vaguely remember, but need to just confirm things

**Comment by paddatrapper** [comment]
The largest difference between gnutls and openSSL is the license - GPL-licensed code needs to have a specific exception to link against openSSL. That is why a fair bit of the Debian archive links against gnutls instead. Other than that I'm not sure there is a particular preference either way
