### ISSUE TITLE
Publish containers to the public

### ISSUE THREAD

**Issue by jooola** [libretime/libretime#2145]
We currently build and and tag the containers from tags and the main branch.

The containers are pushed to ghcr.io/libretime/*.

I mentioned in the PR for the containers setup that we should probably use ghcr.io for development purpose and unreleased versions, and use docker hub for tagged release. I think we can apply this strategy starting with 3.0.0.

We should have:
- `ghcr.io/libretime/libretime-<app>:main`
- `ghcr.io/libretime/libretime-<app>:3.0.0-beta.0`
- `ghcr.io/libretime/libretime-<app>:<3.0.0|3.0|latest>`
- `libretime/libretime-<app>:<3.0.0|3.0|latest>`

Do we see any limitation in this ? Shouldn't we rather mirror both registries so we don't have any surprises ?

I wonder if we will have problem between branches names and tags.

Also, the [current packages on ghcr.io are private](https://github.com/orgs/libretime/packages), and I don't have the permissions to open them to the public, maybe @paddatrapper  you can do this ? (Note: the `libretime-dev` image should not be exposed to the public)

**Comment by paddatrapper** [comment]
I've changed the visibility to be public for all images except `libretime-dev`.

I don't see an issue with this. Maybe we prepend tags with `v` (e.g. `v3.0.0`) to avoid collisions with branches? Or name version support branches `3.0.x` for example.
