### ISSUE TITLE
Audio not synced with schedule

### ISSUE THREAD

**Issue by esbobkov** [libretime/libretime#2195]
**Describe the bug**

After upgrade to beta.0 
Wrong audio in stream from previous show.
It's happens sometimes

Restart liquidsoap and playout services fixes problem

**To Reproduce**

1. Setup schedule and shows with autoloading playlists with dynamic SmartBlocks. `Allow last track to exceed time limit` enebled
2. Listen
3. When new shows started, track from previous shows doesn't cut-off and play till the end. "On Air" indicator is grey.

**Expected behavior**
 Track from previous shows cut-off and track from current show start play

**LibreTime version:**
3.0.0-beta.0, 3.0.0-beta.1
liquidsoap 1.4.4

**Installation method:**

- OS: Ubuntu
- OS Version: 20.04.4 Focal Fossa
- Method: `./install` script

**Comment by jooola** [comment]
Could you paste the logs please, for liquidsoap, playout and legacy ?

**Comment by jooola** [comment]
And could you show whether the schedule has been generated ?

**Comment by rjhelms** [comment]
I am experiencing this same issue, on version 3.0.0-alpha.12 after upgrading from alpha.8.

Here are the relevant logs - there was nothing logged in legacy.log for this time period.

[playout.log](https://github.com/libretime/libretime/files/9767615/playout.log)
[liquidsoap.log](https://github.com/libretime/libretime/files/9767616/liquidsoap.log)

There are 3 30-minute shows, at 17:00, 17:30, and 18:00. The show at 17:00 played normally, but had files extending past the length of the program. The file playing at 17:30 continued to play, causing the content for the 17:30 program to not start until it ended at approximately 17:44. Then the program at 17:30 began, 14 minutes late, and continued to play past the start of the 18:00 program.

At this point I intervened manually and restarted liquidsoap and playout services per @esbobkov's comment. Will continue to monitor.

**Comment by rjhelms** [comment]
It also seems like Liquidsoap is not rotating logs properly, and continued writing some things to liquidsoap.2022-09-07_16-28-47_858161.log since the upgrade - here is the extract of that for the same time period:

[liquidsoap.2022-09-07_16-28-47_858161.log](https://github.com/libretime/libretime/files/9767829/liquidsoap.2022-09-07_16-28-47_858161.log)

**Comment by jooola** [comment]
The log rotation bug has been fixed since then, please upgrade to libretime 3.0.0.
