### ISSUE TITLE
Podecast Feature improvement wish list (to be added to).

### ISSUE THREAD

**Issue by ghost** [LibreTime/libretime#222]
*UPDATED 02:20 UK time 07 June
1. Track Title to be imported from Podcast Item Title, not the tag ID3 Title Tag
2. Track Description to be imported from Podcast Item Description, not the track's ID3 description. If that is empty, use the feed's description. This should be stripped of all html and utf 'weird stuff' and sanitized. IE smart quotes made dumb etc. (I have written php code for this, just ask, example output below).

Why? This avoids such joyful imports we have have had such track titles as '1234567.1.mp3' - when the podcast title is 'The future of solar engineering - with Dr David Gilben' and track descriptions like 'My 3rd cut - still  too much bass?' when there is a nice description in the podcast item description
(we have actually done this here using an external cron  SimplePie PHP CLI job but it would be far nicer if it did it by default)
**Example:** all but two shows in this whole week were derived from the Podcast feed data. 
[http://www.deprogrammedradio.com/at-widget/deprogrammed-radio-widget-test.php?nocache=156375#currentshow](url)

A user php file for Title and another for Description is very useful here so that title content can be modified.

Example - this is fairly common from a WordPress feed: (Category:Title)
"Wonderful Show: Wonderful Show #12 How to save the world.."
Ability for user's dev to str_replace() to: 
"Wonderful Show #12 How to save the world.."
And similarly for description: Ability to remove such things as 'Love and Kisses' signing blocks.[](url)

We have this working here already.

----
The above issue is now covered in #431, the individual comments will be updated once we have individual issues for them.

**Comment by Robby262** [comment]
Podcast Auto-Cull option
For speech based pod-driven stations like this: http://www.deprogrammedradio.com/ or stations that broadcast whole music shows as a single mp3 file, it would be very useful (but not essential) to have a 'wipe all tracks older than x' option.
Why? Because ephemeral items like 'daily news hour' & 'Latest Top 40' can easily fill VPS storage for no good purpose.

**Comment by Robby262** [comment]
Auto create chain of things or a new 'Podcast' block.
As per Robbt's various suggestions - with a tweak or two from me:
Auto create the following ALL WITH THE SAME NAME AS THE PODCAST FEED TITLE upon adding a new Podcast Feed:
1/ Dynamic Smartblock  'a la Robbt' selecting the latest podcast item from feed.
2/ Playlist containing the above Dynamic Smartblock suitable for adding to a show 'Autoplaylist'.

Why? Noob Friendly and consistent, Only one thing to add to a show from an added Pod Feed.

**Comment by Robbt** [comment]
I think this list is actually fairly useful stating point for improving the Podcast functionality, even if Robby Walsh decided to leave github for some reason.

**Comment by Robbt** [comment]
I have implemented the automatic creation of smartblock and playlist option for Podcasts with #278

**Comment by hairmare** [comment]
I added a note that we are covering the initial item here in #431. I guess we should close this once we have  an issue or pull request for auto-culling as per https://github.com/LibreTime/libretime/issues/222#issuecomment-306652180.
