### ISSUE TITLE
Systemd ProtectHome security feature might be to restrictive

### ISSUE THREAD

**Issue by jooola** [libretime/libretime#2242]
### Describe the bug

Based on: https://discourse.libretime.org/t/import-failed-permission-denied-whatever-the-file-is/1338/13

The `ProtectHome=true` feature in the systemd service might restrict too much users that might want to put there storage into `/home/libretime`.

### To reproduce

1. Install LibreTime with a storage in /home
2. Upload a file
3. Import fails with permission error

### Expected behavior

The /home dir should be usable by the libretime services.

### LibreTime version

3.0.0

### Installation method and OS / Environment

Operating system: Ubuntu 20.04.5 (Focal)
Method: Installer script

**Comment by jooola** [comment]
@paddatrapper Should we simply remove this feature ?

**Comment by paddatrapper** [comment]
Yeah, probably
