### ISSUE TITLE
Replay Gain doesn't work on tracks without id3 tags

### ISSUE THREAD

**Issue by aresstokrat** [LibreTime/libretime#225]
Alpha 1 + raspbian jessie
Due to different mastering 50% of imported tracks to the library has different volume lvls. During the listening i have to make radio volume in the player up and down. 
Replay Gain is turned on in the settings.

It's not working?

**Comment by hairmare** [comment]
I think it works on x86, at least you seem to be the first one to notice that replaygain isn't working. 

Can you check the results of running the replaygain command directly on a file and let us know if anything shows up in analyzer's output if you upload while using the `systemctl stop airtime-analyzer; sudo -u www-data airtime_analyzer` hack?

**Comment by aresstokrat** [comment]
what options run replaygain with?
its working , at least i can run it without options

```
$ replaygain --version
replaygain 1.3.3

```

**Comment by Robbt** [comment]
It would be nice if we had some kind of metadata edit when replaygain has been ran. 
I tried replaygain --version and I got this error
```
Traceback (most recent call last):
  File "/usr/bin/replaygain", line 4, in <module>
    __import__('pkg_resources').run_script('rgain==1.3.4', 'replaygain')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 738, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1506, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/rgain-1.3.4-py2.7.egg/EGG-INFO/scripts/replaygain", line 4, in <module>
    __import__('pkg_resources').run_script('rgain==1.3.4', 'replaygain')
  File "build/bdist.linux-x86_64/egg/rgain/script/__init__.py", line 24, in <module>
  File "/usr/lib/python2.7/dist-packages/gi/__init__.py", line 79, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gst not available

```
So evidently my replaygain is not working and I need to resolve this as some MP3s a

**Comment by hairmare** [comment]
I think the `Namespace Gst not available ` is due to a missing `python-gst-*` package (`python-gst-1,0` or maybe 2.0).

I'll do some digging and figure out how exactly replaygain is getting called to help debug thism but haven't got to it yet.

**Comment by matejb123** [comment]
Just found out replaygain is not working if there are no ID3 tags present in the file. So replaygain tag doesn't get written and there is no warning about it. There should at least be some warning that replaygain processing hasn't been done.

**Comment by maydo** [comment]
> 
> 
> Just found out replaygain is not working if there are no ID3 tags present in the file. So replaygain tag doesn't get written and there is no warning about it. There should at least be some warning that replaygain processing hasn't been done.

i can confirm this.
is there any fix or workaround for this ?

if you run replaygain on console
ID3NoHeaderError: u'yourfile' doesn't start with an ID3 tag

**Comment by jooola** [comment]
Replaygain probing and computing is now handled by ffmpeg.
