### ISSUE TITLE
External Podcasts are limited to 49

### ISSUE THREAD

**Issue by Robbt** [LibreTime/libretime#228]
I was trying to add a podcast and it says Podcast limit reached. Will diagnose and fix.

**Comment by hairmare** [comment]
Probably due to the check in [`Application_Service_PodcastService::PodcastLimitReached()`](https://github.com/LibreTime/libretime/blob/dea59558a2047ab21e14278ed7a85e85317614a9/airtime_mvc/application/services/PodcastService.php#L28-L35). Maybe this should depend on `LIBRETIME_ENABLE_BILLING` to trigger (or not be a thing at all).

**Comment by Robby262** [comment]
Good call. That might explain some stuff on my 'snag list'

**Comment by Robbt** [comment]
It is hardcoded as an exception. PodcastLimitReachedException in the rest podcast controller.

See airtime_mvc/application/services/PodcastService.php
PodcastLimitReachedException
 -  21     /**
 22      * There is maximum of 50 podcasts allowed in the library - to limit
 23      * resource consumption. This function returns true if the podcast
 24      * limit has been reached.
 25      *
 26      * @return bool
 27      */
 28     public static function PodcastLimitReached()
 29     {
 30         if (PodcastQuery::create()->count() >= 50) {
 31             return true;
 32         } else {
 33             return false;
 34         }
 35     }
 36 

The question is do we fix this by making it a user configurable variable ? 
For my immediate purposes the simple fix is just upping the number but this seems like a rather arbitrary number to stick our users with.

**Comment by Robby262** [comment]
I already had upped that to 64. But now I seem to get stuff failing in the upload window and the some pods are not downloading, Is there another setting somewhere that needs to match? The cpu is is NOT overloaded at all.

**Comment by Robbt** [comment]
No I don't think so. I'd check the /var/log/airtime/airtime-celery.log and see if it has anything in regards to the failures etc. I haven't noticed any failures on my part after I upgraded the timeout for the celery worker. There is definitely some room for improvement in terms of how it keeps track of failed downloads though.

**Comment by Robbt** [comment]
Yeah it might make sense to take it out all together there is no reason for us to impose artificial resource boundaries on our users when this isn't SAAS, but if we made it depend upon LIBRETIME_ENABLE_BILLING then that will allow us to push it under the rug and someone can benefit from it if they decide to provide LibreTime in a fashion where they need to impose resource limits on their users.

**Comment by Robby262** [comment]
If a download fails, it reports the error but the import of that file continues but complains as it has no file to work on and then fails. Surely, on a failed download, it should abort the import of that item, tell you what failed, and then continue with the rest of the podcast list?
