### ISSUE TITLE
Docs on how to configure SSL specifically for Docker installation

### ISSUE THREAD

**Issue by oscargws** [libretime/libretime#2329]
### Is your feature request related to a problem?

Hey team, I'm having trouble configuring HTTPS for my stream when using the `docker-compose` approach.

### Describe the solution you'd like

It would be fantastic to have some basic instructions to follow, tailored to `docker-compose` installations, on how to configure my SSL certs for not only the web app, but for the icecast stream as well

**Comment by oscargws** [comment]
@jooola @paddatrapper, not sure if the Docker feature development has reached support for `https` yet. Apologies if this is still on the roadmap.

**Comment by paddatrapper** [comment]
It is the same, just your web server (e.g. nginx) needs to proxy to the port on the host where libretime-legacy is running. E.g. `localhost:8080` if it is on the same server

**Comment by paddatrapper** [comment]
Icecast does not support being reverse proxied. See the Danger block on https://libretime.org/docs/admin-manual/setup/reverse-proxy/

**Comment by paddatrapper** [comment]
```
server {
    listen 80;
    server_name radio.example.com;
    location / {
        rewrite ^ https://$server_name$request_uri? permanent;
    }
}

server {
    listen 443 ssl;
    server_name radio.example.com;

    ssl_certificate /etc/letsencrypt/live/radio.example.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/radio.example.com/privkey.pem;

    location / {
        proxy_set_header Host                          $host;
        proxy_set_header X-Real-IP                  $remote_addr;
        proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host  $host;
        proxy_set_header X-Forwarded-Port  $server_port;

        proxy_pass http://localhost:8080/;
    }
}
```

**Comment by oscargws** [comment]
@paddatrapper that's the current `libretime.conf` I'm using, and it's successfully allowing Libretime to be accessed via HTTPS, but if I try to access the icecast stream it only allows http. Is there an additional step I need to do to enable HTTPS for icecast?

**Comment by paddatrapper** [comment]
See https://libretime.org/docs/admin-manual/setup/reverse-proxy/#icecast

**Comment by paddatrapper** [comment]
That configuration file is probably not configurable in the ways required to get SSL working in Docker though

**Comment by jooola** [comment]
Here is maybe a similar discussion https://discourse.libretime.org/t/api-is-unreachable-behind-nginx
