### ISSUE TITLE
Logs don't rotate

### ISSUE THREAD

**Issue by Robbt** [LibreTime/libretime#233]
At least on Ubuntu 14.04 the various /var/log/airtime logs don't rotate and thus we end up with files that continue to grow rather than truncated .1 and .2 or zipped files. This could be an issue over time and is probably something we should resolve.

**Comment by Robbt** [comment]
So the logrotate.d has entries for airtime-liquidsoap and airtime-php. And there is an entry in cron.daily for logrotate but I'm not sure this is working. It is possible that my production box that I upgraded just needed these entries set-up.

Also since we enabled logging for airtime-analyzer and airtime-playout we will also need to add logrotate.d entries for them.

**Comment by paddatrapper** [comment]
Fixed in #987
