### ISSUE TITLE
Move forked php dependencies to the libretime org

### ISSUE THREAD

**Issue by jooola** [libretime/libretime#2346]
### Is your feature request related to a problem?

A few php libraries that LibreTime is depending on are currently under my username namespace on Github.

While I don't plan to delete them as it would break a lot of things, I think it's better to move them under the LibreTime organization.

 

### Describe the solution you'd like

@paddatrapper What do you think is cleaner:
- fork under the Libretime org
- transfer them, as Github will probably automatically redirect composer to the new repository path

### Additional context

https://github.com/jooola/propel1
https://github.com/jooola/celery-php

**Comment by paddatrapper** [comment]
Probably transfer and maybe fork to your namespace to be safe?

**Comment by jooola** [comment]
> Probably transfer and maybe fork to your namespace to be safe?

Hmm, I think if I fork again it will break the redirection. Maybe we should try this out with a fake repo.

**Comment by paddatrapper** [comment]
If the redirect works, then that is probably best

**Comment by jooola** [comment]
I have tested using this project https://github.com/jooola/test-composer-transfer

So, without breaking compatibility:
- we cannot rename the composer package name to match the new Github namespace,
- but we can change the project GitHub namespace.

Now I wonder if keeping the name will make this confusing.

**Comment by paddatrapper** [comment]
Is there a way to work out how many things depend on those libraries?

**Comment by jooola** [comment]
> Is there a way to work out how many things depend on those libraries?

Not sure to understand. Do you mean phase the libraries out of the project ?

The php celery library should be removed by #1972.
The propel2 library is here to stay, until we drop the php code.

Another idea is to vendor them inside the project.

**Comment by jooola** [comment]
Ah, nobody should use the libraries in my namespace, I haven't published anything. If someone relies on them, they shouldn't expect stability.

**Comment by jooola** [comment]
I would say, the safest (less magic) would be to:
- fork the repositories,
- change the packages names to match the namespace,
- update libretime to use the new namespace
- keep the old repositories around until we consider we can break the legacy install process

**Comment by paddatrapper** [comment]
Yeah, that sounds good. Do we want to fork via the Github UI and have the forked from line linking to the ones in your namespace or hard fork and create new repos?

**Comment by paddatrapper** [comment]
I've forked both into the libretime namespace
