### ISSUE TITLE
[Question] Mobile app for listening to a Libretime radio

### ISSUE THREAD

**Issue by andresmrm** [LibreTime/libretime#235]
Hello!

A friend of mine will launch a web radio using Libretime and she asked me about the possibility of a mobile app (probably Android) to listen to the radio. Some people prefer an app to a browser on mobile...

Is there something like that? Maybe a generic app for web radios that supports Libretime?

Thanks for the attention

**Comment by Robbt** [comment]
There is nothing official as of now. There are a couple of barebone radio apps listed on Github that should work with the stream provided by Libretime. Perhaps you would like to try one and then document the process in our documentation. Here is one I found while googling android radio app github - https://github.com/y20k/transistor

Here's one I found substituting ios for android that looks promising. https://github.com/swiftcodex/Swift-Radio-Pro

If you don't have time to document them you could give them a test and just add comments here as to how they worked out for you or if you found a better option.

Hope that is helpful.

**Comment by Robby262** [comment]
There are even quite a few (advert supported) free app services that work perfectly. They basically get the data from icecast/shoutcast and don't care whether it is Libretime or not. They appear in Apple, Android and Blackberry App Stores. Here is the one I use. [](https://www.nobexpartners.com/) This one only supports MP3 and AAC

**Comment by hairmare** [comment]
There is also a list of players supported by icecast on [their page](http://icecast.org/apps/#players). Once you configure your icecast's [YP support](http://icecast.org/docs/icecast-2.4.1/yp.html) some of these apps find the station automatically.

LibreTime also has native integration with [tunein](http://tunein.com/) but it's unclear if that still works (#189). We get support questions from listeners using tunein regularly even though we never used the api at my station. Tunein has apps for all relevant platforms. Registration is free but it's probably also ad supported like other free apps.

Specifically on Android, I've used [this](https://play.google.com/store/apps/details?id=com.voody.icecast.player) before. It doesn't have ads and looks rather basic. It worked fine in my tests. It's code is [on GitHub](https://github.com/assen-totin/android-icecast-player).

**Comment by Robby262** [comment]
Our own Tunein cron job does work - the built in Libretime's one does not.

**Comment by andresmrm** [comment]
Thanks for the quick replies!

I'll check the apps with my friend and reply here later.

**Comment by Tucker2015** [comment]
Get Apps for IOS and Android from Nobex Radio

http://nobexradio.com

**Comment by Robby262** [comment]
Nobex is ok but i get more listeners on the TuneIn App
