### ISSUE TITLE
Streaming Additional Options are not editable via web UI and thus not user configurable when default streaming selected

### ISSUE THREAD

**Issue by Robbt** [libretime/libretime#236]
The additional options aspect of the Streams are currently not editable or user configurable. These were hardcoded in the SAAS provider but should have good default secure password see  #86  
This makes the streaming analytics package inaccessible because it depends upon the admin password being entered in here.

Proposed Solution:
Modify the HTML & Javascript and form processing code to make this work and ensure that it updates the Icecast configuration.

**Comment by Robby262** [comment]
Odd, mine seems to be working. I will recheck/

**Comment by Robbt** [comment]
Ok, I just realized this is only the case when default streaming is selected.
I think if anything we should at least work to get these filled in by default by coordinating the set-up of the icecast file because otherwise we are exposing people who set-up a new install to a security hole in terms of icecast password etc.

**Comment by dosmanak** [comment]
It is really unclear. Because the not default option says  / 3rd Party Streaming so I thought it is meant to change the server settings. Perhaps some tooltip above disabled fields could help.

**Comment by Robbt** [comment]
This could definitely use some clarification. Feel free to make suggestions via mock-up or if you are brave via PR.

**Comment by hairmare** [comment]
I'll just add that it's this switch that should probably change for the UX to be simpler here.

![image](https://user-images.githubusercontent.com/116588/51826849-56786a80-22e8-11e9-90a9-76232cfe2342.png)

I think it was built this way for SaaS and I believe we should probably just migrate everyone to "3rd Party" in a release where we remove the confusing "Streaming Server" item.

**Comment by jooola** [comment]
Related to #1986
