### ISSUE TITLE
Help! Cant login anymore

### ISSUE THREAD

**Issue by Robby262** [LibreTime/libretime#239]
The station is playing ok.
I did some updates and upgrades and now I can't login anymore.
I also installed letsencrypt ssl cert. Logging in just returns me to the Radio front page and I can see no errors in any logs that even slightly relate. I reset the password - same.
Ran out of ideas.
It kinda looks like an .htaccess type issue but there is not one.

**Comment by Robbt** [comment]
Sounds like an issue with SSL not being properly configured. Did you somehow disable port 80 and standard http during the process ?

**Comment by Robby262** [comment]
Thanks @Robbt . Indeed SSL is the culpit. Nice little note in cerbot log saying that it didn't like some rules in the airtime.conf and so it was not going to use them.
I had installed using strict (force everything to ssl) and that did not work.
I reconfigured with 'easy' and that does 'work-ish' but it will not redirect from http to https automatically, but it works if i type in the direct https login url.
This seems to apply, but I do not have time right now to try it:
[https://community.letsencrypt.org/t/cant-get-redirection-to-https-working-after-setup-with-certbot/25383/4](https://community.letsencrypt.org/t/cant-get-redirection-to-https-working-after-setup-with-certbot/25383/4)

**Comment by hairmare** [comment]
I safe bet is probably to install the letsencrypt cert before installing LibreTime. If you already have installed LibreTime, you could use the `webroot` plugin for certbot and point it to the `public/` dir of your mvc install.

I'm closing this since we are already tracking the basics of this in #88
