### ISSUE TITLE
Problem: Installer is broken due to missing soundcloud, env and rabbitmq settings

### ISSUE THREAD

**Issue by hairmare** [LibreTime/libretime#24]
This was introduced by #14 and needs to be fixed. I looks like it needs a multi pronged fix since there are two main failures.

1. missing soundcloud config
2. no support for env subdir in conf dir
3. setup does not create `cloud_storage.conf` and leaves `rabbitmq-analyzer.ini` empty

Workaround from https://github.com/LibreTime/libretime/pull/14#issuecomment-283634730

```bash
# after completing setup (ie no error from rabbitmq, but it hangs in the end)
#sudo bash -c 'echo soundcloud_client_id = 0 >> /etc/airtime/airtime.conf'
#sudo bash -c 'echo soundcloud_client_secret = 0 >> /etc/airtime/airtime.conf'
#sudo bash -c 'echo soundcloud_redirect_uri = http://example.org >> /etc/airtime/airtime.conf'

# sudo ln -s /etc/airtime /etc/airtime/production
#sudo cp ./airtime_mvc/tests/conf/testing/cloud_storage.conf /etc/airtime/

# do these before running sudo commands in the last setup step!
sudo bash -c 'cat > /etc/airtime/rabbitmq-analyzer.ini <<EOD
[rabbitmq]
host = 127.0.0.1
port = 5672
user = airtime
password = airtime
vhost = /airtime
EOD'

# start icecast
sudo sed -i -e 's/ENABLE=false/ENABLE=true/' /etc/default/icecast2
sudo service icecast2 start

# reload page and you should be on the default radio page
```
Solution: Add soundcloud_* defaults to config file during initial generation and make `/etc/airtime/<env>/` installer location sane.

* [x] add soundcloud to default config #25 
* [x] make default production env and symlink it to conf dir in setup (so we catch all python things as well)
* [x] add a quick and dirty `cloud_storage.conf` install to the setup script
* [ ] figure out why `rabbitmq-analyzer.ini` is empty and fix that
* [x] use upgraded setuptools #32 #33 

We can refactor it to fall back on `LIBRETIME_CONF_DIR/*.conf` if `LIBRETIME_CONF_DIR/ENVIRONMENT/*.conf` is missing later, I need to read up on how to best do that in python.

Do we want to have nice setup steps for the soundcloud and cloud storage steps? Is anyone currently not using a `file` backend in `cloud_storage.conf` that can share an S3 example?

**Comment by Robbt** [comment]
In regards to the S3 example, I don't believe there is one. This is one of the issues I ran into originally when building from the saas-dev branch.  There no example cloud_storage.conf and so we will need to reverse-engineer it if we want S3 functionality.

**Comment by hairmare** [comment]
The PHP parts should be breeze, I'm not sure if there are any direct S3 connections from python.

**Comment by Robbt** [comment]
The rabbitmq.ini files is created the web interface setup airtime_mvc/public/setup/rabbitmq-setup.php but the actual values entered in are added to airtime.conf so I'm not sure if they are needed by the airtime_analyzer python app or not. Either way the issue appears to be with the call to _write, either it isn't happening or it isn't writing the configuration properly to the rabbit-mq.ini file. This is a function defined in the Setup class in setup-functions.php and it appears to work for writing airtime.conf. So I'm not sure what is causing it to write a blank file for rabbitmq.ini

**Comment by Robbt** [comment]
Also in regards to my recent commit I ended up creating a production directory in the install script, should we instead simply make a symlink for production to point to it to its parent /etc/airtime ? Or do we want a separate production directory. Originally this was part of the /etc/airtime-saas/production but we stripped that out. I think only the python apps are using it.

**Comment by hairmare** [comment]
I was planning on refactoring the Config class in PHP so it reads from the $ENVIRONMENT specific folder if that is available and falls back to the global folder (at an item level!). I'm waiting to do this until I have complete grasp at how all the python parts handle their configs. The idea would be to implement something that works the same on both sides.

The symlink is more of a crutch for local installs since parts of the code use `/etc/airtime/airtime.conf` directly and others go for `/etc/airtime/${ENVIRONMENT}/airtime.conf`. 

It might also be a hacky temp fix to get 3.0.0-alpha tagged with a working installer.

**Comment by Robbt** [comment]
Yeah I agree. I agree we should get a working alpha with the installer. My last PR fixes the symlink and cloud_storage.conf issue. Once those are accepted we just need to figure out why the rabbit-mq setup script is failing to write to the ini file properly.

**Comment by Robbt** [comment]
So I tested my original tar.gz script and it also created a blank rabbit-mq.ini file, so the issue most likely isn't something we introduced. I need to setup a step-by-step debug but I haven't set-up that environment yet. If I get around to it I'll try to write up documentation, unless you already have xdebug connected to an IDE and can share some pointers.

**Comment by hairmare** [comment]
I have xdebug, but no proper way to step through the code, I'll have to jiggle my `vim` config a bit for that.

I'm pretty sure that it's already missing in [`moveRmqConfig`](https://github.com/sebastianbergmann/dbunit/blob/f2f8bec1d6ad7ad0bcdb47c1ed56d9d42d3e39ab/src/DataSet/XmlDataSet.php#L67) on the final setup page. Something must be wrong with the [`RabbitMQSetup`](https://github.com/LibreTime/libretime/blob/bd7091ae59bc40ac866d7ca3162f06d29e011c2e/airtime_mvc/public/setup/rabbitmq-setup.php) class. The corresponding [form](https://github.com/LibreTime/libretime/blob/bd7091ae59bc40ac866d7ca3162f06d29e011c2e/airtime_mvc/build/airtime-setup/forms/rabbitmq-settings.php) looks ok as well.

All I found in the actual writing method is a [sad workaround](https://github.com/LibreTime/libretime/blob/bd7091ae59bc40ac866d7ca3162f06d29e011c2e/airtime_mvc/public/setup/setup-functions.php#L58-L62) that doesn't quite explain our issues. The whole `_write` method looks like it could use some serious refactoring, I don't trust the state-machine used to redo the file there a bit. Surely a lib exists that can help us there.

**Comment by hairmare** [comment]
Empty `/etc/airtime/rabbitmq-analyzer.ini` is not only on Ubuntu but on Debian as well, I'm prepared to leave this as a known issue when it comes to releasing v3.0.0-alpha. We can add the fix from above to the release documents and fix it later once we figure it out.

**Comment by Robbt** [comment]
I figured it out. Preparing commit right now. Basically we need the Rabbitmq.ini file in the build directory to serve as a template. The _write function simply reads through the config file and then replaces the values with values from the web interface. Currently the rabbitmq.ini file is missing from the build so it had nothing to read/write from and thus it was producing an empty file.
