### ISSUE TITLE
mp3 files already in media source dont show up/ system tab not visible

### ISSUE THREAD

**Issue by Dorifer** [LibreTime/libretime#240]
Installed libretime on a debian jessie machine. In the Installation I defined an separate disk meant for media files (/media/stuff in my case) a already downloaded several podcasts in this directory but they don't show up in the "tracks" tab. I wanted to check the media Folder like explained in the documentation but for some reason the "system" entry doesn't show up in my installation.

I'm not sure is these two problems are related, do you need any additional information about my installation?

thx in advance

**Comment by Robbt** [comment]
They need to be imported. There currently isn't a provision to read files in a directory and import them. They currently are only importable via the web UI. There is a work in progress #111 that should do this. I haven't tested it to know whether it is working at this point or not.

**Comment by hairmare** [comment]
As per my last tests #111 isn't lacking much. @HaJoHe did a great job! 

Most of what is still mysterious is in the config reading parts (which are quite hacky anyhow (I'm currently learning python to a degree where I'll have an idea how to solve that)). 

For some weird reason there is also a problem in #111 with the php parts not sending the needed amqp messages. I'll have to try and reproduce those with a working xdebug setup to figure out what's really wrong.

**Comment by Robbt** [comment]
This isn't a bug but an expectation of media import which is dependent upon #111 being completed. So I'm going to close it for now.
