### ISSUE TITLE
Login problem with Safari and Chrome

### ISSUE THREAD

**Issue by xabispacebiker** [LibreTime/libretime#243]
I can loggin only with Firefox.

Safari Versión 10.1.1 (12603.2.4)
Google Chrome Versión 59.0.3071.115 (Build oficial) (64 bits)

![airtime_login_problem](https://user-images.githubusercontent.com/1733884/28230869-d71184c6-68e8-11e7-9be9-1ab06e210b6c.jpg)

**Comment by hairmare** [comment]
I use Chrome on a Mac most of the time. The sad tape error is usually something server side. Is there anything in `/var/log/airtime/zendphp.log`? 

Maybe localStorage or or the session have something wrong in them. Does it work if you use a private tab (<kbd>Cmd + Shift + N</kbd> in Chrome on a Mac)?

**Comment by xabispacebiker** [comment]
This is the zendphp.log when I try to login:

#6 /usr/share/airtime/php/airtime_mvc/application/airtime-boot.php(84): Zend_Application->run()
#7 /usr/share/airtime/php/airtime_mvc/public/index.php(68): require_once('/usr/share/airt...')
#8 {main}
2017-07-15T11:11:46+01:00 WARN (4): airtime.97irratia.info SQLSTATE[55P03]: Lock not available: 7 ERROR:  could not obtain lock on row in relation "cc_pref"
2017-07-15T11:11:46+01:00 WARN (4): airtime.97irratia.info SQLSTATE[55P03]: Lock not available: 7 ERROR:  could not obtain lock on row in relation "cc_pref"
2017-07-15T11:11:50+01:00 WARN (4): airtime.97irratia.info Your system does not have the es_ES.UTF-8 locale installed. Run: sudo locale-gen es_ES.UTF-8
2017-07-15T11:11:55+01:00 WARN (4): airtime.97irratia.info Your system does not have the es_ES.UTF-8 locale installed. Run: sudo locale-gen es_ES.UTF-8
2017-07-15T11:12:00+01:00 WARN (4): airtime.97irratia.info Your system does not have the es_ES.UTF-8 locale installed. Run: sudo locale-gen es_ES.UTF-8
2017-07-15T11:12:05+01:00 INFO (6): airtime.97irratia.info Checking autoplaylist poll
2017-07-15T11:12:05+01:00 WARN (4): airtime.97irratia.info Your system does not have the es_ES.UTF-8 locale installed. Run: sudo locale-gen es_ES.UTF-8
2017-07-15T11:12:10+01:00 WARN (4): airtime.97irratia.info Your system does not have the es_ES.UTF-8 locale installed. Run: sudo locale-gen es_ES.UTF-8
2017-07-15T11:12:12+01:00 WARN (4): airtime.97irratia.info Your system does not have the es_ES.UTF-8 locale installed. Run: sudo locale-gen es_ES.UTF-8
2017-07-15T11:12:12+01:00 NOTICE (5): Trying to get property of non-object
2017-07-15T11:12:12+01:00 ERR (3): airtime.97irratia.info [ErrorController.php:26 - errorAction()] - Forbidden
2017-07-15T11:12:12+01:00 ERR (3): airtime.97irratia.info [ErrorController.php:27 - errorAction()] - #0 /usr/share/airtime/php/airtime_mvc/application/controllers/LoginController.php(27): CORSHelper::enableCrossOriginRequests(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#1 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(516): LoginController->indexAction()
#2 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('indexAction')
#3 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#4 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#5 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#6 /usr/share/airtime/php/airtime_mvc/application/airtime-boot.php(84): Zend_Application->run()
#7 /usr/share/airtime/php/airtime_mvc/public/index.php(68): require_once('/usr/share/airt...')
#8 {main}
2017-07-15T11:12:12+01:00 ERR (3): airtime.97irratia.info [ErrorController.php:54 - errorAction()] - An internal application error has occurred.: exception 'Zend_Controller_Action_Exception' with message 'Forbidden' in /usr/share/airtime/php/airtime_mvc/application/common/CORSHelper.php:14
Stack trace:
#0 /usr/share/airtime/php/airtime_mvc/application/controllers/LoginController.php(27): CORSHelper::enableCrossOriginRequests(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#1 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(516): LoginController->indexAction()
#2 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('indexAction')
#3 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#4 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#5 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#6 /usr/share/airtime/php/airtime_mvc/application/airtime-boot.php(84): Zend_Application->run()
#7 /usr/share/airtime/php/airtime_mvc/public/index.php(68): require_once('/usr/share/airt...')
#8 {main}

**Comment by hairmare** [comment]
This seems to be the CORS check acting up in some way. The `Forbidden` seems to be [this one](https://github.com/LibreTime/libretime/blob/6e2cb2b2a80442f5a5aa9e181649393bdabd6ea7/airtime_mvc/application/common/CORSHelper.php#L14). I'm not sure why it's failing, are you using a non-standard port?

**Comment by xabispacebiker** [comment]
I am using port 8080.

**Comment by xabispacebiker** [comment]
The problem here is that $request->getHeader('Origin') returns the server's name with port, and the function getAllowedOrigins is returning the server name without the port, so the IF condition  in line 11 `!in_array($origin, self::getAllowedOrigins()` will always be true throwing the zend controller exception.

inside the IF at public static function enableCrossOriginRequests:
`die (var_dump($origin, self::getAllowedOrigins()));`

`string(34) "http://airtime.97irratia.info:8080" array(3) { [0]=> string(0) "" [1]=> string(29) "http://airtime.97irratia.info" [2]=> string(30) "https://airtime.97irratia.info" }`

This change would make it:

Line 9 at airtime_mvc/application/common/CORSHelper.php
$origin = preg_replace('/:[0-9]+/', '', $request->getHeader('Origin'));

**Comment by hairmare** [comment]
The port could also be added to [CORSHelper.php#L29-L30](https://github.com/LibreTime/libretime/blob/6e2cb2b2a80442f5a5aa9e181649393bdabd6ea7/airtime_mvc/application/common/CORSHelper.php#L29-L30) if it's not default. I'm preparing a PR for that.

I finally realized why this problem isn't showing up locally, I was always using localhost to test and localhost has less strict CORS requirements in Webkit based browsers.

Did you see that you can also add additional CORS URLs once you're logged in (in "Settings" » "General"). You can use those if you need to support multiple hostnames or ports for the same instance.

**Comment by xabispacebiker** [comment]
I would suggest that if $origin does not really need the port we should remove it with preg_replace. It will avoid  errors in the future.

**Comment by hairmare** [comment]
Thanks for persisting and debugging, I pushed a fix that should work in #250.

I didn't change `$origin` since it's the actual value we are validating (what the client is sending). IMHO changing the value kind of goes against the spirit of validation.

**Comment by xabispacebiker** [comment]
Same happens with the updated fix. This is a new installation in a different server with the latest changes:

`die (var_dump($origin, self::getAllowedOrigins()));`

`string(31) "https://airtime.sonicbunker.com" array(2) { [0]=> string(0) "" [1]=> string(30) "http://airtime.sonicbunker.com" }`

This url uses https.

**Comment by paddatrapper** [comment]
I'm currently getting this running the latest git commit. Firefox login works fine, while Chrome does not. Tested on Windows and Debian. The LT server is running in a LXC container with web-traffic proxied through another container on the same host running Nginx.

````
2017-11-13T22:15:15+02:00` ERR (3): libretime.example.com [ErrorController.php:26 - errorAction()] - Forbidden
2017-11-13T22:15:15+02:00 ERR (3): libretime.example.com [ErrorController.php:27 - errorAction()] - #0 /usr/share/airtime/php/airtime_mvc/application/controllers/LoginController.php(27): CORSHelper::enableCrossOriginRequests(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#1 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(516): LoginController->indexAction()
#2 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('indexAction')
#3 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#4 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#5 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#6 /usr/share/airtime/php/airtime_mvc/application/airtime-boot.php(84): Zend_Application->run()
#7 /usr/share/airtime/php/airtime_mvc/public/index.php(68): require_once('/usr/share/airt...')
#8 {main}
2017-11-13T22:15:15+02:00 ERR (3): libretime.paddatrapper.me [ErrorController.php:54 - errorAction()] - An internal application error has occurred.: Zend_Controller_Action_Exception: Forbidden in /usr/share/airtime/php/airtime_mvc/application/common/CORSHelper.php:15
Stack trace:
#0 /usr/share/airtime/php/airtime_mvc/application/controllers/LoginController.php(27): CORSHelper::enableCrossOriginRequests(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#1 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(516): LoginController->indexAction()
#2 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('indexAction')
#3 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#4 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#5 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#6 /usr/share/airtime/php/airtime_mvc/application/airtime-boot.php(84): Zend_Application->run()
#7 /usr/share/airtime/php/airtime_mvc/public/index.php(68): require_once('/usr/share/airt...')
#8 {main}
````

**Comment by hairmare** [comment]
@paddatrapper I'm assume your LibreTime instance is on a non standard port and the nginx-proxy is on the port 80 or 443. 

You can either use 80 or 433 in airtime.conf and have all LibreTime traffic go through the proxy or you can add the actual URL you are using in your browser to the CORS URL list in "Settings" » "General".

**Comment by paddatrapper** [comment]
This is where things get fun. So local access (from within the LT container) is through apache on localhost:80, however external access is run through the proxy (port 443 on the external domain with 80 redirecting to 443, as SSL negotiation takes place at the proxy level). The external domain gets resolved to localhost in the LT container and cannot run through the proxy thanks to LXC and iptables shenanigans. The proxy is another LXC container on the same host.

I have `airtime.conf` using `base_url: libretime.example.com` (as an example, the actual domain is set up and working) and `base_port: 80`, as these will allow LT to access the API from within the container. Apache is running on the standard port 80 in the container. I have also added 
````
libretime.example.com
localhost
````
to the CORS URL list, with no success...

**Comment by hairmare** [comment]
I think you have to add the protocol to the URLs in the list for it to work, CORS can be protocol sensitive.

**Comment by paddatrapper** [comment]
Tried with 
````
http://libretime.example.com
http://localhost
````
with no success. Do I need to restart any services after changing them?

**Comment by hairmare** [comment]
No need for any restarts.

Are you connecting to the proxy or the the LibreTime container?

```
https://libretime.example.com
http://libretime.example.com
http://localhost
```

**Comment by paddatrapper** [comment]
Any external connection happens via the proxy

Thanks, those worked. For anyone coming here in the future: The URL listed needs to match the external URL that the user's web browser is connecting to. In my case that was `https://libretime.example.com`

**Comment by Robbt** [comment]
It appears we merged a fix for this issue. If anyone is still having a problem feel free to re-open it.
