### ISSUE TITLE
Custom/3rd party Streaming

### ISSUE THREAD

**Issue by Sergey0892** [libretime/libretime#2445]
### Describe the bug

I haven't used libretime for a long time and now I did a clean install via the Release tarball.

I can't connect to a third-party Icecast server.

Either this is a bug in this version or there are new conditions for connecting an external server.

In version 3.0.0-alpha.12, this problem was not observed

### Expected behavior

In version 3.0.0-alpha.12, this problem was not observed

### LibreTime version

3.0.2

### Installation method and OS / Environment

Operating system: Ubuntu 20.04 lts
Method:

### Client Environment

Operating system:
Browser:

### Screenshots

![no 3rd party Streaming](https://user-images.githubusercontent.com/90310551/225350763-94482030-f6c0-42b6-b5f9-785a476b015d.png)
![There is 3rd party Streaming](https://user-images.githubusercontent.com/90310551/225350805-6aeed964-284d-4891-82c9-d309c0661431.png)

**Comment by jooola** [comment]
Please read the changelog, upgrade procedure, documentation.

**Comment by paddatrapper** [comment]
Namely https://libretime.org/docs/releases/3.0.0-beta.0/#%EF%B8%8F-before-upgrading
