### ISSUE TITLE
drf does not yet support django 4.2

### ISSUE THREAD

**Issue by jooola** [libretime/libretime#2498]
### Describe the bug

I was a bit too fast to while merging django >=4.2, drf didn't released a version that ship the latest fix to work with django 4.2.

### To reproduce

Run from the current main and see the gunicorn logs.

### Expected behavior

DRF should work with django 4.2

**Comment by paddatrapper** [comment]
Looks like we need the next DRF release - https://github.com/encode/django-rest-framework/pull/8794

**Comment by jooola** [comment]
I am tempted to install drf from the repo directly, in order to test the django 4.2 integration before they can release.

@paddatrapper Do you agree and think this isn't a bad idea ?

**Comment by paddatrapper** [comment]
Looks like they are pretty close to a release, so there shouldn't be any major bugs that we would hit. Assuming we can easily switch back to versioned releases, then I think we should install from the repo for the moment

**Comment by jooola** [comment]
According to https://github.com/encode/django-rest-framework/issues/8942 django-rest-framework 3.14 work with django 4.2.1.

DRF won't work if we have django 4.2.1 and drf <3.14, so we probably want to bump the minimal version of DRF to 3.14 and revert the installation from the main branch.
