### ISSUE TITLE
Icecast does not properly handle UTF-8

### ISSUE THREAD

**Issue by jooola** [libretime/libretime#2501]
### Describe the bug

https://discourse.libretime.org/t/icecast-charset/1451

Adding this to the icecast config solves the problem:
```xml
    <mount type="default">
       <charset>UTF-8</charset>
    </mount>
```

### To reproduce

1. Play a track that contain UTF-8 only chars
2. See the icecast status page
3. See badly displayed track metadata

### Expected behavior

The metadata should be displayed without de/encoding issues.

### LibreTime version

3.0.2

### Installation method and OS / Environment

Operating system: Debian bullseye
Method: ansible

### Client Environment

Operating system:
Browser:

**Comment by paddatrapper** [comment]
This sounds like something that should be enabled in the icecast debian package by default...

**Comment by jooola** [comment]
The only way I can think of to fix this would be to commit a default icecast config, add the required changes and copy the file in-place during the first icecast installation.

Playing with sed/ed seem like a bad idea.

**Comment by paddatrapper** [comment]
How do we handle the password change? We could do something similar. Long term, I'll file a bug against the icecast debian package to fix it there

**Comment by jooola** [comment]
The password change is easy because we replace an existing string.

Adding an entire child after a specific comment feels a bit risky. I want to add this section after the mounts default section, to prevent confusion.

**Comment by paddatrapper** [comment]
Ok. Yeah, then we probably need to ship a full config file

**Comment by paddatrapper** [comment]
Debian bug report - https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1034283
