### ISSUE TITLE
Handle PEP-668 and install LibreTime in a venv

### ISSUE THREAD

**Issue by jooola** [libretime/libretime#2507]
### Describe the bug

The introduction of https://peps.python.org/pep-0668/ in Debian Bookworm, will break our current install procedure.

This PEP will prevent the installation of pip packages globally, which we heavily rely on.

Since we will not rely on the distribution python packages, the solution is to install LibreTime inside a virtual env, either using pipx or manually.

I am unsure what is best for our use case, using venv seem more flexible, but pipx removes a decent amount of boilerplate we will have to write.

While we only have to implement this to support debian bookworm, I think we can extend this setup to all the distributions we support.

Some old discussion somewhat related about this https://github.com/libretime/libretime/issues/1207

cc @paddatrapper

### To reproduce

1. Install LibreTime on debian bookworm
2. See the pip install error

### Expected behavior

The LibreTime installer should be able to install the apps dependencies and packages.

### Relevant log output or error messages

```shell
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```

### LibreTime version

3.0.2

### Installation method and OS / Environment

Operating system: >= Debian Bookworm
Method: Ansible, installer, maybe docker

### Client Environment

Operating system:
Browser:

**Comment by paddatrapper** [comment]
Do we need the flexibility yet? We could always move to manual venvs if pipx proves to be limiting. It seems that it matches our use case exactly - have python apps and dependencies in virtual environments that can be run from a known $PATH directory

**Comment by jooola** [comment]
> Do we need the flexibility yet? We could always move to manual venvs if pipx proves to be limiting. It seems that it matches our use case exactly - have python apps and dependencies in virtual environments that can be run from a known $PATH directory

I think we need to consider the following points:
- Should we have a single venv per application ? If so pipx fits, but we will duplicate both remote and the shared/api-client dependencies. Space usage might only be an issue on cheap boards, but I am not even sure we actually support those. Setup and cleanup will take more time, as we have to setup multiple venv for each app.
- How does gunicorn behave when installed from the system packages but needs to run an app inside a venv somewhere in a hidden venv ? Using a venv is probably more straightforward when it comes to doing some kind of venv activation, while I know t is doable using pipx. Here is a commit to fix this particular setup in the ansible role: https://github.com/libretime/ansible-role-libretime/commit/14c095a61c362128558efbc4905d7c28bd54090b https://github.com/libretime/ansible-role-libretime/commit/66209cfb3bb1547583c1ce08d906a533b6a82a97 I think using the distribution gunicorn/uvicorn package ensure we have security patches at least on the "infra" side of the deployment.
- With pipx, we expose the entry points globally, so we should be ok with regards to liquidsoap calling libretime-playout-notify.

**Comment by paddatrapper** [comment]
> we don't relying on the system-site-package and install gunicorn/uvicorn from pip, which should properly isolate the new venv from outside packages.

I think is probably the cleanest solution - it also makes our various platform targets more consistent.
