### ISSUE TITLE
Recommend using a reverse proxy over editing the LibreTime nginx config

### ISSUE THREAD

**Issue by jooola** [libretime/libretime#2543]
### Is your feature request related to a problem?

I recently added a way to prevent loosing changes in the nginx config file during upgrade, for example, if someone configured the libretime nginx configuration to work with Certbot. This is handy, but I realize that this might have been a big mistake.

If we need to update the nginx configuration file, for example because we want to add a feature (#2522, #2234), we have to rely on a breaking change, because users will have to update their nginx configuration manually, or pass the `--update-nginx` flag to overwrite the config file, but lose their cerbot configuration.

We do print a diff of the nginx configuration, but maybe this isn't really user-friendly.

### Describe the solution you'd like

I think we should rather encourage users to set up a reverse proxy, and allow us to edit the nginx configuration file. Then we can introduce new features without introducing a breaking change.

We could do the following steps:
- Extend the docs and recommend to set up a reverse proxy, warn why not using a reverse proxy might be difficult to maintain.
- Deploy a nginx reverse proxy config using the installer script, with or without a feature-flag
- Install Cerbot using the installer script, with or without a feature-flag
- Change the default install port for the libretime installer to be 8080, with or without a feature-flag (e.g. when using `--with-reverse-proxy` we use port 8080, otherwise we use port 80).

### Describe alternatives you've considered

We can consider that changing the nginx configuration file is not a breaking change, but this would not be a happy path for the less experienced users around LibreTime.

**Comment by paddatrapper** [comment]
Hmm... Yes, it is probably best to tell people to use a reverse proxy in front and apply changes there.

This applies to Icecast config too - any changes to that is now a breaking change if people have configured SSL support.
