### ISSUE TITLE
[Question] Several instances of Libretime

### ISSUE THREAD

**Issue by yarik2720** [LibreTime/libretime#255]
How to properly install several instances of Libretime with vagrant?

**Comment by hairmare** [comment]
You would need to change the port mappings in `Vagrantfile` so each instance uses its own ports and you should probably call the installer in the box without the `-I` argument.

The `Vagrantfile` in the repo is optimized for setting up a local developer/tester environment so it might not be the best fit for "production" deploys.

**Comment by yarik2720** [comment]
Is there another ways to install several instances currently?

**Comment by hairmare** [comment]
You should be able to run multiple instances of LibreTime based on just one install by creating multiple vhosts and setting the `LIBRETIME_CONF_DIR` env variable for each virtualhost. 

You would also need to change `LIBRETIME_LOG_DIR`. 

They both default to the `airtime` locations [here](https://github.com/LibreTime/libretime/blob/c3bd93779b6686759aff0b888980df6471bdbc11/airtime_mvc/application/configs/constants.php#L41-L42). 

You would also need to create a separate config dir for each instance and run the python services once per instance. Each one with `LIBRETIME_CONF_DIR` and `LIBRETIME_LOG_DIR` envs matching what your virtualhosts use.

I'm not sure if everything works when installing multiple instances as I don't believe anyone has tested such a set up. Please report back if it works or any issues you run into.

If you are on a systemd based distro this should not be too hard to set up. Let us know if you need help and I'll try to write up a quick how to.

It'll probably make sense to close this issue by adding some info/examples to the docs once the feature is tested.

**Comment by yarik2720** [comment]
What about database? I thought it must be unique for each virtualhost to make individual programs for every virtualhost.
Also, can you tell how to setup correctly variables?

**Comment by hairmare** [comment]
The database server (and RabbitMQ) can be shared by the instances. You would create an individual database per instance in PostgreSQL & a vhost per instance in RabbitMQ. The LibreTime instances should also have their own user/password combos to access those.

In apache you can use [`SetEnv`](http://httpd.apache.org/docs/2.0/mod/mod_env.html#setenv) in a virtualhost to set env variables.

```apache
<VirtualHost *:80>
    # ...
    SetEnv LIBRETIME_CONF_DIR /etc/libretime/instance1
    SetEnv LIBRETIME_LOG_DIR /var/log/libretime/instance1
    # ...
</VirtualHost>
```

In nginx you can set env variables that are passed to php-fcgi with [`fastgci_param`](http://nginx.org/en/docs/http/ngx_http_fastcgi_module.html#fastcgi_param).

```
location / {
    # ...
    fastcgi_param LIBRETIME_CONF_DIR /etc/libretime/instance1
    fastcgi_param LIBRETIME_LOG_DIR /var/log/libretime/instance1
    # ...
}
```

**Comment by yarik2720** [comment]
Stucked on setup on step 4, after filling in folder I have this error:
Error moving rabbitmq-analyzer.ini or deleting /tmp/rabbitmq.ini.tmp!

**Comment by hairmare** [comment]
Most likely the step failed because $LIBRETIME_CONF_DIR doesn't contain the *env* symlink hack.

```bash
ln -s $LIBRETIME_CONF_DIR $LIBRETIME_CONF_DIR/production
```

The config structure should get easier to handle with #253 (ie. it won't need multiple files and the weird symlink once that is merged).

On larger installs your best bet might be to skip the setup wizard completely by creating all the needed configs manually before connecting to the webinterface and starting services.

**Comment by yarik2720** [comment]
Currently have no success with it, first instance set up on default paths and after that moved configs to folder /etc/airtime/instance1. Libretime started well after that. For second instance I don't know how to create new host for rabbitmq. 
Maybe there is full guide how to setup rabbitmq and postgresql for several instances?

**Comment by hairmare** [comment]
Yes, docs would be nice... We should be sure that it works before writing those though.

To set up an additional rabbitmq vhost you can run [the commands the installer uses](https://github.com/LibreTime/libretime/blob/c3bd93779b6686759aff0b888980df6471bdbc11/install#L1018-L1026) for each instance:

```bash
RABBITMQ_VHOST="instance1"
RABBITMQ_USER="instance1user"
RABBITMQ_PASSWORD="instance1password"

rabbitmqctl add_vhost "${RABBITMQ_VHOST}"
rabbitmqctl add_user "${RABBITMQ_USER}" "${RABBITMQ_PASSWORD}"
rabbitmqctl set_permissions -p "${RABBITMQ_VHOST}" "${RABBITMQ_USER}" ".\*" ".\*" ".\*"
```

**Comment by yarik2720** [comment]
I tried that method of initialising configs:
1. Complete setup wizard
2. setup env in virtualhost
3. move configs to /etc/airtime/instance1

after that I have setup wizard showing again, that stucks at step 4: Error moving rabbitmq-analyzer.ini or deleting /tmp/rabbitmq.ini.tmp!

**Comment by yarik2720** [comment]
Now I have success on two instances on ubuntu 16.04. (setting up still in progress)
This needs to
*create copy of database 
`CREATE DATABASE instance2 TEMPLATE airtime;`
*set up additional vhost
```
rabbitmqctl add_vhost /instance2
rabbitmqctl add_user instance2user instance2password
rabbitmqctl set_permissions -p /instance2 instance2user ".\*" ".\*" ".\*"
```
*after creating main instance of libretime copy generated configurations and edit them on api_key and on settings of rabbitmq and database
also need to change path of logging dirs

now have problem on settings saving, I got error:
`An internal application error has occurred.: PhpAmqpLib\Exception\AMQPProtocolChannelException: ACCESS_REFUSED - access to exchange 'airtime-pypo' in vhost '/instance2' refused for user 'instance2user' in /usr/share/airtime/php/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php:188`

**Comment by hairmare** [comment]
> Met another problem: instance 2 can't connect to liquidsoap and liquidsoap.cfg don't changes after making some configuration on Libretime, maybe I forgot to setup something in aitime.conf?

Most likely liquidsoaps telnet port needs to be changed on the second instance from the hardcoded default: https://github.com/LibreTime/libretime/blob/9739d64063a390bc5c953dc9186d0b80449f80cf/python_apps/pypo/liquidsoap/ls_script.liq#L5

We should probably make it configurable through the *usual* way through the generated `liquidsoap.cfg`.

> Also, how I can change music dir for instance 2?

The music dir is stored in the database in the table `cc_music_dirs` your best bet is  to change it directly in the second instances database.

**Comment by yarik2720** [comment]
after setting up variables for first instance as default path as in code below
```
<VirtualHost *:80>
    # ...
    SetEnv LIBRETIME_CONF_DIR /etc/airtime
    SetEnv LIBRETIME_LOG_DIR /var/log/airtime
    # ...
</VirtualHost>
```

I have in pypo.log errors:
`2017-09-18 21:14:08,534 [api_client] [INFO ]  Unable to get Airtime API version number.`
and after that main instance can't connect to liquidsoap

**Comment by hairmare** [comment]
The `SetEnv LIBRETIME_CONF_DIR` line only work for the PHP parts. You also need to set the env variable for the python parts. One possible way to do this would be using a systemd override or by copying and hacking the SysV/upstart scripts for the services. this depends on the distro you are using. Which one are you on?

**Comment by yarik2720** [comment]
Now I'm testing on Ubuntu 16.04

**Comment by hairmare** [comment]
Great, so your setup is systemd based. To support multiple instances natively we would need to switch to using systemd templates, this isn't very high on the priority list but you can work around it by duplicating an existing config and add matching `Environment=LIBRETIME_CONF_DIR=/etc/airtime` lines.
You can do something similar to the following and then hack the instance1 files. Keep in mind that the liquidsoap telnet issue still needs fixing/working around.

```
cp /etc/systemd/system/airtime-playout.service /etc/systemd/system/airtime-playout-instance1.service
cp /etc/systemd/system/airtime-liquidsoap.service /etc/systemd/system/airtime-liquidsoap-instance1.service

```

**Comment by Robbt** [comment]
This issue was moved to http://libretime.trydiscourse.com/t/question-several-instances-of-libretime/27
