### ISSUE TITLE
Track stuck in pending import

### ISSUE THREAD

**Issue by mtgaming** [LibreTime/libretime#256]
Whenever I attempt to upload at track it is stuck in pending import even though it uploads successfully to the /srv/airtime/stor folder. It never shows up in the track list and just says pending import in the upload section. 

Any indication of what I need to do/change? I'm not sure what logs to provide as what I searched around in gave no indication as to an error or anything.

**Comment by hairmare** [comment]
Most likely analyzer isn't running or the stor directory isn't set up as expected.

Do both `/src/airtime/stor/organize` and `/srv/airtime/stor/imported` exist? Which of them is the file in?

What distro are you on? Did you install from source or from a tarball? Is there anything suspicious in `/var/log/airtime/zendphp.log` or in the output of `sudo journalctl -u airtime_analyzer`?

**Comment by xabispacebiker** [comment]
Might this be related to folder permissions ?

**Comment by OliCat** [comment]
Hello,

I experimented the same issue with a fresh git install on debian jessie.
The error was an incompatibility between the version of pika since 27/07 and airtime_analyzer.

I have removed the pip package and installed the deb package. It's ok now.

**Comment by mtgaming** [comment]
`/src/airtime/stor/organize` exists and the file is in there. 

`/src/airtime/stor/imported` does not exist. 

I'm on Ubuntu 16.04.3. I installed from the github source, the latest pre-alpha. 

Nothing suspicious in `/var/log/airtime/zendphp.log`, it says the file was moved from the tmp folder and that is it. 

Running `sudo -journalctl -u airtime_analyzer` produced the following error: 

> Aug 01 20:12:19 gtavrp airtime_analyzer[9281]: Airtime Analyzer 1.0
Aug 01 20:12:19 gtavrp airtime_analyzer[9281]: Traceback (most recent call last):
Aug 01 20:12:19 gtavrp airtime_analyzer[9281]:   File "/usr/bin/airtime_analyzer", line 4, in <module>
Aug 01 20:12:19 gtavrp airtime_analyzer[9281]:     __import__('pkg_resources').run_script('airtime-analyzer==0.1', 'airtime_analyzer')
Aug 01 20:12:19 gtavrp airtime_analyzer[9281]:   File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 742, in run_script
Aug 01 20:12:19 gtavrp airtime_analyzer[9281]:     self.require(requires)[0].run_script(script_name, ns)
Aug 01 20:12:19 gtavrp airtime_analyzer[9281]:   File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1503, in run_script
Aug 01 20:12:19 gtavrp airtime_analyzer[9281]:     exec(code, namespace, namespace)
Aug 01 20:12:19 gtavrp airtime_analyzer[9281]:   File "/usr/local/lib/python2.7/dist-packages/airtime_analyzer-0.1-py2.7.egg/EGG-INFO/scripts/airtime_analyzer", line 73, in <module>
Aug 01 20:12:19 gtavrp airtime_analyzer[9281]:     run()
Aug 01 20:12:19 gtavrp airtime_analyzer[9281]:   File "/usr/local/lib/python2.7/dist-packages/airtime_analyzer-0.1-py2.7.egg/EGG-INFO/scripts/airtime_analyzer", line 51, in run
Aug 01 20:12:19 gtavrp airtime_analyzer[9281]:     debug=args.debug)
Aug 01 20:12:19 gtavrp airtime_analyzer[9281]:   File "/usr/local/lib/python2.7/dist-packages/airtime_analyzer-0.1-py2.7.egg/airtime_analyzer/airtime_analyzer.py", line 45, in __init__
Aug 01 20:12:19 gtavrp airtime_analyzer[9281]:     self._msg_listener = MessageListener(rmq_config, cloud_storage_config)
Aug 01 20:12:19 gtavrp airtime_analyzer[9281]:   File "/usr/local/lib/python2.7/dist-packages/airtime_analyzer-0.1-py2.7.egg/airtime_analyzer/message_listener.py", line 89, in __init__
Aug 01 20:12:19 gtavrp airtime_analyzer[9281]:     self.connect_to_messaging_server()
Aug 01 20:12:19 gtavrp airtime_analyzer[9281]:   File "/usr/local/lib/python2.7/dist-packages/airtime_analyzer-0.1-py2.7.egg/airtime_analyzer/message_listener.py", line 113, in connect_to_messaging_server
Aug 01 20:12:19 gtavrp airtime_analyzer[9281]:     self._channel.exchange_declare(exchange=EXCHANGE, type=EXCHANGE_TYPE, durable=True)
Aug 01 20:12:19 gtavrp airtime_analyzer[9281]: TypeError: exchange_declare() got an unexpected keyword argument 'type'

**Comment by OliCat** [comment]
Hello,

`Aug 01 20:12:19 gtavrp airtime_analyzer[9281]: self._channel.exchange_declare(exchange=EXCHANGE, type=EXCHANGE_TYPE, durable=True)
Aug 01 20:12:19 gtavrp airtime_analyzer[9281]: TypeError: exchange_declare() got an unexpected keyword argument 'type'`

It's the same exception i had.

To solve it:

- sudo pip uninstall pika

- sudo apt install python-pika

**Comment by hairmare** [comment]
@OliCat Thanks for the pointer.

It looks like [Debian](https://packages.qa.debian.org/p/python-pika.html), [Ubuntu](https://packages.ubuntu.com/search?keywords=python-pika) and [CentOS](https://centos.pkgs.org/7/epel-x86_64/python2-pika-0.10.0-9.el7.noarch.rpm.html) all install pika `0.10.0`. The pika project seems to have published a pre-release on [PyPi](https://pypi.python.org/pypi/pika) and [GitHub](https://github.com/pika/pika/releases/tag/0.11.0b1) tagged as `0.11.0b1`, for some reasons (probably due to the pikas tag convention) this pre-release is being picked up when the installer uses `pip` to get the package.

To work around this we could freeze pika in [setup.py](https://github.com/LibreTime/libretime/blob/276a69aa1bef527260efc170d7caab7d04b4ca13/python_apps/airtime_analyzer/setup.py#L31) and/or add `python-pika` to the files in [installer/lib](https://github.com/LibreTime/libretime/tree/c3bd93779b6686759aff0b888980df6471bdbc11/installer/lib) as needed. It might make more sense to just do the latter and I'm preparing a PR to that effect.

I suppose we want to update to pika `0.11.0` once there is a stable release that is also available as OS package. This might take a while since the last pika release was ages ago and the lib seems to have quite some changes.

**Comment by OliCat** [comment]
Hello,

Yes, the bad version installed is `0.11.0b1` from pip.

**Comment by Robbt** [comment]
Since we merged the python-pika change that seems to have address this I'm going to mark this closed.

**Comment by Cysioland** [comment]
Also fails for me, but with:

```
/usr/local/lib/python2.7/dist-packages/requests-2.18.4-py2.7.egg/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.22) or chardet (2.0.1) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "/usr/bin/airtime_analyzer", line 4, in <module>
    __import__('pkg_resources').run_script('airtime-analyzer==0.1', 'airtime_analyzer')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/airtime_analyzer-0.1-py2.7.egg/EGG-INFO/scripts/airtime_analyzer", line 8, in <module>
    import airtime_analyzer.airtime_analyzer as aa
  File "/usr/local/lib/python2.7/dist-packages/airtime_analyzer-0.1-py2.7.egg/airtime_analyzer/airtime_analyzer.py", line 12, in <module>
    from status_reporter import StatusReporter 
  File "/usr/local/lib/python2.7/dist-packages/airtime_analyzer-0.1-py2.7.egg/airtime_analyzer/status_reporter.py", line 1, in <module>
    import requests
  File "/usr/local/lib/python2.7/dist-packages/requests-2.18.4-py2.7.egg/requests/__init__.py", line 84, in <module>
    from urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/urllib3-1.22-py2.7.egg/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/crypto.py", line 12, in <module>
    from cryptography import x509
  File "/usr/local/lib/python2.7/dist-packages/cryptography/x509/__init__.py", line 7, in <module>
    from cryptography.x509 import certificate_transparency
  File "/usr/local/lib/python2.7/dist-packages/cryptography/x509/certificate_transparency.py", line 22, in <module>
    @six.add_metaclass(abc.ABCMeta)
AttributeError: 'module' object has no attribute 'add_metaclass'
```

**Comment by Robbt** [comment]
This appears to be an issue with the python library. What version of linux did you install this under ?
