### ISSUE TITLE
New install and migration from Airtime: database restore error

### ISSUE THREAD

**Issue by comiconomenclaturist** [libretime/libretime#2563]
### Describe the bug

I've just installed Debian 11 on a server and then installed libretime 3.0.2.
I then ran `sudo -u libretime libretime-api dbshell < airtime-backup` but I got the error:

```
2023-05-25 11:40:37.846 | CRITICAL | libretime_shared.config._base:__init__:50 - 1 validation error for Config
general -> public_url
  invalid or missing URL scheme (type=value_error.url.scheme)
```

The airtime backup is from Airtime 2.5.1 - is this supported? Any idea how I can import the database?

### To reproduce

1. Install OS
2. Install Libretime 3.0.2
3. Restore Airtime database

### Expected behavior

The database should be restored.

### Relevant log output or error messages

```shell
2023-05-25 11:40:37.846 | CRITICAL | libretime_shared.config._base:__init__:50 - 1 validation error for Config
general -> public_url
  invalid or missing URL scheme (type=value_error.url.scheme)
```

### LibreTime version

3.0.2

### Installation method and OS / Environment

Operating system: Debian 11
Method: Installer script

### Client Environment

Operating system:
Browser:

**Comment by paddatrapper** [comment]
You need to configure the public url in the configuration file. See https://libretime.org/docs/admin-manual/setup/configuration/#general

**Comment by comiconomenclaturist** [comment]
Thanks. I don't have a resolvable FQDN just yet so I tried putting in the local IP. 
I now get the error:

```
\connect: FATAL:  database "airtime" does not exist
CommandError: "psql -U libretime -h localhost -p 5432 libretime" returned non-zero exit status 2.
```

Is it possible to gert Libretime up and running without the FQDN and SSL certs for testing?

**Comment by paddatrapper** [comment]
Looks like your configuration file has different DB connection details that what the DB has. You don't need SSL certs and using localhost as the public_url initially will work. Are you following the migration guide? https://libretime.org/docs/admin-manual/setup/migrate-from-airtime/

**Comment by comiconomenclaturist** [comment]
Yes, that's the guide I've been following. I did the initial install, and no setup. The next step was just trying to restore the Airtime DB, but the new install's DB is called libretime, whereas the Airtime backup is called airtime. I guess that's the problem? What would be the best way to solve this? Rename libretime to airtime in psql and update `/etc/libretime/config.yml`?

**Comment by paddatrapper** [comment]
Once you update the config file, you need to run the DB migration script: https://libretime.org/docs/admin-manual/setup/install/#setup which should create the required DB columns

**Comment by jooola** [comment]
The docs are a bit outdated and missing some steps.

You probably need to run the migrations before starting LibreTime.

**Comment by comiconomenclaturist** [comment]
Yep that's it thanks. The docs appeared to specifically say DON'T run any setup, but this command seemed to do the trick:
`sudo -u libretime libretime-api migrate`

Also, great to see Libretime is using Django, looking forward to getting stuck in.

**Comment by comiconomenclaturist** [comment]
It looks like I spoke too soon, as the `sudo -u libretime libretime-api migrate` wipes out all everything in `cc_shows`, `cc_show_instances`, `cc_files`, `cc_prefs` etc.

I can now login, but I have no data from Airtime.

Steps taken so far are:

1) Change db name to airtime in /etc/libretime/config.yml
2) `sudo -u libretime libretime-api dbshell < airtime-backup`
3) `sudo -u libretime libretime-api migrate`

This last step gets the install working, but removes all the content from the database.

**Comment by jooola** [comment]
Could you delete the new DB, and start over while following the documentation https://github.com/jooola/libretime/blob/airtime_migration/docs/admin-manual/install/migrate-from-airtime.md

**Comment by jooola** [comment]
@comiconomenclaturist The branch that I shared you no longer exists, could you try the new docs for the migration https://libretime.org/docs/next/admin-manual/install/migrate-from-airtime/
