### ISSUE TITLE
Webstream - wrong metadata

### ISSUE THREAD

**Issue by wriop** [LibreTime/libretime#259]
Hello,
if i stream another webstream via libretime the metadata is wrong.
The Metadata from the webstream is only in the title part. The artist part ist empty.

Is a fix possible?

Greetings

**Comment by hairmare** [comment]
It looks like this won't be easy to implement across the board.

In the case of MP3 streams the stream metadata is already combined into one single metadata field containing all the info (ie. artist, title, album and, maybe station info). If the stream is OGG ecapsulated it may contain full metadata, so we could use that. (See [this stackoverflow](https://stackoverflow.com/a/28549316) for info).

It looks like the current [liquidsoap `input.http` code](https://github.com/LibreTime/libretime/blob/a69b86acc8a90aed1352812869590609701d3233/python_apps/pypo/liquidsoap/ls_lib.liq#L263-L415) doesn't have any special metadata handling. Most likely it's a simple passthough.

**Comment by xabispacebiker** [comment]
You are right @hairmare, but I think that might be updated in the liquidsoap.liq file. I will take a look as I need this also to be corrected.
