### ISSUE TITLE
Issues with ffmpeg silence detection thresholds

### ISSUE THREAD

**Issue by rjhelms** [libretime/libretime#2629]
### Describe the bug

The call to run ffmpeg for detect silences is as follows:

https://github.com/libretime/libretime/blob/bd6822fec615a2329745cf18aa3039a157870d47/analyzer/libretime_analyzer/pipeline/_ffmpeg.py#L75-L80

There are two issues with this call:

- ffmpeg does not support multiple filter arguments, so the highpass filter is not applied. To be effective, need to be chained eg `highpass=frequency=1000,silencedetect=noise=0.15:duration=1`
- more importantly, these settings are very different from what the old `silan`-based detection used.
    - Silan used a threshhold of 0.001 (equivalent to -60dB), 0.15 as used now is equivalent to -16dB. This is very aggressive, which is especially noticeable with spoken-word programming as final syllables or words can get detected as silence.
    - 1000Hz for a cutoff seems incredibly high (although this has no impact as it's not currently being applied) I'm not certain how silan's high pass coefficient maps to a frequency, but the 0.99 value Libretime used seems to be equivalent to about 80Hz which is a reasonable value.

To be consistent with the silence detection before the change to ffmpeg was implented, the filter should be something like: `highpass=frequency=80,silencedetect=noise=0.001:duration=1`

### To reproduce

1. Upload a file, and review cue points
2. In audio editing software, confirm that cue points are at logical place

### Expected behavior

As silence detection, cue in and out points should not trim off any of the content of the track.

For example, here is the results for the cue-out point identified for a track in our music library:
![image](https://github.com/libretime/libretime/assets/8541186/47efb626-20e8-4f37-9402-a7146d5b6c6d)

- The yellow marker is the current behaviour of libretime_analyzer, which trims off a bit of the end of the track.
- The red marker marker is the cue point ffmpeg reports if the highpass filter at 1000Hz is applied, trimming things even more aggressively.
- The green marker is the cue point ffmpeg reports with the values suggested to be consistent with the old silan behaviour, which does not trim off any actual audio in the track.

### LibreTime version

3.0.1

### Installation method and OS / Environment

Operating system: Ubuntu 20.04.5 LTS
Method: install script

**Comment by jooola** [comment]
Hey  @rjhelms,
Haha, indeed, I might have been a bit aggressive on the settings here.

It was my intention to make this configurable from the UI, but the analyzer doesn't support passing configuration from the UI/legacy app yet, we might be able to use the configuration file, but I think this would be a bad idea.

I have some branches working on this locally, never had the chance to push it. I'll see if I can push some change to make this happen.
