### ISSUE TITLE
How could I show 'Listener Stats' to 'Program Manager'?

### ISSUE THREAD

**Issue by rafaeletc** [LibreTime/libretime#266]
Where can I tweak user role settings?

**Comment by Robbt** [comment]
I don't think there is a UI for this right now. The role permissions are hardcoded, you could manually modify it in the code or work on a pull request to modify and add this functionality. I haven't looked into the specifics of where it is located in the code at this point but it might not be too difficult.

**Comment by hairmare** [comment]
You can change `'A'` to `'P'` here:

https://github.com/LibreTime/libretime/blob/4557395a865ed8d7592604b73c47ed3f5353c9dc/airtime_mvc/application/configs/ACL.php#L87

As Robb hinted, we absolutely welcome a pull request make this configurable 😉

**Comment by Robbt** [comment]
This issue was moved to http://libretime.trydiscourse.com/t/how-could-i-show-listener-stats-to-program-manager/22
