### ISSUE TITLE
Problem: certain podcasts fail to download files with "can't sync to an MPEG frame" error

### ISSUE THREAD

**Issue by adamburnsuk** [LibreTime/libretime#271]
Hello everyone,

This is a bit of a feature request and a question at the same time.  I run an online podcast network.  We do live streaming using an icecast server, but are looking to add pre-recorded shows as well.  These shows are all podcasts and release shows on a daily and/or weekly basis.  I have created a java program that will automatically download the latest episode of each show and put in a specific folder.  I have seen an issue or two dealing with podcasts, so maybe I'm missing a feature that already exists in LibreTime, if so, apologies.

But, I would like to create a schedule in LibreTime and just replace the files every day with the newest version.  Based on my limited understanding (I'm new to LibreTime/Airtime) each new file gets it's own database entry, so I'm not sure I can just replace files.  When I try to do a smart list, it seems to select the files when I add them to the show and never get updated again.

Does anyone have an idea of how I might set up this automated solution?  

Thanks,
Adam

**Comment by Robbt** [comment]
Hey Adam, not sure how I missed this issue. But there is a podcast subscription option added to LibreTime, you can just subscribe to a podcast and it will automatically download the newest one as well as create a playlist that contains a smartblock that will automatically update to the latest episode. 

Check out this wiki page for more details on how to set this up - https://github.com/LibreTime/libretime/wiki/Automatic-Playlists,-Smartblocks-and-Podcasts

I'm going to mark this closed for now but feel free to ask questions, there is also now a forum at discourse.libretime.org

**Comment by adamburnsuk** [comment]
Hey Rob,

Thanks for the personal reply.  I've installed libretime and am trying out
the podcast feature.  It's FANTASTIC.  I do have a question though.  I also
posted this in discord.  I thought I'd email this direct to you in case you
have any tips.  I am a developer (automation specialist)...but mostly
familiar with javascript, java, and c#.  So, it is going to be a bit of a
slow process figuring out how to debug php/python code.

Anyway, I am trying to use the podcast functionality and I don't know much
about how to debug issues.  But some of the podcast feeds, when i try to
import episodes, it will spin, but the green check mark will never appear
and the track doesn't seem to be imported.  There are no errors thrown, so
I'm unsure how to troubleshoot this.

Other podcasts work fine.  The feeds validate, so I don't think it's an
issue with them.

Any help or even tips for how to go about debugging the podcast import
feature would be really appreciated.

Thanks,
Adam

**Comment by Robbt** [comment]
Hey Adam, check out /var/log/airtime/airtime-celery.log and see if there are logs in there. The celery worker is what does the downloading of podcasts and it is likely that there are errors in there. It maybe they are timing out, there is another issue #220 that I created regarding a problem with podcasts failing if they take longer than 5 minutes to download. 

Let me know if you are able to figure it out.

In regards to contributing it's just a matter of learning and deciphering how the project is put together. It's an Object orientated MVC (model-view-controller) based web-app so probably not too drastically different than a lot of Java based web-apps. Getting a proper debugger set-up with debugger and a IDE that can let you walk through the code is probably the first step. I can give you some pointers in that regard. I'm using Phpstorm because I get a free student license but Eclipse and Xdebug should also work for free. Xdebug is a server side debugger, the only trick I found is that manually setting break points in the IDE didn't work but manually inserting xdebug_break() did.

**Comment by adamburnsuk** [comment]
So, I was able to find the log.  It was not in the location that you specified.  But I am now seeing the error...I have no idea what the error means...  

[2018-02-05 20:56:20,582: INFO/MainProcess] Task podcast-download[php_5a78c4f45253e6.63856814] succeeded in 0.232907097001s: '{"status": 0, "episodeid": 8, "error": "can\'t sync to an MPEG frame"}'

"Can't sync to an mpeg frame"

I have a couple of different podcasts that are getting that error and none of their files will download.  When googling this issue, I find some stuff about mutegen...is that what libretime is using?  Have you ever run into this issue?

**Comment by Robbt** [comment]
Mutagen is a python library used to read the mp3 id3 tags. Evidently something is causing this to fail, it could be that the files aren't properly downloading or they are incompatible with mutagen for some reason. This same error cropped up in issue #411, if you are able to provide a link to an example RSS feed or mp3 file I can analyze it and try to figure out what is causing this error. It's possible the track doesn't have ID3 tags and thus this error is happening, either way we should probably figure out a work around but that would be easier if there was something to test it on.

**Comment by adamburnsuk** [comment]
I'm not sure if I should keep posting here or post on an open issue, or open a new issue.  :)   But, here is a sample feed.
http://pokeitwithastick.podbean.com/feed

None of the files on this feed will download.  Funny thing is, even though it looks like a mutagen error, when I download manually to my machine and try to pull tag info using mutagen in python it works.  Mutagen doesn't throw any errors in that case.  But I always get the same "can't sync to an mpeg frame" error when using the airtime task.

**Comment by Robbt** [comment]
I would create a new issue. Looking at the podcast it might be possible that the jpg files are throwing off the podcast downloads. I'll have to test it and see if I can determine the cause. Your testing seems to suggest that it's not bad files per se.

**Comment by Robbt** [comment]
I tried this podcast that was mentioned above and it worked without problem with #639
