### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by CaptRR** [LibreTime/libretime#272]
I have run into a weird install issue.  When I run the install.sh, using sudo bash install.sh, I get the following error:
install: line 103: ./build.sh: Permission denied

I'm running ubuntu 14.04, but also got the same error on ubuntu 16.04.  Not sure if anyone knows why this is happening, or maybe its an alpha related bug, or even a problem with the keyboard mouse actuator :)

Thanks

**Comment by Robbt** [comment]
Hmm, not sure. Are you installing it on a virtual machine or a physical device ?
You could try typing
chmod +x build.sh 
This will give the command permission to execute. Not sure why it doesn't have it in the first place.
Did you install via the zip file or a git clone ?

**Comment by Robbt** [comment]
This issue was moved to http://libretime.trydiscourse.com/t/installation-issue/24
