### ISSUE TITLE
Can't cancel on-going 24 hour linked show

### ISSUE THREAD

**Issue by Robbt** [LibreTime/libretime#273]
This is on an Libretime instance I'm using as a relay. It rebroadcasts a linked webstream for 24 hours a day. I'm trying to switch the originating stream, there is no way to edit it (since it is linked) and when I click canel show it pops up with a confirmation prompt and then doesn't actually change anything.

I'll look at the logs, and try to figure this out but I wanted to document this in a bug report so that I remember to look into it and resolve it. The workaround is to delete the upcoming shows and insert a new one which results in a 24 hour delay.

**Comment by Robbt** [comment]
This still needs to be confirmed on a computer other than our streaming computer. Also this made me think we need to document the best way to have a streaming relay on a separate computer from your transmission machine. There are some improvements in terms of relaying id3 metadata and the possibility of the the streaming server behaving as a backup in the case of a network outage. The current way I have it setup is the streaming server listens to the we we streaming so that the network isn't overloaded at the transmitter site.

**Comment by expert-geeks** [comment]
I experienced the same bug. The workaround I found was to change the end of the show time so that it's less than 24 hrs, then you are able to cancel the show.

**Comment by Robbt** [comment]
So the issue isn't exclusive to 24 hour shows but in fact that you can't cancel a "linked" show that is currently airing. It runs into this exception.

https://github.com/LibreTime/libretime/blob/be5222d3a23f739b84326f445f1e4ecf1087110f/airtime_mvc/application/models/Scheduler.php#L172-L184

and basically I came up with a fix by passing an override to the validate request above that ignores this when a show is being cancelled.
