### ISSUE TITLE
Config CORSHelper

### ISSUE THREAD

**Issue by celiandu61** [LibreTime/libretime#276]
Hey, i'm working on the website on my radio. We are using libretime, i want to use the api to refresh the "on air" button on my website, so i'm using the api http://URL/api/live-info-v2
But i don't find explainment about usage of the CORSHelp i searched in the code source, and to get allowedDomain it call 
https://github.com/LibreTime/libretime/blob/061450a71fed6fc457396717210b15bdb5386275/airtime_mvc/application/models/Preference.php#L141

So, i need to add manually a domain in the database or, there is a command or a file to allow a domain ?

**Comment by hairmare** [comment]
You can add additional CORS URLs by adding them in the Admin Interface under "Settings" > "General".

**Comment by celiandu61** [comment]
Oh, sorry. I did not see that. Thx ;)
