### ISSUE TITLE
Is not an issue! Openldap ldif

### ISSUE THREAD

**Issue by rallep71** [LibreTime/libretime#277]
I search for an Openldap ldif Scheme to Import, or Tutorial to make a scheme step by step. Thankx

**Comment by hairmare** [comment]
The LDAP support was written and tested against an install of [FreeIPA](https://www.freeipa.org). It was written in a  generic fashion so it should work with most ldap configurations. The example conf file has [some explanatory comments](https://github.com/LibreTime/libretime/blob/bf643d45a0479269e6d84f6a10d34d4c5686e976/airtime_mvc/build/airtime.example.conf#L331-L364). The FreeIPA project has a [Quick Start Guide](https://www.freeipa.org/page/Quick_Start_Guide) and [more](https://www.freeipa.org/page/Documentation)

I do plan on writing up end-uesr friendly FreeIPA specific docs once I've also implemented and tested SingeSignOn with krb5.

What type of LDAP server do you plan on using? Usually the tooling you use for managing the server will already have some rules on how to structure the users and groups.
If you only want to use LDAP for LibreTime users you are probably better off with keeping the users in the database. Using LDAP will only add complexity without offering any real gain.

**Comment by Robbt** [comment]
This isn't an issue but a discussion regarding LDAP. So I'm going to close it. If someone wants to make it into a specific actionable feature request we can re-open it in the future.
