### ISSUE TITLE
auto disconnect of dj/live shows not working

### ISSUE THREAD

**Issue by unosonic** [libretime/libretime#2796]
### Describe the bug

dj/live shows don't terminate after scheduled end time

### To reproduce

1. create a dj/live show in calendar 
2. schedule it at a certain time and with a certain duration
3. wait and listen...
4. show doesn't end at the expected end date. dj has to end live streaming in order to terminate the show. If dj continues, his/her sho continues. 

### Expected behavior

a live show should stop at the scheduled end date of this show

### Relevant log output or error messages

```shell
2023/12/11 16:25:07 [show_input:3] user 'djane' connected
2023-12-11 16:25:07,731 | INFO     | libretime_playout.notify.main:live_auth:120
 - Checking 'show' live stream user authentication 'djane'
2023/12/11 16:25:07 [show_input:3] user 'djane' authenticated
...
2023/12/11 16:30:00 [server:3] New client: 127.0.0.1.
2023/12/11 16:30:00 [server:3] Client 127.0.0.1 disconnected.
2023/12/11 16:30:00 [server:3] New client: 127.0.0.1.
2023/12/11 16:30:00 [decoder:3] Method "FFMPEG" accepted "/var/lib/libretime/playout/scheduler/4.mp3".
2023/12/11 16:30:00 [server:3] Client 127.0.0.1 disconnected.
2023/12/11 16:30:00 [s3:3] Prepared "/var/lib/libretime/playout/scheduler/4.mp3" (RID 2).
2023/12/11 16:30:00 [lang:3] timeout --signal=KILL 45 libretime-playout-notify media '10' &
2023/12/11 16:30:00 [switch_9442:3] Switch to insert_metadata_9427.
2023/12/11 16:30:00 [lang:3] Using message format 1
2023/12/11 16:30:00 [lang:3] Using message format 1
2023/12/11 16:30:00 [lang:3] Using message format 1
2023/12/11 16:30:00 [server:3] New client: 127.0.0.1.
2023/12/11 16:30:00 [lang:3] web_stream.get_id
2023/12/11 16:30:00 [server:3] Client 127.0.0.1 disconnected.
2023-12-11 16:30:00,345 | INFO     | libretime_playout.notify.main:media:72 - Sending currently playing media id '10'
### source feeding from djane stopped manually
2023/12/11 16:30:27 [harbor:input_show:2] Feeding stopped: Mad.End_of_stream.
2023/12/11 16:30:27 [lang:3] timeout --signal=KILL 45 libretime-playout-notify live 'live_dj' 'false' &
2023-12-11 16:30:28,154 | INFO     | libretime_playout.notify.main:live:100 - Sending currently playing live source 'live_dj' status 'false'
2023/12/11 16:30:28 [server:3] New client: 127.0.0.1.
2023/12/11 16:30:28 [lang:3] sources.stop_input_show
```

### LibreTime version

3.2.0

### Installation method and OS / Environment

Operating system: Ubuntu 20.04 LTS
Method: installer script

### Client Environment

Operating system: Linux Mint
Browser: Firefox

**Comment by caveman99** [comment]
I tried tracing this through the instances... looks like a communication problem between playout and liquidsoap. the kick is scheduled but never executed.

Same happens for webstreams. if i have a webstream with 3 hours default length and schedule it in an one hour show it keeps playing for 3 hours.

**Comment by BrixSat** [comment]
Thanks @jooola i applied the patch restarted the libretime-playout but no luck, the dj is still connected. will try to kick it with iptables and see if it helps


`Jun 13 15:55:31 libretime systemd[1]: Started LibreTime Playout Service.
Jun 13 15:55:34 libretime libretime-playout[194067]: 2025-06-13 15:55:34,000 | INFO     | libretime_playout.main:cli:100 - Timezone: ('WET', 'WEST')
Jun 13 15:55:34 libretime libretime-playout[194067]: 2025-06-13 15:55:34,004 | INFO     | libretime_playout.main:cli:101 - UTC time: 2025-06-13 14:55:34.004134
Jun 13 15:55:34 libretime libretime-playout[194067]: 2025-06-13 15:55:34,117 | INFO     | libretime_playout.liquidsoap.client._client:wait_for_version:60 - found version (1, 4, 3)
Jun 13 15:55:34 libretime libretime-playout[194067]: 2025-06-13 15:55:34,121 | INFO     | libretime_playout.player.fetch:__init__:63 - PypoFetch: init complete
Jun 13 15:55:34 libretime libretime-playout[194067]: 2025-06-13 15:55:34,130 | INFO     | libretime_playout.player.queue:main:36 - waiting indefinitely for schedule
Jun 13 15:55:34 libretime libretime-playout[194067]: 2025-06-13 15:55:34,132 | INFO     | libretime_playout.history.stats:run:152 - starting stats collector
Jun 13 15:55:34 libretime libretime-playout[194067]: 2025-06-13 15:55:34,222 | INFO     | libretime_playout.message_handler:run_forever:96 - starting message handler
Jun 13 15:55:34 libretime libretime-playout[194067]: 2025-06-13 15:55:34,301 | INFO     | kombu.mixins:Consumer:229 - Connected to amqp://libretime:**@127.0.0.1:5672//libretime

Jun 13 15:55:34 libretime libretime-playout[194067]: 2025-06-13 15:55:34,394 | ERROR    | libretime_playout.liquidsoap.client._client:_set_var:50 - Done
Jun 13 15:55:34 libretime libretime-playout[194067]: 2025-06-13 15:55:34,395 | ERROR    | libretime_playout.liquidsoap.client._client:_set_var:50 - Variable station_name set (was "R\195\161dio Amor Portugal").
Jun 13 15:55:34 libretime libretime-playout[194067]: 2025-06-13 15:55:34,396 | ERROR    | libretime_playout.liquidsoap.client._client:_set_var:50 - Variable message_format set (was "0").
Jun 13 15:55:34 libretime libretime-playout[194067]: 2025-06-13 15:55:34,397 | ERROR    | libretime_playout.liquidsoap.client._client:_set_var:50 - Variable message_offline set (was "R\195\161dio Amor Portugal - AutoDj").


Jun 13 15:55:35 libretime libretime-playout[194067]: 2025-06-13 15:55:35,404 | INFO     | libretime_playout.player.liquidsoap:verify_correct_present_media:288 - Need to add items to Liquidsoap *now*: {1049}
Jun 13 15:55:35 libretime libretime-playout[194067]: 2025-06-13 15:55:35,407 | INFO     | libretime_playout.player.fetch:main:308 - Bootstrap schedule received: {'2025-06-13-14-00-00': FileEvent(start=datetime.datetime(2025, 6, 13, 14, 0), end=datetime.datetime(2025, 6, 13, 14, 57, 30), type=<EventKind.FILE: 'file'>, row_id=1049, uri=None, id=3058, show_name='autodj-radioamorportugal', fade_in=500.0, fade_out=500.0, cue_in=3335.407449, cue_out=3450.67102, track_title='APLAUSO ESP MUS ART PORT 13-06-2025.mp3', artist_name=None, mime='audio/mp3', replay_gain=-8.03, filesize=59067730, file_ready=True), '2025-06-13-14-57-30': FileEvent(start=datetime.datetime(2025, 6, 13, 14, 57, 30), end=datetime.datetime(2025, 6, 13, 15, 0), type=<EventKind.FILE: 'file'>, row_id=1050, uri=None, id=2927, show_name='autodj-radioamorportugal', fade_in=500.0, fade_out=500.0, cue_in=0.0, cue_out=149.32898, track_title=' Luis Godinho - España del Sol', artist_name='Luis Godinho', mime='audio/mp3', replay_gain=-5.35, filesize=2853386, file_ready=True), '2025-06-13-14-59-55': ActionEvent(start=datetime.datetime(2025, 6, 13, 14, 59, 55), end=datetime.datetime(2025, 6, 13, 14, 59, 55), type=<EventKind.ACTION: 'event'>, event_type='switch_off'), '2025-06-13-15-00-00': ActionEvent(start=datetime.datetime(2025, 6, 13, 15, 0), end=datetime.datetime(2025, 6, 13, 15, 0), type=<EventKind.ACTION: 'event'>, event_type='kick_out'), '2025-06-13-15-00-00_0': FileEvent(start=datetime.datetime(2025, 6, 13, 15, 0), end=datetime.datetime(2025, 6, 13, 15, 55, 17), type=<EventKind.FILE: 'file'>, row_id=1052, uri=None, id=3060, show_name='autodj-radioamorportugal', fade_in=500.0, fade_out=500.0, cue_in=0.0, cue_out=3317.82025, track_title='20 Mais 22 2025 - Primeira Hora.mp3', artist_name=None, mime='audio/mp3', replay_gain=-9.33, filesize=53086148, file_ready=True), '2025-06-13-15-55-17': FileEvent(start=datetime.datetime(2025, 6, 13, 15, 55, 17), end=datetime.datetime(2025, 6, 13, 16, 52, 10), type=<EventKind.FILE: 'file'>, row_id=1051, uri=None, id=3059, show_name='autodj-radioamorportugal', fade_in=500.0, fade_out=500.0, cue_in=0.0, cue_out=3413.114938, track_title='20 Mais 22 2025 - Segunda Hora.mp3', artist_name=None, mime='audio/mp3', replay_gain=-9.12, filesize=54610863, file_ready=True), '2025-06-13-16-52-10': FileEvent(start=datetime.datetime(2025, 6, 13, 16, 52, 10), end=datetime.datetime(2025, 6, 13, 18, 0), type=<EventKind.FILE: 'file'>, row_id=1053, uri=None, id=1838, show_name='autodj-radioamorportugal', fade_in=500.0, fade_out=500.0, cue_in=0.0, cue_out=4069.064812, track_title='Duas Horas', artist_name='Mcm Coraçao Da Musica', mime='audio/mp3', replay_gain=-12.07, filesize=145486657, file_ready=True), '2025-06-13-17-59-55': ActionEvent(start=datetime.datetime(2025, 6, 13, 17, 59, 55), end=datetime.datetime(2025, 6, 13, 17, 59, 55), type=<EventKind.ACTION: 'event'>, event_type='switch_off'), '2025-06-13-18-00-00': ActionEvent(start=datetime.datetime(2025, 6, 13, 18, 0), end=datetime.datetime(2025, 6, 13, 18, 0), type=<EventKind.ACTION: 'event'>, event_type='kick_out')}
Jun 13 15:55:35 libretime libretime-playout[194067]: 2025-06-13 15:55:35,414 | INFO     | libretime_playout.player.fetch:main:312 - Loop #1
Jun 13 15:55:35 libretime libretime-playout[194067]: 2025-06-13 15:55:35,427 | ERROR    | libretime_playout.liquidsoap.client._client:_set_var:50 - 5
Jun 13 15:55:35 libretime libretime-playout[194067]: 2025-06-13 15:55:35,433 | INFO     | libretime_playout.player.push:main:62 - heartbeat
Jun 13 15:55:35 libretime libretime-playout[194067]: 2025-06-13 15:55:35,434 | INFO     | libretime_playout.player.queue:main:57 - New schedule received
Jun 13 15:55:35 libretime libretime-playout[194067]: 2025-06-13 15:55:35,434 | INFO     | libretime_playout.player.queue:main:39 - waiting 114.565692s until next scheduled item
`
