### ISSUE TITLE
Does not go to the login page

### ISSUE THREAD

**Issue by sugonjakas** [LibreTime/libretime#280]
Hello!
Please help me solve the problem on debian 8. I'm far from a professional in programming. The essence is this:
1. Installed libretime without errors
2. To attach an address to the domain, I used an example from airtime (airtime-vhost.conf)

3. After successfully passing the initial settings path, the main screen is not displayed properly and does not enter the login page (I'm attaching the page).
![screenshot - 24 08 2017 - 21 55 51](https://user-images.githubusercontent.com/8542438/29676852-14b0b9d0-891b-11e7-93da-3986a0d6abec.png)
![screenshot - 24 08 2017 - 21 56 03](https://user-images.githubusercontent.com/8542438/29676853-14b68aa4-891b-11e7-9704-ba31c5e451c4.png)
![screenshot - 24 08 2017 - 21 58 52](https://user-images.githubusercontent.com/8542438/29676854-14c04314-891b-11e7-80ab-5281fee03cba.png)

Thank you in advance for your help!

**Comment by Robbt** [comment]
Well it seems like an apache config w/ maybe a mod_rewrite problem. Can you check the logs /etc/airtime/zendphp.log ?

**Comment by sugonjakas** [comment]
I apologize. Now I deleted it and rolled back to airtime. But before that it was empty in /etc/airtime/zendphp.log. Mod_rewrite - enabled.

**Comment by Robbt** [comment]
Ok, so this was an Airtime 2.5.x upgrade and there was nothing in /etc/airtime/zendphp.log, it seems likely that there was an issue with the upgrade script modifying the apache settings based upon the pre-existing 2.5.x. There hasn't been a lot of testing of what can go wrong during the upgrade process but this seems to be one of them.

**Comment by sugonjakas** [comment]
Likely. In the near future we plan to upgrade to a new server, I'll try to install it on a clean server after moving. Thank you!

**Comment by Robbt** [comment]
Well we should be able to fix the issue with diagnosing Apache settings and comparing them to what is expected. My guess is that they didn't get modified somehow to correspond with what is needed and thus even the logs were going somewhere else (probably /var/log/apache2/) 

But a clean install is another option and probably a faster way to get up and running.

**Comment by Robbt** [comment]
This issue was moved to http://libretime.trydiscourse.com/t/does-not-go-to-the-login-page/26
