### ISSUE TITLE
Need to contact Hairmare immediately

### ISSUE THREAD

**Issue by phil2211** [LibreTime/libretime#287]
# current behaviour
I can't contact hairmare on any known channels at all
verbose level of hairmare is not satisfying (exit code == 0??)

# expected behaviour
Hairmares contact data is known to phil2211

# acceptance criteria
Hairmare is contacting his ancient friends more often

**Comment by hairmare** [comment]
wait wat, imma call you tomorrow

**Comment by phil2211** [comment]
Acceptance criteria still not reached...
