### ISSUE TITLE
Pre-commit CI failing

### ISSUE THREAD

**Issue by paddatrapper** [libretime/libretime#2905]
The pre-commit CI check is failing due to configuration issues on the pipeline by the look of it - https://results.pre-commit.ci/run/github/82463450/1705584761.NYyMzxuuROyMU_i4SU68LA

**Comment by paddatrapper** [comment]
I've moved the integration to website, where we don't use shfmt or shellcheck, which are the failing checks

**Comment by jooola** [comment]
I knew I saw a note somewhere that pre-commit.ci was failing, I retried anyway, and bumped in the same problem again...
