### ISSUE TITLE
Install on Debian 8.9 in openvz

### ISSUE THREAD

**Issue by rallep71** [LibreTime/libretime#296]
Package sysvinit is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  systemd-sysv upstart sysvinit-utils sysvinit-core file-rc

E: Package 'sysvinit' has no installation candidate
./install: Zeile 676: php: Kommando nicht gefunden.

**Comment by hairmare** [comment]
Among the packages that replace sysvinit I think `systemd-sysv` is what debian-9 will be using so switching to that might make sense. I didn't really expect debian-8.9 to break things since it's not a major release like debian-9.

**Comment by Robbt** [comment]
This issue was moved to http://libretime.trydiscourse.com/t/install-on-debian-8-9-in-openvz/23
