### ISSUE TITLE
Import from cloud

### ISSUE THREAD

**Issue by celianvdb** [LibreTime/libretime#297]
Hey, i started my webradio since some weeks and i got a lot of files from different author and they everytime use wetransfer/gdrive/dropbox to send files.

Are you interesting if i add a feature to download files using a link from wetransfer/gdrive/dropbox on the upload page ?

**Comment by hairmare** [comment]
This seems like a worthy feature! Thanks for offering to implement it. Do you have a preference on how you would like to implement it? It might make sense to do the actual downloading in celery, similar to what the podcast downloader is doing.

**Comment by Robbt** [comment]
An additional useful feature that could be integrated into this would be the automated retrieval of files via FTP. I know that at least a few radio programs make their shows available in a certain directory to download to radio stations. Luckily most programs use RSS and perhaps this would be kind of a hybrid between the filesystem based media-import and a cloud import. Anyways I just thought I'd throw out the idea and encourage you to contribute. The most time consuming aspect is to integrate the script into the UI but we can help with that. Celery also does appear to be a good way to go about it.

**Comment by celiandu61** [comment]
Thanks for your interest :) In 3-4 weeks i will have time to dev this feature !
