### ISSUE TITLE
Russian translations misspelling.

### ISSUE THREAD

**Issue by hardwaynews** [LibreTime/libretime#300]
Hello i installed libretime and found misspelling on preference/stream-setting
Written :   Авто откоючение внешнего потока:
Must be :   Авто отключение внешнего потока:
If i find something else you will be informed.
If you will need some help just ask)
Thank you.

**Comment by hairmare** [comment]
Hi @hardwaynews 

Welcome to the community 😃  Thanks for reporting the issue.

You can fix translations directly in zanata if you would like to do so. You can find our "zanata Project" at https://translate.zanata.org/iteration/view/libretime/master.

I'll grab new translations from there when I do the next alpha release. I'll do it myself when I do the next release if you don't get around to if before then.

Thanks again for reporting this issue.

**Comment by yarik2720** [comment]
@hardwaynews thanks for paying attention
as in translate from English "Auto Switch Off:" there must be just "Авто-отключение:"
@hairmare Fixed that

**Comment by Robbt** [comment]
I think that this issue has been resolved through zanata. I'm going to mark it closed for now.
