### ISSUE TITLE
Let' sencrypt cerboot No problem just a question

### ISSUE THREAD

**Issue by rallep71** [LibreTime/libretime#302]
Let' sencrypt cerboot No problem just a question
Would it be possible to provide a detailed documentation and an example? The current Docu is not very helpful, not even the links that have already been posted here.

thank you

**Comment by Robbt** [comment]
This is a good idea. If you wanted to work on it we'd be happy to merge the update to the documentation. I haven't worked through the process, but I think that it would make sense to do this with an additional option in either the install or under settings once it has been installed as an additional feature for admins to check.

**Comment by hairmare** [comment]
The [existing docs](https://github.com/LibreTime/libretime/blob/29e7cc38a7eba52851437da853d6d3a60bf03ab0/docs/manual/secure-login-with-ssl/index.md) are in dire need of cleanup. Following them will most certainly make more issues and their wording is quite confusing in some places (ie. where they call self signed certs ''snakeoil'').

What are the issues you are having with [certbot](https://certbot.eff.org/)? It would be nice if we could get them figured out to help us update the docs.

Most of the work that has been but into the TLS side of things have been to ensure that using TLS actually works. Now that we are closer to that state It's probably time to start thinking about refactoring the docs.

**Comment by Robbt** [comment]
This issue was moved to http://libretime.trydiscourse.com/t/let-sencrypt-cerboot-no-problem-just-a-question/20
