### ISSUE TITLE
Import process stuck when no user "admin" exists

### ISSUE THREAD

**Issue by doriot** [libretime/libretime#3024]
### Describe the bug

If the user "admin" is removed from the system, LibreTime isn't able to import sounds anymore : the import process is stuck in pending state in the "recent upload" panel
Re-adding a user called "admin" restore the ability of LibreTIme to import sounds

Note : The system had an another user with administrative rights

### To reproduce

--Fresh LibreTime 4.1.0 install --

Log-in as admin
Go to Settings / Users
Create a new user with admin rights
Logoff

Log-in with the created user
Go to Settings / user 
Delete admin user 
Go to Upload panel
Try to import sounds

### Expected behavior

LibreTime should be able to import sounds even with no user called "admin" present in the system

### LibreTime version

4.1.0

### Installation method and OS / Environment

Operating system: Debian 11
Method: installer

### Client Environment

Operating system: Ubuntu 24LTS
Browser: Firefox

**Comment by paddatrapper** [comment]
Are there any logs from around the time of import?

**Comment by doriot** [comment]
I don't have the associated logs.
I can reproduce the bug if you want, and send you the logs if needed.

Please Advice

**Comment by doriot** [comment]
Tried to reproduce the bug on a fresh install

It was not an admin account issue, but rather a configuration problem with the public_url in config.yml

Closing the issue
