### ISSUE TITLE
Deprecated packages Warning on install

### ISSUE THREAD

**Issue by xabispacebiker** [LibreTime/libretime#304]
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.
Package raven/raven is abandoned, you should avoid using it. Use sentry/sentry instead.

**Comment by hairmare** [comment]
Guzzle broke backwards compatibilty with the switch to guzzlehttp/guzzle so getting rid of it would need quite some refactoring.

I don't think raven/raven is being actively used anywhere so we can probably get rid of it without replacing it with sentry/sentry (although [sentry](https://sentry.io) support would be a nice feature).
