### ISSUE TITLE
Display track filename and file size in edit screen

### ISSUE THREAD

**Issue by RobertWaterloo** [libretime/libretime#3053]
### Is your feature request related to a problem?

I would like to see the filename and file size of the tracks. 

### Describe the solution you'd like

Filename and file size could be displayed as a (non-editable) field in the track edit screen.

### Describe alternatives you've considered

Currently I look at the server's filesystem and hunt through the LibreTime track repository at /srv/libretime/imported/

Most of our DJs don't have the permissions to navigate the server filesystem.

### Additional context

I think Airtime 2.x may have displayed filename.

**Comment by dakriy** [comment]
I am currently working on this as my station operator wanted it too.

**Comment by dakriy** [comment]
I implemented this + being able to add the filename as one of the track dashboard columns too. I would like your input if you have any @RobertWaterloo , here is a screenshot from my local instance:

![show-filename](https://github.com/user-attachments/assets/29842788-261a-404f-94d9-61bffed0b6a2)

**Comment by RobertWaterloo** [comment]
Excellent! Looks really good.

I'd like to find the files in the repository, so it would be handy if the
the fully-qualified path could be made visible too. eg.
/srv/libretime/imported/13/artist/album/filename.mp3 Maybe as a separate
column...

Thanx!
--Bob.

Bob Jonkman ***@***.***
Radio Waterloo CKMS-FM 102.7 https://radiowaterloo.ca/
Host and Producer: CKMS Community Connections, Mondays 11am-Noon
Member: Technical, Program and Music Committees

**Comment by dakriy** [comment]
Administrators can now see the full file path, but any other type of user just sees the file name as it can be extra clutter unnecessary information for anybody other than an administrator who has access to the filesystem.
