### ISSUE TITLE
There was an error creating the database - Fresh install

### ISSUE THREAD

**Issue by DarkBlaez** [LibreTime/libretime#306]
At first I thought perhaps this was an error brought about by a previous host installed with other software. But after trying to run ./install -fiap on fresh Ubuntu 14.04 a number of times and each time a fresh OS on a VM, this error seems to be prevalent , reproduces each time.

During the install there appears to be no errors, a few warnings but nothing that would cause this error.

Upon hitting the URL for the first time, the usual screen for the database setup is presented. Taking all of the defaults results in the error "There was an error creating the database"

This  is reproducible every time from a fresh install of Ubuntu 14.04. What is the work around? I think others have seen this issue before as well and thought it would have been resolved by now since anyone with access to cheap VMs for testing can easily create a fresh instance and test the installer

I saw another post where it was suggested to init the DB but here's the result after su postgres to become the user

psql -d postgres -tAc "CREATE USER airtime WITH ENCRYPTED PASSWORD 'airtime'; ALTER USER airtime CREATEDB;"
ERROR:  role "airtime" already exists

So it appears some of the initial setup is indeed OK

The real issue is the database needs to be UTF8 and should be set in the install script or flagged

DB

**Comment by Robbt** [comment]
Most of our testing has been done with VirtualBox on local VM's. What set-up were you using ? We have seen some issues with certain VPS providers that I'm not sure were completely resolved.

When testing it I haven't ran into this issue. Please share more specifics about your set-up so we can replicate and resolve this issue. Thanks.

**Comment by DarkBlaez** [comment]
Looks like when the install script sets the locale this may not be taking pace. This happens on Digital Ocean, Vultr VPS providers.

What I had to do was:

1. Fresh install Ubuntu 14.04
2. set LANG=en_US.UTF-8 and  LC_ALL=en_US.UTF-8 in /etc/default/locale
3. also set the same in /etc/environment
4. sudo locale-gen "en_US.UTF-8"
5. sudo dpkg-reconfigure locales
6. reboot

After that and checking locales everything looked good to perform the install. At this point the install completed and everything went without error. So we are good here. Just note that the install is not setting the locale for some reason even though I can see it setting things up as the script runs

DB

**Comment by Robbt** [comment]
Odd, if you want to try to fix the script to get it to do this automatically feel free to contribute a PR. Otherwise we can leave this open and see if someone with access to digital ocean or Vultr can replicate and resolve in the script.

**Comment by hairmare** [comment]
I did some successful digital ocean tests on dply.co a while ago: https://github.com/LibreTime/libretime/issues/209#issuecomment-304448396.

Recommending users to actively set up their locale is probably sensible for most cases. This info should probaby go into the cloud setup up docs that we should add to the manual.

**Comment by Robbt** [comment]
This issue was moved to http://libretime.trydiscourse.com/t/there-was-an-error-creating-the-database-fresh-install/18

**Comment by banad60** [comment]
now we have nearly may 2019 and the installation sucks on ubuntu 18.04 as in 2017 on 14.04. 
quite great fun!

**Comment by Robbt** [comment]
@banad60 Your comment is not helpful in any way. Did you experience a similar database error during installation on Ubuntu 18.04 ? Which release were you using and what type of VPS was it ?

**Comment by banad60** [comment]
i know that this comment was not very friendly, sorry about my frustration on this. i worte a comment at https://discourse.libretime.org/t/there-was-an-error-creating-the-database/53/21 about these issues.

In short here: 
I get it mostly running, but not all. My setup is a ubuntu 18.04 LTS server as a VM in a test-enviorment (qemu/KVM) and it should run sometimes later on a real machine in a DMZ. (... if it is usable)

There was simply no database created during the installation-process (and i don't know why and i also will not know it - i do not wanna become a LibreTime-developer for installing it). 

The tested LibreTime-release have been first the master-bunch from git and then libretime-3.0.0-alpha.7. At least i get it to run .... and run in the next problem: it could not connect with mixxx 2.2.2, but icecast can ... hui!!  (i know about the ports 8000/8001 and liquidsoap, so i am at this moment proofing, if the reason for this is the setup or has it something to do with the Butt-problems > 0.1.14)

**Comment by Robbt** [comment]
Hmm, yeah the install script is kind of a hack, we are working on debian packages which will in theory provide a more fool proof way to install everything. Without logs from the install script it is hard to determine what failed. I suspect that if you didn't have SSH and ran the install script it got stuck on a prompt and didn't install the database. In that case the `sudo ./install -fiap` is the recommended way as it will say yes automatically to everything.

butt-0.1.17 works with libretime now and i've never encountered a specific error with mixxx - do you have any idea what the error is ?

**Comment by banad60** [comment]
There are a lot of logs, what log do you exactly mean/want/need? I have no log deleted, so in theorie it would be recoverable.

At the moment i have no sense, why mixxx can not connect. I think it may be butt or liquidsoap. Liquidsoap on this 18.04 was version 1.1.1. I try an upgrade to 1.3.7 and i will tell you how it did.

**Comment by Robbt** [comment]
If you want to upgrade to liquidsoap 1.3 you will need to modify some of the settings - https://github.com/LibreTime/libretime/issues/192

Butt & Mixxx are totally different icecast/liquidsoap client software. If you try butt and it works then the issue is likely with your mixxx configuration.

To see what the errors are you could look at the mixxx logs so as to see what is failing when you try to connect and/or the logs under /var/log/airtime/pypo-liquidsoap/ should contain details of the liquidsoap running and what errors happen when you try to connect with mixxx from the servers perspective.
