### ISSUE TITLE
[API V2] POST to schedule fails with Server Error 500

### ISSUE THREAD

**Issue by caveman99** [libretime/libretime#3088]
### Describe the bug

I am sending a POST request to schedule, intending to add a song at the end of an existing auto-populated schedule. I am populating the dataset with all fields but the ends_at is not accepted. I think it's something to do with the ends_at serializer override in api/libretime_api/schedule/serializers/schedule.py

### To reproduce

send POST to api/v2/schedule (this is an object dump of the data fields i sent)
```
    [cue_out] => 00:03:35.502000
    [ends_at] => 2024-10-07T14:28:45Z
    [starts_at] => 2024-10-07T14:25:10Z
    [length] => 00:03:35.502000
    [fade_in] => 00:00:00.100000
    [fade_out] => 00:00:02
    [cue_in] => 00:00:00
    [position] => 8
    [position_status] => 1
    [broadcasted] => 0
    [played] =>
    [instance] => 6770
    [file] => 2190
    [stream] => 
```
File and instance are valid for the request.

### Expected behavior

add to the schedule in the desired (unoccupied) position

### Relevant log output or error messages

```shell
2024-10-07 13:49:18,378 log ERROR Internal Server Error: /api/v2/schedule
Traceback (most recent call last):
  File "/opt/libretime/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/libretime/lib/python3.8/site-packages/psycopg/cursor.py", line 737, in execute
    raise ex.with_traceback(None)
psycopg.errors.NotNullViolation: null value in column "ends" violates not-null constraint
DETAIL:  Failing row contains (140760, 2024-10-07 14:25:10, null, 2190, null, 00:03:35.502, 00:00:00.1, 00:00:02, 00:00:00, null, f, 6770, 1, 0, 8).
```

### LibreTime version

develop-2643813fb7dfeb02e3cbb643e04b40c1121c89a2

### Installation method and OS / Environment

Operating system: Ubuntu 20.04.6 LTS
Method: git checkout -> install.sh

### Client Environment

Operating system:
Browser:

**Comment by paddatrapper** [comment]
What are the API logs for that request?

**Comment by jooola** [comment]
The v2 API does not yet support write operations. So this ticket is rather a missing feature than a bug.

**Comment by caveman99** [comment]
@joola completely understandable, as the V2 Api is pretty much boilerplate code. However I have a API workflow where i use a mix of V1 and V2 and that would be the last missing piece. Is there another API action i can use to add a new item at the end of a scheduled show instance?

What i use right now:
- a GET to api/v2/files to get a list of items in my library
- several GET to api/v2/schedule to get scheduled items in the past 24 hours and for the upcoming hour
- a loop with PATCH calls to api/v2/schedule/<id> to swap out the id of an item if it was played in the last 24 hours (this works!)
- a call to api/recalculate-schedule because the previous calls leave the schedule with wrong cuepoints, becasue i did not adjust the length of the items but just swap out the id.

Up till here everything works as intended.

Now i am checking with api/v2/schedule if the recalculation left me with a show that does not run to the end, because the substituted items may be shorter than the original ones. If it is too short i want to append another random item to the end of the schedule with the POST call and that one is failing.
