### ISSUE TITLE
Libretime layout improvements

### ISSUE THREAD

**Issue by xabispacebiker** [LibreTime/libretime#313]
I made a few (from my point of view) improvements to the interface.

![libretime-interface-mods](https://user-images.githubusercontent.com/1733884/31018327-f0a22e52-a52b-11e7-95a6-3deb46fb586b.png)

This screenshot shows the Host preferences page, who do not have access to the General Preferences.

https://github.com/xabispacebiker/libretime/tree/reconditioning-interface-personal-block

**Comment by hairmare** [comment]
Awesome! These changes look great, moving the Logout button also solves the issue of the previous link disapearing on small screens in some locales. Do you plan on adding a UI for updating the logo or did I miss that looking at your branch?

**Comment by xabispacebiker** [comment]
The logo is set in General Preferences.
![captura de pantalla 2017-09-30 a las 11 26 11](https://user-images.githubusercontent.com/1733884/31044571-309ad8a0-a5d2-11e7-9656-7b4f557becc4.png)

**Comment by Robbt** [comment]
Hey @xabispacebiker do you want to do a PR for this ? I think it would be a good improvement for the LibreTime UI in general and the logo change would be a definite improvement. The only thing we might want to do is update the manual.

**Comment by HammyHavoc** [comment]
I'd like to see this too. Though speaking of logos, would you be interested in a LibreTime logo for the project and to set as default to replace http://radio.voidancerecords.com/css/images/airtime_logo_med2.png? If so, let @bryandesrosiers know and he might be interested in helping. :- )

**Comment by Cysioland** [comment]
@xabispacebiker Yeah, definitely a pull request would be nice

**Comment by xabispacebiker** [comment]
@HammyHavoc , it would definitely be awesome if @bryandesrosiers could provide a default logo for the project. Hopefully, I can find some time this week to send the pull request.

**Comment by Cysioland** [comment]
@xabispacebiker In absence of that, even a plain "LibreTime" text would be nice

**Comment by xabispacebiker** [comment]
If we get the logo soon, then the wait is worth it.. but if it's gonna take long we might just add some default text, or just leave it empty until a station logo is configured in preferences.
