### ISSUE TITLE
Problem with HTML encoding in smart block builder

### ISSUE THREAD

**Issue by squiggleuk** [LibreTime/libretime#328]
**Problem**
There an issue with SmartBlock builder saving some characters as the HTML encoded value when the are entered in the 'sp_criteria_value' field. Can lead to SmartBlocks note returning the desired tracks.

**Steps to reproduce**
Set the 'genre' of a track or two to 'D&B'.
Create a new SmartBlock
Set the criteria to be 'Genre' 'is' 'D&B'
Click generate - (No results are returned - Unexpected)
Save the Smart Block
Close The Smartblock
Reopen the SmartBlock
Observe the criteria value is now 'D&amp;B'

I did try to find where this might be happening, but struggled. Maybe 'airtime_mvc/application/forms/SmartBlockCriteria.php' ?

**Comment by hairmare** [comment]
Most likely `Zend_Form_Element_Text` is doing this.

https://github.com/LibreTime/libretime/blob/276a69aa1bef527260efc170d7caab7d04b4ca13/airtime_mvc/application/forms/SmartBlockCriteria.php#L269-L279

I think it's something to do with the default ZF1 view helper escaping the value on output and it then getting saved already encoded on subsequent saves.

Possibly this is the default view helper and it does do some escaping on the value:

https://github.com/zendframework/zf1/blob/a90f3a8d71e0788020f730da83674b7312bd3b16/library/Zend/View/Helper/FormText.php#L68-L74

I'd need to reproduce this on my dev box to really figure out more though.

**Comment by Robbt** [comment]
This is most likely the same problem as highlighted in #282.

**Comment by squiggleuk** [comment]
Agree. Apologies - I never spotted the other issue.

Shall I close this off under the assumption that all fields will be covered under #282 ?

**Comment by Robbt** [comment]
I'd keep it open for now and we can just close them both when the issue is resolved.

**Comment by Robbt** [comment]
I found where it is getting escaped it was from commit 74bc485b and here is the culprit https://github.com/LibreTime/libretime/blob/49a715bc98d14c7f412803d598c83661d81b1d20/airtime_mvc/application/models/Block.php#L1442 
I haven't had time to take this out and see if the situation is magically resolved and I'm not sure if wrapping the value is necessary for protection or a mistake.
