### ISSUE TITLE
Current ideal distro for Libretime? +a couple more questions

### ISSUE THREAD

**Issue by astrotumult** [LibreTime/libretime#336]
Greetings! I'm hesitant to use the issue tracker for general questions / non-issues, but I don't find a general mailing list, and by asking questions now, perhaps I can prevent reporting issues later.

I am going to replace an Airtime instance with Libretime (full clean install, new VPS), and my question is whether there is currently a strongly preferred distro? Just due to having the most current experience with CentOS 7, that would be my preference, but I am really pretty agnostic about it if there are compelling reasons to use a different distro.

Question 2: What is the current status of recording streams of live broadcasts from remotes without a soundcard? This is an essential feature to me. I have previously (at a station that used custom software, not Airtime) hacked together a streamripper solution for this, but I am wondering if it works built-in at this point.

I've been lurking here for months but am planning to finally get started implementing. I am a professional web developer (PHP + JS/jQuery mostly these days, but also significant Python and PostgreSQL experience) and am hoping to be able to contribute once I start actually using the software.

Thanks!

**Comment by squiggleuk** [comment]
Hi @astrotumult,

There's a bit of discussion about this in #191. I've recently installed on Ubuntu 16.04LTS with minimal issue (I had to fix the problem with silian and incorrect file lengths)

I believe that recording isn't working to well currently. However, in #291 @groundtruthnz shares a nice script similar to what you've mentioned.

**Comment by hairmare** [comment]
Hey @astrotumult 

Welcome to the community!

If CentOS is your preferred distro you might want to give my "Skunkworks" LibreTime packages a try.

The easiest way to use them is to install `epel-release` and the [nux-dextop repo](https://li.nux.ro/repos.html) and then go to [the noarch dir](https://download.opensuse.org/repositories/home:/radiorabe:/airtime/CentOS_7/noarch/) of the [OBS build project](https://build.opensuse.org/package/show/home:radiorabe:airtime/libretime) and install the current `libretime-release-*.rpm` from there. Please be warned that the install is still a bit experimental as it uses liquidsoap 1.3. On the upside it has a usable silan install out of the box.

I plan on transitioning the whole build-infra stuff to the LibreTime orga but haven't gotten to that yet. There are also some questions regarding the liquidsoap build that need to stabilize so we have a proper way forward. Like everything, the alpha status is still warranted and if you're coming from legacy upstream it might take some polishing to get everything you currently need up to speed.

Line in recording is mostly broken and stream line in is a common feature request. So there is some refactoring potential there. We hope to get this done before we get to beta releases but there might be quite some beta releases on the way there. Any help on this is gladly appreciated!

From my POV (as a PHP dev that only recently started doing serious python) I consider the PHP parts rather legacy but they do work and are extendable for the time being. The frontend parts are a complete mess at this point. I had a go at refactoring in [my fork](https://github.com/radiorabe/libretime/tree/dev/js-refactor) but got bogged down when I realized that there doesn't seem to be a sane upgrade path for the datatables code. The PHP/Js parts still seem to work in new browsers and are PHP safe so they work for now. The newish python code looks rather ok but some cross cutting concerns (like the API situation) clearly need proper addressing. There is also some python 2to3/future work that needs to be taken care of at some point.

Let us know where you'd like to start hacking and I'll take care getting you an orga invite so you can tag stuff and self-assign issues. We're looking forward to you pull requests!

Again, thanks for contributing!

**Comment by Robbt** [comment]
This issue was moved to http://libretime.trydiscourse.com/t/current-ideal-distro-for-libretime-a-couple-more-questions/19
