### ISSUE TITLE
Scheduled Play does not show up?

### ISSUE THREAD

**Issue by Zopokx** [LibreTime/libretime#337]
Is any magical or hidden mechanism to show up the -scheduled play-?
https://sourcefabric.booktype.pro/airtime-25-for-broadcasters/stream-settings/static/Screenshot309-Master_source_switch.png

My instance of libretime does not have it, and I do not know if it's my fault...

**Comment by hairmare** [comment]
Hi @Zopokx 

Welcome to the community!

It's a pro feature that was never included in any opensource code so the LibreTime doesn't have access to it. We are working on replacing what it did under the hood with a [wiki page](https://github.com/LibreTime/libretime/wiki/Smart-Block-development) and numerous issues like #335, #319 and more.

As with legacy upstream you can also hack the code to replace the silence parts with you own fallback (if that is what you are after).

I'm going to tag this as "documentation" so I don't forget to clarify the relation/differences to legacy upstream in https://github.com/LibreTime/libretime/blob/master/docs/faq.md as the recently closed #179 reminded me to.

Thanks for raising this and welcome aboard.

**Comment by Zopokx** [comment]
So, the basic functionality for managing tracks & playlists (like ZaraStudio) doesn't exist? I thinks I am missing this point...

**Comment by Robbt** [comment]
No. All of that works. The prompt at the top just doesn't exist that indicates designated "Scheduled Play". The On Air button to the right still lights up when tracks are being played. Basically if you schedule tracks on the calendar they should play at the appropriate times. The indicators at the top are useful for indicating live streaming which is what their original purpose was.

**Comment by Zopokx** [comment]
It should be my fault. I have right now a track playing, but I can't hear it neither I can't see the On Air button working... so? 
Does libretime works with local auto generated sound stream?
![captura de pantalla de 2017-10-18 15-06-23](https://user-images.githubusercontent.com/1054576/31720173-1a28740e-b416-11e7-815c-53ee2ab5d4ba.png)

**Comment by Robbt** [comment]
Yeah. There is an issue elsewhere. If you cloned from git there is an issue that just merged that might fix this. Issue probably with pypo.

**Comment by Zopokx** [comment]
OMFG, very BAD luck guy... xD

Fixed for now. Thankyou! I was getting nuts!

**Comment by hairmare** [comment]
Yeah you really had back luck, great to here that it's working now.

**Comment by Robbt** [comment]
This issue was moved to http://libretime.trydiscourse.com/t/scheduled-play-does-not-show-up/21
