### ISSUE TITLE
Problem: The cursor doesn't default to the track search bar upon page load

### ISSUE THREAD

**Issue by Robbt** [LibreTime/libretime#339]
This is another persistent request from one of our users that should improve usability. 

Basically the idea is that upon page load the cursor should default to the search bar.
Thus if someone is looking at the tracks page and they start typing then what they are typing will show up in the search box.

This seems like a logical default position for the cursor and would avoid an extra click for most use cases.

**Comment by jerry924** [comment]
@Robbt - here is a way I got this to work. You might want to try it out and then do a PR if it works out everywhere.

This keeps the focus on the input box all of the time.

Steps to add this:

1) edit the file: airtime_mvc/public/js/airtime/library/library.js
2) Add the following code in between the line of dashes. The code above the first line of dashes and below the second line of dashes is existing code in the javascript above:

```
       AIRTIME.library.setCurrentTable(table, false);
       oTable = $datatables[table];
       setColumnFilter(oTable);
       oTable.fnSetFilteringDelay(350);

       var simpleSearchText;

       /*----------------------------------------------------*/
       /* Always keep cursor focus on the filter box */
       /* set focus into the input box when page loads */
       $(window).ready(function(){ 
          $libContent.find("#library_display_filter label").find('input').focus();
       } );
       /* set focus into the input box when user clicks anywhere else in UI */
       $(window).click(function(){
          $libContent.find("#library_display_filter label").find('input').focus();
       } );
       /*----------------------------------------------------*/

       $libContent.on("click", "legend", function(){
           $simpleSearch = $libContent.find("#library_display_filter label");
           var $fs = $(this).parents("fieldset"),
               searchHeight,
               tableHeight = getTableHeight(),
               height;
```

**Comment by Robbt** [comment]
Cool, thanks for the contribution. I'll have to play with this and figure out the best way to do this.
