### ISSUE TITLE
Problem: Undefined index from missing cloud_storage.conf causes PHP errors in conf.php

### ISSUE THREAD

**Issue by Robbt** [LibreTime/libretime#34]
Currently /usr/share/airtime/php/airtime_mvc/application/configs/conf.php gives errors related to Undefined index: amazon_S3 on line 58. If these are commented out a number of other issues in the config crop up.

**Comment by Robbt** [comment]
This is a duplicate of issue #24

**Comment by Robbt** [comment]
The sections that are likely in this file are below referenced below. Until we setup an S3 account to test this it might be good idea to simply comment out the amazon_s3 index.
python_apps/airtime_analyzer/airtime_analyzer/cloud_storage_uploader_libcloud.py:            self._storage_backend = cloud_storage_config_section
python_apps/airtime_analyzer/airtime_analyzer/cloud_storage_uploader_libcloud.py:            self._provider = config.get(cloud_storage_config_section, 'provider')
python_apps/airtime_analyzer/airtime_analyzer/cloud_storage_uploader_libcloud.py:            self._bucket = config.get(cloud_storage_config_section, 'bucket')
python_apps/airtime_analyzer/airtime_analyzer/cloud_storage_uploader_libcloud.py:            self._api_key = config.get(cloud_storage_config_section, 'api_key')
python_apps/airtime_analyzer/airtime_analyzer/cloud_storage_uploader_libcloud.py:            self._api_key_secret = config.get(cloud_storage_config_section, 'api_key_secret')

**Comment by hairmare** [comment]
I might give it a go with https://github.com/minio/minio (a s3 compatible storage server). There are others as well, but I haven't used anything opensource yet.

Did you see [airtime_mvc/tests/conf/testing/cloud_storage.conf](https://github.com/LibreTime/libretime/blob/9bac8354b6cce1730eb1784700fa80741af130f2/airtime_mvc/tests/conf/testing/cloud_storage.conf)? That has worked fine for me.

**Comment by Robbt** [comment]
I have this one, haven't tested it yet, but I did get a sample cloud_storage.conf based upon the testing with the keys that would be expected from the cloud_storage based upon python.
