### ISSUE TITLE
Upload of mp3 files fail on debian stretch 9

### ISSUE THREAD

**Issue by b01xy** [LibreTime/libretime#340]
Hello,

On a fresh debian stretch 9, the install file from git works well but the upload of mp3 files fails, whereas uploading ogg, wav, and flac files works

the folder /srv/airtime/stor/organize/ exists and the mp3 file is in it

From /var/log/airtime/airtime_analyzer.log : 
```
2017-10-18 02:00:07,626 [message_listener] [INFO ]   Listening for messages...
2017-10-18 02:01:15,219 [message_listener] [INFO ]   - Received '{"tmp_file_path":"\/srv\/airtime\/stor\/organize\/deutsch2410114.mp3","storage_backend":"file","import_directory":"\/srv\/airtime\/stor\/\/imported\/1","original_filename":"deutsch2410114.mp3","callback_url":"http:\/\/88.177.212.178\/\/rest\/media\/24","api_key":"ADO9GYYER95G94TCEC8L","file_prefix":""}' on routing_key ''
2017-10-18 02:01:18,853 [playability_analyzer] [WARNI]  Command '['liquidsoap', '-v', '-c', 'output.dummy(audio_to_stereo(single(argv(1))))', '--', u'/srv/airtime/stor/organize/deutsch2410114.mp3']' returned non-zero exit status -11
2017-10-18 02:01:18,854 [analyzer_pipeline] [ERROR]  
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/airtime_analyzer-0.1-py2.7.egg/airtime_analyzer/analyzer_pipeline.py", line 73, in run_analysis
    metadata = PlayabilityAnalyzer.analyze(audio_file_path, metadata)
  File "/usr/local/lib/python2.7/dist-packages/airtime_analyzer-0.1-py2.7.egg/airtime_analyzer/playability_analyzer.py", line 30, in analyze
    raise UnplayableFileError()
UnplayableFileError
2017-10-18 02:01:18,869 [message_listener] [ERROR]  Analyzer pipeline exception: 
2017-10-18 02:01:18,948 [status_reporter] [INFO ]  HTTP request sent successfully.
```
Maybe a  problem related to #256 ?

I tried to uninstall everything even python, install python-pika first and then LibreTime but nothing changed.

also, 
```
liquidsoap -v -c 'output.dummy(audio_to_stereo(single("/srv/airtime/stor/organize/deutsch2410114.mp3")))'
Segmentation fault
```

any idea ?
thks
b

**Comment by Robbt** [comment]
This sounds like it might be a codec issue, considering the other formats are working and this is on debian. Even though mp3 is no longer patent encumbered as of a few months ago but I don't think we've seen anything like this before. I'll look at the code and see if I can find any reason why it might be failing based upon those lines of code. Have you tried different many mp3 files, it might be something as simple as the encoding format or what not.

**Comment by b01xy** [comment]
Hi,
thanks for your quick reply
yes, I've tried several mp3 files encoded by myself or music from the net
after a new réinstall of LibreTime, flac upload is not working anymore, ogg is still working, strange !?
++
b

**Comment by Robbt** [comment]
Ok, yeah so this runs liquidsoap to see if it can play the file. For some reason this is failing. The next step is to try to run liquidsoap from the command line and see what the error is. Most likely you just need to type` liquidsoap -v -c  output.dummy(audio_to_stereo(single(argv(1)))) /srv/airtime/stor/organize/deutsch2410114.mp3` and see what happens.

**Comment by Robbt** [comment]
I might not have parsed the command line instruction correctly as you might need to add a -- before the filename. Make sure that file exists as well.

**Comment by Robbt** [comment]
`liquidsoap -v -c "output.dummy(audio_to_stereo(single(argv(1))))" -- /srv/airtime/stor/organize/deutsch2410114.mp3` or `liquidsoap -v -c "output.dummy(audio_to_stereo(single(argv(1))))" -- /srv/airtime/stor/organize/deutsch2410114.mp`3 or `liquidsoap -v -c output.dummy(audio_to_stereo(single(argv(1)))) --/srv/airtime/stor/organize/deutsch2410114.mp3`

**Comment by b01xy** [comment]
Yep,
the pb may come from here : 
```
radio@radio:/srv/airtime/stor/organize$ liquidsoap -v -c "output.dummy(audio_to_stereo(single(argv(1))))" -- /srv/airtime/stor/organize/250114_1.mp3
Segmentation fault
radio@radio:/srv/airtime/stor/organize$ liquidsoap -v -c "output.dummy(audio_to_stereo(single(argv(1))))" -- /srv/airtime/stor/organize/250114_1.mp3
Segmentation fault
radio@radio:/srv/airtime/stor/organize$ liquidsoap -v -c output.dummy(audio_to_stereo(single(argv(1)))) --/srv/airtime/stor/organize/250114_1.mp3
-bash: syntax error near unexpected token `('
radio@radio:/srv/airtime/stor/organize$ liquidsoap -v -c output.dummy(audio_to_stereo(single(argv(1)))) /srv/airtime/stor/organize/250114_1.mp3
-bash: syntax error near unexpected token `('
```
I also tried : 
`liquidsoap -v -c 'output.dummy(audio_to_stereo(single("/srv/airtime/stor/organize/250114_1.mp3")))'`
which also seg fault

++
b

**Comment by Robbt** [comment]
So there is a problem with your liquidsoap binary then. I haven't looked into it looks like by default https://packages.debian.org/stable/sound/liquidsoap has 1.1.1-7.2 whereas the Ubuntu trusty has 1.1.1-6ubuntu2.

I'm not sure where the issue with liquidsoap is coming from as I think other people have successfully installed from Stretch without running into this particular problem.

**Comment by Zopokx** [comment]
I'm using debian stretch too (git clone) and I didn't experienced this problem...

**Comment by hairmare** [comment]
@b01xy  I'm assuming you installed the debian packages for liquidsoap (or automatically got them installed). Can you try using an opam install of liquidsoap? Details on the opam install may be found [here](http://liquidsoap.fm/download.html) and you would also need to apply the patch linked in #192.

I'm not sure why it would segfault though as others have had success. Maybe running the command through strace indicates something. Is AppArmor or something similar activated on the machine?

**Comment by b01xy** [comment]
thanks for your reply
I'll try your advice on a fresh debian install asap
I don't have access now to the machine I previously installed (it is now installed in the local network of a school), but I'll try when I'll go there
btw, also thks to all the persons involved in LibreTime, really nice work :)
++
b

**Comment by Robbt** [comment]
This issue was moved to http://libretime.trydiscourse.com/t/upload-of-mp3-files-fail-on-debian-stretch-9/15
