### ISSUE TITLE
Unable to login to discourse

### ISSUE THREAD

**Issue by squiggleuk** [LibreTime/libretime#343]
![capture](https://user-images.githubusercontent.com/14201513/31821230-5baac8c8-b59c-11e7-819d-4fc115cbb6ed.PNG)

I'm trying to click login with github, I see the popup window, but it has the attached error.

Tried logging out of github and trying again, this time i got a login window in the popup, but after logging into github saw the same error.

Is anyone else able to log into the forum ok? Trying to work out if the issue is with me or SSO

**Comment by ronstep** [comment]
I got the same, but just re registered

Regards

**Comment by Robbt** [comment]
Ok, I think I fixed it, I had http:// vs. https:// for the callback URL in the github application. I got the same error as you guys and then tried it again when I changed the setting and it worked. I also registered a new oauth application to the LibreTime project vs. my own personal github. Let me know if it works for you now squiggleuk and I'll close this issue.

**Comment by squiggleuk** [comment]
Fix confirmed.

Many thanks!
