### ISSUE TITLE
High Memory usage on Debian 9 - Rabbitmq?

### ISSUE THREAD

**Issue by amavarick** [LibreTime/libretime#346]
I have a Debian 9 VPS that has nothing else installed than what came from VPS which they call a minimal install.  The only software installed is LibreTime and it is just a base default install with no customizations.  Server left running, no load, just Libretime running averages around 1.78GB of memory usage.  For comparison, I have another Debian server running Icecast and Liquidsoap which is at 1.01GB BUT I'm running 4 separate radio station streams on that one.

Here are my exact commands to deploy this Debian 9 box.  Commands don't include any hardening steps which I would use later outside of testing purposes.

```
passwd
apt install -y sudo nano locales
apt-get remove -y exim4 exim4-base exim4-config exim4-daemon-light
apt purge -y exim4
sudo apt-get update && sudo apt -y upgrade
sudo apt-get -y autoremove && sudo apt-get -y autoclean
#sudo reboot
sudo dpkg-reconfigure locales
sudo locale-gen --purge en_US.UTF-8
sudo update-locale LANGUAGE="en_US.UTF-8"
sudo sed -e 's/^fe/#fe/g' -i /etc/hosts
sudo sed -e 's/^ff/#ff/g' -i /etc/hosts
sudo apt -y install unattended-upgrades
sudo reboot
#Install Libretime.org
sudo apt -y install git && sudo git clone https://github.com/libretime/libretime.git
cd /root/libretime
./install -iap
```

![vpsmemory](https://user-images.githubusercontent.com/20918832/32137957-16a1dbec-bbf8-11e7-9383-639135bc3c75.png)

**Almost 3 pages of PIDs just for Rabbitmq...**

![rabbitmq taking lots of memory htop01](https://user-images.githubusercontent.com/20918832/32137960-1f6ff3a8-bbf8-11e7-82e6-8252c92aa36b.png)

```
# cat /proc/meminfo
MemTotal:        6291456 kB
MemFree:         4422036 kB
Cached:          1225572 kB
Buffers:               0 kB
Active:           727548 kB
Inactive:         809208 kB
Active(anon):     140724 kB
Inactive(anon):   170460 kB
Active(file):     586824 kB
Inactive(file):   638748 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:                 4 kB
Writeback:             0 kB
AnonPages:        311184 kB
Shmem:            259968 kB
Slab:              72620 kB
SReclaimable:      50392 kB
SUnreclaim:        22228 kB
```

Please advise if there is any other further information I can provide.  I'm wondering if RabbitMQ is creating additional processes and not closing/purging them properly.  Please advise if there is any other information I can provide for troubleshooting.  I did provide my commands above for someone to be able to quickly duplicate their server as I have for testing this.

**Comment by hairmare** [comment]
Hey @amavarick 

Sorry for not getting back to you earlier, I've been way to busy with the Audio-over-IP deploy at my station lately.

I think the high memory usage in RabbitMQ happens when nothing is scheduled an the playout engine tries to figure out what to play by basically just hammering RabbitMQ with a ton of requests.

I've only seen this happen on fresh installs with no uploaded files and nothing scheduled though, so I'm not sure if this is the issue you are facing.

The amount of beam processes getting spawned certainly indicates that the error might be somewhere else. Maybe there are more hints in `systemctl status rabbitmq-server` or in `journalctl`. You might also want to try stopping everything related to RabbitMQ with `systemctl stop rabbitmq-server`, ensuring that no RabbitMQ processes (and killing them if they still exist) and then restarting RabbitMQ with `systemctl start rabbitmq-server` again.

The only additional thing that I can think of that might be an issue is IPv4 vs IPv6. If I recall correctly the Erlang beam stuff RabbitMQ is using doesn't really work well on an IPv6 only stack. I wouldn't expect you VPS to be IPv6 only though.

**Comment by amavarick** [comment]
Yes, the issue was on a brand new instance that has been sitting with no uploads or schedules.  I'm going to create a new instance and load some files and create some schedules to see if this makes a difference.  I disabled IPv6 public IP but left the IPv6 localhost in place because ehrlang needs the IPv6 localhost.   IPv4 is fully implemented and functional.

sudo rabbitmqctl status
Status of node rabbit@stream3 ...
[{pid,1065},
 {running_applications,[{rabbit,"RabbitMQ","3.6.6"},
                        {mnesia,"MNESIA  CXC 138 12","4.14.2"},
                        {ranch,"Socket acceptor pool for TCP protocols.",
                               "1.2.1"},
                        {rabbit_common,[],"3.6.6"},
                        {os_mon,"CPO  CXC 138 46","2.4.1"},
                        {xmerl,"XML parser","1.3.12"},
                        {sasl,"SASL  CXC 138 11","3.0.2"},
                        {stdlib,"ERTS  CXC 138 10","3.2"},
                        {kernel,"ERTS  CXC 138 10","5.1.1"}]},
 {os,{unix,linux}},
 {erlang_version,"Erlang/OTP 19 [erts-8.2.1] [source] [64-bit] [smp:48:4] [async-threads:64] [kernel-poll:true]\n"},
 {memory,[{total,75795416},
          {connection_readers,46392},
          {connection_writers,30488},
          {connection_channels,103016},
          {connection_other,91984},
          {queue_procs,191520},
          {queue_slave_procs,0},
          {plugins,0},
          {other_proc,16482032},
          {mnesia,90184},
          {mgmt_db,0},
          {msg_index,62240},
          {other_ets,979960},
          {binary,2661424},
          {code,17754321},
          {atom,752561},
          {other_system,36549294}]},
 {alarms,[]},
 {listeners,[{clustering,25672,"::"},{amqp,5672,"::"}]},
 {vm_memory_high_watermark,0.4},
 {vm_memory_limit,2576980377},
 {disk_free_limit,50000000},
 {disk_free,29925548032},
 {file_descriptors,[{total_limit,65436},
                    {total_used,6},
                    {sockets_limit,58890},
                    {sockets_used,4}]},
 {processes,[{limit,1048576},{used,245}]},
 {run_queue,0},
 {uptime,1842437},
 {kernel,{net_ticktime,60}}]


You are faithful at responding to all, no issues with response.  The memory usage though higher is not overly alarming and thus low priority, at least my VPS provider is not complaining.  ;-)  I really appreciate your dedication to this project and swift response and commits for high priority issues.
