### ISSUE TITLE
Best practices: How to add an advert/commercial

### ISSUE THREAD

**Issue by Zopokx** [LibreTime/libretime#347]
I have an advert of ~24 seconds. What is the best way to insert it at an specific time without disturb the schedule? (for example, at 13:37 o'clock)

**Comment by Robbt** [comment]
There is nothing in particular that allows this to happen at this point. The idea of advertisements or station IDs being blended on top of already existing scheduled programming is an interesting one but nothing in the codebase allows this at this point. The only feasible way I could see this happening is to have another program sign-on as the "master" stream and broadcast the ad. Programming this setup would probably need to happen independent of LibreTime at this point in time.

**Comment by hairmare** [comment]
Liquidsoap does have some support for overlaying tracks onto each other. If you don't need the advert to be overlayed onto the currently running program you might be able to acheive something like this using smart blocks, it won't really be able to play the ad at an exact time but could get you close to that time.

**Comment by Robbt** [comment]
I am thinking this could be partially solved by #693 where at least we would have an option to insert tracks independent of the autoloading playlist but it wouldn't be tied to a specific time.

But as far as adding a new feature that would intervene and insert tracks without disturbing the schedule this is out of the scope of what we are planning to do with LibreTime at this point. LibreTime is pretty much a hard schedule broken up by different show times and so there is no flexibility in terms of allowing tracks to overflow their show boundaries. 

The idea of introducing the ability to overlay tracks with liquidsoap with mixing multiple tracks and chiming in at certain times sounds like something with exploring in the future but I don't think we are anywhere close to implementing it at this point.
