### ISSUE TITLE
Advanced Search not available in Calendar mode

### ISSUE THREAD

**Issue by jerry924** [LibreTime/libretime#350]
Libretime version: 0dd0a443f

When I am in the calendar mode and I want to add tracks to a specific show I have selected from the calendar, there is no option to perform an advanced multifield search or time range search.

![image](https://user-images.githubusercontent.com/7436317/32639299-1197cbfa-c578-11e7-9ed2-5c605d2f7df7.png)

When I am in the Tracks view, this option exists.

![image](https://user-images.githubusercontent.com/7436317/32639334-462b33a2-c578-11e7-87bc-5410574b793b.png)

I really need the advanced search when I am trying to build my show.

**Comment by hairmare** [comment]
Meh, you stumbled upon a bug in the datatables based UI parts of the frontend. I've made multiple attempts at restoring sanity in those code paths but have failed so far since the indivual parts of those pages are tightly coupled in a fashion that doesn't lead to an easy fix.

Under the hood the funtionality is there but refactoring the UI parts to do the right things seems rather elusive given the messy code underneath the calendar scheduling page.

**Comment by jerry924** [comment]
The good news is the button appears to be there. I was playing around with the CSS editor in Chrome and I actually got it to show up. Now trying to reproduce it since I didn't notice which change made it appear. I think it may just be hidden below the input box, but now trying z-index isn't doing it.

Good news is at least in chrome dev tools I got it to show up at least once!

**Comment by jerry924** [comment]
Ok, found this problem.

In CSS,  ```.panel-header{  z-index:1;  }```  is causing the Advanced Search carrot to be hidden.    

If you change ```z-index: auto;``` 

Then it shows up and functions perfectly fine.

![image](https://user-images.githubusercontent.com/7436317/32853403-0fac4c86-c9f0-11e7-8423-2c76cac703ff.png)

**Comment by jerry924** [comment]
Pull Request #359 submitted

**Comment by hairmare** [comment]
Great to see that you found the underlying issue. Thanks for the PR!

**Comment by jerry924** [comment]
This fix had the unintended consequence of not allowing the Show Dialog to be closed in Dashboard mode.  The "X" here became unclickable.

The problem here is that in Dashboard mode and in Calendar mode, the same panel-header style is used for both, and the competing z-index setting will never allow both to work together. I have a transaction where I forked the panel-header into panel-header-calendar to be used for the Calendar-mode dialog.  

This is now in my environment, but I want to spend more time testing before doing a PR.

Prior to pull request, my changes can be seen in https://github.com/jerry924/libretime/tree/issue350b_advsearch_calendermode

![issue350b](https://user-images.githubusercontent.com/7436317/33246373-a19c3706-d2c8-11e7-9b0e-ad1f546f93cb.png)

**Comment by hairmare** [comment]
I just gave your changes a quick test and they do fix the issue without introducing any noticeable side effects.

**Comment by jerry924** [comment]
I wasn't terribly happy with the fix because I had to fork the class. I will try some more to see if there is another way to simply override the class for one use of it instead before raising a pull request on this.  I can hack my way through CSS, but was hoping to find a cleaner solution.

**Comment by jerry924** [comment]
I submitted a pull request. I tried out several other things, but couldn't find a good workable solution as long as the same CSS style was used for both headers. One needs to be set to z-index 1 and one needs to be set to auto. It doesn't matter which, but they can't be the same.

**Comment by jerry924** [comment]
@hairmare  - I tried to do a pull request earlier (#408), but it seemed stuck, so I cancelled it refreshed my fork, recreated the txn and did pull request #409. It also seems hung in Travis again.   

Am I doing something wrong/any new process?

**Comment by hairmare** [comment]
Fixed in #409
