### ISSUE TITLE
Problem: Smartblocks no longer show number of files that meet the criteria

### ISSUE THREAD

**Issue by Robbt** [LibreTime/libretime#366]
This is a minor issue but one that makes it more difficult for a human to validate their smartblock form is correct while they are writing it.

Basically I've traced it down to commit b6f33f60 and the refactoring of the smartblock where the $formisvalid parameter is no longer being sent and createUpdateResonse is used instead of createFullResponse w/ the isValid parameter being passed.

**Comment by Robbt** [comment]
Ok so the problem here is that the means through which this would be updated is bypassed by the refactored way of doing things. The files meeting the criteria are part of the smart-block-criteria.phtml file and this is no longer generated touched after the initial load. 

This view is created by the function startForm in SmartBlockCriteria.php but it always takes the default parameter $p_isValid = $false. Previously this whole view would of been regenerated everytime a change was made by the createFullResponse function but the createUpdateResponse function only touches the update.phtml view  which only shows the tracks in the playlist (or smartblock). 

So there isn't an obvious simple fix here and it will require additional refactoring to reimplement this feature. Currently the display code is contained inside of the smart-block-criteria.phtml and displayed based upon the $showPoolCount variable (which is only set to true if $p_isValid is passed to the startForm.

So that's where this stands at the moment. anyone who wants to dive in and provide suggestions is welcome to do so.

**Comment by Robbt** [comment]
In the spirit of updating my issue queue before I walk away I have determined the easiest course of action would be to perform an update w/ the createUpdateResponse function by simply calling $this->view-criteriaMatch = $obj->getListofFilesMeetCriteria()['count'];
similar to the way the length is updated and other portions not directly rendered. The issue right now is that there is no field called criteriaMatch and no mechanism in place with the current setup to display or hide that field based upon valid criteria as was developed before. So that is the next step.

**Comment by Robbt** [comment]
Running into the issue that I have no idea where the $this-view-variables are set. For instance $this->view-length isn't part of the update.phtml rendered view yet it is updated by the createUpdateResponse function. When I tried to create an arbitrary variable and get it to display and change upon update it doesn't show at all. 

I tried last night to enable zfdebug and had to delete the memory and time options from it because they are no longer included in zfdebug but it doesn't show any of the variables related to the actual playlist. At one point I tried to setup a simple debugger so I could walk through the variables etc but I'm not sure how to do that with LibreTime especially considering so much happens as AJAX calls etc.

Also running echo or Logging of print_r and var_dump has been resulting in hung pages without any sort of error in my log. So I'm just reminded of how much I don't really understand Zend and the particular choices made by the previous developers and all of the legacy oddness that we have inherited in this project. This is more of a vent but @hairmare or anyone else who has advice for how to dig deeper here feel free to chime in.

**Comment by Robbt** [comment]
Ok, I think I have figured out why the length gets updated from the createUpdateResponse it is relying upon javascript to do this that has at various points sprinkled around it
  //redraw library table so the length gets updated
                dt.fnStandingRedraw();
So this gets back into datatables and the callback function of smart_blockbuilder.js is where this is called. Ok, next I peer into the guts of jquery datatables and see if I can determine how to add a criteria to this.

I was able to determine that yes indeed the poolCount methodology above is working but the $view->poolCount does only apply to update.phtml so I'm assuming javascript is necessary to update outside of this tiny part of the HTML.

**Comment by hairmare** [comment]
I'll try to give this a deeper look over the weekend. Glossing over your comments we might be able to get away with just copying some logic from `smart-block-criteria.phtml` to `update.phtml`.

I'll have to take a closer look and maybe load it into my debugger to be sure. Some of the view variables might be set from a view helper, those cases could be findable with a debugger (I usually use eclipse because I'm lazy and have enough RAM, the set up is a pain each time I need it nevertheless).

**Comment by Robbt** [comment]
Well I spent a number of hours working to get debugging working with Xdebug and I was finally successful. I'm using PhpStorm and getting it working was a little bit tricky in the first place, but once I finally got it connected with LibreTime I ran into the issue that none of the breakpoints I set under application where recognized. 

There was also an annoying amount of refreshes going on because the dashboard.js updates the UI every 50 ms or so even if there isn't a song playing. So when I was breaking at the first line of every PHP script it would basically break the UI and overwhelm my IDE with a lot of requests.

But basically what I found necessary was to go into the code and manually add the xdebug_break() function right before the line of code I wanted to debug. With a working connection to my IDE this made it possible for me to step into the program. Perhaps I'll add a write-up to the wiki. Should we maybe add xdebug to our vagrant boxes by default. Now I finally have the tools to figure untangle this further.

**Comment by hairmare** [comment]
Generally I'm +1 on the idea of adding xdebug to the vagrant box. It should probably only be added to the vagrant boxes and not to the installer script since no one should be running with xdebug on production. That folks might be running vagrant installs as production also needs considering.
