### ISSUE TITLE
Enhancement: In Add/Remove Content for a show, add next show/previous show buttons

### ISSUE THREAD

**Issue by jerry924** [LibreTime/libretime#367]
I find myself going through all of the shows in a week for a given set of updates I need to make. Either I need to shuffle songs, or remove unused tracks, update underwriting spots, etc.  The current steps to edit every show are:

1) go to Calendar
2) select the first show on Sunday at 12am and select Add/Remove Content
3) perform edits
4) close popup window
5) go back and remember where I left off and then select that hour and select Add/Remove Content again.

It would make this much more simple if there were Next Show/Previous Show buttons to move to the next and previous show in the calendar.   When I am done editing this show in step 3, I could click next show and immediately just do the edits to the next show.

<img width="658" alt="next-prev show buttons" src="https://user-images.githubusercontent.com/7436317/33163375-1cd2b3d4-cfe3-11e7-81bb-8a53946907ef.png">

Additionally, there may be a benefit to having buttons for Next Instance of this show/previous instance of this show.  This would take you to next/previous linked instance of the same show rather than the next/previous show on the calendar.  Some discussion would be needed on how to handle this if both use cases were desired to be covered.  Maybe the controls can be on different parts of the popup. The next show/previous show could be by the existing OK button.  The next instance/previous instance of this show could be near the header where the show name date and time range is shown.

<img width="634" alt="next-prev instance" src="https://user-images.githubusercontent.com/7436317/33163523-d3e23a9a-cfe3-11e7-8c0e-dec31d7235a5.png">

I am filing this to open discussion about this use case and see if there is a concensus of the usefulness of this feature.

**Comment by Robbt** [comment]
Cool, this is a good idea. Definitely better than arbitrarily extending x many hours into the future (which is what I've usually done). I'd say we should work on the Next Show/Previous Show first and maybe reserve the Next Instance for another view based upon show owners or whatever. I also think it would be more difficult to code this without a bit more code regarding identifying the focused show etc.

**Comment by hairmare** [comment]
I like this idea. Maybe the wording on the buttons should be "next show" and "previous show". When I read instance I would kind of expect it to open the next instance of the specific show. That may just be me though. 

About instances, I'm not really happy about the use of the word instance in most places where it is used. The feedback I get from non native English speakers, non IT folk is generally that they don't understand the word until they look it up. Thus I'd rather not see the word proliferate all over the UI. Right now only my Program Manager needs to understand it since most DJs wont do their own scheduling.

**Comment by jerry924** [comment]
@hairmare - agree about instance. I only used it because that was the term used already. But anything else can work as well.

The ER description above is to add two different types of controls. One to go to next/previous show in calendar and a separate set of controls to go next/previous instance of this same show only if the show was repeating.   I think both have different use cases. A program scheduler may need to update all shows, so they would go through one-by-one using Next Show.  A program scheduler may separately need to only update every instance of a single show which is the purpose for the other buttons.

I do think adding 4 more buttons can complicate things. Maybe using icons <<   and >>   near the Show details in top (my second screenshot) is used for the instance-based move.  Then the icons next to the OK button in bottom right can have the words Next Show/Previous Show as in my first screenshot.
