### ISSUE TITLE
Upgrade - Now no sound

### ISSUE THREAD

**Issue by petegriggs** [LibreTime/libretime#375]
Hello,

Got the upgrade done had a problem with stick stream entries which is now resolved. A playlist is playing and its showing "On Air" however nothing on the stream but silence. Help?!

**Comment by petegriggs** [comment]
Update to this....Webstreams work. Am going to try deleting all content and re uploading tracks.

**Comment by Robbt** [comment]
You should look at your logs, namely the /var/log/airtime/pypo/pypo.log - this is playout. Find the errors and post them here and we can help troubleshooting it.

**Comment by petegriggs** [comment]
I have blown it out and started again and now got play out. Tracks aren't registering for their full length though.

Once we get upgraded hopefully can dedicate sometime to looking at the code etc.

________________________________

**Comment by Robbt** [comment]
You need to look around on here for all of the silan stuff, it can really mess up track lengths, but there are instructions for how to work around it. I'm guessing you are using Ubuntu 14.04. check out the release notes.

**Comment by Robbt** [comment]
https://github.com/LibreTime/libretime/releases

**Comment by Robbt** [comment]
I'm going to mark this as closed and suggest that if you have further questions you post them on the [Discourse](http://discourse.libretime.org) forum since we are trying to reserve the issue queue for specific bugs.
