### ISSUE TITLE
JavaScript has a hard upload limit of 500MiB

### ISSUE THREAD

**Issue by hairmare** [LibreTime/libretime#384]
The JavaScript parts have a hard-coded upload size limit of 500 MiB when using dropzone.min.js.

The hardcoded value is in

https://github.com/LibreTime/libretime/blob/0327a750ad6a1b3a96c650cf344de058a76a1bac/airtime_mvc/public/js/airtime/library/plupload.js#L23

We should probably make this properly configurable.

**Comment by korotkov13** [comment]
I just made a clean install and I found that it not working with editing airtime_mvc/public/js/airtime/library/plupload.js file.
I guess I need also to change this parameter in airtime.conf in etc/apache2

**Comment by hairmare** [comment]
> I guess I need also to change this parameter in airtime.conf in etc/apache2

You need to change both `post_max_size` and `upload_max_filesize`. See for instance [these drupal docs](https://www.drupal.org/docs/7/managing-site-performance-and-scalability/increase-upload-size-in-your-phpini) for more details.

My change from #386 then takes care of setting up the js parts to match whats in PHP.
