### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by Audrik** [LibreTime/libretime#385]
Hello, when I put Libretime in French, the UI stay in English. Is it possible to translate Libretime? Thx

**Comment by hairmare** [comment]
Hi @Audrik 

Welcome to the community!

Most of the translations are rather dated at this point. You'll find that some parts of the UI do in fact speak french while others don't. French has a coverage of 61.91% translated strings.

If you want to help out you can work on the french translation at https://translate.zanata.org/iteration/view/libretime/master/languages/fr.

We plan on having nice documentations on how to help translate LibreTime at some point (I've been working on them as part of #301).

Cheers,
Lucas

**Comment by Robbt** [comment]
Since this is related to ongoing work for translation and there isn't a specific action for this I'm going to close this issue for now.
