### ISSUE TITLE
Support for Ubuntu snaps

### ISSUE THREAD

**Issue by HammyHavoc** [LibreTime/libretime#390]
Hey all,

Looks great, installation and maintenance looks to be a pain though. Any chance of packaging for Ubuntu snaps like RocketChat supports? Nice and simple.

**Comment by hairmare** [comment]
Apart from Canonicals [Snaps](https://snapcraft.io/) there is also [AppImage](https://appimage.org) and [Flatpak](https://flatpak.org/) to consider. With these formats I'm not quite sure where to make the cut when it comes to embedding the PostgreSQL database vs. using one already available as a Snap/AppImage/Flatpak. They all have pretty similar aims when it comes to app distribution and seem to be geared mostly at the desktop market.

In the rare moments where I get to work on actual deploy scenarios I've been focusing on single concern docker images with the aims of making it easy to run LibreTime on Kubernetes Clusters like OpenShift or in the public Clouds. So far I have found that having OS packages makes it easier to build an install that works on a fully supported stack. I'm assuming this would also apply to formats like Snap.

I also see an issue with the way our current db update scenario breaks the the built-in rollback feature in such containers. 

As far as I can tell Snaps are LXC based and Flatpak does something like docker under the hood. I haven't found the time to look into what actually packaging an app for any of these looks like recently, so I'm not even sure if my unrelated Docker efforts would be of any use for one of the formats.

That being said, we would absolutely welcome contributions to make deploying in any desktop app container solution easier/possible.
