### ISSUE TITLE
Consider moving Radio Page menu item to top right of browser UI

### ISSUE THREAD

**Issue by HammyHavoc** [LibreTime/libretime#397]
I feel that it would make a lot of sense to move the Radio Page navigation entry from the left sidebar menu to somewhere in the upper right of the browser interface.

If you consider the left sidebar as a choice of actions and configurable options in terms of UX, it then makes a lot of sense to keep passive things like the Radio Page up near the 'Listen' button that brings up a player. :- )

**Comment by Robbt** [comment]
This is an interesting proposal. There are certainly many UI/UX choices that could be improved further. Would you be interested in providing a mock-up of this and then from there someone could work on a PR to implement this modification.
