### ISSUE TITLE
Feature: Next Cue Point

### ISSUE THREAD

**Issue by benhartwich** [LibreTime/libretime#398]
Hi,

till now, there´s only a fixed crossfading possible, but at professional broadcast automation software you´ve got a next cue point, which you can set per song and indicates, when the next track in the playlist should start. 

Would it be possible to add this feature to the roadmap of libretime? I think, this would enhance the possibilities of libretime!

**Comment by hairmare** [comment]
Hi @benhartwich 

Welcome to the LibreTime community.

Right now we have silan based cue points that are automagically set. There used to be a small ui component to change these automatic cue points but it was abandoned at some point before we forked.

I did some exploratory work on restoring the feature a while ago and while most of the plumbing is still there. The editing widget/wavetable display does have some bugs that need to be fixed before the feature is usable without frustration.

If you'd like to play with it https://github.com/radiorabe/libretime/commit/e1f3249a74a0a4a1e03aad5de54d953e4ba60a2c should get you started. Most likely it would make sense to cherry-pick that commit onto a new branch based off of master and then start figuring out why the ui is broken.

Cheers,
Lucas

**Comment by benhartwich** [comment]
Hi, 

sounds good. I could help identifying problems, but I´ve got less coding skills. Could you please create a new branch for testing this? Would be easier to install / use.

**Comment by hairmare** [comment]
I rebased my oldish dev branch to a current master: https://github.com/radiorabe/libretime/tree/dev/waveform-ui. Please notify me if you build something upon it so I can refrain from further force pushing to it.

I assume it's mostly frontend based work that needs to be done to get it working. The issues I was seeing all hinged around clicks not being mapped to the right parts of the wavetable display.

**Comment by benhartwich** [comment]
I´ve installed this branch, but I can´t find any setting possibility to set the cue points. Have I to activate anything?

**Comment by benhartwich** [comment]
Is there any update on this?
