### ISSUE TITLE
Problem: Player not working [Radio Page]

### ISSUE THREAD

**Issue by SGQuar** [LibreTime/libretime#403]
Hi all.
I have a problem. Click to icon play and no start player ! .... javascript error  (TypeError: g.instance.playSound is not a function). 
![untitled](https://user-images.githubusercontent.com/16132740/34652120-a7d54d2a-f3e2-11e7-8ca2-0eb4ea9def8a.png)

Help me.

**Comment by Robbt** [comment]
It has been working on most other deployments. What browser(s) gave you the error. What distribution did you install LibreTime on, etc.

**Comment by SGQuar** [comment]
LibreTime: 3.0.0_alpha.3
Browser(s): FireFox, Chrome .... 
I tried several times to install it, and the error was left

**Comment by Robbt** [comment]
What linux distribution are you installing LibreTime on ?

**Comment by hairmare** [comment]
Also, does it work if you connect directly to the icecast server? It's usually at port 8000.

**Comment by SGQuar** [comment]
Ошибка состоит из самого браузера. 
Thank you

**Comment by SGQuar** [comment]
you can close issue ... Player not working with browser firefox

**Comment by wifiblog** [comment]
Hello,
All worked well on "Microsoft Edge 41" and "Opera" until I install Adobe Flash Player tonight, there is an error on the play button of the main page but not the player interface "listen" to the Dessou of "live".
After uninstalling "Flash Player Adobe", everything comes back normal.
I think "Flash Player" is not for nothing in this malfunction.
Hope this will help you.

PS: I am French, I use google translate to communicate.
