### ISSUE TITLE
PHP Fatal error when trying to edit a playlist

### ISSUE THREAD

**Issue by saschaludwig** [LibreTime/libretime#412]
OS: Fresh installed Ubuntu 16.04.3 LTS
LibreTime Version: dbf0a7b, installed via git clone and ./install

Steps to reproduce:
1. Open https://automation.rc5.de/showbuilder#playlists
2. select the first playlist
3. click "edit"

The XHR Post Request to https://automation.rc5.de/playlist/edit throws the following 500 error:

```[Thu Jan 18 22:08:50.939884 2018] [:error] [pid 31291] [client 78.94.176.230:52528] PHP Fatal error:  Uncaught Error: Call to undefined method Application_Model_Playlist::isStatic() in /usr/share/airtime/php/airtime_mvc/application/views/scripts/playlist/update.phtml:7\nStack trace:\n#0 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/View.php(157): include()\n#1 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/View/Abstract.php(888): Zend_View->_run('/usr/share/airt...')\n#2 /usr/share/airtime/php/airtime_mvc/application/views/scripts/playlist/playlist.phtml(71): Zend_View_Abstract->render(NULL)\n#3 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/View.php(157): include('/usr/share/airt...')\n#4 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/View/Abstract.php(888): Zend_View->_run('/usr/share/airt...')\n#5 /usr/share/airtime/php/airtime_mvc/application/controllers/PlaylistController.php(122): Zend_View_Abstract->render(NULL)\n#6 /usr/share/airtime/php/airtime_mvc/application/controllers/PlaylistController.php(229): Playlist in /usr/share/airtime/php/airtime_mvc/application/views/scripts/playlist/update.phtml on line 7, referer: https://automation.rc5.de/showbuilder```

It's just a test system, so if you need access to it just contact me.

**Comment by Robbt** [comment]
Ok, I'll check this out. I suspect this is related to my recently pushed changes to the relative date smartblock as I did something related to that isStatic function. If we had more test coverage it might be able to catch issues like this before they get pushed out.

**Comment by Robbt** [comment]
Ok, so basic mistake, a recent change tried to call a function that didn't exist for Playlists. It was a simple fix to check if an object was a block before calling the method isStatic. In briefly testing it appears that this fixes it.

**Comment by saschaludwig** [comment]
I can confirm that #413 solved the problem. Thank you very much.
