### ISSUE TITLE
Library Changes: FullCalendar Javascript

### ISSUE THREAD

**Issue by paddatrapper** [LibreTime/libretime#417]
[FullCalendar](https://fullcalendar.io/) is used to provide the calendar in LibreTime, however it has been [modified](https://github.com/LibreTime/libretime/blob/master/airtime_mvc/public/js/fullcalendar/AIRTIME_DEV_README) for LibreTime's needs.

````diff
denise@denise-DX4860:~/airtime/airtime_mvc/public/js/fullcalendar$ diff -u fullcalendar_orig.js fullcalendar.js
--- fullcalendar_orig.js	2013-10-08 16:03:35.442375219 -0400
+++ fullcalendar.js	2013-10-08 16:53:02.586338519 -0400
@@ -227,7 +227,7 @@
 	var absoluteViewElement;
 	var resizeUID = 0;
 	var ignoreWindowResize = 0;
-	var date = new Date();
+	var date = adjustDateToServerDate(new Date(), options["serverTimezoneOffset"]);
 	var events = [];
 	var _dragElement;
 	
@@ -2273,7 +2273,7 @@
 	function updateCells(firstTime) {
 		var dowDirty = firstTime || rowCnt == 1; // could the cells' day-of-weeks need updating?
 		var month = t.start.getMonth();
-		var today = clearTime(new Date());
+		var today = clearTime(adjustDateToServerDate(new Date(), opt("serverTimezoneOffset")));
 		var cell;
 		var date;
 		var row;
@@ -3106,7 +3106,7 @@
 		var headCell;
 		var bodyCell;
 		var date;
-		var today = clearTime(new Date());
+		var today = clearTime(adjustDateToServerDate(new Date(), opt("serverTimezoneOffset")));
 		for (i=0; i<colCnt; i++) {
 			date = colDate(i);
 			headCell = dayHeadCells.eq(i);
@@ -3863,7 +3863,7 @@
 				if (seg.contentTop !== undefined && height - seg.contentTop < 10) {
 					// not enough room for title, put it in the time header
 					eventElement.find('div.fc-event-time')
-						.text(formatDate(event.start, opt('timeFormat')) + ' - ' + event.title);
+						.text(formatDate(event.start, opt('timeFormat')) + ' - ' + formatDate(event.end, opt('timeFormat')) + ' ' + event.title);
 					eventElement.find('div.fc-event-title')
 						.remove();
 				}
````

In order to package LibreTime for Debian and Ubuntu, these changes need to be upstreamed, the library needs to be forked under a new name, or the dependency needs to be removed or updated. These changes are not very straight forward, as they make use of the `adjustDateToServerDate()` function which is defined in `js/airtime/common/common.js`

The related packaging issue is libretime/libretime-debian-packaging#1

**Comment by Robbt** [comment]
Yeah I agree this doesn't seem like it would be pushable upstream. So we should try to think of an alternative way to handle it or consider forking.

**Comment by Robbt** [comment]
Looking at FullCalendar.js they appear to know have some kind of timezone support - https://fullcalendar.io/docs/timezone/timezone/

Having never really looked into this fully it might make sense to try and figure this out. The only issue I can imagine with using packages is the instability brought about by API changes between different versions of a library. But I guess this will be figured out as we move towards having a version actually packaged.

**Comment by paddatrapper** [comment]
Once everything is packaged, we'll be able to ensure that specific versions of LT are bound to specific library versions because the stable releases of Debian and Ubuntu will not upgrade versions (excluding the backports repos, which are disabled by default), there will only be security patches. So if we aim to be compatible with the current versions of each, we should need only minor things changed before release in Buster or Buster+1. The libraries we use seem to be stable and so it should be fairly straightforward to keep things up to date once we are using a newer version

**Comment by paddatrapper** [comment]
Closing as wontfix as this will be replaced as part of the Vue UI implementation
