### ISSUE TITLE
Library Changes: tipsy Javascript

### ISSUE THREAD

**Issue by paddatrapper** [LibreTime/libretime#419]
[tipsy](https://github.com/jaz303/tipsy) is used to provide tooltips in LibreTime, however it has been [modified](https://github.com/LibreTime/libretime/blob/master/airtime_mvc/public/js/tipsy/AIRTIME_DEV_README) for LibreTime's needs.

````diff
denise@denise-DX4860:~/airtime/airtime_mvc/public/js/tipsy$ diff -u jquery.tipsy_orig.js jquery.tipsy.js
--- jquery.tipsy_orig.js	2012-12-13 12:03:48.780751104 -0500
+++ jquery.tipsy.js	2012-12-13 12:08:15.564761493 -0500
@@ -173,12 +173,10 @@
         
         if (!options.live) this.each(function() { get(this); });
         
-        if (options.trigger != 'manual') {
-            var binder   = options.live ? 'live' : 'bind',
-                eventIn  = options.trigger == 'hover' ? 'mouseenter' : 'focus',
-                eventOut = options.trigger == 'hover' ? 'mouseleave' : 'blur';
-            this[binder](eventIn, enter)[binder](eventOut, leave);
-        }
+        var binder   = options.live ? 'live' : 'bind',
+            eventIn  = options.trigger == 'hover' ? 'mouseenter' : 'focus',
+            eventOut = options.trigger == 'hover' ? 'mouseleave' : 'blur';
+        this[binder](eventIn, enter)[binder](eventOut, leave);
         
         return this;
````

In order to package LibreTime for Debian and Ubuntu, these changes need to be upstreamed, the library needs to be forked under a new name, or the dependency needs to be removed or updated. The upstream project is [available](https://packages.debian.org/sid/libjs-jquery-tipsy) in Debian, so the ideal case would be to ensure that we can use the pure upstream library.

The related packaging issue is libretime/libretime-debian-packaging#1

**Comment by Robbt** [comment]
Yeah, modifying Libretime to work with upstream packages would be a good idea. I think another thing that we will need to do is test LibreTime with all of the upstream packages as the codebase might be brittle enough to be dependent upon the specific version of each JS library that was included.

**Comment by paddatrapper** [comment]
Shall I create a package once the i18n is out of NEW that is installable (though not fully conformed to Debian policy) that we can use to test against the current versions of the libraries in unstable? It would also be useful to check to see if my assumptions and packaging is correct

**Comment by Robbt** [comment]
That sounds like a good idea for testing purposes.

**Comment by hairmare** [comment]
I did some testing on an old branch where I attempted parts of the js stuff. The main issue we will most likely be facing is datatables. I should probably grab my old refactor branch, back out of the datatables change and looks whats salvagable there and some of these could be squished by using bower or whatever to install heads of the css/js parts (and thus making it easier to distinguish what needs to be tackled when it comes to updating).

**Comment by hairmare** [comment]
It looks like I have some cherry picking on my todo list. I just found https://github.com/LibreTime/libretime/commit/677d8ed50b19c4aabb7c9ea918b0e0066f94489d in my last js refactor attempt.

**Comment by zklosko** [comment]
Does this still need to be fixed?

**Comment by paddatrapper** [comment]
Probably not as we are moving away from the PHP UI and all the JS that is included there. So I'll close these as wontfix, instead they will be replaced by whatever we use in the Vue UI
