### ISSUE TITLE
Binary file included in source

### ISSUE THREAD

**Issue by paddatrapper** [LibreTime/libretime#423]
[airtime_mvc/public/js/airtime/player/muses.swf](https://github.com/LibreTime/libretime/blob/master/airtime_mvc/public/js/airtime/player/muses.swf) is a binary file without an apparent source file. Is there a source available somewhere? Also is it even used? If not, it can be dropped so we don't have to bother rebuilding it

**Comment by Robbt** [comment]
Looks like it comes from https://www.muses.org/  
From their website - Muses Radio Player is an open source Web Player for audio streaming (radio over the internet).

**Comment by paddatrapper** [comment]
Muses appears to be [GPL-2+](https://www.muses.org/open-source) licensed. The GPL is incompatible with the MIT/expat license we're shipping LibreTime under. Thus we can't actually use it in any form...

**Comment by Robbt** [comment]
We aren't shipping LibreTime under MIT, it is AGPLv3, and has been since we forked from the codebase that SourceFabric switched to AGPLv3 after there SaaS drive, before it was GPL2. I think they are compatible but I'm not 100% sure. I'll investigate.

**Comment by paddatrapper** [comment]
Ah right. Packing MIT Javascript libraries has gotten me confused :)

**Comment by Robbt** [comment]
There license here(https://www.muses.org/open-source) - says -
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.

So I think we're good.

**Comment by paddatrapper** [comment]
Yup. I agree with you there. I'll add Muses to the list of stuff to package

**Comment by paddatrapper** [comment]
I'll patch this out of the packaging and close this

**Comment by hairmare** [comment]
#249 tracks getting rid of muses completely
