### ISSUE TITLE
Uploaded audio files showing half of expected duration

### ISSUE THREAD

**Issue by guythnick** [LibreTime/libretime#425]
You can see in the below screenshot that the audio file length is half of what it shows in the preview.  The actual length is correct in the preview, but the scheduler thinks it is the shorter value.  Looking at the uploaded track timestamps, this happened between 1/11 and 1/12.  I am still looking to see if there are any updates that caused this

I have confirmed this is happening with mp3s of various lengths.  However, if I upload a file that I have previously uploaded that has the correct duration, the new file is also the correct duration.  I have looked at many of the logs in /var/logs/airtime/, but can't find any noticeable error. 

Does anyone know the particular service that determines the length of a file?  Or, how it is possible that the preview shows the correct duration, and the rest of the site is showing half of that?

![wrong_duration_issue](https://user-images.githubusercontent.com/5290202/35462132-536f44a2-02b0-11e8-9e2a-45185214d114.jpg)

**Comment by guythnick** [comment]
Upon further investigation, it looks like in the cc_files table in the db, the 'length' column is correct. It is the cuein and cueout that is incorrect.

**Comment by guythnick** [comment]
Actually, reading through some of the Silian issues, it does in fact look like it got updated some how to a different version of 0.3.2.  I downgraded to 0.3.2~trusty~sfo-1 per #177 and now it is marking them correctly.

**Comment by hairmare** [comment]
An alternative fix is to upgrade to 0.3.3 as described in the the [release notes](https://github.com/LibreTime/libretime/releases). Debian testing and Ubuntu LTS also have 0.3.3 by now.

**Comment by hairmare** [comment]
Duplicate of #177
