### ISSUE TITLE
Fresh install Apache2 not enabling site

### ISSUE THREAD

**Issue by Tucker2015** [LibreTime/libretime#426]
Hi, Just done 2 installs on a VPS using Ubuntu 14.04

Everything installs fine up to the point to goto the IP address to continue setup but I find that apache2 has not got the airtime.conf in sites-available.

**Comment by Robbt** [comment]
I suspect you feel prey to the interactive script requiring case sensitivity in return to the y or n prompt when it asks if you want to create the Apache config. I should open a issue for this. Try again with ./install -fiap and see if it works.
  
  
  

  
  
  
  
  
>

**Comment by Tucker2015** [comment]
Yep I worked that one out myself.  Thanks.

**Comment by Robbt** [comment]
This was likely caused by #427, so I'm closing it and allowing that issue to stay open.
