### ISSUE TITLE
Some songs are cut short

### ISSUE THREAD

**Issue by techbp** [LibreTime/libretime#430]
Example:
a song is supposedly be played at a duration of 4:31sec, but when it's streamed it's being cut short at 2:10sec ...

Not all songs but it happens more often than not

**Comment by JohnnyC1951** [comment]
This is a common problem in Libretime and Airtime and it is due to a broken Silan program in some versions.
See the Release notes for version 3.0.0 alpha here.. [https://github.com/LibreTime/libretime/releasesA](url)  and read ALL of it. There are other pitfall fixes in it too,

**Comment by techbp** [comment]
Thanks! Checking...

**Comment by techbp** [comment]
Ok, I believe this is a Silan issue based from the link you provided. I have checked the Silan version in my server and it is **0.3.2-1build1**
I'm running an Ubuntu Trusty in the background.

Should I upgrade to 0.3.3 Silan ?

**Comment by JohnnyC1951** [comment]
If you uninstall it it will work, but you may get excess silence on the front or back of an odd track and lots of errors in the Analyser Log (so keep an eye in the size of that. Also, the 'screwed up tracks will stay screwed up as they will now have the cue points stored in them. So either delete and reimport from the panel or...... someone wrote a script to reprocess them. Search this GIT Issues for 'Silan'.

**Comment by techbp** [comment]
Thanks for your advice. I followed this https://github.com/LibreTime/libretime/issues/214
but I can't dpkg (see error):

 sudo dpkg -i silan_0.3.3~nmu1_armhf.deb
dpkg: error processing archive silan_0.3.3~nmu1_armhf.deb (--install):
 package architecture (armhf) does not match system (amd64)
Errors were encountered while processing:
 silan_0.3.3~nmu1_armhf.deb

**Comment by JohnnyC1951** [comment]
Well, it says you have an Intel/AMD Machine but are trying to install a package designed for the ARM processor. Look for a deb for AMD 64bit and it should install.

**Comment by techbp** [comment]
Thank you so much! I didn't noticed that. Now my problem is I can't install it. The package is looking for dependencies. This is the package:
https://launchpad.net/ubuntu/artful/amd64/silan/0.3.3-1

and the dependencies at the bottom of the page. I'm trying to install one by one but it fails since it's looking for dependencies. Now I'm looking for available complete package, but it seems I can't find any :-(

**Comment by JohnnyC1951** [comment]
Are you using the Airtime Repo?

**Comment by techbp** [comment]
I downloaded it from LibreTime here in github and installed it using the command ./install from command line. Oh, then that's a great news then 👍  Thanks for the letting me know

**Comment by hairmare** [comment]
@JohnnyC1951 Thanks for helping us triage issues. This is very much appreciated!

**Comment by danyjcms** [comment]
Any news on getting this fixed? Thanks!

**Comment by JohnnyC1951** [comment]
Using the 'upstream' Silan from the the Sourcefabric as described in the last release notes DOES WORK :) I have been using it for months.
The one described and put in Hairmare's repo does not install here. I get 'Not found'.

**Comment by hairmare** [comment]
Duplicate of #177
