### ISSUE TITLE
Admin request: Lets get some help from probot

### ISSUE THREAD

**Issue by hairmare** [LibreTime/libretime#434]
I'd like to activate some [probot](https://probot.github.io/) apps on this repo.

As a first step let's activate the following apps to get started.

## [WIP](https://probot.github.io/apps/wip/)
Blocks merge of PRs with WIP in title.

![wip](https://raw.githubusercontent.com/gr2m/wip-bot/master/assets/wip.gif)

## [Lock Threads](https://probot.github.io/apps/lock/)
Locks issues and prs for further edits a year after they have been closed.

![Lock Threads](https://raw.githubusercontent.com/dessant/lock-threads/master/assets/screenshot.png)

## [Invite Contributors](https://probot.github.io/apps/invite-contributors/)
Automatically invites people that got their first pull request merged to the Contributors group so they can tag issues and self assign issues.

Since the last one needs configuration I'll do a PR on it anyway, so we can discuss it's merits over there.

----

There are [more apps](https://probot.github.io/apps/) available on the probot page. If everyone is on board, I see us adding [stale](https://probot.github.io/apps/stale/), [support](https://probot.github.io/apps/support/) and [Triage New Issues](https://probot.github.io/apps/triage-new-issues/) when we are ready for them asap.

**Comment by Robbt** [comment]
This all looks good to me.

**Comment by hairmare** [comment]
WIP and Lock Threads activated, I'll close this when I do the PR for Invite Contributors.

**Comment by hairmare** [comment]
invite-contributors PR created: #436
