### ISSUE TITLE
Problem: User can't set Source for Master or Show Source under Live Broadcasting Stream Setting

### ISSUE THREAD

**Issue by Robbt** [LibreTime/libretime#44]
In addition we need to modify the code to pull some functionality from 2.5.x as this interacts with Liquidsoap configuration. 

Here are some notes from Taiga.io 
The functionality most likely uses Harbor Input via Liquidsoap to work - http://savonet.sourceforge.net/doc-svn/harbor.html

And here is the analysis from the 2.5.x code.

For instance the getters and setters in airtime_mvc/application/models/StreamSetting.php: $settings["dj_live_stream_port"] = self::getDjLiveStreamPort();

The code that was removed was the pypo python app that interfaced with liquidsoap - this function in python_apps/pypo/pypo/pypofetch.py
def regenerate_liquidsoap_conf(self, setting):
has had all functionality stripped out probably because they just have a static liquidsoap configuration for airtime.pro

The next steps is to copy the function from the airtime 2.5.2 codebase and then re-enable the forms to see if this works and troubleshoot away. Seems doable.

**Comment by hairmare** [comment]
This might also relate to #42

**Comment by hairmare** [comment]
The UI is mainly in `LiveStreamSettings` [master](https://github.com/LibreTime/libretime/blob/0f8c3b7c92496af1a59aba04b1573dacd235e0ad/airtime_mvc/application/forms/LiveStreamingPreferences.php) vs [2.5.x](https://github.com/LibreTime/libretime/blob/archive/airtime/2.5.x/airtime_mvc/application/forms/LiveStreamingPreferences.php) and the corresponding template in `form/preferences_livestream.phtml` [master](https://github.com/LibreTime/libretime/blob/0f8c3b7c92496af1a59aba04b1573dacd235e0ad/airtime_mvc/application/views/scripts/form/preferences_livestream.phtml) and [2.5.x](https://github.com/LibreTime/libretime/blob/archive/airtime/2.5.x/airtime_mvc/application/views/scripts/form/preferences_livestream.phtml). Looking at the differences there might be more underlying issues as well.

**Comment by Robbt** [comment]
This is being worked on in #84 

Things that need to be done still.

- [ ]  fix form validation of ports and mount points 
- [ ] validate liquidsoap reconfiguration function works properly
- [ ] strip out or reinstate source URL override functionality

- [ ] 

- [ ]

**Comment by Robbt** [comment]
This was fixed with #84. There is still room for improvement with the validation causing page reloads immediately after some errors are displayed but the whole thing was handled via an AJAX call vs. a typical form submission so this was part of the issue.
