### ISSUE TITLE
Extending the Libre Weekly Widget. A working suggestion.

### ISSUE THREAD

**Issue by JohnnyC1951** [LibreTime/libretime#440]
A suggestion and example slot-in replacement. It adds the use of the 'Show Description', 'Show Logo',  'Show URL' and I added the timezone (mostly to smooth-over Americans).
Simply replace this: '/usr/share/airtime/php/airtime_mvc/application/views/scripts/embed/weekly-program.phtml' with the file in the zip. That's it. Tested with 3.0.0-alpha.4. As is, it uses show logos of 80px by 80px.
See it working here: [http://deprogrammedradio.com](url) and here [https://x-pedia.org](url)

![screenshot-extended-widget](https://user-images.githubusercontent.com/33095908/36047171-35163a8c-0dd3-11e8-9e4a-5b678d9785d2.jpg)
![screenshot-extended-widget2](https://user-images.githubusercontent.com/33095908/36047177-380adc0c-0dd3-11e8-8786-77b4d9ba3b8c.jpg)
[weekly-program.phtml.zip](https://github.com/LibreTime/libretime/files/1712253/weekly-program.phtml.zip)

**Comment by Robbt** [comment]
Cool, would you mind converting this to a pull request so we can merge it and give you credit as a contributor. I think that it would make a big improvement over what we have now. I always wondered what the purpose of adding logos and descriptions was if they aren't used anywhere.

**Comment by JohnnyC1951** [comment]
Since yesterday, I made the date bar static. Much better, I think. It doesn't disappear.

**Comment by Robbt** [comment]
Cool, this doesn't seem that complex. I think we could merge a pull request for this. You'd just need to do it via git. If you don't want to go through the trouble of doing that I could use what you have here and make it happen, but I think it would be cool if you were able to contribute it.

But yeah to do it via git there are a few steps. First you just need to fork the LibreTime repo (via the web interface).

Then if you had cloned LibreTime via ` git clone https://github.com/LibreTime/libretime.git`
You just need to add your remote repo for your fork.


git remote add name URL

then finally once you've made the file change
git checkout -b feature/changed-weekly-program

git add airtime-mvc/filename.phtml
git commit -m 'your log message'
then 
git push remotename feature/changed-weekly-program 
it should ask for your login and it will then go onto your fork

then the github UI will ask you if you want to open a PR for your branch and you can submit the PR

Now that I type it out it is far amount of additional steps beyond just posting a simple phtml file as an attachment but it is useful for larger changes and it's fun to see who has contributed code to the codebase over the years.

We could also probably figure out a way to pull Show Genre from the DB as well.
I know this change will be useful for my station.

Now I just need to figure out a way to mirror the widgets so our on-site physical stream isn't made accessible via the web but we can get the information from our schedule out to our web stream etc.

But yeah to do it via git there are a few steps. First you just need to fork the LibreTime repo (via the web interface).

Then if you had cloned LibreTime via ` git clone https://github.com/LibreTime/libretime.git`
You just need to add your remote repo for your fork.


git remote add name URL

then finally once you've made the file change
git checkout -b feature/changed-weekly-program

git add airtime-mvc/filename.phtml
git commit -m 'your log message'
then 
git push remotename feature/changed-weekly-program 
it should ask for your login and it will then go onto your fork

then the github UI will ask you if you want to open a PR for your branch and you can submit the PR

Now that I type it out it is far amount of additional steps beyond just posting a simple phtml file as an attachment but it is useful for larger changes and it's fun to see who has contributed code to the codebase over the years.

We could also probably figure out a way to pull Show Genre from the DB as well.
I know this change will be useful for my station.

Now I just need to figure out a way to mirror the widgets so our on-site physical stream isn't made accessible via the web but we can get the information from our schedule out to our web stream etc.

**Comment by JohnnyC1951** [comment]
Pull req done.
In a website iframe, the date header is now static while the content scrolls. I made the current show flip its image from right to left and is highlit stands out more, I feel. Got rid of the annoying loading 'flash' and removed a page error (character-set not defined) while I was in there. If we could get the data as an std json feed instead of embedded in the page, we could do more like soft refreshes etc. Actually I could do more from the API, like I did in AT Hacks :\

**Comment by JohnnyC1951** [comment]
Updated version.
[weekly-program.phtml.zip](https://github.com/LibreTime/libretime/files/1714691/weekly-program.phtml.zip)

**Comment by adamburnsuk** [comment]
Hey JohnnyC....I used your weekly widget and it works great.  Since you have already been playing around with the widget I was wondering if you have noticed that it switches days when it hits  12am UTC...no matter what time you have server or Libretime set to.  I'm still trying to learn php and zend framework to try to fix this, but since you're already familiar with the widget, I was wondering if you had noticed it?  There is already an issue logged for this, but noone has figured out how to solve it yet.  It's issue 401.    :)

https://github.com/LibreTime/libretime/issues/401

**Comment by JohnnyC1951** [comment]
Hmmm
I answered this last night with a new version & screenshots. and a another comment following that. They have vanished or went somewhere else

**Comment by JohnnyC1951** [comment]
Found it. You had double posted. The reply is in [](https://github.com/LibreTime/libretime/issues/401)

**Comment by JohnnyC1951** [comment]
Latest time corrected weekly schedule widget http://deprogrammedradio.com/images/schedule.jpg
<img style="width:100%" src='http://deprogrammedradio.com/images/schedule.jpg'>

**Comment by JohnnyC1951** [comment]
NOTE: This is optimized for 100px x 100px show images. but it is displaying my 80px x 80px  ones, so it is a bit blurred.

Here is an Alpha. Live site here [http://www.deprogrammedradio.com/](http://www.deprogrammedradio.com/) and here [https://x-pedia.org/new-widget/weekly-program.phtml](https://x-pedia.org/new-widget/weekly-program.phtml) and here [https://x-pedia.org/](https://x-pedia.org/) Note: Every one is a bit different but it is the same file, I am expecting bug reports, so expect it to limp - but if so we can fix it. Read.me inside.
[http://deprogrammedradio.com//downloads/new-widget.tar.gz](http://deprogrammedradio.com//downloads/new-widget.tar.gz)

When we have confirmed it works, we can see about getting it added, or not. This is all my original code. LT users are free to use it, 'as is'.
