### ISSUE TITLE
Why my station is offline

### ISSUE THREAD

**Issue by tuktukvlad** [LibreTime/libretime#441]
Hello!
Everything worked perfectly! But today with this problem, the broadcast stopped but the program was planned. I tried manually cancel it and create a new program, added a playlist to it, but the icecast was offline. The server reboot helped. What could be the problem?
Thanks for answers!
![default](https://user-images.githubusercontent.com/22128719/36062515-5b5067b6-0e7f-11e8-96db-24d2834cdac0.PNG)
![2](https://user-images.githubusercontent.com/22128719/36062518-5e3547da-0e7f-11e8-9a7b-1edc872e7b66.PNG)
![3](https://user-images.githubusercontent.com/22128719/36062534-b9cbb318-0e7f-11e8-901f-68deb927be0c.PNG)

**Comment by Robbt** [comment]
I would try restarting the airtime-liquidsoap and airtime-celery services.
I've noticed sometimes that the check mark isn't always a reliable indicator that everything is working.
I'm not sure if this [troubleshooting page](http://libretime.org/manual/troubleshooting/) needs updating w/ the proper commands, to a degree it depends upon what distribution you are using.

Also check your /var/log/airtime/airtime-celery.log or any other logs in there for possible errors that could explain this.

Hope this is helpful, let us know if you are able to figure it out.

**Comment by JohnnyC1951** [comment]
A 'Restart Everything' button would be useful on the status page.

**Comment by Robbt** [comment]
This would be a good idea, I'm not sure how it would work with the permissions required to restart a service though. 

We would need to give the apache user access to restart the services which come with security issues. 

At the very least a link to a command line script that could be ran as root would be helpful.

**Comment by hairmare** [comment]
AFAICT the offline message could also indicate something wrong with the pypo subsystem and might have been fixable with restarting the airtime-playout service, celery isn't usually involved in this error. @tuktukvlad do you have any log files left from before the reboot? `/var/log/airtime` usually contains some info in the playout/pypo and liquidsoap logs as to what's going on.

**Comment by tuktukvlad** [comment]
It happened around 16:05
I do not really understand the log files, this is ls_script.log and pypo.log
![ls_scrip](https://user-images.githubusercontent.com/22128719/36076483-bbba4e52-0f6d-11e8-9261-9135e2d8749a.PNG)
![pypo](https://user-images.githubusercontent.com/22128719/36076484-be014044-0f6d-11e8-9120-c1ed63ef26ab.PNG)

**Comment by hairmare** [comment]
The pypo log indicates that it tried to play a jingle as the first track in the show starting 16:05. The ls_script.log indicates that the pypo parts stopped scheduling show for the liquidsoap playout to play.

Assuming that jingle usually works, was there anything in the log right after the excerpt you posted? It looks like the exact moment pypo stopped working is missing from the file (it should come right after the last line in the screenshot).

**Comment by tuktukvlad** [comment]
When playing the jingle, the icecast was already offline and there was silence. In libretime, everything was fine, the program was playing. Here are these parts of log files
[ls_script.log](https://github.com/LibreTime/libretime/files/1714731/ls_script.log)
[pypo.log](https://github.com/LibreTime/libretime/files/1714732/pypo.log)

**Comment by hairmare** [comment]
There are a bunch of 500 errors in the pypo.log. 

```
2018-02-10 16:05:01,133 [pypofile] [ERROR]  <Response [500]>
2018-02-10 16:05:01,133 [pypofile] [ERROR]  Could not copy from http://admin.minsk-house.by/rest/media/2 to /var/tmp/airtime/pypo/cache/scheduler/2.mp3
2018-02-10 16:05:01,134 [pypofile] [ERROR]  500 - Error occurred downloading file
```

Please post the zendphp.log, it might contain at as to what is going on there.

**Comment by tuktukvlad** [comment]
[zendlog.log](https://github.com/LibreTime/libretime/files/1714782/zendlog.log)

**Comment by hairmare** [comment]
Having a gap between two shows would make it so that nothing is in that minute. It doesn't explain why it didn't resume playout at 16:05.

In the zend logs there seems to be an issue that correlates with the pypofile errors from before:
```
2018-02-10T16:05:01+03:00 ERR (3): admin.minsk-house.by [ErrorController.php:26 - errorAction()] - Incorrect API key
2018-02-10T16:05:01+03:00 ERR (3): admin.minsk-house.by [ErrorController.php:27 - errorAction()] - #0 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Plugin/Broker.php(309): Zend_Controller_Plugin_Acl->preDispatch(Object(Zend_Controller_Request_Http))
#1 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(941): Zend_Controller_Plugin_Broker->preDispatch(Object(Zend_Controller_Request_Http))
#2 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#3 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#4 /usr/share/airtime/php/airtime_mvc/application/airtime-boot.php(84): Zend_Application->run()
#5 /usr/share/airtime/php/airtime_mvc/public/index.php(68): require_once('/usr/share/airt...')
#6 {main}
2018-02-10T16:05:01+03:00 ERR (3): admin.minsk-house.by [ErrorController.php:54 - errorAction()] - Произошла внутренняя ошибка.: Zend_Controller_Exception: Incorrect API key in /usr/share/airtime/php/airtime_mvc/application/controllers/plugins/Acl_plugin.php:142
Stack trace:
#0 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Plugin/Broker.php(309): Zend_Controller_Plugin_Acl->preDispatch(Object(Zend_Controller_Request_Http))
#1 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(941): Zend_Controller_Plugin_Broker->preDispatch(Object(Zend_Controller_Request_Http))
#2 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#3 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#4 /usr/share/airtime/php/airtime_mvc/application/airtime-boot.php(84): Zend_Application->run()
#5 /usr/share/airtime/php/airtime_mvc/public/index.php(68): require_once('/usr/share/airt...')
#6 {main}
```
I don't have an explanation as to what would be causing such an `Incorrect API key` error. Did you update to 3.0.0-alpha.4 lately? If so did you restart after the update?

**Comment by tuktukvlad** [comment]
The latest version is installed ... It was installed on a clean server Ubuntu 16.04. After that, there were a few reboots, there were no updates.

**Comment by tarkank** [comment]
Had exactly the same issue as @tuktukvlad had just right now on my stream. I ran a test playlist a couple of days ago when I first installed LT and had no issues. Today I added another schedule for the same playlist and it didn't work until I hit the save button without changing anything on the settings section and it started playing automatically.

**Comment by phoenixqss** [comment]
hello everyone! I have the same problem. how can I fix this?

**Comment by paddatrapper** [comment]
@phoenixqss please create a discord post/new issue with all the details and relevant log files

**Comment by zklosko** [comment]
I'd like to close this since the issue is over three years old and a number of changes have occurred at both the OS level and within our codebase. @tuktukvlad have you still been having this issue? Have you upgraded since?
