### ISSUE TITLE
Problem: airtime-celery.log is not being created

### ISSUE THREAD

**Issue by Robbt** [libretime/libretime#442]
I thought that we had changed this but it doesn't appear to be the case.
The issue is that the airtime-celery worker is not creating a log in /var/log/airtime-celery.log

I know that I had enabled this and it might be a simple modification required for the airtime-celery python app.

Newer installs of LibreTime don't include the logfile for the celery worker.

For instance here is the process list /usr/bin/python -m celery worker --time-limit=6000 --concurrency=1 --config=celeryconfig --app=airtime-celery.tasks:celery --loglevel=DEBUG --logfile=/var/log/airtime/airtime-celery.log --pidfile=/var/run/celery/airtime-celery.pid --hostname=airtime-celery@transmitter

Vs. one on a vagrant box
/usr/bin/python /usr/local/bin/celery worker -A airtime-celery.tasks:celery --time-limit=300 --concurrency=1 --config=celeryconfig -l INFO

**Comment by Robbt** [comment]
Maybe someone with python expertise can figure out why we aren't creating logs for airtime-celery.log on most installations. This would help troubleshooting sometimes.

**Comment by paddatrapper** [comment]
Could be file permissions or something in the celery code

**Comment by Robbt** [comment]
This needs further testing and shouldn't be left to go stale.

**Comment by rocknowradio** [comment]
This is also happens to me.

System:
`root@s1:/var/log/airtime# uname -a
Linux s1 4.15.0-142-generic #146-Ubuntu SMP Tue Apr 13 01:11:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
root@s1:/var/log/airtime# cat /usr/share/airtime/php/VERSION
cf75b14e2
`

/var/log/airtime content:
`root@s1:/var/log/airtime# ls -l /var/log/airtime
total 4328
-rw-r--r-- 1 www-data www-data   19191 Jul 26 22:53 airtime_analyzer.log
-rw-r--r-- 1 www-data www-data  208400 Aug 18 08:05 api.log
drwxrwxr-x 2 www-data www-data    4096 Aug 16 02:23 pypo
drwxrwxr-x 2 www-data www-data    4096 Aug 18 08:14 pypo-liquidsoap
-rw-r--r-- 1 www-data www-data  794217 Aug 18 09:01 zendphp.log
-rw-r--r-- 1 www-data www-data   36347 Aug 10 06:22 zendphp.log.1.gz
-rw-r--r-- 1 www-data www-data 3088925 Jul 26 23:29 zendphp.log.2
-rw-r--r-- 1 www-data www-data   23774 Jul 30 19:14 zendphp.log.2.gz
-rw-r--r-- 1 www-data www-data   44708 Jul 30 06:24 zendphp.log.3.gz
-rw-r--r-- 1 www-data www-data   42364 Jul 29 06:23 zendphp.log.4.gz
-rw-r--r-- 1 www-data www-data   51699 Jul 28 06:24 zendphp.log.5.gz
-rw-r--r-- 1 www-data www-data   14257 Jul 27 06:23 zendphp.log.6.gz
-rw-r--r-- 1 www-data www-data   69471 Jul 26 06:23 zendphp.log.7.gz
`
Running celery instances:
`root@s1:/var/log/airtime# ps aux | grep celery
celery    9134  0.0  0.5 120140 40372 ?        Ss   Jul30  23:12 /usr/bin/python3 /usr/local/bin/celery worker -A airtime-celery.tasks:celery --time-limit=1800 --concurrency=1 --config=celeryconfig -l INFO
celery    9143  0.0  0.4 119452 34376 ?        S    Jul30   0:00 /usr/bin/python3 /usr/local/bin/celery worker -A airtime-celery.tasks:celery --time-limit=1800 --concurrency=1 --config=celeryconfig -l INFO
`
As comment 1 says, there is no --loglevel or --logfile.

I would modify myself into the source code - although an absolute beginnner in LT code -- only I'm not 100% sure where exactly.

Checking out the source code as of today, I see:
/python_apps/airtime-celery/install/upstart/libretime-celery.conf 
`exec celery worker -A airtime-celery.tasks:celery --time-limit=300 --concurrency=1 --config=celeryconfig -l INFO`
/python_apps/airtime-celery/install/systemd/libretime-celery.service
`ExecStart=/usr/local/bin/celery worker -A airtime-celery.tasks:celery --time-limit=1800 --concurrency=1 --config=celeryconfig -l INFO`
(which matches my instances command line).

Also I see in /python_apps/airtime-celery/install/initd/libretime-celery that
`DEFAULT_USER="celery"
DEFAULT_PID_FILE="/var/run/celery/%n.pid"
DEFAULT_LOG_FILE="/var/log/celery/%n.log"
DEFAULT_LOG_LEVEL="INFO"
DEFAULT_NODES="celery" `
which surely indicates the logging intention, I think.

/etc/systemd/system/libretime-celery.service:
`root@s1:/var/log/airtime# cat /etc/systemd/system/libretime-celery.service
[Unit]
Description=LibreTime Celery Service
After=network.target

[Service]
User=celery
Group=celery
Environment=RMQ_CONFIG_FILE=/etc/airtime/airtime.conf
WorkingDirectory=/srv/airtime
ExecStart=/usr/local/bin/celery worker -A airtime-celery.tasks:celery --time-limit=1800 --concurrency=1 --config=celeryconfig -l INFO
Restart=always

[Install]
WantedBy=multi-user.target
`

I guess my question is this: besides reconfiguring libretime-celery service by hand, is there a setting/config file/script/set of commands that would allow libretime-celery logging enabled?

**Comment by jooola** [comment]
This has been fixed
