### ISSUE TITLE
Automatic Playlist Returns Blank Playlist

### ISSUE THREAD

**Issue by techbp** [LibreTime/libretime#451]
I have an existing playlist (filled with audios) and I want to automate it on schedule to run for 3 hours or so. So I set this up with Automatic Playlist and select an existing playlist BUT the playlist is blank after adding it as Automatic Playlist. 

Supposedly it's not blank right? Or did I miss anything?

btw i downloaded the latest version here...

**Comment by hairmare** [comment]
Automatic Playlists get populated roughly half an hour before the show starts. Are you taking that into account? Does the show show up with this icon ![autoplaylist_icon](https://raw.githubusercontent.com/Robbt/libretime/968dcfa6adcda0fe8b2fb7becc4c7419e4b9fa70/airtime_mvc/public/css/images/icon_alert_cal_autoplaylist.png "Icon")?

**Comment by techbp** [comment]
Yes that "A" icon shows. Hmm, so that's how it works? It should be under "In the Future"? Cause I tested it under "Now".

**Comment by Robbt** [comment]
If you want to schedule it for now you can just drag the playlist into the show listing under dashboard. Automatic playlist is setup to enable playlists to be built in the future based upon changing items in your database, ie a new podcast has been downloaded and scheduled.

**Comment by techbp** [comment]
Oh yeah, that makes sense. Thank you!
