### ISSUE TITLE
Problem: Facebook Widget does not work (needs app ID setting)

### ISSUE THREAD

**Issue by Robbt** [LibreTime/libretime#452]
We have a facebook widget radio player but it doesn't work at this point because I think it doesn't have an appropriate app ID. We need to document how to modify this and make it so people can update the radioplayer w/ an app ID as I don't think we want to handle this like the SaaS version did w/ a singular ID controlled by SourceFabric.

**Comment by hairmare** [comment]
The settings are in the config, some docs on how to set this up would indeed be nice.

https://github.com/LibreTime/libretime/blob/efe0aefddcf8d3616797259e3a6a2c583f2461b9/airtime_mvc/build/airtime.example.conf#L321-L329

I would also assume that the feature needs some testing as facebook might have evolved their APIs since this was integrated. Do we know if anyone has tried setting this up so far?

**Comment by Robbt** [comment]
Ok, yeah I thought it might be in there but didn't look, there is no reason why we couldn't put a form to change it in the administrative UI. Testing and documentation are definitely needed.

**Comment by JohnnyC1951** [comment]
I made my own FB app (I have quite a few). It is really just filling out a form, getting verified and they give you an App ID. Took just a few minutes and you will need an https green padlock server to do anything interesting. I guess ATP Pro being hosted on SF has a single APP ID, which simplifies things for them. I had it working, but then I made my own Twitter & FB bots which do more.

**Comment by Robbt** [comment]
I'm nearly 100% sure this doesn't work because Airtime.Pro made an announcement about all the work they did to refactor their facebook widget to work again with the new facebook API. So I suggest that we either fix this or remove it before we release the beta as there is no sense in having a broken feature included by default.

**Comment by Robbt** [comment]
A useful contribution would be to test this and if it doesn't work and isn't easily fixable to put together a PR to remove this from the widget menu.
