### ISSUE TITLE
FTP accounts for each DJ then pipeline that to their playlist.

### ISSUE THREAD

**Issue by sevenelevendj** [LibreTime/libretime#453]
Hey guys,
I've been trying to find a solution to this but can't figure it out. Is there some way to accomplish this? Basically I would like todo what the Title says. To avoid the DJ's to get access to the playlists, download tracks that are not theirs, etc. Any help would be much appreciated.

**Comment by Robbt** [comment]
For this to happen you will need to write code. There has been some work done for this on #111 but that would only bring the tracks in. The bigger issue here is that there is no isolation between specific DJs libraries and other libraries.

**Comment by sevenelevendj** [comment]
Oh well then, I seem to be in a lot of trouble then. Seems to be impossible to achieve for me, and it's an essential workflow for my station to be able to operate properly. I need to find a solution, If anyone has any advise I would greatly appreciate it.

**Comment by Robbt** [comment]
Well, it is definitely achievable with some development work. I'm assuming that you don't have any programmers on your team at this point. I have been meaning to prioritize work on the FTP based import but I've not had it rise above the other competing interests in my life. 

The way my station achieves a similar workflow for people unable to upload directly to LibreTime and schedule their show is we have RSS feeds from our website and we subscribe to each show via the Podcast feature on LibreTime. This has an automatically updated smartblock which schedules their show each week (if they upload a new one). They upload their shows to our website via FTP and import them via a web interface. The whole process is more cumbersome than it should be and it is relying upon an outdated version of Drupal, but it works for them.

Why can't they upload their shows directly to LibreTime via the website with an individualized login for each producer. 

The other part of your request is to prevent DJs from viewing other peoples tracks/playlists etc. This is something that we could code by making the Library filter to only show tracks where the user is the Owner. I think this could be done without too much code but the javascript library we are using is hacked together and I haven't spent the time to really figure out how to implement this. I do think that even if they can see other DJs tracks they can't edit them.

**Comment by sevenelevendj** [comment]
I don't mind them seeing tracks that are not theirs, the issue here is that they are able to download anything! :/ I will have to work on that then I guess. Thing is I'm not very good with  php. In fact I had to deal with php by starting working with librecast along with wordpress (later being just too easy), now this is some challenge. Also I don't have too much experience working with linux systems. Anyways I thought there wasn't a solution at all. I misunderstood your earlier comment. Now you gave me hope to play with the code. I just need them to not be able to download anything that is not theirs. That would be it. I really appreciate your input btw.

**Comment by sevenelevendj** [comment]
Well that was pretty easy I guess. Maybe I should ask for a revision? I believe dj's shouldnt be allowed to download tracks that are not theirs.

**Comment by Robbt** [comment]
Well implementing not downloading other DJs tracks would be tricky if you aren't familiar with PHP and the various components LibreTime was built in. I'm not sure if this is a blocker for you but you could implement a feature request or if you are able to code an easy way to do this and administrative UI to allow people to turn it on or off you could do a pull request.

**Comment by sevenelevendj** [comment]
Now a DJ can only see the preview option instead of seeing preview and download. Feels good to have my first official steps with php. Thank you ! It was something really easy but feels good. hehe

**Comment by Robbt** [comment]
Cool glad you were able to figure out a way to hack it to make it work for your station.

**Comment by sevenelevendj** [comment]
I will definitely try to help implementing what you suggest. Also I believe I can do more stuff related to tighten the a little bit more the limits regarding DJ roles.
