### ISSUE TITLE
Possibility to do webstreams (relay) ....

### ISSUE THREAD

**Issue by tgd1973** [LibreTime/libretime#455]
Hello ! When there is nothing programmed, then in the calendar everything is empty at a certain date, I would like to have the possibility to start a link , automatically to another webradio (webstreams)  as protection against silence.
Possible? 
How is it done?

**Comment by Robbt** [comment]
This would have to be done with a custom Liquidsoap configuration at this point. But you could also setup an an automatic playlist that contains a webstream equal to the content of the show and then program everything you want to play above it. It will play what you manually schedule and if you forget to schedule it will play the webstream. Not an ideal setup but a possible way of doing this.

**Comment by tgd1973** [comment]
Can you tell me which file to modify to make the change with liquidap?

**Comment by Robbt** [comment]
This is related to issue #229 (no documented easy way to customize liquidsoap files) and so while you can edit the liquidsoap file that airtime-liquidsoap links to it wouldn't necessarily be easy to upgrade. As far as the specifics of how to get liquidsoap to work like this you'd need to check out the liquidsoap documentation here's a link - http://liquidsoap.info/doc-dev/blank.html - I haven't personally spent a lot of time playing with liquidsoap.

**Comment by tgd1973** [comment]
Can tell me someone where the file  ls_script.liq    is? i hava a debian install ...
here there is no more ...
/usr/lib/airtime/pypo/bin/liquidsoap_scripts/ls_script.liq

I do not understand why there must be someone who likes to make all these changes but without writing a DOC ...

In git the path is this but I do not understand where it ends up in the debian installation ...
libretime/python_apps/pypo/liquidsoap/ls_script.liq

Thanks.

**Comment by tgd1973** [comment]
Nobody knows how to answer where these file are?   ls_script.liq  on debian ?

**Comment by Robbt** [comment]
Sorry for the delay, it is in /usr/local/lib/python2.7/dist-packages/airtime_playout-1.0-py2.7.egg/liquidsoap/ls_script.liq after the installation.
If you override it and the install a new version of the package it will overwrite it, so you may want to simply modify and reinstall the python package.

**Comment by tgd1973** [comment]
For the moment , I've been able to edit the 
`/usr/local/lib/python2.7/dist-packages/airtime_playout-1.0-py2.7.egg/liquidsoap/**ls_script.liq**` 
file so that I can receive an external stream when ofline so I do not have to always have something in the calendar ... in this way must only have to program the events ... reception on the external streaming when there is nothing in the program, in this way also doing anti silence.
The changes to be made directly inside the file  **ls_script.liq** are these:
`# original code commented out`
`#default = amplify(id="silence_src", 0.00001, noise())`
`# Play RADIO when is OffLine: Mountpoint`
`default = input.http(id="web_stream", autostart=true, buffer=0.5, max=20., "http://192.168.0.18:8110/autodj.mp3")`
`ref_off_air_meta = ref off_air_meta`
`if !ref_off_air_meta == "" then`
`    ref_off_air_meta := "LibreTime - offline"`
`end`
`#default = rewrite_metadata([("title", !ref_off_air_meta)], default)`
`ignore(output.dummy(default, fallible=true))`

It would be much more convenient if there was the possibility to insert the address of the streaming in a menu of the type as explained in the post #229 :

https://user-images.githubusercontent.com/1733884/28263752-462efd10-6ae8-11e7-862f-29fb6c45df91.png

**Comment by Robbt** [comment]
Well you are more than welcome to work on a PR for this functionality. It's just a matter of playing around with the Zend MVC templates and integrating the work you did above. Thanks for sharing your solution.
