### ISSUE TITLE
more or less items in smart block then defined

### ISSUE THREAD

**Issue by Liberator1967** [LibreTime/libretime#459]
I've created two smart blocks.
One picks randomly a jingle of a pool of jingles (works fine).
The other one picks randomly 5 items from a pool of songs (works fine).
Then I've created a plalist with the scheme : SB1, SB2, SB1, SB2, SB1, SB2 etc.
I repeated this play list a couple of times in a show.

I would expect 1 jingle, 5 songs, 1 jingle, 5 songs etc...
But, what I really get is : 1 jingle, 5 songs, 1 jingle, 7 songs, 1 jingle 3 songs etc.
This really drives me crazy cause I'm absolutely sure I've defined the right smart blocks.

**Comment by Robbt** [comment]
Can you provide an example of the exact contents of the smartblock ?
It is hard to duplicate some of these smartblock errors.

**Comment by Liberator1967** [comment]
Thanks for your quick response Robbt,
I attached the screens of the two smart blocks, the play list and the result (view of scheduled show).
All files are tagged in the copyright-field to make the distinction between jingles and regular songs.
The play list starts with two songs, followed by repeating groups of SB1, SB2, SB1, SB2 etc.

In the result-screen the jingles are the ones with the hash-sign in the title.
You can see that there are 7 songs between the two jingles ' rustig bedje....' and '17. Palermo...'.
It's dutch but you I'm sure you can see it...
I'm absolutely sure the smart blocks are correct.
Another strange thing....it seems no random fault, there is a pattern in it.

![sb 2](https://user-images.githubusercontent.com/36259379/37047932-c02c1f90-216c-11e8-84e9-dc2e49aab3a1.png)
![result](https://user-images.githubusercontent.com/36259379/37047933-c04d09bc-216c-11e8-87d1-f04135d3afba.png)
![sb 1](https://user-images.githubusercontent.com/36259379/37047934-c06976f6-216c-11e8-861f-8d1441838d43.png)
![play list](https://user-images.githubusercontent.com/36259379/37048468-469114e0-216e-11e8-913a-44da588608db.png)

**Comment by Robbt** [comment]
Thanks for sharing the screen shots. I'll try to recreate something on a test server. Without being able to step through the code while it's doing this I'n not sure how easy it will be to trace down this bug.

**Comment by JohnnyC1951** [comment]
My first thought is some embedded language issue.
The admin  pages are displayed and entered in utf8 but, your copyright fields may possibly be in some other code like ISO 8859 from your tagging software. Therefore, although the terms of interest may LOOK identical, in raw code they may not be and you may be getting unexpected results. I get issues like this with Spanish, ESPECIALLY when there are accented characters and HTML entities like $ £ > < and &nbsp;. I hope this helps.

**Comment by Robbt** [comment]
So as I was digging around in the code that converts playlists containing smartblocks to items I am wondering if there isn't something occurring here where they are getting out of order. I haven't tried to duplicate it exactly but I think the error could lie with the retrieveMediaFiles part of the Scheduler.php model.
https://github.com/LibreTime/libretime/blob/be5222d3a23f739b84326f445f1e4ecf1087110f/airtime_mvc/application/models/Scheduler.php#L245-L312
