### ISSUE TITLE
Ubuntu 14.04 with default installation as documented, Icecast missing metatagging

### ISSUE THREAD

**Issue by Power2All** [LibreTime/libretime#460]
Hi,

I installed LibreTime default as is requested in the documentation here:
http://libretime.org

All is fine, installation went nice, all works, streaming works.
Only problem is, is that metatags aren't sent to Icecast server, so it will always keep saying "Unknown" as song title, both on icecast itself, as well as in my player like Foobar2000.
Something looks to be wrong when it comes to sending tags ?
The website itself shows the name of the tune, although not properly, but the website itself grabs the info from Libretime itself, however, metatagging is bugged right now.

Anybody has a solution to fix it ?

![image](https://user-images.githubusercontent.com/2010549/37028408-74c94fec-2134-11e8-975d-cabc6328ae29.png)

![image](https://user-images.githubusercontent.com/2010549/37028461-954039b6-2134-11e8-9267-752a5dbcdfb8.png)

![image](https://user-images.githubusercontent.com/2010549/37028482-a4d9eb9c-2134-11e8-8912-f55ed15caa83.png)

**Comment by Power2All** [comment]
Found a possible solution.
Currently testing it out:

https://github.com/savonet/liquidsoap/issues/418

This is a pure Liquidsoap issue, where the vorbis code is the problem.
Compiling Liquidsoap 1.1.1 now from scratch with the following patches applied:

https://github.com/savonet/liquidsoap/files/880893/0001-tags-allows-any-tag.txt
https://github.com/savonet/liquidsoap/files/880889/0001-use-list-version-of-Vorbis.tags.txt

If this works, and solves my problem, I'll post instructions for others how to apply this.

**Comment by Power2All** [comment]
Alright, patches applied, all compiled and installed (used liquidsoap 1.1.1 and PACKAGES.default to compile).
Now installing LibreTime ones more from scratch, and apply then again liquidsoap, mine version, and then see how it goes.

**Comment by hairmare** [comment]
This is probably due to liquidsoap distro packages being broken. You might want to consider early adopting liquidsoap 1.3 as per #192. Compiling your own 1.1.1 should also work.

**Comment by Power2All** [comment]
Bugged

```
root@stream:~/libretime# liquidsoap --debug /usr/local/lib/python2.7/dist-packages/airtime_playout-1.0-py2.7.egg/liquidsoap/ls_script.liq
Error: expected an encoding format after %ifencoder!

```

**Comment by Power2All** [comment]
I tried Liquidsoap 1.2.1, which was a little less new.
Sadly, this showed the same issue as 1.1.1 did.
Showing the program on the website, but not on the icecast metatag.\
Stays UNKNOWN for some reason.

**Comment by Power2All** [comment]
Applied patches for Liquidsoap 1.2.1.
Unknown is gone now, but it's empty.
Seems the liquidsoap script is not sending the metadata as it should.
If there is no immediate solution for this, I might need to modify the ls_script myself to execute a META change to the icecast server itself, which is rather ugly, and want to avoid.

**Comment by Power2All** [comment]
Problem found, issue can be solved.
I just noticed, metatagging works fine with MP3 streaming.
With OGG you need to enable a function:

![image](https://user-images.githubusercontent.com/2010549/37096522-25c730e0-2219-11e8-9926-e221f88cd6fb.png)


Thanks either way !
