### ISSUE TITLE
Offline streaming of random music

### ISSUE THREAD

**Issue by Power2All** [LibreTime/libretime#462]
I've made a little modification to the streaming code "ls_script.liq" to allow random DJ sets to be played when nobody is live.
Still need to apply a modification for showing show on the website streaming info:

You can find the changes I made back in the original ls_script.liq, use on your own accord:

```
#server.register(namespace="dynamic_source",
#                description="Start a new dynamic source.",
#                usage="start <uri>",
#                "read_start",
#                fun (uri) -> begin log("dynamic_source.read_start") begin_stream_read(uri) end)
#server.register(namespace="dynamic_source",
#                description="Stop a dynamic source.",
#                usage="stop <id>",
#                "read_stop",
#                fun (s) -> begin log("dynamic_source.read_stop") stop_stream_read(s) end)

#server.register(namespace="dynamic_source",
#                description="Stop a dynamic source.",
#                usage="stop <id>",
#                "read_stop_all",
#                fun (s) -> begin log("dynamic_source.read_stop") destroy_dynamic_source_all() end)

def update_metadata(m) =
  title = m["title"]
  ignore(title)
  album = m["album"]
  ignore(album)
  artist = m["artist"]
  ignore(artist)

  [("artist","#{title} (#{album})"),("title","#{artist}")]
end

music = normalize(playlist(reload=1, reload_mode="rounds", mode="randomize", "/location/of/music/files"))
security = single("/location/of/static/ogg/or/mp3/file/as/fallback.ogg")
v = random(weights=[1],[music])
default = fallback(track_sensitive=false, [v, security])
default = map_metadata(update_metadata, default)

#default = amplify(id="silence_src", 0.00001, noise())
#ref_off_air_meta = ref off_air_meta
#if !ref_off_air_meta == "" then
#    ref_off_air_meta := "LibreTime - offline"
#end
#default = rewrite_metadata([("title", !ref_off_air_meta)], default)
#ignore(output.dummy(default, fallible=true))

master_dj_enabled = ref false
live_dj_enabled = ref false
scheduled_play_enabled = ref false
```

(Editted script, had a few typo's)

UPDATE

Here is to edit the website, so it shows the information on frontpage when offline.

Open file "/usr/share/airtime/php/airtime_mvc/application/views/scripts/embed/player.phtml"

The function attachStreamMetadataToPlayer needs to be replace with the following:

```
        function attachStreamMetadataToPlayer(){
            $.ajax({url: "<?php echo $this->metadata_api_url?>",
                data: {type:"interval",limit:"5"},
                dataType: "jsonp",
                success: function(data) {

                    if (data.current === null) {
                        if (data.currentShow != null && data.currentShow.length > 0) {
                            //Master/show source have no current track but they do have a current show.
                            $("p.now_playing").html($.i18n._("On Air") + "<span>" + data.currentShow[0].name + "</span>");
                        } else {
                            // Offline show, check data from Icecast
                            $.ajax({url: "/stats-icecast.json",
                                data: {type:"interval",limit:"5"},
                                dataType: "json",
                                success: function(data2) {
                                    if (typeof data2.icestats.source.title === 'undefined') {
                                        if (data2.icestats.source[0].title === null) {
                                            $("p.now_playing").html($.i18n._("Off Air (Offline Music)") + "<span>"+ $.i18n._("Unknown") + "</span>");
                                        } else {
                                            $("p.now_playing").html($.i18n._("Off Air (Offline Music)") + "<span>"+ $.i18n._(data2.icestats.source[0].title) + "</span>");
                                        }
                                    } else {
                                        if (data2.icestats.source.title === null) {
                                            $("p.now_playing").html($.i18n._("Off Air (Offline Music)") + "<span>"+ $.i18n._("Unknown") + "</span>");
                                        } else {
                                            $("p.now_playing").html($.i18n._("Off Air (Offline Music)") + "<span>"+ $.i18n._(data2.icestats.source.title) + "</span>");
                                        }
                                    }
                                },
                                error: function(xhr, error) {
                                    console.debug(xhr); console.debug(error);
                                }

                            });
                            // $("p.now_playing").html($.i18n._("Off Air") + "<span>"+ $.i18n._("Offline") + "</span>");
                        }
                        time_to_next_track_starts = 20000;
                    } else {
                        var artist = data.current.name.split(" - ")[0];
                        var track = data.current.name.split(" - ")[1];
                        var nowPlayingHtml = "";
                        if (artist) {
                            nowPlayingHtml += artist;
                        }
                        if (track) {
                            nowPlayingHtml += "<span>" + track + "</span>";
                        }
                        $("p.now_playing").html(nowPlayingHtml);

                        var current_track_end_time = new Date(data.current.ends);
                        if (current_track_end_time == "Invalid Date" || isNaN(current_track_end_time)) {
                            // If the conversion didn't work (since the String is not in ISO format)
                            // then change it to be ISO-compliant. This is somewhat hacky and may break
                            // if the date string format in live-info changes!
                            current_track_end_time = new Date((data.current.ends).replace(" ", "T"));
                        }
                        var current_time = new Date();
                        //convert current_time to UTC to match the timezone of time_to_next_track_starts
                        current_time = new Date(current_time.getTime() + current_time.getTimezoneOffset() * 60 * 1000);
                        time_to_next_track_starts = current_track_end_time - current_time;
                    }

                    if (data.next === null) {
                        $("ul.schedule_list").find("li").html($.i18n._("Nothing scheduled"));
                    } else {
                        $("ul.schedule_list").find("li").html(data.next.name);
                    }
                },
                error: function(xhr, error) {
                    console.debug(xhr); console.debug(error);
                }
            });

            //Preventative code if the local and remote clocks are out of sync.
            if (isNaN(time_to_next_track_starts) || time_to_next_track_starts < 0) {
                time_to_next_track_starts = 0;
            }

            // Add 3 seconds to the timeout so Airtime has time to update the metadata before we fetch it
            metadataTimer = setTimeout(attachStreamMetadataToPlayer, time_to_next_track_starts+3000);
        }
```

Want to see it in action ?
Look at http://www.aniradio.org which is mostly playing offline tracks.

**Comment by tarkank** [comment]
Hi, thanks a lot for this. One question, is it possible to adapt this? If yes, how can I do it?

#!/usr/bin/liquidsoap
# Log dir
set("log.file.path","/tmp/basic-radio.log")

# Music
# myplaylist = playlist(mode="normal","/home/headtone/radioheadtone/mp3s/test.m3u")

morning		= playlist("/location/of/music/files")
genre	        = playlist("/location/of/music/files")
daytime		= playlist("/location/of/music/files")
genre1		= playlist("/location/of/music/files")
evening		= playlist("/location/of/music/files")
genre2       	= playlist("/location/of/music/files")
genre3             = playlist("/location/of/music/files")
chillout	        = playlist("/location/of/music/files")
genre4		= playlist("/location/of/music/files")
alternative	= playlist(mode="normal","/location/of/music/files")
jingles 	        = playlist("/home/audio/jingles")

# If something goes wrong, we'll play this
security = single("/home/headtone/radioheadtone/sets/zzz.mp3")

# Start building the feed with music
radio = switch([ 
				({16h-20h}, genre1), 
				({20h-22h}, genre), 
				({22h-0h}, alternative),
				({0h-2h}, genre3),
				({2h-6h}, morning),
				({6h-7h}, genre2), 
				({7h-9h}, genre4),
				({9h-10h}, alternative),
				({10h-15h}, daytime),
				({15h-16h}, evening),
			])

# And finally the security
radio = fallback(track_sensitive = false, [radio, security])

# radio = smart_crossfade( fade_out = 10.0, fade_in = 10.0, start_next = 10.0, radio )

# Stream it out
output.icecast.vorbis(
quality = 2.,
 description="Eastanbul",
 genre="Everything", url="http://www.eastanbul.com",
 host = "localhost", port = 80,
 password = "password", mount = "headtone.ogg",
 radio)

**Comment by Power2All** [comment]
I'll look into it later.
But it should be easly incorporated into the ls_script.liq file.
Basically, the output is done through ls_script itself, and you force a metadata update through my piece of code, so to speak.

**Comment by tarkank** [comment]
Thanks, I appreciate it. 

That's what I thought when I saw the .liq file. It is difficult to upload 100's of tracks and try to make playlists from different genres that I want to schedule meaningfully on LT's dashboard only.

**Comment by Power2All** [comment]
Hope this is what you're searching for.

```

**Comment by Power2All** [comment]
Here is what I slapped togheter really quick.
Not sure if it works, as I didn't test it.
Let me know what "error" you might get when applying this.
Basically, this way, you put the script in it's own LIQ file, seperated from ls_script.liq, with the randomizer you randomize the tune being played, and with reload=1, you make sure every time it chooses a song, it reloads the folder, in case you added/removed audio files.

```
#server.register(namespace="dynamic_source",
#                description="Start a new dynamic source.",
#                usage="start <uri>",
#                "read_start",
#                fun (uri) -> begin log("dynamic_source.read_start") begin_stream_read(uri) end)
#server.register(namespace="dynamic_source",
#                description="Stop a dynamic source.",
#                usage="stop <id>",
#                "read_stop",
#                fun (s) -> begin log("dynamic_source.read_stop") stop_stream_read(s) end)

#server.register(namespace="dynamic_source",
#                description="Stop a dynamic source.",
#                usage="stop <id>",
#                "read_stop_all",
#                fun (s) -> begin log("dynamic_source.read_stop") destroy_dynamic_source_all() end)

%include "/location/of/custom/offline-music.liq"

master_dj_enabled = ref false
live_dj_enabled = ref false
scheduled_play_enabled = ref false
```

offline-music.liq:

```
# Metadata updater
def update_metadata(m) =
  title = m["title"]
  ignore(title)
  album = m["album"]
  ignore(album)
  artist = m["artist"]
  ignore(artist)

  [("artist","#{title} (#{album})"),("title","#{artist}")]
end

# Playlists of all the moments
morning     = normalize(playlist(reload=1, reload_mode="rounds", mode="randomize", "/location/of/audiofile/or/m3u"))
genre       = normalize(playlist(reload=1, reload_mode="rounds", mode="randomize", "/location/of/audiofile/or/m3u"))
daytime     = normalize(playlist(reload=1, reload_mode="rounds", mode="randomize", "/location/of/audiofile/or/m3u"))
genre1      = normalize(playlist(reload=1, reload_mode="rounds", mode="randomize", "/location/of/audiofile/or/m3u"))
evening     = normalize(playlist(reload=1, reload_mode="rounds", mode="randomize", "/location/of/audiofile/or/m3u"))
genre2      = normalize(playlist(reload=1, reload_mode="rounds", mode="randomize", "/location/of/audiofile/or/m3u"))
genre3      = normalize(playlist(reload=1, reload_mode="rounds", mode="randomize", "/location/of/audiofile/or/m3u"))
chillout    = normalize(playlist(reload=1, reload_mode="rounds", mode="randomize", "/location/of/audiofile/or/m3u"))
genre4      = normalize(playlist(reload=1, reload_mode="rounds", mode="randomize", "/location/of/audiofile/or/m3u"))
alternative = normalize(playlist(reload=1, reload_mode="rounds", mode="randomize", "/location/of/audiofile/or/m3u"))
jingles     = normalize(playlist(reload=1, reload_mode="rounds", mode="randomize", "/location/of/audiofile/or/m3u"))

# Security file
security    = single("/location/of/audiofile")

# Switcher for music at times
default       = switch([

({16h-20h}, genre1),
({20h-22h}, genre), 
({22h-0h},  alternative),
({0h-2h},   genre3),
({2h-6h},   morning),
({6h-7h},   genre2), 
({7h-9h},   genre4),
({9h-10h},  alternative),
({10h-15h}, daytime),
({15h-16h}, evening)

])

# Fix the audio with a fallback, and choose a random song each time, depending on the switcher
default = fallback(track_sensitive=false, [default, security])
default = smart_crossfade(fade_out = 10.0, fade_in = 10.0, start_next = 10.0, default)
default = map_metadata(update_metadata, default)
```

**Comment by tarkank** [comment]
Thank you so much! Will try as soon as I can and let you know.

**Comment by Power2All** [comment]
Updated my javascript code, in case of multiple streams.

**Comment by tgd1973** [comment]
It would be very useful if you can change the embedded player from the external page in order to run as HTML5, not flash ... to no longer be blocked by browsers ...

**Comment by Power2All** [comment]
I already fixed something, it's simple to force HTML5.

Open "/usr/share/airtime/php/airtime_mvc/application/views/scripts/embed/player.phtml"

The part with "this.settings" needs to have a single extra line added, I paste the whole block:

```
            this.settings = {
                'forceHTML5': true,
                'volume': 100,
                'jsevents': true,
                'autoplay': false,
                'buffering': 0,
                'title': 'test',
                'bgcolor': '#FFFFFF',
                'skin': 'mcclean',
                'reconnectTime' : 2000, //Doesn't seem to do anything
                'width': 180,
                'height': 60
            };
```

This force the player in HTML5.
The reason it won't play on mobile, depends on if you use HTTPS or HTTP.
I had to do some tricky NGINX fuckery to get the player working in HTTPS form.

**Comment by tgd1973** [comment]
I have already tried for some time but it does not work ... to me in chrome it continues to be seen as flash and therefore blocked. Even your site is blocked ... from chrome as a flash

**Comment by Power2All** [comment]
Change $.ajax({url: "/stats-icecast.json" to the URL where your icecast is.

As for Flash, I'll let the original developer deal with replacing it with jplayer to be honest.

**Comment by Robbt** [comment]
Well you are more than welcome to work on helping us transition to jplayer vs. the way it is now. There is no original developer involved for the most part as we are a community driven fork of Airtime and whoever wrote the original code is probably not involved at this point.

**Comment by Power2All** [comment]
I will see if I can get the time for it @Robbt.
Kind of full-time working here, I did those changes, cause I already had examples ready to be used, cause of when I used purely Airtime.
I need to know how the webplayer is accessed, through which templates, since I only see the mrp.js as the main source of the player, correct ?

**Comment by Robbt** [comment]
Totally understand the limited time, that is one of the reasons why our project is called LibreTime - we are all working on it during our limited free time. I haven't spent much time looking into how the webplayer is setup so I can't provide any insight, @hairmare might be able to. The way I've had to approach everything is through reading the source code like a detective and following the various links. Thanks for anything you can contribute.

**Comment by Power2All** [comment]
I also figured out a funny but completely noob script to use PHP to read out the remaining time of the running song, and add it behind the playing song info on the website, with a bit of javascript fuckery.

Check www.aniradio.org for example :) @Robbt 
If I want to push this to current libretime, I need to properly write a fix for it, but if you like, I could add it too :)

**Comment by hairmare** [comment]
Replacing the radio page player has been discussed in #249. The phtml file changed by @Power2All  is where the changes for switching from muses to jPlayer on the radio page would need to go. 

#229 should help adding fallback scenarios like you describe without the need to change core LibreTime scripts.

Personally I don't see myself investing much time in the radio page as I consider it of limited value as it will never replace using a full fledged CMS alongside LibreTime. Better metadata integrations points for external CMS solutions are where I am focusing on regarding this.

I think there is also some work to do with in stream (ie. id3) metadata vs. js metadata generation and handling.

**Comment by Power2All** [comment]
@hairmare Correct, I am planning to eventually rewrite the website into Laravel anyway, and using the API's of LibreTime eventually to grab the info to show.

Either way, this might be some little options for users using LibreTime.
I guess you guys have no blog on github or somewhere where these kind of modifications could be shared ?

**Comment by Robbt** [comment]
@Power2All We have the Github Wiki and Libretime Manual as two places these sort of hacks can be documented. As far as Laravel it is one of the frameworks mentioned as a possible replacement for Zend in #2

**Comment by Power2All** [comment]
@Robbt Correct, Laravel is piss easy with deploying, currently coding on a video transcoding and streaming platform right now, for a few fansub groups who need this, also, will have some functions that Wowza doesn't have either. Going to be open source and purely through Laravel in combination with a few default packages from ffmpeg and handbrake :)
