### ISSUE TITLE
/etc/airtime/liquidsoap.cfg configuration file not created upon install

### ISSUE THREAD

**Issue by frecuencialibre** [LibreTime/libretime#469]
hello all! 

any ideas as to what could be happening? here are steps to reproduce:

1. fresh ubuntu 16.04 server install on a virtual machine
2. `git clone https://github.com/LibreTime/libretime.git`
3. `cd libretime && sudo ./install`
4. all standard web install steps
5. nav to http://__base_url__/preference/stream-setting and i see this error: 
![imagen](https://user-images.githubusercontent.com/36803137/37542591-4e9f191c-2924-11e8-9235-ee96f1f9c6ce.png)
7. `ls -la /etc/airtime` shows only the airtime conf file, and what i would assume to be standard ownership and permissions:
```
/etc/airtime$ ls -la
total 12
drwxr-xr-x   2 www-data www-data 4096 mar 16 13:51 .
drwxr-xr-x 110 root     root     4096 mar 15 21:07 ..
-rw-r--r--   1 www-data www-data 2309 mar 16 13:51 airtime.conf
```

I spent too many hours yesterday trying to fix this failure to connect to streams, but honestly don't understand enough to be able to troubleshoot very well. More observations:
- the liquidsoap.cfg file that existed in the previous testing instance did not update upon changes made in settings > streams, but the database did.
- `sudo service airtime-liquidsoap restart` appeared to do nothing - neither created liquidsoap.cfg nor updated it.

many thanks in advance!!!

**Comment by Robbt** [comment]
What do you see under /var/log/airtime/pypo/pypo-liquidsoap.log
What happens when you manually start liquidsoap via `sudo -u www-data airtime-liquidsoap`

**Comment by frecuencialibre** [comment]
Thanks for the response!

> What do you see under /var/log/airtime/pypo/pypo-liquidsoap.log ?
That file doesn't exist. /var/log/airtime/pypo/pypo.log ends with a million "Unable to get Airtime API version number."

>  What happens when you manually start liquidsoap via sudo -u www-data airtime-liquidsoap
```
Airtime Liquidsoap
Unable to connect to the Airtime server.
HTTP Error 404: Not Found
traceback: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/airtime_playout-1.0-py2.7.egg/liquidsoap/generate_liquidsoap_cfg.py", line 48, in run
    ss = ac.get_stream_setting()
  File "/usr/local/lib/python2.7/dist-packages/api_clients-1.0-py2.7.egg/api_clients/api_client.py", line 470, in get_stream_setting
    return self.services.get_stream_setting()
  File "/usr/local/lib/python2.7/dist-packages/api_clients-1.0-py2.7.egg/api_clients/api_client.py", line 145, in __call__
    f = urllib2.urlopen(req, timeout=ApiRequest.API_HTTP_REQUEST_TIMEOUT)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found
```
several times until `giving up and exiting...`

hmmm...

**Comment by Robbt** [comment]
Unable to get Airtime API version number. is the problem.
It is trying to reach the API section of your website and failing. Is there a URL setup that is under /etc/airtime/airtime.config ?

Is your base_url accessible from the command-line ? I'm thinking that it might have to do with the virtual box and connecting to itself. 

For development purposes it is recommended that you use vagrant.
And for hosting purposes virtualbox is almost never the ideal solution, if you want to use it you will have to do a lot with configuring port forwarding etc.

**Comment by frecuencialibre** [comment]
woooowwww, faeries dancing all over themselves!!!

i logged in to the virtual machine where libretime is installed and tried `curl my_base_url` and got our dsl modem admin page! (modem config somehow didn't work) so then, still logged in to the virtual machine with libretime, i edited /etc/hosts to redirect my base_url to 127.0.0.1, and... 
![image](https://user-images.githubusercontent.com/36803137/37673186-349e2f44-2c35-11e8-85bb-5e1330ee1024.png)

¡muchas gracias! regarding vagrant and virtualbox, i've never used them... on the recommendation of a hacker friend I've been using Red Hat Virtual Machine Manager, but am really a newbie here. Our use case as a zero budget independent radio that just wants to get up and running is that we really value specific installation instructions over support for a wide range of operating systems and versions. 

thank you!

**Comment by Robbt** [comment]
Yeah for a radio station it may make sense to just run it on a stand-alone machine vs. a virtualbox. But whatever works for you guys.
