### ISSUE TITLE
Problem: Debian install has issues

### ISSUE THREAD

**Issue by hairmare** [LibreTime/libretime#47]
The docs [recommend Debian over Ubuntu](https://github.com/LibreTime/libretime/blob/0f8c3b7c92496af1a59aba04b1573dacd235e0ad/docs/manual/preparing-the-server/index.md) but the actual install currently only works on Ubuntu. I think Debian is a better recommendation than Ubuntu since it is a less complex OS. If you ask **rms** he would go on a tangent about Debian being the more Free 😉 

Since this was only tested on Ubuntu lately nothing has been done to keep Debian working. Most of the issues are rather small stuff (like Debian not having `curl` on the CLI per default). Some of the newer python apps like analyzer and celery only have upstart scripts (where in older cases like pypo upstart falls back to the existing SysV scripts).

Solution: Test and fix the installer for Debian, convert init scripts to SysV for maximum compatibility. Fix the version recommendation in the docs.

Ubuntu will still be using upstart to keep the SysV scripts running, I think this offers the best of both worlds. Other distros (ie. CentoOS and Debian testing) will be supported by systemd anyway and we will only need one set of scripts once SysV is completely gone from our support matrix.

**Comment by korotkov13** [comment]
I got also on ubuntu 14.04 error while installing.
almost at the end when getting this message 

> Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.
Package videlalvaro/php-amqplib is abandoned, you should avoid using it. Use php-amqplib/php-amqplib instead.
Package raven/raven is abandoned, you should avoid using it. Use sentry/sentry instead

i got this 
> Generating autoload files
fatal: Not a git repository (or any of the parent directories): .git

and install stops.
where I can get the .git file?

**Comment by hairmare** [comment]
@korotkov13 using a git clone is the proper way to test pre-release versions. I made #51 so tarball installs will work again as well. The recommendation will be to use those on tags once we have them properly built (the github tarballs are a bit bare for the installer to make sense without a .git folder).
