### ISSUE TITLE
 probeleme musqiue library

### ISSUE THREAD

**Issue by premiumbe** [LibreTime/libretime#471]
Hello, how is it that I have a title of 7minute and when I look in my library it is only 3 minutes? I have to change each music manually the cut out. Do you have a solution ?

**Comment by Robbt** [comment]
You are most likely running into an issue with silan. The default package provided by Ubuntu & Debian is broken and results in incorrect track lengths.

**Comment by loadedstudios** [comment]
Also having this issue with tracks cutting out after 6 minutes of play into a 60 minute mix... with a strange glitch noise.

**Comment by premiumbe** [comment]
Problem solve thank you
