### ISSUE TITLE
Issues at summertime UK changeover.

### ISSUE THREAD

**Issue by JohnnyC1951** [LibreTime/libretime#472]
My station settings are:
Hardware clock UTC, Unix Time UTC, Libre Station Time UTC, Admin UTC
I am in the UK.
I had a show set for midnight until one. It displayed midnight until 2am, overlapping another show I could not edit to a sensible state. 
At 1 am exactly the station went silent
I switched the admin interface time to Europe London and a 1 hour gap appeared in the schedule, which I was able to fill and station playout commenced.
Weird stuff:
The UK time changes to summertime @ 2AM not 1AM
EVERYTHING was set to UTC, so nothing should care about UK summer time.
AT 2.5.2 didn't care. LT does.

**Comment by Robbt** [comment]
It would be good if we could figure out what specific code changes dealing with timezones etc was done from LT that might have introduced this issue.

**Comment by JohnnyC1951** [comment]
The only thing that makes sense to me is something is reading the user's timezone and using it, instead of using the set params.

**Comment by JohnnyC1951** [comment]
Locales? I wonder if something odd there. I have reinstalled since. Seems all good now.

**Comment by frecuencialibre** [comment]
@JohnnyC1951 are you still troubleshooting this one? if so then i'll assign you to this issue, if not then let's close it. thanks! :smiley:

**Comment by JohnnyC1951** [comment]
If you can arrange some summer-time/wintertime changes in the next week, I would be pleased to. :)
Confucius said 'If nothing alters, it will remain the same'. You can close it, but it will still exist.

**Comment by frecuencialibre** [comment]
k. closing since we have a boatload of other stuff to focus on.
