### ISSUE TITLE
issue installing 

### ISSUE THREAD

**Issue by tarkank** [LibreTime/libretime#478]
I got the result below when I tried to install the latest repo 3.0.0-alpha.4 25fbb56
any idea?

`perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
Enabling site airtime.
To activate the new configuration, you need to run:
  service apache2 reload
Install default Airtime Icecast configuration? (Y/n): Y

-----------------------------------------------------
          * Installing Airtime Services *
-----------------------------------------------------
Traceback (most recent call last):
  File "/usr/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 215, in main
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python2.7/locale.py", line 581, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
root@eastanbul:~/libretime-3.0.0-alpha.4#`

**Comment by ronstep** [comment]
This is how I got over it

Wipe server start again and before installing Libretime
#Purge all locales but en_US.UTF-8
sudo locale-gen --purge en_US.UTF-8
#Populate LANGUAGE=
sudo update-locale LANGUAGE="en_US.UTF-8"

Then Install using
sudo ./install -fiap

Hope this helps

**Comment by tarkank** [comment]
thanks! will try

**Comment by hairmare** [comment]
This is [described in the release-notes](https://github.com/LibreTime/libretime/releases/tag/3.0.0-alpha.4#issues-no-locale-3.0.0-alpha.4). Please let us know if it didn't work so we can reopen this issue.
