### ISSUE TITLE
Default playlist

### ISSUE THREAD

**Issue by Cysioland** [LibreTime/libretime#481]
Basically, now when you don't schedule a show, you have silence. But some stations use live content only intermittently, falling back to auto-DJ for the rest of the day. To spare programmers from having to schedule faux shows 24/7, maybe there could be a feature of "default playlist", as in playlist that automatically gets queued when nothing else is queued.

**Comment by hairmare** [comment]
The work from @kenrestivo in #505 can probably serve as a starting point to get there. I haven't tried it out though.

**Comment by Robbt** [comment]
So this might make even more sense with the fill remaining #605 if we integrated some kind of default playlist that is scheduled at the end of any tracks with remaining files. It would also solve an issue I was thinking of that many stations would want to have a consistent set of playlists that are appended on to each show and you wouldn't want to modify every show playlist if you decided to change it.

**Comment by Robbt** [comment]
The global intro and outro playlist proposed in #693 should be able to serve the purpose of default playlist.
The way I would imagine it is you would set a "smart block" of tracks with time remaining as the outro and they would only be only scheduled if a show wasn't set up and/or there was enough time to fill in.

This isn't quite the same as a default playlist aka AutoDJ but could serve the same purpose if people were provided with enough examples of how to leverage auto DJs.
