### ISSUE TITLE
Multiple Instance of LT on One Install

### ISSUE THREAD

**Issue by techbp** [LibreTime/libretime#483]
Hi! I wonder if this is even possible:

1. One installation of LT
2. Multiple instance assigned to different ports
3. One source file of audios

How can I achieve this? Is there any existing guidelines on how to do this - like step by step instruction?

With my searching, I found this post:
https://github.com/LibreTime/libretime/issues/255

But I found it incomplete,.. I know how to setup vhosts, and to edit the files that was mentioned... but it's incomplete - I'm afraid I'll messed up the whole installation so I opted to ask here first hoping for a detailed answer. Thank you so munch!

**Comment by techbp** [comment]
Thank you so much for your reply. Okay will look into that now. 

to Admin: Please don't close this Issue yet. Until we get a solid set of steps on how to perform this, by then we can close this. Thanks

**Comment by techbp** [comment]
How can I install new database to each instance? My first instance is at vhost airtime with port 8008
then the 2nd one is airtime2 and port 8009

**Comment by Robbt** [comment]
So I'm going to close this because we don't have any intention to start supporting multiple stations on a single server anytime soon. If someone wants to work on this they are welcome to contribute documentation and any PRs that might be needed to make it work.
