### ISSUE TITLE
setup

### ISSUE THREAD

**Issue by 00aixxia00** [LibreTime/libretime#484]
hey, 
habe libretime auf meinem ubuntu-server installiert und im browser eine rudimentäre website. Frage mich wie ich nach erfolgreicher Installation mit dem setup beginnen kann. Mein localhost zeigt keine Setup oberfläche an. Für Hilfe wär ich sehr dankbar

Liebe Grüße

**Comment by rallep71** [comment]
Schau mal hier nach, https://youtu.be/MzK_HxTlzAU

**Comment by 00aixxia00** [comment]
Hey, ich arbeite gerade das Video durch und hab einige Fragen, können wir via Discord/Teamspeak/Skype in Kontakt treten? Würde mich freuen!

Liebe Grüße, Franziska

**Comment by rallep71** [comment]
Ja, können wir machen, info@webjab.de

**Comment by hairmare** [comment]
Ich gehe davon aus, dass sich das sortiert hat. Ansonsten einfach hier oder, noch besser, im Forum melden.
