### ISSUE TITLE
libretime.org shutdown?

### ISSUE THREAD

**Issue by joaoherberto** [LibreTime/libretime#486]
Is libretime.org shutdown?

**Comment by Robbt** [comment]
Evidently there is a problem with it. This is also causing the discourse forum to be inaccessible.
I sent @hairmare an e-mail because he registered the domain and so I have no way of doing anything about it without his help.

**Comment by joaoherberto** [comment]
I operate a cPanel server, if need be I can donate a hosting account, but if domain name access is unavailable, that is problematic.

Let me know.

**Comment by Robbt** [comment]
Yeah, the site was I think hosted on github via the mkdocs platform. I'm not sure what has occurred I saw something happened with the domain on 4/25/18 but I haven't seen any posts or e-mails from @hairmare to indicate what happened. Hopefully he responds soon.

**Comment by JohnnyC1951** [comment]
Worrying. I hope he is ok. The domain itself has not expired.

**Comment by Robbt** [comment]
Yeah the documentation and all code is still available. I haven't received any replies to my emails from @hairmare so I'm not sure what is going on. He was active on github as of 3 days ago so I don't think he is completely off-line. I'm not sure what to make of the situation, he has sole control of the DNS and without it we have no way of fixing it aside from perhaps registering a new domain name and setting that up instead. I'm hoping that he checks back in at some point soon.

**Comment by JohnnyC1951** [comment]
I do hope we are not getting into a 'Stalled Airtime' situation.
Should we not be thinking about a fallback plan?

**Comment by rallep71** [comment]
Since 2 - 3 months nothing much goes, I have been following the project since the beginning, now libretime.org is gone for a few days, somehow it seems to be like it was at airtime again, maybe we can rent libretime for 99$? Irony off--

**Comment by rallep71** [comment]
i now it----

**Comment by Robbt** [comment]
I'm a little bit concerned about the lack of communication but I am an administrator for this github repo although I don't have the login for the root LibreTime user. I'm hopeful that @hairmare pops back up and fixes the DNS but if we don't hear from him in another week we can make a decision as to how to proceed. This isn't as bad a situation as what happened to the Void Linux project where their leader just [disappeared](https://www.voidlinux.eu/news/2018/05/serious-issues.html) and they had no way to add new maintainers etc. 

I've been pretty lax on reviewing PRs and in general contributing to the project. I hope to get back into it but having the docs and discourse forum go down is frustrating

**Comment by JohnnyC1951** [comment]
I think it might be prudent to clone the entire Official GIT into one that you own the Root, Robbt.

**Comment by BenHippynet** [comment]
The site has just come back up.

**Comment by JohnnyC1951** [comment]
... as if by magic?

**Comment by JohnnyC1951** [comment]
Libretime Discourse is also back up. Thankyou @Haremare
[https://discourse.libretime.org/](https://discourse.libretime.org/)

**Comment by Robbt** [comment]
Ok, so I'll close this now. As whatever DNS fix needed to be done appears to have occurred. It was down for almost 2 weeks though.
