### ISSUE TITLE
SQLSTATE Unique violation: 7 ERROR:  duplicate key value violates unique constraint "cc_stream_setting_pkey"

### ISSUE THREAD

**Issue by xabispacebiker** [LibreTime/libretime#491]
Recently I started to get this error and postgresql service randomly stops so the scheduled programs stop playing. So to say that a few days ago the system crashed with a disk corruption error, (this has happened in the last year with two other disks. By now we decided to mount a Raid 1 system to avoid or at least mitigate data corruption but that's another story).

```
2018-06-09T23:45:37+02:00 ERR (3): [ErrorController.php:54 - errorAction()] - An internal application error has occurred.: exception 'PDOException' with message 'SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint "cc_stream_setting_pkey"
DETAIL:  Key (keyname)=(radio.mp3_listener_stat_error) already exists.' in /usr/share/airtime/php/airtime_mvc/application/models/StreamSetting.php:39
Stack trace:
#0 /usr/share/airtime/php/airtime_mvc/application/models/StreamSetting.php(39): PDOStatement->execute()
#1 /usr/share/airtime/php/airtime_mvc/application/models/StreamSetting.php(522): Application_Model_StreamSetting::setValue('radio.mp3_liste...', 'OK', 'string')
#2 /usr/share/airtime/php/airtime_mvc/application/controllers/ApiController.php(1302): Application_Model_StreamSetting::SetListenerStatError('radio.mp3_liste...', 'OK')
#3 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(516): ApiController->updateStreamSettingTableAction()
#4 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('updateStreamSet...')
#5 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#6 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#7 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#8 /usr/share/airtime/php/airtime_mvc/application/airtime-boot.php(84): Zend_Application->run()
#9 /usr/share/airtime/php/airtime_mvc/public/index.php(68): require_once('/usr/share/airt...')
#10 {main}
```

**Comment by xabispacebiker** [comment]
I think I found the error and solution. 

When I run the query "SELECT * FROM cc_stream_setting WHERE keyname = 'radio.mp3_listener_stat_error'" I got no results. I tried to search the value by reading all rows and I could find something like this 'radio.mp_listener_stat_error'. Again, I tried to select where keyname = 'radio.mp_listener_stat_error' but it could not find the value either. Apparently there was some white unicode character in the keyname, therefor it was not returned by the query.

The i run:

`UPDATE "cc_stream_setting" SET keyname = 'radio.mp3_listener_stat_error' WHERE keyname LIKE 'radio.mp%_stat_error';`

and now the keyname is correctly typed and the error is not raising any more.. Hopefully the system will be stable again.

Life can be strange sometimes.

**Comment by Robbt** [comment]
So we should try to figure out if this is a bug with the SQL created somewhere. I just started looking into the listener_stat section of the code. And perhaps the wrong code name is initialized. I've seem random lock errors as well in the logs w/o immediate impact on the site but perhaps this could be the case. Worth further investigation.
