### ISSUE TITLE
On Air dont work

### ISSUE THREAD

**Issue by hopfrogsalerno** [LibreTime/libretime#498]
It seems to work everything but the radio it doesn't have audio and it is not "On Air" . The radio is on Debian 9. someone can help me. Thanks

![onair](https://user-images.githubusercontent.com/3592000/43310268-6f5d2eca-9187-11e8-88fc-22bc4bbf9370.png)
![status](https://user-images.githubusercontent.com/3592000/43310269-6f7e21f2-9187-11e8-8010-53058875cd56.png)

**Comment by Robbt** [comment]
It is also possible that something else isn't working. This requires looking deeper into the logs. For instance we still haven't setup a status page for airtime-celery which is needed for part of it.
When you go to http://yourdomain:8000 do you see a icecast page w/ information ?

Are there any errors in /var/log/airtime/zend-php.log  ? (I'm not 100% sure this is the write log name but it is similar). If you aren't familiar with checking logs it maybe something that I can write up more detailed documentation on. Let me know and I'll try to help.

**Comment by hopfrogsalerno** [comment]
Thanks. I have resolved with Ark74 indications
