### ISSUE TITLE
Imported tracks wrong length (Cue Out)

### ISSUE THREAD

**Issue by Ark74** [LibreTime/libretime#500]
I've noticed that some tracks length is not well recognized on the current latest LibreTime version installed on Xenial.
![lt_track](https://user-images.githubusercontent.com/7444518/43374928-bd4472c8-9377-11e8-8dd9-fafb6478573f.png)

The current fix is to go to the track and manually edit the **Cue Out** value.
Have you noticed the same issue?
Maybe it's related to https://github.com/LibreTime/libretime/issues/352

**Comment by Robbt** [comment]
No this is probably related to the broken silan silence detection. See this section of the release notes - https://github.com/LibreTime/libretime/releases#issues-silan-3.0.0-alpha.5

**Comment by Ark74** [comment]
That may be it. Let me see if a backport can help.
https://github.com/Ark74/silan3.3

**Comment by Ark74** [comment]
That was it!
By upgrading to silan 3.3 it worked out fine.

We could build from source, download and install backport or add the repo mentioned at the releases notes from the installer, let me know if that could work.
Cheers!
