### ISSUE TITLE
Es lädt zu lange beim Pfad einstellen

### ISSUE THREAD

**Issue by NEROFM** [LibreTime/libretime#504]
Guten Tag,

wenn wir unseren Pfad bei der Installation auf der Webseite (Schritt 4) eingeben lädt es gefühlt 100.000 Stunden. Es wäre vom vorteil dies vielleicht zu beheben.

**Comment by MTRNord** [comment]
Same issue here. After setup it gets extremly slow

**Comment by Robbt** [comment]
Can you share what Distro of Linux you are using ?
Do you see any errors it /var/log/airtime/zendphp.log ?

**Comment by Lapotor** [comment]
What is the output when you try:
`find / -depth -type f -name zendphp.log`

**Comment by hairmare** [comment]
I think using a path other than the default `/srv/airtime/stor` is most likely broken. You might be able to work around this changing that path in the database after a successful install or by bind mounting your actual storage location to `/srv/airtime` before the install.

**Comment by Robbt** [comment]
There hasn't been any movement on this bug and it is more of a support request without additional details, so I'm going to close it for now and @NEROFM  can re-open it if they are able to provide more troubleshooting information or add a support request to the [forum[(https://discourse.libretime.org)

Also someone should test and see whether using a path other than /srv/airtime/stor works and/or we should disable this. With #514 I hardcode /srv/airtime/stor/uploads which would make less sense if we allow the user to choose a separate directory to store their libretime library. I opened up #620 to deal with testing filesystem paths other than the default.
