### ISSUE TITLE
Problem: LibreTime uses a ReCaptha  Version 1 that has been discontinued

### ISSUE THREAD

**Issue by Robbt** [LibreTime/libretime#506]
If a user enters the wrong login, LibreTime will ask for a recaptcha but the recaptcha it is using is no longer valid and so it fails.

**Comment by Lapotor** [comment]
What if it get replaced with nocaptcha Recaptcha from Google ?

**Comment by Robbt** [comment]
Ok, so we need to either disable this functionality or rewrite it without depending upon Zend_Recaptcha because Zend 1 recaptcha only supports the no longer existent version 1 of recaptcha.

I'm thinking that disabling it for now makes the most sense because it can basically lock people out with no recourse and that is a bigger issue in my mind than preventing bots from attacking the system. 

One option could just be a mandatory timeout for a specific login if they fail X amount of times in a row. This might already be the case w/o the recaptcha.

**Comment by hairmare** [comment]
> it can basically lock people out with no recourse 

Don't you get another three tries if you reload the page? IMO the "security" parts of the captcha don't really work so I think removing it would be fine.
