### ISSUE TITLE
An error occurred while processing your upload. Please try again in a few minutes.

### ISSUE THREAD

**Issue by sander816** [LibreTime/libretime#507]
on a fresh install i keep getting this error when uploading songs:
An error occurred while processing your upload. Please try again in a few minutes.
Apache.conf has 500m filesize

in zendlog i do see that rabbitmq is not running:
```
root@vps3:/srv# service rabbitmq-server start
Job for rabbitmq-server.service failed because the control process exited with error code. See "systemctl status rabbitmq-server.service" and "journalctl -xe" for details.
root@vps3:/srv#

root@vps3:/srv# systemctl status rabbitmq-server.service
● rabbitmq-server.service - RabbitMQ Messaging Server
   Loaded: loaded (/lib/systemd/system/rabbitmq-server.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2018-08-29 07:35:29 EDT; 50s ago
  Process: 1269 ExecStartPost=/usr/lib/rabbitmq/bin/rabbitmq-server-wait (code=exited, status=137)
  Process: 1268 ExecStart=/usr/sbin/rabbitmq-server (code=killed, signal=TERM)
 Main PID: 1268 (code=killed, signal=TERM)

Aug 29 07:35:29 vps3 systemd[1]: Starting RabbitMQ Messaging Server...
Aug 29 07:35:29 vps3 systemd[1]: rabbitmq-server.service: Control process exited, code=exited status=137
Aug 29 07:35:29 vps3 systemd[1]: Failed to start RabbitMQ Messaging Server.
Aug 29 07:35:29 vps3 systemd[1]: rabbitmq-server.service: Unit entered failed state.
Aug 29 07:35:29 vps3 systemd[1]: rabbitmq-server.service: Failed with result 'exit-code'.
root@vps3:/srv#

```

**Comment by sander816** [comment]
reinstalling i get this:
```
-----------------------------------------------------
               * Configuring RabbitMQ *
-----------------------------------------------------
Error: unable to connect to node rabbit@vps3: nodedown

DIAGNOSTICS
===========

attempted to contact: [rabbit@vps3]

rabbit@vps3:
  * connected to epmd (port 4369) on vps3
  * epmd reports: node 'rabbit' not running at all
                  no other nodes on vps3
  * suggestion: start the node

current node details:
- node name: 'rabbitmq-cli-1742@vps3'
- home dir: /var/lib/rabbitmq
- cookie hash: o0vh8ZdIZBQzihw8PGvmVg==

Error: unable to connect to node rabbit@vps3: nodedown

DIAGNOSTICS
===========

attempted to contact: [rabbit@vps3]

rabbit@vps3:
  * connected to epmd (port 4369) on vps3
  * epmd reports: node 'rabbit' not running at all
                  no other nodes on vps3
  * suggestion: start the node

current node details:
- node name: 'rabbitmq-cli-1893@vps3'
- home dir: /var/lib/rabbitmq
- cookie hash: o0vh8ZdIZBQzihw8PGvmVg==

root@vps3:~/libretime#


```

**Comment by sander816** [comment]
btw, i am on openvz vps

**Comment by Robbt** [comment]
So there is a problem with your rabbitmq installation.
What distribution of Linux/edition of this distro are you using and what are your system resources ie amount of RAM.

A little googling shows that exit=137 is often associated with OOM errors (out of memory). I'm not sure that this is the case for rabbitmq but if you are trying to run on a VPS with 1Gb or less of memory this is a real possibility.

Can you look at your rabbitmq settings under /etc/airtime/airtime.conf and see what you have for host ?
It should probably be 127.0.0.1 but maybe you have a domain name or something in there.

**Comment by sander816** [comment]
Yes, its 512mb

**Comment by sander816** [comment]
Is there wat to limit memory use?

**Comment by Robbt** [comment]
I don't think there are any specific settings I can think of to tweak to make it reliably work with that little memory. LibreTime is built with a lot of different services. I think that you might be able to get it working with 1GB but 512mb is probably insufficient.

**Comment by sander816** [comment]
But it can run on a rpi also?
Is that rpi3 only? Because the 1st rpi had 512mb

**Comment by Robbt** [comment]
Yeah I suspect that it the case. I don't know of anyone running LibreTime in such a resource constrained setup. I'm not saying it isn't possible just that nobody has done so and documented it thus far.

**Comment by Robbt** [comment]
I think it is safe to say that LibreTime requires at least 1GB of memory to properly work so I'm going to close this because it was likely failing due to not having enough resources.
