### ISSUE TITLE
airtime_analyzer doesn't move files it fails to import to a new directory

### ISSUE THREAD

**Issue by Robbt** [libretime/libretime#508]
Basically airtime_analyzer doesn't move files it fails to import from /stor/organize into /stor/problem or any other directory.

This isn't a issue for the UI but will cause issues if we use it to import from a local filesystem watched folder and it doesn't allow sysadmins to revisit the files that failed to import and will eventually clog the /stor/organize folder with "bad files" that failed to import for one reason or another.

**Comment by Robbt** [comment]
I suspect the proper place to insert the code to do this is under the analyzer_pipeline.py when an exception is raised to try a file move to a problem_file folder. 

Currently the way analyzer is written is it supports amazon_s3 and otherwise does things with the FileMoverAnalyzer so if we are going to continue theoretically support amazon_s3 we don't want to do this if it is there. It may make sense to check and see if the storage_backend=file and then try the move.

I'll write up something soon enough and push a PR.

**Comment by jooola** [comment]
This seem outdated, I think failed import are reported back to the API, and are cleaned by a background task every hour if I am correct.


Closing as resolved.
