### ISSUE TITLE
Problem: The Podcast Datatable initially only shows 25 podcasts regardless of actual #

### ISSUE THREAD

**Issue by Robbt** [LibreTime/libretime#511]
Basically there is a bug somewhere in the code that makes it so that the podcast-datatable only shows the first 25 podcasts until you select a larger number. It will say 25/25 entries even when there are 26 or more podcasts.

This is a tricky bug to fix as I spent a lot of time looking at the various javascript files to try to diagnose it but it is a messy spaghetti code nightmare and perhaps this will be fixed only when we move away from datatables to a modern javascript framework. I know that it was fixed in airtime.pro from back when we had a subscription to it but I don't know what is causing the error. It is possibly related to #124 but until I get a better grasp of how we are using datatables exactly then I'm pretty sure I will just be wasting my time trying to fix it.

**Comment by Robbt** [comment]
Ok, it appears that the issue is that the dropdown is becoming the maximum number. Ie if you have 51 podcasts and 50 selected it will show Showing 1 to 50 of 50 entries. At this point it will make the maximum number stop at 100 because paging is not enabled. This is probably a hint as to where the problem is occurring now I just need to determine what line of code is incorrect in some code written hastily by someone years ago who is no longer affiliated with the project. I suppose I could ping him and ask him but I'm not sure what the status of the license Airtime.pro is using and if he would even remember or be allowed to share his fix.

**Comment by frecuencialibre** [comment]
where does it say "showing  _____" ? i can't see it. screenshot?

**Comment by hairmare** [comment]
I think It's about the "Show <num>" thing at the bottom right of the screenshot below... It's wrong until the users selects an actual number and then it's fixed for that user. I think this also affects all the other library pagination pages (ie. the screenshot below was made on the Tracks page which IMO is also affected).

<img width="753" alt="screen shot 2019-01-08 at 21 58 00" src="https://user-images.githubusercontent.com/116588/50858476-cc944c00-1390-11e9-8548-deb0370198cc.png">

**Comment by Robbt** [comment]
Actually the # out of # is missing, I'm not sure where it went, evidently some change we pushed through had the side effect of removing this line. I'll look into it figuring it out and see when and what caused it to go away. Removing it fixes the problem of it showing incorrect values but was unintended.

**Comment by paddatrapper** [comment]
Fixed in #813
