### ISSUE TITLE
no ssl available for output stream

### ISSUE THREAD

**Issue by drh8ball** [libretime/libretime#513]
Hi at all,
I want to integrate the player widget in my site, but my browser shows me mixed content because of the stream from http. I have a working setup for icecast with ssl, but I am not able to set right address. I can set port, but not protocoll.
![bildschirmfoto_2018-09-06_16-52-10](https://user-images.githubusercontent.com/43039898/45165841-f0cef900-b1f5-11e8-8383-11a25763ef04.png)
Where can I change this?
Thank you.

**Comment by Robbt** [comment]
checkout the files in airtime_mvc/public/widgets - I'm not sure if that is where it actually is coming from but there is a js file.

Like much of this project unfortunately whomever wrote the code in the first place is no longer around and a lot of the knowledge we have is dependent upon us digging through the codebase to try to find answers.

Looking at the path in the url embeddablewidgets I did `grep -ir 'embeddablewidgets' *`
in the source directory and I found application/controllers/EmbeddablewidgetsController.php & airtime_mvc/application/views/scripts/embeddablewidgets/player.phtml 

I'd check those out for a possible answer to your problem. I'd do more digging for you myself but I'm trying to get as much done while my daughter is taking a nap. Let us know if you find a good solution/hack. It is something I need to fix as well.

**Comment by drh8ball** [comment]
My hack is very very dirty, but it works.
I will search for a clean way, but I am no php coder.
In /usr/share/airtime/php/airtime_mvc/application/models/StreamSetting.php on line 81 i did this:
$url = "http://$host:$port/$mount"; --> $url = "https://$host:8443/$mount";

I think about making a new checkbox "alternate url" under settings output stream stream X.
If it is checked, there will be a textbox for the string, this must be written to database, from there we can use it directly in my file, without this dirty hack.

**Comment by JohnnyC1951** [comment]
I suspect you have set the SSL flags in Icecast and assumed it's working?
You can use Icecast 2.4 binaries FROM Icecast.org NOT the ones LT installed.
The standard distros before Bionic do NOT have ssl compiled in.
Upcoming Icecast 2.5 has SSL in by default.

**Comment by hairmare** [comment]
I started work on this in https://github.com/radiorabe/libretime/commit/d0357a47d3489dfac2bdc0c9ac79a853d66f1e12 but didn't get around to really testing any of it.

**Comment by maxlinux2000** [comment]
Hi all, 
I have seen that you also have the problem that basic icecast does not have SSL support.
I have solved it on my servers by recompiling icecast with support for ssl.
In the future, if linux distributions do not fix this problem, you can think about creating a libretime repository, contain the packages needed to install this program from the terminal with something like: "sudo apt install libretime" and there will be a modified version of icecast with SSL support.

In the meantime I pass my notes (in Spanish ... sorry) to install SSL icecast in armbian (ubuntu 18.04)

....al parecer en Ubuntu el paquete icecast2, no está compilado con soporte ssl, así que tenemos que volver a compilarlo nosotros mismo.
Comparto aquí mis notas, por la posteridad y para mi futura referencia en el caso lo necesite.


Voy a asumir que ya tines instalado ispConfig en tu armbian (OrangePi Pc2 en mi caso), de que tienes IP fija y pública (123.123.123.100) de que tienes un subdominio asignado desde tu registar con un record A, por ejemplo así:

radio.example.org -> 123.123.123.100

1) Crea una web en ispConfig con SSL y Let's Encrypt al subdominio radio.example.org con IP 123.123.123.100.
No hace falta nada mas. Esta pagina web en realidad no se va a usar si fuera para los cerfiticados SSL.

2) Ahora vamos a desistalar si aúno no lo has hecho eventuales isntalaciones de icecast2

`# apt remove --purge icecast2`

3) vamos preparar el entorno de compilación para icecast:

`# apt install git gcc build-essential libcurl4-openssl-dev libxslt1-dev libxml2-dev libogg-dev libvorbis-dev libflac-dev libtheora-dev libssl-dev libspeex-dev`

4) ahora bajamo el último código fuente disponible de icecast

```
# git clone --recursive https://git.xiph.org/icecast-server.git  (tarda un poco a mostrar algo... espera)
# cd icecast-server
# ./autogen.sh
# ./configure --with-curl --with-openssl
# make -j4  (si tu placa tiene 8 núcleos, pon -j8 ... y si solo quieres usar 2 pon -j2)
# make install
```

5) ahora hay que crear un usuario para icecast

`# adduser --disabled-password --gecos "" icecast`

6) crear logs

```
# mkdir -p /var/log/icecast/ 
# touch /var/log/icecast/error.log
# touch /var/log/icecast/access.log
# chown -R icecast.icecast /var/log/icecast
# chown -R icecast.icecast /etc/icecast

```
7) ahora el certificado SSL ya creado en ispconfig para la pagina web radio.example.org

```
# mkdir /etc/icecast/ssl/
# touch /usr/local/bin/icecastLetEncrypt.sh
# chmod 755 /usr/local/bin/icecastLetEncrypt.sh
# mcedit /usr/local/bin/icecastLetEncrypt.sh
```

...y escribe algo así:
---------------------------------------------------------------
```
#!/bin/bash
cat /etc/letsencrypt/live/radio.example.org/cert.pem \
/etc/letsencrypt/live/radio.example.org/privkey.pem \
> /usr/share/icecast/icecast.pem
chown icecast.icecast /etc/icecast/ssl/icecast.pem
chmod go-r /etc/icecast/ssl/icecast.pem
```
---------------------------------------------------------------

8) ahora la configuración de icecast:

---------------------------------------------------------------

<icecast>
    
    <location>ESpaña</location>
    <admin>maxlinux2000@gmail.com</admin>

    

    <limits>
        <clients>100</clients>
        <sources>2</sources>
        <queue-size>524288</queue-size>
        <client-timeout>30</client-timeout>
        <header-timeout>15</header-timeout>
        <source-timeout>10</source-timeout>
        
        <burst-on-connect>1</burst-on-connect>
        
        <burst-size>65535</burst-size>
    </limits>

    <authentication>
        
        <source-password>MySecretPasswd</source-password>
        
        <relay-password>MySecretPasswd</relay-password>

        
        <admin-user>admin</admin-user>
        <admin-password>MySecretPasswd</admin-password>
    </authentication>

    

    
    

    
    <hostname>radio.example.org</hostname>

    
    <listen-socket>
        <port>8000</port>
        
        
    </listen-socket>
    

    <listen-socket>
        <port>8443</port>
        <ssl>1</ssl>
    </listen-socket>


    
    <http-headers>
        <header name="Access-Control-Allow-Origin" value="*" />
    </http-headers>


    
    
    
    
    

    
    

    


    

    
    

    

    <mount type="normal">
        <mount-name>/stream2.mp3</mount-name>

        <username>Tester</username>
        <password>MySecretPasswd</password>

        <max-listeners>100</max-listeners>
        
        <burst-size>65536</burst-size>
        
        <hidden>1</hidden>
        <public>1</public>
        
        <http-headers>
                <header name="Access-Control-Allow-Origin" value="*" />
        </http-headers>
        
    </mount>


    

    

    <fileserve>1</fileserve>

    <paths>
        
        <basedir>/usr/share/icecast</basedir>

        
        <logdir>/var/log/icecast</logdir>
        <webroot>/usr/share/icecast/web</webroot>
        <adminroot>/usr/share/icecast/admin</adminroot>
        

        
        
        
        <alias source="/" destination="/status.xsl"/>
        
        <ssl-certificate>/etc/icecast/ssl/icecast.pem</ssl-certificate>
    </paths>

    <logging>
        <accesslog>access.log</accesslog>
        <errorlog>error.log</errorlog>
        
        <loglevel>3</loglevel> 
        <logsize>10000</logsize> 
        
        
    </logging>

    <security>
        <chroot>0</chroot>
        
    </security>
</icecast>


---------------------------------------------------------------

9) ahora probamos si funciona con

`# sudo -H -u icecast /usr/local/bin/icecast -b -c /etc/icecast/icecast.xml`

si hay errores hay que corregirlos.
El motivo del error aparece en la pantalla.
En normalidad son problemas de permisos o de que no encuentra un archivo o una carpeta.


10) creación de un servicio systemd

`# mcedit /etc/systemd/system/icecast.service`

y pega dentro al fichero:

----------------------

> [Unit]
> Description=icecast service
> After=multi-user.target
> 
> [Service]
> Type=forking
> Restart=on-failure
> User=icecast
> ExecStart=/usr/local/bin/icecast -b -c /etc/icecast/icecast.xml
> WorkingDirectory=/home/icecast
> StandardOutput=syslog
> StandardError=syslog
> 
> [Install]
> WantedBy=multi-user.target

----------------------

11) mata a icecast si es eventualmente activo. Para mirar el PID, puedes dar este comando:

`# ps -A | grep icecast`

y te sale ago así:

>   PID TTY          TIME CMD
> 22780 pts/0    00:00:04 icecast

Para matar icecast dale un

`# kill -9 22780 ` 
(el pid no será lo mismo)

y luego

```
systemctl daemon-reload
systemctl enable icecast.service
systemctl start icecast.service

```
ahora tienes icecast activo y con SSL

vete a la pagina https://radio.example.org:8443 y verás que se abre icecast con soporte para SSL

Notas:
Esta configuración de icecast.xml, permite 2 trasmisiones simultáneas a la vez. Una en el punto de montaje:
https://radio.example.org:8443/stream  (source/MySecretPasswd)
y el otro en
https://radio.example.org:8443/stream2.mp3 (Tester/MySecretPasswd)


la trasmisión de Source (cool mic desde android o ffmpeg desde linux u otra app que soporte icecast) hay que ponerle:


servidor: radio.example.org
Mount: stream
puerto: 8000
usuario: source
contraseña: MySecretePasswd


servidor: radio.example.org
Mount: stream2.mp3
puerto: 8000
usuario: Tester
contraseña: MySecretePasswd

**Comment by JohnnyAtomsk** [comment]
@maxlinux2000 kudos to you, good man! i can confirm, this solution really works :)

**Comment by maxlinux2000** [comment]
I believe that the solution to get rid of problems with SSL is to use the combination of Docker + Traefik.
If the Libretime team could create a dockerfile and a docker-compose for this magnificent products, it would give us a standardized installation and debug system.
If all the facilities are the same, it will be much easier to debug and fix the bugs.

I also assure you that installing libretime is not a simple thing on everyone's cover. You have to have enough experience, and a lot of free time to solve the problems.

However, with docker + traefik it is almost trivial to install a service.
All services work in http and traefik which is a reverse proxy, it deals with adding the ssl certificate. Therefore internally everything works with http, but on the internet it works with https.
This greatly simplifies session deploy.

Do you need an icecast? docker run majorcadevs / icecast

I encourage you to pass the project to docker so that it can spread much more.

**Comment by paddatrapper** [comment]
Docker: https://github.com/ned-kelly/docker-multicontainer-libretime or https://github.com/kessibi/libretime-docker

**Comment by maxlinux2000** [comment]
TNX!!!!! It's working!
But now I need to use with Traefik 1.7. Do you have try it?

**Comment by paddatrapper** [comment]
I have never used Traefik, sorry

**Comment by maxlinux2000** [comment]
I will try to use. For the moment I deployed this
https://radio.iesus.win

For the moment it's only the installer, and I haven't try the connection
with db and icecast. But look good.
It's running in a little orangePi  with traefik
I will send you my docker- compose file when finished

**Comment by Robbt** [comment]
Is there anyway to do this without requiring docker ? We should support SSL for output if possible. I honestly just haven't taken the time to dig into this yet.

**Comment by paddatrapper** [comment]
You can add a stanza to the Apache config to proxy some endpoint (e.g. /live_stream) to localhost:8000 and handle SSL there. The advantage is that you only need 1 domain and 1 certificate, but it means that the endpoint cannot be used in LibreTime. Another way is to create a subdomain and a second vhost which proxies to icecast (e.g. stream.example.com). This requires a subdomain/second domain and 2 SSL certificates, but means that LT isn't restricted from using any endpoints.

**Comment by H0ST4L3X** [comment]
> My hack is very very dirty, but it works.
> I will search for a clean way, but I am no php coder.
> In /usr/share/airtime/php/airtime_mvc/application/models/StreamSetting.php on line 81 i did this:
> 
> `$url = "http://$host:$port/$mount"; --> $url = "https://$host:8443/$mount"`;
> 
> I think about making a new checkbox "alternate url" under settings output stream stream X.
> If it is checked, there will be a textbox for the string, this must be written to database, from there we can use it directly in my file, without this dirty hack.

I like this hack, it's simple. Just change a few static values in the config.
Still, it might be overwritten automatically when updating at some point in the future...
For a little more satisfaction one might also want to adjust:
/usr/share/airtime/php/airtime_mvc/application/views/scripts/dashboard/stream-player.phtml
Replace http:// with https:// to make the Player (up top right) in the Admin dashboard work.

**Comment by maxep** [comment]
I agree that the ssl connection should be manage at the reverse proxy level. The only issue is when using the Live Stream player and the Widget player on Chrome which does not allows https/https mixed content.

It would be great to be able to override the `Stream URL` of **Output Streams**, so we can provide a https URL to be used in players. Kind of like we do for the 'Master Source Host' and 'Show Source Host'.

Would that be a simple change?

**Comment by jooola** [comment]
You can now define a public_url for the icecast streams, which let's you define a secure url if needed:

```yaml
stream:
  outputs:
    icecast:
      - enabled: true
        public_url: https://radio.org/main.ogg
```
