### ISSUE TITLE
Change airtime_analyzer to airtime-analyzer.service

### ISSUE THREAD

**Issue by AEK-BKF** [LibreTime/libretime#516]
Hi,
I've installed Libretime on Ubuntu Server 16.04 (64bit) via Virtual box.
I got this error when I run : **sudo service airtime-analyzer start** 

> Failed to start : airtime-analyzer.service : Unit airtime-analyzer.service not found

![error](https://user-images.githubusercontent.com/16412739/45532264-51a89380-b7eb-11e8-8f21-619bbec7a038.png)

Please any help

**Comment by AEK-BKF** [comment]
Ah Ok ! Never mind !
I wrote wrong command : _sudo service airtime-analyzer start_
The correct one is : **sudo service airtime_analyzer start**

Thanks :)

**Comment by Robbt** [comment]
Actually this is a point of annoyance for me personally because I have ran into this. I think we should use the same string format for services. Does this seem like a good idea to anyone else, either changing the old ones to use _ or modify analyzer to use the - instead. If we don't want to break any scripts/past muscle memory we could

**Comment by AEK-BKF** [comment]
+1
:+1:

**Comment by hairmare** [comment]
This has annoyed me as well 😉The `_` is pythonic and the `-` is how everyone else usually does it. We should probably just rename the service file with the pythonic `_` to a `-` and live with the actual script have a different file that the unit.

**Comment by hairmare** [comment]
I vote for `-` since it seems more natural in systemd and a majority of the services we already have use `-`. My decision isn't based on hard fact but more of a gut feeling so it doesn't really count though.

**Comment by Robbt** [comment]
Since there is a consensus here I'm going to re-open it as an issue. I just edited the title to reflect the change.

**Comment by hairmare** [comment]
Do we want to combine this with the overdue change of switching to `libretime-*` service names?

**Comment by Robbt** [comment]
We could do certainly do that, it would make sense, is there a easy way to maintain an alias to the old ones ?

**Comment by paddatrapper** [comment]
Looks like you can alias units (using `Alias=` under `[Install]`), but this is only relevant for installing units (`systemctl enable` and `systemctl disable`). We could symlink back to the old units, which should work as expected.

**Comment by paddatrapper** [comment]
The recommended way in the [docs](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Description) is to use a symlink
