### ISSUE TITLE
Icecast connection timeout

### ISSUE THREAD

**Issue by danyjcms** [LibreTime/libretime#521]
I'm trying to use airtime and Icecast on the same server. However I get this message on my output stream (Stream 1) 
<img width="332" alt="screen shot 2018-09-21 at 2 03 31 am" src="https://user-images.githubusercontent.com/43466085/45868423-dee76d00-bd42-11e8-9030-bc1eadfad423.png"> regardless if I choose Default streaming or 3rd party. 

I can connect remote to my URL and log into Libretime but URL:8000 times out and can't reach my Icecast status page.

Additional info:
Settings>Status shows no issues

Using Ubuntu 14.04 

Thanks!

**Comment by Robbt** [comment]
So the Settings-> Status page doesn't currently determine Icecast. It sounds like Icecast is not working. Have you tried to manually start it sudo service icecast2 status and maybe try sudo service icecast2 start or /etc/init.d/icecast2 start

**Comment by danyjcms** [comment]
Tried:
$ sudo service icecast2 restart

Restarting icecast2: Starting icecast2
Detaching from the console
icecast2.

$ sudo initctl list | grep airtime-liquidsoap
airtime-liquidsoap start/running, process 11417

$ sudo service airtime-liquidsoap restart
airtime-liquidsoap stop/waiting
airtime-liquidsoap start/running, process 8406

Now I can access my Icecast status page from the server's browser via _localhost_:8000 but not from outside doing _URL_:8000 or _IP_:8000

I'm guessing this is an IP/URL setting issue, not sure where to go from here.

Thanks.

**Comment by danyjcms** [comment]
Getting this message on the streams page now:

<img width="461" alt="screen shot 2018-09-21 at 10 11 57 am" src="https://user-images.githubusercontent.com/43466085/45892963-f3e5ef80-bd86-11e8-9209-31e633c15456.png">

**Comment by Robbt** [comment]
This seems like a firewall issue. Did your Ubuntu install include a firewall for some reason ? This isn't installed by LibreTime but perhaps it came along with your VPN or was otherwise installed. Or maybe your host isn't pointed to this machine correctly. It is hard to say with knowing the setup. Also have you changed the icecast passwords ? This is recommended and could be part of the issue as you'd need to change the password saved by a custom stream preference.

**Comment by danyjcms** [comment]
This now works, 2 observations: Ports 8000 and 8001 were closed in an external firewall. Removed blocking and now I can stream. 

The authentication problem went away when I left the host as _localhost_:8000 but on the outside it works with my streaming link (_URL_:8000). So it works now but on my stream settings it still authenticates as localhost.
