### ISSUE TITLE
How can I change Media folder ?

### ISSUE THREAD

**Issue by AEK-BKF** [LibreTime/libretime#522]
Hi,

I've installed the latest version of Libretime, and I set the media folder as default : **/srv/airtime/stor/**
So, I want to change it to another folder, I'm on production server (Ubuntu Server 16.04)

Thanks.

**Comment by AEK-BKF** [comment]
Thanks for quick reply,
My motivation for changing the folder is : I'm uploading music files. I have just 20GO in root folder **/**
So, I want to change it to **/home** folder where I've more than **1To** 
Please, could you give me the field and table to change the path ?

**Comment by Robbt** [comment]
I'm not sure off the top of my head and I don't have the codebase up (posting from phone) I think the folder is in a preference called cc_media_folder. Like I said the easiest thing to do would be copy the files to the new filesystem and make a folder owned by www-data and symlink /srv/airtime/stor to link to that directory. That's what I did for someone in a similar position and it worked.

**Comment by AEK-BKF** [comment]
Thank you so much !
