### ISSUE TITLE
How could I set two output streams live ?

### ISSUE THREAD

**Issue by AEK-BKF** [LibreTime/libretime#524]
Hi,
Is it possible to set two or three output streams on air ?
i.e : 
I put some music files on air at : **example.com:8000/stream1**
and others on air at : **example.com:8000/stream2**

Thanks

**Comment by Robbt** [comment]
The multiple streams are currently just for different bitrates/encodings of the same content. In order to do what you are asking you would need to have 2 different libretime installs feeding to an external icecast. Stream1 would come from libretime 1 and Stream2 would come from LibreTime2.

Hope that makes sense.

**Comment by AEK-BKF** [comment]
Thanks for answer,
So as I understood it isn't possible to do that in one server.. !

**Comment by AEK-BKF** [comment]
Where can I get the source code (php) of Libretime ?

**Comment by Robbt** [comment]
It's here in the github repository. Just clone it and look under airtime_mvc/public and that is where the bulk of the php code is. It's built zend_mvc version 1.

**Comment by AEK-BKF** [comment]
Ok, I've just found this article about multiple instances : 
https://discourse.libretime.org/t/question-several-instances-of-libretime/27

But I didn't get it working ! Please could you show us in a tutorial how to configure two instances of LT with different ports?
I want to keep everything shared except the port for every instances.

Thanks

**Comment by Robbt** [comment]
I have never tried to get this working. I don't think @yarik2720 was ever able to get it working either. So unless someone figures it out and wants to provide a tutorial I'm going to say that we just don't support running multiple instances of LibreTime on a single server. The best option at this pointwould be to get separate VPS for each instance. If someone wants to put in the time to figure this out then we can add it to the docs. In the meantime I'm going to close this issue for now.

**Comment by JohnnyC1951** [comment]
I bet you could do it with docker instances, with a single Icecast.

**Comment by yarik2720** [comment]
Agreed. That is possible with sibgle icecast on server and libretime install via docker or vagrant. Also, I recommend to use web interface of both instances on different browsers

**Comment by JohnnyC1951** [comment]
It should be fine if the dockers are used with separate vhost proxies on different subdomains.

**Comment by Robbt** [comment]
I think while it is possible, the original poster was asking for a tutorial and documentation for how to set it up. Anyone want to do this ?

**Comment by JohnnyC1951** [comment]
I dont have time to set it all up and test it right now, however. This is standard docker setup territory and there are plenty of tutorials for that.

**Comment by hairmare** [comment]
The main pain points of a "several instances" setup will be that the music database isn't shared. So it most likely won't solve the original issue here. @AEK-BKF if duplicating all the uploads and managing them repeatedly per instance I can try to write up some pointer to get you started. Keep in mind that actually running a "several instances" might surface some weird bugs that noone has encountered so far.
