### ISSUE TITLE
Use standard ID3 "comment" metatag field instead of "description"

### ISSUE THREAD

**Issue by frecuencialibre** [libretime/libretime#526]
Hi all, 

As we've been cleaning up audio file metadata and importing our radio's library into libretime, we've come up against an issue that is complicating our efforts to import music and then quickly add it to playlists/smart blocks. 

It seems he standard ID3 "comment" field is not searchable by Libretime. Can anyone else confirm this? 

Instead, I see a "description" field, which is searchable, but which doesn't exist within [standard ID3 tag fields](https://en.wikipedia.org/wiki/ID3), and so cannot be easily added by third party metatag editors.

Our use case, which IMHO could be streamlined greatly in the UI at some point, is that radio collective members are trying to import music _directly_ into a scheduled show. Currently the best way we've found is to add custom metatags to files prior to import, and then use either a playlist or a smart block to query our custom tags. It would be great to be able to use the comment field rather than mangling the genre, for example. 

thanks!
-ryan

**Comment by hairmare** [comment]
The `comment` field should get mapped somewhere. I did some digging in the code but wasn't able to find where. I always thought it would end up in the description field on the ui but never checked.

It looks like analyzer isn't doing anything to the tag:
https://github.com/LibreTime/libretime/blob/1b273062c47498fbed8e5fa0490e39a5dbeb37a9/python_apps/airtime_analyzer/airtime_analyzer/metadata_analyzer.py#L130

Analyzer then goes on to send it's data to the `CcFiles::updateFromArray()` method by way of the "modern" RESTful API where it gets processed by this:
https://github.com/LibreTime/libretime/blob/5b822afe14046157a8d9fbdff103eb383673e6be/airtime_mvc/application/models/airtime/CcFiles.php#L189-L239

I haven't figured out where/why it isn't storing the comment in the description or what is actually up here.

**Comment by Robbt** [comment]
So LibreTime also apparently doesn't save any modifications to metadata made from inside of the program back to the file's id3 tag. Once it is imported any changes made will happen only inside of the database. Would it make sense to try to write back changes in the UI to the files ? I can see a few issues with this but thought I'd bring it up for discussion as it is somewhat relevant to this.

**Comment by JohnnyC1951** [comment]
I use the 'Composer' and 'Encoder' fields in my RSS importer scripts. Not pretty, but it works.

**Comment by hairmare** [comment]
> So LibreTime also apparently doesn't save any modifications to metadata made from inside of the program back to the file's id3 tag.

Yupp, it doesn't not sure if i would consider that a bug or a feature, though. I can probably argue the case in both directions.

**Comment by JohnnyC1951** [comment]
Its a bug.

**Comment by xabispacebiker** [comment]
> So LibreTime also apparently doesn't save any modifications to metadata made from inside of the program back to the file's id3 tag. Once it is imported any changes made will happen only inside of the database. Would it make sense to try to write back changes in the UI to the files ? I can see a few issues with this but thought I'd bring it up for discussion as it is somewhat relevant to this.

It would fully make sense to write the changes to the id3 tag of the files. It's very annoying that all the work done ( in case of database corruption, whatsoever ) is gone upon reinstall. This is something I was gonna request / deploy.

**Comment by JohnnyC1951** [comment]
One could argue that it is not LT's job to mess with the original source material.
You don't back up your database regularly? I would do that for a start. Saved my ass a few times.
Before I started using my own importer, I used to use a bulk tagging program. There are lots of those around, even fully automatic ones.
My podcast importer code (various versions around for AT and LT) is now an RSS Proxy and uses the library EyeD3 to fill some tags from the original RSS Feeds before import, which I use to auto-fill the Show Title and Show description after LT's RSS import has been done. It is a bit messy and cheats but has proven to be very reliable. This proxy is unsuitable for bulk music import.

**Comment by Robbt** [comment]
So in this [forum post](https://discourse.libretime.org/t/song-metadata-issue/201/2) someone reported an issue where the metadata wasn't being updated based upon what was in the LibreTime database and it is clear that the original designers specifically chose to not update the id3 tags.

With watched folders this certainly makes sense as you don't want to alter a file that isn't being stored internal to LibreTime. I think also if we started edited the id3 tag we would need to update the hash of files that is stored. Considering there is an issue where

I was just discussing with @frecuencialibre about doing in the UI in terms of podcast import metadata overriding but unless we start saving the metadata edits back to the file it would all be internal to the LT database. But considering LibreTime currently is tricked by files where the ID3 tag length of a file is longer than the file that is actually imported it might make sense to fix this one way or another. See #537 

I think that it might make sense to update the id3 tags but we could also run into issues with say wav files and/or issues with differing metadata. I've also been considering the option of adding another column to the database to track for instance when a track EXPIRES. If we had to port this back to the id3 tag somehow it would need to be stored in some tag in a special data format. I think ogg supports custom tags but mp3 do not. Considering mp3 won by default and is no longer patented then supporting that makes sense.

But also considering in at least feature published Podcasts we provide files from inside of LibreTime to the public it would make sense to have the metadata edits in this case be saved back to the file. So it's an open question as to whether it should be changed. I can see arguments for and against. I opened up a bug #618 to deal with the metadata updating issue reported on the forum. Happy to discuss this in further depth.

**Comment by JohnnyC1951** [comment]
Extended custom tags are supported in MP3 3.2 and beyond.

**Comment by frecuencialibre** [comment]
ok so this issue thread now has two topics:

**original specific bug with the comment id3 field**: i propose that this thread remain focused on this one. 

**conversation re: LT not saving any modifications to metadata**: 
i created an issue focused on this here: https://github.com/LibreTime/libretime/issues/621

re: the podcast issue mentioned, it seems block this issue wouldn't necessarily block that functionality.

re: custom tags, i haven't checked the mp3 spec, but have seen metadata editors like puddletag successfully save and retrieve custom tags on mp3 files.

**Comment by JohnnyC1951** [comment]
There are TWO comment fields in >= MP3.2.1 defined. One is the original comment tag. The other is in extended. The spec. also defines how these should be handled. In a nutshell, if there is an extended comment tag - use that. Else, use the original tag if available.
This should be taken into account.

**Comment by frecuencialibre** [comment]
regarding the original bug reported in this issue, i just reproduced it again: nothing is stored in the `comments` column of the `cc_files` table.

-  i notice that the column name is plural, but the standardized tag name is singular. the array keys provided here: https://github.com/LibreTime/libretime/blob/634ac9c8463ad62860750ddd579356a19fcd98ab/airtime_mvc/application/models/airtime/om/BaseCcFiles.php#L4977
also use the plural comment**s**, and _seem_ (i'm not sure) to be created from the keys of the db table. simply changing the table column name in my dev instance breaks things, and i'm out of my php comfort zone, so i thought i'd check in again.

- while researching whether sourceforge could have decided to intentionally remove the ability to search by comment, i found this comment describing a method that doesn't exist...
https://github.com/LibreTime/libretime/blob/634ac9c8463ad62860750ddd579356a19fcd98ab/airtime_mvc/application/models/airtime/om/BaseCcFilesQuery.php#L299

**Comment by frecuencialibre** [comment]
ID3v2 adds "Comments", both plural and capitalized first letter, correct? i see that case seems irrelevant for the composer field. maybe i'm barking up the wrong tree. my php skills suck, don't even have an IDE set up...

**Comment by JohnnyC1951** [comment]
COMMENTS tag is in the list as ALL CAPS
the extended comment tag is COM

**Comment by JohnnyC1951** [comment]
Hmm. I have not seen an import from comments or COMM (in v2 extended) fields at all.

**Comment by frecuencialibre** [comment]
> LibreTime stores comments in the database

@Robbt you tested this and were able to see metadata comment content in
your db?

**Comment by Robbt** [comment]
I haven't tested anything yet I'm just analyzing the code at this point.

**Comment by frecuencialibre** [comment]
i remember adding text to the comment of an mp3, uploading/importing it,
but then not being able to see my test comment text in the comment db
column...

**Comment by JohnnyC1951** [comment]
Yep. That is the whole problem.

**Comment by BobJonkman** [comment]
LibreTime is also inconsistent for the "Website" field in the UI. It does not show the file's URL (ID3v2 WXXX, "User defined URL link frame").  The http://libretime.example.com/api/live-info returns an object for "url", but I don't know if this is LibreTime's "Website" field, or the embedded WXXX attribute.

I can open a separate issue for Website vs. WXXX if necessary...

--Bob.
