### ISSUE TITLE
choosing Stream Label: not works

### ISSUE THREAD

**Issue by korotkov13** [LibreTime/libretime#53]
if I want to show only **Station name - Show name** I go to In `settings-streams menu` and choosing it.
but on radio page is showing only **Artist - Title** 
Is it hard to make it work?

**Comment by Robbt** [comment]
I haven't spent any time looking at the radio page. So I'm not sure. You want your stream to not display track information ?

**Comment by korotkov13** [comment]
I want to add a show name.

**Comment by hairmare** [comment]
If it's about this one:

<img width="478" alt="screen shot 2017-03-10 at 12 57 22" src="https://cloud.githubusercontent.com/assets/116588/23794609/4d55b44c-0591-11e7-92c0-983f148b9653.png">

I think it only applies to the stream metadata. Is it doing the right thing in icecast?

**Comment by korotkov13** [comment]
Yes right that. icecast shows the right info.

I could make it work only manually editing file `/airtime_mvc/application/views/scripts/embed/player.phtml`

**Comment by hairmare** [comment]
This would need a slight refactor of the view at [`airtime_mvc/application/views/scripts/embed/player.phtml#L304-L335`](https://github.com/LibreTime/libretime/blob/276a69aa1bef527260efc170d7caab7d04b4ca13/airtime_mvc/application/views/scripts/embed/player.phtml#L304-L335) as well as injecting the "Stream Label" preference into the view in [`EmbedController::playerAction()`](https://github.com/LibreTime/libretime/blob/master/airtime_mvc/application/controllers/EmbedController.php#L18). The preference can be accessed with `Application_Model_Preference::GetStreamLabelFormat()` and I would need to do some more investigation to figure out it's format.

Feel free to create a PR if you (or anyone else) would like to take crack at it.

**Comment by korotkov13** [comment]
Unfortunately I do not have the necessary knowledge for this:(. If I find something, I'll write

**Comment by hairmare** [comment]
No worries, maybe someone else want's to take a crack at it. I might come around to it later, for now I need to concentrate on the parts that are critical for my own deploy, since this is not really critical I can't prioritize it. My last comment should make implementing this a breeze since I already spelunked the code for anyone anyone wanting to contribute.

**Comment by korotkov13** [comment]
Of coarse. You are already made a great job! 
It could made at the last stage :)
