### ISSUE TITLE
There is nowhere else to post this. There is no 'off topic'

### ISSUE THREAD

**Issue by JohnnyC1951** [LibreTime/libretime#539]
Alas, I am forking this into a fast track repo as I cannot wait many months between releases, can you?
It will be Peoples Radio and I need help from coders. PM me and please form an orderly queue. I am JohnnyC1951 in Airtime. I had hoped, even until just now, that this would not be needed and,frankly, I don't need the hassle. All devs will be equal - no fiefdoms here.

**Comment by Robbt** [comment]
Hey, if you want to fork and work on your own thing that is totally cool and encouraged. Every one will benefit from your experiments. If you feel like sharing your code back with the project I would be happy to review the PR. I know you feel a certain tension with other developers at time but I don't want that to discourage you. This is a open community project and we can discuss and disagree. If you want to diverge and forl and not push the code back, the AGPLv3 means people could grab your code and use it if they found out useful. So we all win. But yeah feel free to contribute on here as well. I'll be reviewing the list of packages that might be needed to improve installation on certain VPS distros.

**Comment by JohnnyC1951** [comment]
It will just be a fixed up installer version with some of my enhanced and added widgets, hopefully a fix for the 'Jack issue', and then frozen. I don't see the fork being actively worked on for more than a few weeks  as almost all of it is finished and working.
