### ISSUE TITLE
Smart Block does not show number of tracks that meet the selected criteria

### ISSUE THREAD

**Issue by rrfklaus** [LibreTime/libretime#541]
Dear Sirs and Madames,

I have now switched from Airtime to Libretime ...

In some places, getting used to, but it works ...

I have a question about the smart blocks ...

In airtime you could see how many songs / tracks were saved for the smartblock ...

I can not find that at libretime, or is it hidden somewhere?

Maybe someone can answer that question for me ...

Many thanks in advance..

Klaus

**Comment by Robbt** [comment]
Hello Klaus, ideally questions about how LibreTime work should be posted on the Discourse Forum and this reserved for bugs, but I could see how this feature missing could be considered a bug.

So I'm not 100% sure what you mean by "saved" - I don't think we currently show how many tracks match the criteria for the smart block. I remember seeing this in the code and I can't recall exactly why it wasn't included without diving back in. I'll make this the focus and change the title to reflect this as it should be a simple and useful change to show how many tracks might be selected by a smartblock criteria.

Now if you mean what tracks were actually selected by the "smartblock" if you are using a static smartblock then they are displayed below. Whereas with a dynamic smartblock we do offer a preview option.

**Comment by rrfklaus** [comment]
Hallo, 

vielen Dank für die Antwort ...

Ich habe einmal einen Screenshit gemacht unm zu Zeugen, was ich genau meine... 
Im Libretime fehlt das was ich im Airtime mit eunem Pfeil dargestellt habe...

![screen_airtime_smartblock](https://user-images.githubusercontent.com/44077436/46906161-77ff4300-ceff-11e8-99e9-bcce111af8f8.jpg)

**Comment by Robbt** [comment]
So evidently there was an attempt by myself to fix this with #370 but it doesn't appear to be working.
