### ISSUE TITLE
Overwrite

### ISSUE THREAD

**Issue by rrfklaus** [LibreTime/libretime#542]
Dear Sirs and Madames,

at airtime I could overwrite wonderful titles without them appearing twice ...

I have some finished radio broadcasts, which I could overwrite as I said in airtime, only in the libretime is not possible. I then have the old and the new shipment in the list ... Both with the same name ...

The format of the radio broadcasts is Mp3

Am I doing something wrong .. ?? It's kind of silly, if you always have to delete one of them ... Is there a solution?

Kind regards

Klaus

**Comment by hairmare** [comment]
Hi @rrfklaus 

If you want to rename a repeating show in the same slot, currently the only way really is to delete it and re-create a show in the same slot with the new name. Maybe you need to update the end-time on the existing slots.

I'm not sure I understand what exactly you are trying to achieve. Can you share any screenshots or similar to clarify?

**Comment by rrfklaus** [comment]
Hallo

Vielen Dank für die Antwort... Ich habe mich ein bischen falsch Ausgedrückt.
Was ich meine ist folgendes...  Wir haben vorgefertigte Sendungen im Programm, die IMMER den Selben Namen haben  (gataggt sind) ...

Wenn sagen wir mal Show A hochlade, und 1 Woche später wieder Show A  (gleichen Tags etc. wie die erste Fassung)  wird diese nNicht überschrieben, sondern befindet sich dann Doppelt auf dem Server ...

Ich habe einmal einen Screenshot gemacht, um es besser dastellen zu können, denn ich kann manches eben nicht so gut erklären...

![screen_oberwrite_show_librerime](https://user-images.githubusercontent.com/44077436/46906142-16d76f80-ceff-11e8-9afc-77dda9a24d46.jpg)

**Comment by hairmare** [comment]
Kein Problem, Ich verstehe jetzt deine Frage. Leider ist das ein bislang ungelöstes Problem. Das Ersetzen einer ausgestrahlten Sendung mit einer neuen für die nächste Ausstrahlung ist so leider aktuell nicht möglich. 
Es gibt zwar Workarounds mit Smart Blöcken, die sind allerdings leider nicht wirklich praktisch. Eventl. ist das auch etwas, dass mit der "Watched Folders" Funktionalität gelöst werden können. In meiner Station haben wir den Prozess dahingehend angepasst, dass die vorproduzierten Sendungen individuell getaggt werden, das macht sie erkenntbar, löst aber nicht das Problem, dass die Stundenfiles dann jeweils doppelt sind.

**Comment by rrfklaus** [comment]
Vielen Dank für die Antwort ... Schade da kann man dann erst einmal leider nichts machen.
Das wäre einmal eine Option, die man angreifen sollte, und zusätzlich das sich dann auch automatisch die Zeiten im Smart Block, Playliste und Co angleichen... So das man dann auch Nachrichten mit einbauen kann, ohne das die mal abbrechen, oder es Sekundenlang nichts zu hören gibt ... Das hat mir und einigen andeen auch schon beim Airtime gefehlt ...

Ich wünsche ein schönes Wochenende...
