### ISSUE TITLE
proposal: docker install repo(s) under LibreTime github user

### ISSUE THREAD

**Issue by frecuencialibre** [libretime/libretime#551]
hi all, 
at our radio station, after much time spent trying different server setups, we've found that installing LibreTime with docker to be the best choice for [various reasons](https://github.com/LibreTime/libretime/issues/515#issuecomment-424862231).

we're currently deploying @ned-kelly 's [multicontainer libretime](https://github.com/ned-kelly/docker-multicontainer-libretime) build. i've also been trying to contribute back simple fixes, bug reports, and documentation, and we've agreed that it would be great for this build to come under the main LibreTime umbrella. What do folks think? Should this multicontainer repo be created?

Other libretime instalations with docker also exist, and we could also consider creating additional versions down the line. See [this thread](https://github.com/LibreTime/libretime/issues/515).

Probably the main reason NOT to create the repo is the concern is that "officially supporting docker will lead to more support overhead since we'll be explaining docker to folks that really just want to get LibreTime up and running."  this is fair. i personally could help with support triage, and would hope that docker-specific issues would be posted either in the forum or in the docker repo(s) rather than the main libretime repo, but I've only been using docker for a few weeks! Regarding this concern, I think we should learn from [AzuraCast's approach and experience](https://www.azuracast.com/install.html#using-docker-recommended). 

thanks all!
-ryan

**Comment by hairmare** [comment]
I'm on board with this but, like explained elsewhere, I'd like to ensure that we can support multiple different variants of the docker images so I can also use it as the final location for my personal LibreTime on Openshift Dockerfiles.

I'll set up the repo and invite @ned-kelly to it as a maintainer over the weekend.

**Comment by frecuencialibre** [comment]
given the [restrictive nature of Dockerfile naming](https://stackoverflow.com/questions/26077543/how-to-name-dockerfiles), i wonder if it wouldn't be best to have multiple descriptively-named repositories.

**Comment by hairmare** [comment]
The git repo containing the container images don't need to map to images in a 1-1 fashion and docker builds can be configured for a git repo containing multiple Dockerfiles.

**Comment by frecuencialibre** [comment]
hi all, i'm re-opening this since we don't have consensus, and even a little confusion caused by me mentioning this [elsewhere](https://github.com/LibreTime/libretime/pull/584#issuecomment-436868417).

@hairmare the repo with the issues that @ned-kelly suggests we transfer is the [multicontainer docker repo](https://github.com/ned-kelly/docker-multicontainer-libretime).

@Robbt already did did some [research](https://github.com/LibreTime/libretime/pull/584#issuecomment-437688381) on github.com permissions config, which I can now confirm. It appears we're going to need to temporarily open repo creation permissions. any objections? if not, @ned-kelly could you give us a window of time within which you could do this?



from slack:
Ned:
I'd prefer to just move the repo
one repo for the multi-container build
one for a single container build
one for the k8's scripts
(Kubernetes)
keep's it simple then - easy for people to clone down and make edits if they need
[...]
Ryan:
i'd prefer that as well cuz that way i could just fork repos to get deployable container definitions. please lemme know how i can help move this forward
[...]

**Comment by Robbt** [comment]
Sure I'm ok with moving forward with the transferring the repo so we can maintain the discussion and issue queues etc. 

If we decide that it makes sense to have a singular repo for all docker stuff then we can do that via a future commit on the transferred repository.

If @hairmare is ok with this approach, I'll make the repo creation permission open and we can move the multi-container repo over.

**Comment by Robbt** [comment]
So here is what I'm thinking what @ned-kelly is doing is somewhat experimental and has some features that are specific to the process he is implementing such as running ffmpeg on podcasts to workaround a bug in the libretime-core. 

So if we moved it into the libretime repo it would probably make sense to have a version that was just based upon the main repo and avoided any modifications. In addition it would probably mean trying to do PRs in accordance with the C4 which means generally not merging your own PRs. If @ned-kelly & @frecuencialibre are the only people working on it then this could just slow down the development at this point unnecessarily. We could of course ignore that aspect of the C4 for this repo but I think we have benefited from the code-review and discipline introduced by not merging our own PRs in general in the main repo. I know that it has given me a chance to spot bugs and also get feedback on code that might have introduced bugs or wasn't as well written as it could be.

Anyways I'd like to move forward with at least a single container build as part of the libretime repo. If we want to move over the multi-container one and make it official I'm not against that at all but we should at least discuss the ramifications of the thoughts I had above regarding it impacting the current workflow for @ned-kelly & the C4.

I also just suggested that we try to make docker our recommended install for new users.

**Comment by ned-kelly** [comment]
> Anyways I'd like to move forward with at least a single container build as part of the libretime repo. If we want to move over the multi-container one and make it official I'm not against that at all but we should at least discuss the ramifications of the thoughts I had above regarding it impacting the current workflow for @ned-kelly & the C4.

Fine by me - Comments already here: https://github.com/LibreTime/libretime/issues/624 - IMHO it's worth having two (at least) repo's on Github if we're to have an official Libretime Docker build which is moving that way by the looks, again based on my comments in #624 One that's the simple build, the other that's the multiple container setup - We can also add in Kubernetes configuration there and/or perhaps a Helm package for people wanting to run this in a commercial setup I think @hairmare may already have a Helm package also? ...
