### ISSUE TITLE
Add PPA to ensure latest Silan for Ubuntu based installations

### ISSUE THREAD

**Issue by Robbt** [LibreTime/libretime#552]
We have a number of solutions mentioned in the release notes but this requires an additional step and many individuals won't read the release notes. So if possible we should detect and perform an upgrade to a working version of silan with the install script.

**Comment by hairmare** [comment]
Debian 10+ will have a working install again, maybe we should start thinking about the possibility of getting the usable silan backported to older releases. AFAIKT it needs to be in Debian stable for this. Ubuntu Bionic already has the updated silan in it's repos. Maybe @paddatrapper has some inputs on this as he has taken over maintainership of silan in Debian.

**Comment by paddatrapper** [comment]
I may be able to backport silan into the current stable release. It depends on how many of its dependencies need to be backported. I can do this while Stretch is stable or once Buster is released in about 6 months time. It just depends on how the rest of my year plays out. My current goal is to get the lastest Liquidsoap release package and then try backport silan. Liquidsoap unfortunately is a little too complex to backport easily, so encouraging people to use the new stable in 6 months is probably the best way to get that

**Comment by JohnnyC1951** [comment]
Is there a good reason why LT does not install Haremare's OBS version by default?

**Comment by hairmare** [comment]
My version is not officially supported and I have no plans to do so. Generally overriding distro packages is a bad idea and I think this should be very explicit for the user.

**Comment by JohnnyC1951** [comment]
IMO, Installing the distro version if it does not work in the app, is also a bad idea.
So, how about the script asking the user (incorporating a caveat/disclaimer), with a default of 'Y'. It would be more user friendly & stop a lot of issues/posts especially for newbies? That might 'square the circle'.

**Comment by JohnnyC1951** [comment]
I suppose we could repackage silan as silan-libretime and globally change the LT code silan refs to match? I have no idea how much work that is, but it sounds rather like a search/replace job?

**Comment by paddatrapper** [comment]
That then breaks any use of distro packages, even if it does work... I think @Robbt has the right way of doing it (via installing unofficial if needed), if we can confirm that there are no issues when upgrading a distro to a version with a working Silan version packaged in it. Ideally it should prefer the distro's version in this case as this has the security support of the distro.

**Comment by JohnnyC1951** [comment]
I guess, on reflection, you are right @paddatrapper. I did suggest the same above.

**Comment by paddatrapper** [comment]
@JohnnyC1951, ah yes, I see it now. I agree that a promp should be used to install, so that the end user is aware of the work around

**Comment by frecuencialibre** [comment]
what if we decided as a group that the [beta release](https://github.com/LibreTime/libretime/issues/544) will only support ubuntu 18?  the php 7.1 issue would have to be addressed by the installer, but perhaps that decision would still simplify our lives. @hairmare @Robbt 
https://packages.ubuntu.com/bionic/sound/silan

**Comment by Robbt** [comment]
For the purposes of this conversation the debian based distros we currently support are 
14.04 - but being deprecated due to end of LTS on April 2019 has silan 0.3.2-1 - broke
16.04 - is EOL on 4/2021 and has Php 7.0 and silan 0.3.2-1 - broke - and even though Php 7.0 is EOL by the PHP project in the past canonical has supported their php version with bug fixes see [this](https://askubuntu.com/questions/318326/what-is-canonicals-lts-support-policy-for-eol-software)
18.04 - will be supported until 4/2028 - see [this](https://betanews.com/2018/11/18/ten-year-support-ubuntu-18-04-lts/) and has silan 0.3.3-1 - which doesn't have the libretime import crippling bug.

Debian 10 will have silan 0.4 but it won't be released for a while.
Debian 9 has the broke version

I'll talk more about the 18.04 in #580 

But just for the purposes of this topic I think that the workarounds we will need to do to get 18.04 working are going to be worse than coming up with a fix for 16.04 and Debian 9. So I'd probably lean against it but we can talk more about 18.04 in the relevant issue.

**Comment by paddatrapper** [comment]
Debian 10 should be released around April next year.

I want to spend some time in January backporting silan 0.3.3 to Debian 9 during the release freeze. Once that is done, users can install it from stretch-backports without issue

**Comment by hairmare** [comment]
> install it from stretch-backports without issue

That sound like the point where we should automate this in the installer. I'm looking forward to this point!

**Comment by Robbt** [comment]
A little off topic but I think that we've seen issues with the liquidsoap provided by Debian 9 as well see #352 so will we be able to backport that as well ? Liquidsoap is far more essential than silan which we could easily remove without it affecting too many users negatively.

**Comment by paddatrapper** [comment]
Unfortunately backporting Liquidsoap is not possible - there are too many other packages that I would need to backport as well...

**Comment by Robbt** [comment]
Well we need to figure out #352 and determine if mp3 importing is broken out of the box with Debian because otherwise we can't support Debian until liquidsoap is upgraded.

**Comment by paddatrapper** [comment]
I only really know about Ubuntu packages because they work the same as Debian ones. I don't have any direct experience targeting Ubuntu, but it should be straightforward enough to target Ubuntu 16.04 in the mean time. I would need help testing and around any Ubuntu specific issues, as I have never run Ubuntu in production as I just deploy Debian.

Does Ubuntu 16.04 have the required packages for us to rely on (PHP 7.0, working silan, working Liquidsoap)? I haven't yet made a request to sync Ubuntu's version of Liquidsoap with Debian (they uploaded a Ubuntu specific patch some time ago, so it doesn't automatically sync), so it still provides 1.1.1. If it is the decided target for a beta, I can start working on an all-in-one package that effectively replicates the install script. My goal would be not to include any Ubuntu specific things, but the dependency versions would effectively make 16.04 the only viable candidate.

My end goal is still to have working Buster/Buster+1 packages so that I can deploy LT in the production environments I am involved with. I would love to find some way of helping that effort, but I think migrating from Zend 1 needs more experience with PHP than I have. It would also need a resolution for #2, but that seems to be a while off.

I agree with focusing on getting a working Beta out, targeting Ubuntu 16.04 and then start working on Debian/PHP > 7.0 compatibility from there.

**Comment by Robbt** [comment]
Yeah for some reason liquidsoap 1.1.1 works under Ubuntu w/o any issues that I'm aware of. They don't have working Silan by default but we can probably easily build a working deb that can upgrade if people add the our apt repo. And they do have php 7.0 which is only supported by php until next month but in theory security updates should be continued by ubuntu if they are found until 2021.

I'd be happy to help support this effort. In theory we could also support 18.04 but this would require people to install the [PPA](https://launchpad.net/~ondrej/+archive/ubuntu/php) for php 7.0 and I think that the silan fix is included in 18.04 by default. So targeting 16.04 is probably best at this point. 

I'm happy to help with testing Ubuntu stuff I just don't know how to do the whole process of building and maintaining a deb package repo.

**Comment by paddatrapper** [comment]
The version in Ubuntu had a fix uploaded to it that was applied directly to the Ubuntu package, not going through Debian, that is why it works and Debian's does not. Thinking out loud - I may be able to apply the patch to Debian and upload to sloppy backports or proposed updates... I'll have to look at that.

I'm happy to build a deb that people can use to test. Once it is ready, I'll tag a release in [libretime-debian-packaging](https://github.com/LibreTime/libretime-debian-packaging) and attach it there.

**Comment by ned-kelly** [comment]
> Well I think building custom packages can make sense for docker because with docker you are ideally in the end just providing a pre-built image most of the time to end-users. But if we are trying to provide a more general distribution based upon the packages that are built into the distribution then that is introducing another thing to break down.

Agree here - I think there needs to be a few various installers and then the pre-built docker images...

FWIW - I'm planning on taking all the various prices of my multi-container docker build over the holiday period and putting it into a single container for smaller deployments so I can personally run it on Heroku (i.e. an on-line streaming station only -- not a larger FM setup who should ideally be running in multiple containers and some sort of orchestration setup such as Kubernetes).

**Comment by Robbt** [comment]
This might end up solving itself if we transition to php 7.2 compatible zend at #670  by encouraging people to use Ubuntu 18.04 or Debian 10 and/or have them manually install the silan fix if they choose a older distro that has bad packages.

**Comment by paddatrapper** [comment]
Is there anything more we can do on this bug? Debian 10 has been released with a working version, Ubuntu 18.10 works and most of our efforts are focusing on these releases and later. People running 16.04 and Debian 9 should either upgrade or have enough knowledge to install silan from the PPA. Considering that LT requires a dedicated machine/VM to run, there shouldn't be too many other services running that could cause issues on upgrade

**Comment by hairmare** [comment]
I guess we can either keep this open until we phase out Debian 9 and Ubuntu 16 support in the installer or we can just close this now since it is properly documented in the release notes and there haven't been any new issues pertaining to this.

Maybe we should add a silan version check in the installer and emit a warning if a buggy silan is used as means to having actively done something to close this.

**Comment by Robbt** [comment]
So I think that we are in the boat where even silan 0.3.3 is bad and segfaults vs. providing bad information. So basically anyone using a version of Ubuntu less than 19.10 will need to manually build silan to get it working, unless we want to start hosting our own package repository to fix broken default packages. 

Here are the build instructions I just posted on the forum for someone 

I posted the following instructions.

git clone https://github.com/x42/silan.git
sudo apt install dh-autoreconf autogen libavcodec-dev libavformat-dev libsound1-dev
sudo apt install
cd silan
./autogen.sh
make
sudo make install
which will create a 0.4 silan in /usr/local/bin
you can then sudo apt remove silan
then run
silan --version and you should have 0.4 installed.

Probably the easiest workaround for people with bad versions from their package manager.

**Comment by paddatrapper** [comment]
I've been thinking about setting up a PPA for our Ubuntu support. It has several advantages, including building LT for many architectures, improved update management and means we could include things like a working silan version. I'll try get a chance to work on it this week or later on the month

**Comment by paddatrapper** [comment]
I have created https://launchpad.net/~libretime/+archive/ubuntu/libretime and uploaded the current alpha.8 package to test. Once it is all working, I will test backporting silan for 18.04 and upload it there too

**Comment by monomusika** [comment]
hello good day, I've been having problems with libretime for a month now that the music tracks play at half of their real time, I opened a thread and they told me it's a silan problem.  I am learning have me patience please.  as far as I can see I have the silan version 0.3.2 and I need to upgrade to a recent and stable version but I really don't know how to do it from SSH.  Could you tell me the steps please?  I am using Ubuntu 18.4 xenial.  thanks and have a nice day

**Comment by Robbt** [comment]
Here are the steps to install silan 0.4 via the command line/ssh
```
apt install git
git clone --branch v0.4.0 https://github.com/x42/silan.git
cd silan/
apt install dh-autoreconf autogen libavcodec-dev libavformat-dev libsndfile1-dev
apt install
./autogen.sh 
make
make install
apt remove silan
```

You will also need to update the Silan information for the tracks you've imported - see https://discourse.libretime.org/t/how-to-check-if-silan-is-working/256/13

**Comment by monomusika** [comment]
> Estos son los pasos para instalar silan 0.4 a través de la línea de comando / ssh
> 
> ```
> sudo apt install git
> git clone --branch v0.4.0 https://github.com/x42/silan.git
> cd silan/
> sudo apt install dh-autoreconf autogen libavcodec-dev libavformat-dev libsndfile1-dev
> sudo apt install
> ./autogen.sh 
> make
> sudo make install
> sudo apt remove silan
> ```
> 
> También deberá actualizar la información de Silan para las pistas que ha importado; consulte https://discourse.libretime.org/t/how-to-check-if-silan-is-working/256/13

Thanks you! :)

**Comment by paddatrapper** [comment]
The PPA now includes Silan version 4.4.1, which should work without people needing to compile from source.

**Comment by paddatrapper** [comment]
So the installer can add the PPA and install silan from it to ensure that people have a working version on Ubuntu

**Comment by Robbt** [comment]
So next step is to add the PPA via the installer for Ubuntu based systems  ?

**Comment by paddatrapper** [comment]
Yup

**Comment by zklosko** [comment]
Can this be closed out?

**Comment by paddatrapper** [comment]
> So next step is to add the PPA via the installer for Ubuntu based systems

This still needs doing
