### ISSUE TITLE
Problem: Playout wont work if locale is missing

### ISSUE THREAD

**Issue by Robbt** [LibreTime/libretime#553]
According to the release notes we have a couple of steps that are necessary.

```

Some minimal OS installs do not have a default locale configured. This only seems to affect some VPS installs as they often do not have a locale setup in the default images provided.

You can set up the locale using a combination of the following command. You might also want to consult the documentation of your VPS provider as it may contain an official way to set up locales when provisioning a VPS.

# Set locale using systemds localectl
localectl set-locale LANG="en_US.utf8"

These instructions do not seem to work on all Debian based distros so you might need to use update-locale as follows.

#Purge all locales but en_US.UTF-8
sudo locale-gen --purge en_US.UTF-8
#Populate LANGUAGE=
sudo update-locale LANGUAGE="en_US.UTF-8"
```

We should look into how to do this automatically.

**Comment by hairmare** [comment]
IMO this only affects minimal installations (mostly in OS images provided by some cloud providers) that also need additional consideration like setting up a proper timezone.

**Comment by Robbt** [comment]
Yeah there are evidently a number of issues and missing packages that affect certain minimal installations. Would there be a way to do this in the install script that doesn't negatively impact people with normal sized distributions.

**Comment by JohnnyC1951** [comment]
The script generates locales in ubuntu.

**Comment by Robbt** [comment]
This is a duplicate of #317 and so I'm closing it.
