### ISSUE TITLE
Silan OBS Repo in Alpha 5 Release notes, for Trusty, does not contain silan files.

### ISSUE THREAD

**Issue by JohnnyC1951** [LibreTime/libretime#556]
http://download.opensuse.org/repositories/home:/hairmare:/silan/xUbuntu_14.04
Contains: 
 | Parent Directory |   | - |  
  | amd64/ | 19-Nov-2017 16:49 | - |  
  | i386/ | 19-Nov-2017 16:49 | - |  
  | Packages | 19-Nov-2017 16:49 | 0 | Details
  | Packages.gz | 19-Nov-2017 16:49 | 20 | Details
  | Release | 19-Nov-2017 16:49 | 1.0K | Details
  | Release.gpg | 19-Nov-2017 16:49 | 481 | Details
  | Release.key | 19-Nov-2017 16:49 | 1.1K | Details
  | Sources | 19-Nov-2017 16:49 | 0 | Details
  | Sources.gz | 19-Nov-2017 16:49 | 20 | Details

But Xenial does
http://download.opensuse.org/repositories/home:/hairmare:/silan/xUbuntu_16.04/
  | Packages | 03-Jun-2017 17:19 | 2.1K | Details
  | Packages.gz | 03-Jun-2017 17:19 | 800 | Details
  | Release | 03-Jun-2017 17:19 | 1.0K | Details
  | Release.gpg | 03-Jun-2017 17:19 | 481 | Details
  | Release.key | 03-Jun-2017 17:19 | 1.1K | Details
  | silan_0.3.3~nmu1.diff.gz | 03-Jun-2017 17:19 | 1.2K | Details
  | silan_0.3.3~nmu1.dsc | 03-Jun-2017 17:19 | 939 | Details
  | silan_0.3.3~nmu1.orig.tar.gz | 03-Jun-2017 17:19 | 23K | Details
  | Sources | 03-Jun-2017 17:19 | 1.1K | Details
  | Sources.gz | 03-Jun-2017 17:19 | 661 | Details

**Comment by hairmare** [comment]
Looks like it was [excluded on OBS](https://build.opensuse.org/project/monitor/home:hairmare:silan?arch_x86_64=1&defaults=0&excluded=1&repo_xUbuntu_14_04=1) for some reason.

I replaced the line in the release notes with a working repo:

```bash
echo 'deb http://download.opensuse.org/repositories/home:/hairmare:/silan/Ubuntu_14.10_standard/ ./' \
  > /etc/apt/sources.list.d/hairmare_silan.list
```

Thanks for the report. Please close this once you confirm it's working.

**Comment by JohnnyC1951** [comment]
That installed ok, thanks.
