### ISSUE TITLE
Maybe not an issue but 'oddness' in 'cc_files'

### ISSUE THREAD

**Issue by JohnnyC1951** [LibreTime/libretime#558]
Running a simple query on cc_files, an update of a complete record choked. Updating named fields worked.
I found that blank fields of the INT and TIMESTAMP types actually seem to contain ASCII spaces, which Postgres was not happy about. Manually clearing these values allowed the update to work.
Maybe this is some sort of standard POSTGRES behaviour, but I thought I should share it, in case this is causing issues elsewhere.

**Comment by hairmare** [comment]
Any chance you could share the affected query? I don't think the last release contained any db migrations relating to cc_files.

**Comment by JohnnyC1951** [comment]
I think this is an artifact of the postgres editor I was using.
Closing this.

**Comment by hairmare** [comment]
We don't support direct edits to the database anyway... So, ok, I guess.

**Comment by JohnnyC1951** [comment]
I was trying to force a silan rescan. Just for info.
