### ISSUE TITLE
Problem: The utils folder contains a lot of scripts that won't work with LT

### ISSUE THREAD

**Issue by Robbt** [LibreTime/libretime#561]
There are a number of scripts in the utils folder that won't work with LT as referenced in #351 

This includes scripts that specifically contact SourceFabric phone_home_stat & phone_home_stat.php
as well as a airtime-nuke that hasn't been modified to work with LT and is probably dangerous

The solution here is to either add a disclaimer as a README that lets people know that these scripts aren't tested or to test them and remove the ones that don't work as intended. Perhaps we can do the README as step 1 and then remove or update it as we test and/or remove the scripts from the utils.

Ideally the README would also contain a brief description of the intended use-case and parameters required for each util and we could even designate a "contrib" folder for scripts that people have submitted that haven't been officially vouched for but people might find useful.

**Comment by hairmare** [comment]
I'm nuking the phone_home stuff in https://github.com/LibreTime/libretime/pull/562 since I find it obvious that we don't want to keep it and it's completely defunct anyway.

**Comment by JohnnyC1951** [comment]
Backup should be enabled by default and fixed if necessary. It is stupid not to back up,

**Comment by Robbt** [comment]
Determining a good default backup process would be helpful but it would require an external repository to actually backup too and also a tested and verifiable restore process.

**Comment by zklosko** [comment]
With exception to the `airtime-log` bash script, I'd say that we're good on this task. Is there anything else that needs to be done here?
