### ISSUE TITLE
File duration is truncated to 59:54.3 when uploading shows of over 1 hour

### ISSUE THREAD

**Issue by ghost** [LibreTime/libretime#576]
File duration is truncated to 59:54.3 when uploading shows of over 1 hour. In the next screenshot you can see a file which was uploaded through the UI. The dashboard shows a duration of 59:54.3 but the player is showing a duration of 2 hours.

![libretime_dashboard issue](https://user-images.githubusercontent.com/20809792/47342546-4a0ac300-d6a4-11e8-89b9-8f4adff58571.JPG)

I've also imported some files via the commandline to /srv/stor/airtime/xxx. These seem to appear normally in the dasboard. In the next example you can see that the FFM137 show the right duration of 2 hours. The subsequent ones were uploaded through the UI. These show a wrong duration time.

![libretime_dashboard issue1](https://user-images.githubusercontent.com/20809792/47342659-88a07d80-d6a4-11e8-8181-4cea7bc15d59.JPG)

**Comment by Robbt** [comment]
Did you upgrade Silan as per the release notes ?

**Comment by itcrowdsource** [comment]
Hi @Robbt  yeah my apologies. I didn't knew I had to upgrade Silan. I just upgraded it and the issue seems to be resolved. Thanks! Next week we're going to try to take LibreTime into production. We have been using Airtime for many years, this is a new exciting path for us;-)
