### ISSUE TITLE
Problem: upgrade path for cc_music_dirs from Airtime 2.5 to LibreTime

### ISSUE THREAD

**Issue by Robbt** [LibreTime/libretime#577]
There was an issue in #113 that appears to be related to LibreTime not working correctly with cc_music_dirs other than /srv/airtime/stor.

In addition if we are phasing out watched folders than we also need to determine how this will work. In general we need to do some testing for directories other than /srv/airtime/stor and see if they work. And if Airtime 2.5 allowed multiples, how to transition them upon install and how we can handle watched folders or test at least what happens when someone using watched folders upgrades to LT.

**Comment by Robbt** [comment]
The work I did doesn't support static files. It is basically an importer that allows file system based import process. It requires a file to be copied into the directory. I looked into the watched folder importation work done previously at #111 and attempted to make it work with airtime-analyzer but I wasn't successful. @HaJoHe basically had to implement a parallel version of airtime-analyzer to get it to work for him and somewhere along the line it wasn't working when I tried to get it working.

#542 is a bug report that is basically asking for the ability to have static files that are overwritten and can be scheduled.

So there evidently are some existing workflows like the one you describe that are built around this idea that you have a file and continually overwrite it. Some of the issues I see with this are the fact that files can be of different lengths. For instance say the schedule expects a file to be 1 minute long but someone records a 2 minute version. If it is in a static playlist and is replaced by a new version externally there is no mechanism that I'm aware of that will automatically update existing playlists when a file was overwritten with a new copy. In fact we are attempting to workaround the idea that a new file was created all together.

In my mind this seems like an outdated approach that could be fixed with properly configured smartblocks without relying upon external files and losing data. But I also know that once people are familiar with a process they are loath to change it especially for something that seems more complicated and is probably more subject to breaking.

The basic issue is that media-monitor no longer exists and in order to support this functionality we would need to reinvent it or do more work on #111 and then in turn support two parallel but basically the same importers. I'd be concerned that the watched folder importer would be more brittle. If we are going to change airtime_analyzer to get it to work with static files we will need to do a fair amount of changes to the php portion of the rest importer. Then there is the issue of monitoring these static files (especially remote network files). What happens if for instance the network is done, do we track that a file is external from the UI. Or do we cache these files and copy them into libretime.

In the case of a file being externally overwritten how do we know that it has changed or are we specifically designing the system to pretend that once a file is imported it is the same file always and then basically expecting people to understand this intuitively. These were the concerns that led me away from working further on #111 and implementing something simpler that basically duplicates the functionality that existed with media-monitor that simply imported files that were copied into the /srv/airtime/stor/organize directory. We still have an issue #508 where files that fail to import aren't moved at all.

So yeah I'm not against the idea of watched folders and this is the first time someone has come forward with an explicit requirement that it be used. Would it make more sense to implement something geared towards static external files/folders rather than the way it has been promoted before ?

Is there a reason we can't update workflows to have people directly use the system to upload the files vs. having them use some external resource. Perhaps a specialized way of importing would make sense. For a lot of this external files we are using RSS and smartblocks but that is geared primarily towards shows at this point but it could also work for weekly segments but would require more of an infrastructure in place. So yeah feel free to share more about this in this topic, they are related enough and otherwise #70 is where it was discussed previously.

**Comment by zklosko** [comment]
This issue appears to be moot due to #71 and #1226. Is it time to close this? It would basically make us ready for beta.

**Comment by paddatrapper** [comment]
I think there is still merit here, though maybe not as a beta blocker. We still need to find a way to support watch folders as it is a very useful workflow for a variety of tasks. Some could be replaced with RSS feeds and the podcast ingest we already have, but for internal content that seems like overkill

**Comment by paddatrapper** [comment]
Directories other than /srv/airtime should work. I think this needs testing, but probably isn't a release blocker

**Comment by jooola** [comment]
I have been using a custom directory since I first installed Libretime. Everything is working fine. I think this can be closed.
