### ISSUE TITLE
Problem: Podcast Override & Automatic Smartblock are disabled by default

### ISSUE THREAD

**Issue by Robbt** [LibreTime/libretime#578]
I suggest that we set the default setting be for Podcasts to override the album name with and create the automatic smartblock.

My reasoning is that this behaviour is useful and self explanatory once displayed but not easy for someone to find and choose unless they are exploring the UI.

I don't see this causing any real problems, most people who subscribe to a podcast will probably find the smartblock to be more useful than annoying or confusing. And iTunes being the most popular podcast client also overrides the album name of tracks it downloads with the podcast name. So this shouldn't be a big problem if we do this. If someone finds it detrimental they can disable it.

If others agree that we should enable this I'll create a PR to push this to be the default.

**Comment by frecuencialibre** [comment]
i vote yes.  otherwise you get to step 7 [here](https://github.com/LibreTime/libretime/wiki/Automatic-Playlists,-Smartblocks-and-Podcasts) and then realize you ahve to start over.
