### ISSUE TITLE
Feature Request: Make default library view sorted by Column: Uploaded On and showing newest tracks

### ISSUE THREAD

**Issue by Robbt** [LibreTime/libretime#579]
The Track Library view by default includes a column for Title, Create, Album, Length and is usually sorted by Title.

I want to suggest that we change this to include the Column Uploaded, and make the track sort so that newest tracks are at the top of the list.

I suggest this because most of the tech support I've done for LibreTime has been explaining to people who just uploaded a track how to find it and this involves clicking on columns, finding uploaded, checking it and then clicking on uploaded. 

So this is the most useful view for most people. Once you start searching you can sort by title, or length etc because you have a specific goal for the library. If you are just opening the library without a idea what to look for it is probably because you are looking for a track you just added and requiring search for that is not easy.

**Comment by frecuencialibre** [comment]
sounds good! i think however that this is a feature request not a problem.

**Comment by JohnnyC1951** [comment]
I would like to suggest something slightly different.
Save and re-use current column settings on exit. I think that ticks most boxes.
