### ISSUE TITLE
system menu is missing

### ISSUE THREAD

**Issue by whohoho** [LibreTime/libretime#588]
I just installed libretime from git.

The menu is now on verticall and on the left, but it seems there is no system menu.

How do i go to the media folder settings?

**Comment by Robbt** [comment]
There is no media folders setting. See the release notes

**Comment by Robbt** [comment]
Also see discussion in #70 and #514 and $577 - I'm going to close this now but feel free to follow up if you require this. The docs will be when  #514 is merged.
