### ISSUE TITLE
Problem: Help Tips point to Airtime.Pro Manual

### ISSUE THREAD

**Issue by Robbt** [LibreTime/libretime#59]
This is probably a simple fix, but the little help tips that show up when users are doing tasks for the first time like creating shows point to http://sourcefabric.booktype.pro/airtime-pro-for-broadcasters/library/ rather than the LibreTime manual.

**Comment by ronstep** [comment]
If you need someone to write a manual with screen shots I'm happy to help, just shout at me.

**Comment by hairmare** [comment]
@ronstep Thanks for the offer. I imported the manual Robb is referencing into https://github.com/LibreTime/libretime/tree/master/docs. You can see it in action on http://libretime.org.

If you want to help improving it there are "Edit on GitHub" links throughout the page.

Thanks for contributing!
