### ISSUE TITLE
Proposal: enable podcast smartblock and playlist creation by default

### ISSUE THREAD

**Issue by frecuencialibre** [LibreTime/libretime#614]
i think that the global setting "Podcast Automatic Smartblock and Playlist" should be enabled by default.  otherwise you get to step 7 of the [add a podcast process](https://github.com/LibreTime/libretime/wiki/Automatic-Playlists,-Smartblocks-and-Podcasts) and then realize you have to start over. my [comment](https://github.com/LibreTime/libretime/issues/578#issuecomment-433506915) was mistaken, i thought we were talking about this setting. this was also discussed but not resolved in https://github.com/LibreTime/libretime/issues/560#issuecomment-430271180 .

**Comment by Robbt** [comment]
This was done in #581 and I just tested and a fresh install it is enabled for me.

**Comment by frecuencialibre** [comment]
ok sweet. sorry for the noise
