### ISSUE TITLE
Liquidsoap doesn't get updated metadata from LibreTime database

### ISSUE THREAD

**Issue by Robbt** [LibreTime/libretime#618]
According to this forum post - https://discourse.libretime.org/t/song-metadata-issue/201/2 there is a bug where liquidsoap isn't pulling updated metadata from the libretime database as it purports to here - https://github.com/LibreTime/libretime/blob/634ac9c8463ad62860750ddd579356a19fcd98ab/python_apps/pypo/pypo/telnetliquidsoap.py#L4-L36

So if this isn't working there is a bug somewhere. It could be resolved by saving metadata edits back to libretime as discussed in #526 or in troubleshooting what is happening with the function above. At this point we still need to verify this bug is reproducible because I am not the original reporter.

**Comment by hairmare** [comment]
I think this is about pypo not pulling metadata from the web-api if none is available in the actual file (as is the case with wav files). I think I've seen this before but can't find an issue describing it. I'm pretty sure the following line is somehow involved.

https://github.com/LibreTime/libretime/blob/49a715bc98d14c7f412803d598c83661d81b1d20/python_apps/pypo/liquidsoap/ls_script.liq#L111

At least I think it's where the data ends up being applied in the liquidsoap parts. Seeing how there's not much to it maybe we need to stare at the python parts more to figure this one out.

**Comment by Schellsburg** [comment]
The issue of edits to metadata made through the Web interface being ignored in favor of the tags in the uploaded audio files applies to MP3 files too, not just to uploaded WAV files with no metadata. This is a notable change in behavior from Airtime (assuming it's by design and not simply a bug).

**Comment by Robbt** [comment]
I suspect that this is an unintended side-effect of the switch to airtime_analyzer style import vs. media-monitor that was done to make the import process more friendly to cloud-based storage such as S3 that was used by Airtime.pro. As above this could be fixed by saving the metadata changes back to the metadata of the files referenced in #526

**Comment by Robbt** [comment]
I think we should probably do something about this rather than late it go stale.

**Comment by xabispacebiker** [comment]
I will look into it too
