### ISSUE TITLE
Problem: Library search has no way of matching tracks that contain a phrase

### ISSUE THREAD

**Issue by Robbt** [LibreTime/libretime#626]
Problem: When you search through the Library interface it will treat each word as a separate search and match results that contain either of the words.

For example if you search for `Thursday News` it will show anything that contains news or Thursday in the title. If you wrap the text with quotes like "Thursday News" as is customary in web searches it will return no results.

What would be expected is to return results that contained Thursday News as a phrase.

In addition any it will show any tracks that contain any sequence of the letters at all for instance if you searched for `station id` it would also return tracks  that contained words like friday or side because id is a part of those words

This contributes to #90 and is probably related to #63 

I'm not sure that this is something that we can easily address but it would be helpful if the default behavior was more optimal.

Suggestions for how to improve:

- No longer match on tracks that contain the search term only as an internal set of characters.
- Either provide " " functionality to match exactly or make the results match the phrase for multiple term searchs by default. 

I think that in general returning less more precise results will be more helpful in terms of finding exact results and since the results are driven by an ajax query people can adjust their search interactively if they find they aren't getting enough results.

**Comment by hairmare** [comment]
PostgreSQL has extensive support for things like stemming in their [dictionaries part](https://www.postgresql.org/docs/9.1/textsearch-dictionaries.html). I'm pretty sure using this from zf1 is possible but certainly not available OOTB without writing raw queries. I'm not sure if it makes sense to invest too much time into this rather than looking at how maintain our domain specific search requirement in the lieu of #2.

**Comment by Robbt** [comment]
Yeah, I don't think we should do this with zf1 for sure. I think that the /rest/media/ API and controller though is something we could rewrite and use to test out a new framework/backend. I really haven't dug deep enough to understand how we can start routing certain requests to a new controller/framework while still using our current one and proceed replacing everything step by step. This is what I think might make sense for starting to address #2 without trying an often failed rewrite everything at once approach. In addition it could help us to stay in accordance with the C4 and not start a topic branch for a new framework.

**Comment by hairmare** [comment]
There's the [StranglerApplication](https://www.martinfowler.com/bliki/StranglerApplication.html) pattern for one, but it's a ton of work to actual get through to the part where "legacy" is gone. I've been thinking about writing up a proposal around that pattern, microservices and finding synergies with other liquidsoap user for #2 but I don't think I'll actually get to it until the beta phase is well underway.

**Comment by Robbt** [comment]
Interested read, it seems that most of the recommendations for how to migrate away from zend1 involve doing this sort of thing. In theory it seems like it could work. I think that it makes sense to refactor to create a better API and get the front-end independent and doing things with more micro services. I think that we have a rather large API already but it isn't documented very well. In addition there is a /rest/media API that is being used by newer parts of the system like the podcast module but not for datatables. So I can imagine how the Library could be improved a lot by making API calls and this fits into this specifically. It seems like a good place to start experimenting at least.
