### ISSUE TITLE
Feature Request: Allow podcasts to aquire metadata from RSS feed when files are missing metadata

### ISSUE THREAD

**Issue by Robbt** [LibreTime/libretime#633]
Basically a number of audio files we receive from a certain provider have no id3 metadata and really non-descriptive filenames. These same files have decent title data and descriptions in the RSS feed itself. 

This could probably be done in celery and would be an easy fix. It would go a long way to making the metadata played out over the feed make sense to listeners vs. inscrutable file names.

**Comment by JohnnyC1951** [comment]
Could we modify the proposal to include the description?

**Comment by Robbt** [comment]
I modified the description to make this more about metadata in general to represent the fact that it could include more than just track title but also description.

**Comment by Robbt** [comment]
So this is more or less a duplicate of #431 - and so if we can address that issue we can solve this one as well. So aside from setting up a proxy solution the question is where the best place to insert this fix is. The way I enabled the addition of album name overriding was by adding additional parameters to the podcast-download celery task and passing a podcastname and override flag. This would get ridiculous if we started doing this for every field we wanted to change AND the podcast_name is from the system vs. the RSS feed so it is readily available. 

I don't think that the actual episodes RSS metadata ie title & description etc aren't stored in an easily accessible spot in the database, so if I took a similar approach and passed them as a parameter it would require modifying a bit of code and adding the title and description to the podcast_episode database table. 

The right approach might be to add this data to podcast_episodes and then intercept the callback where podcast_episodes is updated and then modify the metadata from inside of PHP vs. passing stuff to python and celery. That's what I'll investigate next.

**Comment by Robbt** [comment]
So this is somewhat working, it might need refinement and could use some testing. But basically the newest PR pulls the title from the feed and if album override is enabled it will override the title for the track with the one from the RSS feed. We should probably update the UI to show album & title override or decide if we want to have a separate flag for title override in the options etc. 

I personally am of the opinion that overriding it all at once as one option is probably a good idea and we just change it to metadata override. But I'd like to hear other peoples thoughts.

**Comment by JohnnyC1951** [comment]
See my recent comments in other threads. There is overlap.
