### ISSUE TITLE
Sometimes error 404 when setting up a live stream

### ISSUE THREAD

**Issue by itcrowdsource** [LibreTime/libretime#641]
We're encountering issues on our newly build LibreTime live streaming server. We had a similar setup with Airtime which worked well. But our DJs that want to initiate a live stream are inconsistently encountering a 404 error when they try to connect. Sometimes they're able to connect a few times in a row. And after a while it's impossible to connect. Most of our DJs are using the Butt client (https://danielnoethen.de/) to setup a stream. I disabled the firewall, went through all the system logs and also checked all the logs in /var/log/airtime/  but couldn't find anything specif related to this issue. Does anyone has a suggestion where to start tackling this issue?

Ps. we have just migrated our other Airtime system to LibreTime which is working prettyg well. Many thanks for the great work of this community! :-)

**Comment by frecuencialibre** [comment]
could this be related? https://github.com/LibreTime/libretime/issues/160

and docs: http://libretime.org/manual/stream-settings/#input-stream-settings

**Comment by itcrowdsource** [comment]
@frecuencialibre That might me the culprit. Have you got a good suggestion for alternative software streaming clients? We have selected Butt a few years ago as the primary software client for our DJs because it was the most stable solution by that time. But maybe there are better alternatives. We prefer to work with open source solutions because it resembles the spirit of our radio station. We're a non-profit organisation.

**Comment by Robbt** [comment]
Hmm if this worked with Airtime we can probably figure out what change causes Butt to fail and revert it or otherwise fix it. The state of good free streaming clients is pretty bad and so fixing this Butt issue is probably a good idea. Mixxx is overkill for most purposes.

**Comment by frecuencialibre** [comment]
@itcrowdsource if you're willing to go the command line route there's [ices2](http://www.icecast.org/ices/docs/ices-2.0.2/). we haven't found a good, simple GUI streaming client. try butt 1.13?

**Comment by JohnnyC1951** [comment]
does it work on master?

**Comment by JohnnyC1951** [comment]
**Please note this**, I have mentioned this a few times now:
The Butt 1.13 vs later Butt, I have discussed elsewhere.
I have used both Butt 1.13 and MIXXXX v1.x with great success (MIXXX is excellent) in AT & LT.
MIXXX 2 release and later will not connect to LT. But MIXXX 2.0 ALPHA does. So maybe there is a clue to this in the changelog/delta. Maybe Mixxx is in a git and we could see this.
Later versions of Butt and MIXXX v2 will not connect to AT/LT
The connecting protocol (Icecast2 compatible) changed in later icecast2 specs.
Butt, MIXXX, and more changed the way they log in as a source. There is an extra handshake now, so MIXXX 2.0 and later BUTT are waiting for a response from AT/LT which never arrives, hence no connection.
You will see LOTS reports of BUTT and MIXXX now being broken, but this is not the case. Very modern radio software works great in this situation.

**Comment by itcrowdsource** [comment]
> does it work on master?
It doesn't work on master either, same 404 error
@frecuencialibre ices2 isn't an option for us because we're bound to multiple types of clients. We have over 250 DJs who work for us. Some of them use Windows, other are bound to Mac's. I can't think of anyone using Linux, but probably that's a fairly small percentage.
@Robbt would be good indeed to figure out what the main cause is of this issue.

**Comment by JohnnyC1951** [comment]
MIXXX is available for windows mac & linux

**Comment by itcrowdsource** [comment]
Thanks @JohnnyC1951 I'll give it a try.
I've checked the TCP stream from the Butt client, but I can't find any specific causes. I'm getting a 404 error with no further details.
```
PUT /show HTTP/1.1
Authorization: Basic <auth string>=
Host: :8002
User-Agent: butt 0.1.15
Content-Type: audio/mpeg
ice-name: no name
ice-public: 0
ice-audio-info: ice-bitrate=256;ice-channels=2;ice-samplerate=44100

HTTP/1.0 404 Not found
Content-Type: text/html

<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en"><head><title>Liquidsoap source harbor</title></head><body><p>This page isn't available.</p></body></html>
```

**Comment by itcrowdsource** [comment]
I think @frecuencialibre  is right. This is similar to #160

**Comment by frecuencialibre** [comment]
appears this [can be fixed by updating liquidsoap](https://github.com/LibreTime/libretime/issues/160#issuecomment-447819363)

@itcrowdsource if you've concluded this issue is a duplicate, could you close it?

**Comment by Robbt** [comment]
@frecuencialibre I think it's reasonable for us as maintainers to close an issue for people once it's determined to be a duplicate. As far as I know people can continue conversation on a closed issue until unless it is locked. So I'm going to close this for now.

**Comment by itcrowdsource** [comment]
Has anything changed in the source code regarding this issue? I've just updated Libretime to the latest version and using it with Butt v0.1.17. It seems that the problem doesn't persist anymore. I'll continue to do some more tests though.

**Comment by frecuencialibre** [comment]
> Has anything changed in the source code regarding this issue?

not yet. has your liquidsoap version changed? `liquidsoap --version`

**Comment by itcrowdsource** [comment]
Liquidsoap 1.1.1

**Comment by frecuencialibre** [comment]
@itcrowdsource i think what's changed is that you're now using butt 1.17 (not 1.16) which has fixed the issue. 

> fixed connection issue with airtime

https://sourceforge.net/p/butt/news/2018/12/new-release-butt-0117/
