### ISSUE TITLE
Problem: Import failed

### ISSUE THREAD

**Issue by JJK1231** [LibreTime/libretime#644]
On my Raspbarry PI, the airtime-analyzer is not working. As i do sudo invoke-rc.d airtime-analyzer start i get Unit airtime-analyzer.service could not be found.
invoke-rc.d: initscript airtime-analyzer, action "status" failed.
and manual start also works not.

**Comment by Robbt** [comment]
It is still airtime_analyzer vs. airtime-analyzer although we plan on changing the file name so this sort of confusion doesn't happen in the future.

**Comment by JJK1231** [comment]
I did do run it now but when i upload something i get: An error occurred while processing your upload

**Comment by paddatrapper** [comment]
What OS are you running on your pi?

**Comment by frecuencialibre** [comment]
> An error occurred while processing your upload

also, i'd check your php error log. this could be as simple as a permissions issue with your folders. this command will output the last 50 lines:

```
tail -n 50 /var/log/airtime/zendphp.log
```

**Comment by Robbt** [comment]
I'm going to close this because it is a support request and the OP is not actively pursuing this or responding.
