### ISSUE TITLE
Problem: Status Page does not support purely systemd units

### ISSUE THREAD

**Issue by paddatrapper** [LibreTime/libretime#662]
**Describe the bug**
Installing airtime_analyzer, airtime-liquidsoap and airtime-playout using systemd units (with no files in `/etc/init.d`) and not having `initctl` installed results in the configuration checklist thinking that the services are not running, when they actually are (as verified using `systemctl status`).

**To Reproduce**
1. Install the [deb](https://cloud.paddatrapper.com/s/id2opdGcs5jGde9)
2. Step through installer
3. Verify running status of services

**Expected behavior**
The configuration checklist reports that they are running (and that they are actually running)

**LibreTime version:**
3.0.0-alpha.6

**Installation method:**
 - OS: Ubuntu
 - OS Version: 16.04.5 LTS (Xenial Xerus)]
 - Method: deb package

**Comment by hairmare** [comment]
This also affects the status page under settings which calls the same code.

I've been ignoring the checklist in my rpm based installations since they have the same problem. I've started to think about solving this issue by asking the system dbus directly (and allowing that through polkit) but haven't gone down that route since it's quite a piece of work. The last time I checked we still supported some pre systemd distros. I don't think there any of the remaining distros will not be based on systemd once we drop support for Ubuntu Trusty so I've been holding off on implementing anything until then.

On production I usually skip the whole configuration checklist thing because I create the conf manually.

**Comment by hairmare** [comment]
Now that Ubuntu Trusty is off the tables it looks like all of our distros support systemd as default init system. We might consider just deferring to something like [Cockpit](https://cockpit-project.org/) to cover this need and mostly remove the status functionality. I would like to keep the status page to some extent so [embedding cockpit](https://cockpit-project.org/guide/149/embedding.html#embedding-components) could be a solution.

**Comment by paddatrapper** [comment]
The problem with embedding cockpit is that it makes packaging a nightmare... At least in Debian, I would need to patch the embedded link out

**Comment by Robbt** [comment]
I see that Cockpit packages are in Debian Buster - https://packages.debian.org/buster/cockpit - are these too old to be compatible ? I think that embedding it would just be integrating a iframe to cockpit that is running elsewhere, so it would be no different than how we use Icecast etc. I certainly understand the concern if we were treating it like a jquery library etc but if we just do the simple integration and install the packages independent of the files it doesn't seem like it would introduce any problems. It might be overkill in comparison to what we have now but it might not. 

I think in some ways it would be cool if we had opt-in crash and statistic reporting but considering the amount of bugs we already have open we are not lacking for bugs to fix.

**Comment by paddatrapper** [comment]
Ah yes, sorry I seemed to fail to find that package when I was searching through. So if we depend on cockpit and set it up on the same server, it is fine in terms of Debian policy. Connecting to a hard-coded remote instance would be more of an issue.

It is certainly overkill compared to what we have now, but we may be able to integrate it to do things like automatically restart the systemd units after the setup wizard

**Comment by dave31610** [comment]
hi how can i solve the problem i can't figure it out and i don't know how to get it right

**Comment by paddatrapper** [comment]
So it seems that the configuration checklist reports things correctly, however the status page in LibreTime does not (testing on vagrant Debian Buster box)
