### ISSUE TITLE
Change UI to accept time 23:59:59

### ISSUE THREAD

**Issue by bjjayk** [LibreTime/libretime#676]
So the discussion was about the UI giving only the option to select 23:59 which leads to a 1-minute gap in playout. A solution so far was to select the following date at 0:00, which might cause confusion.

> The solution to this, in general, is to do 00:00 of the next day and not leave 23:59. Now as far as improvements to the UI what you are suggesting sounds like it might make sense but I'd need to see a mockup and/or description of the problem its trying to solve to visualize it better.

I guess it would make no sense to change the date and time picker tool and add and end day button there. So maybe even simpler approach would be to let the UI accept seconds, so we could at least set it to something like 23:59:59 (maybe even .9999999 like the settings in the cue points).
So I would suggest setting a checkbox that when set opens up the entry field to be filled in by hand and accept it like that. Or set the value fixed as 23:59:59.99999 when checked. So that would not screw up all that was made so far, but in case it is needed could be used. I mean the only use case is exactly the end between days. And for that reason, it would be enough to document the feature with a mouse hover, so that the user exactly knows when to hit the checkmark and enter data by hand.

It would also make sense because I see the shows which are overlapping to 0:00 the next day marked with a red exclamation mark in the calendar. it's always the first show and the last show shown in the view. I guess it because it goes to the next page.

So as for mockup:
add one line under End time
add hover info icon "If you need to enter the exact end time, check the following checkbox to enter the time manually. This is used to set the exact end time, only at the end of the day."
Checkbox
Entryfield (maybe even prefilled with 23:59:59.99999 when checked)

Checkbox active should stop the time picker above from working.

So that would be my user-oriented approach.
What do you think?

**Comment by Robbt** [comment]
Yeah this is tricky with our current setup, I don't think the proposed solution would be the easiest way to implement or the most intuitive way of doing this for a new user.

What we really want to do is show them how they can make the end time 00:00:00 of the next date or do this via an alternative route. 

When you click the end time it pops up with the selection widget. Perhaps below this pop-up you could have end of day button that automatically sets it to 00:00:00 with the next date.

I don't know how easy to implement any of these options would be. The easiest thing option would be a hover info icon that explains for end of day enter 00:00:00 of the next date. This would help explain this to people without requiring us to refactor the javascript and rebuild the UI.
