### ISSUE TITLE
WebCaster (Question)

### ISSUE THREAD

**Issue by adamburnsuk** [LibreTime/libretime#679]
**Is your feature request related to a problem? Please describe.**
I am using libretime for a live podcasting network and a lot of my users are not very technical.  They usually have problems setting up the broadcasting software on their on computers.  Some of them also have crappy computers and Mixxx or whatever doesn't run well.  Anyway, we are making due right now...but what I would like to offer is a WEB interface that streams to libretime.  You can see an example of this at https://webcast.github.io/webcaster/.   I am wondering how easy it would be to integrate this into libretime (it connects directly to liquidsoap and I'm not sure that is possible with libretime as I believe the desktop clients connect to icecast)

**Describe the solution you'd like**
I would like a webcaster type widget that can be added to any website (Wordpress plugin would be wonderful), that I can use to allow my users to log in to my website and stream direct from there.

**Describe alternatives you've considered**
There is another libretime alternative that does this already.  https://www.azuracast.com/ .  But, this solution is missing some of the features that I love and need in libretime.

**Additional context**

Really this is more of a question than anything.  I am not a php developer unfortunately and still trying to grasp all the intricacies of how libretime is doing everything.  I just wanted someone to take a look and figure out if they think it's even possible to integrate something like this with libretime.  If it is, it might even be something I could work on...I just need to be pointed in the right direction.

**Comment by adamburnsuk** [comment]
I don't think it's quite that simple.  I tried using the example webcaster and changed the url to the url for my server, but I'm getting handshake timeout.  The webcaster has to connect via websocket and I don't think I can make a websocket connection to libretime endpoints (correct me if I'm wrong).  I think it's wanting to make a direct websocket connection to liquidsoap.  Again, apologize for my ignorance If I'm getting it terribly wrong.  :)

**Comment by hairmare** [comment]
It looks like you'd need liquidsoap 1.3.x and Chrome for this to work. Using that combination I can get http://webcast.github.io/webcaster/ to connect to a development vagrant box (CentOS based with the patch from #192 and liquidsoap 1.3.5).
When I connect the stream I can see `2019/01/07 19:06:08 [master_harbor:3] Decoding...` in ` /var/log/airtime/pypo-liquidsoap/ls_script.log`.
I haven't been able to get any sound out of it but it It looks like my Chrome is having some issues with the webcaster demo (ie. the level meter doesn't show any sound).

Depends on #192

**Comment by paddatrapper** [comment]
Webcaster works in Firefox too and with #931 merged, streams perfectly to LibreTime. The only thing to note is that the Streaming URI should be in the form `ws://username:password@server:port/mount`, and not have `http://` at the beginning
