### ISSUE TITLE
Support AWS S3 storage

### ISSUE THREAD

**Issue by whiteblue3** [LibreTime/libretime#680]
**Is your feature request related to a problem? Please describe.**
Storage should can be on AWS S3 storage. No document for config or feathers.
 

**Describe the solution you'd like**
There is AWS S3 open source on GitHub repository. Why should use it?

**Comment by hairmare** [comment]
Did you consider using [s3fs-fuse](https://github.com/s3fs-fuse/s3fs-fuse)?

**Comment by whiteblue3** [comment]
Oh, is it applicable? Thank you :)
