### ISSUE TITLE
TLS on AWS ELB has a problem

### ISSUE THREAD

**Issue by whiteblue3** [LibreTime/libretime#681]
**Describe the bug**
I'm apply to TLSv1.2 on AWS ELB (Elastic Load Balancer)
Main page has no widgets. Cannot login to manager

**LibreTime version:**
https://github.com/LibreTime/libretime/pull/670

**Installation method:**
 - OS: Ubuntu
 - OS Version : 18.04
 - Method: sudo -H ./install --web-root=/srv/airtime --web-user=www-data

**Comment by hairmare** [comment]
This is probably a duplicate of #515.
