### ISSUE TITLE
Debian Jessie is EOL

### ISSUE THREAD

**Issue by paddatrapper** [LibreTime/libretime#684]
Debian Jessie ended security updates on 17/05/2018, but a limited number of packages and architectures are supported until around 2020 by the LTS project.

We should check if the packages required by LT are supported by the LTS project. If they aren't, we should drop support for Jessie.

**Comment by hairmare** [comment]
I disabled wheezy like so when I noticed... 

https://github.com/LibreTime/libretime/blob/bd1636ece203ee62768ff23d0a24e8fec3406fc9/install#L637-L641

I'll also mention this in the release notes if we merge it... Jessie should be long gone already.

**Comment by paddatrapper** [comment]
I'll open a PR to add the warning for deprecation in Alpha 8 then

**Comment by paddatrapper** [comment]
Reopening to remind us to drop support in alpha.8

**Comment by paddatrapper** [comment]
TODO:

- [ ] `exit 1` in the installer for Jessie
- [ ] Update `/docs/vagrant` to reflect no Jessie
- [ ] Remove `debian-jessie` from Vagrantfile

**Comment by paddatrapper** [comment]
With the EOL of Jessie, we can also drop support from PHP 5

**Comment by paddatrapper** [comment]
Scratch that, it is needed for CentOS 7 as it has PHP 5.4
