### ISSUE TITLE
Settings menu item not visible for Program Manager users

### ISSUE THREAD

**Issue by delrizzo** [LibreTime/libretime#698]
Hi Gang,
Really appreciate the work you're all doing here. We are in the midst of setting up a broadcast station, and have switched from 2.5.1 to Libretime. Noticing some things and I hope to get more involved as time goes on and our station becomes more self-reliant.

Anyhow, In creating our user database yesterday, I noticed that users designated at "Program Managers" do not have the "Settings" tab in the left side menu. This doesn't seem to be the case for "Admin" or even (at least) "DJ" level users. Because there is no username link at the top right as there was in 2.5.1, users need to access that Settings tab in order to be able to change their default assigned password. I think this is possibly a bug, so reporting here. I did a check of previous issues and found nothing that referred to this, so if it exists, my apologies.

**Describe the bug**
"Settings" menu tab not visible for "Program Manager" users.

**To Reproduce**
1. Create a new user
2. Give the user "Program Manager" access
3. Logout, and login again as that user
4. Notice that there is no "Settings" tab in the menu

**Expected behavior**
I expected there to be a Settings tab, which would give the user access to be able to modify their individual settings, or at the very least change their password.

**LibreTime version:**
0370dfb7c

**Installation method:**
 - OS: Ubuntu
 - OS Version 18.04.1 LTS
 - Method: ./install
 - Details: Installed with PHP 7.1
![screen shot 2019-01-17 at 1 00 58 am](https://user-images.githubusercontent.com/30699584/51306999-74de8c00-19f3-11e9-9383-301623997d96.png)

**Screenshots**

**Client (please complete the following information if applicable):**
 - OS: Mac 10.12.6
 - Browser Chrome
 - Version 71.0.3578.98

**Comment by paddatrapper** [comment]
Hi @delrizzo. This is definitely a bug. Thanks for reporting it!

**Comment by hairmare** [comment]
Does clicking their username work? That should navigate to `/user/edit-user` as well.

In the ACL bit the roles are a hierarchy so a program manager should always see more than a DJ.

That the Settings menu can only be seen by admins was introduced in 3aee9a49bc524450011310419dee1adb23b9a702 on the saas-dev branch.

**Comment by delrizzo** [comment]
I have not been able to find the username to click on... maybe I'm missing something? I was wondering why that isn't there (vs being there in Libretime).
Further to that, a DJ can see the Settings tab, but a guest cannot. And there is no text link for user where it used to be in airtime.

**Comment by Robbt** [comment]
Perhaps the move of the log-out inadvertantly removed the username see #489

**Comment by frecuencialibre** [comment]
heya @delrizzo good catch. we need this fixed at my station too. 

i think fixing this could be pretty simple - just some templating php/html and css. i'd suggest that in addition to and also restoring the settings menu as per your screenshot, we could also re-enstate the link to edit the user account lost here: https://github.com/LibreTime/libretime/pull/489/files#diff-165f6eea594414ec748228edc340227e

i think the rationale behind that change was to fix the layout that was breaking, so we'll have also fix that with css at a range of screen sizes. i personally have always found it weird that the logout button is in the bottom left. i always look for it in the top right as per convention on many websites, and also think it could just be a text link not a huge button. 

Dave, is your thinking similar on this one? i'm totally flexible. you mentioned in slack your hope to get time to chip in, any interest in a PR to fix this one?

**Comment by hairmare** [comment]
The fix would possibly be to just change the action the settings menu is hooked up to

https://github.com/LibreTime/libretime/blob/87b8ef4f9137c3a36ef75882375fd0e5aac0e0a3/airtime_mvc/application/configs/navigation.php#L71-L74

Change this section in the navigation.php file to this:

```php
     'resource' => 'usersettings', 
     'action' => 'edit-user', 
     'module' => 'default', 
     'controller' => 'user', 
```
This should make the Settings menu appear for all users and it should also make it's link point directly to the user settings page.

**Comment by Robbt** [comment]
Cool. I think the solution proposed by @hairmare is a good one, next step is a PR.

**Comment by hairmare** [comment]
I just got to testing my change and it doesn't seem to be enough, at least on my current test machine I doesn't get the Settings menu to show up.
