### ISSUE TITLE
Podcast ingest timeout error

### ISSUE THREAD

**Issue by frecuencialibre** [LibreTime/libretime#702]
**Describe the bug**
when trying to import a large number of podcasts at once on a relatively slow internet connection, i'm seeing all episodes successfully imported into the library, but some (those that took longer) not recognized as having been imported within the podcast episode listing (ie. delete-able and shown with a green checkmark). This is not a huge deal, but noting here for the record. zendphp.log error:

```
2019-01-19T00:43:02+00:00 INFO (6): frecuencialibre.mazorca.org Moving file /tmp/phpLutgj7 to /external-media/organize/Musica%20que%20Resiste_03_Makila%2069_final.mp3
2019-01-19T00:43:47+00:00 ERR (3): frecuencialibre.mazorca.org [ErrorController.php:26 - errorAction()] - Incorrect API key
2019-01-19T00:43:47+00:00 ERR (3): frecuencialibre.mazorca.org [ErrorController.php:27 - errorAction()] - #0 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Plugin/Broker.php(309): Zend_Controller_Plugin_Acl->preDispatch(Object(Zend_Controller_Request_Http))
#1 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(941): Zend_Controller_Plugin_Broker->preDispatch(Object(Zend_Controller_Request_Http))
#2 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#3 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#4 /usr/share/airtime/php/airtime_mvc/application/airtime-boot.php(84): Zend_Application->run()
#5 /usr/share/airtime/php/airtime_mvc/public/index.php(68): require_once('/usr/share/airt...')
#6 {main}
2019-01-19T00:43:47+00:00 ERR (3): frecuencialibre.mazorca.org [ErrorController.php:54 - errorAction()] - Se ha producido un error de aplicación interno: Zend_Controller_Exception: Incorrect API key in /usr/share/airtime/php/airtime_mvc/application/controllers/plugins/Acl_plugin.php:142
Stack trace:
#0 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Plugin/Broker.php(309): Zend_Controller_Plugin_Acl->preDispatch(Object(Zend_Controller_Request_Http))
#1 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(941): Zend_Controller_Plugin_Broker->preDispatch(Object(Zend_Controller_Request_Http))
#2 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#3 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#4 /usr/share/airtime/php/airtime_mvc/application/airtime-boot.php(84): Zend_Application->run()
#5 /usr/share/airtime/php/airtime_mvc/public/index.php(68): require_once('/usr/share/airt...')
#6 {main}
```

**To Reproduce**
1. add a podcast
2. import 10+ episodes at once

**Expected behavior**
they all download

**LibreTime version:**
https://github.com/frecuencialibre/libretime/tree/deploy-podcast-ui

**Installation method:**
 - Ubuntu 16.04.5 LTS  via docker multicontainer: https://github.com/frecuencialibre/docker-multicontainer-libretime

**Comment by Robbt** [comment]
So the issue isn't that they didn't download but by the time they downloaded the script that informs the UI that they were successfully downloaded timed out and thus they aren't shown as downloaded in the Podcast page right ?

Is this still the case if you navigate away and then back to the podcast page ? Ie is it a temporary thing or are they not marked as downloaded at all and thus libretime might re-download another copy of them.

**Comment by frecuencialibre** [comment]
> So the issue isn't that they didn't download but by the time they downloaded the script that informs the UI that they were successfully downloaded timed out and thus they aren't shown as downloaded in the Podcast page right ?

correct

> Is this still the case if you navigate away and then back to the podcast page ? 

yes

> Ie is it a temporary thing or are they not marked as downloaded at all and thus libretime might re-download another copy of them.

never marked as downloaded. 
thanks!
