### ISSUE TITLE
Problem: The ability to mass import podcasts via OPML or textfile could be useful.

### ISSUE THREAD

**Issue by Robbt** [LibreTime/libretime#72]
This could be useful for mass import of podcasts via the OPML format or via a text-file or copy and pasting into a text area could be useful feature to speed up the process of setting up a station.

**Comment by JohnnyC1951** [comment]
I made an importer for AT that is a stand alone cronjob that will import from a CSV list of RSS2.0 feeds. That should still work.

**Comment by Robbt** [comment]
I think I know the script you are mentioning. We already have Podcast support built into the web UI interface so doing it externally is no longer necessary. This was the suggestion of adding a URL parser that would directly add the podcasts to LibreTime so that a user doesn't need to manually add them.

**Comment by JohnnyC1951** [comment]
Mine goes way past adding a podcast. It, forces stereo, down-samples if required,  fills in the genre info,  pads shows with genre specific intro jingles, adds randomized, show-genre-specific music to a given length - for repeating shows, makes the tea and carries out the trash.

**Comment by Robbt** [comment]
Interesting. It would be good to integrate some of that functionality into a smarter version of a smart block play list. I have been considering making a default playlist template for podcasts since we've now added an automatic playlist scheduling functionality.

**Comment by JohnnyC1951** [comment]
The idea was to import series of podcasts, as they become available, in such as fashion that Airtime would automatically play them week after week. To do this, I make a copy of the pod, pad it to the full show length and call it a consistent name eg. my-greatshow-full-latest.mp3
The sneaky bit is putting the show title, presenter, genre and a lot more in the mp3 metadata.
When this imports, it over-rights last week's file fooling Airtime - but the show info now shows last week's show info.
So, I have another cron job that updates the AT show info from the metadata held in the mp3.
Voila! Automatic ongoing self updating show content.

**Comment by JohnnyC1951** [comment]
Can Libre Time do this functionality all by itself now?

**Comment by Robbt** [comment]
Yes. The functionality that exists. 
Podcast/RSS subscription - it has a nice UI for adding podcasts and downloading episodes.
Auto Playlist - this is allows you to assign a playlist to a show that will be scheduled an hour before it is supposed to air. 

Inside the playlist you can include any number of smart blocks which will grab their tracks based upon the latest criteria. For instance you can have a track that says "Grab 1 item of the newest track that has an album = Democracy Now."  This will automatically grab and schedule a track from the DemocracyNow podcast. You can include station ID blocks, jingle/filler blocks etc as well and it will schedule them.

This is in contrast to the AutoDJ included with Airtime.Pro that would just grab random tracks to fill up a show based upon criteria. There was no ability to specify 1 smart block of a random station ID followed by 1 of the latest podcast etc. So it provides much more control over the tracks played than what SourceFabric provided.

What it doesn't do is normalize and auto-fill to a specific time limit. It could be modified to do the auto-fill but that would require a smarter smart block that adjusts its time limit to fit into the remaining time.

**Comment by JohnnyC1951** [comment]
Great progress then. Without auto-update, I would stick with what I have. It works very well

**Comment by Robbt** [comment]
[Here](https://github.com/imelgrat/opml-parser) is a library that processes OPML in php
