### ISSUE TITLE
"Bad file extension" error upon m4a podcast import

### ISSUE THREAD

**Issue by frecuencialibre** [LibreTime/libretime#721]
**Describe the bug**
Podcasts fail to import. I'm seeing this error in zendphp.log:

```
2019-01-24T18:39:16+00:00 ERR (3): fl.local [MediaController.php:161 - postAction()] - Bad file extension.
#0 /usr/share/airtime/php/airtime_mvc/application/models/airtime/CcFiles.php(99): CcFiles::createAndImport(Array, '/tmp/phpP6Lmrw', 'videoplayback')
#1 /usr/share/airtime/php/airtime_mvc/application/modules/rest/controllers/MediaController.php(145): CcFiles::createFromUpload(Array)
#2 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(516): Rest_MediaController->postAction()
#3 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('postAction')
#4 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#5 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#6 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#7 /usr/share/airtime/php/airtime_mvc/application/airtime-boot.php(84): Zend_Application->run()
#8 /usr/share/airtime/php/airtime_mvc/public/index.php(68): require_once('/usr/share/airt...')
#9 {main}
2019-01-24T18:39:32+00:00 WARN (4): fl.local Celery task DbId: 165
DbTaskId: php_5c4a058a527e36.67507114
DbTrackReference: 165
DbName: podcast-download
DbDispatchTime: '2019-01-24 18:35:54'
DbStatus: SUCCESS
ThirdPartyTrackReferences:
  DbId: 165
  DbService: podcast
  DbForeignId: '166'
  DbFileId: null
  DbUploadTime: '2019-01-24 18:39:32'
  DbStatus: null
  CeleryTaskss:
    CeleryTasks_0: '*RECURSION*'
 episode 166 unsuccessful with message 400 Client Error: Bad Request for url: http://fl.local/rest/media
```

**To Reproduce**
1. Add one of these feeds with m4a enclosures: https://podsync.net/Z4JjXtcV3 or https://podsync.net/UVYAstc9m
2. The xml should parse correctly and show up, but then try to manually import an episode and you should get the error above.

**Expected behavior**
podcast episode imports successfully

**LibreTime version:**
current HEAD

**Installation method:**
 - ubuntu 16.04.5 LTS via docker multicontainer

**Comment by hairmare** [comment]
I looks like m4a should be allowed:
https://github.com/LibreTime/libretime/blob/5b822afe14046157a8d9fbdff103eb383673e6be/airtime_mvc/application/common/FileDataHelper.php#L5-L26
It would be interesting to know what's in `$fileExtension` here:
https://github.com/LibreTime/libretime/blob/a92c75023cbca16820c4188f876fa20294934946/airtime_mvc/application/models/airtime/CcFiles.php#L138-L143

**Comment by frecuencialibre** [comment]
thanks for checking this one out. unfortunately my laptop fell off a car so iĺl be unable to help test etc. until i can get up and running again :(. in order to confirm the redirect hypothesis, did you already try swapping the enclosure url for it's final destination in the xml file? i did some testing like this on other issues, adding for example podcasts at http://10.0.2.2/testfeed/feed.xml (that ip is that of the host from the vagrant vm guest)

**Comment by Robbt** [comment]
It looks like the file is downloading, the issue is that somehow the file extension/name gets lost in the redirect/download which causes the /rest/media request to the site to fail. 
Not sure what the best way to resolve this is but the following are the lines where I suspect it is running into issues.

https://github.com/LibreTime/libretime/blob/a92c75023cbca16820c4188f876fa20294934946/python_apps/airtime-celery/airtime-celery/tasks.py#L152-L158

The airtime-celery logs show that it downloads and detects that it as a m4a file but I suspect that it is trying to upload the tmp filename without the extension back to the LibreTime zend server which is why you get the 400 error.

I could imagine some kind of python code that detects a missing extension and appends one based upon the metadata but I'm not sure if there isn't an easier way to resolve this or if this would cause unintended side-effects.

**Comment by frecuencialibre** [comment]
ok back up and running on another machine and i had a chance to check this. 

> It looks like the file is downloading

yep. i see files in /tmp downloaded with the original urls.

i also tried the test that i suggested above: saving the feed xml file locally and then replacing enclosure links with their final destinations. unfortunately the final url contains ampersands (&) which bust the xml. i tried url encoding them (tried both as &amp; and &26), but it the file created in /tmp is always 0 bytes, and then predictably i get the nonetype error: ` episode 189 unsuccessful with message 'NoneType' object does not support item assignment`. so in the end i couldn't conclusively isolate this as the fault of the redirect.

I do agree that adding a step that checks the actual downloaded file for it's type would be a great step towards making this tool more robust, and which possibly could also possibly also resolve #675 . 

regarding the answer you linked, i see 
1. HTTP headers for the files in the sample feeds above: `Content-Type: audio/mp4`, and
2. this in the xml:
```
<enclosure [...] type="audio/x-m4a"></enclosure>
```

however both of those suppose that people have correctly configured their servers, and we also see that filenames can be busted by redirects. really the best would be to somehow actually check the file, but who knows how difficult that would be in python.

**Comment by Robbt** [comment]
So I opened up a bug with liquidsoap for this. I suspect that libfaad is having issues with the dash format produced by youtube - https://github.com/savonet/liquidsoap/issues/713

**Comment by Robbt** [comment]
It looks like using ffmpeg for liquidsoap is the suggested solution from @toots is this possible with the new 1.3 liquidsoap debian package @paddatrapper ? He suggests that it is with opan and I figure it is not with the 1.1.1 package.

**Comment by paddatrapper** [comment]
It is possible with Liquidsoap 1.3.4, but I'll only be able to package it once Buster is released

**Comment by Robbt** [comment]
So this is an issue with liquidsoap that we can't fix directly and it basically involves m4a pulled from youtube videos.
