### ISSUE TITLE
Bug in API controller

### ISSUE THREAD

**Issue by mikeopensauce** [LibreTime/libretime#726]
I have discovered a bug in the API controller and I have fixed it in my installation.
I'm now sure how we go about changing code, nor do I think I am worthy, but here are the changed items. It causes request for the on-air-light to give a 500 error.
/usr/share/airtime/php/airtime_mvc/application/controllers/ApiController.php
Missing $request = $this->getRequest();
References to current and currentshow should refer to $range["tracks"]["current"]

Code should read

```
//Used by the SaaS monitoring
    public function onAirLightAction()
    {

        $request = $this->getRequest();
        $this->view->layout()->disableLayout();
        $this->_helper->viewRenderer->setNoRender(true);

        $result = array();
        $result["on_air_light"] = false;
        $result["on_air_light_expected_status"] = false;
        $result["station_down"] = false;

        $range = Application_Model_Schedule::GetPlayOrderRange();

        $isItemCurrentlyScheduled = !is_null($range["tracks"]["current"]) && count($range["tracks"]["current"]) > 0 ? true : false;

        $isCurrentItemPlaying = $range["tracks"]["current"]["media_item_played"] ? true : false;

        if ($isItemCurrentlyScheduled ||
            Application_Model_Preference::GetSourceSwitchStatus("live_dj") == "on" ||
            Application_Model_Preference::GetSourceSwitchStatus("master_dj") == "on")
        {
            $result["on_air_light_expected_status"] = true;
        }

        if (($isItemCurrentlyScheduled && $isCurrentItemPlaying) ||
            Application_Model_Preference::GetSourceSwitchStatus("live_dj") == "on" ||
            Application_Model_Preference::GetSourceSwitchStatus("master_dj") == "on")
        {
            $result["on_air_light"] = true;
        }

        if ($result["on_air_light_expected_status"] != $result["on_air_light"]) {
            $result["station_down"] = true;
        }

        $this->returnJsonOrJsonp($request, $result);
    }
```

**Comment by Robbt** [comment]
Thanks for the bug report and fix, I'm not sure based upon your issue when exactly this big occurs and does it always happen or just under certain circumstances.

So you are definitely worthy of making a chance to the code but whether you want to spend the time to understand git and how to do a pull request aka PR is up to you. Basically to contribute you would need to create your own Fork of LibreTime and then open up a new branch for this fix and commit and push the change and then your Github page for your fork will open up a dialogue to ask if you want to make a PR. You can open that and then we can easily test, review and merge it if it doesn't need any changes.

The benefit to this is that you would get credited as a contributor to LibreTime on our github page and it's less work for us but depending upon how much you want to invest in this it might not make sense. If you do think that you will be making other code fixes and changes it would be awesome to welcome you as a contributor and so learning the PR process would make that happen. here's a [tutorial](https://reflectoring.io/github-fork-and-pull/) I found but in general just looking at PR fork & pull would make sense.

**Comment by Robbt** [comment]
Hey Mike, I'm going to reopen this so that we can remember too look into it and also mark it as closed if and when you submit a PR.
