### ISSUE TITLE
Problem of API key

### ISSUE THREAD

**Issue by TinQuen57000** [LibreTime/libretime#727]
Hi, I've got a problem with my Libretime station.

When the station needs to read a track, everything stops and the red button "Live" stops and nothing works.
We also have the problem when "webstream" change (we have 3 studios in North East of France).

I've got a problem on my zendphp.log but I don't find how to resolve it : 

`2019-02-04T16:50:13+01:00 ERR (3): airtime.radiocampuslorraine.com [ErrorController.php:26 - errorAction()] - Incorrect API key
2019-02-04T16:50:13+01:00 ERR (3): airtime.radiocampuslorraine.com [ErrorController.php:27 - errorAction()] - #0 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Plugin/Broker.php(309): Zend_Controller_Plugin_Acl->preDispatch(Object(Zend_Controller_Request_Http))
#1 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(941): Zend_Controller_Plugin_Broker->preDispatch(Object(Zend_Controller_Request_Http$
#2 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#3 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#4 /usr/share/airtime/php/airtime_mvc/application/airtime-boot.php(84): Zend_Application->run()
#5 /usr/share/airtime/php/airtime_mvc/public/index.php(68): require_once('/usr/share/airt...')
#6 {main}
2019-02-04T16:50:13+01:00 ERR (3): airtime.radiocampuslorraine.com [ErrorController.php:54 - errorAction()] - An internal application error has occurred.: Zend_Controller_Exception$
Stack trace:
#0 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Plugin/Broker.php(309): Zend_Controller_Plugin_Acl->preDispatch(Object(Zend_Controller_Request$
#1 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(941): Zend_Controller_Plugin_Broker->preDispatch(Object(Zend_Controller_Request_Http$
#2 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#3 /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#4 /usr/share/airtime/php/airtime_mvc/application/airtime-boot.php(84): Zend_Application->run()
#5 /usr/share/airtime/php/airtime_mvc/public/index.php(68): require_once('/usr/share/airt...')
#6 {main}`

Please help us, our radio station looks like so unprofessional with this bugs :(

System infos : we are on ubuntu, with Libretime b79af94.
I'm so sorry for my English.

Best, Quentin.

**Comment by Robbt** [comment]
Hmm your API key seems wrong. Can you see if there is an api_key in your /etc/airtime/airtime.conf file ? - you shouldn't post it here, but just see if there is something in there that looks like a random string.

That is what 

Did you upgrade from Airtime to LibreTime ? Are there any additional files in /etc/airtime perhaps left over from the airtime that might be conflicting.

Also I'm not clear when this is occurring. Does your broadcast work sometimes or is it always broken at this point ?

It could be that rabbitmq is trying to use an incorrect key and you are running into an issue with upgrading from Airtime that we haven't fully explored. There used to be a /etc/airtime/rabbitmq-analyzer.ini file but that was replaced with /etc/airtime/airtime.conf and the contents were merged.

You might want to look into other logs in /var/log/airtime/pypo/pypo.log and see if it is showing more errors.

Hope that this can help you get to the bottom of it. We still haven't fully tested upgrading from Airtime 2.5.x so if that is indeed what you have done perhaps we can help you get it up and running. LibreTime is still underfunded volunteer ran alpha quality software and we are working as hard as we can to improve it.
