### ISSUE TITLE
Widgets missing

### ISSUE THREAD

**Issue by hopfrogsalerno** [LibreTime/libretime#751]
Libretime is installed on a VPS with Debian9. After a normal OS upgrade, widgets disappeared. Everything else works well. What could be the problem? Thank you

**Comment by Robbt** [comment]
I need more information. What do you mean by disappeared ? Specifically which widgets. Do you mean they disappeared from the site you embedded them on or the widget section of LibreTime ? 

Have you tried looking into the LibreTime widget code and see if it comes up. What kind of errors if any do you see if you ended the widget on blank html page ?

Do you see any errors in zend-php.log

**Comment by Robbt** [comment]
I'm going to close this because we need more information to troubleshoot it. Feel free to ask again with more information or re-open it.
