### ISSUE TITLE
apache2 error.log after install: PHP Fatal error:  Declaration of Zend_Rest_Route::assemble(...) must be compatible with Zend_Controller_Router_Route_Module::assemble(...)

### ISSUE THREAD

**Issue by synthead** [LibreTime/libretime#757]
**Describe the bug**
After installing LibreTime on Ubuntu 18.04 LTS via `sudo ./install` (as noted in [the documentation](https://libretime.org/install/) and performing the setup tasks in the browser, this line is written to Apache's `error.log` when attempting to load AirTime:

```
[php7:error] [pid 12578] [client 127.0.0.1:40152] PHP Fatal error:  Declaration of Zend_Rest_Route::assemble($data = Array, $reset = false, $encode = true) must be compatible with Zend_Controller_Router_Route_Module::assemble($data = Array, $reset = false, $encode = true, $partial = false) in /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Rest/Route.php on line 52, referer: http://localhost:8080/?config
```

**To Reproduce**
1. Have a 18.04 LTS server ready.
2. Download and extract LibreTime `3.0.0-alpha.6` from [the releases](https://github.com/LibreTime/libretime/releases)
3. Run `sudo ./install` and answer `y` to all the prompts.
4. Open http://localhost:8080 in a browser and follow the steps to ensure LibreTime can connect to PostgreSQL and RabbitMQ.
5. Click the "Open AirTime" button (forget what it said exactly) to complete setup.
6. Observe that a black page is returned and that this error is written to Apache's `error.log`:
   ```
   [php7:error] [pid 12578] [client 127.0.0.1:40152] PHP Fatal error:  Declaration of Zend_Rest_Route::assemble($data = Array, $reset = false, $encode = true) must be compatible with Zend_Controller_Router_Route_Module::assemble($data = Array, $reset = false, $encode = true, $partial = false) in /usr/share/airtime/php/vendor/zendframework/zendframework1/library/Zend/Rest/Route.php on line 52, referer: http://localhost:8080/?config
   ```

**Expected behavior**
LibreTime opens.

**LibreTime version:**
3.0.0-alpha.6

**Installation method:**
 - OS: Ubuntu
 - OS Version 18.04 LTS
 - Method: `sudo ./install`
 - Details: Called the install script with `sudo`, got `.tar.gz` file from GitHub

**Comment by Robbt** [comment]
Yeah the Zend 1 framework does not support Php 7.2 and above. At some point @hairmare will do a alpha.7 release which switches us to a forked library that contains fixes to make LibreTime work. At this point you can use the master release or wait for alpha.7 to come on. I'm going to close this as it is already been fixed in the master.
