### ISSUE TITLE
LibreTime 3.0.0-alpha.6 on Ubuntu 18.04 Blank Page

### ISSUE THREAD

**Issue by maydo** [LibreTime/libretime#758]
Hello,

after some reading, i think this is related to this issue
https://github.com/LibreTime/libretime/issues/580

I have installed LibreTime 3.0.0-alpha.6 (Tarball Installation) on a fresh Ubuntu 18.04 virtual machine
and running into a blank page

is there any fix for that ?
or should i go for Ubuntu 16.04.

**Comment by Robbt** [comment]
Yes you just need to use the GitHub master branch or wait for alpha.7 to be released.

**Comment by maydo** [comment]
how can i do the installation from github master branch on a fresh ubuntu 18.04 ?

**Comment by maydo** [comment]
its working

i just run the uninstaller, cloned from git and run installer again in the clone
seems fine now on ubuntu 18.04

**Comment by Robbt** [comment]
great. going to mark this as closed.
