### ISSUE TITLE
"Show/Find in Tracks" from Scheduled List

### ISSUE THREAD

**Issue by maydo** [LibreTime/libretime#761]
Hi,

an right click option for Finding in Tracks for a specific track from scheduled list would be nice
for editing tracks this would be a nice workflow

**Comment by hairmare** [comment]
Hey @maydo 

Sorry for the late response.

Do I understand you correctly: You want to right-click on a track and then have the option to see in which programs the track has been scheduled/played.

Or is it the other way around?

Feel free to create a pull request that implements what you need. We would be glad to merge it after appropriate review.

If you don't feel up to writing a pull request, maybe you could help by visualizing your feature request with some screenshots with "paint style" notes on them to help us understand your idea.

Thanks for being aboard "Team LibreTime" in any case!

Cheers,
Lucas
