### ISSUE TITLE
Listeners stat does not work

### ISSUE THREAD

**Issue by tuktukvlad** [LibreTime/libretime#762]
**Describe the bug**

Hello! Listeners stat does not work. Previously, everything was fine. Any ideas?

**To Reproduce**
1. Go to 'Listeners stat'
2. See error

**LibreTime version:**
3.0.0 alpha 4

**Installation method:**
 - OS: Ubuntu
 - OS Version 16.04.5 LTS (Xenial Xerus)
 - Method: `./install`
 - Details: Git clone

**Screenshots**
![scr](https://user-images.githubusercontent.com/22128719/53693419-1efe5180-3db1-11e9-9bc8-45864207242c.PNG)

**Client (please complete the following information if applicable):**
 - OS: Win 10
 - Browser chrome
 - Version 70

**Comment by Robbt** [comment]
It is working for me so it isn't universally broken, can you look at your zendphp.log and find any error messages.

Also did you upgrade versions or make any other changes that might have caused it to break ?

Have you tried it with different browsers to make sure it isn't a browser-specific issue, look at your javascript console and see if any of the javascript is erroring out.

**Comment by Robbt** [comment]
I'm going to close this. Feel free to re-open if you have more information to help us reproduce it.
