### ISSUE TITLE
Cut a new release that includes fix for "300k empty playlists" bug

### ISSUE THREAD

**Issue by synthead** [LibreTime/libretime#767]
Now that https://github.com/LibreTime/libretime/issues/411 (and https://github.com/LibreTime/libretime/issues/743) is resolved, can we cut a new release?  Our radio server is having this issue on a daily basis, and we've even catered to the workarounds, so we're not sure what's going on.  It'd be great to `dpkg -i` a new libretime deb that solves this issue!

**Comment by Robbt** [comment]
So the debian packages are built by @paddatrapper and @hairmare has been the one to cut every release so far, so feedback from both of the would be essential for this to move forward.

**Comment by paddatrapper** [comment]
I would like to get Buster support in, but that isn't crucial considering it isn't released yet. When a new release is made, I'll update the packages

**Comment by synthead** [comment]
Awesomeeeeee, thank you @paddatrapper!  @Robbt, can we cut a new release?  Happy to help if I can throw in hands :raised_hands:

**Comment by Robbt** [comment]
Before we cut a new release I want to do some more testing to make sure that the database updates don't need to correspond to the release version to be automatically deployed. Also I'd rather not do the release without @hairmare unless he isn't able to for some reason. 

If you just want to fix this problem, the easiest thing to do is just make sure that you don't have any autoloading playlist enabled with None selected as the playlist. Sorry about this bug and hopefully we can get a new version out. I'm not sure how installing a deb on top of a working install would work either.

**Comment by synthead** [comment]
@Robbt, how's the testing going?  Thanks so much for doing this!

**Comment by Robbt** [comment]
I have not gotten around to testing this. I was at the FSF LibrePlanet conference over the weekend and I'm just working on getting situated. I'll try to prioritize this. I got a lot of inspiration for how we can move forward with LibreTime in general.

**Comment by guythnick** [comment]
++ to @Robbt  , thanks for your dedicated work on this.  Will be happy to test a new release for this fix.  I've put in my own workarounds, but they are quite sloppy.  
Truly respect your dedication to this project!

**Comment by paddatrapper** [comment]
We are planning on releasing alpha.7 once the two PRs listed in [milestone 8](https://github.com/LibreTime/libretime/milestone/8) are merged. #781 just requires testing and #784 can be merged once #781 has landed

**Comment by Robbt** [comment]
So #781 has been closed because it wasn't the right approach and I haven't been able to duplicate the bug it was attempting to fix. I would like my bug fix in #802 to be merged but then we can push the release w/ updated information.

**Comment by paddatrapper** [comment]
I've merged #802, just need to update the release notes

**Comment by paddatrapper** [comment]
(which I am busy doing at the moment)

**Comment by Robbt** [comment]
Ohh I just did that. Sorry.

**Comment by Robbt** [comment]
I also added a contributors section where we list the various users who contributed PRs to this release.

**Comment by paddatrapper** [comment]
No worries, I have merged the changes I made into yours.

**Comment by paddatrapper** [comment]
Released :tada: deb packaging will follow in the next day or so
