### ISSUE TITLE
Mixcloud integration

### ISSUE THREAD

**Issue by gusaus** [LibreTime/libretime#769]
**Describe the solution you'd like**
[Mixcloud](https://www.mixcloud.com/) is an online music streaming service that allows for the listening and distribution of radio shows, DJ mixes and podcasts.

Provide a way to publish your pre-recorded live events or uploaded DJ Mixes directly to your Mixcloud profile with just a few clicks. 
 * publish a DJ mix you have uploaded to LibreTime
 * publish a live recording made within LibreTime
 *  enter and edit Mixcloud metadata such as description, picture, tags

**Describe alternatives you've considered**
* Airtime had basic Mixcloud Integration in the works but it was never completed - https://github.com/sourcefabric/airtime/pull/46

**Additional context**
* Radio.co provides a good example of functionality that would be good to have - https://help.radio.co/live-broadcasting/publish-your-live-recordings-and-dj-mixes-to-mixcloud

**Comment by Robbt** [comment]
Thanks for finding this Gusaus. I agree MixCloud integration would be a killer feature. At least one station here in town using LibreTime also encourages their producers to use MixCloud for syndicating their livestreams.
