### ISSUE TITLE
Song requests from API

### ISSUE THREAD

**Issue by Wurden** [LibreTime/libretime#770]
Hi I'm currently a user of SAM Broadcaster, which was the best solution at the time when we started our hobby radio. I've also been looking at RadioDJ but it doesn't seem to provide a vastly different overall experience, they both only run on Windows.
I would really love to switch completely to open source and run our radio on Linux and so I found LibreTime. It looks like a great automation solution kudos!

I have one feature that I would be really missing from SAM or RadioDJ, which is the ability to request any song in the playlist of the radio.
In SAM Broadcaster they have a solution where you call an API endpoint with a song ID, the requested song is then added to the bottom of the play queue.

SAM also uses a set of rules called "request policy" where you can define that the same artist can't be requested within x minutes, the same track can't be requested in x minutes and so on.

Would it be possible to add a song request feature to libretime?
If yes, I might be interested in developing it myself if you can suggest where and how you would implement it.
Thanks.

**Comment by Robbt** [comment]
Ok, so this is an interesting idea but it would not be trivial to implement. The first challenge is that LibreTime unlike a lot of other automation systems is built primarily with a hard division between shows. 

Each show exists on the schedule for a certain amount of time and is typically programmed ahead of time by the DJs or producers (unless they are doing live). But LibreTime does have the ability to upload tracks onto an ongoing show and even alter the schedule, change the play order of tracks etc. So it isn't impossible for something like this to happen.

LibreTime is kind of ideal for stations where a number of different DJs collaborate to build a schedule and there are certain programs that need to air at certain times such as news programming etc. We make it really easy to syndicate shows from RSS and also livestream other stations at a certain time.

There is another open-source automation system that is designed to be more interactive and already has the requests feature that is [AzuraCast](https://github.com/AzuraCast/AzuraCast)

While I don't want to dissuade you from checking out LibreTime, we don't currently have a very highly specified API, we don't have a well documented end-user accessible list of tracks and IDs (without providing a guest login) although I think that there is now a media/feed it still requires authentication and is just unstructured JSON. 

So yeah if you wanted to contribute to LibreTime we are always welcoming new developers, the software stack is a little stale being built with Zend 1 MVC (EOL as of 2016) and jQuery AJAX. At the same time it does offer a lot of nice features that you may have seen already while playing around with it. But feel free to checkout AzuraCast and see if it is a better fit for your needs if the request feature is essential.

**Comment by Wurden** [comment]
@Robbt thanks for the quick reply. It isn't trivial in SAM Broadcaster either and I have spent a great deal of time customizing the frontend for our needs, fully integrated in the Drupal CMS. Check out italosound.com if you're interested.

I kinda figured about the API, as the only documentation I could find was the code itself 😄
We are a radio that mainly plays randomly selected music from a playlist, not a great deal of shows yet, that's why the request feature is such a neat feature. I'll check out AzuraCast too and see how it compares, thanks a lot for the suggestion!

**Comment by lZzozZl** [comment]
I think feature like this will turn allot of heads towards libretime.
