### ISSUE TITLE
Provide a way for smartblocks to return unplayed tracks

### ISSUE THREAD

**Issue by frecuencialibre** [LibreTime/libretime#775]
**Is your feature request related to a problem? Please describe.**
I'm trying to program multiple irregularly published podcasts in a single show. For this, I'd like to be able to configure a smartblock to return content that has never been played. Unfortunately none of the modifiers available for the `Last Played` search criteria seem to be able to do this, not even `is not`. 

**Describe the solution you'd like**

1. One possibility would be to provide a "never" modifier to the `Last Played` criteria. 
2. Another would be add `null` capable "not after" and "not before" negated modifiers: This would perhaps be more intuitive for folks, but you'd have to reason that in order to get tracks that have never been played you'd have to set it to "not before" 1 minute ago. 
3. both 1 and 2

How's this sound from a UI perspective?

Additionally, the `is` and `is not` modifiers to `Last Played` seem to have no effect. Can anyone reproduce this?

Thanks!

**Comment by Robbt** [comment]
I'd think 1 would be easier to implement and easier to explain how to use.
I'm ok with 2 as well but think that the workflow is more complex to describe but it could be useful in other ways.

Also it would be nice if we had a playcount for tracks but that isn't implemented at all.

In addition it might be useful to allow smartblocks to be sorted by last played in addition to upload date (newest)

**Comment by Robbt** [comment]
Ok, my thoughts on this are that the easiest way to solve this is by adding a sort by the "last played date".
or sort by 'played most recently' or 'least recently played' - which would include all of the items that have never been played or have null in that column. This would basically accomplish what is requested above and would also not result easily in null values after an item had been played it would just be cycled to the back of the sort order and something else would replace it.

**Comment by Robbt** [comment]
So after a far amount of wrangling this, there appears to be no way of including NULL values in the sort order of the propel ORM addAscendingOrderByColumn('lptime').
I tried adding a column via coalesce to add a default value to lptime when it is null but was unable to do this with a simple override.

With postgresql there [is](https://www.postgresql.org/docs/9.4/queries-order.html) actually a suffix NULLS FIRST or NULLS LAST that can be added to a query but propel 1.7 doesn't support this.

So at this point the only way to implement this that I can tell would be to add a default value of say '1970-01-01' to every entry in cc_files for lptime and then we could sort and files that had the default value  would come first and then have their value updated once they were played.

We could do this to existing installs via a database update. Wanted to see if anyone else had feedback or ideas on this.
