### ISSUE TITLE
Setup Weblate translations integration

### ISSUE THREAD

**Issue by hairmare** [libretime/libretime#78]
I'm still torn about deciding to integrate https://github.com/LibreTime/libretime/commit/2e9583c687b6c4922d3160bc32be1642b92b1be1 from 2.5.x. There absolutely needs to be some automation to keep translation working and up and running, I'm pretty sure we have some russian customers that will greatly appreciate us not breaking this.

While transifex is free for opensource, it looks like http://zanata.org/ from redhat is actually the more libre way to go. I think our setup is pretty close to a podir config as per [the zanata docs](http://docs.zanata.org/en/release/user-guide/projects/podir-example/).

If no one has a better proposal (I would actually prefer a solution that allows github logins) I'll do some testing on my branch with real zanata and then open a pr when it looks ready.

* [x] configure zanata and push initial strings
* [ ] push new strings to zanata using travis
* [ ] pull translated strings into github repo and/or release tarballs

Fixes #107

**Comment by hairmare** [comment]
I set up a zanata for LibreTime and tested it by round-tripping some de-DE strings. It may be found at https://translate.zanata.org/iteration/view/libretime/master.

I have the maintainer tooling somewhat prepared on a branch and am looking into how we can automate this through travis. I'll also have to test the install a couple of times so I don't break anything.

For now the zanata is useable, but you need to ping me if you want any changes to be pulled back into the LibreTime GitHub.

**Comment by hairmare** [comment]
This is raising some questions over here 😕.

1. When should we push strings to zanata? After each merge to master or on each tag.
2. When do we want to pull strings from zanta? Should they get auto committed?

I think legacy upstream had a cronjob or similar for pulling strings. Zanata has [webhooks](http://docs.zanata.org/en/release/user-guide/projects/project-settings/#webhooks) but I only see one for 100% translated events.

I'm not sure I'm a fan of auto committing, IMO preferably zanta would create pull requests so we can hold off if we are sure some bad strings slipped in. It might also make sense to just bake a zanata pull into the release tarball and to update strings in the repo manually right before regenerating and pushing new ones.

Also, should regenerating strings be part of a PR that touches such strings or do we bundle multiple string changes into one run of the gettext tools?

**Comment by jooola** [comment]
Zanata seems not maintained anymore, I propose to use Weblate https://weblate.org/en/.

**Comment by jooola** [comment]
I created the project here https://hosted.weblate.org/projects/libretime/

The weblate admin will only have to approve our subscriptions as an open source project within a week.

I can now upload the locales to weblate once we scanned the source files again.

**Comment by jooola** [comment]
I don't know who has an account on weblate, but I am happy to promote anyone as maintainer once I have your account name or email.

**Comment by paddatrapper** [comment]
Does the integration need to be enabled before or after #1402 is merged?

**Comment by jooola** [comment]
The integration can be added anytime, I haven't configured any translation component yet.

**Comment by jooola** [comment]
#1402 Is actually a cleanup/update PR, I'll rename it. But it is required before I can configure the translation component on Weblate.

**Comment by paddatrapper** [comment]
The integration is installed

**Comment by jooola** [comment]
We still have some alerts to fix https://hosted.weblate.org/projects/libretime/legacy/#alerts 

Does the weblate app have few buttons to turn ? I don't have access to the app. So I am asking.

**Comment by jooola** [comment]
Cool I'll try to find a way to fix the latest issue, but I can't seem to find why this last alert is still here.

I don't know how we want to proceed, but now that the translation integration is open, we should decide how we want to handle translations PRs.

Do we review them ? De we let them sit a bit before merging, or do we simply do a quick review and fast merging ?

**Comment by paddatrapper** [comment]
I've been giving them a once over, but I can't really do review on anything except English, Afrikaans and a smattering of Dutch. Perhaps letting them sit for a couple days is a good idea

**Comment by paddatrapper** [comment]
We also need to add translation guides to the various documentation points

**Comment by jooola** [comment]
I know Weblate is able to improve the quality of the translation by adding extra steps before accepting a translated string.

A string could require at least 2 translator to verify it in order to make it a accepted. Only then will it be pushed to Github.

Right know, I think any Weblate translator is able to contribute to the translations, this is awesome, but might be risky if those translations are accepted right away.

Also I noticed that a lot of strings are split into multiple chunks, which is a really hard way of translating as you get to translate chunk after chunk.

Ideally, **new code** will have to use **string templates** and not string concatenation.

Yes, regarding the documentation I'll try to refresh the existing one and add some key points in a PR.
