### ISSUE TITLE
List LibreTime on alternativeto.net

### ISSUE THREAD

**Issue by SlvrEagle23** [LibreTime/libretime#782]
Howdy, LibreTime dev team!

My name's Buster and I'm the lead developer for a FOSS piece of radio software called AzuraCast. I wanted to take some time today to stop by and say hello, show my support for my fellow FOSS developers and mention one minor thing.

First of all, a huge thank you to the whole team here for keeping the open-source legacy of AirTime alive after SourceFabric discontinued their own FOSS project. I'm a big believer in the power of open-source to be the great equalizer, allowing great things to be used by people regardless of their income or means.

I've seen that LibreTime excels in schedule-driven station management and I've sent a number of prospective users your direction as a result, and I know that for other use cases your team has referred to AzuraCast, and I really appreciate the openness and kindness that exists between our projects, even if we don't directly talk. We're all in it for the interest of serving the greater good, so the more we can support one another, the better.

Anyway, on to my actual point. I was looking through my analytics today and noticed that a fair amount of traffic is coming to my site through a site called [alternativeto.net](https://alternativeto.net). I've used the site before myself when looking for FOSS alternatives to software, and it helps direct a lot of people toward free and open-source options they wouldn't have otherwise known about.

AirTime is listed as an alternative in the webcasting space, but it's listed as "Discontinued" since SourceFabric focused specifically on the commercial offering. It might be useful for your project to be listed there as well, so people looking for alternatives to the closed-source, proprietary commercial providers can find every option in one place.

I know it's a small suggestion, but really I just wanted to stop by and show a little appreciation. I know first-hand how hard FOSS projects can be to maintain, and how thankless that work can seem sometimes. Here's to keeping web radio free and open to everyone. <3

**Comment by Robbt** [comment]
Thanks for the suggestion. I went ahead and added LibreTime to the list as an alternative to AzuraCast & Airtime. We appreciate what you are doing over there as well and we were considering reaching out a while ago to see if and how we might be able to collaborate. At this point it seems like both projects have their distinct strengths and so it probably mostly makes sense to spread awareness of each other as alternatives for people who are seeking a distinct solution.

Thanks for coming over to say hello.

**Comment by gusaus** [comment]
Weclome @SlvrEagle23! 

Slightly off topic, but I wanted to reference https://github.com/opencollective/opencollective/issues/1864#issuecomment-477392802 as it's related to how these projects could potentially benefit from both x-promotion and sharing resources via Open Collective.

As mentioned in https://github.com/opencollective/opencollective/issues/1864#issuecomment-477399887, there's been a recent push by the Open Collective team to onboard and sustain projects and we've set up a #communitymedia channel in https://opencollective.slack.com/ to bring collaborators and contributors together.

**Comment by Robbt** [comment]
So this has been done but we could use good Screenshots and an Intro Video.
