### ISSUE TITLE
Replace Airtime.pro has a new look modal with LT information/changes

### ISSUE THREAD

**Issue by Robbt** [LibreTime/libretime#783]
**Describe the bug**
When you upgrade LibreTime from Airtime you get presented with a modal that says
Airtime Pro has a new look!

**To Reproduce**
Install Airtime 2.5.1 via deb
Upgrade to LibreTime
Login to your instance and you see it

**Expected behavior**
We should replace this with our own modal or just disable it.

**LibreTime version:**
Latest git with database schema fix PR

**Comment by Robbt** [comment]
Here is the code
https://github.com/LibreTime/libretime/blob/adb8d8c01d7a392512ded62f1a282dbebd6df3cf/airtime_mvc/application/layouts/scripts/layout.phtml#L189-L236

It is never shown to new stations and I don't think we trigger it to be reseen so it will only show up for people updating from an existing Airtime install. Here is the code that triggers it.

https://github.com/LibreTime/libretime/blob/adb8d8c01d7a392512ded62f1a282dbebd6df3cf/airtime_mvc/application/models/Preference.php#L1544-L1553

The question is do we want to repurpose it for LibreTime and maybe use it to announce new features of new releases ? Or should we just disable it ?

**Comment by paddatrapper** [comment]
Announcing important new features may be useful, but should be used very sparingly

**Comment by Robbt** [comment]
I'd say that we could try using this everytime we put out a new release, it should only pop up once and it could include the release notes and a video guide to what has changed. This would be an extra bit of effort and probably wouldn't have much impact on regular users since we don't even have a recommended way to upgrade.

But I suspect all we would need to do is set the pref "whats_new_dialog_viewed" to false via the upgrade SQL and change the contents of this part of the template. I think the purpose of it originally was to kind of explain to SaaS customers why the entire interface was different when they went from airtime 2.5.x based to the saas-dev branch that we forked from. And that was an abrupt change.

We could just make it point to an intro to LibreTime video and have it show up for all new instances as a way of directing people to an intro to LibreTime. Either way just some thoughts I am not strongly tied to any of them in particular. I do plan on putting together a basic intro to LibreTime screencast. I'll be sharing my draft first recordings on the wiki as well as the scripts. Then we can figure out how to integrate it into the main docs and any corrections/re-recordings I might want to do.

**Comment by paddatrapper** [comment]
Hmm... I think a welcome to LibreTime popup when first installed is a good idea. As for displaying on updates, maybe on feature and major updates. So if we are following semantical versioning: X.Y.Z, always have a popup for changes to X, but only for important changes when incrementing Y and never when incrementing Z. I am reluctant to over-use it, mainly because I know I get annoyed by seeing modals frequently...

Perhaps getting it to read from a changelog file? That way we can minimise the duplication of release notes - note them in the changelog file and flesh them out for the GitHub release notes.

**Comment by Robbt** [comment]
Cool. Yeah I do think we should figure out a way to make our release notes more visible. They have been of high quality but sometimes you have to dig to find them. There should probably be a link to them on the main README and possibly front page of libretime.org especially if they contain known issues etc.

**Comment by Robbt** [comment]
This should be easy for someone to replace with a readme or basic information about libretime or even pull it from the release notes - here is where the code is called that makes this show up. At a minimum replacing the text would be a nice and easy way to make the airtime.pro text disappear and a simple contribution. 

https://github.com/LibreTime/libretime/blob/50ca96156ef1962ea79ef1172ca81084529ff7a4/airtime_mvc/application/layouts/scripts/layout.phtml#L170-L189
