### ISSUE TITLE
Make listeners statistics available to other users type than Admin

### ISSUE THREAD

**Issue by nixhol** [LibreTime/libretime#786]
At the moment listeners stats are only available for Admin user type. At least Program Manager users (and maybe DJ) should be allowed to see it.

They are people organizing show schedule and content, so they are the people organizing the broadcast. Listeners statistics is very interesting for them.

**Comment by Robbt** [comment]
I agree, the statistics are useful and in need of improvement. This should be a relatively small change. I'd say that we at least give program manager access and then we could consider DJ in the future perhaps when we can get granular access and/or show specific listener stats. I'm not opposed to the DJ getting access but I can imagine that some stations might not want their DJs to be able to access listener stats.

We almost have enough triggers that it is worth considering allowing the admin to give certain roles specific permissions via a UI checkbox interface but that would also complicate the setup and administration in general so sane defaults are probably best for now.
