### ISSUE TITLE
Problem: Radio Page player doesn't play sound

### ISSUE THREAD

**Issue by Robbt** [LibreTime/libretime#79]
The player on the front page before you login doesn't produce sound for me when I click play. The internal listen/preview functionality works so hopefully it is something simple.

**Comment by hairmare** [comment]
Are you sure that liquidsoap hasn't crashed? I'm listening to my dev box through it right now.

**Comment by Robbt** [comment]
Ok, I will check it again. I'm currently working on the LiveStream preferences UI/liquidsoap config reversion.

**Comment by korotkov13** [comment]
I got the same on macOS safari, but I think it's safari's issue. after updating it's working.

**Comment by hairmare** [comment]
I can confirm that it doesn't work on Safari 10.0.3. @korotkov13 did you update safari? I'm still on OSX and not on macOS yet.

**Comment by hairmare** [comment]
MP3 work on El Capitan 10.11.6 with Safari 10.0.3, Ogg/Vorbis does not.

The radio page cycles through all available streams so it will fall back properly if one of the streams is mp3.

**Comment by korotkov13** [comment]
I tested it with mp3 stream. I think the problem is with safari cache. If I clean it, it start working.
Or I need to relaunch safari.
@hairmare  I use the latest OSX and safari

**Comment by hairmare** [comment]
I'm gonna close this when I release 3.0.0-alpha-1. Let me know if you feel I shouldn't.

**Comment by korotkov13** [comment]
@hairmare ok.)
