### ISSUE TITLE
Proposal: Formalize documentation as requirement for every PR that adds a new feature

### ISSUE THREAD

**Issue by Robbt** [LibreTime/libretime#794]
**Is your feature request related to a problem? Please describe.**
I would like for us to add a requirement that for a new feature to be merged it is required to add documentation to the manual. I'd also like to improve the basic documentation.

**Describe the solution you'd like**
The goal is to provide explanations and links to more in depth discussion of functionality without cluttering the UI. If something doesn’t make sense to someone they can click the UI.

I also would like for us to adopt the following criteria for the documentation in general. 

- For pages that document specific “sections” or pages of LibreTime there should be a help button included that links to page in the manual.

- The manual should include a write-up description of each option in the same order that it is presented in the UI.

- All sections should have a basic description of the functionality and if they are advanced a link to a more detailed page where the design justification and explanation is made.

- We add a tutorials section that contains links to relevant tutorials and encourage the creation of tutorials for complex new features that are added.

- Include a developer footnote section that links to the relevant code and/or PR where the features were added.

- All current bugs/issues that are relevant to the feature/section should have links embedded in the documentation

**Describe alternatives you've considered**
As an alternative It may make sense to create a release specific PR where all required doc changes are tracked and pushed to to so that the manual doesn't expect everyone to be running the latest version of libretime based upon the master and instead defaults to the latest release.

**Comment by paddatrapper** [comment]
I like this proposal.

For linking to bugs/issues, there would need to be a tag on bugs that are linked so that the bug note can be removed from the docs once the issue is closed. Maybe [manual-documented] that is then removed once the documentation is fixed to remove it. A comment with a link to the documentation page would also be helpful for tracking issues.

It would be useful to be able to select what version of the docs you are looking at - similar to how ReadTheDocs does it. It would only need to save docs from each git tag and the tip of master. Maybe defaulting to the latest release tag.

**Comment by hairmare** [comment]
Do we want to have something like [the Update Docs Probot](https://probot.github.io/apps/update-docs/) nag us?

We could fix the mkdocs generator to also publish old versions of the docs based on individual tags. A good time to do this would probably be when we start finalizing the new web-site for beta.

**Comment by Robbt** [comment]
I think that bot sounds like a good idea.

**Comment by hairmare** [comment]
I also remembered that we also need a [pull request template](https://help.github.com/en/articles/creating-a-pull-request-template-for-your-repository) and docs :tada: 

I guess this isn't a 3.0.0-alpha.8 blocker but something we might want to put in the 3.0.0 milestone. I'm removing the alpha milestone, feel free to re-add it or the 3.0.0 milestone.
