### ISSUE TITLE
Determine best hosting for LibreTime Tutorials

### ISSUE THREAD

**Issue by Robbt** [LibreTime/libretime#795]
**Is your feature request related to a problem? Please describe.**
I have developed a number of screencast tutorials that explain various features and I'd like them to be officially hosted by the project.

**Describe the solution you'd like**
We could setup a 3rd party host such as youtube or archive.org and then embed into mkdocs by modifying the javascript as described [here](https://github.com/mkdocs/mkdocs/issues/243) 

**Describe alternatives you've considered**
We could also setup a separate repo called tutorials on git and transcode them to webm and mp4 and include them video the <video> tag. Adding them to the main docs repo would increase the size of the main git repo too much.

**Additional context**
Currently the videos are unlisted on youtube on my personal account and available via the [wiki](https://github.com/LibreTime/libretime/wiki/Tutorials)

I would also like to credit the [Greater Columbus Arts Council](https://gcac.org) in the videos since they provided via a grant to my organization to pay me to develop documentation. We don't have a formal mechanism for mentioning sponsors but I'd like us to discuss that.

**Comment by paddatrapper** [comment]
As much as I prefer archive.org, I think YouTube would be the best to use here. That way people who require access can be granted it to upload and manage videos on a LibreTime channel without needing to know the main account credentials (As far as I know, team accounts are still possible). Adding an additional git repo would require coordinating PRs and git doesn't handle large binary files very well. Looking at what other projects to (Blender, Krita, etc), YT tutorials seem to be the way to go.

As for sponsorship mentions, perhaps a screen at the end of the video with logos of any sponsors that were involved in making that video? That way we can add YT call-to-action links to websites, etc. We can also add links in the video description.

**Comment by gusaus** [comment]
I also agree having a LibreTime YouTube account would be the best option. With regards to crediting sponsors, it would be ideal to document all the ways organizations and individuals can sponsor and support the LibreTime project. Sponsor/backer mention on videos, radio spots, podcasts, could be just a few of the ways in addition to the more traditional website credit. We could create a variety of goals and perks as well as a transparent process for collecting/distributing funds with a LibreTime Open Collective. https://discourse.libretime.org/t/opencollective-to-help-sustain-the-project-and-community/84

**Comment by b01xy** [comment]
1000001 thanks for Libretime doc, help and dev
For me at least Vimeo would already be better than youtube, co-publishing at the same time the videos on a more ethic plateform as archive.org or peertube.

**Comment by paddatrapper** [comment]
The issue with vimeo is that there is a size limit per week and year, and there seems to be no team account feature which would require sharing the username and password among multiple people, which is a recipe for disaster...

**Comment by Robbt** [comment]
Can anyone point me to how we actually create a shared channel for YouTube. I've never actually done it. Would we need to have a Google account to own it ? I think peertube and archive.org are good as alternative/backup locations. I'm ok with putting stuff on vimeo as well but it probably makes sense to use YouTube to maximize exposure as the existing LibreTime tutorials on YouTube have thousands of views and are I think are not in English so there is obviously an audience that is interested in learning this stuff. I am not against putting stuff on Vimeo as well. The create once publish everywhere is a good idea in my mind. But yeah if we can minimize sharing passwords etc that would be good. We could also setup our own video hosting using mediagoblin or something like that but this would require hosting and ongoing costs that we havent the infrastructure to facilitate payment for yet.

**Comment by paddatrapper** [comment]
One person needs to create a new channel by going to `Settings -> See all my channels or create a new channel -> Create new channel`. Once it is created, other managers can be added from the settings menu. I am happy to create and add people if that is the way we want to go.

Self-hosting could also be done using a Peertube instance, but I think we can look at that once we have some sort of way to support hosting costs.

**Comment by paddatrapper** [comment]
I have created a [YouTube Account](https://www.youtube.com/channel/UC-MA9GzkTb8th1YlDmF0NfA) for LibreTime. If anyone wants access, email me (github@paddatrapper.com) with your Google Account and I'll add you as a manager

**Comment by frecuencialibre** [comment]
https://vimeo.com/user90812787 libretime tutorials in spanish

**Comment by paddatrapper** [comment]
@frecuencialibre do you mind uploading those to the YouTube account too, or providing me the files to do so? It would be nice to include them with the English videos @Robbt has made
