### ISSUE TITLE
Bringing other radio related software under the LT banner

### ISSUE THREAD

**Issue by paddatrapper** [LibreTime/libretime#797]
I would like to move some of the projects I work on specifically for radio management to the LibreTime umbrella. The projects are:

- [Zebra Crossing](https://gitlab.com/zebra-crossing/zebra-crossing) - radio traffic (commercials) management system written in Python using the Django framework.
- [Top30 Creator](https://gitlab.com/paddatrapper/top30) - Rundown creator for chart show recap jingles and imaging written in Python using PyQt.

I think these project would benefit from the exposure that being associated with LibreTime has and LibreTime would benefit by having an ecosystem of open source applications around it that cater specifically for the radio and streaming industry. Thoughts?

**Comment by Robbt** [comment]
Can these projects integrate with LibreTime ? Can we use Zebra Crossing to manage spots in LibreTime ? Just hearing about these for the first time. What is the development history for these projects, are you the primary developer and did you create them initially ?

Curious about this. I'll post more about the idea of an ecosystem of open source applications under the open collective post.

**Comment by Robbt** [comment]
So it looks like based upon the commit history you are the sole developer of these and they're being used at your station right now. 

As someone installing them and trying to run them the workflow for how they work wasn't obvious but I think that a traffic management system would be a good thing to integrate into LibreTime as a way of managing spots.

Is ZebraCrossing primarily orientated to building a report and logging the commercials ? I wasn't able to figure out how to get time-slots connected to the campaign in terms of creating a log.

I'm not sure exactly how top30 worked as I couldn't get the GUI to work, and I don't think I have the file formats that are required to use the CLI. I opened up an issue with your gitlab.

They both seem like interesting projects so we should continue the discussion regarding how they can work with LibreTime.

**Comment by paddatrapper** [comment]
Yeah I am the sole developer. They both stem out of automating parts of my job that I find boring or repetitive. I no longer create the Top 30 chart run-downs, but the guy who does still uses Top30 to do so (and was the main reason the GUI was slapped on top). From next year I will be moving more into providing FLOSS solutions to various stations, so I expect these tools to grow and others to be written as I go. Of course it is all slow going to start.

Documentation is a little scarce... I try to document as I go, but there are holes that I miss just because I know the system inside out. Your efforts setting up and testing are useful in identifying those holes.

I would definitely like to integrate Zebra Crossing into LibreTime (exporting a schedule that can be imported into LT or something to that effect, open to ideas though). It is mainly focussed on tracking and reporting of commercials. Traffic bookings come it, are added to the system and it keeps track of what campaigns are currently flighting, coming up and have passed. I am working on getting it to automatically schedule spots based on time ranges, but I am stuck on how to represent it to the user in a flexible way. It is tracked in [#12](https://gitlab.com/zebra-crossing/zebra-crossing/issues/12). Our ads come in as a set of [date/day of the week, time range, number of spots] and I want Zebra Crossing to use that to calculate which ad break to place the spot in so that the ads for all campaigns are spread over the slots in the range (essentially filling the "hash" table of ad breaks).

Running Top30 should just be running `top30` from the command line. I plan on packaging it for Debian once Buster is released, after that it will appear as a desktop icon.

**Comment by gusaus** [comment]
@paddatrapper Would these projects play well with any other platforms on this list? https://github.com/opencollective/opencollective/issues/1864#issuecomment-477392802

**Comment by paddatrapper** [comment]
Well Top30 Creator creates a mp3 audio file that can be used anywhere that can play mp3s. Currently Zebra Crossing has no external output, but I would like to allow it to export a playlist scheduler file with instructions around when to play what. That could then be imported into Rivendell, LibreTime and Azuracast. As OBS, Mixxx and Audacity don't have scheduling capabilities, it won't be much use there. They also are targetting a different use-case and task

**Comment by gusaus** [comment]
@paddatrapper I should have specified with Rivendell, LibreTime, and Azuracast. All of the above, including these projects you're working on, could be included and supported via the Open Producer collective we're dusting off https://opencollective.com/openproducer
