### ISSUE TITLE
[Suggestion/Request] Streaming video formats (mp4 at least) with same libretime schedule functionality 

### ISSUE THREAD

**Issue by tarkank** [LibreTime/libretime#798]
Libre and Airtime was meant to stream audio formats, that's alright. But what about video formats since icecast, liquidsoap support it. Without changing any functional logic of Libretime (scheduling, playlist creation, watch folders etc.) could this be achieved by simply adding video mime types? I think this would be a very useful addition.

**Comment by Robbt** [comment]
You are welcome to experiment with this and share your results but this is not likely to be a simple modification. It would require touching the entire stack from airtime-playout, airtime-liquidsoap, airtime-analyzer and rewriting the web interface to handle video files.

**Comment by tarkank** [comment]
@Robbt Ok, didn't know it would need changes in these functions. Thought a mime-type change could be enough. Thanks for the answer.

**Comment by Robbt** [comment]
Yeah, I'm going to close this for now. Feel free to re-open if you have any results to share from experimenting with it. I know something like this would be valuable.
