### ISSUE TITLE
Expose Sources Info via live-info-v2 API end point.

### ISSUE THREAD

**Issue by detobate** [LibreTime/libretime#799]
**Is your feature request related to a problem? Please describe.**
It'd be useful to know what "type" of show is currently playing.  I.e. is the source a live DJ, or a pre-scheduled show,  to allow 3rd party scripts/tools do things differently.

**Describe the solution you'd like**
Expose the livedj, masterdj, and scheduledplay source status via the existing live-info-v2 API endpoint.

**Describe alternatives you've considered**
I manually add this to my Libretime installations currently, thought I'd suggest it upstream.

**Additional context**
e.g.

  "sources": {
    "livedj": "off",
    "masterdj": "off",
    "scheduledplay": "on"
  }

**Comment by Robbt** [comment]
Thanks for the PR this was fixed with #800
