### ISSUE TITLE
Contributing: Translation Portuguese (Portugal) (pt_PT)

### ISSUE THREAD

**Issue by LordFader** [LibreTime/libretime#817]
European Portuguese: PT

**Comment by LordFader** [comment]
I would like to contribute to translate Libretime for Portuguese PT.

**Comment by hairmare** [comment]
Hi @LordFader 

Sorry for my late response. Thank you very much for expressing interest in translating LibreTime. Currently, we've been on planning to use [Zanata](https://zanata.com) as our main "non techie" translation interface.

Right now the (technical and organizational) integration of this platform is still underway and it looks like it will take some time (ie. alpha going rc phase) until we can finish setting everything up.

For most languages I guess it will make sense to set up a designated translation team with up to three dedicated team leads and possibly more translators. Would you be willing to take a leading role in the pt_PT translation effort? Do you have any other inputs we need to consider for pt_PT or i18n?

For now, progress on our i18n efforts are tracked in #301 with my current update on the state of i18n in https://github.com/LibreTime/libretime/pull/301#issuecomment-516129090.

I'm leaving this issue open and tagging it as i18n as a tracker for setting up the pt_PT translation team and what is needed from a techie point of view. Please let us us know if you would like to consider taking a leading role in the pt_PT translation effort so we can get you on-boarded.

Cheers
Lucas
