### ISSUE TITLE
Incorrect time shown

### ISSUE THREAD

**Issue by coryshort** [LibreTime/libretime#821]
After around 24 hours the time shown is not correct 
this makes it hard to program shows as it sometimes will not allow a show to be added when the time is incorrect on the web UI

**Comment by Robbt** [comment]
I suspect that this is an issue with your server time falling out of date. Either way we need more information as this is too vague. Please edit this bug with the required information distro - specifics as to what you mean by time shown being out of date - so we can reproduce it.
