### ISSUE TITLE
Login 3.0.0-alpha.7 : OOPS something went wrong

### ISSUE THREAD

**Issue by Denniz** [LibreTime/libretime#822]
**Describe the bug**
After clean install, login with default user & pass (admin) results in "OOPS something went wrong" page.

**To Reproduce**
- Clean OS install, fully upgraded, clone from github, install with `./install`,
- Open server URL in Chrome browser, see generic page,
- Click "login" (top-right),
- Enter username & password --> error page.

**Expected behavior**
Get into the application settings/schedule.

**LibreTime version:**
3.0.0-alpha.7

**Installation method:**
 - OS: Ubuntu
 - OS Version 16.04.5 LTS (Xenial Xerus)
 - Method: `./install` after clone from github
 - Details: 

**Client (please complete the following information if applicable):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 74.0.3729.169

**Additional context**
Also tried using `./install -fiab` but then I get database errors when entering default folder during setup.
With `./install` I can finish setup but not login.

**Comment by Robbt** [comment]
Look at the /var/log/airtime/zend-php.log and share the errors you see. This will provide us with the additional information required to troubleshoot.

Also are you installing this on a shared server or a dedicated server (just for LibreTime).

**Comment by b01xy** [comment]
Hello,

Same problem here, on a recent Libretime installation in a LXC container, it is possible to log in on Linux/firefox but not on Windows Firefox/chrome/brave nor on Mac Safari/Chrome (Firefox works)

When it doesn't work I have the page "Ooops something went wrong"

Some airtime/zendphp.log that seems relevant :+1: 

```
2019-10-24T14:01:07+00:00 ERR (3): air3.p-node.org [ErrorController.php:26 - errorAction()] - Forbidden
2019-10-24T14:01:07+00:00 ERR (3): air3.p-node.org [ErrorController.php:27 - errorAction()] - #0 /usr/share/airtime/php/airtime_mvc/application/controllers/LoginController.php(27): CORSHelper::enableCrossOriginRequests(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#1 /usr/share/airtime/php/vendor/zf1s/zend-controller/library/Zend/Controller/Action.php(516): LoginController->indexAction()

```
in the status page, I have LibreTime Version | d02055174

thanks for any help
++
b

**Comment by b01xy** [comment]
Ok, solved my problem with : 
- a more coherent setup between /etc/hostname and /etc/hosts file that cause problems to rabbitmq (thus I was not able to save the preferences)
- an update of libretime with the last git version
- an addition of URL in "URLs CORS autorisées" in the General preferences of Libretime : 
```
https://sub.domaine.org
http:/sub.domaine.org
http://sub
http://localhost
https://sub
https://localhost
```
Not sure all are necessary, but my Libretime is inside a LXC container with a proxy vhost on the apache front.

Shall we close this bug which was not really a bug at the end ?

**Comment by paddatrapper** [comment]
The CORS URLs should be documented. I remember running into the same issue before

**Comment by paddatrapper** [comment]
Tracking the documentation in #917
