### ISSUE TITLE
Create LibreTime DJ subsequently creates WordPress user

### ISSUE THREAD

**Issue by tonyzeoli** [LibreTime/libretime#827]
**Is your feature request related to a problem? Please describe.**

I'm a consultant working for my clients who are currently using AirTime, but want to migrate to LibreTime. Like the Mixcloud integration with Radio.co, which I read about here on the Git forum, they want to create a method to use the WordPress Rest API for Users to create a new user once a LibreTime DJ is created and then make available an archive of that DJs shows (uploaded in LibreTime) available as a list on an archive page in WordPress.

**Describe the solution you'd like**

We would like to be able to:

1. When a DJ is created in LibreTime, create a new user in WordPress
2. When the new user is created in WordPress, the DJ then gets access to WordPress and uploads their show file in WordPress and it's added to the folder for the DJ ID created when the LibreTime DJ was created. We understand that the DJ will have to keep the exact same title in the ID3 tag, so the file will be directed to the same folder LibreTime created for the DJ. We tested this with LibreTime via the Uploader and realized that if we kept the title the same in the ID3 tag, it would store the file in the exact same DJs folder. But if you change one character, it would create a new folder for that DJ. This concept avoids all DJs having to submit their shows and we have to upload them using the Uploader.
3. When a new file is uploaded by the DJ, it gets assigned to its scheduled time slot. We then send a signal back to WordPress to disallow new uploads until the upload for that DJ has aired, then WordPress removes the upload restriction and allows the DJ to upload a new show, and then repeat the process. This way, the DJ doesn't accidentally upload more than one show file and the system doesn't know what to play for the next DJs time slot.
4. We need to note when the file has completed its scheduled air time and that triggers an instance in WordPress for that user to publish a - let's call it a non-interactive stream - archive of the file in WordPress.

**Describe alternatives you've considered**

AirTime has a Upload API and a Show metadata API and we're thinking about using this to create the WordPress plugin that will spawn a new user in WordPress when a DJ is created in airtime, as well as sync the DJ with their schedule time on the primary show. And the DJ will be able to upload.

**Additional context**

No additional context. Just hoping to get access to a user api and a show meta api to then link all this up and make it work. Any help someone can give on this feature would be appreciated.

**Comment by tonyzeoli** [comment]
Sorry, I may have just answered my own question with XML and Smartblocks, which means I don't have to create a DJ in LibreTime, I can just add their podcast feed to a SmartBlock and assign it to the show calendar. This may negate the need for syncing DJs between LibreTime and Wordpress.

**Comment by gusaus** [comment]
@tonyzeoli Is there anything else from https://discourse.libretime.org/t/question-about-user-api-uploading-from-wordpress-and-podcast-function/298/3 that should be addressed in this issue queue? 

Possibly this? 
> I would think there would need to be a WordPress plugin as well as the equivalent in Drupal that would use an API to make these connections and trigger these events.

Any new functionality not yet on the LibreTime roadmap could be crowdfunded via Open Collective https://github.com/LibreTime/libretime/issues/796

**Comment by tonyzeoli** [comment]
Yes, the Smart Block + Podcast feed solution is amenable for the short term. But in the long term, it would be helpful to sync a DJ in LibreTime to his/her Show Page and Author status in WordPress, so that shows that complete can be pushed to WordPress automatically after the show has aired on its air date in LibreTime, giving the option to archive content in WordPress once an episode of a show completes and being able to attribute the episode to the contributing DJ.

**Comment by tonyzeoli** [comment]
@gusaus The one thing I need to know if using SmartBlocks with podcast category fees is:

How does the smart block know to play the most recent show from the category feed and if no new show is uploaded, will it play the previous show. Does the smartblock say, "if have new show, play new show. If don't have new show, then play last show available."?

**Comment by Robbt** [comment]
@tonyzeoli the way a smartblock works in conjunction with a podcast is that it will play the latest, if no new one is updated it will play the last show. It is basically sorted by "newest" by default. 

Another new setting I just added was "least recently played" which will select at random first any track that matches the criteria that has never registered as having played and then if every track has been played already it will select the track it hasn't played in the longest time. This is useful if you have a show that you only get sporadic updates and you don't want it to just play the same show week after week. In theory if a new show was uploaded it would also play this, but for shows that are getting updated on a regular basis "newest" is probably the best.

**Comment by hairmare** [comment]
> 1. When a DJ is created in LibreTime, create a new user in WordPress

You might consider having LibreTime and WordPress consume users from a common LDAP directory.

The remainder of your scenario might also benefit from a working watched folders feature and some shared storage, although I guess the smartblock method should work just as well. The watched folders feature is tracked in #70 with some work in #514.
