### ISSUE TITLE
No sound on live stream

### ISSUE THREAD

**Issue by codenift** [LibreTime/libretime#828]
I just installed Libretime. Everything seems to work except one thing, when I click on  "Listen" or play button on the live player. I'm able to play and hear the mp3s from the list individually. The tracks seem to be live and show that it is changing tracks on the player. I tried the live stream on every browser and no luck. I have the stream set up to mp3 128kbit/s. How do I fix this? 

Edit:
Everything is checked on Status, I'm able to do everything with no issues. The problem I find is within the live stream url itself. Is this an issue with liquidsoap? I have my stream setup as MP3 128kbits (port 8000 / Icecast)

Clinking on the stream name, example: http://(MY.IP.NUMBER):8000/_a    does nothing. 
"Failed to load resource: The request timed out."

If anybody can help me on why it's not playing anything on the stream I would appreciate it very much. Thanks.

And also, one more thing.. I noticed, is there anyway I can actually name the stream name incase I don't want "_a" or "_b"?

**Comment by Robbt** [comment]
Go to your IP:8000 and do you see your stream ? 

There is a stream section under settings where you can change the name of your stream.

Have you tried opening the stream with VLC or media player capable of playing a stream ?

**Comment by codenift** [comment]
Ah! I see now. I hovered the "Additional Options" dropdown which I thought it was just a dark title bar for the stream URL so I didn't click on it. I'm now able to see the additional options although I can't edit it. Sorry, I'm new to Libretime. I'll look more on the documentation.

Going to my IP:8000, is not responding. On VLC, it fails to open the stream. Seeing it on the inspector for the player the request also fails to connect.

**Comment by Robbt** [comment]
If you don't get anything by going to http://yourip:8000 then that means Icecast is not running. You might also benefit from browsing the logs in the /var/log/airtime/ directory.

**Comment by codenift** [comment]
Yes. I was using DreamHost and had an issue on it, but now the icecast is installed correctly and I have it working. Thanks.
