### ISSUE TITLE
Project Logo

### ISSUE THREAD

**Issue by paddatrapper** [LibreTime/libretime#829]
We need a project logo to use on things like YouTube and the website. I'm a terrible designer, so I don't think I should create it, but can give it a try

**Comment by gusaus** [comment]
We might want to consider reaching out to the open source design group
(they are also on Open Collective). Possibly there’s an opportunity for
some type of in-kind sponsorship. I’m part of few other projects with a
similar need, so I’ll try to connect just to see if they might be an option.

**Comment by Robbt** [comment]
I created the logo for Discourse but would be happy if someone were to do a better job - here are some links to it in different formats- feel free to use it for now.
 **https://aws1.discourse-cdn.com/standard10/uploads/libretime/original/1X/c20f6e31165fac844f91616d7d2415445650957e.png** 
**https://aws1.discourse-cdn.com/standard10/uploads/libretime/optimized/1X/89235d38f681188ea1b8cbe47164ec963b3b941c_2_690x229.png**
**https://aws1.discourse-cdn.com/standard10/uploads/libretime/original/1X/aedbc8cebc5c795b08586d6bd98aca1e3d0fc8d3.png**

**Comment by mirzazulfan** [comment]
Hi guys. What about this logo? :)
![libretime](https://user-images.githubusercontent.com/36124339/60319871-1a822800-99a2-11e9-8d41-ecb389c834e5.png)

**Comment by paddatrapper** [comment]
@mirzazulfan - those look really good! I especially like the middle one on the bottom row. Potentially combining it with the LibreTime from the top for a banner look when required

**Comment by Robbt** [comment]
Yeah looks really good.

**Comment by mirzazulfan** [comment]
Thanks guys, I'll send all files tomorrow and create a pr. :)

**Comment by gusaus** [comment]
Thank you @mirzazulfan! How did you find this post? Are you a member/user of LibreTime?

**Comment by mirzazulfan** [comment]
H @gusaus  I am very happy to be able to help open source projects. and I've made many logos for open source projects for free. I often look for open source projects that require a logo. That is very pleasant for me. :) Thanks guys. I've created a pr #831 and you can also download it on [GDrive](https://drive.google.com/drive/folders/1VLNpJkq7Mx503bs-WdsV0qMS7A8zuxw2)
