### ISSUE TITLE
Calendar Edit Instance / Show not possible

### ISSUE THREAD

**Issue by maydo** [LibreTime/libretime#835]
Hi,

i have two instances of libretime running a few months now.

currently im not able to "edit instances" on both machines. 
the fields are greyed out, like "autoloading playist, who, djs etc etc"
see img.

editing a single show is possible

any ideas ?

![20190702131239](https://user-images.githubusercontent.com/27486434/60508798-bb872080-9ccb-11e9-8105-97c0bb1bd523.jpg)

i think it has something todo with the long timelime (creation date)
most of the shows are created a few months ago.

**Comment by Robbt** [comment]
I have not seen this with shows that are many years old at this point. Make sure you are trying to edit a show is in the future vs. a show that has always aired. I think that the options are grayed out for past shows.

**Comment by maydo** [comment]
Hi Robbt, yes i know that, its shows in future. 

Not sure since when it is, couse we are not editing each day, but it was working nice during latest edits.
i just noticed today, its same issue on both machines running ubuntu 18.04

maybe it has something todo with some updated ubuntu core packages ?

**Comment by Robbt** [comment]
Check zendphp.log in /var/log/airtime and see if there are any PHP errors or anything that could help point to the reason this happens.

**Comment by maydo** [comment]
<pre><code>
(
    [helper] => formTextarea
    [_allowEmpty:protected] => 1
    [_autoInsertNotEmptyValidator:protected] => 1
    [_belongsTo:protected] => 
    [_decorators:protected] => Array
        (
            [ViewScript] => Array
                (
                    [decorator] => ViewScript
                    [options] => Array
                        (
                            [viewScript] => form/add-show-block.phtml
                            [class] => block-display
                        )

                )

        )

    [_description:protected] => 
    [_disableLoadDefaultDecorators:protected] => 
    [_errorMessages:protected] => Array
        (
        )

    [_errors:protected] => Array
        (
        )

    [_errorMessageSeparator:protected] => ; 
    [_filters:protected] => Array
        (
        )

    [_ignore:protected] => 
    [_isArray:protected] => 
    [_isError:protected] => 
    [_isErrorForced:protected] => 
    [_label:protected] => Instance Description:
    [_loaders:protected] => Array
        (
            [DECORATOR] => Zend_Loader_PluginLoader Object
                (
                    [_loadedPluginPaths:protected] => Array
                        (
                        )

                    [_loadedPlugins:protected] => Array
                        (
                        )

                    [_prefixToPaths:protected] => Array
                        (
                            [Zend_Form_Decorator_] => Array
                                (
                                    [0] => Zend/Form/Decorator/
                                )

                        )

                    [_useStaticRegistry:protected] => 
                )

        )

    [_messages:protected] => Array
        (
        )

    [_name:protected] => add_show_instance_description
    [_order:protected] => 
    [_required:protected] => 
    [_translator:protected] => 
    [_translatorDisabled:protected] => 
    [_type:protected] => Zend_Form_Element_Textarea
    [_validators:protected] => Array
        (
            [StringLength] => Array
                (
                    [validator] => StringLength
                    [breakChainOnFailure] => 
                    [options] => Array
                        (
                            [0] => 0
                            [1] => 8192
                        )

                )

        )

    [_validatorRules:protected] => Array
        (
        )

    [_value:protected] => 
    [_view:protected] => 
    [_isPartialRendering:protected] => 
    [_concatJustValuesInErrorMessage:protected] => 
    [class] => input_text_area
    [disabled] => disabled
    [readonly] => readonly
)
</pre></code>

there is this entry in zendphp.log when open "edit instance"

**Comment by Robbt** [comment]
Hmm, that isn't showing an error or why it is being made readonly. There are not errors being thrown ?

**Comment by maydo** [comment]
yes its just an info. there is no other related entries in zendphp.log

**Comment by maydo** [comment]
no errors, its just an info.

it must something related to ubuntu 18.04 packages which was updated.
couse same issue on two machines.
one is running latest LT git version (977b5c002)
one is running LT (d02055174)

**Comment by Robbt** [comment]
Did your php version change ? Can you figure out what version of php you are running ? I haven't been to active with LibreTime development lately but I want to try to help. Other than php package updates shouldn't have this sort of impact.

**Comment by maydo** [comment]
yes its just an info. 
i have no more ideas how to debug

**Comment by maydo** [comment]
PHP 7.2.19-0ubuntu0.18.04.1 (cli) (built: Jun  4 2019 14:48:12) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.19-0ubuntu0.18.04.1, Copyright (c) 1999-2018, by Zend Technologies

running php 7.2, also tried downgrading to 7.1 but was getting a blank page on 7.1

**Comment by maydo** [comment]
Hi Robbt,

for testing i have just installed a brandnew VM ubuntu 18.04.2 and latest LT from scratch.
and its same issue. so it can just be related to some ubuntu core packages.

i think it needs to be fixed on libretime

i have checked php packages, it was from beginning php7.2 
latest update was on 04.06.2019 from 7.2.17 to 7.2.19

**Comment by Robbt** [comment]
Ok, are you just not able to edit the show->instance to change this ? I booted up LibreTime and I believe that these are somewhat intentionally disabled for show instances. I also saw the same behavior when editing an a instance running a different distro.

Is your thought that you want to have different autoplaylists for different instances ? 
Are you able to edit the show directly ?

**Comment by maydo** [comment]
im able to edit a single show, but when show is repeating, im not able to edit instances

so if you want edit instances, you need to edit all repeating single shows in future

this was 100% working before

**Comment by Robbt** [comment]
Hmm, then this might be a side effect of a change that was made in LibreTime, I don't think it is related at all to any changes in your ubuntu system as I noticed the same behavior. 

Ok I found where this is happening and it was likely caused by the #4b9e50b64b commit or #0cf27e91e2 - as these commits touched  /airtime_mvc/public/js/airtime/schedule/add-show.js which is where the disable event came from. 

I haven't looked into it yet but feel free to try and analyze what caused this. It should be reversible with a PR.

**Comment by Robbt** [comment]
Ok I got curious, those commits I mentioned above are not relevant. According to the code which has been in place since 2013 editing a show instance disables all of these forms.

Here is the blame from airtime_mvc/application/services/ShowFormService.php 
```

e259639d1a (denise             2013-03-27 09:02:49 -0400  80)     public function delegateShowInstanceFormPopulation($forms)
e259639d1a (denise             2013-03-27 09:02:49 -0400  81)     {
e259639d1a (denise             2013-03-27 09:02:49 -0400  82)         $this->populateFormWhat($forms["what"]);
731b86b36c (denise             2013-03-27 16:25:39 -0400  83)         $this->populateInstanceFormWhen($forms["when"]);
731b86b36c (denise             2013-03-27 16:25:39 -0400  84)         $this->populateFormWho($forms["who"]);
731b86b36c (denise             2013-03-27 16:25:39 -0400  85)         $this->populateFormLive($forms["live"]);
731b86b36c (denise             2013-03-27 16:25:39 -0400  86)         $this->populateFormStyle($forms["style"]);
731b86b36c (denise             2013-03-27 16:25:39 -0400  87) 
e8a8aeaf00 (drigato            2013-12-13 12:13:58 -0500  88)         /* Only the field on the 'when' form will get updated so we should
e8a8aeaf00 (drigato            2013-12-13 12:13:58 -0500  89)          * make all other forms disabled or readonly
e8a8aeaf00 (drigato            2013-12-13 12:13:58 -0500  90)          * 
e8a8aeaf00 (drigato            2013-12-13 12:13:58 -0500  91)          * 'what' needs to be readonly because zendform will not validate
e8a8aeaf00 (drigato            2013-12-13 12:13:58 -0500  92)          * if they are disabled
e8a8aeaf00 (drigato            2013-12-13 12:13:58 -0500  93)          * 
e8a8aeaf00 (drigato            2013-12-13 12:13:58 -0500  94)          * All other forms can be disabled because we do not update those values
e8a8aeaf00 (drigato            2013-12-13 12:13:58 -0500  95)          * when the user edits a repeating instance
e8a8aeaf00 (drigato            2013-12-13 12:13:58 -0500  96)          */
e8a8aeaf00 (drigato            2013-12-13 12:13:58 -0500  97)         $forms["what"]->makeReadonly();
0789de9392 (Duncan Sommerville 2014-09-19 13:02:38 -0400  98)         $forms["what"]->enableInstanceDesc();
2a53241ba3 (Lucas Bickel       2017-03-10 16:20:44 +0100  99)         $forms["autoplaylist"]->disable();
731b86b36c (denise             2013-03-27 16:25:39 -0400 100)         $forms["repeats"]->disable();
e8a8aeaf00 (drigato            2013-12-13 12:13:58 -0500 101)         $forms["who"]->disable();
e8a8aeaf00 (drigato            2013-12-13 12:13:58 -0500 102)         $forms["style"]->disable();
881471c6b8 (Duncan Sommerville 2015-06-26 14:23:45 -0400 103)         // Hide the show logo fields when users are editing a single instance
881471c6b8 (Duncan Sommerville 2015-06-26 14:23:45 -0400 104)         $forms["style"]->hideShowLogo();
e8a8aeaf00 (drigato            2013-12-13 12:13:58 -0500 105)         $forms["live"]->disable();
731b86b36c (denise             2013-03-27 16:25:39 -0400 106)         $forms["record"]->disable();
731b86b36c (denise             2013-03-27 16:25:39 -0400 107)         $forms["rebroadcast"]->disable();
731b86b36c (denise             2013-03-27 16:25:39 -0400 108)         $forms["abs_rebroadcast"]->disable();
e259639d1a (denise             2013-03-27 09:02:49 -0400 109)     }
e259639d1a (denise             2013-03-27 09:02:49 -0400 110) 
a7601d290f (denise             2013-03-21 10:05:11 -0400 111)     /**

```

So I'm not sure how it was working for you before when the ability to edit much in a show instance has not changed evidently.
