### ISSUE TITLE
Allocate more HD space

### ISSUE THREAD

**Issue by sheckamania** [LibreTime/libretime#844]
Hey. I installed Libretime on my server that I got from a company. The server has 2TB of space on it. I noticed however that when I looked at the libretime storage, it said that I have 3.9 gigs used of 19 gigs. I want to allocate at least 750 gigs to Libretime. How do I do it? Any and all information would be helpful.

**Comment by hairmare** [comment]
This depends on how you installed the server and how it's storage is set up. Usually there should be some kind of storage management (ie. lvm) on the server. In the case of lvm you would so something along the lines of [this documentation](https://www.tldp.org/HOWTO/LVM-HOWTO/extendlv.html).

Specifically for LibreTime I would recommend that the storage attached to the server should be split into two separate RAID drives. A small one for the OS (ca. 5GB should be enough), as well as another one for LibreTimes `/src/airtime` mountpoint using the remainder of the storage.

**Comment by joaoherberto** [comment]
@sheckamania were you able to figure this out?

**Comment by sheckamania** [comment]
Hey everyone. Yes I have figured it out. I ended up re-installing Libretime to a different folder on the system for it to allocate the whole drive. However, I ended up having to change folder permissions within it in order for the music to be fully scanned, and for them to show up.

**Comment by joaoherberto** [comment]
Yes, this makes sense, the OS is usually installed on a separate partition for /, and the /home directories on a separate partition. The OS is usually given between 20-30 gigs of space, hence the Libretime not seeing the other space.
