### ISSUE TITLE
Problem: Add dialog to prompt user to change the default IceCast password upon install

### ISSUE THREAD

**Issue by Robbt** [LibreTime/libretime#86]
Since many users will be just rolling this out without much expertise, we should at least try to encourage secure installations.

Taking a queue from the how the setup dialog prompts the user to change their rabbitmq password, we should also include something that asks them to change their icecast password or perhaps handle this via the web interface and then saves it automatically. 
Or perhaps it can autogenerate a secure password and seed it into the web interface/icecast config.

Ideally the rabbitmq password prompt would be handled better in the same way as well since most people will likely ignore the prompt and just use the default password thus creating a potential vulnerability.

**Comment by squiggleuk** [comment]
When going through the setup, I always presume that changing the rabbitmq password would break everything on the following pages... Autogenerating a secure password feels like the best way. Maybe have somewhere in admin/settings that displays it and allows it to be changed? (So Libretime and IceCast password remain in sync)

**Comment by hairmare** [comment]
My understanding is to use the advanced rabbitmq setup with a different password if you prepared your server manually with a proper password. This [google search](https://www.google.com/search?q=site%3Alibretime.org&oq=site%3Alibretime.org+&aqs=chrome..69i57j69i58.2444j0j7&sourceid=chrome&ie=UTF-8#safe=off&q=site:libretime.org+rabbitmq&*) shows me that the manual needs some info on manually setting up a secure rabbitmq. 

The manual is also missing a walkthrough of the initial setup with more explanations, in fact I see no mention of the whole setup routine in the docs. We might opt to add links to this in the setup dialogs and also maybe reword the dialog.

**Comment by squiggleuk** [comment]
Could we do something like this in the install script?

icecastPass=$(date | md5sum | cut -c1-9)
icecastConfig="/etc/icecast2/icecast.xml"

sed -E -i "s/(<source-password>)(.*)(<\/source-password>)/\1$icecastPass\3/" $icecastConfig
sed -E -i "s/(<relay-password>)(.*)(<\/relay-password>)/\1$icecastPass\3/" $icecastConfig
sed -E -i "s/(<admin-password>)(.*)(<\/admin-password>)/\1$icecastPass\3/" $icecastConfig
sed -E -i "s/(<master-password>)(.*)(<\/master-password>)/\1$icecastPass\3/" $icecastConfig

# update database with $icecastPass

**Comment by frecuencialibre** [comment]
continuing here the conversation started over in a docker repo https://github.com/ned-kelly/docker-multicontainer-libretime/issues/20#issuecomment-445907162

@Robbt in response to your comment re: security, any reason why editing icecast.xml would be more of a concern than the editing of other files, such as airtime.conf, that the installer is already doing?

**Comment by Robbt** [comment]
I suppose it isn't a bigger security concern but it would involve altering the permissions for the icecast file so that www-data could right it or perhaps adding www-data to the icecast group. Whereas airtime.conf has only ever been owned by www-data. The path forward on multiple distributions is less obvious but could be figured out.

**Comment by Robbt** [comment]
So my preference for this would be for the install script that runs as root to choose random values and then insert these into the icecast XML file and seed the database. Then we can make this secure by default without requiring action by the user and they can modify it if they want. We will probably need to make the default streaming settings user configurable.

**Comment by frecuencialibre** [comment]
@ned-kelly do you have any opinion on the approach @Robbt describes in [his comment above](https://github.com/LibreTime/libretime/issues/86#issuecomment-448276995)?

**Comment by paddatrapper** [comment]
Debian and Ubuntu already prompt to change the Icecast password when installing the icecast2 package.

I would also suggest that it be behind a prompt in the installer to account for people installing Icecast on a different server/already set the password/etc

**Comment by Robbt** [comment]
@paddatrapper so maybe the way we are installing the deb packages is circumventing this prompt and we could re-enable it or somehow hook into it ? I don't want to reinvent the wheel here but I also don't want people to have hackme as their icecast password when they install it and don't know any better.

**Comment by Robbt** [comment]
So I started to do some research into the best way to edit an XML file via the command line in Linux and came upon XML starlet and this command ```sudo xmlstarlet ed -u /icecast/authentication/source-password -v nohack /etc/icecast2/icecast.xml``` will for instance change the icecast.xml file - so it might be worth doing this in the install script. 

Then we would also need to update the DEFAULT_ICECAST_PASS in ```airtime_mvc/application/configs/constants.php``` to be a new value. It might make sense to using the install script to simply add random ones. I think once we save it in the DB liquidsoap should pull it automatically from the DB and put it in liquidsoap.cfg.

If we just did a random password then it might make sense to show it to the admin upon install so they can right it done. Or maybe make it accessible via the stream settings. Anything should be a step up from the current default of hackme.

**Comment by Robbt** [comment]
So the database just pulls it from the preferences database - using setDefaultIcecastPassword while the constant is only pulled if there is nothing set in the database, so its a question of bootstrapping the whole process and probably adding something into the database that inserts it into the database. We would also need to replace this in defaultdata.sql  - airtime_mvc/build/sql/defaultdata.sql:INSERT INTO cc_stream_setting ("keyname", "value", "type") VALUES ('s1_pass', 'hackme', 'string');

So the next step is to start coding an approach with the install file.

**Comment by Robbt** [comment]
So we have a little bit of a chicken and an egg thing going on here, because when icecast2 is installed we don't have a database setup and the database isn't created until 'airtime_mvc/public/setup/database-setup.php' is ran during the installer.

So the question is do we store the icecast2 password somewhere so that the installer can read it and then add it to do the database later on in the install process and simply add a new function to the database-setup.php that reads from this file and inserts the appropriate data into the database.

I think I prefer this to having the installer and www-data being added to the icecast group and having write permissions for /etc/icecast.xml - as that would probably be a bigger liability than storing the icecast2 password in a temp file.

**Comment by paddatrapper** [comment]
The installer doesn't need to be added to the icecast group, but I agree that a temp file would be better
