### ISSUE TITLE
[Question] Schedule Custom Stream Server

### ISSUE THREAD

**Issue by MZwillus** [LibreTime/libretime#863]
Hi all,

I was wondering if there is a possibiblity to schedule the custom stream servers.

We need to stream to a server at certain hours only, but I can't find any configuration and no information in the documentation.

Cheers
Malte

**Comment by Robbt** [comment]
This functionality is not currently built-in, generally LibreTime is setup to be the server that people stream too and there is support for giving people permission to stream during certain times but it hasn't been designed to say stream only during certain periods.
