### ISSUE TITLE
Can't tell which version is actually installed.

### ISSUE THREAD

**Issue by joaoherberto** [libretime/libretime#864]
I just did a fresh install two days ago, using GIT I noticed on the version tool tip is says I am using an old version and that 3.0.0-alpha.8/ is available. I went to to my install directory, ran “git pull” and it says it is up to date?

What am i missing here?
![Selection_495](https://user-images.githubusercontent.com/3608446/63855194-ab9a5e80-c953-11e9-9e90-8b921c71b927.png)

**Comment by hairmare** [comment]
The commit-ish in the title bar (306954cbf) is the actual version you installed. The message in the version tooltip is somewhat unreliable when installing directly from git and not using a release tarball.

Last time I looked there was no simple way to detect a git installation. Once we can detect that properly it would make sense to "fix" the version tooltip so it doesn't recommend updating to a release that is older than the actual commit-ish.
