### ISSUE TITLE
Unable to view schedule beyond the current week

### ISSUE THREAD

**Issue by jbatesuk** [LibreTime/libretime#865]
**Describe the bug**
When trying to access the schedule beyond the current week, nothing is shown. It's blank, despite shows being scheduled for that week

**To Reproduce**
1. Open the dashboard
2. Open /schedule
3. Select Week/Month or try and skip to the next week
4. Javascript error is given in console.

**Expected behavior**
I expected to be able to view the schedule for the next weeks/months, but it's all blank.

**LibreTime version:**
Version: 306954c (installed yesterday via git)

**Additional context**
Console error is as follows:

`TypeError: date.format is not a function. (In 'date.format('YYYY-MM-DD HH:mm:ss')', 'date.format' is undefined)`

**Comment by paddatrapper** [comment]
@hairmare could this be related to #858?

**Comment by jbatesuk** [comment]
A bit more information:

When logging in as a DJ,  can view the schedule without any issue, but not when an admin or Program Manager.

**Comment by hairmare** [comment]
@paddatrapper It certainly looks like it's related to #858. I think the original branch where I got this change was using a library to monkey patch the format call. 

I created #866 that simply reverts this until I can figure out why I did the change (and where the method should be defined).
