### ISSUE TITLE
Raspbian GNU/Linux 10 (buster) is not supported with raspbian-10

### ISSUE THREAD

**Issue by nscpro** [LibreTime/libretime#867]
When LibreTime support Raspbian 10 Buster?

**Comment by paddatrapper** [comment]
What is the error you are running into? Is I te just a missing distro in the install or is there an actual error when attempting to install required packages?

**Comment by hairmare** [comment]
Raspbian 9 needed this hack:
https://github.com/LibreTime/libretime/blob/e26b9c272159faf882b26d0ee591638831f4c3c8/install#L628-L635

I haven't had a Raspbian 10 to play with yet but I'd assume something similar is needed.

**Comment by paddatrapper** [comment]
Fixed in #930
