### ISSUE TITLE
Can't delete past shows from the interface

### ISSUE THREAD

**Issue by SireAngelus** [LibreTime/libretime#869]
As in the subject, i cannot delete a show after setting it up.
plus many problems with the playout service crashing on me on many occasions

**Comment by hairmare** [comment]
As far as I remember past shows can never be edited in the UI. You should be able to delete future occurrences of shows though.

Do you have any more details on the crashing playout service? Some liquidsoap or pypo log dumps would help us narrow down what's going on with your playout service.
