### ISSUE TITLE
Live program loses time if I edit while it is playing

### ISSUE THREAD

**Issue by Archieradio** [LibreTime/libretime#874]
**Describe the bug**
I program my station in 24 hour programs. First, I create the program on the calendar. Then, I populate the program with SmartBlocks. Then I work my way through the computer generated playlist, editing and rearranging as I see fit. The goal is to have each day programmed in advance, but sometimes that is not possible so I end up editing that day's show while it is playing. When I do this, the live program is recalculated and all of the previously scheduled timing is thrown off. Invariably, the log creates a several second gap prior to the song that is currently playing, and the current song skips back in time to make up for the changed timing. It doesn't matter the type of change I make - simply swapping the order of two songs later in the program, removing a song, adding a song.... 

The timing error seems to accumulate at the rate of approximately 5 seconds per hour. That is, if the day's program has been running about an hour, I can expect the log to register a 5 second or so gap between the previous song and the current song. If it has been running for 10 hours, the gap would be much larger. As far as I can tell, there is no exact formula, these are only estimates. And the amount of time loss doesn't seem to change with how far into the day's programming I make the change. That is, if I am editing a show one hour into the day's program, I will see a few second adjustment whether the edits I am making are in the next hour of programming, or whether they are edits involving songs scheduled much later in the day.

**Expected behavior**
I guess I wouldn't expect the 'reality' of the timing of the broadcast to vary so much from the 'scheduled' timing of the broadcast. And I am perplexed as to why, if the real time is so different from the scheduled time, an untouched/unedited live program would be able to end at the scheduled time.

**LibreTime version:**
Popup says 'Could not detect version for VERSION file', wants me to upgrade to version 3.0.0-alpha.8 . 

**Installation method:**
 I don't know but might be able to find out if necessary.

**Screenshots**
If applicable, add screenshots to help explain your problem. Here is a screenshot of the log showing an 8 second gap between two songs.
<img width="619" alt="Screen Shot 2019-09-16 at 2 06 45 PM" src="https://user-images.githubusercontent.com/55411270/64990422-078a4000-d88d-11e9-8420-0c4aea3f65d6.png">

**Client (please complete the following information if applicable):**
 - OS: [e.g. Fedora]  macOS Mojave 10.14.6 
 - Browser [e.g. chrome, safari] . Chrome.
 - Version [e.g. 22] Chrome Version 76.0.3809.132 (Official Build) (64-bit)

**Additional context**

**Comment by Archieradio** [comment]
Maybe this is too basic a question? Maybe it's something that everybody knows already? If that's the case, maybe someone could tell me? I've been using the system for about 8 months so I don't have a ton of experience, I apologize if it's a dumb question!

**Comment by paddatrapper** [comment]
This definitely seems like a bug. Can you post your pypo and airtime-playout logs?

**Comment by Archieradio** [comment]
I will work on that. I have a friend who probably knows what you are talking about - he's out of the country right now but should be able to help me out.

In the meantime, I've gotten a little smarter and broken my 24 hour program up into smaller programs to help me avoid the problem of editing a live show. Still would like to figure out what is going on though...
