### ISSUE TITLE
live-info-v2 API action returns NULL for current track

### ISSUE THREAD

**Issue by delrizzo** [LibreTime/libretime#875]
**Describe the bug**
The API action live-info-v2 consistently returns NULL for the current track value. Previous and Next tracks populate correctly.

**To Reproduce**
1. Access the API function via https://<your server URL>/api/live-info-v2
2. examine the output - tracks->current = 'null'

**Expected behavior**
Expect the information for the current track to be populated as previous and next are.

**LibreTime version:**
977b5c002

**Installation method:**
 - OS: Ubuntu 18.04.2 LTS
 - Method: ./install script
 - Details: Github

**Client (please complete the following information if applicable):**
 - OS: Ubuntu
 - Browser Chrome

**Additional context**
Would also like to mention that calls to unauthenticated API functions require double loading - first attempt always gives a 'not found' page, then second (and subsequent loads are ok). We are still investigating whether this is something on our end, but have workarounds for the time being.

**Comment by Robbt** [comment]
Thanks for reporting this, hopefully I or someone else gets a chance to test it out and see if we can duplicate it soon. The API is pretty poorly documented and only minimally implemented so this isn't a surprise that there might be issues with it.

**Comment by vjku** [comment]
This is happening as the value of $currentShowID is being set to null in the method GetPlayOrderRange in the Schedule model (/usr/share/airtime/php/airtime_mvc/application/models/Schedule.php)

I just tried replacing the shorthand conditional below

`$currentShowID = (is_array($shows['currentShow'] && count($shows['currentShow'])>0)) ? $shows['currentShow']['instance_id'] : null;`

with the regular conditional below and it returns the $currentShowID as expected.

`
if(is_array($shows['currentShow']) && count($shows['currentShow'])>0){
    $currentShowID = $shows['currentShow']['instance_id'];
} else {
    $currentShowID = null;
}
`

This solves this current returning null issue as well as another API endpoint **on-air-light** which was what I was actually troubleshooting as it was returning 

`{"on_air_light":false,"on_air_light_expected_status":false,"station_down":false,"master_stream":false,"live_stream":false,"master_stream_on_air":false,"live_stream_on_air":false}` 

when I was expecting output as 

`{"on_air_light":true,"on_air_light_expected_status":true,"station_down":false,"master_stream":false,"live_stream":false,"master_stream_on_air":false,"live_stream_on_air":false}`

**Comment by Robbt** [comment]
Cool. Thanks for digging in there @vjku - do you want to open a PR for this ?

**Comment by paddatrapper** [comment]
I am able to reproduce the issue and confirm that the fix proposed by @vjku fixes it. @vjku do you want to open a PR or shall I?

**Comment by paddatrapper** [comment]
The issue with 
```
$currentShowID = (is_array($shows['currentShow'] && count($shows['currentShow'])>0))?$shows['currentShow']['instance_id']:null;
```
Is that the closing parenthesis of `is_array` is in the wrong place. It should be before the `&&`, not before `?`. But I think expanding the conditional out looks better, as I have done in https://github.com/paddatrapper/libretime/commit/7e19a28caf65ddba908dcdd1c5232e45aa139878 . I'll open a PR to fix
