### ISSUE TITLE
I can't make changes to the schedule

### ISSUE THREAD

**Issue by RememberForgottenHits** [LibreTime/libretime#880]
Hi,

I have a problem with the schedule! I can't no make changes to the schedule, and  can't add new shows to schedule. Only can delete shows.

I have been using the software for over 1.5 years and this problem/error is the first time.

I use a version of libretime 3.0.0-alpha.6  I've also tried versions 3.0.0-alpha.7 & 8

I have restarted own VPS server. My server distro is Debian 9

How can I solve this problem?

I can also create a new account if you want to access the running system where this problem occurs. Maybe the problem can be better understood in this way.

Thank you for helping me

**Comment by Robbt** [comment]
Well first I'd check the /var/log/airtime/zendphp.log and see if there are any obvious errors in there. 
Also did you make any changes or upgrades to your system that precluded this ?
I haven't seen this but hopefully the log will provide more insight.
Is it possible you have ran out of disk space on your VPS or something along those lines that might be affecting the database ?

**Comment by RememberForgottenHits** [comment]
Thank you for helping me.

My VPS server HDD has a total capacity of 300GB and has been used 63.2 GB (21.5% used). That's not the problem.

I have not made any changes to the server and software. Automatic distro update is only turned on.

Last time I made changes to the schedule about a month ago, everything worked properly.

My ZENDPHP log file content from morning  https://pastebin.com/0qdFmzvy

**Comment by paddatrapper** [comment]
Can you post the apt log for the time between it known to be working and when it broke?

**Comment by Robbt** [comment]
It looks like there is something happening with Zend security and the DOMObject that I haven't seen before.

**Comment by RememberForgottenHits** [comment]
Where do I find this apt.log? My /var/log/airtime catalog is like this:

pypo _(folder)_
pypo-liquidsoap _(folder)_
airtime_analyzer.log
zendphp.log

**Comment by paddatrapper** [comment]
Yeah, I'm talking about `/var/log/apt/history.log` - it will show any recent updates performed, but looking through it, I don't see anything obvious that could have broken things.

**Comment by Robbt** [comment]
I suspect it has to do with switching to php7.0 as the apt-log shows this was installed on the 24th.
And the error -  

> 2019-09-27T05:08:57+02:00` ERR (3): radio.rememberhits.com [Logging.php:166 - loggingShutdownCallback()] - Uncaught Error: Class 'DOMDocument' not found in /usr/share/airtime/php/vendor/zf1s/zend-xml/library/Zend/Xml/Security.php:82`

Looking up that error I found this -> https://stackoverflow.com/questions/14395239/class-domdocument-not-found which suggests installing php-xml and php-doc

Based upon your apt log I think that you might want to try to install via
`sudo apt install php7.0-xml` 
but it might be php5.6-xml or even php-xml or php7.3-xml
depending upon what is actvely being used. If you add a` <?php phpinfo()  ?>` to a file under your libretime root you can see what version is being used and whether php-xml is included. I suspect you inadvertantly switched to using php7.0 which didn't have this library installed and thus LibreTime broke. 

I hope this fixes your problem, if so please let us know.

Thanks,
   Robbt

**Comment by RememberForgottenHits** [comment]
Big big thanks for help me **Robbt**!!! I installed _"sudo apt install php7.0-xml"_ on the server and everything will work perfectly again after that.
