### ISSUE TITLE
After upgrade PHP 7.0 to 7.3 no can login libretime admin panel...

### ISSUE THREAD

**Issue by RememberForgottenHits** [LibreTime/libretime#885]
Hi,

After upgrade PHP 7.0 to 7.3 no can login libretime admin panel... only see "An error has occurred" you can look it http://rememberhits.com

But server works perfectly. Im see installed wordpress web, icecast & schoutcast works and can listen music.

If im downgrade PHP 7.3 to 7.0 all works fine. Im need to be active PHP 7.3  

How to im fix this mistake?

Thanks for help ;)

**Comment by Robbt** [comment]
You will need to look at the zendphp.log and see what new errors it is provided, it could be a missing package or a new issue with Zend that requires a fix.

**Comment by RememberForgottenHits** [comment]
Thanks for your reply!

zendphp.log is 8,4MB big and it's full of that kind of information. https://pastebin.com/RJ3GmX85

**Comment by Robbt** [comment]
My guess is you are missing the php7.3-pgsql package.

**Comment by RememberForgottenHits** [comment]
Thank you again **Robbt**! After _"sudo apt install php7.3-pgsql"_ it's now all works perfecto!!! Now all software upgraded :)
I wish you all the strength to develop this great software! I love LIBRETIME!!!
