### ISSUE TITLE
Import from Podcast folder only works on the 1st page

### ISSUE THREAD

**Issue by dordecutuvelo** [LibreTime/libretime#904]
Hi!

For a project we created a rssmp3.php URL that contains about 500 small length audios. In trying to import them to create a smartblock/playlist, not only I can only import them all individually but I can only import what is in the first page. If I choose to display 25 files per page, I can import the 25 of the first page, but nothing from the second and further. If I change the setting to 100 files per page, I manage to import the first 100, but nothing from the second page and so on. 

Any tips on that?

Thanks!

**Comment by Robbt** [comment]
I suspect that you have identified a bug in the podcast module code, this is an interesting approach towards importing audio. Someone will need to verify the bug and hopefully offer a fix.
