### ISSUE TITLE
MVC/Liquidsoap Synchronization : Hardening Exception Handling?

### ISSUE THREAD

**Issue by numericalatina** [LibreTime/libretime#906]
**Describe the bug**
Desynchronization between the MVC and Liquidsoap playout.
This is probably a duplicate of #699 and might be related to #232 and #125 or even #307
Opening my own issue so I can make a whole of it and work towards a solution.

**To Reproduce**
For instance, adding a track after the current one, and the removing the latter, should result in changing the currently playing track ("take over"). Instead, ON AIR turns off, and cannot catch up until pypofetch times out. 

**LibreTime version:**
I'm running *almost bleeding-edge LibreTime (last merge the 7th Oct - 50ca96156ef1962ea79ef1172ca81084529ff7a4)
Liquidsoap is 1.3.3 and I have applied the patch from https://github.com/radiorabe/libretime/tree/feature/liquidsoap-1.3-for-3.0.0-alpha.7

**Installation method:**
Running on a custom docker container, based on Ubuntu Xenial inspired by this thread #624

**Additional context**

I can confirm the work-around is to restart *airtime-playout*, but the bug will reappear after some hours.

After staring at the logs my impression is *pypopush* dies at some point, and that causes this desynchronization, as the only schedule update is obtained when pypofetch times out.
This could explain why the issue overcomes after a period of silence.

On the other hand, I suspect* pypopush* dies just because of a poor exception handling.
Indeed, RabbitMQ regularly throws broken pipe errors, although it reconnects immediately after.
Other connections have been seen to 'misbehave' similarly, such as telnet to liquidsoap.

And this could be happening not only to _pypopush_. 
Hardening exception handling in pypo could be the real issue here?

**Comment by numericalatina** [comment]
This is the kind of exception raising that might be killing processes such as **pypopush**
2afe01b3ddc94194101a4a2149116e27e0e115e5

Those processes live in separate threads, which could be part of the issue
(Because they are not re-spawn by the supervisor process, for example...)

**Comment by Robbt** [comment]
Thanks for your insight, if you can figure out how to trigger this it would be helpful for us to reproduce and determine a fix. Also feel free to open a PR for improved exception handling for pypo - fixing these type of issues are one of the biggest challenges I think we are facing in terms of getting LibreTime adopted for more serious usages.
