### ISSUE TITLE
How to add custom sample rate for mount points?

### ISSUE THREAD

**Issue by joaoherberto** [LibreTime/libretime#912]
Is there a way to manually force liquidsoap to use a custom sample rate?

**Comment by Robbt** [comment]
This would most likely fall under the purview of #229 - and so the simple answer is no there is no easy way to customize liquidsoap at this point, the question then becomes is either do we want to step up and build something that allows airtime.conf to customize liquidsoap configuration or is there a workaround that people can use in the meantime. I don't have the knowledge directly accessible in my memory but I figure it may be out there.
