### ISSUE TITLE
Make AutoLoading Playlist load time configurable by end user

### ISSUE THREAD

**Issue by Paomas81** [LibreTime/libretime#913]
Hi everyone, i need to change scheduled show's preload time. By default the preload time is 1 hour before start time. I need to set this time of 5 min before scheduled show.

**Comment by paddatrapper** [comment]
At the moment, I don't think that this is possible. Much of the internals of LT are hard-coded and still need to be exposed in the config file

**Comment by Paomas81** [comment]
Thanks for your answer :-)

**Comment by Robbt** [comment]
I'm going to make this a proper feature request as we have had enough requests for this. The basic way it could be implemented would be to have an option in the database configurable in the settings so that autoloading playlists can be built at different times before they air.
