### ISSUE TITLE
Provide a User-Agent to streaming server when using a Webstream

### ISSUE THREAD

**Issue by hgshoggins** [LibreTime/libretime#915]
As an Icecast server host, I have several clients using LibreTime that are connecting to us, and we would like to identify more precisely the different clients. All "classic" clients like VLC send a `User-Agent` header when connecting to our server, but not LibreTime.
Would love to see this feature added.

**Comment by paddatrapper** [comment]
Streaming is handled by Liquidsoap, so this will need to be implemented in the Liquidsoap scripts. I assume that liquidsoap supports setting the User-Agent
