### ISSUE TITLE
How to update config after config file changed

### ISSUE THREAD

**Issue by fauust** [LibreTime/libretime#918]
Hi!
What is the proper way to update Libretime settings after editing `/etc/airtime/airtime.conf` file?

From https://libretime.org/manual/host-configuration/ we should use the following command:
```bash
sudo airtime-update-db-settings
```
But I can't find the command anywhere.

My setup:
- Ubuntu 16.04;
- version 3.0.0-alpha.8;
- from installer script (`sudo ./install`).

**Comment by fauust** [comment]
BTW I could not find how to tag this with the documentation label instead of bug...

**Comment by paddatrapper** [comment]
You should restart the various parts (`systemctl restart airtime_analyzer airtime-playout airtime-celery airtime-pypo`) to use the new config. The docs need updating to reflect this
