### ISSUE TITLE
MVC breaks with input streams (ports 8001 & 8002)

### ISSUE THREAD

**Issue by numericalatina** [LibreTime/libretime#919]
**Describe the bug**
When live streaming to LibreTime on ports 8001 or 8002, the MVC interface would break (500)
I've found this is because of this line introduced recently on ScheduleController L305

**To Reproduce**
streaming to LibreTime on ports 8001 or 8002

**Expected behavior**
MVC working (showing ON AIR or the orange string)

**LibreTime version:**
latest

I'm opening a pull request with the fix immediately

**Comment by numericalatina** [comment]
The above commit fixes the issue when Streaming to Input ports, however, it produces an other bug when Scheduling a Webstream: once the webstream goes on air, the MVC interface freezes.

I can confirm the error disappears when reverting this commit. So we're in the situation 

So I'm asking to please re-open this issue. We need to find a fix that solves both bugs, instead of one or the other.

![LT_blank](https://user-images.githubusercontent.com/39980286/69575939-2b01f300-0f80-11ea-84e9-087d6e467b88.png)

Note how this could be related to #921 as the screens look similar

**Comment by paddatrapper** [comment]
Damn... I wonder what is causing that. @numericalatina please open a new issue describing the problem and reference this issue and the PR.
