### ISSUE TITLE
Problem: Podcast Web UI doesn't confirm track download

### ISSUE THREAD

**Issue by Robbt** [LibreTime/libretime#92]
Something in the podcast code changes we did made it so podcast downloads aren't confirmed back to the UI. Normally they should have a green check mark when they are done downloading but instead the ongoing download dialog continues to display.

This is probably an issue with the celery task callback.

**Comment by Robbt** [comment]
Ok, I did test this with the first version forked right from the saas-dev branch and it was working just fine.
In looking at the modifications, I don't see how the podcast download code would of affect this callback. Which is probably related to the callback_url and /rest/media. 

the callbackUrl is $stationUrl . 'rest/media' 
It could also be connected with the updateTrackReference.

I noticed we did some changes to the rest upload. I'll have to continue to dig deeper, just wanted to share the results of the digging I've done so far.

**Comment by Robbt** [comment]
I think it is related to this error - localhost [ThirdPartyCeleryService.php:33 - _executeTask()] - Invalid request: Unable to execute INSERT statement [INSERT INTO "third_party_track_references" ("id", "service") VALUES (:p0, :p1)] [wrapped: SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "file_id" violates not-null constraint

**Comment by hairmare** [comment]
The `INSERT INTO "third_party_track_references" ("id", "service") VALUES (:p0, :p1)` doesn't seem to what to set the `file_id`. I'm pretty sure the issue is somewhere in `airtime_mvc/application/services/PodcastEpisodeService.php`.

**Comment by hairmare** [comment]
The issue is `file_id` being `NOT NULL` in `third_party_track_references`. It needs to allow a value of `0` so we can create a placeholder for a podcast before the actual file exists. I'm assuming this behaviour changed in propel, postgresql at some point. We might also have been missing a change in schema.xml that was already in the autogenerated files. #95 fixes this together with the per album override option.
