### ISSUE TITLE
Stream setting update failing

### ISSUE THREAD

**Issue by numericalatina** [LibreTime/libretime#926]
**Describe the bug**
I found the following error recurrently in my logs
`Invalid argument supplied for foreach() in /usr/share/airtime/php/airtime_mvc/application/controllers/ApiController.php:1413`

Checking that line in code:
```
$data = json_decode($request->getParam("data"), true);
foreach ($data as $k=>$v) {
```

This variable $data is null.

**To Reproduce**
I found it on logs, but coincidently the stream setting always displays an error, although it's connected

**LibreTime version:**
Bleeding edge

**Installation method:**
 - OS: [e.g. Ubuntu]
 - OS Version [Xenial] 
 - Method: [Docker]

**Screenshots**
![stream setting](https://user-images.githubusercontent.com/39980286/70145738-a1c07f80-1655-11ea-92a4-53d2c01dc506.png)

**Comment by numericalatina** [comment]
This is the whole request, data is absent evidently
```
(
    [_paramSources:protected] => Array
        (
            [0] => _GET
            [1] => _POST
        )

    [_requestUri:protected] => /api/update-stream-setting-table/api_key/4IDDA3PI8LJWT1JL1EWD/format/json
    [_baseUrl:protected] => 
    [_basePath:protected] => 
    [_pathInfo:protected] => /api/update-stream-setting-table/api_key/4IDDA3PI8LJWT1JL1EWD/format/json
    [_params:protected] => Array
        (
            [controller] => api
            [action] => update-stream-setting-table
            [api_key] => 4IDDA3PI8LJWT1JL1EWD
            [format] => json
            [module] => default
        )

    [_rawBody:protected] => 
    [_aliases:protected] => Array
        (
        )

    [_dispatched:protected] => 1
    [_module:protected] => default
    [_moduleKey:protected] => module
    [_controller:protected] => api
    [_controllerKey:protected] => controller
    [_action:protected] => update-stream-setting-table
    [_actionKey:protected] => action
)
```

**Comment by Robbt** [comment]
I tried this on an existing vagrant box updated to the latest codebase and could not reproduce it. Is this still current ?

**Comment by numericalatina** [comment]
do not stale this, still happening
hope to have a time to solve it soon
cheers
