### ISSUE TITLE
Correctly support upgrade using install script

### ISSUE THREAD

**Issue by paddatrapper** [LibreTime/libretime#940]
**Is your feature request related to a problem? Please describe.**
There is a bug in the install script where `OLD_CONF=$(grep "[media-monitor]" /etc/airtime/airtime.conf)` doesn't provide the intended result because we will always assume that an existing conf is an upgrade because the `[ ]` are brackets in grep and thus they will match if any of the letters match. This means that the script will always assume that it is an upgrade if `/etc/airtime/airtime.conf` exists.

So when I take that out and run install it doesn't assume it is an upgrade and nothing happens. So I think rerunning install to facilitate upgrading is actually an unintended feature of this bug. But it hangs trying to stop media-monitor when I run it. So yeah, I think I should open a bug for that and perhaps add a --upgrade flag to ./install that will facilitate upgrading w/o assuming the user had an instance of airtime or always assuming it is an upgrade when they run install.

**Describe the solution you'd like**
We should either add a `--upgrade` flag to `install`  that will facilitate upgrading w/o assuming the user had an instance of airtime or always assuming it is an upgrade when they run install.

**Additional context**
Found by @Robbt [here](https://github.com/LibreTime/libretime/pull/933#issuecomment-571680862)

**Comment by Robbt** [comment]
This is related to and could help fix #623

**Comment by paddatrapper** [comment]
Fixed by #953
