### ISSUE TITLE
Master Source doesn't actually play out

### ISSUE THREAD

**Issue by paddatrapper** [LibreTime/libretime#945]
**Describe the bug**
When streaming to the master source, it connects and is detected, but the source is not changed when you turn it on in the UI. If you have a scheduled show playing, it continues playing.

**To Reproduce**
1. Create a Debian Buster vagrant image
2. Set master stream username and password
3. Set up a show with content playing
4. Connect to master stream
5. Toggle input to master stream

**Expected behavior**
The master stream should be heard on stream_1

**LibreTime version:**
5cfa57234b12e8e0b96cb1ef903c1d2fec36d805

**Installation method:**
 - OS: Debian Buster vagrant
 - OS Version: Buster
 - Method: git

**Comment by paddatrapper** [comment]
Testing in Debian Stretch results in the server returning a 404 error when trying to stream to 8001 master

**Comment by Robbt** [comment]
So we should test and make sure that the liquidsoap 1.3 fix didn't somehow introduce this bug at least with regards to Debian Stretch. There was one change to the liquidsoap_auth but it didn't seem like it would cause an issue. It could also be related to other tweaks we have merged to the form etc. Does a show based stream work out of the box or does it similarly fail ?

**Comment by paddatrapper** [comment]
In Stretch I get a 404 error using the show mount too. I'll test for before the liquidsoap changes

**Comment by paddatrapper** [comment]
Weird... Everything I try is returning 404 now... Can you replicate the error in the current git head?

**Comment by Robbt** [comment]
So yeah it's not working for me under ubuntu-xenial but I don't have a good setup to test it. I need to get darkice with a sample config setup for testing purposes.

**Comment by paddatrapper** [comment]
You can also use ffmpeg to stream to it: ffmpeg -re -i <source_file> -acodec libvorbis -b:a 128k -f ogg -content_type application/ogg "icecast://source:master@localhost:8001/master"

**Comment by Robbt** [comment]
Ok with that I also get the 404 error from ffmpeg at least under Ubuntu-xenial so I suspect that the change made in liquidsoap_auth.py for 1.3 is causing an issue. The port is actually open and I get a socket error from mixxx,. So we broke this somewhere, probably a good idea to try to figure out when and where at this point.

**Comment by Robbt** [comment]
Ok, I tried it on an instance pre our liquidsoap 1.3 fix and it failed, so this probably isn't the issue. I wonder if it has to do with vagrant or virtualbox but I don't think that it is. I can connect via telnet to the port but I don't know how to test it manually like that.

**Comment by paddatrapper** [comment]
Ok my testing results:

9ea0afbcb (Current HEAD):
* Master:
  * Buster - connects, enable but stream doesn't actually output anything
  * Stretch - 404 error
* Show:
  * Buster - connects, enable but stream doesn't actually output anything
  * Stretch - 404 error

1c2906f (Before liquidsoap changes):
* Master:
  * Buster (with patch) - connects, enable but stream doesn't actually output anything
  * Stretch - 404 error
* Show:
  * Buster (with patch) - connects, enable but stream doesn't actually output anything
  * Stretch - 404 error

e23246955 (3.0.0-alpha8):
* Master:
  * Buster (with patch) - RabbitMQ fails to start, so can't install
  * Stretch - 404 error
* Show:
  * Buster (with patch) - RabbitMQ fails to start, so can't install
  * Stretch - 404 error

**Comment by paddatrapper** [comment]
I want to try run the liquidsoap scripts alone and test connecting to them

**Comment by Robbt** [comment]
So is it possible that ffmpeg is incompatible with our liquidsoap instance, this sounds familiar to what was happening with BUTT where it was failing to connect because liquidsoap doesn't respond correctly, but was fixed See #160 and #641

**Comment by paddatrapper** [comment]
hmm... Could be. I'll tets with ices2

**Comment by Robbt** [comment]
Feel free to share your ices2 config here and I can help testing.

**Comment by paddatrapper** [comment]
About to give this a try:

```
<?xml version="1.1"?>
<ices>
  <background>0</background>
  <consolelog>1</consolelog>
  <pidfile>ices.pid</pidfile>
  <stream>
    <metadata>
      <name>Test Master</name>
      <genre>None</genre>
    </metadata>
    <input>
      <module>playlist</module>
      <param name="type">basic</param>
      <param name="file">playlist.txt</param>
      <param name="random">0</param>
      <param name="once">0</param>
      <param name="restart-after-reread">1</param>
    </input>
    <instance>
      <hostname>localhost</hostname>
      <port>8001</port>
      <password>master</password>
      <mount>/master</mount>
    </instance>
  </stream>
</ices>
```

**Comment by paddatrapper** [comment]
Debian Stretch on git HEAD:
```
EROR input/input_calculate_ogg_sleep Timing control: can't determine sample rate for input, not vorbis.
EROR stream/ices_instance_stream Failed initial connect to localhost:8002 (Login failed: Invalid argument)
```

Not sure what is causing the first error though...

**Comment by paddatrapper** [comment]
Same errors on Debian Buster with git HEAD

**Comment by paddatrapper** [comment]
Tried with Mixxx, but it  wouldn't connect at all

**Comment by paddatrapper** [comment]
Webcaster - https://webcast.github.io/webcaster/ can also be used to test streaming.

**Comment by paddatrapper** [comment]
And testing HEAD with that correctly plays out both show and master mounts. So it seems that we only support a subset of Icecast streaming clients

**Comment by Robbt** [comment]
It would be great if we could fix this incompatibility or at least document it and determine why it is happening.

**Comment by paddatrapper** [comment]
Opened #955 to track it
