### ISSUE TITLE
The 'zipp>=0.5' distribution was not found and is required by importlib-metadata

### ISSUE THREAD

**Issue by triangle-stream** [LibreTime/libretime#952]
**Describe the bug**
I'm facing this issue on several machines/OS like Ubuntu 16.04, Ubuntu 18.04, CentOS 7, Raspbian (latest).
The problem seems to occur also on new installed OS. This come by executing ./install (as root or sudo) after the Icecast configuration step.

The exact line is: 
```
Moving zipp-0.0.0-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Adding zipp 0.0.0 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/zipp-0.0.0-py2.7.egg
error: The 'zipp>=0.5' distribution was not found and is required by importlib-metadata
```
Am i missing something?

**To Reproduce**
Just run ./install (as root) on any of mentioned OS.

**LibreTime version:**
Latest (from git clone).

**Installation method:**
 - OS: Ubuntu
 - OS Version 16.04.5 LTS
 - `./install`

**Additional context**
There's also one strange line in the icecast configuration:
`./install: line 909: [: !-f: unary operator expected`

**Comment by paddatrapper** [comment]
Fixed in #954 
The strange line in install will be fixed in #953
