### ISSUE TITLE
LibreTime Mounts are only compatible with legacy icecast streaming clients

### ISSUE THREAD

**Issue by paddatrapper** [LibreTime/libretime#955]
Only some streaming clients work when streaming to master/show mounts. See #945 for details. https://webcast.github.io/webcaster/ works, while FFmpeg does not.

The cause needs investigating. It could be that Liquidsoap only supports a subset of clients. Shortcomings should be fixed or documented as known issues.

**Comment by maxlinux2000** [comment]
Hi, I can confirm that I can reproduce this bug on debian buster (raspbian buster on raspberrypi4)
Liquidsoap, work just fine using the android app BroadcastyMyself, and sometime works with the app CoolMic too.

...but I need ffmpeg in order to stream event without my presence, only ssh connection.

Obliviously I can connect with both Apps and ffmpeg directly to icecast

**Comment by paddatrapper** [comment]
I think the first step would be to create a basic source in liquidsoap and see if clients can connect to that. If they can, then our implementation is the issue, otherwise it is a liquidsoap issue

**Comment by maxlinux2000** [comment]
I Installed libretime in a ubuntu 18.04 and there is same problem.
looking about liquidsoap, I can see that is very old

root@r1:~# apt-cache show liquidsoap
Package: liquidsoap
Architecture: amd64
Version: 1.1.1-7.2ubuntu1

but the last version is the 1.4.1
https://www.liquidsoap.info/doc-1.4.1/

today I will to update this package with the last version and I will
try again to connect with ffmpeg.

**Comment by paddatrapper** [comment]
It has been updated to 1.3.7 in 19.10 and hopefully 1.4.1 in 20.04 when it eventually passes through proposed. My testing was against Liquidsoap 1.3.3 in Debian Buster

**Comment by maxlinux2000** [comment]
OK!! Solved!!

Try this to your libretime installation

arecord -f dat -D plughw:CARD=HD3000,DEV=0 |\
ffmpeg -i - \
-acodec libmp3lame \
-ab 128k \
-ac 1 \
-content_type audio/mpeg -f mp3 \
-legacy_icecast 1 \
icecast://source:PASSWD@YourDomain.org:8001/master

Note the Protocol flag: "icecast 1"

Liquidsoap is working but accept only icecast connection using the old protocol
so, in ffmpeg is easy to add this flag: "-legacy_icecast 1"

regards
MaX

**Comment by paddatrapper** [comment]
Ah that makes sense and is hopefully fixable!

**Comment by paddatrapper** [comment]
This is an issue that Liquidsoap upstream needs to fix - https://github.com/savonet/liquidsoap/issues/1078

**Comment by paddatrapper** [comment]
Fixed in `ocaml-cry` version 0.6.5, which will be uploaded to Debian soon. So future releases of Ubuntu and Debian should support newer sources without needing us to change anything. A solution for older distros is to install ocaml-cry through opam or build it from source

**Comment by Robbt** [comment]
If anyone ends up fixing this through opam it would be a good idea to write up docs for other people on how to use opam to solve problems like this.
