### ISSUE TITLE
Issue with import

### ISSUE THREAD

**Issue by hajjam-admin** [LibreTime/libretime#956]
I Can't import new files on the library 
Fresh install yesterday from the git on a debian 9 over dedicated server
Libretime version 52dd3f8ff
Webserver lunched over the 8888 port
All services are green on status

Error :   `Can not connect to the streaming server Problem with Liquidsoap...` on the stream window
```

**root@server:/var/log/airtime# sudo service airtime-liquidsoap status**
● airtime-liquidsoap.service - Airtime Liquidsoap Service
   Loaded: loaded (/etc/systemd/system/airtime-liquidsoap.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2020-01-24 08:30:01 UTC; 1s ago
 Main PID: 8074 (airtime-liquids)
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/airtime-liquidsoap.service
           └─8074 /usr/bin/python /usr/bin/airtime-liquidsoap

ينا 24 08:30:01 server systemd[1]: Started Airtime Liquidsoap Service.
```

```
**tail -f zendphp.log** 
2020-01-24T08:15:35+00:00 INFO (6): kimsufi.server.net Moving file /tmp/phpSJSeWY to /srv/airtime/stor/organize/001.mp3
2020-01-24T08:16:01+00:00 WARN (4): kimsufi.server.net SQLSTATE[55P03]: Lock not available: 7 ERREUR:  n'a pas pu obtenir un verrou sur la relation « cc_pref »
```

**Comment by Robbt** [comment]
Debian 9 aka Stretch has issues with mp3 files. It is recommended that you use Debian 10 aka Buster see #340 - @paddatrapper might be able to give better advice at this point.

**Comment by hajjam-admin** [comment]
I got the Libretime working on debian 9 in the 1c2906f5a version, maybe one monthe ago... over a kvm vps on debian9... it was because the libfdkaac-ocaml-dynlink library for the aac (on ubuntu 16.04 it didn't wrok for me)... some major changes last month cause the import issue with debian 9. i will try a new fresh install with debian 10 and check . thank you

**Comment by paddatrapper** [comment]
Try run `sudo journalctl -fue airtime-playout`, access the stream page and see what the result in the log is. It may take up to 30 seconds to show an error

**Comment by hajjam-admin** [comment]
```
root@server:~# sudo journalctl -fue airtime-playout
Failed to add match 'airtime-playout': Argument invalide
```

**Comment by paddatrapper** [comment]
Hmm... I don't know why liquidsoap is refusing the connection...

**Comment by Robbt** [comment]
You could try manually running airtime-liquidsoap and seeing what happens, I suspect it is dying for one reason or another and thus this is why airtime-playout can't connect
try ```sudo -u www-data airtime-liquidsoap```

Then you can restart airtime-playout from another terminal window and you should see any logged messages by airtime-liquidsoap including if it crashes, you could also just check the logs under /var/log/airtime/pypo-liquidsoap (not 100% sure this is the right directory it might be under /var/log/airtime/pypo as a subdirectory)

**Comment by hajjam-admin** [comment]
```
root@server:~# sudo -u www-data airtime-liquidsoap
Airtime Liquidsoap
At /usr/local/lib/python2.7/dist-packages/airtime_playout-1.0-py2.7.egg/liquidsoap/ls_lib_legacy.liq, line 168, char 39:
  the variable output.shoutcast used here has not been previously defined.
```

i will try a fresh install with the old version to be sure that it not comming from the server, repository or something like this.

**Comment by hajjam-admin** [comment]
Still got the same problem after installing with the old verison i don't understand why liquidsoap is refusing connection.

**Comment by paddatrapper** [comment]
It is refusing to connect because of this:
> At /usr/local/lib/python2.7/dist-packages/airtime_playout-1.0-py2.7.egg/liquidsoap/ls_lib_legacy.liq, line 168, char 39:
  the variable output.shoutcast used here has not been previously defined.
but I don't know why it is encountering that error

**Comment by hajjam-admin** [comment]
i don't have any ls_lib_legacy.liq file on that folder.
```
root@server:/home/hajjam# ls /usr/local/lib/python2.7/dist-packages/airtime_playout-1.0-py2.7.egg/liquidsoap/*.liq
/usr/local/lib/python2.7/dist-packages/airtime_playout-1.0-py2.7.egg/liquidsoap/fdkaac.liq
/usr/local/lib/python2.7/dist-packages/airtime_playout-1.0-py2.7.egg/liquidsoap/ls_lib.liq
/usr/local/lib/python2.7/dist-packages/airtime_playout-1.0-py2.7.egg/liquidsoap/ls_script.liq
/usr/local/lib/python2.7/dist-packages/airtime_playout-1.0-py2.7.egg/liquidsoap/mp3.liq
/usr/local/lib/python2.7/dist-packages/airtime_playout-1.0-py2.7.egg/liquidsoap/ogg.liq
/usr/local/lib/python2.7/dist-packages/airtime_playout-1.0-py2.7.egg/liquidsoap/opus.liq
```

**Comment by paddatrapper** [comment]
The move from `ls_lib.liq` to `ls_lib_legacy.liq` for liquidsoap <= 1.1.1 happened in #931. Have you installed the libraries required to use liquidsoap with Shoutcast?

**Comment by hajjam-admin** [comment]
it's the default install with icecast i don't use until now shoutcast. 
```
root@server:/home/hajjam# liquidsoap --version
Liquidsoap 1.1.1
Copyright (c) 2003-2013 Savonet team
Liquidsoap is open-source software, released under GNU General Public License.
See <http://liquidsoap.fm> for more information.


```

**Comment by hajjam-admin** [comment]
It worked after a dist upgrade to debian 10.

**Comment by Robbt** [comment]
So it looks like this is working with Debian 10 and/or the specific issues aren't clear any more so I'm going to close this for now to try to tidy up the issue queue. If you are still having an issue feel free to request support. Thanks.
