### ISSUE TITLE
Error while installing Libretime on Ubuntu 16.04.3

### ISSUE THREAD

**Issue by panbak** [LibreTime/libretime#961]
While installing Libretime on Ubuntu 16.04, I get the error in the image.
![image_2020_02_21T23_40_15_170Z](https://user-images.githubusercontent.com/16959986/75080340-675bd580-5514-11ea-8515-ec3ed5aaf2f7.png)

-I just follow the installling instructions.

**Installation method:**
 - OS: Ubuntu
 - OS Version: 16.04.3 
 - Method: sudo ./install
 - Details: I just cloned the master branch of Libretime

**Comment by gnoukos** [comment]
Juste remove line 928 from install file

`loudCmd "pip install zipp==1.0.0"`

**Comment by panbak** [comment]
Thanks! It worked.
