### ISSUE TITLE
Stream Configuration should use provided hostname value from install

### ISSUE THREAD

**Issue by kmahelona** [libretime/libretime#966]
**Describe the bug**
I've noticed this issue before even with Airtime 2.5.1. Things seem finicky. With a clean install, the local `icecast2` stream works fine. Once I enable another stream with, say, `aac` codec, then all of a sudden the local `icecast2` stream breaks. If I change my settings back to the original, it still fails. `liquidsoap` logs don't have anything useful except that it disconnects, and `icecast2` says timeout (because of the disconnect).

**Logs**
On restarting `airtime-liquidsoap` it appears to connect then it disconnects,

/var/log/airtime/pypo-liquidsoap/ls_script.log 
```
2020/03/02 20:14:01 [LibreTime!:3] Connecting mount _a for source@tehiku.radio...
2020/03/02 20:14:01 [LibreTime!:3] Connection setup was successful.
2020/03/02 20:14:01 [lang:3] timeout --signal=KILL 45 pyponotify --connect --stream-id=1 --time=1583132723.99 &
2020/03/02 20:14:01 [server:3] New client: 127.0.0.1.
2020/03/02 20:14:01 [server:3] Client 127.0.0.1 disconnected without saying goodbye..!
2020/03/02 20:14:01 [server:3] Client 127.0.0.1 disconnected without saying goodbye..!
2020/03/02 20:14:01 [server:3] New client: 127.0.0.1.
2020/03/02 20:14:01 [server:3] New client: 127.0.0.1.
2020/03/02 20:14:01 [server:3] Client 127.0.0.1 disconnected without saying goodbye..!
2020/03/02 20:14:01 [server:3] Client 127.0.0.1 disconnected without saying goodbye..!
2020/03/02 20:14:01 [server:3] New client: 127.0.0.1.
2020/03/02 20:14:02 [server:3] Client 127.0.0.1 disconnected without saying goodbye..!
2020/03/02 20:14:02 [server:3] New client: 127.0.0.1.
2020/03/02 20:14:02 [server:3] New client: 127.0.0.1.
```

/var/log/icecast2/error.log 
```
[2020-03-02  20:14:01] INFO connection/_handle_source_request Source logging in at mountpoint "/_a" from 172.31.40.79
[2020-03-02  20:14:01] INFO source/source_main listener count on /_a now 0
[2020-03-02  20:14:12] WARN source/get_next_buffer Disconnecting source due to socket timeout
[2020-03-02  20:14:12] INFO source/source_shutdown Source from 172.31.40.79 at "/_a" exiting
[2020-03-02  20:14:48] INFO connection/_handle_source_request Source logging in at mountpoint "/_a" from 172.31.5.166
[2020-03-02  20:14:48] INFO source/source_main listener count on /_a now 0
[2020-03-02  20:14:59] WARN source/get_next_buffer Disconnecting source due to socket timeout
[2020-03-02  20:14:59] INFO source/source_shutdown Source from 172.31.5.166 at "/_a" exiting
[2020-03-02  20:15:35] INFO connection/_handle_source_request Source logging in at mountpoint "/_a" from 172.31.40.79
[2020-03-02  20:15:35] INFO source/source_main listener count on /_a now 0
[2020-03-02  20:15:46] WARN source/get_next_buffer Disconnecting source due to socket timeout
[2020-03-02  20:15:46] INFO source/source_shutdown Source from 172.31.40.79 at "/_a" exiting
```

**To Reproduce**
1. Clean install of LibreTime
2. Load up some shows, playlists, and music (get stuff playing)
3. Open the icecast2 website, e.g. 127.0.0.1:8000
4. Play the stream (it works!)
5. Go back to stream settings e.g. http://127.0.0.1/preference/stream-setting
6. Add another stream with another codec (I did aac) or edit stream with to use codec aac
7. Liquidsoap can't seem to connect to icecast.

**Expected behavior**
We expect that simple enabling/disabling multiple streams and changing the codecs that are displayed in the drop downs should work.

**LibreTime version:**
https://github.com/TeHikuMedia/libretime/tree/python3_libretime_watch_rebased_ubuntu_eoan
I've got a lot going on there - basically it's a merge of the python3 PR, the watch PR with my own updates, and a new branch (I intend on making a PR) for Ubuntu 19.10

**Installation method:**
 - OS: Ubuntu 19.10
 - Method: `./install`
 - Details: I've got this all deployed in AWS via ansible.

**Comment by kmahelona** [comment]
I can resolve this problem by completely deleting the database. So I suspect the error is somewhere with changing stream settings that are then written to the database and then maybe interpreted into the `liquidsoap.cfg`?

**Comment by kmahelona** [comment]
Ok, figured it out. So there's a little bit of inconsistency around what you set your host address to be. By default LibreTime uses `127.0.0.1` as the icecast2 server url. However in my case I have `tehiku.radio` as my host name from the `/config?` step. So when I use the website to change the stream settings, it puts in `tehiku.radio` as expected.

So the problem is, by virtual of AWS load balancers, my server would have to send the connection outside at `tehiku.radio:8000` and back into itself. My solution here is to change the steam to `Custom / 3rd Party Streaming` and then modify the server IP address. Or... fix up my security groups and listeners to work...

Having said all that, I think this bug is valid (maybe it needs a name change) as we should update that initial stream config to use the host provided form the config setup and not `127.0.0.1`. This would also resolve the issue where if you were doing a remote setup and clicked the "listen" button, you'd get a player trying to play a stream from `127.0.0.1`.

**Comment by jooola** [comment]
@kmahelona Does this issue still occur with the latest version of LibreTime ?
