### ISSUE TITLE
webstreams not playing

### ISSUE THREAD

**Issue by kmahelona** [LibreTime/libretime#969]
**Describe the bug**
Webstreams don't play. Liquidsoap still runs and so does airtime-playout, but the sound of silence.

**To Reproduce**
1. Create a webstream in the UI
2. Schedule webstream
3. Play the LibreTime stream to confirm/deny the silence.

**Expected behavior**
We should expect the webstream to work. The UI is accepting the link I put in, `http://radio.tehiku.live:8040/stream`

**LibreTime version:**
master + python3 + watch_folder

**Installation method:**
 - OS: Ubuntu
 - OS Version 19.10
- liquidsoap 1.3.7
 - ./install

**Error Log**
`/var/log/airtime/pypo-liquidsoap/ls_script.log`
```
2020/03/06 08:30:10 [server:3] New client: 127.0.0.1.
2020/03/06 08:30:10 [lang:3] dynamic_source.id
2020/03/06 08:30:10 [lang:3] ["Invalid URL"]
2020/03/06 08:30:10 [lang:3] ["Done"]
2020/03/06 08:30:10 [server:3] Client 127.0.0.1 disconnected.
```

**Additional context**
One other person mentioned this as an important feature in discourse https://discourse.libretime.org/t/stream-connected-but-not-playing/379/3. Curious if anyone else has come accross this problem or has tried this.

I can confirm that liquidsoap 1.3.7 can indeed play the webstream above by running a liq script.

**Comment by Tucker2015** [comment]
Are you trying to play the stream in Google Chrome ? If so your shoutcast stream needs to be HTTPS now as Chrome will not accept HTTP.

**Comment by kmahelona** [comment]
No this is for scheduled web streams in LibreTime. You can play other shoutcast and icecast streams in your own broadcast, so chrome doesn’t affect this. I did however notice that chrome broke our shoutcast streams (I didn’t get the memo) and have since fixed that.

**Comment by paddatrapper** [comment]
Python 3 related issue. Doesn't affect current master and fixed in #951

**Comment by kaya-karaca** [comment]
Still happening here with version: 16bff4ff9

**Comment by paddatrapper** [comment]
@kaya-karaca what distro are you using and what stream are you trying to play?

**Comment by kaya-karaca** [comment]
Ubtuntu 18 and i try to play an Airtime Pro stream.

**Comment by paddatrapper** [comment]
Liqudsoap < 1.3.7-1 is not built with SSL support, so if your stream starts with 'https' it will not play. The error doesn't seem to be displayed to the user at all either. If you re-build Liquidsoap or install from OPAM, it should work

**Comment by paddatrapper** [comment]
I've opened #1068 to improve error reporting

**Comment by kaya-karaca** [comment]
> 
> 
> Liqudsoap < 1.3.7-1 is not built with SSL support, so if your stream starts with 'https' it will not play. The error doesn't seem to be displayed to the user at all either. If you re-build Liquidsoap or install from OPAM, it should work

Alright, but is there any other workaround? I have the fear that upgrading Liquidsoap will bring many other possible bugs and errors. Or is this not true?

**Comment by paddatrapper** [comment]
> Alright, but is there any other workaround?

You've got two options:

1. Rebuild the version of liquidsoap you have, including SSL support
2. Installing from OPAM

I haven't heard of any issues using Liquidsoap >= 1.3.7, but that doesn't mean that there aren't any. You will need to test and ensure that it works for your purpose

**Comment by Robbt** [comment]
Yeah I'd recommend doing it on a test system and posting the steps here if you are successful so others can benefit. It could cause issues if you tried to do it on your production system and somehow broke your liquidsoap install but it is probable that 1.3.7 will work if installed correctly.
