### ISSUE TITLE
Playback interrupted when removing currently playing item and stream type is opus

### ISSUE THREAD

**Issue by kmahelona** [LibreTime/libretime#975]
**Describe the bug**
I've been testing playback of webstreams, and to quickly do that I'm doing a lot of hard cuts. This means I select the currently playing item and hit REMOVE. I've noticed that when I'm streaming from LibreTime using the opus codec and I REMOVE the currently playing item, then playback stops (I'm playing in browser on the icecast landing page). Simply refreshing the browser and hitting play causes the stream to start playing. I don't have this problem while streaming from ogg vorbis or MP3. I know this is a strange edge case, but I'd advise against using opus until this problem is fixed.

**To Reproduce**
1. Set your Stream Type to opus in '/preference/stream-setting'
2. Open your stream in a browser and start listening to it
3. Go to '/showbuilder' and select the currently playing track
4. Remove the currently playing track making sure there is an item that will play after it
5. You playback should be interrupted.

**Expected behavior**
We should expect no interruption in the playback of the stream when we make "hard cuts" (e.g. removing currently playing items).

**LibreTime version:**
master + python3 + libretime_watch_rebased

**Installation method:**
 - OS: Debbian
 - OS Version 10 (Buster)
 - Method: `./install`

**Browser**
- Chrome, Mac OS X, playing directly from the icecast page which means it's the browsers player as opposed to a third part player (e.g. jplayer).

**Comment by Robbt** [comment]
Hmm, we need to verify that this isn't a problem introduced via python3 and we need to look at the liquidsoap logs etc.

**Comment by Robbt** [comment]
I suspect this a liquidsoap issue based upon the fact that it only happens with a specific codec. Now just need to generate some opus files and test it. Testing a variety of files would be a good thing for #1022 and #1021
