### ISSUE TITLE
Ensure icecast2 service starts on reboot

### ISSUE THREAD

**Issue by kmahelona** [LibreTime/libretime#977]
**Is your feature request related to a problem? Please describe.**
I know this is about a third party package but a key component in LibreTime is the icecast2 server that runs on the local machine. I've noticed that upon rebooting my machines (Debian) the icecast2 service doesn't start and I need to manually do `service icecast2 start`

**Describe the solution you'd like**
I'm not sure *how* to fix this but I supposed making sure the LibreTime install script does what it has to to make the icecast2 service run at boot because it doesn't appear that the package does this itself.

**Comment by paddatrapper** [comment]
`systemctl enable icecast2`

**Comment by kmahelona** [comment]
Is it ok to do that in the install script so users don't have to do it as an additional step?

**Comment by paddatrapper** [comment]
I don't see why not

**Comment by zklosko** [comment]
@kmahelona Is this still an issue? Looking to close old issues.

**Comment by jooola** [comment]
Yes, the installer does enable icecast by default.
