### ISSUE TITLE
iframe tag attribute has no double quotes

### ISSUE THREAD

**Issue by gagzzz** [LibreTime/libretime#988]
**Describe the bug**
It's a tiny bug, on the public page of libretime, the player seems to be loaded in an iframe, but the src attribute doesn't use double quotes as it should.

**To Reproduce**
1. install a fresh libretime
2. fetch its frontpage
3. look at its source

**Expected behavior**
src=url should be src="url"

**LibreTime version:**
3 alpha 8

**Installation method:**
 - OS: ubuntu
 - OS Version 18.04
 - Method: `./install` script
 - Details: [how did you call the install script, where did you get packages from]

**Screenshots**

**Comment by valerio-bozzolan** [comment]
(GitHub ghosts? Apologies for such rows.)

Here to say that with [Border Radio](https://border-radio.it/) we had enough time to fix this issue with a pull request. Let's see when it will be merged. Happy hacking!

https://github.com/LibreTime/libretime/pull/1119
