### ISSUE TITLE
Feature Request: Rescan media files + update database if needed

### ISSUE THREAD

**Issue by HaJoHe** [LibreTime/libretime#99]
Libretime 'lost' during migration a handy function of airtime, the possibility to upload files in a directory with a automatic datahandling (adding it into database or just updating the database for this file)

**Comment by hairmare** [comment]
I think this is the watched folders feature tracked in #70. The UI is fairly easy to implement but the actual watching needs to be moved from legacy media-monitor to analyzer or a new python component.

**Comment by Robbt** [comment]
Merging this into #70
